### ISSUE TITLE
Aqara Door Sensor stay off

### ISSUE THREAD

**Issue by sbou88** [AlexxIT/XiaomiGateway3#1]
Hello, 
All in title. 

![image](https://user-images.githubusercontent.com/51677845/91668174-e7d64100-eb0a-11ea-9abf-3bc94f5732f7.png)
![image](https://user-images.githubusercontent.com/51677845/91668178-fe7c9800-eb0a-11ea-9e26-1f3192b5b644.png)

**Comment by AlexxIT** [comment]
Is it fixed in the latest release?

**Comment by sbou88** [comment]
Yes it's done. thx
