### ISSUE TITLE
Ikea Bulb show brightness as real number

### ISSUE THREAD

**Issue by lonebaggie** [AlexxIT/XiaomiGateway3#100]
Using IKEA Bulb E14 400 when setting brightness , returning value as real number not integer. So when I set brightness via HA at 50% bulb returns  brightness value as 127.5  If I set brightness at 1% it returns  2.5500000000000003

Running version 0.10.1

**Comment by AlexxIT** [comment]
It's make a bug or you don't like big numbers?

**Comment by lonebaggie** [comment]
If I change brightness via Mi Home or dimmer, brightness get returned as a real number (165.65) rather than an whole number  that HA normally uses  . No real issue but it makes all my dials, and front end break as it is showing numbers with decimal points

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
