### ISSUE TITLE
Add Dessmann Q3 lock (dsm.lock.q3)

### ISSUE THREAD

**Issue by whowho182** [AlexxIT/XiaomiGateway3#1001]
Can you support the Bluetooth version of smart lock dessmann q3? At present, only the power parameter can be displayed. There is also a small problem that the water immersion sensor of Mijia is not available.
![微信图片_20230309120627](https://user-images.githubusercontent.com/49549058/223914221-ca3b6fe9-5aab-4cdb-b871-d55754ff022d.png)
![微信图片_20230309115137](https://user-images.githubusercontent.com/49549058/223914231-24b36f4c-95a6-46b4-adb7-54f070b6fead.png)
[xiaomi_gateway3-4dff3b5bf87d917c4824ab54b1e2507b-Mi Flood Detector-f4b41fb7dd4e50dbab3e55e93aaae217.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10927570/xiaomi_gateway3-4dff3b5bf87d917c4824ab54b1e2507b-Mi.Flood.Detector-f4b41fb7dd4e50dbab3e55e93aaae217.json.txt)
[xiaomi_gateway3-4dff3b5bf87d917c4824ab54b1e2507b-门锁-b8899eeb8714d2719eee6d24cd45d78f.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10927571/xiaomi_gateway3-4dff3b5bf87d917c4824ab54b1e2507b-.-b8899eeb8714d2719eee6d24cd45d78f.json.txt)

**Comment by AlexxIT** [comment]
Looks like your lock already supported. You has action and battery sensors

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
