### ISSUE TITLE
Fix Gateway become unavailable for ZHA/Z2M modes

### ISSUE THREAD

**Issue by Largelos** [AlexxIT/XiaomiGateway3#1005]
I have two lumi.gateway.mgl03 gateways with custom firmware 1.5.4
FIRMWARE........: 1.5.4_0090 #20220509
Both devices become unavailable sometimes, ZHA/Z2M also not working, but telnet available and port 8888 is open.
Reboot gateway help to solve problem shortly, but sooner or later connection lost again. 
Debug info and some CLI output attached, with "netstat -anp | grep "8888"", /var/log/messages, /var/log/miio_client.log, var/log/openmiio.log content and "ps".
Is there any other info exist I can provide to help debug this issue? 

[cli_history.txt](https://github.com/AlexxIT/XiaomiGateway3/files/11006944/cli_history.txt)

[config_entry-xiaomi_gateway3-c50d57db82fc35693dabcfa88451dfa4.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/11006952/config_entry-xiaomi_gateway3-c50d57db82fc35693dabcfa88451dfa4.json.txt)
[home-assistant_2023-03-17T22-56-54.751Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/11006953/home-assistant_2023-03-17T22-56-54.751Z.log)

**Comment by AlexxIT** [comment]
I hope this will be fixed in next release. You can try latest master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0

**Comment by Largelos** [comment]
It's not network issue and device is not offline in fact, and telnet
opening fine at same time, but integration able to connect to gateway only
after gateway reboot
