### ISSUE TITLE
Cannot connect to the gateway

### ISSUE THREAD

**Issue by aLAN-LDZ** [AlexxIT/XiaomiGateway3#1006]
Hi
I have a xiaomi v2 gateway with software: 1.0.5_0016
Attempting to add an integration ends with the error "Unable to connect to gateway"

I tried to connect both to wifi and lan, unfortunately it didn't change anything. I can see the token without any problem

**Comment by AlexxIT** [comment]
Double check gateway IP address. Check you using same LAN segment without any restrictions about local connections.

"Unable to connect to gateway" means what it means. Hass can't connect to your gateway.
