### ISSUE TITLE
Fix resource leak on Multimode Gateway (after fail Z3 utility)

### ISSUE THREAD

**Issue by Wh1terat** [AlexxIT/XiaomiGateway3#1010]
Every ~2 hours I'm seeing my BLE mesh lights disconnect in home assistant; I thought I had solved it but turned out to be a red herring. (I don't use the mgl03 for zigbee).

However I do believe I have found the cause now.

```23:36:27.594 PNC github.com/AlexxIT/openmiio_agent/internal/zigbee/zigbee.go:91 > error="fork/exec /bin/Lumi_Z3GatewayHost_MQTT: resource temporarily unavailable"```

This is a fatal error and openmiio exits; restarting it restores the service.

Resource temporarily unavailable when trying to fork would lead you to believe it's hitting user limits. 
That said, I can't see how it could be hitting these limits (unless openmiio is essentially fork bombing?)

Thoughts?

```
# ulimit -a
-f: file size (blocks)             unlimited
-t: cpu time (seconds)             unlimited
-d: data seg size (kb)             unlimited
-s: stack size (kb)                8192
-c: core file size (blocks)        0
-m: resident set size (kb)         unlimited
-l: locked memory (kb)             64
-p: processes                      227
-n: file descriptors               1024
-v: address space (kb)             unlimited
-w: locks                          unlimited
-e: scheduling priority            0
-r: real-time priority             0```

# cat /proc/sys/kernel/threads-max
454
```

Additionally, openmiio redirects (not appends) to the log:
https://github.com/AlexxIT/XiaomiGateway3/blob/65308cbbddeebba28a9ce41ed797bcdd16cced1c/custom_components/xiaomi_gateway3/core/shell/base.py#L13

Double >> would be preferable for logging:

```python
RUN_OPENMIIO = "/data/openmiio_agent miio mqtt cache z3 --zigbee.tcp=8888 >> /var/log/openmiio.log 2>&1 &"
```

**Comment by Wh1terat** [comment]
Looks like it probably is thread count. 
This is just over about 10 minutes:

```
# ps wlT | grep Lumi_Z3GatewayH | wc -l
78
# ps wlT | grep Lumi_Z3GatewayH | wc -l
79
# ps wlT | grep Lumi_Z3GatewayH | wc -l
79
# ps wlT | grep Lumi_Z3GatewayH | wc -l
79
# ps wlT | grep Lumi_Z3GatewayH | wc -l
84
# ps wlT | grep Lumi_Z3GatewayH | wc -l
85
```

That's crazy.  I'm guessing it will continual to spawn new threads until either threads-max is exceeded or stack size is.

Something is definitely broken here.

**Comment by Wh1terat** [comment]
@AlexxIT 
It's https://github.com/AlexxIT/openmiio_agent/commit/f436d4cf3d62e797a890d62a55adadeb88fdfd52

1.0.0 isn't leaving the zombies

**Comment by AlexxIT** [comment]
Thanks! Very helpful

**Comment by AlexxIT** [comment]
Interesting, why your Z3Gateway fail all the time

**Comment by Wh1terat** [comment]
Glad to assist 😄 

Could be because I'm not using the gateway for Zigbee; just for a few legacy BLE devices.

**Comment by AlexxIT** [comment]
This is because your zigbee chip has custom firmware. Z3 app fail to start.
I have fixed leftover. It will be in next version.
But I recommend you to flash original zigbee firmware via gateway dropdown menu.

**Comment by Wh1terat** [comment]
It's not running custom firmware; as part of my troubleshooting I even restored it to stock (including reflashing ble and zigbee firmwares).

For now I've just taken z3 and port args out of RUN_OPENMIIO.

**Comment by AlexxIT** [comment]
Well. Doublecheck. I don't know any other reason why Z3 may constantly fail.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
