### ISSUE TITLE
No support for Xiaomi scales and Mi Band?

### ISSUE THREAD

**Issue by Hipokys** [AlexxIT/XiaomiGateway3#1011]
Hello!
No support for Xiaomi scales and Mi Band?
On older versions, experimentally, you added this.
It worked the same in the https://github.com/AlexxIT/gw3.

**Comment by AlexxIT** [comment]
You right. It was supported earlier with gw3 app. But this requires a huge effort and support for each of the Multimode Gateway 1 firmware.
Today's version of [openmiio_agent](https://github.com/AlexxIT/openmiio_agent) works on all firmware versions of three gateway models at once. But it does not have as cool BLE support as gw3 had.
I guess with all my [projects](https://github.com/AlexxIT), I just don't have time to follow the way of gw3
