### ISSUE TITLE
Gateway 3 + TH sesor + MQTT

### ISSUE THREAD

**Issue by antarctis-hvac** [AlexxIT/XiaomiGateway3#102]
topic zigbee/recv from public MQTT on Gateway 3 with TH sensor contains:

{"cmd":"read","did":"lumi.158d000462fbcc","id":307,"params":[{"res_name":"8.0.2001"}],"source":"","time":1604984871931} 

Where temperature and humudity values?

Home Assiatanrt show it correctly.

**Comment by AlexxIT** [comment]
In other params https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/core/utils.py
