### ISSUE TITLE
Add support Yeelight C1

### ISSUE THREAD

**Issue by leeteke** [AlexxIT/XiaomiGateway3#1025]
**BLE MESH Device**
_Name：Yeelight Smart Color Temperature Downlight C1 Light
Type: YCCBC1019/YCCBC1020

The device is now recognized as an unknown MESH(11667) device and can only be controlled on and off, unable to control color temperature and brightness.

Can we increase support for this device to control it like Yeelight M2 ？

Thanks~

**Comment by yaochengbo124** [comment]
Your problem can be achieved using a converter function, implementing a custom one.

**Comment by yaochengbo124** [comment]
https://github.com/AlexxIT/XiaomiGateway3/wiki/Converters

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
