### ISSUE TITLE
Fix Aqara Cube support on Hass 2023.4

### ISSUE THREAD

**Issue by hsguyue** [AlexxIT/XiaomiGateway3#1026]
Upgraded to HA Core 2023.4, unable to control Aqara Cube and sensor status action, but there is no control and no logs.

**Comment by AlexxIT** [comment]
Known problem. Broken in Hass 2023.4

**Comment by yaochengbo124** [comment]
me too

**Comment by yaochengbo124** [comment]
HASS core project team replied: This is a custom component, which is not maintained by the HA core project. Please report your issue to the maintainer or in the source repository of this custom component.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
