### ISSUE TITLE
switch.toggle broken in version v0.10 / v0.10.1

### ISSUE THREAD

**Issue by Rupunx** [AlexxIT/XiaomiGateway3#103]
Вызов службы switch.toggle выполняет только включение устройства (из интеграции со шлюзом).
Выключение устройства не происходит. Ошибок никаких не выводится

Поломалось в версиях  v0.10 / v0.10.1
Откатился на v0.9 - всё работает.

**Comment by AlexxIT** [comment]
The master version has a fix. Can be installed via HACS. Will be in the next release

**Comment by dixanl** [comment]
тоже не работает

**Comment by Rupunx** [comment]
Да, не стал писать, проверил и на 10 и на 10.1 - не работает на обеих

**Comment by AlexxIT** [comment]
Fix only in master version

**Comment by AlexxIT** [comment]
I fixed problem in v0.10.2
