### ISSUE TITLE
Update stop support for the gateway alarm?

### ISSUE THREAD

**Issue by YanivKrit** [AlexxIT/XiaomiGateway3#1032]
Hello, 
I am using the alarm feature of the Xiaomi Gateway 3 (ZNDMWG03LM version 1.5.4_xxxx) and up until 2-3 days ago everything was fine, no I get the following error:
![image](https://user-images.githubusercontent.com/65375122/231210431-3a8254cb-1240-4fc8-af1a-50f918fe9fae.png)
![image](https://user-images.githubusercontent.com/65375122/231210149-b2364d22-6766-431a-b043-41c29cb52404.png)

Is it not supported any more?

**Comment by AlexxIT** [comment]
Your gateway doesn't work at all. You need to check errors in logs.

**Comment by YanivKrit** [comment]
THANK YOU for the super fast comment, for some reason I had to reconfigure the gateway and it worked, thank you very much!
