### ISSUE TITLE
Integration does not connect to my gateways

### ISSUE THREAD

**Issue by Vladimir-huligan** [AlexxIT/XiaomiGateway3#1033]
3 devices (2 gateway getways and a vacuum cleaner) were integrated from the Mihome into the Home Assistance. The vacuum cleaner is geographically located elsewhere. integration sees the gateways, sees their tokens, but does not connect to any of them.
![1](https://user-images.githubusercontent.com/73360995/231361643-ff241577-8b62-46de-a515-6300a1cff25f.png)

**Comment by dolonfly** [comment]
> the same issues in 3.2.0 gateway3 All entities no longer provide，but they work normally in version 3.1.0
> 
> Home Assistant 2023.4.3 gateway DMWG03LM firmware 1.0.6_0016
> 
> Okay, maybe it's my network problem
> 
> Logger: custom_components.xiaomi_gateway3.core.gateway Source: custom_components/xiaomi_gateway3/core/shell/base.py:172 Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues)) First occurred: 21:31:34 (4 occurrences) Last logged: 21:43:39
> 
> 192.168.0.3 | Can't prepare gateway Traceback (most recent call last): File "/config/custom_components/xiaomi_gateway3/core/gateway/**init**.py", line 205, in prepare_gateway return await self.mgw2_prepare_gateway(sh) File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw2.py", line 32, in mgw2_prepare_gateway msg = await sh.run_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 123, in run_openmiio_agent ok = await self.check_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/shell_arm.py", line 48, in check_openmiio_agent return await self.check_bin( File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 92, in check_bin raw = await download(url) File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 172, in download async with session.get(url_or_path) as resp: File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in **aenter** self._resp = await self._coro File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request await resp.start(conn) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start with self._timer: File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in **exit** raise asyncio.TimeoutError from None asyncio.exceptions.TimeoutError

same with me , and i  am  sure i have followed all of the steps in these instructions: may firmware 1.0.6_0016 not suitable？
https://github.com/AlexxIT/XiaomiGateway3#network-configuration

**Comment by flyibeat** [comment]
> > the same issues in 3.2.0 gateway3 All entities no longer provide，but they work normally in version 3.1.0
> > Home Assistant 2023.4.3 gateway DMWG03LM firmware 1.0.6_0016
> > Okay, maybe it's my network problem
> > Logger: custom_components.xiaomi_gateway3.core.gateway Source: custom_components/xiaomi_gateway3/core/shell/base.py:172 Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues)) First occurred: 21:31:34 (4 occurrences) Last logged: 21:43:39
> > 192.168.0.3 | Can't prepare gateway Traceback (most recent call last): File "/config/custom_components/xiaomi_gateway3/core/gateway/**init**.py", line 205, in prepare_gateway return await self.mgw2_prepare_gateway(sh) File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw2.py", line 32, in mgw2_prepare_gateway msg = await sh.run_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 123, in run_openmiio_agent ok = await self.check_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/shell_arm.py", line 48, in check_openmiio_agent return await self.check_bin( File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 92, in check_bin raw = await download(url) File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 172, in download async with session.get(url_or_path) as resp: File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in **aenter** self._resp = await self._coro File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request await resp.start(conn) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start with self._timer: File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in **exit** raise asyncio.TimeoutError from None asyncio.exceptions.TimeoutError
> 
> same with me , and i am sure i have followed all of the steps in these instructions: may firmware 1.0.6_0016 not suitable？ https://github.com/AlexxIT/XiaomiGateway3#network-configuration

For me, it is already working.
Maybe it takes time for the back-end to upgrade the openmiio firmware.

**Comment by dolonfly** [comment]
> > > the same issues in 3.2.0 gateway3 All entities no longer provide，but they work normally in version 3.1.0
> > > Home Assistant 2023.4.3 gateway DMWG03LM firmware 1.0.6_0016
> > > Okay, maybe it's my network problem
> > > Logger: custom_components.xiaomi_gateway3.core.gateway Source: custom_components/xiaomi_gateway3/core/shell/base.py:172 Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues)) First occurred: 21:31:34 (4 occurrences) Last logged: 21:43:39
> > > 192.168.0.3 | Can't prepare gateway Traceback (most recent call last): File "/config/custom_components/xiaomi_gateway3/core/gateway/**init**.py", line 205, in prepare_gateway return await self.mgw2_prepare_gateway(sh) File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw2.py", line 32, in mgw2_prepare_gateway msg = await sh.run_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 123, in run_openmiio_agent ok = await self.check_openmiio_agent() File "/config/custom_components/xiaomi_gateway3/core/shell/shell_arm.py", line 48, in check_openmiio_agent return await self.check_bin( File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 92, in check_bin raw = await download(url) File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 172, in download async with session.get(url_or_path) as resp: File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in **aenter** self._resp = await self._coro File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request await resp.start(conn) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start with self._timer: File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in **exit** raise asyncio.TimeoutError from None asyncio.exceptions.TimeoutError
> > 
> > 
> > same with me , and i am sure i have followed all of the steps in these instructions: may firmware 1.0.6_0016 not suitable？ https://github.com/AlexxIT/XiaomiGateway3#network-configuration
> 
> For me, it is already working. Maybe it takes time for the back-end to upgrade the openmiio firmware.

may this cause, i reinstall and got following log. it seems cant download openmiio_agent, is there any way to install and run it manual? 

2023-04-15 18:40:39 [D] 192.168.10.3 [BASE] openmiio_agent: ERROR: can't download latest version
2023-04-15 18:40:39 [D] 192.168.10.3 [BASE] 649e31507b67 (10441) setup mesh ES1ZB: occupancy, occupancy_duration, occupancy_distance, idle_time, occupancy_timeout, distance_00_08, distance_08_15, distance_15_23, distance_23_30, distance_30_38, distance_38_45, distance_45_53, distance_53_60, illuminance, action, approach_distance, led, mesh

**Comment by AlexxIT** [comment]
@flyibeat just temporary problems with connection from Hass server to GitHub (download openmiio app)

@dolonfly your problem should be fixed in v3.2.1

**Comment by dolonfly** [comment]
> @flyibeat just temporary problems with connection from Hass server to GitHub (download openmiio app)
> 
> @dolonfly your problem should be fixed in https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.1

version 3.2.1  works for me , it's working now, thanks very much.

**Comment by AlexxIT** [comment]
Closed without response
