### ISSUE TITLE
[feature request]XIAOMI HOME HUB support

### ISSUE THREAD

**Issue by leonunix** [AlexxIT/XiaomiGateway3#1036]
As everyone know. xiaomi is release a home hub at china. HW: ZSWG01CM. It like a gateway but not only gateway.
If use with gateway together. Some BLE device will connect to this hub. So we can not get status on gateway. Anyway  to get data on hub?
I have try to open telnet port. With the same method on gateway3. It see no such function. Is any one intersting with this HW? If you want to test, I can help.

HW info
Name: Xiaomi Home Hub
Model: xiaomi.gateway.hub1

**Comment by AlexxIT** [comment]
I'm not interested in this hub. No Zigbee, high price. Completely different software.
It may be interesting for MiHome users. But Multimode 2 (white) is more interesting for Hass.

There is no problem with BLE/Mesh devices after this release:
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
