### ISSUE TITLE
How to update home assistant entities and devices 

### ISSUE THREAD

**Issue by yapluka128** [AlexxIT/XiaomiGateway3#1040]
Hello,
I am using ZNDMWG02LM with Mi Home and Home Assistant 2023.4.2 and the v3.2.0 integration.
Everything is working fine. 
I added a new light group in Mi Home, but I can't find a way to update the Home Assistant integration to show this new group. What am I missing?

Thank you for your understanding.

**Comment by dixon777** [comment]
You may reload XiaomiGateway3 integration as follows:
![image](https://user-images.githubusercontent.com/19166775/233787125-065bde53-2b3b-4069-81de-2823ff6bdc99.png)
The light group device should pop up within a minute.

If this doesn't work, restart HA.

**Comment by yapluka128** [comment]
Hello,
thank you for your answer. Unfortunately, I have done many tests regarding your answer, and I can't seem to update the integration. Every time I click on reload or restart HA, it seems that there is no change. 

How do I do this?

**Comment by yapluka128** [comment]
It seems it is the same issue here : https://github.com/AlexxIT/XiaomiGateway3/issues/210#issuecomment-777604232

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/1016
