### ISSUE TITLE
What can and can't I do with Bluetooth?

### ISSUE THREAD

**Issue by RedFox-Fr** [AlexxIT/XiaomiGateway3#1041]
Hi,

I successfully integrated Xiaomi Gateway 3 (ZNDMWG03LM) with Home Assistant, updated firmware, ncp Zigbee and ncp Bluetooth.
ZHA works and my Zigbee devices are recognized and functional.

But what about my Bluetooth devices?

I have 4 Mijia thermometers (LYWSD03MMC) which were associated with the Xiaomi gateway. I updated the firmware of one of the thermometers with pvvx/ATC_MiThermometer. The thermometer works, but I can no longer recognize it from the gateway with "Xiaomi Home". It is seen from time to time in Home Assistant, but the sensor values do not appear.

What should I do to make this thermometer work with pvvx firmware in Home Assistant via Xiaomi gateway?

By the way, I have a Bluetti EB3A power station with Bluetooth connectivity. Is it possible for Home Assistant to communicate with this device using the Xiaomi gateway? It also does not appear in the list of Bluetooth devices...

Thank you very much for your work

**Comment by szymucha94** [comment]
@RedFox-Fr this gateway only supports xiaomi-approved ble devices. If you flashed your thermometers with atc fw they start to advertise (by default) using another protocol, also flashing usually changes device name.
If you want these to work with gateway you have to retain their original names (not ATC_XXX etc), mi-like protocol and original ble key.

**Comment by RedFox-Fr** [comment]
OK.

I was unable to attach the thermometer to the gateway. But after reflashing the thermometer with original firmware, it works.

Anyway, I need to find a good Bluetooth solution if I want to talk to any devices...

Thanks.
