### ISSUE TITLE
Xiaomi Multimode Gateway 2 (EU) - Device Offline

### ISSUE THREAD

**Issue by AdrianKuta** [AlexxIT/XiaomiGateway3#1045]
Currently I have two gateways in my network:
1.  Xiaomi Gateway v3 - ZNDMWG03LM
2. Xiaomi Multimode Gateway 2 (EU) / Xiaomi Smart Home Hub 2- ZNDMWG04LM - lumi.gateway.mgl001

Both are in the same network. I was able to add integration for the first one, without any problems.
But I can't connect to my second gateway.
Gateway is added to my Xiaomi Home app and is online. I used mail and password to add integration in Home Assistant. So when I clicks 'Add integration -> Xiaomi Gateway 3' I see option for my second gateway (ip address is correct): 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/46381935/232917524-bde44efb-ff7e-403f-847b-fa55b9ca68cb.png">

But every time I try to add it, I received error "can't connect to gateway" - or similar. And in system logs I see info "Device offline":
<img width="485" alt="image" src="https://user-images.githubusercontent.com/46381935/232917800-455ca6e4-7a62-49b7-9eb8-ad52fe484c47.png">

Do any of you have any ideas what could be wrong?

**Comment by AlexxIT** [comment]
Are you sure that IP address correct? Your server in same LAN network segment? And you don't have any restrictions between local devices?

**Comment by AdrianKuta** [comment]
Ok, server was in subnet 192.168.23.0/24 and gateway was in 192.168.7.0/24. I moved gateway to the same subnet as server, and now it's working 👍 
Second gateway (Xiaomi Gateway v3 - ZNDMWG03LM) is working even if it's in different subnet 🤔 

Thank you for your help!

**Comment by AlexxIT** [comment]
The problem will be only after gateway restart.
Integration uses miio protocol only for opening telnet.
But miio protocol won't answer on request from another subnet.
The first gateway will execute the command from the other subnet, but will not respond to it.
How the second gateway will behave, I do not know. I haven't tried it.
