### ISSUE TITLE
Status for Xiaomi door lock XMZNMST02YD unavaliable 

### ISSUE THREAD

**Issue by kyc1338** [AlexxIT/XiaomiGateway3#1046]
Hi

I have problem to obtain the status of my Xiaomi door lock XMZNMST02YD,
the status of all entities related to the lock didn't updated and only occasionally show "Become unavailable" following by the lock status "was locked" , 
Xiaomi multimode Gatway (CN) FW version 1.5.4_0090, 
GW3 version 3.2.1, 
HA latest version

Please help!!

Thanks

**Comment by DieMetRik** [comment]
same issue with lock ZNMS17LM
GW 1.5.4_0090

**Comment by LANB0** [comment]
same issue with lock XMZNMS09LM
GW 1.5.4_0090

**Comment by SosoKapianidze** [comment]
I have the same issue, also BLE mesh lights and motion sensors aren't working too
GW GW 1.5.4_0090

**Comment by SosoKapianidze** [comment]
I've tried to restart GW and it works now

**Comment by kyc1338** [comment]
What do you mean "restart"GW? Reload or re-install? I tried both, same - not work.

**Comment by DieMetRik** [comment]
After 2 day all works!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
