### ISSUE TITLE
Qingping Temp & RH Monitor (CGG1)

### ISSUE THREAD

**Issue by Vovan177** [AlexxIT/XiaomiGateway3#105]
Afte some update HA and Xiaomi Gateway 3 integration, when restart HA CGG1 registering temperature about 15C, humidity about 52% fnd battery 80%. After 5-10 minutes its back to real: 8C, 50%, 30%. MiHome displays real states.

**Comment by AlexxIT** [comment]
Please enable debug mode (readme), wait 1 hour before restart, 1 hour after restart and send logs.

**Comment by Vovan177** [comment]
Log files: [https://drive.google.com/file/d/1Rnpwddbtodi1ZRB4iOxQ0Yadg5kQdS3z/view?usp=sharing](url)

**Comment by AlexxIT** [comment]
I fixed problem in v 0.10.2
