### ISSUE TITLE
Add Hungarian translation

### ISSUE THREAD

**Issue by zsigus** [AlexxIT/XiaomiGateway3#1050]
Hi
[hu.txt](https://github.com/AlexxIT/XiaomiGateway3/files/11304433/hu.txt)

Thank you for your work! 

I am attaching the Hungarian translation.
.txt -> .json

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
