### ISSUE TITLE
The triple key only recognizes one

### ISSUE THREAD

**Issue by happyfoeverq** [AlexxIT/XiaomiGateway3#1051]
I use a triple key wireless switch made by a third party, which is normal in MIot app. After adding HA, only left key is recognized.
How do I get HA to recognize the other two keys.

**Comment by cnjingrui** [comment]
我也遇到同样的问题，请问你得到解决了吗？

**Comment by AlexxIT** [comment]
You need to start by providing useful information. At least the model of the device. Screenshot of the Home Assistant device.

**Comment by laipeng101** [comment]
> 您需要首先提供有用的信息。至少设备型号。家庭助理设备的屏幕截图。

![1695648412607](https://github.com/AlexxIT/XiaomiGateway3/assets/32242425/5912cb29-1f0e-4ea6-acbc-4e15428d57d4)
IMILAB Smart switch K1-C
https://home.miot-spec.com/s/chuangmi.switch.meshc01

**Comment by Tingan03** [comment]
I also encountered the same problem.
[topwit.switch.rzw45](https://home.miot-spec.com/spec/topwit.switch.rzw45)
[topwit.switch.rzw32](https://home.miot-spec.com/spec/topwit.switch.rzw32)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/117313149/19fc228b-5a73-48c1-b44c-d7f7b841f5eb)

**Comment by AlexxIT** [comment]
Closed without response
