### ISSUE TITLE
 When integrating with the Xiaomi Multi-Mode Gateway 2 using the plugin, the error "Invalid Gateway Token" is returned.

### ISSUE THREAD

**Issue by wrjvszq** [AlexxIT/XiaomiGateway3#1052]

**Comment by AlexxIT** [comment]
Well error pretty clear. Token wrong. Try to get it with another way.

**Comment by wrjvszq** [comment]
Both the tokens I obtained automatically and manually are incorrect, and cannot be integrated.
 However, I was able to integrate successfully using the following method:

1. Use the Xiaomi account to integrate XiaomiGateway3
2. Delete XiaomiGateway3
3. Re-integrate XiaomiGateway3, but this time select the Multi-Mode Gateway 2 option, and it will be successful.

**Comment by AlexxIT** [comment]
As I can understand it, the problem is solved
