### ISSUE TITLE
Multi mode gateway(ZNDMWG03LM) BLE device disconnected

### ISSUE THREAD

**Issue by isdebug** [AlexxIT/XiaomiGateway3#1053]
The thing is like this
After updating approximately 3.2.0 to 3.2.1, the BLE devices on the gateway will gradually become "unavailable" every two days or so, but they can be operated on the Mijia APP. After clicking "reload" on the config/integrations page, these BLE devices will resume working
I have tried removing the gateway from the Mi Home app, then removing XiaomiGateway3 from the hassle and re adding and initializing it, but still cannot solve the problem;
I have also tried selecting [DANGER] Use storage in memory, but still cannot solve the problem;
Before making the above attempt, I ensured that the router settings had never changed and the gateway location had not changed. However, during this period, I added several BLE devices. I wonder if it was due to the addition of devices? Currently, XiaomiGateway3 controls 24 devices (4 zigbee, 20 BLE)
I'm not sure if it's related to the latest version update of XiaomiGateway3, so I'm trying to provide feedback

**Comment by McYars** [comment]
Same problem.

**Comment by zhim0293** [comment]
Same problem.

**Comment by littlehi** [comment]
Same problem.

**Comment by FalenDemon** [comment]
Looks like the same to me. Gateway - ZNDMWG03LM / FW - 1.5.4_0090
HA - 2023.05.02. 
None off BLE devices working from 12.05. Including door lock, mesh spot lights, kettle and other devices. 
"Cloud link" entity not available. Zigbee devices working.

**Comment by micturkey** [comment]
Same problem, BLE devices works well but mesh devices become unavailable every serveral days.

**Comment by micturkey** [comment]
> > Same problem, BLE devices works well but mesh devices become unavailable every serveral days.
> 
> 咱们遇到的问题可能不一样...

Emmm yes, your problem is with BLE devices but mine is with mesh devices 😂

**Comment by yyax** [comment]
me to！

**Comment by yyax** [comment]
所有蓝牙mesh设备变成不可用了 ，重载也没有用 ， 卸载重装后可以用几个小时，然后又不可用。

**Comment by FalenDemon** [comment]
Looks like discribed problem is gone after 2023.05.03 HA update. Right now all BLE devices available in HA.

**Comment by nemoforum** [comment]
I was running into the same issue, however, I can't clearly identify the reason.
Possible reasons are:
- HA update
- Gateway firmware update: mgl03_1.5.1_0032_mod20211108 -> mgl03_1.5.4_0090_mod20220510
3 days ago I installed mgl03_1.5.5_0006_mod20230517 - still working. Will see.

**Comment by yyax** [comment]
2.4gwifi   40MHz to 20MHz

**Comment by MaoZ1993** [comment]
> I have recently switched to version 3.1.0 and it seems that the problem has been alleviated. At least there have been no issues in the past 4 days

Same here. 3.1.0 solved my issue. I have two gateway setup and I think this issue is related to multiple gateway support features introduced in 3.2.0.

**Comment by AlexxIT** [comment]
@isdebug there is no info about your gateway firmware.
Are you sure we talking about BLE devices and not Mesh devices?

@micturkey I can confirm a situation where Mesh devices stop working and BLE devices continue. I'm trying to figure out why.

**Comment by AlexxIT** [comment]
@isdebug you still haven't provided the firmware of your gateway

**Comment by micturkey** [comment]
> @isdebug there is no info about your gateway firmware. Are you sure we talking about BLE devices and not Mesh devices?
> 
> @micturkey I can confirm a situation where Mesh devices stop working and BLE devices continue. I'm trying to figure out why.

Thanks, waiting for update :).
Now I use an automation to reboot every gateways every 2 days, and mesh devices wouldn't stop working again.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0

**Comment by perfect-deform** [comment]
``Viomi Kettle V-SK152 sensors info seems to be still unavailable.

gateway: Xiaomi ZNDMWG03LM
FW: 1.5.4_0090 (Custom)
Integration: 3.3.4

```2023-10-31 07:36:48 [D] 192.168.0.156 [MQTT] miio/report b'{"id":1518051946,"method":"_sync.ble_query_prod","params":{"pdid":1116}}'
2023-10-31 07:36:48 [D] 192.168.0.156 [MQTT] miio/report_ack b'{"error":{"code":-7,"message":{"operation":"query_prod","pdid":1116}},"id":1518051946}'
2023-10-31 07:34:59 [D] 192.168.0.156 [BASE] b87c6fae0830 (1116) setup ble V-SK152: power, temperature, ble
2023-10-31 07:40:09 [D] 192.168.0.156 [MQTT] miio/report_ack b'{"id":2096716974,"result":{"operation":"keep_alive","intvl":1200,"delta":300,"filter":[{"mac":"B8:7C:6F:AE:08:30","pdid":1116,"ttl":7200,"desc":"has no permit"}]}}'
2023-10-31 07:41:52 [D] 192.168.0.156 [MQTT] miio/report b'{"id":1259895991,"method":"_sync.ble_query_prod","params":{"pdid":1116}}'
2023-10-31 07:41:52 [D] 192.168.0.156 [MQTT] miio/report_ack b'{"error":{"code":-7,"message":{"operation":"query_prod","pdid":1116}},"id":1259895991}'```
