### ISSUE TITLE
Request for support Xiaomi Multimode Gateway firmware 1.5.5_0006

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#1057]
Request for support Xiaomi Multimode Gateway firmware 1.5.5_0006,thanks.

**Comment by AlexxIT** [comment]
Sorry. Telnet cannot be opened on this firmware using the software method.
You either have to wait for a new way to open the Telnet. Or solder the gateway and downgrade the firmware. Or throw the gateway in the trash :)

**Comment by lxz946786639** [comment]
> Sorry. Telnet cannot be opened on this firmware using the software method. You either have to wait for a new way to open the Telnet. Or solder the gateway and downgrade the firmware. Or throw the gateway in the trash :)

haha

**Comment by 18605000242** [comment]
> Sorry. Telnet cannot be opened on this firmware using the software method. You either have to wait for a new way to open the Telnet. Or solder the gateway and downgrade the firmware. Or throw the gateway in the trash :)

is it any way to downgrade if the firmware is 1.5.5?

**Comment by gewanbo** [comment]
I accidentally clicked on the upgrade and ended up with version 1.5.5_0006. The Xiaomi app kept prompting you to click on the upgrade button. Finally, I found this solution and downgraded back to 1.5.0 using UART method. Then, I manually upgraded to 15.4. Many thanks to @AlexxIT for providing the detailed documentation. The UART method is indeed not easy for me. I have no idea what UART is, and I got stuck in the process because I couldn't find the firmware file like 15.x.uart. I also tried this method mentioned at https://github.com/AlexxIT/XiaomiGateway3/wiki/Downgrade-Firmware#solder-uart. Fortunately, after restarting, I was lucky enough to find it back at version 15.0. I'm happy now!

**Comment by benghee** [comment]
> Request for support Xiaomi Multimode Gateway firmware 1.5.5_0006,thanks.

There is another easy way, no need downgrade FW or TRASH your Xiaomi devices, which is just switch to another Xiaomi integration from HACS that works perfectly fine (tested on Google Home and Apple Home like an old day). 
But i need to thank to AlexxIT all these years working hard on the updates and make Xiaomi devices used to integrated well with HA.

**Comment by TwKenYang** [comment]
> > Request for support Xiaomi Multimode Gateway firmware 1.5.5_0006,thanks.
> 
> There is another easy way, no need downgrade FW or TRASH your Xiaomi devices, which is just switch to another Xiaomi integration from HACS that works perfectly fine (tested on Google Home and Apple Home like an old day). But i need to thank to AlexxIT all these years working hard on the updates and make Xiaomi devices used to integrated well with HA.

Xiaomi Miot Auto can find the gateway, but it is often unavailable

**Comment by thanhbacmc** [comment]
> > > Request for support Xiaomi Multimode Gateway firmware 1.5.5_0006,thanks.
> > 
> > 
> > There is another easy way, no need downgrade FW or TRASH your Xiaomi devices, which is just switch to another Xiaomi integration from HACS that works perfectly fine (tested on Google Home and Apple Home like an old day). But i need to thank to AlexxIT all these years working hard on the updates and make Xiaomi devices used to integrated well with HA.
> 
> Xiaomi Miot Auto can find the gateway, but it is often unavailable

or Xiaomi MIoT ok!

**Comment by Algorithm0** [comment]
Xiaomi Miot Auto с хабом и всеми устройствами, которые подключены через него, работает ИСКЛЮЧИТЕЛЬНО ЧЕРЕЗ ОБЛАКО. В особенности если ваши хаб настроен на китайские сервера, то вы можете получить значительную задержку в сравнении с этой интеграцией, не говоря уже о конфиденциальности.
AlexxIT, огромное спасибо за то, что ты делаешь. Это просто превосходно.

**Comment by skrashevich** [comment]
I have found a way to activate telnet on firmware 1.5.5, but it requires the key (not a token!) from the device. Unfortunately, I have not yet discovered a way to obtain it without telnet already being open. However, if you have saved it somewhere before updating to 1.5.5, the re-opening telnet process will be very straightforward.

**Comment by rezmus** [comment]
```
cat /data/miio/device.conf
```

key/mac/did is unique per device so you can only calc pswd and send commands to device you have this data for (backup before telnet is locked).

**Comment by AlexxIT** [comment]
I come to you with good news. I updated my first post with a description of how to enable telnet on 1.5.5 firmware:
https://github.com/AlexxIT/XiaomiGateway3/issues/1057#issuecomment-1543550411

**Comment by cxfksword** [comment]
> I come to you with good news. I updated my first post with a description of how to enable telnet on 1.5.5 firmware: [#1057 (comment)](https://github.com/AlexxIT/XiaomiGateway3/issues/1057#issuecomment-1543550411)

Thanks, I've done it!

**Comment by Vlavlabur** [comment]
"5 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause."
There are 5 double clicks on the video, and 6 in the description...
How right?

**Comment by AlexxIT** [comment]
I don't know why only 5 works on video. There should be 6.
But anyway. Keep trying until green light.

**Comment by Plaudern** [comment]
I have three p3 gateways, one 4.0.2_0024_0644. Two 4.0.1_0004, I tried to use 5-2-2-2-2 to open telnet (the green light is on), I tried to scan with nmap and the results are as follows
（This is a P3 with firmware 4.0.1_0004）
```bash
PS C:\Users\Plaud>nmap -p 22-23 192.168.8.243
Starting Nmap 7.94 ( https://nmap.org ) at 2023-06-06 08:53 中国标准时间
Nmap scan report for AC-Controller-2936.lan (192.168.8.243)
Host is up (0.040s latency).

PORT   STATE  SERVICE
22/tcp closed ssh
23/tcp open   telnet
MAC Address: 54:EF:44:2E:1F:FF (Lumi United Technology)

Nmap done: 1 IP address (1 host up) scanned in 4.06 seconds
```
and then I used telnet to connect
```bash
PS C:\Users\Plaud>telnet 192.168.8.243
AC-Controller-1FFF login: admin
Password:
Login incorrect
```
What should I do? Does it mean that I can only go through the flash UART method?

**Comment by rezmus** [comment]
if you did not use them in HA before they still have password on telnet. clicks enable tty/telnetd and are solution only for ppl who deleted password before, but updated to locked firmware.

**Comment by ThomasD013** [comment]
> Well. You need to be more careful and stop upgrading to unsupported firmwares. Fortunately for you, there is a way to fix it.
> 
> # Software method
> If the gateway previously worked in Home Assistant integration, you can enable Telnet on firmware 1.5.5: 5 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause, 2 clicks, pause. https://www.youtube.com/shorts/qJ21wWNE1Gg
> 
> **Warning!** Incorrect clicks can reset the gateway. 10 clicks - reset gateway.
> 
> Then you need to install any supported firmware: https://github.com/zvldz/mgl03_fw/tree/main/firmware
> 
> # Hardware method
> If the gateway has not previously worked in Home Assistant integration, you can enable Telnet, but it will have a password, which is impossible to find out. So you need to flash your gateway with UART: https://github.com/AlexxIT/XiaomiGateway3/wiki

How can i disable automated udpate ? I woke up this morning and my gateway was upgraded :/

**Comment by AlexxIT** [comment]
I described about version in the blog https://github.com/AlexxIT/Blog/issues/13

**Comment by dfanica** [comment]
This worked wonders for me. I upgraded a few days ago without knowing that it will break my integration. I did try for about 1-2 hours to get open the telnet but eventually managed. Thanks everyone in this discussion for all the info!

**Comment by HowLow** [comment]
> ```
> cat /data/miio/device.conf
> ```
> 
> key/mac/did 对于每个设备都是唯一的，因此您只能计算 pswd 并向您拥有此数据的设备发送命令（在 telnet 锁定之前备份）。

问下这个did里面是一串阿拉伯数字么 能否给个示例 我好像找到了一串did

**Comment by ifflanb** [comment]
Is it likely or possible that this will ever be fixed in a more permanent way? I have noticed that for me, the Telnet gets broken every time the gateway loses power. Then by the time you have gotten the click timing correct in order to re enable it, you end up hard resetting the device by accident and losing your child devices. This is a real pain.

**Comment by rezmus** [comment]
clicks are meant only for temporary telnet access so you can get gw cloud key.

```
cat /data/miio/device.conf
```

integration should be able to enable telnet on 1.5.5 when key is filled.

**Comment by ifflanb** [comment]
Thanks @rezmus . I already have a key specified in the Gateway config. Do the keys change?

**Comment by ifflanb** [comment]
Hmm ok. I guess mine is ok then. So your saying that you can restart your gateway and the Telnet remains working?
