### ISSUE TITLE
Xiaomi Mijia Mosquito Repellent 2 Smart Version (WX10ZM)

### ISSUE THREAD

**Issue by Denis-blr** [AlexxIT/XiaomiGateway3#1059]
The control in the fumigator Xiaomi Mijia Mosquito Repellent 2 Smart Version (WX10ZM) does not work. When you click the enable button in the integration in HA, nothing happens. Management via Mi Home works.

**Comment by AlexxIT** [comment]
Check if management via Mi Home works when you not at home or with disabled bluetooth on the phone.
Because you can control device via direct BT connection
