### ISSUE TITLE
No Device found in HA after Integration with Gateway

### ISSUE THREAD

**Issue by githubreabyorg** [AlexxIT/XiaomiGateway3#106]
The Mi cloud account integration is working, I can check device info, token and etc. 
The Mi Gateway has been added to HA integration successfully, but no device nor entity discovered after integration. I tried factory reset the gateway, no difference.  
Any suggestion? Is there any dependency package required for this integration or any specific configuration is required in HA? 

Environment:
Integration code installed with HACS, I tried both v0.10.1 and v0.10.0. 
Home Assistant: 0.115.2 running on Docker.
Device firmware: v1.4.5_0016 (Downgraded from v1.4.7_0065)
 one subdevice zigbee and two BLE device linked the gateway, none of them pop up in HA.

**Comment by AlexxIT** [comment]
Do you add integration two times? For cloud and for gateway?

**Comment by githubreabyorg** [comment]
Tried every way, only cloud, only gateway, or both. No difference for me, all integration works, just no device found in HA.

**Comment by AlexxIT** [comment]
Oh. You downgraded. Check #83

**Comment by githubreabyorg** [comment]
Device pop up right after delete json files. Thanks. BTW, maybe add this to FAQ?
