### ISSUE TITLE
Adding Vima Smart Lock

### ISSUE THREAD

**Issue by daniperaleda** [AlexxIT/XiaomiGateway3#1065]
Hi

I have been working for more than 2 years with ZHA and Xiaomi Gateway 3. I have just bought a VIMA Smart Lock. It connects using ZHA, but not many options appears on it.

I have tried to swicht to normal operation of Xiaomi Gateway 3 disabling ZHA or unistalling ZHA...but it doesn't discover any divice...any sensor nor the smart lock.

How do you recommend me to operate?

**Comment by AlexxIT** [comment]
Are you sure gateway should support this device model?

https://github.com/AlexxIT/XiaomiGateway3#zigbee-custom-firmware

**Comment by daniperaleda** [comment]
> Are you sure gateway should support this device model?
> 
> https://github.com/AlexxIT/XiaomiGateway3#zigbee-custom-firmware

Interesting @AlexxIT lexxIt...sorry but I don't have thought that option...where can I find custom firmware?...

Another crazy topic...in this case, of multimode...could I use it to put a firmware that could allow me to use the hub with the Tuya App?...I know it could be crazy...but changing the firmware I don't know if it is possible.

**Comment by AlexxIT** [comment]
<img width="671" alt="image" src="https://github.com/AlexxIT/XiaomiGateway3/assets/511909/34d10c89-00ee-4636-9dee-4c77c5b8f246">

**Comment by daniperaleda** [comment]
> <img alt="image" width="671" src="https://user-images.githubusercontent.com/511909/243330104-34d10c89-00ee-4636-9dee-4c77c5b8f246.png">

Thanks @AlexxIT  I have seen that option...but where to find a different firmware?

**Comment by AlexxIT** [comment]
I the next dropdown
