### ISSUE TITLE
Add support for bean.switch.*

### ISSUE THREAD

**Issue by MapleEve** [AlexxIT/XiaomiGateway3#1074]
Hi, I've recently bought bean.switch to let my 86-type switch support remote control.

But unfortunately, HAAS only recognize the Mesh info rather than the on/off switch info (for more than one switches).

The miot link is below:
one button(including double control model): https://home.miot-spec.com/spec/bean.switch.bl01
two buttons: https://home.miot-spec.com/spec/bean.switch.bl02
three buttons: https://home.miot-spec.com/spec/bean.switch.bl03

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1845053/20f9b64c-ae06-4f5c-bd90-38a8eb110c4f)

Thanks.

**Comment by AlexxIT** [comment]
You can try to do it yourself

**Comment by MapleEve** [comment]
> You can try to do it yourself

Sure I tried, but the num ID and siwtch stats are so complicated. I just want to control all 3 switches. And it's not wifi switch or smart switch. They are connected thorugh 220V to make old switch into BLE and MiHome control.

**Comment by three1bro** [comment]
{
   9612: ["WhoKnows", "Mesh Singel Wall Switch", "bean.switch.bl01"],
    "spec": [
        Converter("switch_1", "switch", mi="2.p.1"),
        MapConv("mode_1", "select", mi="2.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
	Action,
        ButtonMIConv("button_1", mi="3.e.1", value=1),
    ] 
},{
   9613: ["WhoKnows", "Mesh Double Wall Switch", "bean.switch.bl02"],
    "spec": [
        Converter("switch_1", "switch", mi="2.p.1"),
        Converter("switch_2", "switch", mi="3.p.1"),
        MapConv("mode_1", "select", mi="2.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
        MapConv("mode_2", "select", mi="3.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
	Action,
        ButtonMIConv("button_1", mi="4.e.1", value=1),
        ButtonMIConv("button_2", mi="5.e.1", value=1),
    ] 
},{
   9614: ["WhoKnows", "Mesh Triple Wall Switch", "bean.switch.bl03"],
    "spec": [
        Converter("switch_1", "switch", mi="2.p.1"),
        Converter("switch_2", "switch", mi="3.p.1"),
        Converter("switch_3", "switch", mi="4.p.1"),
        MapConv("mode_1", "select", mi="2.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
        MapConv("mode_2", "select", mi="3.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
        MapConv("mode_3", "select", mi="4.p.2", map={ 0: "off", 1: "wireless", 2: "flex", 3: "scene" }),
	Action,
        ButtonMIConv("button_1", mi="5.e.1", value=1),
        ButtonMIConv("button_2", mi="6.e.1", value=1),
        ButtonMIConv("button_2", mi="7.e.1", value=1),
    ] 
}

This is my code , it test in my switch. thanks https://github.com/AlexxIT/XiaomiGateway3/issues/1140#issue-1882147598
