### ISSUE TITLE
Add support PTX Mesh Single Wall Switch and Double Wall Switch 

### ISSUE THREAD

**Issue by xiaoyaofengyuxing** [AlexxIT/XiaomiGateway3#1078]
Could you please add this new mesh device to next version? Thanks.
The report is similar with #993.

Brand: PTX
Name: Mesh Single Wall Switch
Model: 090615.switch.aksk1
Entities: switch

I added this line in "./core/converters/devices.py" and it's works well
```
}, {
    11333: ["PTX", "Mesh Single Wall Switch", "090615.switch.aksk1"],
    "spec": [
        Converter("switch", "switch", mi="2.p.1"),
    ],
```

Brand: PTX
Name: Mesh Double Wall Switch
Model: 090615.switch.aksk2
Entities: channel_1,channel_2
```
}, {
    11332: ["PTX", "Mesh Double Wall Switch", "090615.switch.aksk2"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),        
    ],
```

**Comment by AlexxIT** [comment]
Thanks!

**Comment by xiaoyaofengyuxing** [comment]
Thanks!

**Comment by HugoPresents** [comment]
this works well on no N version

12471: ["PTX", "Mesh Double Wall Switch(no N)", "090615.switch.aksk2"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
    ]
}

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
