### ISSUE TITLE
firmware Xiaomi Multimode Gateway 2 (EU) (ZNDMWG04LM)

### ISSUE THREAD

**Issue by shurakenas** [AlexxIT/XiaomiGateway3#1079]
How to upgrade to custom? In the description, only the firmware for gateway 3. I connected the Tuya switch, and it immediately goes into the "unavailable" state, although he is in touch.
Model - lumi.gateway.mgl001
https://ibb.co/kSSH0FB

**Comment by shurakenas** [comment]
[https://ibb.co/kSSH0FB](url)

**Comment by shurakenas** [comment]
After the integration update, it stopped being added at all.
https://ibb.co/W2j7gx1

**Comment by AlexxIT** [comment]
I'm not making custom firmware
