### ISSUE TITLE
Telnet blocked on gateway3

### ISSUE THREAD

**Issue by byxil** [AlexxIT/XiaomiGateway3#1081]
I have had gateway3 for about a year now and it has always worked fine.
It has lost its entities for a few days and I can't get it to work anymore.
I saw that telnet is blocked and this I think is the problem (before it worked).
My device model is:
Name: Gateway3
Model: lumi.gateway.mgl03
Firmware: 1.5.4
I don't have the key but only the tocken and when I try to reconfigure the gateway from the integration, the message "Wrong open telnet command" appears

**Comment by AlexxIT** [comment]
Double check that you have old 1.5.4 firmware. Double check that your gateway in same subnet with Hass server.
There cannot be any magic here

**Comment by cma84** [comment]
> no sorry, I checked the firmware from the MI Home app (to which the gateway has always been connected) and it must be updated because now it gives me the 1.5.5_0006 version So with the new firmware telnet is blocked, right? Do you know if it is possible to downgrade? Thank you
> 
> Edit: I see now that you put a guide to do this, thanks

hello, how did you solve it?

In my case I had it working, but I bought a Raspberry Pi 4 and mounted again HA and now I can't get the integration of the Gateway V3.

I have the same firmware version as you but as I said it was working before the change of equipment.
