### ISSUE TITLE
Add support linp.switch.q3s3

### ISSUE THREAD

**Issue by happyhaha1** [AlexxIT/XiaomiGateway3#1083]
Try to add support for linp.switch.q3s3,I am not able to make the button event work under wireless and scene mode in HA.
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:switch:0000A003:frfox-bl01:1:0000C808

```
{
    2274: ["Linptech", "Lingpu wall switch MESH (three bond)", "linp.switch.q3s3"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
        Converter("channel_3", "switch", mi="4.p.1"),
        Converter("action", "sensor", enabled=False),
        Converter("led", "switch", mi="5.p.1"),
    ],
}, 
```

**Comment by happyhaha1** [comment]
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/10184254/13ec759d-3b65-4ab9-badb-dd20d6064da5)
action  is Not available

**Comment by AlexxIT** [comment]
You need to add converters for events.

**Comment by happyhaha1** [comment]
i add this  but not work
```
        Converter("action", "sensor", enabled=False),
```

**Comment by AlexxIT** [comment]
This converter only shows decoded events. But other converters should decode them. I'm from mobile. Can't help you now.

**Comment by happyhaha1** [comment]
Waiting for you to help me

**Comment by dixon777** [comment]
The site related to the product id ( linp.switch.q3s3) you provided should be:

**Comment by dixon777** [comment]
The website related to linp.switch.q3s3 should be:
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:switch:0000A003:linp-q3s3:2:0000C810
Its bottom shows the protocols related to the button click events:
```
{
  "iid":7,
   ...
  "events":[
  {"iid":1,"type":"urn:linp-spec:event:left-click:00005001:linp-q3s3:2","description":"left-click","arguments":[]},
  {"iid":2,"type":"urn:linp-spec:event:middle-click:00005002:linp-q3s3:2","description":"middle-click","arguments":[]},
  {"iid":3,"type":"urn:linp-spec:event:right-click:00005003:linp-q3s3:2","description":"right-click","arguments":[]}
  ]
}
```

With this info, you may use ButtonMIConv to define how button click events should be decoded:
```
{
    2274: ["Linptech", "Lingpu wall switch MESH (three bond)", "linp.switch.q3s3"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
        Converter("channel_3", "switch", mi="4.p.1"),

        Converter("action", "sensor", enabled=False),

        # Modified from xiaomi_gateway3/core/converters/devices.py line 881
        ButtonMIConv("button_1", mi="7.e.1", value=1), 
        ButtonMIConv("button_2", mi="7.e.2", value=1), 
        ButtonMIConv("button_3", mi="7.e.3", value=1), 

        Converter("led", "switch", mi="5.p.1"),
    ],
}
```
Once you put this piece of code in HA config and reload HA, you should be able to see something pops up in attribute "Action". I am not 100% sure since I don't have your device to play around, so let me know if it works

**Comment by happyhaha1** [comment]
Thank you, is ok

**Comment by happyhaha1** [comment]
{
    2274: ["Linptech", "Lingpu wall switch MESH (three bond)", "linp.switch.q3s3"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
        Converter("channel_3", "switch", mi="4.p.1"),

        Converter("action", "sensor", enabled=False),

        # Modified from xiaomi_gateway3/core/converters/devices.py line 881
        ButtonMIConv("button_1", mi="7.e.1", value=1), 
        ButtonMIConv("button_2", mi="7.e.2", value=1), 
        ButtonMIConv("button_3", mi="7.e.3", value=1), 

        Converter("led", "switch", mi="5.p.1"),
    ],
}, {
    # https://home.miot-spec.com/s/5045
    2429: ["Linptech", "Lingpu wall switch MESH (double bond)", "linp.switch.q3s2"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),

        Converter("action", "sensor", enabled=False),

        # Modified from xiaomi_gateway3/core/converters/devices.py line 881
        ButtonMIConv("button_1", mi="7.e.1", value=1), 
        ButtonMIConv("button_2", mi="7.e.2", value=1), 

        Converter("led", "switch", mi="5.p.1"),
    ],
}, {
    # https://home.miot-spec.com/s/5045
    2428: ["Linptech", "Lingpu wall switch MESH (one bond)", "linp.switch.q3s1"],
    "spec": [
       Converter("channel_1", "switch", mi="2.p.1"),
        Converter("action", "sensor", enabled=False),

        # Modified from xiaomi_gateway3/core/converters/devices.py line 881
        ButtonMIConv("button_1", mi="7.e.1", value=1), 

        Converter("led", "switch", mi="5.p.1"),
    ],
}

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
