### ISSUE TITLE
Update support for PTX Mesh Multifunction Wireless Switch

### ISSUE THREAD

**Issue by ibmcoco** [AlexxIT/XiaomiGateway3#1084]
This is a multi-button device.
Now only one key can be used.
[https://github.com/AlexxIT/XiaomiGateway3/issues/1063](https://github.com/AlexxIT/XiaomiGateway3/issues/1063)
I made a modification and currently can support two keys.

I only have a two-button device, so can't do more testing.

```
}, {
    # https://home.miot-spec.com/spec/chuangmi.switch.meshb01
    # https://github.com/AlexxIT/XiaomiGateway3/issues/1063
    10371: ["PTX", "Mesh Multifunction Wireless Switch", "090615.remote.mlsw0a"],
    "spec": [
        MiBeacon, BLEAction, Button,  # don't know is it BLE or Mesh
        EventConv("action", mi="2.e.1", value="click_1"),
        EventConv("action", mi="2.e.2", value="click_2"),
        EventConv("action", mi="3.e.2", value="hold_1"),
        EventConv("action", mi="3.e.3", value="hold_2"),
    ],
```

**Comment by ymj0424** [comment]
I'm curious as to why the domain name wasn't specified?

**Comment by AlexxIT** [comment]
Domain inside BLEAction

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
