### ISSUE TITLE
Please add support for Presence sensor Linptech ES1DB

### ISSUE THREAD

**Issue by kulnis182** [AlexxIT/XiaomiGateway3#1086]
Could you please add support for  Presence sensor Linptech ES1DB (ES2)
This is the same version as currently supported Linptech ES1ZB.
The only differences Linptech ES1DB (ES2) is the top mounted sensor
This device can be added to MI home application

**Comment by AlexxIT** [comment]
You need to provide device MiHome model and MiHome number.

**Comment by rezmus** [comment]
iirc it is same model in mijia, no need to add anything.

**Comment by AlexxIT** [comment]
@rezmus thanks! So model already supported.
