### ISSUE TITLE
Fix mesh mosquito led switch

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#1088]
State should be inverted

**Comment by saury** [comment]
Is this issue relates to device mesh switch 'Mi Smart Dual One Way Wall Switch Mesh'(DHKG02ZM)? 
I find this mesh switch's on/off status not syncing after upgrading to latest version. Have to downgrade to v3.1.0.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
