### ISSUE TITLE
lumi.gateway.v3 and sub-device become unavailable

### ISSUE THREAD

**Issue by dengke80622** [AlexxIT/XiaomiGateway3#1089]
For testing, have a fresh installation on vmware workststion and add core integrated Xiaomi Aqara Gateway (lumi.gateway.v3_1.4.1_176.0220) with the token, sub-devices are identified and work OK, BUT after a while, all entities of the gateway and its sub-device turn to "unavailable". reload integration can solve this issue temporarily but happens again after a while.

LOG:
Home Assistant Core
Got error element in data {"error":"Invalid key"}
June 26, 2023 at 2:47:43 PM – (ERROR) components/xiaomi_aqara/light.py
Got error element in data {"error":"Invalid key"}
June 26, 2023 at 2:23:59 PM – (ERROR) components/xiaomi_aqara/config_flow.py - message first occurred at June 26, 2023 at 2:23:59 PM and shows up 2 times

OS information:
Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3
Frontend 20230608.0 - latest

Noticed that in readme.md, the supported version for Home Assistant is from 2022.8.x to 2023.5.x.
The gateway works well before 2023.6 update, please help to look into this issue, appreciate :)

**Comment by AlexxIT** [comment]
This is another integration
