### ISSUE TITLE
BLE LYWSDCGQ not in Home Assistant... again

### ISSUE THREAD

**Issue by Montaraz1** [AlexxIT/XiaomiGateway3#109]
Hi, i know that this issue seems already deal with,
but i cant see any Xiaomi TH Sensor (LYWSDCGQ/01ZM) in Home Assistant.

I try to update to 0.10.2 and restart many times HA and Gateway too.

Here's my log...no sign of bluetooth

https://docs.google.com/document/d/1sh419IzhdPMnbfGyBJHzkNPodg1XkujdrKGGtkjM43E/edit?usp=sharing

Thanks for help

**Comment by AlexxIT** [comment]
Enable `debug: miio` mode

**Comment by Montaraz1** [comment]
here.

thanks
[miio.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5546161/miio.txt)

**Comment by AlexxIT** [comment]
Remove your log, has some private data. Your gw can't connect to sensor. I don't know why.

**Comment by Montaraz1** [comment]
Ok, that for warning.
in the app Xiaomi Home are connected and show temperature.

So there's no solutions?

**Comment by mikeinblue** [comment]
I got the same problem.Don't know why?
![Uploading D87431DA-07E7-4100-82DC-BD3D4A2566BC.png…]()

**Comment by AlexxIT** [comment]
May be you have another BLE gateways

**Comment by mikeinblue** [comment]
I checked my mihome and found the TH sensor is connecting through my speaker.So I can it in mihome but can't connect in hass. Thanks.Alex

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
