### ISSUE TITLE
Fix error on battery info for LYWSD02MMC

### ISSUE THREAD

**Issue by mdarek2** [AlexxIT/XiaomiGateway3#1095]
The new version (firmware 2.0.1_0021) does not read the battery status.
Gateway firmware : 1.5.0_0102

**Comment by mdarek2** [comment]
"message": [
          "192.168.1.56 | ERROR processing MQTT: miio/report b'{\"id\":1491357038,\"method\":\"_async.ble_event\",\"params\":{\"dev\":{\"did\":\"blt.3.1eck6cs2klk00\",\"mac\":\"A4:C1:38:44:4F:F6\",\"pdid\":9538},\"evt\":[{\"eid\":18435,\"edata\":\"64\"}],\"frmCnt\":102,\"gwts\":1688075996}}'",
          "192.168.1.56 | ERROR processing MQTT: miio/report b'{\"id\":1909449039,\"method\":\"_async.ble_event\",\"params\":{\"dev\":{\"did\":\"blt.3.1eehpp9dc5k00\",\"mac\":\"A4:C1:38:A7:BF:71\",\"pdid\":9538},\"evt\":[{\"eid\":18435,\"edata\":\"64\"}],\"frmCnt\":53,\"gwts\":1688075999}}'"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/xiaomi_gateway3/core/device.py",
          434
        ],
        "timestamp": 1688076000.922741,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py\", line 170, in mqtt_message\n    await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/base.py\", line 108, in dispatcher_send\n    await handler(**kwargs)\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/ble.py\", line 42, in ble_mqtt_publish\n    await self.ble_process_event(msg.json[\"params\"])\n  File \"/config/custom_components/xiaomi_gateway3/core/gateway/ble.py\", line 75, in ble_process_event\n    device.update(payload)\n  File \"/config/custom_components/xiaomi_gateway3/core/device.py\", line 434, in update\n    gateway.setups[conv.domain](gateway, self, conv)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: None\n",
        "count": 2,
        "first_occurred": 1688075997.8625734

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2

**Comment by dansh1n** [comment]
There is still no data on the battery in the NA or am I doing something wrong? :)

`{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2023.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Moscow",
    "os_name": "Linux",
    "os_version": "6.1.57-v8+",
    "supervisor": "2023.10.0",
    "host_os": "Debian GNU/Linux 12 (bookworm)",
    "docker_version": "24.0.6",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "xiaomi_gateway3": {
      "version": "3.3.3",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "codeowners": [
      "@AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "requirements": [
      "zigpy>=0.44.1"
    ],
    "version": "3.3.3",
    "is_built_in": false
  },
  "data": {
    "version": "66bde38",
    "options": {
      "host": "***",
      "token": "***",
      "key": "***",
      "ble": true,
      "stats": true,
      "debug": []
    },
    "errors": [],
    "device": {
      "type": "ble",
      "model": 9538,
      "fw_ver": null,
      "available": true,
      "decode_time": 498,
      "entities": {
        "temperature": {
          "state": "21.5",
          "value": 21.5
        },
        "humidity": {
          "state": "45",
          "value": 45
        },
        "ble": {
          "state": "2023-10-23T07:50:41+00:00",
          "value": "2023-10-23T07:50:41.594703+00:00"
        }
      },
      "gateways": [
        "54ef4dd217f0"
      ],
      "stats": {
        "mac": "a4c13ff30c7d",
        "available": true
      },
      "unique_id": "a4c13ff30c7d"
    },
    "logger": []
  }
}`

**Comment by mdarek2** [comment]
You're right, it doesn't work.
