### ISSUE TITLE
Fix FTP for Xiaomi Multimode Gateway

### ISSUE THREAD

**Issue by gyenesadam** [AlexxIT/XiaomiGateway3#1099]
Hello!

First of all, i want to say than you for your work?

Secondly, i have a very amateur problem.
I have a ZNDMWG03LM gw, with 1.5.4_0090 fw.
I made the 5 sec hack with the motion sensors. Now my wife want to drop me or the gw or both out 😁.
I unable to connect to the gw via ftp.

In HA, i enable FTP, after the HA lost connection with the GW, and I unable to connect with ftp://IP_Address.
I need some extre options, or username&password?
What i missed?

Thanks if you or anybody can help hold my home and family :).

![Screenshot_20230705_214702_Home Assistant](https://github.com/AlexxIT/XiaomiGateway3/assets/77073590/22cf5df0-8323-4246-93f9-4fbcb698662b)
![Screenshot_20230705_214656_Home Assistant](https://github.com/AlexxIT/XiaomiGateway3/assets/77073590/adb6a21a-d120-4ec5-bf75-72aac287ed43)

**Comment by AlexxIT** [comment]
I don't understand your language on screens. Maybe you have selected "reboot gateway". Because you don't need any credential for connecting to FTP.

**Comment by gyenesadam** [comment]
I selected the "FTP access" row, then the GW goes unavailable for a few minutes.
I tried it many times, triex reset, and reinstall everything, what is in connection the GW, and the HA connection.

The problem is the same.

**Comment by AlexxIT** [comment]
You need to collect debug logs

**Comment by gyenesadam** [comment]
Enabled log, then try to send FTP enable cmd:

Ez a hiba egy egyéni integrációból lett származtatva.

Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/shell/base.py:41
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 14:37:45 (2 occurrences)
Last logged: 15:27:48

192.168.1.220 | Can't run telnet command: ftp
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 209, in telnet_send
    await sh.run_ftp()
  File "/config/custom_components/xiaomi_gateway3/core/shell/shell_mgw.py", line 37, in run_ftp
    if await self.check_bin("busybox", MD5_BUSYBOX, URL_BUSYBOX):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 93, in check_bin
    await self.exec("killall " + filename)
  File "/config/custom_components/xiaomi_gateway3/core/shell/base.py", line 41, in exec
    raw = await asyncio.wait_for(coro, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 634, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes

**Comment by AlexxIT** [comment]
You can try latest master version

**Comment by gyenesadam** [comment]
Exellent, works perfectly, thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.2
