### ISSUE TITLE
BLE LYWSDCGQ/01ZM

### ISSUE THREAD

**Issue by Sleinous** [AlexxIT/XiaomiGateway3#11]
Thanks for adding BLE support, I was running previous version (so I followed your instructions of rebooting my gateway - I just powercycled it).
I have the exact setup you tested, i.e. Gateway v3 with 3 of the temperature sensors (LYWSDCGQ/01ZM) but am unable to see any of these devices in Home Assistant !
Have also tried removing the integration and the repo entirely and rebooting HA each time, no luck as of yet.
As far as I understood, you've added BLE support using exactly the same test hardware.

![image](https://user-images.githubusercontent.com/33639239/92395638-ef59a380-f123-11ea-9638-6e4ba6421928.png)

**Comment by hoangtridung** [comment]
The same issue,  unable to see any devices in Home Assistant

**Comment by Mantoui** [comment]
The same issue, unable to see any devices in Home Assistant

**Comment by AlexxIT** [comment]
Devices don't appear immediately. You need to wait for them to start sending data

**Comment by Sleinous** [comment]
Hi there, it’s now been 36hours and still nothing.
My gateway is definitely retrieving information from BLE devices as it’s updating temps and humidity from time to time in Xiaomi Home app.

**Comment by Sleinous** [comment]
Same results with v0.2.3, have left it 12hrs now - fw 1.4.6_0012

**Comment by viiy** [comment]
I have 3 LYWSD03MMC and 2 LYWSDCGQ;
All LYWSD03MMC near rpi4, so it works by rpi4 bluetoth (mitemp_bt)
Through this integration, I can see all devices, but it does not work as expected; The temperature and humidity are rarely updated, sometimes it ceases to be displayed at all, the battery status is not displayed at all.

**Comment by mbratukha** [comment]
I have only one **LYWSD03MMC** and it's being recognized in ca. 5 minutes after restart of HA.
The only thing is: the first comes the temperature, but it takes much longer until the humidity data appears.
In general data comes very rare and in non-consistent time intervals.

It would be nice to have battery status.

**Comment by AlexxIT** [comment]
Fix in latest master version. I have not tested it for stability yet

**Comment by Sleinous** [comment]
@AlexxIT Thanks for your continued troubleshooting :) Have just switched to master branch and testing, left it a few hours now - for now BLE temp & humidity sensors (LYWSDCGQ/01ZM) aren't showing yet.

**Comment by Sleinous** [comment]
@AlexxIT 
Successfully discovered all devices (LYWSDCGQ/01ZM) in v0.2.4 👍 
![Screenshot_20200912-054954_Home Assistant](https://user-images.githubusercontent.com/33639239/92986526-e36f3800-f4bb-11ea-85e0-18321c93669c.jpg)
![Screenshot_20200912-055002_Home Assistant](https://user-images.githubusercontent.com/33639239/92986531-ecf8a000-f4bb-11ea-8f89-b516d5641f02.jpg)
![Screenshot_20200912-055010_Home Assistant](https://user-images.githubusercontent.com/33639239/92986535-f3871780-f4bb-11ea-924b-2bc7c66e672c.jpg)
From my sode this issue can be closed, thanks for your help !!

**Comment by viiy** [comment]
My 2 LYWSDCGQ and 3 LYWSD03MMC still not work properly;
1 LYWSDCGQ and 1 LYWSD03MMC not display any data.
Other devices update information every 30-60 minutes.(

**Comment by mbratukha** [comment]
I can confirm better behavior of LYWSD03MMC sensor for me with the latest version (0.2.4):

- Sensor data is coming more quickly
- The device become available much quickly after restart of HA
- The battery state is coming now!!! I'm not sure whether it's correct, because the device is used for 8 months and the battery should definitely be less then 100%:
![image](https://user-images.githubusercontent.com/1413357/92994285-619dff80-f4f9-11ea-8cf2-d7603f7beaad.png)

**Comment by Sleinous** [comment]
My batteries are at 65 and 67% so it does seem to be capturing data from the device for me

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexxIT** [comment]
Some one still have a problems?

**Comment by viiy** [comment]
> Some one still have a problems?

Yes. https://github.com/AlexxIT/XiaomiGateway3/issues/11#issuecomment-691416775

**Comment by AlexxIT** [comment]
@viiy are you using latest version v0.2.4?

**Comment by viiy** [comment]
yes, 
restart many times, 
turned off mitemp_bt,
all devices online at mi home

all LYWSD03MMC connected to gateway directly
1 LYWSDCGQ connected through YLXD02YL and CJXJSQ02ZM
1 LYWSDCGQ connected  through YLXD05YL
now both LYWSDCGQ not work  

all LYWSD03MMC and LYWSDCGQ in devices list, but only 2 LYWSD03MMC display data

**Comment by AlexxIT** [comment]
@viiy enable debug mode, described in readme. `debug: true` will be enought. And check logs

**Comment by viiy** [comment]
> @viiy enable debug mode, described in readme. `debug: true` will be enought. And check logs

[xg3.log](https://github.com/AlexxIT/XiaomiGateway3/files/5217787/xg3.log)

**Comment by AlexxIT** [comment]
@viiy I see problem #24 
Will fix it. But it may take time

**Comment by AlexxIT** [comment]
Check release v0.3.0

**Comment by viiy** [comment]
Update 1h ago.
Now, no "Bluetooth loop error: 'mac'" in log.
the last LYWSDCGQ is now working and it showed up as a new device, so there is now one more device in my devices list than I have.
the latest LYWSD03MMC is still not available, I also reconnected it in mihome but it doesn't help

**Comment by AlexxIT** [comment]
@viiy I see in your logs only 3 devices: `'blt.3.13cfk4ua0lk00', 'blt.3.13c5cf2so5s00', 'blt.3.13c4b6o0slo00'`

**Comment by viiy** [comment]
@AlexxIT but i have 5 in mi home.
Now 4 in ha, but only 3 LYWSDCGQ  which are connected directly to gateway works well

**Comment by viiy** [comment]
@AlexxIT 
my hypothesis was confirmed.
only devices in the coverage area of the gateway work.
devicese which connected throuth YLXD05YL, YLXD02YL, CJXJSQ02ZM - not work

**Comment by rezmus** [comment]
if sensor is not in gateway covarage it knows nothing about it, which means you cant pull any data for such sensor.

**Comment by viiy** [comment]
this is the most discouraging news ...

**Comment by Sleinous** [comment]
Yes those devices aren't Xiaomi Gateway V3, they are different brands/devices - you'd have to find an integration/custom component for the BLE/Zig gateway functionality they provide in order to grab the data back off them. Other option would just be to buy a 2nd Xiaomi Gateway V3 if the dependant devices are too far away to link to the first Xiaomi Gateway V3 you already have ;)
@AlexxIT Ever since v2.3 everything is running fine for me now, just added a 4th temp humidity sensor and temp/humid/battery data pulled through within abotu 5 minutes (battery is always slowest)
All working great ! Thanks a million again, if noone else has same issue as me this can now be closed
