### ISSUE TITLE
Xiaomi TH Sensor 2 (LYWSD03MMC) is stuck

### ISSUE THREAD

**Issue by freeball155** [AlexxIT/XiaomiGateway3#110]
Hello.
I have several sensors from subject. I noticed that from one of them the readings to the HA stopped coming. However, in the Mi Home app and on the screen, it continues to show the correct values. I restarted the HA and the gateway, as well as the sensor itself (took out and inserted back the battery). Did not help. Other similar sensors work fine.

What can be done? Collect debug? I wanted to clarify with which option to launch debug: true or bluetooth?

![Screenshot 2020-11-17 at 13 41 44](https://user-images.githubusercontent.com/4979885/99388587-7d999500-28de-11eb-92e1-a3ae95806609.png)
![2020-11-17 14 09 49](https://user-images.githubusercontent.com/4979885/99388659-9a35cd00-28de-11eb-80c6-408db74b9e91.jpg)
![2020-11-17 14 09 42](https://user-images.githubusercontent.com/4979885/99388665-9bff9080-28de-11eb-8af6-6ac66f635f3a.jpg)

**Comment by freeball155** [comment]
I "solved" the problem. 

I have two gateways - one in the main house (192.168.88.104) and one in another building (192.168.88.190). The sensor is located in another building closer to the gateway with IP 192.168.88.190. The distance between buildings is large enough (~30 meters). However, both gateways seem to see messages from this sensor. At least this follows from the logs that I collected:

2020-11-17 14:15:00  DEBUG    gateway3      192.168.88.190 | gateway <= {'online': True}
2020-11-17 14:15:00  DEBUG    gateway3      blt.3.14kb04hj8lk00 retain: {'humidity': 53.2, 'temperature': 10.2, 'battery': 100}
2020-11-17 14:15:00  DEBUG    gateway3      192.168.88.104 | gateway <= {'online': True}
2020-11-17 14:15:00  DEBUG    gateway3      blt.3.14kb04hj8lk00 retain: {'temperature': 5.7, 'battery': 100, 'humidity': 68.1}

2020-11-17 16:17:13  DEBUG    gateway3      192.168.88.190 | Process BLE {'dev': {'did': 'blt.3.14kb04hj8lk00', 'mac': 'A4:C1:38:59:1B:76', 'pdid': 1371}, 'evt': [{'eid': 4102, 'edata': '1602'}], 'frmCnt': 60, 'gwts': 1605622632}
2020-11-17 16:17:15  DEBUG    gateway3      192.168.88.104 | Process BLE {'dev': {'did': 'blt.3.14kb04hj8lk00', 'mac': 'A4:C1:38:59:1B:76', 'pdid': 1371}, 'evt': [{'eid': 4102, 'edata': '1602'}], 'frmCnt': 60, 'gwts': 1605622633}

And it looks like one gateway, then what is further from the sensor, has saved the last and incorrect values. And, for some reason, only these values were displayed in HA. Although the correct values came from the second gateway at the same time.

I reboot the second gateway (192.168.88.104) which retain incorrect values and the problem went away.

I'll attach the debug logs just in case. Maybe you can see the root of the problem and be able to solve it.

[debug.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5554848/debug.txt)

**Comment by AlexxIT** [comment]
Component don't support BLE on two gateway in one Home Assistant. Because both gateway have same BLE devices with same ID. A lot of code needs to be rewritten to support. Will be in future versions.

**Comment by freeball155** [comment]
Is it enough to just turn off the BLE mesh gateway in the second gateway settings?

**Comment by AlexxIT** [comment]
You can turn off BLE option in HA. In this file `/config/.storage/core.config_entries`.
I have not programmed changing settings in the GUI yet.

**Comment by duckqu** [comment]
У меня такая же проблема, но только у меня один шлюз.
Есть два датчика LYWSD03MMC, с одного данные всегда приходят новые. Со второго не обновляются, но в Mi Home данные есть. 
Перезагружал интеграцию, не помогало, в логах были старые значения температуры и влажности.
Перезагрузил сам шлюз, датчики (вынув батарейки).
И данные со второго стали приходить, но вот уже с первого — нет 😂

Просто поменялись местами, не пойму что за магия. 

----------------
I have the same problem, but only I have one gateway.
There are two LYWSD03MMC sensors, new data always comes from one. They are not updated from the second, but there is data in Mi Home.
I rebooted the integration, it did not help, the logs had old values of temperature and humidity.
I rebooted the gateway itself, the sensors (removing the batteries).
And data from the second began to come, but from the first sensor - no 😂

They just changed places, I don't understand what kind of magic.
