### ISSUE TITLE
Question about device not working after multimode 2 firmware upgrade

### ISSUE THREAD

**Issue by MagicStarTrace** [AlexxIT/XiaomiGateway3#1112]
I clicked to upgrade the firmware to 1.0.6_0016, is there a way to roll it back?
After the firmware upgrade, all devices in HASS are unavailable.

Thank You!

**Comment by marceautw** [comment]
Xiaomi Multimode Gateway 2 FW: 1.0.6_0016 should work fine!!

<img width="511" alt="2023-07-27 23_43_59-設定 – Home Assistant" src="https://github.com/AlexxIT/XiaomiGateway3/assets/88045089/d0adea01-a049-41e4-86fa-b5f50c07d840">

**Comment by alexLBdesign** [comment]
![problem](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/231899a3-48be-4d85-80f0-376e39405417)
I have problem my hub is not CN it is EU version and it is not 03 it is 04 version. It is connected and HA can see attached Bluetooth Clock with Humidity/Temp sensor to this Hub but i have no data 
![problem 2](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/789a08e6-42e6-4aba-9e08-bf7ed8a30338)

Is this some bug?

**Comment by AlexxIT** [comment]
1.0.6_0016 supported. I don't know how to downgrade firmware

**Comment by Sp-Link** [comment]
> 1.0.6_0016 supported. I don't know how to downgrade firmware

   I seem to have encountered a similar problem.My recently installed Home Assistant and Xiaomi Gateway 3.I Follow the instructions to successfully connect to Xiaomi Multimode Gateway 2 (CN).But the devices connected to Xiaomi Multimode Gateway 2 (CN) do not show a connection.And the Xiaomi Smart Home Hub 2 Data and other data of Xiaomi Multimode Gateway 2 (CN) display an unavailable status.Attempting to switch to XiaomiGateway3 version, the problem still exists.Relevant information can be found in the picture.I hope this information is useful.

**Comment by alexLBdesign** [comment]
update from yesterday....just got small Xiaomi TH Sensor 2 Temperature and data from this device is presented in HA. Old device Xiaomi TH Clock Humidity does not give me data.

![interace](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/9b84b71e-1692-4161-845f-dfa895601ecc)
![model](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/24e1ce21-84f0-415a-af19-ed5524da53ce)
![ne radi](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/4bdc937a-9ec2-4e9f-a435-52b71a34b505)
![radi](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/95fb0584-d7d3-4635-896a-0bf3fb4d66da)
