### ISSUE TITLE
Add support Yeelight K series

### ISSUE THREAD

**Issue by HugoPresents** [AlexxIT/XiaomiGateway3#1114]
FYI, this convert works for me.

```
{
    12455: ["Yeelight", "K Series Single Wall Switch", "090615.switch.aksk1"],
    "spec": [
        Converter("switch", "switch", mi="2.p.1"),
    ],
}
```
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1559200/ba173213-2f40-4944-b563-30b8c5539fc6)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.3
