### ISSUE TITLE
Xiaomi Multimode Gateway 2 (EU) - Device model Wrong listed and connected devices does not show data

### ISSUE THREAD

**Issue by alexLBdesign** [AlexxIT/XiaomiGateway3#1115]
I have Xiaomi Smart Home Hub 2 aka lumi.gateway.mgl001 aka Xiaomi Multimode Gateway 2 (EU) aka **DMWG04LM**. Firmware version is: 1.0.5_0016. My Xiaomi Hub is EU version and my Mi account is location Germany.  I din`t have problems connect this device to HA but HA see this device as Xiaomi Multimode Gateway 2 **CN** and model gateway DMWG**03**LM, see the picture:

![post problem](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/e3093622-d66b-4ac4-a6b9-208e75f8297c)

On this Hub i have connected Xiaomi Temperature and humidity monitor clock, **model:** miaomiaoce.sensor_ht.o2.  HA see that I have this device connected to the Hub and during installation of the Hub ask me to add this Clock to the Board and to choose in which room it is (that is all fantastic) but after I choose everything the data never shows. 

![01](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/d02297f5-27db-4a0d-bf4e-58ac69599694)

![02](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/a4e3ff22-c686-498e-bf5b-c1649b7f2a02)

![03](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/17b63221-cc7c-463d-a894-2da6b13844b3)

Is this some minor Bug, is there chance to see the data of connected devices to the Hub in HA?

PS: I have Mikrotik as router and only with this Hub device I have change behavior. I have Xiaomi TV Box S (2nd Gen) and Xiaomi Mi Air Purifier 3H EU both on same WiFI, and they are working just fine but this hub can not be added to be static IP. It works, but he disappear from Leases table or just have status Waiting. If I choose to get IP from DHCP he works but get status Bound only after 15-20 minutes. All other devices get this status momentarily.

**Comment by AlexxIT** [comment]
Remove client ID setting in Mikrotik DHCP lease page.

**Comment by alexLBdesign** [comment]
I put Hub in the middle of the apartment keeping in mind that it will need to connect to week Bluetooth devices. Distance is less then 2 meters to Mi clock and maybe 6 meters from Mikrotik router. I can connect to MiClock (with my phone) from distance 7-8 meters and 2-3 walls inbetween. Clock is fine and it has good signal. I removed Client ID from Static configuration. You can see that status is waiting but device is working and i can ping it. Still no data from sensors.

![client id](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/7bdf5bf1-c429-4641-a662-b938b5b29432)

[xiaomi_gateway3-45a0b8cbc876627b97027cbd03b27116-Xiaomi Multimode Gateway 2 CN-bd5bf61c877bfa099b484cedd5b9746e.json (3).txt](https://github.com/AlexxIT/XiaomiGateway3/files/12209861/xiaomi_gateway3-45a0b8cbc876627b97027cbd03b27116-Xiaomi.Multimode.Gateway.2.CN-bd5bf61c877bfa099b484cedd5b9746e.json.3.txt)

**Comment by AlexxIT** [comment]
Well. You have China model `lumi.gateway.mcn001`. It shouldn't be a problem for integration, but anyway.

Latest firmware should be 1.0.6. Try to update.

**Comment by alexLBdesign** [comment]
I do not thinck  that i have CN version. Just check, my model is lumi.gateway.**mgl001** aka **ZNDMWG04LM**.

Mi home device token extractor
![model](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/dc2d8751-ef96-4ae6-9b1e-fca72ba15e47)

From Gataway Hub2 Original Box
![box](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/04067195-9f19-400f-afd9-90f514cfd7c8)

**Comment by alexLBdesign** [comment]
Just added new sensor Door and window sensor, Model: isa.magnet.dw2hl
One sensor is working (open close state), but light sensor is status unknown.

![Door and window sensor](https://github.com/AlexxIT/XiaomiGateway3/assets/19772043/0991ed13-34df-49bc-b3c2-4ef5e2c9b9e8)

Here is the log for debuging purposes
[Xiaomi Door_Window Sensor 2.txt](https://github.com/AlexxIT/XiaomiGateway3/files/12233414/Xiaomi.Door_Window.Sensor.2.txt)

**Comment by alexLBdesign** [comment]
> 

Does not giving me update for firmware. After checking it says you have the latest firmware.

**Comment by RaidentaylorFilipeLeite85** [comment]
> Just added new sensor Door and window sensor, Model: isa.magnet.dw2hl One sensor is working (open close state), but light sensor is status unknown.
> 
> ![Door and window sensor](https://user-images.githubusercontent.com/19772043/257624307-0991ed13-34df-49bc-b3c2-4ef5e2c9b9e8.jpg)
> 
> Here is the log for debuging purposes [Xiaomi Door_Window Sensor 2.txt](https://github.com/AlexxIT/XiaomiGateway3/files/12233414/Xiaomi.Door_Window.Sensor.2.txt)

This is happening to me too. Updated firmware to last version.

**Comment by teamfighter** [comment]
Let me subscribe to this thread. I have the same gateway, and lumi.sensor_motion.aq2 does not work correctly with it in HA.
It adds to Home Assistant, even works several times, but after that becomes unavailable.
Any thoughts?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
