### ISSUE TITLE
New lamp in MiJia doesn't show up in HA

### ISSUE THREAD

**Issue by waterdrop01** [AlexxIT/XiaomiGateway3#1116]
I have:
- "MiJia Multimode 2 gateway" 
- 3 Mijia LED controller

I first added 2 LED lamps to Mijia, and after added the Xiaomi Gateway 3 integration. 

It worked perfectly (lamps viewable both in Mijia AND HA).

I then added a 3rd LED lamp to Mijia. But this time it doesn't show up in HA.

Even if removing the integration and re-adding it in HA.

The controller of the 3rd lamp (left) is slightly different from the two first one (right):
![53e5c7f4d852b5e26f7665e9026fbf5d](https://github.com/AlexxIT/XiaomiGateway3/assets/47316824/d14a4133-2e56-4872-8cb1-4097396472b0)

Here is the view from Mijia:

![Screenshot_2023-07-31-14-28-37-45_89ed83f5c7ca8fa2c91fc75c50289338](https://github.com/AlexxIT/XiaomiGateway3/assets/47316824/0f3c7037-4e02-4f7c-840b-3695b7abbe0d)

And here is the view from HA:

![Screenshot_2023-07-31-14-38-11-60_c3a231c25ed346e59462e84656a70e50](https://github.com/AlexxIT/XiaomiGateway3/assets/47316824/355ecd13-d9d7-49ad-9610-657ba6a36a99)

Any idea how to make the 3rd lamp appear in HA?

Thanks a lot for your help!

**Comment by rezmus** [comment]
check model and ask for support.

**Comment by waterdrop01** [comment]
Thanks @rezmus for the suggestion.

Finally ended up working! Not sure what exactly helped, but after unpair/repair as well as delete/configure integration in HA, 3rd lamp showed up!

Closing then.
