### ISSUE TITLE
Request to support the fan-lamp

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#1117]
gateway firmware: v1.5.5_0006
![Screenshot_2023-08-02-21-59-14-127_io homeassistant companion android minimal-edit](https://github.com/AlexxIT/XiaomiGateway3/assets/105607530/72d88174-d518-428f-bab7-2b17235be4fe)
[debug.txt](https://github.com/AlexxIT/XiaomiGateway3/files/12241079/debug.txt)

**Comment by levkanm** [comment]
`{ 
    12385: ["Unknown", "Mesh Ceiling Fan Light", "xingh.light.fsd2"],
    "spec": [
        Converter("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", parent="light", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", parent="light", mink=2700, maxk=6500),
        MapConv("light_mode", "select", mi="2.p.4", parent="light", map={
            0: "Reading", 1: "Office", 2: "Night", 3: "Leisure", 4: "W", 5: "WY", 6: "Night Light", 7: "Y", 8: "None"}),
        Converter("fan", "switch", mi="3.p.1"),
        Converter("horizontal_swing", "switch", mi="3.p.3"),
        Converter("wind_reverse", "switch", mi="3.p.12"),
        BoolConv("natural_wind", "switch", mi="3.p.7"),
        MapConv("fan_level", "select", mi="3.p.2", map={
            1: "1", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6"}),
    ],
}`

**Comment by levkanm** [comment]
> Unfortunately, I don't have time for that. You can do it yourself

The converter has been prepared, please help me add it to the integration. Thank you.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
