### ISSUE TITLE
Formaldehyde Reading is Ten Times the Expected Value

### ISSUE THREAD

**Issue by Necroneco** [AlexxIT/XiaomiGateway3#1127]
I have a formaldehyde monitor (https://home.miot-spec.com/spec/fbs.airmonitor.pth02) (ble 1809)
and the values I'm getting in HA are actually ten times higher than expected. 

I attempted to make the following modification:

```diff
# mibeacon.py

        elif eid == 0x1010 and len(data) == 2:  # 4112
-           payload["formaldehyde"] = int.from_bytes(data, "little") / 100.0
+           payload["formaldehyde"] = int.from_bytes(data, "little") / 1000.0
```

It seems to work, but I'm not sure if this change is appropriate.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.3
