### ISSUE TITLE
请问能不能支持小米人体感应器2S

### ISSUE THREAD

**Issue by hunl1986** [AlexxIT/XiaomiGateway3#1128]
小米人体感应器2S只显示了篮牙的刷新时间，没有显示其它功能的实体，能不能更新一下？

**Comment by AlexxIT** [comment]
Ничего не понимаю

**Comment by Necroneco** [comment]
> 小米人体感应器2S只显示了篮牙的刷新时间，没有显示其它功能的实体，能不能更新一下？

Already supported. #1118
