### ISSUE TITLE
Unsupported gateway model - lumi.gateway.v3

### ISSUE THREAD

**Issue by saadsalmans** [AlexxIT/XiaomiGateway3#1134]
Home Assistant version 2023.8.4
Xiaomi Gateway 3 version 3.3.2 (4efeaee)

Name: Mi Gateway
Model: lumi.gateway.v3
Firmware: 1.4.1_176.0220

After entering the host, token and key (obtained from cloud), it says: 
Unsupported gateway model
<img width="569" alt="image" src="https://github.com/AlexxIT/XiaomiGateway3/assets/20137133/f4d73533-835f-4ef0-a9e8-c5872096d60e">

When I telnet the host manually, it says: 
Trying 192.168.1.xx...
telnet: connect to address 192.168.1.xx: Connection refused
telnet: Unable to connect to remote host

Nothing in HA or Integration logs.

**Comment by AlexxIT** [comment]
Your gateway model unsupported.

**Comment by vecihixtemp** [comment]
Is there any alternative method to add this gateway?

**Comment by AlexxIT** [comment]
Just read the documentation. The answer is in the first section
