### ISSUE TITLE
Opening the Aqara N200 lock using Gateway 3 from Home Assistant

### ISSUE THREAD

**Issue by DieMetRik** [AlexxIT/XiaomiGateway3#1147]
Hello!

I want to opening Aqara lock N200 (BLE) from Home Assistant.

At this moment N200 lock open throw Apple HomeKit.

I think link HomeKit <-> Gateway3 <-> N200

Is it possible to open lock without HomeKit?

I can collect logs, if you say how?
logs exchange Gateway3, BLE and HomeKit

**Comment by Sergey-SRG** [comment]
Ну как подвижки есть?

**Comment by AlexxIT** [comment]
That's technically impossible. The gateway is not involved in the lock control in any way. It can only get the lock status in real time.
