### ISSUE TITLE
cannot show any devices

### ISSUE THREAD

**Issue by onlysunjun** [AlexxIT/XiaomiGateway3#116]
the Xiaomi multi-mode gateway is connected through this plug-in,but the devices connoted to the gateway cannot be displayed.
the gateway is connected to a Xiaomi door lock and two smart switches via mesh bluetooth.
is it because of the firmware?
the

**Comment by AlexxIT** [comment]
What firmware do you have?

**Comment by onlysunjun** [comment]
1.4.7-0065

在 2020-12-18 17:00:29，"Alex X" <notifications@github.com> 写道：


What firmware do you have?

**Comment by AlexxIT** [comment]
Problem in firmware

**Comment by onlysunjun** [comment]
thx for your reply



--
发自我的网易邮箱手机智能版



在 2020-12-19 01:14:26，"Alex X" <notifications@github.com> 写道：


Problem in firmware
