### ISSUE TITLE
Request localized mija bluetooth mesh light group

### ISSUE THREAD

**Issue by cclucky1** [AlexxIT/XiaomiGateway3#1160]
Thanks to the author's integration can let me use mijia bluetooth mesh devices in homeassistant, but in the control of these lights can not do the lights turn on synchronously, it seems very strange, but in the xiaomi app through the light group can be solved by the inability to turn on the synchronization of the problem, may I ask the author has a plan for the light group to achieve the localization of control!

**Comment by AlexxIT** [comment]
#1016
