### ISSUE TITLE
Unable to add Mi Smart Home Hub

### ISSUE THREAD

**Issue by drieshabr123** [AlexxIT/XiaomiGateway3#1173]
Unable ot add my Mi Smart Home Hub to the Gateway3 integration.
Updated the firmware of my hub together with my temperature and humidity sensors, the hub is now running on firmware 1.5.5

Succeeded to connect with the hub using the Miio integration, but keep running into a wall when I try to use the Gateway 3 to get my data into HA. Adding the hub, entering host en token is not an issue, but I don't have the "key". 

error that pops up when I hit submit without defining anything in the key field: "Wrong open telnet command"

**Comment by AlexxIT** [comment]
#1057
