### ISSUE TITLE
Unable to control the access of the Linptech Sliding Window Driver WD1 to the homekit

### ISSUE THREAD

**Issue by nathen-wu** [AlexxIT/XiaomiGateway3#1174]
I have updated to version V3.3.3 and connected to HomeKit through the HomeKit controller. It can also display entities normally, but it cannot be controlled. It can be controlled normally in HA.

**Comment by Necroneco** [comment]
Since it can be controlled normally in HA, maybe the problem is not here?

try reboot the WD1 ? by press the button on the side of device.

**Comment by nathen-wu** [comment]
Thank you. The problem has been resolved. The reason is that I did not set the itinerary for WD1
