### ISSUE TITLE
The value of formaldehyde concentration in HA is ten times smaller than expected

### ISSUE THREAD

**Issue by Catfish-Y** [AlexxIT/XiaomiGateway3#1177]
My formaldehyde monitor ( https://home.miot-spec.com/spec/yuemee.airmonitor.mhfd1 ) shows the value of formaldehyde concentration ten times smaller than expected, after I upgrade xiaomigateway3 to v3.3.3.

Please check this bug.

Thanks.

**Comment by Necroneco** [comment]
due to #1130 ?

**Comment by micturkey** [comment]
Same issue to me.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.2
