### ISSUE TITLE
Devices are missing after the integrations with mi account

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/XiaomiGateway3#118]
Hello all 

I have installed the integration from a new HA, but now I can't view the devices after the integration set with mi home account as you can see in the image bellow 

![xiaomi gateway 3](https://user-images.githubusercontent.com/47602733/100385283-15535d80-301a-11eb-841a-1b303cdc2cba.png)

Is there any way to solve this issue ?

Thank you in advance for your help and best regards

**Comment by AlexxIT** [comment]
Cloud integration don't add devices. Check video in config section.

**Comment by MiAutomations** [comment]
> Cloud integration don't add devices. Check video in config section.

Thank you for your fast reply, but I also have tried with the token extracted from the cloud mi home integration account, and the devices still not appearing with the deleted of the account integration and the restarts needed .... Is there any thing to perform in order to solve this issue ? 

Thank you and bets regards

**Comment by AlexxIT** [comment]
Try reboot gateway

**Comment by MiAutomations** [comment]
Thank you for your support !!
I tried restart the gateway as mentioned by you, install and uninstall the integration re-add the gateway with the token , restar the HA  without success, the devices doesn't appear in the list ... and also the popup window with with the devices list after the integration with the token doesn't appear also ...

![xiaomi gateway 3-1](https://user-images.githubusercontent.com/47602733/100429905-f393be00-308d-11eb-808e-1cc58e32ccc1.png)

**Comment by Alxspb** [comment]
Тоже самое
Нет девайсов. Добавил mi account, затем добавил шлюз, как на видео из документации. Не отображаются подключенные к шлюзу девайсы, хотя они отображаются в mi home.
Рестарт пробовал.

**Comment by MiAutomations** [comment]
Sorry for your work and support I realized that I perform the last firmware update for the hub/gateway and this is the issue 

Thank you for your support

**Comment by Alxspb** [comment]
Same for me. Found message in extension debug logs.

**Comment by MiAutomations** [comment]
By the way is there any way to reverte the firmware update ? 

Thank you

**Comment by AlexxIT** [comment]
You all probably have latest unsupported firmware
https://github.com/AlexxIT/XiaomiGateway3/wiki

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
