### ISSUE TITLE
The component stopped working with BLE devices on Russian region servers

### ISSUE THREAD

**Issue by AlexQuaken** [AlexxIT/XiaomiGateway3#1180]
The component stopped working with BLE devices on Russian region servers, approximately two weeks after a global failure on Xiaomi servers. Meanwhile, BLE devices in MiHome are accessible, sensors transmit and update data, and data is also updating in the Mi Home app & Yandex Smarthome. The issue only pertains to transferring data to Home Assistant if the gateway and sensors are linked to Russian servers. If you switch the gateway to the China region and rebind the BLE sensors, everything works correctly, and the data is sent to Home Assistant.

**Comment by AlexxIT** [comment]
This is a Russian cloud bug. Not related to integration.
