### ISSUE TITLE
Add new linp Unknown BLE

### ISSUE THREAD

**Issue by samuelleung1009** [AlexxIT/XiaomiGateway3#1188]
[https://home.mi.com/webapp/content/baike/product/index.html?model=linp.senpres.ps1bb&videoPlayMode=1#/](url)

Hello, this sensor is connected through the Xiaomi Multimode Gateway , but I cannot find it in the device list of gateway 3. May I ask if I can increase support for it. thanks

**Comment by Necroneco** [comment]
#1192

**Comment by alexreddy78** [comment]
I can confirm, that sensor is not updating statuses in integration at all, it's always unavailable.  Any chances to get it working?

Regards
