### ISSUE TITLE
Always status Unknown (zigbee JTYJ-GD-01LM/BW)

### ISSUE THREAD

**Issue by ADMiNZ** [AlexxIT/XiaomiGateway3#1189]
Always status Unknown for device zigbee JTYJ-GD-01LM/BW

```
 },
   "device": {
      "type": "zigbee",
      "model": "lumi.sensor_smoke",
      "fw_ver": 4,
      "available": true,
      "decode_time": 1805,
      "encode_time": 57538,
      "entities": {
        "smoke_density": {
          "state": "0",
          "value": 0
        },
        "smoke": {
          "state": "unknown",
          "value": null
        },
        "battery": {
          "state": "73",
          "value": 73
        }
      },
```

**Comment by ADMiNZ** [comment]
The interesting thing is that the battery status displays and displays the Smoke Density status. But the main status of Smoke is always unknown

**Comment by ADMiNZ** [comment]
More information. The system transmits permanent status - unknown. That is, it constantly transmits the status, but does not display it correctly. After using the system (with a button or smoke), the status begins to be transmitted correctly

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant
