### ISSUE TITLE
Unable to discover the device

### ISSUE THREAD

**Issue by ivakorin** [AlexxIT/XiaomiGateway3#119]
When I try use integration after add device (second setup step), my gateway can't be discovered by miio and also become unavailability in MiHome.  
After gateway reboot (telnet or cable disconnect) it's availably for some time (i no counted time but about 5-10 min) then again i can't get access to device but i can connect trough telnet. 
When i try turn on pairing by Home Assistant GUI i got follow error: 
`miio.exceptions.DeviceException: Unable to discover the device x.x.x.x`
According to python-miio doc's (https://python-miio.readthedocs.io/en/latest/troubleshooting.html) it can be caused if use subnets, but i don't use subnets.
After delete of integration, no any gateway disconnections from mihome. 
Gateway firmware 1.4.4_0003

**Comment by AlexxIT** [comment]
Try update gateway via Mi Home. Check good firmware list in readme. Update only to supported firmwares.

**Comment by jmpaiva** [comment]
Hi, having the same issue, did you solve it?

**Comment by AlexxIT** [comment]
@jmpaiva try reboot gateway

**Comment by ivakorin** [comment]
> 
> 
> Try update gateway via Mi Home. Check good firmware list in readme. Update only to supported firmwares.

But my firmware is Ok, it's  v1.4.4_0003 and device PN is ZNDMWG03LM if I will be upgrade factory firmware, telnet will be closed it is right? 
And MiHome suggest update to v1.4.7_0065 but it's not supported firmware according readme. Therefore I lost a chance use your integration.

**Comment by rezmus** [comment]
usa region in mi home still has 1.4.6_0012. you can update from there or via telnet yourself.

**Comment by ivakorin** [comment]
So i have tried to switch to US and update of the firmware, but no any result also I have used telnet eventually lost a temper and have used this instruction https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/uart_recovery 
This fixed my issue. 
So i think my device had broken firmware from OEM, because as i understand it's not usual case.

**Comment by AlexxIT** [comment]
First firmwares don't work very well
