### ISSUE TITLE
Add ftd.light.ftdlmp (ble mesh)

### ISSUE THREAD

**Issue by spacex-3** [AlexxIT/XiaomiGateway3#1191]
https://home.mi.com/webapp/content/baike/product/index.html?model=ftd.light.ftdlmp

https://home.miot-spec.com/spec/ftd.light.ftdlmp

Hello, this light is connected through the Xiaomi Multimode Gateway 2, but I cannot find it in the device list of gateway 3. May I ask if I can increase support for it. thanks!!!

**Comment by AlexxIT** [comment]
You can try to add it yourself

**Comment by MisterCommand** [comment]
Added support for `ftd.light.ftdlmp` in version `3.3.6`. Please try it out!

**Comment by AlexxIT** [comment]
Thanks https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.6

**Comment by spacex-3** [comment]
thanks!!!

**Comment by wz69699** [comment]
Can you support [ftd.light.dsplmp](https://home.miot-spec.com/spec/ftd.light.dsplmp)?
