### ISSUE TITLE
After updating v3.3.4, my patch panel has become a light

### ISSUE THREAD

**Issue by 1105169500** [AlexxIT/XiaomiGateway3#1194]
![123](https://github.com/AlexxIT/XiaomiGateway3/assets/33370025/7d9a0958-e757-4f41-a9b0-6bd4a039d7fe)

**Comment by flyibeat** [comment]
solved #1197

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5
