### ISSUE TITLE
Sensors are unavailable after reboot HA in case of multiple hubs

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/XiaomiGateway3#12]
Probably the issue
https://github.com/AlexxIT/XiaomiGateway3/issues/4
was fixed partially.
I have 2 hubs in the same network.
Each hub has 2 devices - door and TH sensors.
Everything was correct after adding the integration.
But after rebooting all items from the second hub are unavailable.
I can remove all XiaomiGateway3 integrations, reboot HA and add them again - then everything works fine till next reboot.

**Comment by slydiman** [comment]
Still actual for 0.2.3
All devices of the second hub are unavailable after reboot HA.

**Comment by slydiman** [comment]
Hello. Is there any progress?

**Comment by slydiman** [comment]
Still actual for 0.3.2
Did you receive the second hub?
Do you need any help, logs, testing?
It is really show stopper for me. 
I cannot drop HomeKit integration and use this one because it does not work with the second hub. 
I cannot reconfigure the integration for the second hub after each HA reboot.
Please fix it.

**Comment by AlexxIT** [comment]
Yes, I got a second hub. Have not dealt with the problem yet.

**Comment by slydiman** [comment]
Thanks! It seems fixed.

**Comment by obiwandeath** [comment]
Hello! Is there support for mesh lamps in the latest update?
