### ISSUE TITLE
Xiaomi Multimode Gateway 2 (CN) FW 1.0.7_0019 just auto updated and fail : (

### ISSUE THREAD

**Issue by felix0324324** [AlexxIT/XiaomiGateway3#1201]
<img width="631" alt="image" src="https://github.com/AlexxIT/XiaomiGateway3/assets/16462532/180b7430-059e-4b3e-b178-7a8a9ec2cfd8">

Is there any update for this FW please?

**Comment by wangyh-thss** [comment]
+1.

I noticed that #1166 fixed the issue for who has the key (i.e., has integrated the gateway previous, to my understanding). While I just got the new gateway device, with the FW 1.0.7_0019, so I guess there is no way to added it to HA for now?

Is there any plan to support this scenario?

Thanks!

**Comment by AlexxIT** [comment]
#1166

**Comment by AlexxIT** [comment]
It can't be any plans because Xiaomi close the way to open telnet without key

**Comment by wangyh-thss** [comment]
> It can't be any plans because Xiaomi close the way to open telnet without key

Thanks for the response, then I guess I need to buy a new one with supportted FW version. :-(
