### ISSUE TITLE
Fix control problem for Aqara Smart Ceiling Light L1-350 (ZNXDD01LM)

### ISSUE THREAD

**Issue by garry0garry** [AlexxIT/XiaomiGateway3#1209]
Aqara zigbee ZNXDD01LM (lumi.light.acn003) fw.28
Gateway DMWG03LM (MGW2) fw 1.0.7_0019
Component [XiaomiGateway3](url=https://github.com/AlexxIT/XiaomiGateway3) v3.3.4
Home Assistant 2023.11.2

The component reads the ZNXDD01LM data correctly, but any attempts to control brightness or color are unsuccessful. It can only be turned on or off.

Attached is a log with debugging data. Like the example "22023-11-11 13:31:31.378", "2023-11-11 13:31:45.457", "2023-11-11 13:31:48.877", where the log seems a little strange, but maybe I'm wrong. Please review and, if possible, make corrections to the component if required.

[home-assistant_xiaomi_gateway3_2023-11-11T10-33-35.126Z.zip](https://github.com/AlexxIT/XiaomiGateway3/files/13328929/home-assistant_xiaomi_gateway3_2023-11-11T10-33-35.126Z.zip)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5
