### ISSUE TITLE
    New Xiaomi Multimode Gateway 2 Error opening telnet command

### ISSUE THREAD

**Issue by lwsxhy8023** [AlexxIT/XiaomiGateway3#1210]
Xiaomi Multimode Gateway 2 Firmware Version 1.0.7_0019
Checked out the latest firmware version v3.3.4 
I was told that it is only possible if there is a secret key, and the location of the secret key file is also given, but I have purchased a new Xiaomi Multimode Gateway 2 and upgraded the firmware without connecting to homeassistant, and there is no secret key in the file.

File location
/config/.storage/core.config_entries
/config/.storage/xiaomi_gateway3/keys.json

I can't find the secret key in

Please give me a way to deal with this, thank you!

**Comment by lwsxhy8023** [comment]
Maybe the Obtain Mi Home device token version is too low and there is no secret key after getting it.

**Comment by AlexxIT** [comment]
There is no solution for your situation right now.
