### ISSUE TITLE
Xiaomi multimode gateway2 "wrong_telnet" error(upgrade the firmware version to 1.0.7_0019)

### ISSUE THREAD

**Issue by hsoybean** [AlexxIT/XiaomiGateway3#1214]
Xiaomi multimode gateway2, upgrade the firmware version to 1.0.7_0019, the keys.json file cannot be found in /config/.storage/xiaomi_gateway3, HA xiaomi gateway 3 integrates and adds Xiaomi Smart Home Hub 2 devices, and show "wrong_telnet" Error message, gateway device cannot be added. How to solve this problem?

**Comment by AlexxIT** [comment]
#1166
