### ISSUE TITLE
Is there a solution now？

### ISSUE THREAD

**Issue by chenweilawyer** [AlexxIT/XiaomiGateway3#1215]
If I didnot connect my Xiaomi Multimode Gateway 2 into HA before and I have a new device with firmware 1.0.7_0019 ... There is no solution to solve the problem of telnet ?

_Originally posted by @SMALLPIGCHANG in https://github.com/AlexxIT/XiaomiGateway3/issues/1166#issuecomment-1805076963_

**Comment by AlexxIT** [comment]
Nothing changed. All answers in original issue
