### ISSUE TITLE
 Mesh HVAC Climate converters problem

### ISSUE THREAD

**Issue by Joee-D** [AlexxIT/XiaomiGateway3#1216]
I just bought a mesh HVAC, it may be the first mesh HVAC(Climate) in Mijia.
And I try to use the gateway3 converters to access into the HA. But I  got some problems.

the spec is this [https://home.miot-spec.com/spec/scdvb.aircondition.acm](https://home.miot-spec.com/spec/scdvb.aircondition.acm)

I create a xiaomi_gateway3.py
```
from custom_components.xiaomi_gateway3.core.converters.devices import * 
DEVICES` = [{
    14050: ["Scdvb", "Air Conditioner", "scdvb.aircondition.acm"],
    "spec": [
        Converter("climate", "climate", mi="2.p.1"),
        MapConv("hvac_mode", mi="2.p.2", map={0: "cool", 1: "heat", 2: "fan", 3: "dry"}, parent="climate"),
        MapConv("fan_mode", mi="3.p.1", map={0: "auto", 1: "low", 2: "medium", 3: "high"}, parent="climate"),
        MathConv("current_temp", mi="4.p.1", min=0, max=70, round=1, parent="climate"),
        MathConv("target_temp", mi="2.p.3", min=16, max=32, round=1, parent="climate"),
    ],
}] + DEVICES 
```

## Question 1:
the HVAC status is alway on in HA
as there is no 'off' option in the 'hvac_mode' param, it use the 'mi="2.p.1' to describe this status.
the device report the status 'off' first and then report the 'hvac_mode'.
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/32849562/89eaaf73-f06b-4f4c-b836-7f2868c9c28f)

Log 1:
2023-11-23 22:12:50.433 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.1.11 [MQTT] miio/command_ack b'{"id":1027205188,"result":[
{"did":"1096534363","siid":2,"piid":1,"value":false,"code":0,"ts":1700748610,"ret":0},  //status: off
{"did":"1096534363","siid":2,"piid":2,"value":0,"code":0,"ts":1700746283,"ret":0}, //hvac_mode: cool
{"did":"1096534363","siid":3,"piid":1,"value":0,"code":0,"ts":1700746283,"ret":0},
{"did":"1096534363","siid":4,"piid":1,"value":24,"code":0,"ts":1700746282,"ret":0},
{"did":"1096534363","siid":2,"piid":3,"value":26,"code":0,"ts":1700746283,"ret":0}]}'

* I want to know how to make the 'mi="2.p.1' as a part of the 'hvac_mode' as 'off' option? 

## Question 2:
* I add {0: "cool", 1: "heat", 2: "fan", 3: "dry"} to the HVAC , but there are still only three hvac_modes in the HA. And I cannot change the hvac_mode or change the target_temp, and there is no logs.
accessed with gateway3:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/32849562/c461bfb1-6074-4791-8389-ff12732ed83b)
accessed with miiot auto:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/32849562/e5a6f583-682e-40a2-9a26-2aedb3542f3f)

I know the climate type device is rare in this project, but I still want to access it  to HA if possible. Thanks.

**Comment by Joee-D** [comment]
It seems that I can refer to the ClimateConv function to make a cpoy or refactor it. I will try later.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
