### ISSUE TITLE
Support lumi.sen_ill.agl01 (GZCGQ11LM)

### ISSUE THREAD

**Issue by ileodo** [AlexxIT/XiaomiGateway3#1220]
I have a GZCGQ11LM light sensor that has been paired with the gateway(lumi.gateway.mgl03) successfully, however the device doesn't show up in the list. 

I tried search all the logs, there is nothing error etc.
the only logline looks relevant is:

```
2023-11-25 17:33:22 [D] 192.168.1.xxx [BASE] 0x54ef4410008ed7d6 (0x2a4e) setup zigbee (lumi.sen_ill.agl01):
```

Could anybody help? Thanks

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5
