### ISSUE TITLE
Can you support LinpTech KE1BB-W2? Now I only can see some action log.

### ISSUE THREAD

**Issue by xiaodongyichuan** [AlexxIT/XiaomiGateway3#1224]
![微信图片_20231128172312](https://github.com/AlexxIT/XiaomiGateway3/assets/26026825/1ad7eaba-608b-43ae-9308-6b0c5c2853be)

**Comment by xiaodongyichuan** [comment]
linp.remote.k9b11

**Comment by xiaodongyichuan** [comment]
pdid is 5481

**Comment by xiaodongyichuan** [comment]
in log files, left SINGLE is 0, left switch SINGLE is 1, Left And Right Button SINGLE is 2, 
left DOUBLE is 131072, left switch DOUBLE is 131073,
left HOLDis 65536, left switch HOLD is 65537,Left And Right Button HOLD is 65538,

**Comment by AlexxIT** [comment]
Looks like you already has converter for this device

**Comment by xiaodongyichuan** [comment]
> Looks like you already has converter for this device

But there is not automation option in automation

**Comment by xiaodongyichuan** [comment]
> > Looks like you already has converter for this device
> 
> But there is not automation option in automation

i add some converter in config , it only show right device name, other is not work

**Comment by AlexxIT** [comment]
If you want automation options, you should program them.

**Comment by xiaodongyichuan** [comment]
> If you want automation options, you should program them.

Means program them in "class MiBeaconConv(Converter):"?
 
Thanks

**Comment by xiaodongyichuan** [comment]
> 1. Hass can't autodetect all triggers for some specific devices. Developers needs to add all possible triggers manually via code like this: https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/device_trigger.py
> 
>     2. It's not necessary to add this code, because any user can write automations with simple entity state triggers

I know your means, I have set it well, thanks very much.

**Comment by chaucern82** [comment]
@xiaodongyichuan Please give me your code ,I have the same problem with the Linptech Bluetooth Wireless Switch (3 Keys), PID 3581, chaucern@163.com, thank you

**Comment by chaucern82** [comment]
@xiaodongyichuan Please give me your code ,I have the same problem with the Linptech Bluetooth Wireless Switch (3 Keys), PID 3581, chaucern@163.com, thank you

**Comment by xiaodongyichuan** [comment]
> @xiaodongyichuan Please give me your code ,I have the same problem with the Linptech Bluetooth Wireless Switch (3 Keys), PID 3581, [chaucern@163.com](mailto:chaucern@163.com), thank you

这不需要写代码，你看一下你按按键的时候在设备页面的日志里面有没有对应的状态变化，设置自动化的时候选择实体状态，填写对应的日志状态变化数值就可以啦。

**Comment by chaucern82** [comment]
明白了，非常感谢@xiaodongyichuan

**Comment by AlexxIT** [comment]
Probably automations will be simplier in next version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
