### ISSUE TITLE
请求大佬支持小米6500pro路由器内置网关

### ISSUE THREAD

**Issue by pengyongsong** [AlexxIT/XiaomiGateway3#1230]
请求大佬支持小米6500pro路由器内置网关，领普人体存在传感器接入的6500pro路由器内置网关，gateway3上发现不了内置网关

**Comment by wdmywm3** [comment]
内置的是中枢网关，中枢本来就无法接入，不行的

**Comment by AlexxIT** [comment]
I don't understand anything.
