### ISSUE TITLE
Is there any plan to support the built-in gateway in xiaomi.controller.86v1?

### ISSUE THREAD

**Issue by wdmywm3** [AlexxIT/XiaomiGateway3#1239]
xiaomi.controller.86v1 is one of the newest 3-key switch with screen and a built-in bluetooth mesh gateway. Here is the miot-spec [link:xiaomi.controller.86v1](https://home.miot-spec.com/s/xiaomi.controller.86v1)
Is there any plan to support the built-in gateway in xiaomi.controller.86v1? It seems to have the same function as the multimode gateway.

**Comment by AlexxIT** [comment]
There are no plans to support Xiaomi gateways. The integration only supports gateways developed by Lumi (for Aqara and Xiaomi brands).
