### ISSUE TITLE
090615.remote.btsw1 Is Not Work

### ISSUE THREAD

**Issue by kiruya1987** [AlexxIT/XiaomiGateway3#1241]
I added the BLE Wireless Switch 090615.remote.btsw1 in the Xiaomi Gateway 3.
And try click the button , the BLE status is changed, but there is no action.
Could you please help to check and fix it?
https://home.miot-spec.com/spec/090615.remote.btsw1
Thank you.

<img width="1046" alt="image" src="https://github.com/AlexxIT/XiaomiGateway3/assets/30430286/e87537be-eb86-4bce-aca9-594b72a0e20f">

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3?tab=readme-ov-file#handle-button-actions
