### ISSUE TITLE
我有密钥，但是还是显示错误的打开telnet命令

### ISSUE THREAD

**Issue by 839924399** [AlexxIT/XiaomiGateway3#1244]
在网关1.0.3版本我保存了密钥
![31b6d173445aa0ed63b634a744dafbe](https://github.com/AlexxIT/XiaomiGateway3/assets/118901615/bf19aa0f-3031-4074-99c9-a24af81e42e3)
但是升级到1.0.7之后，通过密钥和token登录依旧显示错误的打开telnet命令，
![b25e8842aeb81a0f91a9904507dd7e6](https://github.com/AlexxIT/XiaomiGateway3/assets/118901615/c138d0c4-db60-453a-b30d-4b1bab128dc0)
同时Telnet 显示 wrong_telnet
该如何解决

**Comment by AlexxIT** [comment]
I don't understand anything

**Comment by jay1943000** [comment]
试下作者的这个办法 5-2-2-2-2-2-2
https://www.youtube.com/shorts/qJ21wWNE1Gg

**Comment by zxerqw** [comment]
> 试下作者的这个办法 5-2-2-2-2-2-2 https://www.youtube.com/shorts/qJ21wWNE1Gg

这个确实有效，但是默认有密码了，有密码吗？
