### ISSUE TITLE
Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

### ISSUE THREAD

**Issue by r-jean-pierre** [AlexxIT/XiaomiGateway3#1245]
Since the latest core update (2024.1.0b0), I get:
```
2023-12-28 15:16:01.463 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
2023-12-28 15:16:01.486 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
```

I had no issue before the update (12 different devices working well)

**Comment by LokiUA** [comment]
Same here. Core 2024.1.0b0 & 2024.1.0b1

`Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
Unable to prepare setup for platform 'xiaomi_gateway3.sensor': Platform not found (Exception importing custom_components.xiaomi_gateway3.sensor).`

`  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/sensor.py", line 42, in <module>
    "power": POWER_WATT,
             ^^^^^^^^^^
NameError: name 'POWER_WATT' is not defined`

`  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_gateway3/climate.py", line 14, in <module>
    HVAC_MODE_OFF: CURRENT_HVAC_OFF,
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined`

**Comment by fdmsh** [comment]
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 8:22:42 PM (1 occurrences)
Last logged: 8:22:42 PM

Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 8:22:42 PM (1 occurrences)
Last logged: 8:22:42 PM

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 14, in <module>
    HVAC_MODE_OFF: CURRENT_HVAC_OFF,
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined

**Comment by jeremysherriff** [comment]
HA Core 2024.1 is now here and this beta issue is now a reality in prod.

**Comment by LeandroIssa** [comment]
Same problem here!

**Comment by peerless0828** [comment]
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 上午11:36:06 (1 occurrences)
Last logged: 上午11:36:06

Unexpected exception importing platform custom_components.xiaomi_gateway3.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/sensor.py", line 42, in <module>
    "power": POWER_WATT,
             ^^^^^^^^^^
NameError: name 'POWER_WATT' is not defined



Logger: homeassistant.setup
Source: setup.py:403
First occurred: 上午11:36:06 (2 occurrences)
Last logged: 上午11:36:06

Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
Unable to prepare setup for platform 'xiaomi_gateway3.sensor': Platform not found (Exception importing custom_components.xiaomi_gateway3.sensor).

**Comment by paulopais** [comment]
Hi, the same problem..

**Comment by Lobo2022** [comment]
Hi, same problem.

**Comment by CMGeorge** [comment]
https://github.com/AlexxIT/XiaomiGateway3/pull/1246/commits/4d92d50f1488ed9f80d76e89e717b74da9710b66

This is fixing the problem for persons who dont want to rollback or wait.

**Comment by Chupaka** [comment]
To apply #1246 PR quickly, go to your .homeassistant directory and run
```
curl https://patch-diff.githubusercontent.com/raw/AlexxIT/XiaomiGateway3/pull/1246.patch | git apply --check -v
```
(to check that everything will be applied successfully) and then
```
curl https://patch-diff.githubusercontent.com/raw/AlexxIT/XiaomiGateway3/pull/1246.patch | git apply
```

**Comment by ErnestoBrandao** [comment]
for me it does not work :(
Thanks

**Comment by ErnestoBrandao** [comment]
Ok my mistake i was outside .homeassistant directory it WORKS
Thanks

**Comment by Lobo2022** [comment]
I applied #1246.  It works !

**Comment by paulopais** [comment]
Thank you :).. it work

**Comment by SK7WALKER** [comment]
how to apply? from file manager? ssh command line? tried from file manager-settings-run shell command- didnt change anything, from ssh i couldnt change directory

**Comment by paulopais** [comment]
I did it over ssh , i have haos

**Comment by SK7WALKER** [comment]
> I did it over ssh , i have haos

how did you change directory?

**Comment by paulopais** [comment]
cd homeassistant/
![Screenshot_2024-01-04-20-11-50-982_io.homeassistant.companion.android-edit.jpg](https://github.com/AlexxIT/XiaomiGateway3/assets/28353191/1c1a8fb2-9eec-4bbe-a8fa-f02d8ada796f)

**Comment by maddoglee** [comment]
I get this error... The patch looks like an email... is that right?

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/6965361/cb531a25-ff21-4284-863d-67f0774ea927)

**Comment by gcshum** [comment]
You forgot to use curl at the beginning of command.

**Comment by maddoglee** [comment]
> You forgot to use curl at the beginning of command.

Thanks, For some reason when I pasted into the terminal, it dropped the curl command and added a tilde ~ to the end of it... Hmm probably arising from using a mac... thanks for your quick reply though, I noticed the problem and tried to delete my comment, but you were too quick to reply!

**Comment by fulinsky** [comment]
@Chupaka Thank you for sharing!It does work.

**Comment by RikardzPT** [comment]
@Chupaka thank you

It works !

**Comment by jeremysherriff** [comment]
The patch has been merged and is available as part of the `master` branch.

To install it formally, use the "**Redownload**" option in the 3-dot menu in the HACS web interface:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1082213/c81d9ec3-0625-4cae-9a31-342ec02b9f1d)

..and choose `master` (**not** v3.3.4). 
Once downloaded, you will need to restart HA for the changes to take effect.

**Comment by ErnestoBrandao** [comment]
"master" asks for update and installs 3.3.4 and the error returns.

**Comment by jeremysherriff** [comment]
Sorry, yes that is correct. You should not upgrade.
I have updated my above comment:

> After restart, you will be prompted about a pending update (to v3.3.4) - do not upgrade until v3.3.5 is released. If further fixes are released in the meantime, just redownload `master` and restart again.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5
