### ISSUE TITLE
The command “fw_update” was not found.

### ISSUE THREAD

**Issue by zxerqw** [AlexxIT/XiaomiGateway3#1248]
Good day,

My DMWG03LM is currently on firmware version 1.0.3_0028. I’ve tried to upgrade it to mgl03_1.5.6_0001_mod20231031 via telnet, but it says the “fw_update” command was not found. Where should I find a “fw_update” program for it?

Or should I not upgrade the firmware at all? But there is always a chance I might accidentally hit the upgrade button every time I’m in the app.

**Comment by AlexxIT** [comment]
1. This is different gateway models.
2. I'm not writing custom firmwares for gateway.
