### ISSUE TITLE
Plugin Version 3.3.5: Lack of brightness and color temp of entities

### ISSUE THREAD

**Issue by catsimple** [AlexxIT/XiaomiGateway3#1254]
Plugin 3.3.4 with Hass 2023.12: no problem
![Screenshot_2024-01-05-23-28-42-908_io homeassista](https://github.com/AlexxIT/XiaomiGateway3/assets/23014926/82129b79-d2f2-4aa2-bc80-00e861e80af7)

Plugin 3.3.5 with Hass 2023.12 and Hass 2024.1: all brightness and temp of light entities are missing
![Screenshot_2024-01-05-23-26-46-762_io homeassista](https://github.com/AlexxIT/XiaomiGateway3/assets/23014926/07649031-2f49-4c6e-9e9a-17b7d6a5780c)

**Comment by catsimple** [comment]
list of my light entities:
mesh lemesh.light.wy0c15
mesh lemesh.light.wy0c08
unable to find brightness and temp attribute

**Comment by dylango** [comment]
same here
mesh lemesh.light.wy0c15

**Comment by avihome63** [comment]
The same for mesh MJTS01YL/MJTS003 by Xiaomi

**Comment by garry0garry** [comment]
I have the same problem with for Aqara Smart Ceiling Light L1-350 (ZNXDD01LM, lumi.light.acn003).

Xiaomi gateway DMWG03LM, fw 1.0.7_0019. Component v3.3.5. HA 2023.12.4.

**Comment by avihome63** [comment]
Hello, I rolled back locally changes from one of last commits, and bright and color temp starts working.

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/148702602/7f3946a3-0fdc-475a-9a69-ddc7cd3e4f3e)

Look's like it is early to switchover the deprecated constants

**Comment by kolegych** [comment]
Hi, created an MR with proposed changes by @avihome63

**Comment by n506** [comment]
same for YLTS02YL/YLTS04YL and mesh yeelink.light.mb1grp

**Comment by yuhuanfan** [comment]
same issue!!!

**Comment by DiukBogdan** [comment]
> Hello, I rolled back locally changes at 'light.py' that was introduced in one of last [commits ](https://github.com/AlexxIT/XiaomiGateway3/compare/d184d74fc2c52f1b33d22aa5fe3750ec7002b8d3...e9787e7c02b45d20a2147728e7f553a984fc87d3) in master, and bright and color temp starts working.
> 
> ![image](https://private-user-images.githubusercontent.com/148702602/294665418-7f3946a3-0fdc-475a-9a69-ddc7cd3e4f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTM2OTAsIm5iZiI6MTcwNTg5MzM5MCwicGF0aCI6Ii8xNDg3MDI2MDIvMjk0NjY1NDE4LTdmMzk0NmEzLTBmZGMtNDc1YS05YTY5LWRkYzdjZDNlNGYzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzE2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTFhZGIzZDdlOGQ0NTcwOWZkZWRkM2U0MjAxN2ZiZDczMDJhYmI4MzU4NjgzZTU1MzU3YmNkNjFhMWU1MjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hl_ZCIUvNKtL07QmBs5xobo-zwu-c7oJt7ZyNVRR1Ig)
> 
> 1. Get back wildcard import  `from homeassistant.components.light import *`
> 2. Rolled back line `self._attr_supported_features |= SUPPORT_BRIGHTNESS | SUPPORT_TRANSITION `
> 3. Rolled back line `self._attr_supported_features |= SUPPORT_COLOR_TEMP `
> 
> Look's like it is early to switchover from the deprecated constants to new ones

it worked for me. thanks

**Comment by sulliwane** [comment]
Same issue. With 3.3.5 all my BLE devices only had "ON/OFF" control (no more brightness or color control). 

I decided to remove and readd/reconfigure the gateway, even worse, now all my lamp entities don't have any controls, ex:
![Screenshot from 2024-01-24 00-42-52](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/453f2869-9eea-46be-8636-b950707519e6)

**Comment by sulliwane** [comment]
> Hello, I rolled back locally changes at 'light.py' that was introduced in one of last [commits ](https://github.com/AlexxIT/XiaomiGateway3/compare/d184d74fc2c52f1b33d22aa5fe3750ec7002b8d3...e9787e7c02b45d20a2147728e7f553a984fc87d3) in master, and bright and color temp starts working.
> 
> ![image](https://private-user-images.githubusercontent.com/148702602/294665418-7f3946a3-0fdc-475a-9a69-ddc7cd3e4f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTM4NjgsIm5iZiI6MTcwNjA1MzU2OCwicGF0aCI6Ii8xNDg3MDI2MDIvMjk0NjY1NDE4LTdmMzk0NmEzLTBmZGMtNDc1YS05YTY5LWRkYzdjZDNlNGYzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QyMzQ2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjYxYjMxZjlkNTY0MGYyNmE5MmMwMDVlZGQwYTkxZTVmZmQwNjFhYjY2ZmRiMzE5NjBhZDZlMDBmNDNjN2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JT1O6QV1dL09dU0XqrOiVlJlbkW_SfoVs0WDLT4AOhw)
> 
> 1. Get back wildcard import  `from homeassistant.components.light import *`
> 2. Rolled back line `self._attr_supported_features |= SUPPORT_BRIGHTNESS | SUPPORT_TRANSITION `
> 3. Rolled back line `self._attr_supported_features |= SUPPORT_COLOR_TEMP `
> 
> Look's like it is early to switchover from the deprecated constants to new ones

Do I need to restart HA after editing `light.py`?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.6

**Comment by sulliwane** [comment]
Thanks @AlexxIT! 

When will 3.3.6 be available within HA HACS page? I don't see any proposed update so far
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/c8388d60-30ec-4191-ba01-d5b72b5a8587)
