### ISSUE TITLE
With v3.3.5, all BLE Mesh bulbs are ON/OFF only, no brightness settings anymore

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/XiaomiGateway3#1261]
After updating to v3.3.5, all my Xiaomi BLE Mesh (M2 YLDP25YL) bulbs now lack brightness settings. Only On/Off. That's a big issue.

Downgrading to 3.3.4 does fix the issue.

**Comment by chertvl** [comment]
Duplicate of https://github.com/AlexxIT/XiaomiGateway3/issues/1254

**Comment by kolegych** [comment]
You can locally apply changes as in that MR https://github.com/AlexxIT/XiaomiGateway3/pull/1256

**Comment by tianzhuang55** [comment]
same here, looking forward to updates.
Thanks always to the contributors! Greeeeeeeat project!

**Comment by sergiogazprom** [comment]
Подтверждаю, у меня такая же история. Ждем обновления и спасибо за проект!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/1254
