### ISSUE TITLE
DMWG03LM / Xiaomi Multimode Gateway 2 (CN) / lumi.gateway.mcn001 (1.0.7_0019) not working

### ISSUE THREAD

**Issue by gusarov** [AlexxIT/XiaomiGateway3#1263]
Hub: Xiaomi Multimode Gateway 2 (CN)
Model: DMWG03LM
lumi.gateway.mcn001

Firmware: 1.0.7_0019

I bought it it in v1.0.7 (or may be upgraded the very first day). As a result, I don't see any way to connect it properly to HA. Any advice?
So far, I managed to enable telnet with "button click" trick (5-2-2-2-2-2), telnet works on 22 port, but no password is accepted, empty is not working either. Googling shows that it used to be possible to get password on older version of "Mi Hub" app in dev mode, but I doubt it works nowadays (2 years old info and app, nothing like that in current app).

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1462777/fc5c4928-5c1b-44a9-9d1f-060933adc351)

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1462777/da15d1a1-16aa-4b08-86c9-fc4ef385c9c3)
Token is properly auto-extracted and matches to token extractor.

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1462777/d8a076d2-26a9-4f9b-8c1d-bc3b6f2c5c0f)

When telnet is enabled it tries for much longer time, but still "Wrong open telnet command"

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/1462777/2cb0c644-298b-4553-aa7a-5b978ebc0c1e)

What is my options? Flush older firmware with UART? Try to find 2 years old Mi Hub with dev mode? Is my understanding correct that the telnet password here is the same as a key that integration requests or it is not related?

**Comment by AlexxIT** [comment]
#1166
