### ISSUE TITLE
BLE lock status randomly not tracked

### ISSUE THREAD

**Issue by saury** [AlexxIT/XiaomiGateway3#127]
First of all, thanks for developing this awesome plugin.
I'm using the latest version of HA and this component. BLE lock is Mijia Smart Door Lock Lite version and my gateway is in FW v1.4.5_0016.
Though this BLE lock seems not among the listed supported devices, I can still get actions for notifying 'Unlock' status. 
However, actions will not be triggered every time when unlock outside the door. The related info also not appear in debug mode.
I wondered if anyone else met this problem. And is there any solution towards that.

**Comment by AlexxIT** [comment]
Check distance from gw to lock. How many BLE gw do you have?

**Comment by saury** [comment]
They are all in my living room. But I've got another Mijia BLE socket near them. And I checked that this socket can also work as gateway, but not the mesh one as the gateway3 does. 
Will it be the root cause? As I fail to find any switch for disabling the BLE gateway function for this socket, how can I avoid it?

**Comment by mickey50** [comment]
Very similar to my question
https://github.com/AlexxIT/XiaomiGateway3/issues/138
I have only one xiaomigateway3 but have three yeelight lights can use as bluetooch mesh gateway

**Comment by mickey50** [comment]
@saury 
If move the lights to another account ,I think it can't be triggered by other devices in my account ,
looking forward to your test result 。

**Comment by saury** [comment]
@mickey50 
The door unlock status almost all tracked after I move the socket to another account. 
As I'm using HA for configuring all the automations,  it won't bring any inconvenience to me for currently.

**Comment by AlexxIT** [comment]
Interesting. I thought all devices get BLE data.

**Comment by mickey50** [comment]
Maybe I should move the automation from cloud to the HA too,thanks for your experience .

**Comment by saury** [comment]
@AlexxIT @mickey50 
Maybe I was wrong before. It turns out that this issue should be caused by official firmware. After running several days, the unlock status was still untracked randomly. Even automations related with my lock in mijia.app won't trigger also by the same time status untracked.
Anyone else meet this kind of issue, update your gateway to newer modified firmware(1.4.7_0065 in my case) or run ble dfu refer to [this url](https://github.com/niceboygithub/XiaomiGateway3fw).
