### ISSUE TITLE
Automatic reconnection issue

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#1278]
When the WiFi restarts, causing a brief disconnection of the gateway and rendering the device entity unavailable. Even after the gateway comes back online, the integration does not automatically reconnect to the gateway. Reloading the integration still fails to restore the connection; only restarting Home Assistant can restore the connection.

Homeassistant versions:2024.1.3
Gateway:Xiaomi Multimodal Gateway v1.5.6_0001

**Comment by n3o4po11o** [comment]
same issue

**Comment by sebastiankruk** [comment]
Same here.

**Comment by jeblove** [comment]
I have encountered the same issue. Whenever the WiFi restarts or when I click to reload "Gateway 3", it causes all device entities to become unavailable. 
Rebooting the gateway doesn't work either; I can only restart Home Assistant.

**Comment by AlexxIT** [comment]
This problem should be fixed in the next version
https://github.com/AlexxIT/Blog/issues/20

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
