### ISSUE TITLE
How to disable buzzer when switch alarm type

### ISSUE THREAD

**Issue by iapYang** [AlexxIT/XiaomiGateway3#1279]
Currently I Have a Xiaomi Multimode Gateway，model ZNDMWG03LM，verision 1.5.4

When I change the alarm type, like from alarm_away to alarm_night, the buzzer make sounds

Is there any way can I mute the buzzer when change the alarm type?

**Comment by AlexxIT** [comment]
Your task similar with this https://github.com/AlexxIT/XiaomiGateway3/issues/919
BUT. You should update lua code for your needs. I don't know what command gateway sends to buzzer on alarm change. You should find it yourself.

**Comment by iapYang** [comment]
Thanks a lot，i'll make a try

**Comment by sevenissimo** [comment]
Maybe [this](https://gist.github.com/sevenissimo/1b9712e9b9b8a0d28d5f61cbd4e60ec8) should help.

Not extensively tested, but it seems to work.

**Comment by iapYang** [comment]
@sevenissimo thanks a lot，I'll give a try
