### ISSUE TITLE
ERROR after trying to flash EZSP

### ISSUE THREAD

**Issue by LordArrin** [AlexxIT/XiaomiGateway3#1284]
gateway ZNDMWG03LM

ERROR after trying to flash EZSP custom or original - no matter

Tried to do it on 1.5.5_0006, 1.5.6_0001.

[xiaomi_gateway3-8b7e04a3f25a2b9a54e8fcc4c0c7cd1c-Xiaomi Multimode Gateway-39aa1397bf235ed29864ad26cbda8ed7 (1).json](https://github.com/AlexxIT/XiaomiGateway3/files/14323202/xiaomi_gateway3-8b7e04a3f25a2b9a54e8fcc4c0c7cd1c-Xiaomi.Multimode.Gateway-39aa1397bf235ed29864ad26cbda8ed7.1.json)
[home-assistant_xiaomi_gateway3_2024-02-18T15-40-24.782Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/14323206/home-assistant_xiaomi_gateway3_2024-02-18T15-40-24.782Z.log)

Home Assistant Core 2024.2.2
Home Assistant Operating System 12.0.rc1

**Comment by AlexxIT** [comment]
I don't see anything wrong with it. Try restart gateway and Hass and try again.
Also try to collect integration debug logs for this process.

**Comment by LordArrin** [comment]
[home-assistant_xiaomi_gateway3_2024-02-19T01-50-35.611Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/14325432/home-assistant_xiaomi_gateway3_2024-02-19T01-50-35.611Z.log)
original
[home-assistant_xiaomi_gateway3_2024-02-19T01-53-08.906Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/14325439/home-assistant_xiaomi_gateway3_2024-02-19T01-53-08.906Z.log)
custom

**Comment by AlexxIT** [comment]
I think something changed in the ZHA integration. This library used for detecting firmware version.
Your original and custom firmwares flashed OK. But code for detecting fw version doesn't works

**Comment by LordArrin** [comment]
Sooo... Can I you fix it? Or we need to wait for HA developers?

**Comment by LordArrin** [comment]
Good luck man!

**Comment by AlexxIT** [comment]
Luck doesn't have much to do with it. Just time. Free time

**Comment by AlexxIT** [comment]
Probably fixed https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0

**Comment by LordArrin** [comment]
![Screenshot_20240404-202944_Home Assistant](https://github.com/AlexxIT/XiaomiGateway3/assets/79581469/51ef7b25-57a4-486b-bd44-faf528c4dc21)
Yep, thanks!
