### ISSUE TITLE
Aqara Cube - The direction of rotation is not determined

### ISSUE THREAD

**Issue by theodorx7** [AlexxIT/XiaomiGateway3#1286]
HA 2024.2.2
Gateway firmware v1.5.5_0006 custom
Component v3.3.6

Regardless of the direction of rotation left or right, only one event is always displayed - rotation.
In this case, the rotation angle will be transferred correctly.

ROTATION RIGHT

![right](https://github.com/AlexxIT/XiaomiGateway3/assets/99128059/ba105765-7d70-4160-a23f-eca0c9536a97)

ROTATION LEFT

![left](https://github.com/AlexxIT/XiaomiGateway3/assets/99128059/e92dc0d9-bc94-4907-8219-064e29752b81)

**Comment by AlexxIT** [comment]
You right. Direction inside angle. Angle provided with action in single message.
