### ISSUE TITLE
The problem of identifying locks as door

### ISSUE THREAD

**Issue by Mcui7** [AlexxIT/XiaomiGateway3#1297]
Hi, my Aqara N200 lock (ZNMS17LM) has been identified as a door, and I am unable to determine whether the door is opening inward or outward. Is there a way for him to recognize it as a lock?

Xiaomi Multimode Gateway (CN) -ZNDMWG03LM
Firmwares 1.5.4_0090

I tried unlock inside the door, unlock outside the door, and lifting the door handle. But it still shows as door.
And there are only two states : Door is open  or Door is closed
But in miot, it can be seen that there are inside and outside

**Comment by Mcui7** [comment]
Xiaomi Multimode Gateway (CN) -ZNDMWG03LM
Firmwares 1.5.4_0090

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by Mcui7** [comment]
> Show device diagnostics

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.12.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Shanghai",
    "os_name": "Linux",
    "os_version": "4.4.302+",
    "run_as_root": true
  },
  "custom_components": {
    "xiaomi_gateway3": {
      "version": "3.3.6",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.15",
      "requirements": [
        "construct>=2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "codeowners": [
      "@AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "requirements": [
      "zigpy>=0.44.1"
    ],
    "version": "3.3.6",
    "is_built_in": false
  },
  "data": {
    "version": "6a494ae",
    "options": {
      "host": "***",
      "token": "***",
      "key": "CLzUi8SFG4Jotimt"
    },
    "errors": [],
    "device": {
      "type": "ble",
      "model": 1695,
      "fw_ver": null,
      "available": true,
      "decode_time": 3,
      "entities": {
        "action": "",
        "battery": {
          "state": "50",
          "value": 50
        },
        "contact": "off"
      },
      "gateways": [
        "54ef44cf1323"
      ],
      "unique_id": "f9479ba37cdc"
    },
    "logger": [
      {
        "ts": "2024-03-07T23:16:21.889",
        "type": "decode_mibeacon",
        "value": {
          "eid": 4106,
          "edata": "3244DAE965"
        }
      },
      {
        "ts": "2024-03-07T23:16:52.884",
        "type": "decode_mibeacon",
        "value": {
          "eid": 4106,
          "edata": "3263DAE965"
        }
      }
    ]
  }
}

**Comment by Mcui7** [comment]
Can the N200 device driver be defined as door, and can it be defined as lock to facilitate the identification of internal and external door openings

**Comment by Mcui7** [comment]
I have read this [page](https://github.com/AlexxIT/XiaomiGateway3/wiki/Converters), tried to add the converter:
[Aqara N200](https://home.miot-spec.com/s/lumi.lock.bzacn1)
```
DEVICES = [{
    1695: ["Aqara", "Door Lock N200", "ZNMS17LM"],
    "spec": [
        Converter("door", "sensor", mi="3.p.2"),
        Converter("lock", "binary_sensor",  mi="2.p.1"),
    ],
}] + DEVICES
```
The status of the lock has always been unknown
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/111735765/814c3591-1633-41ef-8513-f48e1bbdd02e)

**Comment by Mcui7** [comment]
Should I try changing` Converter("lock", "binary_sensor",  mi="2.p.1")` to `LockConv("lock", "binary_sensor",  mi="2.p.1")`?
I am not at home right now, so I cannot try it directly. That's why I'm asking first.

**Comment by AlexxIT** [comment]
Have you read? https://github.com/AlexxIT/XiaomiGateway3/wiki/Handle-BLE-Locks

**Comment by Mcui7** [comment]
Yes, I have read https://github.com/AlexxIT/XiaomiGateway3/wiki/Handle-BLE-Locks.
This lock was purchased in 2021, so it doesn't seem too old, right?
However, there are indeed few properties visible in miot...

Because I work with Java, reading Python code is a bit challenging for me.
I thought it was necessary to first map out the Lock device and then identify the status based on the corresponding action_id.

**Comment by AlexxIT** [comment]
Check this link https://home.miot-spec.com/s/lumi.lock.bzacn1
Lock from 2019 year. It sends data as events, not states.

**Comment by Mcui7** [comment]
Alright, it seems there isn't a way to add integration directly. I'll think of another way to work around this;
Thank you for the assistance provided.
