### ISSUE TITLE
How to add support for new devices

### ISSUE THREAD

**Issue by Tom0208** [AlexxIT/XiaomiGateway3#1298]
The same device cannot be controlled or set up when connected through XiaomiGateway3, but it can be fully displayed and controlled through Xiaomi Miot Auto.
![PixPin_2024-03-08_15-36-15](https://github.com/AlexxIT/XiaomiGateway3/assets/88831371/2337500f-2ceb-4fee-8ba3-4af49ea73fd2)
![PixPin_2024-03-08_15-36-31](https://github.com/AlexxIT/XiaomiGateway3/assets/88831371/cd7ae931-f034-4baa-a780-b6f89180f005)
![PixPin_2024-03-08_15-37-41](https://github.com/AlexxIT/XiaomiGateway3/assets/88831371/efd0c7da-5f0e-42f9-87dc-fdf45319967c)
![PixPin_2024-03-08_15-38-04](https://github.com/AlexxIT/XiaomiGateway3/assets/88831371/adc47fa1-e97d-4328-926d-7fd4e88b6d06)

**Comment by Mcui7** [comment]
You can read this [page](https://github.com/AlexxIT/XiaomiGateway3/wiki/Converters) and then try to configure it yourself.

**Comment by AlexxIT** [comment]
You should to writer converter like many other users. Check other issues.
