### ISSUE TITLE
Can support Xiaomi new Gateway ZSWG01CM ?

### ISSUE THREAD

**Issue by CHHHAN** [AlexxIT/XiaomiGateway3#1301]
Name is 小米中枢网关
This  gateway native support local control.
But it seems like can't connect to HomeAssistant with XiaomiGateway3.

![微信图片_20240311102748](https://github.com/AlexxIT/XiaomiGateway3/assets/52941464/0040297e-ebce-448a-8b24-3f4ffd688704)

**Comment by moonjunyan** [comment]
同样的问题。。。

**Comment by charliechan53** [comment]
same here... some device like mi wireless remote can't deploy viot miot but when using this gateway, gateway 3 is not support...

**Comment by AlexxIT** [comment]
#1036
