### ISSUE TITLE
The deleted Light Group is still displayed on Gateway3 with the status of Unavailable

### ISSUE THREAD

**Issue by cclucky1** [AlexxIT/XiaomiGateway3#1302]
After removing Light Group in mi home, there still exists a device Xiaomi Mesh Group in gateway3 plugin, it shows unavailable, restarting Home Assistant several times is invalid, sometimes adding Light Groups composed of different brands of lights do not show up in gateway3, in fact, they work fine in mi home! Works fine
Gateway used: Xiaomi Multimode Gateway 2
Firmware version: 1.0.3_0028
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/53963267/314b9c64-10fa-44db-a923-f6e0d7cddd2d)

**Comment by AlexxIT** [comment]
Try to delete them manually. Component didn't delete devices automatically.

**Comment by cclucky1** [comment]
Manual deletion works, but a new problem, I have four spotlights of the same brand and a strip light controller to form a Light Group, they work fine in the meter home, but won't show up in homeassistant unless I form the four spotlights into a Light Group without adding the strip light controller!
