### ISSUE TITLE
 Request to add support for the Telnet password of the gateway.

### ISSUE THREAD

**Issue by LOVE2CMOL** [AlexxIT/XiaomiGateway3#1304]
Hello

I checked the code and found that the Telnet password is hardcoded.
Additionally, the Telnet password for the gateway is empty, which can lead to a significant security risk. If someone gains access to my network environment or if my Wi-Fi password is compromised, they can easily enter the gateway and manipulate files and programs. It is highly insecure. If support for password compatibility can be added, I will be able to set a password for Telnet, greatly reducing the possibility of unauthorized file modifications.🤣

Thank you so much

![image](https://github.com/AlexxIT/XiaomiGateway3/assets/28857775/9e6534c5-002b-412d-a511-128d23ac88eb)

**Comment by AlexxIT** [comment]
#625

**Comment by AlexxIT** [comment]
I don't have plans to spent time on this.
