### ISSUE TITLE
PTX BLE Wireless Switch cannot be used normally

### ISSUE THREAD

**Issue by ARC-MX** [AlexxIT/XiaomiGateway3#1309]
When the PTX wireless switch is pressed, homeassistant cannot read the switch state. xiaomigetway3 shows' This entity is no longer being provided by the xiaomi_gateway3 integration. If the entity is no longer in use, delete it in settings.’
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/34829404/66559ed6-1a27-4f7d-9cc5-072f3247a863)

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by ARC-MX** [comment]
[xiaomi_gateway3-6d4f45eb86975739da6008732c92bb64-PTX BLE Wireless Switch-43e6caba41f22e6fd73352d7a6d33d9a-3.json](https://github.com/AlexxIT/XiaomiGateway3/files/15029001/xiaomi_gateway3-6d4f45eb86975739da6008732c92bb64-PTX.BLE.Wireless.Switch-43e6caba41f22e6fd73352d7a6d33d9a-3.json)

**Comment by AlexxIT** [comment]
I think the device is no longer in your gateway's database. I don't know why it might be missing.

**Comment by ARC-MX** [comment]
I think the reason is that the gateway3 plug-in does not support this device. PTX wireless switch is a substitute for Xiaomi button, which is normally used in Xiaomi APP

**Comment by AlexxIT** [comment]
But you have entities. So the gateway has seen this device before

**Comment by ARC-MX** [comment]
![Screenshot_20240419_202114.jpg](https://github.com/AlexxIT/XiaomiGateway3/assets/34829404/f600d96a-6126-4ada-80e5-a43213048677)

**Comment by AlexxIT** [comment]
You can restart Hass. Devices list loaded on integration start

**Comment by ARC-MX** [comment]
I tried it, but nothing changed, and I don't know if it's the problem with this PTX device

**Comment by ARC-MX** [comment]
I have fixed this bug. My Homeassistant is connected to the router, but the Mijia gateway is connected to other devices, although the same subnet, but there will be problems.

**Comment by AlexxIT** [comment]
Looks like problem solved
