### ISSUE TITLE
Multi-key switch only shows one switch

### ISSUE THREAD

**Issue by hyoukaija** [AlexxIT/XiaomiGateway3#1320]
<img width="837" alt="截屏2024-04-05 20 44 13" src="https://github.com/AlexxIT/XiaomiGateway3/assets/12975337/d67098d3-6293-46ad-9dba-34717dadac95">
My switch is a two-button switch, but only one is displayed. It was normal at first, but I started encountering this problem 1-2 months ago. Please tell me how to fix it

- Upgrading to 4.0.2 cannot solve the problem
- Restarting the device or re-adding the device cannot solve the problem.

**Comment by AlexxIT** [comment]
You need to write converter for your device

**Comment by hyoukaija** [comment]
How to do it?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#add-new-device

**Comment by hyoukaija** [comment]
The link above is very helpful, thank you very much, I attached my code, I hope it can be a reference for others
`
from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [
{
    # dual channel on/off, power measurement
    9610: ["bean", "Double Wall Switch", "bl02"],
    "spec": [
        BaseConv("channel_1", "switch", mi="2.p.1"),
        BaseConv("channel_2", "switch", mi="3.p.1"),
        BaseConv("led", "switch", mi="8.p.1"), 
    ],
},] + DEVICES
`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.3
