### ISSUE TITLE
Compiled MultiPAN RCP firmware (EZSP Firmware: 7.3.1.0 build 0)

### ISSUE THREAD

**Issue by zalatnaicsongor** [AlexxIT/XiaomiGateway3#1328]
Hello,
If it seems to be worthwhile to incorporate into this project, see my repo at https://github.com/zalatnaicsongor/MGLGWFW

### Instructions:
- download script.sh to /data/script.sh
- The baud of the multipan RCP firmware is 115200, the EZSP version is "Firmware: 7.3.1.0 build 0"
- Install the Silicon Labs Multiprotocol addon in HA or use a standalone `cpcd` instance
- execute the script, I tested it on the latest _custom_ version of the firmware.

### Home Assistant setup:

- Currently due to some weird bug in the `openmiio_agent` code, `cpcd` does not connect through the serial proxy provided by `openmiio_agent`, to work around the issue, use ser2net `/data/ser2net -d -C '7000:raw:0:/dev/ttyS2:115200 8DATABITS NONE 1STOPBIT'` 
- Note: ser2net is downloaded by the firmware update script
- Configure the Silicon Labs Multiprotocol addon with the following options:
```
device: /dev/ttyS2
baudrate: "115200"
flow_control: false
autoflash_firmware: false
cpcd_trace: true
otbr_enable: true
otbr_log_level: debug
otbr_firewall: true
network_device: {gatewayIP}:7000
stdout_trace: true
```
- ZHA should automatically discover the socket created by the multiprotocol addon, for zigbee2mqtt use `tcp://core-silabs-multiprotocol:9999`

**Comment by ztdan4ik** [comment]
> * Configure the Silicon Labs Multiprotocol addon with the following options:
> 
> ```
> device: /dev/ttyS2

I can't save add-on config with Device '/dev/ttyS2' 

`Failed to save add-on configuration, Device '/dev/ttyS2' does not exist in Silicon Labs Multiprotocol (core_silabs_multiprotocol). Got {'device': '/dev/ttyS2', 'baudrate': '115200', 'flow_control': False, 'autoflash_firmware': False, 'cpcd_trace': True, 'otbr_enable': True, 'otbr_log_level': 'debug', 'otbr_firewall': True, 'network_device': '192.168.1.174:7000', 'stdout_trace': True}
`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8

**Comment by FerrumLogic** [comment]
Could you please provide more detailed instructions for flashing this firmware?

**Comment by aluisperezh** [comment]
I need too an explanation of how to flash this too. Script provided doesn't work, it stops waiting for the receive comand on serial...

Thanks in advance.

**Comment by xeonxu** [comment]
> I need too an explanation of how to flash this too. Script provided doesn't work, it stops waiting for the receive comand on serial...
> 
> Thanks in advance.

You really should look at this project and have a try: https://github.com/Zhenia-l/XMG2
It's NCP though. But it's more stable then RCP one.
