### ISSUE TITLE
Can I add an occupancy_timeout parameter to a BLE motion sensor using the BLE number（model）?

### ISSUE THREAD

**Issue by flyibeat** [AlexxIT/XiaomiGateway3#1329]
for example，in configuration.yaml
//
xiaomi_gateway3: 
  devices:
    "13617":
      occupancy_timeout: 30
    "lumi.sensor_motion":
      occupancy_timeout: 60
    "e0798d2ce9dc":
      occupancy_timeout: 30
//
 Sensors defined by MAC address will take effect（ble）. And  sensors defined by model will take effect（zigbee）. If I have a large number of identical devices, it would be inconvenient to add them individually through MAC addresses. Thanks
1：
extra:
  cloud_fw: 2.0.1_0036
  cloud_name: 过道人体-里
  did: blt.3.1ftgfhk58kc00
  mac: e0:79:8d:2c:e9:dc
  market_brand: xiaomi
  market_model: XMPIRO25XS, xiaomi.motion.pir1
  market_name: Motion Sensor 2s
  **occupancy_timeout: 30**
  seq: 39
  type: ble
last_report:
  idle_time: 120
last_report_gw:
  fw_ver: 1.0.6_0016
  host: 192.168.0.3
  mac: 54:ef:44:3e:ee:2d
  model: lumi.gateway.mcn001
  name: Xiaomi Smart Home Hub 2
last_report_ts: 17s
last_seen:
  54ef443eee2d: 16s
  54ef44551d7b: 16s
listeners: 4
model: 13617
params:
  idle_time: 120
  motion: true
ttl: 1h5m
uid: e0798d2ce9dc

2：
extra:
  cloud_fw: 2.0.1_0036
  cloud_name: 过道人体-外
  did: blt.3.1ftgd5b50kk00
  mac: e0:79:8d:6f:d2:f5
  market_brand: xiaomi
  market_model: XMPIRO25XS, xiaomi.motion.pir1
  market_name: Motion Sensor 2s
  seq: 133
  type: ble
last_report:
  idle_time: 120
last_report_gw:
  fw_ver: 1.0.7_0021
  host: 192.168.0.4
  mac: 54:ef:44:55:1d:7b
  model: lumi.gateway.mcn001
  name: 小米智能多模网关2 第二台
last_report_ts: 1m38s
last_seen:
  54ef443eee2d: 1m38s
  54ef44551d7b: 1m38s
listeners: 4
model: 13617
params:
  idle_time: 120
  illuminance: 56.0
  motion: true
ttl: 1h5m
uid: e0798d6fd2f5

3：
extra:
  cloud_fw: 1.0.0_0011
  cloud_name: 小米人体传感器
  did: lumi.158d000445e1f8
  fw_ver: 11
  hw_ver: 0
  ieee: 00:15:8d:00:04:45:e1:f8
  lqi: 76
  market_brand: Xiaomi
  market_model: RTCGQ01LM
  market_name: Motion Sensor
  nwk: '0xdc37'
  **occupancy_timeout: 60**
  rssi: -81
  seq: 61
  type: zigbee
last_report:
  battery: 57
  battery_original: 181
  battery_voltage: 2985
  chip_temperature: 86
  lqi: 76
  resets: 30
  send_all_cnt: 1
  send_fail_cnt: 0
  send_retry_cnt: 0
last_report_gw:
  fw_ver: 1.0.6_0016
  host: 192.168.0.3
  mac: 54:ef:44:3e:ee:2d
  model: lumi.gateway.mcn001
  name: Xiaomi Smart Home Hub 2
last_report_ts: 3m15s
last_seen:
  54ef443eee2d: 3m15s
listeners: 3
model: lumi.sensor_motion
params:
  battery: 57
  battery_original: 181
  battery_voltage: 2985
  chip_temperature: 86
  lqi: 76
  resets: 30
  send_all_cnt: 1
  send_fail_cnt: 0
  send_retry_cnt: 0
ttl: 2h50m
uid: '0x00158d000445e1f8'

**Comment by flyibeat** [comment]
i know，It is not possible to add "" outside of 13617.

**Comment by AlexxIT** [comment]
You should use numeric model for BLE and Mesh devices

**Comment by flyibeat** [comment]
> You should use numeric model for BLE and Mesh devices

thanks
