### ISSUE TITLE
Alarm integration

### ISSUE THREAD

**Issue by fiyors** [AlexxIT/XiaomiGateway3#133]
Hi AlexxIt, Thanks for your fantastic work. 

Do you know if is possible to integrate the alarm ? 

Gateway -- lumi.gateway.mgl03

![image](https://user-images.githubusercontent.com/67486161/101470981-fff9ff80-3946-11eb-9c3d-3ca582055d27.png)

Thanks so much !

**Comment by w27** [comment]
Gateway arming is supported by its communication protocol for all firmware versions, even no telnet is required.
Specs:
[http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:gateway:0000A019:lumi-mgl03:2](http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:gateway:0000A019:lumi-mgl03:2)
