### ISSUE TITLE
Can mesh switch show more attributes ?

### ISSUE THREAD

**Issue by mickey50** [AlexxIT/XiaomiGateway3#1330]
I have a mesh switch , It can show lots of attributes when use the  xiaomi Miot Auto but none when use XiaoMiGateway3 , How can i
get the attributes  from xiaomgateway3 localy ,thank you!
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/6166901/40ee4bad-9f6c-4d83-8064-38ca9fb5699d)

**Comment by AlexxIT** [comment]
You should read docs and write converter

**Comment by mickey50** [comment]
> You should read docs and write converter
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/6166901/1a8344db-571a-48e4-9c17-5db597f44b6e)
my mesh switch has no "<brand>", "<name>", "<market model>" so I write like 
`DEVICES = [{
    "12261": [None, None, None],
    "spec": [
        BaseConv("switch", "switch", mi="2.p.1"),  # bool
        MapConv("icon-style", "select", mi="5.p.1", map={0: "Lamp-bulb", 1: "Cylindrical-spotlight"}),
    ],
}] + DEVICES`
it not work ,and  I  change value <brand> <name> <market model>  to the values from   Miot Auto like 
`from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
    "12261": ["linju", None, "linju.switch.sw0a01"],
    "spec": [
        BaseConv("switch", "switch", mi="2.p.1"),  # bool^M
        MapConv("icon-style", "select", mi="5.p.1", map={0: "Lamp-bulb", 1: "Cylindrical-spotlight"}),
    ],
}] + DEVICES`
It still not work . when can I do next ? Thank you !

**Comment by AlexxIT** [comment]
Model should be integer

**Comment by mickey50** [comment]
thank you ,it works .

**Comment by AlexxIT** [comment]
Please post your results. It can be useful for other users

**Comment by mickey50** [comment]
`from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
    12261: ["linju", "Lingju Bluetooth Mesh Switch", "(linju.switch.sw0a01)"],
    "spec": [
        BaseConv("switch", "switch", mi="2.p.1"),  # bool
        BoolConv("指示灯开关", "switch", mi="3.p.2"),
        BoolConv("R脚辅助开关", "switch", mi="3.p.6"),
        MapConv("灵动模式", "select", mi="3.p.4", map={
            0: "关闭", 1: "开启"
        }),
        MapConv("通电后默认状态", "select", mi="2.p.2", map={
            0: "恢复断电前状态", 1: "开启", 2: "关闭"
        }),
        MapConv("互控功能", "select", mi="3.p.3", map={
            1: "互控", 2: "解控"
        }),
        MapConv("icon-style", "select", mi="3.p.5", map={
            0: "灯泡", 1: "射灯", 2: "吸顶灯", 3: "吊灯", 4: "灯带", 5: "小家电", 6: "插座", 7: "阀门", 8: "电机"
        }),
    ],
}] + DEVICES
`
the state like "icon-style" can use for trggier event from mi_app to ha locally (mi_app -> Xiaomi Smart Hub Gateway ->trigger unused mesh device attributes ->xiaomigateway3 -> HA)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.5
