### ISSUE TITLE
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.5

### ISSUE THREAD

**Issue by abooodabdlaa** [AlexxIT/XiaomiGateway3#1342]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.5

_Originally posted by @AlexxIT in https://github.com/AlexxIT/XiaomiGateway3/issues/1257#issuecomment-2088683792_

**Comment by AlexxIT** [comment]
?
