### ISSUE TITLE
Lack of Power attribute of Xiaomi Outlet Pro（xiaomi.plug.mcn003）

### ISSUE THREAD

**Issue by mickeyyeung** [AlexxIT/XiaomiGateway3#1343]
I've noticed that the Xiaomi Wall Socket Pro—the upgraded version of the original Xiaomi Smart Wall Socket—is recognized in Gateway 3 as ID 17885. However, it only displays a single switch and is missing other features such as current power readings. Thanks!
https://home.miot-spec.com/spec/xiaomi.plug.mcn003

**Comment by AlexxIT** [comment]
You need to write the converter yourself

**Comment by mickeyyeung** [comment]
Thanks for your reply!
I tried creating a Converter as below, but after rebooting, the Power status remains 'unknown'. The newly added attributes are also not functioning.

{
    17885: ["Xiaomi", "Xiaomi Smart Wall Outlet Pro", "XMZNCZ03LM", "xiaomi.plug.mcn003"],
    "spec": [
        BaseConv("outlet", "switch", mi="2.p.1"),
        MapConv("power_on_state", "select", mi="2.p.2", map={0: "default", 1: "off", 2: "on"}),
        MapConv("fault", "sensor", mi="2.p.3", map={0: "No Faults", 1: "Over Temperature", 2: "Overload", 3: "Overload And Overheat"}),
        MathConv("power", "sensor", mi="3.p.6", round=1),
        BaseConv("led", "switch", mi="4.p.1"),
    ],
}

**Comment by mickeyyeung** [comment]
> You need to write the converter yourself

Thanks for your reply!
I tried creating a Converter as below, but after rebooting, the Power status remains 'unknown'. The newly added attributes are also not functioning.

{
17885: ["Xiaomi", "Xiaomi Smart Wall Outlet Pro", "XMZNCZ03LM", "xiaomi.plug.mcn003"],
"spec": [
BaseConv("outlet", "switch", mi="2.p.1"),
MapConv("power_on_state", "select", mi="2.p.2", map={0: "default", 1: "off", 2: "on"}),
MapConv("fault", "sensor", mi="2.p.3", map={0: "No Faults", 1: "Over Temperature", 2: "Overload", 3: "Overload And Overheat"}),
MathConv("power", "sensor", mi="3.p.6", round=1),
BaseConv("led", "switch", mi="4.p.1"),
],
}

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
