### ISSUE TITLE
The Xiaomi Human Body Sensor 2S is not working with the new version of HomeAssistant.

### ISSUE THREAD

**Issue by xysgx** [AlexxIT/XiaomiGateway3#1346]
Using the multi-mode gateway (ZNDMWG03LM) to connect the Xiaomi Human Body Sensor 2S (xiaomi.motion.pir1) results in the sensor being non-functional in the latest version of HomeAssistant, displaying "No issues found".

Subsequently, I set up a test environment where, with Core version 2024.5.0 and gateway3 version 3.3.3, the following is observed:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/e6c0c173-d06d-4a14-8faa-c15948cc791a)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/6c0c6691-9958-4694-a538-bb78d3528b3a)

Contrastingly, in Core version 2023.12.4, employing the same gateway3 version 3.3.3, the sensor operates normally, presenting the following status:
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/3420565e-b2c1-4b3a-9c49-2259ecf4a86a)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/f16eb17a-fd52-4668-95d7-3c3154ef21dc)

**Comment by relliky** [comment]
As I mentioned in this thread https://bbs.hassbian.com/forum.php?mod=viewthread&tid=25188&page=1&extra=#pid601311, your integration version is a bit dated and may not be able to pick up any recent fixes. Would recommand you to try to reproduce this issue with the latest integration and submit an issue.

**Comment by xysgx** [comment]
I have also used the latest version of the integration, but the problem remains.
Here's the information I used in the test again today:
HomeAssistant Version:
2024.5.3
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/20dcff17-9f66-4ccf-a1ae-e7e75a5f7f6f)

Integrated version:
4.0.5
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/980d78ee-a334-4a02-9f14-fa796275c5aa)

Firmware version of gateway:
1.5.0 _0102
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/dd42d675-fa6d-424c-afdd-af933bff5040)

2s Sensor version:
2.0.1 _0036
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/07611ec6-03ba-4c87-afeb-f49fe69d4599)

Sensor Bluetooth address:
F4:B3:B1:91:A2:58
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/57667764/93e95cf5-7ea7-4c1f-bee8-b1700ff23112)

Symptom After the basic log is opened, no sensor-related events are displayed in the log
Log: 
[home-assistant.log](https://github.com/AlexxIT/XiaomiGateway3/files/15321918/home-assistant.log)
@AlexxIT
