### ISSUE TITLE
Light status on HA changes automatically without really affecting the lamp

### ISSUE THREAD

**Issue by macming** [AlexxIT/XiaomiGateway3#1351]
Hello, I've encountered the same problem as [#1335](https://github.com/AlexxIT/XiaomiGateway3/issues/1335) on my custom mesh lamp after I updated to v4.0.5, restore the light.py file from v4.0.4 can solved the problem perfectly. 
How to resolve the conflict between different versions?Many thanks!

Here's my xiaomi_gateway3.py:
```
from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
    9754: ["Panasonic", "Floor Lamp", "HHTS2001W"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2"),
        ColorTempKelvin("color_temp", mi="2.p.3"),
    ],
}] + DEVICES
```

**Comment by Sergmasharov** [comment]
I have the same problem. Ikea zigbee e12 lamp randomly on-off state in HA.
![123](https://github.com/AlexxIT/XiaomiGateway3/assets/69318865/e8b77e1a-29be-4be6-a4da-569d495a3a1a)

**Comment by AlexxIT** [comment]
Any `brightness` of `color_temp` update will mark light as `on` state. This is main changes between this 4 and 5 versions
https://github.com/AlexxIT/XiaomiGateway3/compare/v4.0.4...v4.0.5

**Comment by Sergmasharov** [comment]
Yes, but lamp all the time is off. HA changes state randomly.

**Comment by BeckXuan** [comment]
The same issue, too. I use the Xiaomi light mesh group. It will still report the status of color_temp when it is off. Realted log is as follows.
```log
May  8 18:43:41 Mijia_Hub_V2-3022 user.notice miio_bt[476]: [N][mesh_gateway] mible_mesh_report_states 1883: id = 1372128240, js = {"type":16,"method":"properties_changed","params":[{"did":"1030382664","siid":2,"piid":3,"value":4504},{"did":"103035776","siid":2,"piid":3,"value":4504}]}
```

**Comment by hubpf** [comment]
I have adaptive lighting to change light brightness and temp by following the sun. I can see all lights are showing on status, but not really physically on. Please help to fix this.

**Comment by zhang-wenchao** [comment]
I have the same problem, the state of the latest version of the light is abnormal

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
