### ISSUE TITLE
Xlumi.gateway.mgl03 can't search get linp.sensor_occupy.hb01

### ISSUE THREAD

**Issue by ak4741a** [AlexxIT/XiaomiGateway3#1355]
Gateway info:
Gateway: ZNDMWG03LM, ZNDMWG02LM, YTC4044GL, lumi.gateway.mgl03
廠牌：Xiaomi
韌體：1.4.6_0043

sensor info:
linp.sensor_occupy.hb01
廠牌：linp
韌體：2.1.1_0168

linp human body detection sensor has been added to the Mijia app and successfully connected through mesh.
In the integration, this device was not added after joining the gateway.

**Comment by AlexxIT** [comment]
Don't understand you

**Comment by ak4741a** [comment]
sorry modify problem description

**Comment by AlexxIT** [comment]
The answer is here
https://github.com/AlexxIT/XiaomiGateway3?tab=readme-ov-file#supported-firmwares
