### ISSUE TITLE
PTX BLE Wireless Tripple Switch model 14610 recognized but not working

### ISSUE THREAD

**Issue by lj4o7** [AlexxIT/XiaomiGateway3#1358]
[
[xiaomi_gateway3-8b5e38ddf230c90ec52aa8832d1dd9be-影音系统-bb4ba3cd5151b02c47476c63f74243b8.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/15311105/xiaomi_gateway3-8b5e38ddf230c90ec52aa8832d1dd9be-.-bb4ba3cd5151b02c47476c63f74243b8.json.txt)

pressing actions cannot be logged by HA.

**Comment by lj4o7** [comment]
working now after adding these to xiaomi_gateway3.py

DEVICES = [{
14610: ["PTX", "Triple Wireless Switch", "PTX-AK3-QMIMC"],
    "spec": [
        BaseConv("action", "sensor"),
        ConstConv("action", mi="2.e.1012", value=BUTTON_1_SINGLE),
        ConstConv("action", mi="4.e.1012", value=BUTTON_2_SINGLE),
        ConstConv("action", mi="5.e.1012", value=BUTTON_3_SINGLE),
        ConstConv("action", mi="2.e.1014", value=BUTTON_1_HOLD),
        ConstConv("action", mi="4.e.1014", value=BUTTON_2_HOLD),
        ConstConv("action", mi="5.e.1014", value=BUTTON_3_HOLD),
    ],
}] + DEVICES

**Comment by flyibeat** [comment]
resolve #1389
