### ISSUE TITLE
Bluetooth mesh light, which will turn on by itself.

### ISSUE THREAD

**Issue by hzonz** [AlexxIT/XiaomiGateway3#1362]
I can't determine what could cause the lights to turn on on their own.
In the device log, only the lights are turned on.

Affected devices:
Mesh: 090615.light.mlig02
Mesh: MJTS01YL/MJTS003,yeelink.light.light3
Mesh: lemesh.light.wy0c08
Mesh: lemesh.light.wy0c15

I can't be sure when the lights will be on, maybe at night, or early in the morning, or noon.
The previous version was correct, and I'm sure I submitted an issue about not being able to correctly identify the status of the lights.

Mesh: 090615.light.mlig02 Every minute, you will be prompted that it is no longer available.

[home-assistant_xiaomi_gateway3_2024-05-17T09-48-51.113Z.zip](https://github.com/AlexxIT/XiaomiGateway3/files/15347121/home-assistant_xiaomi_gateway3_2024-05-17T09-48-51.113Z.zip)

**Comment by heo-huang** [comment]
I have the same problem with you.When this issue occurs, the device shows as 'on' in Home Assistant, but appears as 'off' in the Mi Home APP.I tried using an older version of Home Assistant, but it didn't make any difference.

Affected devices:
Mesh: yeelink.light.mbulb3
Mesh: emesh.light.wy0c15
Mesh: lemesh.light.wy0c09

Home Assistant Version：2024.3.3
Gateway3 Version: v4.0.5

**Comment by rolay** [comment]
I also encountered the problem of incorrect status. By observing the properties of the mesh device, I found that there was a msg_missed situation. It is estimated that it was caused by message loss. I haven't found a solution yet.

**Comment by hzonz** [comment]
> I have the same problem with you.When this issue occurs, the device shows as 'on' in Home Assistant, but appears as 'off' in the Mi Home APP.I tried using an older version of Home Assistant, but it didn't make any difference.
> 
> Affected devices: Mesh: yeelink.light.mbulb3 Mesh: emesh.light.wy0c15 Mesh: lemesh.light.wy0c09
> 
> Home Assistant Version：2024.3.3 Gateway3 Version: v4.0.5

I previously submitted an issue about the incorrect status of the bluetooth mesh light#1335
This issue seems to be related to the Adaptiv Leting integration.

**Comment by shenmirenQUQ** [comment]
The same problem can be solved by overwriting the 4.0.4 version of light.py into the new 4.0.5

**Comment by hzonz** [comment]
> The same problem can be solved by overwriting the 4.0.4 version of light.py into the new 4.0.5

Version 4.0.4, there is a problem that the light state cannot be correctly identified, or wait for the author to solve this problem.

**Comment by wz69699** [comment]
> I have the same problem because of [#1351 (comment)](https://github.com/AlexxIT/XiaomiGateway3/issues/1351#issuecomment-2106263520) and an automation that adjust brightness when lights are on.
> 
> Version 4.0.5 incorrectly mark the state of the Xiaomi mesh group light as on (but the actual state is off yet), and then the brightness automation will turn the lights on for real.

There is nothing to do with adaptive lighting. Since I tried excluding these lights from adaptive lighting, they still turn on by themselves.

**Comment by hzonz** [comment]
> > > I have the same problem because of [#1351 (comment)](https://github.com/AlexxIT/XiaomiGateway3/issues/1351#issuecomment-2106263520) and an automation that adjust brightness when lights are on.
> > > Version 4.0.5 incorrectly mark the state of the Xiaomi mesh group light as on (but the actual state is off yet), and then the brightness automation will turn the lights on for real.
> > 
> > 
> > There is nothing to do with adaptive lighting. Since I tried excluding these lights from adaptive lighting, they still turn on by themselves.
> 
> By the way, I fixed it by using light.py from version 4.0.4

Is there a problem with lights that use lemesh modules and can't correctly identify the light status?

**Comment by JonathanKang** [comment]
I'm had the same issue with version 4.0.5. I'm using 4.0.4 right now, and this issue is no longer happening.

**Comment by AlexxIT** [comment]
#1351
