### ISSUE TITLE
Add support lumi.lock.mcn009

### ISSUE THREAD

**Issue by PerryLayne** [AlexxIT/XiaomiGateway3#1371]
- lumi.lock.mcn009 is a version of lumi.lock.mcn008 with an added camera.
- E20 WIFI version:   https://home.miot-spec.com/spec/lumi.lock.mcn008
- E20 Cat Eye version:    https://home.miot-spec.com/spec/lumi.lock.mcn009

- These two should be basically interchangeable, so I hope support for the device can be added.
- I don't know how to compile because I have no background in coding. I don't know where to start, but if there are relevant tutorials or guides, I can try to add the related configurations myself.

**Comment by AlexxIT** [comment]
Looks like you have added loock.lock.r2 model in another issue. What about lumi.lock.mcn008 and lumi.lock.mcn009?

**Comment by kssj0001** [comment]
> Looks like you have added loock.lock.r2 model in another issue. What about lumi.lock.mcn008 and lumi.lock.mcn009?

Please add lumi.lock.mcn008 in new version. It's a model without camare.

**Comment by AlexxIT** [comment]
You can send the converter and I'll add it.

**Comment by kssj0001** [comment]
Sorry I'm not a professional programmer. I just change PerryLayne's code in "devices.py", It has the same problem with him. The sensor "door" not working, always been unknown status.

![image](https://github.com/user-attachments/assets/0149aa31-6868-4a51-a6cb-16544a55261e)


`{
    12934: ["Xiaomi", "Smart Door Lock E20 WIFI", "XMZNMS201LM", "lumi.lock.mcn008"],
    "spec": [
        # lock action
        BaseConv("action", "sensor"),
        BaseConv("method", "sensor"),
        BaseConv("action_id", mi="2.e.1020.p.3"),
        BaseConv("method_id", mi="2.e.1020.p.5"),
        BaseConv("key_id", "sensor", mi="2.e.1020.p.1"),
        BaseConv("timestamp", mi="2.e.1020.p.2"),
        MapConv("action", mi="2.e.1020.p.3", map={1: "lock", 2: "unlock", 3: "Lifted Up The Door Handle From Outside To Lock", 4: "locked_from_inside", 5: "released_lock_from_inside", 6: "enabled_child_lock", 7: "disabled_child_lock", 8: "enable_the_away_from_home_mode", 9: "disable_the_away_from_home_mode"}),
        MapConv("method", mi="2.e.1020.p.5", map={1: "mobile_phone", 2: "fingerprint", 3: "password", 4: "nfc", 5: "face", 6: "finger_vein", 7: "palm_print", 8: "lock_key", 9: "one_time_password", 10: "periodic_password", 11: "homekit", 12: "coerce", 13: "two_step_verification", 14: "turntable", 15: "manual", 16: "auto"}),
        MapConv("door", "sensor", mi="3.p.1021", map={1: "locked", 2: "unlocked", 3: "timeout", 4: "ajar"}),
        MapConv("position", mi="2.e.1020.p.6", map={1: "indoor", 2: "outdoor", 3: "unknown"}),
        BaseConv("battery", "sensor", mi="4.p.1003"),
        ConstConv("action", mi="5.e.1006", value="doorbell"),
        BaseConv("timestamp", mi="5.e.1006.p.1"),
    ],
}`

**Comment by PerryLayne** [comment]
> Sorry I'm not a professional programmer. I just change PerryLayne's code in "devices.py", It has the same problem with him. The sensor "door" not working, always been unknown status.
> 
> ![image](https://private-user-images.githubusercontent.com/33344007/382628246-0149aa31-6868-4a51-a6cb-16544a55261e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMzYwODgsIm5iZiI6MTczMzAzNTc4OCwicGF0aCI6Ii8zMzM0NDAwNy8zODI2MjgyNDYtMDE0OWFhMzEtNjg2OC00YTUxLWE2Y2ItMTY1NDRhNTUyNjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA2NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzNkYTc1NTAzMjJmZWU3M2YxMTRmNjc2NTE3NGY3ZTE4NzdhODc4MGQ0MWI2NDlhNjMyZGEyZGQ5MjYyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pf0yc9_5GYXeINF4d5IuR3fSjQl1KSFIBamwLCK3g38)
> 
> { 12934: ["Xiaomi", "Smart Door Lock E20 WIFI", "XMZNMS201LM", "lumi.lock.mcn008"], "spec": [ # lock action BaseConv("action", "sensor"), BaseConv("method", "sensor"), BaseConv("action_id", mi="2.e.1020.p.3"), BaseConv("method_id", mi="2.e.1020.p.5"), BaseConv("key_id", "sensor", mi="2.e.1020.p.1"), BaseConv("timestamp", mi="2.e.1020.p.2"), MapConv("action", mi="2.e.1020.p.3", map={1: "lock", 2: "unlock", 3: "Lifted Up The Door Handle From Outside To Lock", 4: "locked_from_inside", 5: "released_lock_from_inside", 6: "enabled_child_lock", 7: "disabled_child_lock", 8: "enable_the_away_from_home_mode", 9: "disable_the_away_from_home_mode"}), MapConv("method", mi="2.e.1020.p.5", map={1: "mobile_phone", 2: "fingerprint", 3: "password", 4: "nfc", 5: "face", 6: "finger_vein", 7: "palm_print", 8: "lock_key", 9: "one_time_password", 10: "periodic_password", 11: "homekit", 12: "coerce", 13: "two_step_verification", 14: "turntable", 15: "manual", 16: "auto"}), MapConv("door", "sensor", mi="3.p.1021", map={1: "locked", 2: "unlocked", 3: "timeout", 4: "ajar"}), MapConv("position", mi="2.e.1020.p.6", map={1: "indoor", 2: "outdoor", 3: "unknown"}), BaseConv("battery", "sensor", mi="4.p.1003"), ConstConv("action", mi="5.e.1006", value="doorbell"), BaseConv("timestamp", mi="5.e.1006.p.1"), ], }

I'm sorry, but I don't have any knowledge or background in coding. I'm just trying to learn and write code on my own as a hobby. I still haven't been able to solve this problem despite trying countless approaches, none of which have worked.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
