### ISSUE TITLE
Add support wlg.light.wy0a01 mesh light

### ISSUE THREAD

**Issue by KANG0623** [AlexxIT/XiaomiGateway3#1376]
![微信截图_20240605182007](https://github.com/AlexxIT/XiaomiGateway3/assets/99658809/f3c194cd-a8ee-4084-9bd2-d1626987fd4f)
我已经编写好转换器

DEVICES = [{
    16108: ["WLG", "Smart Light", "wlg.light.wy0a01"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", mink=2700, maxk=6500),
    ],
}] + DEVICES

![微信截图_20240608173834](https://github.com/AlexxIT/XiaomiGateway3/assets/99658809/bbb6678b-6196-4aa3-818f-8b7b73f28779)

**Comment by KANG0623** [comment]
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/99658809/4fe56054-5f6a-4f32-a255-0096a285d485)
由此大神提供技术支持

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
