### ISSUE TITLE
Xiaomi Automatic Smart Door Lock sometimes lose data 

### ISSUE THREAD

**Issue by mickey50** [AlexxIT/XiaomiGateway3#138]
Firmware Version: 1.4.6_0012
[gateway.log](https://github.com/AlexxIT/XiaomiGateway3/files/5676797/gateway.log)

**Comment by AlexxIT** [comment]
Do you use latest component version? Need to check `debug: miio` logs.

**Comment by mickey50** [comment]
> Do you use latest component version? Need to check `debug: miio` logs.

alreay on 0.10.4  and I uploaded the log which add debug:miio ,thx @AlexxIT 
[gateway.log](https://github.com/AlexxIT/XiaomiGateway3/files/5687012/gateway.log)

**Comment by AlexxIT** [comment]
Yes, I see loss in the log. There may be a problem in the communication channel (bluetooth). I'll try to investigate the situation.

**Comment by mickey50** [comment]
Distance is about 5m . otherwise , I have three yeelight lights which can be used as bluetooth gateway,is this can cause this problem？@AlexxIT

**Comment by saury** [comment]
@mickey50, you may try to update to newer modified FW or run ble dfu for your gateway refer to [this url].(https://github.com/niceboygithub/XiaomiGateway3fw)
I find the bluetooth connection become unstable after keep running for several days under 1.4.6. You can double confirm by creating any automation in mijia.app and check if this automation execute every time.

**Comment by mickey50** [comment]
> @mickey50, you may try to update to newer modified FW or run ble dfu for your gateway refer to [this url](https://github.com/niceboygithub/XiaomiGateway3fw).
> I find the bluetooth connection become unstable after keep running for several days under 1.4.6. You can double confirm by creating any automation in mijia.app and check if this automation execute every time.
 
I updated to modified version 1.4.7_0115 today to check if it works well . I think it may be because I have other devices can use as gateway ,so it didn't lose events in mijia.app ,many thanks  @saury

**Comment by AlexxIT** [comment]
Same problem #187 
Further discussions in that task
