### ISSUE TITLE
Add support yankon.light.ykmesh mesh light

### ISSUE THREAD

**Issue by will-huang9531** [AlexxIT/XiaomiGateway3#1386]
Gateway3 doesn't support this ble-mesh light，it‘s recognized as a switch.
I tried writing the converter myself, but it didn't work.
miot-spec is here https://home.miot-spec.com/spec/yankon.light.ykmesh
I need your help！

**Comment by will-huang9531** [comment]
this is my converter, I don't know what's wrong with it.
Dose someone can help me check it?

from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
     "yankon.light.ykmesh": ["yankon", "Mesh Light", "yankon.light.ykmesh"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", mink=2700, maxk=6500),
    ],
}] + DEVICES

**Comment by will-huang9531** [comment]
This converter has been tested and is now useable
https://home.miot-spec.com/spec/yankon.light.ykmesh
@AlexxIT 

from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
     20066: [None, "Mesh Light", "yankon.light.ykmesh"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", mink=2700, maxk=6500),
        MapConv("mode", "select", mi="2.p.7", map={0: "none", 1: "warmth", 2: "tv", 3: "reading", 4: "computer", 5: "hospitality", 6: "entertainment", 7: "lighting", 8: "night light"}),
        MapConv("power_on_state", "select", mi="2.p.7", map={0: "default", 2: "on"}),  # config
    ],
}] + DEVICES

**Comment by dythebs** [comment]
same problem

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
