### ISSUE TITLE
Add support for Mi battery presence sensor

### ISSUE THREAD

**Issue by Everwalker** [AlexxIT/XiaomiGateway3#1390]
The new presence sensor can be recognized but data is received.

**Comment by Necroneco** [comment]
#1369

**Comment by Everwalker** [comment]
> #1369

Do I need to do anything about the yaml file? I currently only see a BLE entity and a command entity. Thanks.

**Comment by Necroneco** [comment]
This is supported on "master" but has not yet been released.

You can try to install the main branch.

**Comment by Ivvttck** [comment]
Can you explain more on what do you mean by supported on master?

**Comment by hellowxufang** [comment]
After used master code, the Human Presence Sensor entity in Gateway3 show "Unknown", is the reason for sensor firmware update?

![WeChat截图_20240703102242](https://github.com/AlexxIT/XiaomiGateway3/assets/10987329/b336f94c-c605-4bad-8fc7-989cceb68a4a)
![WeChat截图_20240703102306](https://github.com/AlexxIT/XiaomiGateway3/assets/10987329/7d4d15a8-400d-4534-911a-aa6216dd2807)


> This is supported on "master" but has not yet been released.
> 
> You can try to install the main branch.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
