### ISSUE TITLE
Add rgb_color converter

### ISSUE THREAD

**Issue by ym66666** [AlexxIT/XiaomiGateway3#1396]
How to support color lights? external converter No color mode

**Comment by ym66666** [comment]
![1](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/5ba098ef-18af-41d5-a478-752343ca45ba)
![2](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/c3ad2491-8ccf-4903-8dac-acd3977801c8)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/b57f509e-a2b2-4540-a846-992f47835782)
2024-07-03 19:08:24.511 DEBUG (MainThread) [custom_components.xiaomi_gateway3.mqtt.192.168.31.89] {'topic': 'central/report', 'data': b'{"id":727277201,"_to":128,"type":16,"method":"properties_changed","params":[{"did":"1116431503","siid":2,"piid":4,"tid":158,"value":6205951}]}'}

**Comment by ym66666** [comment]
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/fca72b19-43a5-4011-bd01-935288d4f9fd)
I can't find the corresponding converter, so I can only use MathConv instead, but I can't choose the color.
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/ffba981f-c780-4d47-89c0-561d743042c3)

**Comment by flyibeat** [comment]
Maybe you can try:
MathConv("color", "number", mi="2.p.4", min=1, max=16777215)

**Comment by ym66666** [comment]
First of all, thanks bro.
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/467c744e-594e-493e-846f-a00be86756d3)
I tried,but it's separate and I want it to be integrated into the light

**Comment by flyibeat** [comment]
> First of all, thanks bro. ![image](https://private-user-images.githubusercontent.com/79862330/346248500-467c744e-594e-493e-846f-a00be86756d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzY4NDksIm5iZiI6MTcyMDIzNjU0OSwicGF0aCI6Ii83OTg2MjMzMC8zNDYyNDg1MDAtNDY3Yzc0NGUtNTk0ZS00OTNlLTg0NmYtYTAwYmU4Njc1NmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDY1Mjk4ZDcwYTc3YTE0YzM1Zjc5ZmYwMjRkNTEzNTZjOWQ1Y2Y5NTljMDEyYWVkY2RjYmQ3NWRjMDA0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o2NMMOBi4OygnRckYcCka1Nj5d1RMKRsSwS1NrKJmm4) I tried,but it's separate and I want it to be integrated into the light

light.py Include 
elif conv.attr == ATTR_HS_COLOR:
                self.listen_attrs.add(conv.attr)
                modes.add(ColorMode.HS)

so，Try to change the name from color to hs_color

**Comment by ym66666** [comment]
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/cbc6d7bb-97b4-42e2-8340-a5c20151a11d)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/9b840086-9d31-4086-bba8-b1e5dac6667e)
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/8ca6c13f-0914-4cfe-8b9c-9c6b588a3b28)
The color palette appears, but has no effect and causes some abnormalities in turning on and off the lights

**Comment by ym66666** [comment]
![image](https://github.com/AlexxIT/XiaomiGateway3/assets/79862330/f3eda121-39ff-4653-9490-e2a6cd3fe351)

**Comment by flyibeat** [comment]
Homeassistant does not support the decimal color code, and the author needs to add the relevant conversion code.在 2024年7月6日，15:38，ym66666 ***@***.***> 写道：﻿
image.png (view on web)
image.png (view on web)
image.png (view on web)
The color palette appears, but has no effect and causes some abnormalities in turning on and off the lights

**Comment by flyibeat** [comment]
﻿Homeassistant does not support the decimal color code, and the author needs to add the relevant conversion code.在 2024年7月6日，15:38，ym66666 ***@***.***> 写道：﻿
image.png (view on web)
image.png (view on web)
image.png (view on web)
The color palette appears, but has no effect and causes some abnormalities in turning on and off the lights

**Comment by AlexxIT** [comment]
Unfortunately I don't have such lamps for the test. I'll try to do something about it.
