### ISSUE TITLE
Deprecated constant CONDUCTIVITY

### ISSUE THREAD

**Issue by sephrioth** [AlexxIT/XiaomiGateway3#1398]
CONDUCTIVITY was used from xiaomi_gateway3, this is a deprecated constant which will be removed in HA Core 2025.6. Use UnitOfConductivity.MICROSIEMENS instead, please report it to the author of the 'xiaomi_gateway3' custom integration

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
