### ISSUE TITLE
can't connect gateway

### ISSUE THREAD

**Issue by sanyasd** [AlexxIT/XiaomiGateway3#1399]
I added a cloud account.
![image](https://github.com/user-attachments/assets/8f93c5db-7111-4967-a93e-0953b85288d6)
When I try to add this hub I get an error
![image](https://github.com/user-attachments/assets/0b725945-44b2-48fd-a706-6c9f0e90fcc3)
![image](https://github.com/user-attachments/assets/a09ec97e-c4b7-4d35-8081-7324ee4d70b0)

How can I add a device?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3?tab=readme-ov-file#supported-firmwares
