### ISSUE TITLE
0.2.2 Can't read devices

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/XiaomiGateway3#14]
0.2.0 worked with 2 hubs till reboot HA.
Each hub has 3 sensors: door, TH and light.
I have updated 0.2.0 to 0.2.2.
Now it does not work at all with the following errors in log:

2020-09-09 03:34:06  DEBUG    gateway3      192.168.1.252 | Read devices
2020-09-09 03:34:06  DEBUG    gateway3      192.168.1.253 | Read devices
2020-09-09 03:34:07  DEBUG    gateway3      Can't read devices: Invalid base64-encoded string: number of data characters (57) cannot be 1 more than a multiple of 4
2020-09-09 03:34:07  DEBUG    gateway3      192.168.1.252 | Try enable telnet
2020-09-09 03:34:07  DEBUG    gateway3      Can't read devices: Invalid base64-encoded string: number of data characters (57) cannot be 1 more than a multiple of 4
2020-09-09 03:34:07  DEBUG    gateway3      192.168.1.253 | Try enable telnet
2020-09-09 03:34:07  DEBUG    gateway3      192.168.1.252 | Read devices
2020-09-09 03:34:08  DEBUG    gateway3      192.168.1.253 | Read devices
...

**Comment by Mantoui** [comment]
0.2.2  
2020-09-09 09:34:23  DEBUG    gateway3      10.2.0.107 | Read devices
2020-09-09 09:34:23  DEBUG    gateway3      Can't read devices: Invalid base64-encoded string: number of data characters (57) cannot be 1 more than a multiple of 4

**Comment by AlexxIT** [comment]
It's very strange.

- check `top` for `zigbee_gw` app
- check `cat /usr/app/bin/daemon_app.sh` for `zigbee_gw` app
- show `cat /usr/app/conf/zigbee_gw.conf`
- show `cat /data/conf/os-release`

**Comment by fishbone-git** [comment]
`
Load average: 1.45 1.65 1.68 1/81 5367
  PID  PPID USER     STAT   VSZ  %VSZ CPU %CPU COMMAND
 1153     1 admin    S     1456   2.4   0  0.2 {daemon_app.sh} /bin/sh ./daemon_app.sh
 1213  1153 admin    S    10976  18.7   0  0.0 /usr/app/bin/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g
 `

`# cat /usr/app/bin/daemon_app.sh | grep zigbee_gw

        if [ "`ps -ww | grep zigbee_gw | grep -v grep`xx" == "xx" ]
            $APP_PATH/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g $GW_DID &
            echo "zigbee_gw --- dead ---reboot"
#`

`# cat /usr/app/conf/zigbee_gw.conf 

{
  "data-path":"/data/zigbee_gw/",
  "config-path":"/usr/app/conf/zigbee_gw/",
  "daemon":false,
  "log-debug":true,
  "log-level":6,
  "pid-file":"/var/zigbee_gw.pid",
  "proc-guard-log-file": "/var/zigbee_gw_proc_guard.log"
}`

`# cat /data/conf/os-release 

_VERSION=1.4.5_0012
SN=DLMMGW2013000683
LUMI_VERSION=1.4.6_0030
# 
`

**Comment by Mantoui** [comment]
# ps T | grep zigbee_gw     
```
1202 admin    11072 S    /usr/app/bin/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g 317117661                        
1236 admin    11072 S    /usr/app/bin/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g 317117661                        
1284 admin    11072 S    /usr/app/bin/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g 317117661                       
19308 admin     1392 R    grep zigbee_gw  

```
# cat /usr/app/bin/daemon_app.sh | grep zigbee_gw
```
    if [ "`ps -ww | grep zigbee_gw | grep -v grep`xx" == "xx" ]
        $APP_PATH/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g $GW_DID &
        echo "zigbee_gw --- dead ---reboot"
```
# cat /usr/app/conf/zigbee_gw.conf
```
{
  "data-path":"/data/zigbee_gw/",
  "config-path":"/usr/app/conf/zigbee_gw/",
  "daemon":false,
  "log-debug":true,
  "log-level":6,
  "pid-file":"/var/zigbee_gw.pid",
  "proc-guard-log-file": "/var/zigbee_gw_proc_guard.log"
}
```
# cat /data/conf/os-release
```
_VERSION=1.4.4_0003
SN=ZLMDGW1952001051
LUMI_VERSION=1.4.6_0030
```

**Comment by freeball155** [comment]
The same here. 

# ps | grep zigbee_gw
 1213 admin    10928 S    /usr/app/bin/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g 317088039
27222 admin     1392 S    grep zigbee_gw

# cat /usr/app/bin/daemon_app.sh | grep zigbee_gw
        if [ "`ps -ww | grep zigbee_gw | grep -v grep`xx" == "xx" ]
            $APP_PATH/zigbee_gw -c /usr/app/conf/zigbee_gw.conf -g $GW_DID &
            echo "zigbee_gw --- dead ---reboot"

# cat /usr/app/conf/zigbee_gw.conf
{
  "data-path":"/data/zigbee_gw/",
  "config-path":"/usr/app/conf/zigbee_gw/",
  "daemon":false,
  "log-debug":true,
  "log-level":6,
  "pid-file":"/var/zigbee_gw.pid",
  "proc-guard-log-file": "/var/zigbee_gw_proc_guard.log"
}

#  cat /data/conf/os-release
_VERSION=1.4.4_0003
SN=ZLMDGW1949004835
LUMI_VERSION=1.4.6_0030

# ls -la /data/zigbee_gw/
drwxr-xr-x    2 admin    0              680 Aug 31 10:11 .
drwxrwxrwx   13 admin    0             1352 Jan  1  1970 ..
-rw-r--r--    1 admin    0              232 Aug 31 10:11 device_properties.json
-rw-r--r--    1 admin    0              505 Sep  9 07:09 lumi.158d00045228d7.json
-rw-r--r--    1 admin    0              506 Sep  9 06:20 lumi.158d0004522a2b.json
-rw-r--r--    1 admin    0              506 Sep  9 08:36 lumi.158d00047c5529.json
-rw-r--r--    1 admin    0              505 Sep  9 06:59 lumi.158d0004a02016.json
-rw-r--r--    1 admin    0              506 Sep  9 09:16 lumi.158d0004a02023.json

**Comment by AlexxIT** [comment]
I have `LUMI_VERSION=1.4.6_0012` and no updates in Mi Home. What is your region in Mi Home app?

**Comment by freeball155** [comment]
My region is Ukraine. 
I've used mihome 5.8.16 from [here](https://www.kapiba.ru/2017/11/mi-home.html) to get the token.

# cat /data/zigbee_gw/lumi.158d00047c5529.json
{
    "lumi.158d00047c5529.mac": "158d00047c5529",
    "lumi.158d00047c5529.model": "lumi.sensor_wleak.aq1",
    "lumi.158d00047c5529.prop": "{\"props\":{\"CCA\":1,\"alarm\":0,\"alive\":1,\"battery\":69,\"battery_end_of_life\":0,\"chip_temperature\":29,\"cur_state\":3,\"fw_ver\":4,\"hw_ver\":2,\"lqi\":0,\"parent\":0,\"power_tx\":10,\"pre_state\":1,\"pv_state\":0,\"reset_cnt\":14,\"send_all_cnt\":1,\"send_fail_cnt\":0,\"send_retry_cnt\":0,\"voltage\":3015}}",
    "lumi.158d00047c5529.version": "1.2"
}

**Comment by AlexxIT** [comment]
Ok. The same information as in the database. Will have to support both formats. Not a problem

**Comment by viiy** [comment]
Same with 1hub
After reboot 
Try enable telnet
Read devices
Can't read devices: Invalid base64-encoded string: number of data characters (57) cannot be 1 more than a multiple of 4

Region - China

**Comment by rezmus** [comment]
@AlexxIT 1.4.6_0030 was available in july, but in august was taken down from ota.

**Comment by AlexxIT** [comment]
Can someone send me rootfs (mtd6 or mtd8) for 1.4.6_0030?
Instructions on how to get [here](https://community.home-assistant.io/t/xiaomi-mijia-smart-multi-mode-gateway-zndmwg03lm-support/159586/62). Only step 2. You can send both mtd6 and mtd8, if you don't know which one is latest.

**Comment by rezmus** [comment]
https://ufile.io/hpqeh15t

**Comment by freeball155** [comment]
https://drive.google.com/drive/folders/1EQ2ZOol4fU6rT8TT2m2fmLhckVcr6llu?usp=sharing

**Comment by AlexxIT** [comment]
Check latest **master** version. It can be installed via HACS.

**Comment by freeball155** [comment]
Yes, it works now.
The battery charge level for the water leak sensor is showing now.
Thank.

**Comment by Mantoui** [comment]
> Check latest **master** version. It can be installed via HACS.

it work now  , thanks

![image](https://user-images.githubusercontent.com/4598262/92642029-30afa600-f312-11ea-8f74-5ce4687bb79b.png)
