### ISSUE TITLE
telnet: Unable to connect to remote host

### ISSUE THREAD

**Issue by cenobitedk** [AlexxIT/XiaomiGateway3#140]
Thanks for all your hard work!

I have a device with firmware version v1.4.6_0043, and I have followed [your guide](https://github.com/AlexxIT/XiaomiGateway3/wiki/Decode-Telnet-Password) to retreive the telnet password.

I have the password but I'm stuck at the last step since I can't connect with telnet to the device:
```
$ telnet 192.168.1.57
Trying 192.168.1.57...
telnet: connect to address 192.168.1.57: Connection refused
telnet: Unable to connect to remote host
```

I have tried various solutions, but the telnet service does not seem to respond.
Here's a few of the links I have followed:
https://stackoverflow.com/questions/27941036/telnet-to-login-with-username-and-password-to-mail-server
https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md#method-5---telnet-with-root-acces
The latter link did in particular not help as the gateway does not create its own wifi network.

I had the UART connection running (using `screen` in mac terminal) while booting the device and it reports A LOT of info, however I can't scroll in the window to see if the telnet service has actually started.

I would love any help you can provide. In advance thank you!

**Comment by cenobitedk** [comment]
I tried resetting the device several times and sometimes it creates a network. I have been able to connect to the network once, but I didn't succesfully connect with telnet before the the device somehow returned to normal operation by itself. Not sure how it can do that, but I was not able to recreate the network againg. At least not so far.

<img width="562" alt="Screenshot 2020-12-13 at 23 11 13" src="https://user-images.githubusercontent.com/1397207/102025757-66917a00-3d9a-11eb-9536-19a122566d88.png">

**Comment by cenobitedk** [comment]
After more attempts I was able to connect to the wifi it creates after reset. But telnet is still not possible:
```
$ telnet 192.168.1.1
Trying 192.168.1.1...
telnet: connect to address 192.168.1.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by rezmus** [comment]
telnet is not running by default, you have to start it using this integration or miio cmd.

https://community.home-assistant.io/t/xiaomi-mijia-smart-multi-mode-gateway-zndmwg03lm-support/159586/61

**Comment by cenobitedk** [comment]
@rezmus Thanks! That was not obvious from the guide, but let's see.

Seems I can sorta connect to the device:
```
$ php miio-cli.php --discover 192.168.1.57 --debug
array(2) {
  ["discover"]=>
  string(12) "192.168.1.57"
  ["debug"]=>
  bool(false)
}
Поиск 192.168.1.57
Соединение с устройством IP 192.168.1.57
Статус отладки [1]
Сокет успешно создан

Проверяем доступность устройства 192.168.1.57
Параметр SO_RCVTIMEO сокета успешно задан
 >>>>> Отправляем hello-пакет на 192.168.1.57 с таймаутом 5
 >>>>> Отправлено в сокет 32 байт
 <<<<< Получен ответ от IP 192.168.1.57 с порта 54321
Прочитано 32 байта из сокета
magic: 2131
length: 0020 --> 32 байт
unknown1: 00000000
devicetype: 1655
serial: 1be4
ts: 5fd72d1e --> 1607937310 секунд --> 2020-12-14 09:15:10
checksum: ffffffffffffffffffffffffffffffff
ts_server: 5fd72d1e --> 1607937310 секунд --> 2020-12-14 09:15:10
timediff: 0
Поиск выполнен.
Устройство найдено и отвечает.
```
(really wish it was outputting info in English so it's not limited to a certain nationality)

But I can't turn on telnet: 
```
$ php miio-cli.php  --ip 192.168.1.57 --token ****** --sendcmd '{"id":0,"method":"enable_telnet_service", "params":[]}'
Устройство 192.168.1.57 не доступно или не отвечает.

$ telnet 192.168.1.57
Trying 192.168.1.57...
telnet: connect to address 192.168.1.57: Connection refused
telnet: Unable to connect to remote host
```

Any ideas?

**Comment by rezmus** [comment]
if your hub is connected to cloud you cant discover token. use mi home mod or this integration to get it (and even enable telnet).

**Comment by cenobitedk** [comment]
I do have the token, I just left it out. Using the integration in HA I had found the device information

```
Name: Gateway
Model: lumi.gateway.mgl03
IP: 192.168.1.57
MAC: 54:EF:44:CE:EE:92
Token: 4e6b694c46504c7056616373354c456d
```

But even with the integration it doesn't seem to enable telnet.

**Comment by cenobitedk** [comment]
Wait... the token had changed, so now I have this:
```
$ php miio-cli.php  --ip 192.168.1.57 --token 5a543262706b6a68334c72377a48554d --sendcmd '{"id":0,"method":"enable_telnet_service", "params":[]}'
Устройство 192.168.1.57 доступно и ответило:
{"code":0,"result":["ok"],"id":0}
```

That's positive! :)

That's the third or fouth time I see a new token for this device. Is it typical that it changes often?

**Comment by rezmus** [comment]
it should only change when you reset wifi and pair again.

**Comment by cenobitedk** [comment]
Okay, thanks for your help :)
