### ISSUE TITLE
please add giot.remote.v58kwm

### ISSUE THREAD

**Issue by LOVE2CMOL** [AlexxIT/XiaomiGateway3#1409]
please add giot.remote.v58kwm

doc： 
https://home.mi.com/webapp/content/baike/product/index.html?model=giot.remote.v58kwm#/
https://home.miot-spec.com/spec/giot.remote.v58kwm

thak you

**Comment by AlexxIT** [comment]
Try to write your own converter

**Comment by LOVE2CMOL** [comment]
commit #1410 😀

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
