### ISSUE TITLE
Heatold Thermostat TH1230W support

### ISSUE THREAD

**Issue by sulliwane** [AlexxIT/XiaomiGateway3#1416]
### The problem

Hi,
When trying to add the "[Heatold Thermostat TH1230W](https://home.mi.com/views/introduction.html?region=cn&pdid=12506&model=cubee.airrtc.1230w)" it just shows some details about it but doesn't add the device to HA / XiaomiGateway3:
![thermostat](https://github.com/user-attachments/assets/478c2db5-3694-4565-815b-dd2cb9a257cb)

Did I miss something?

Thanks a lot for your help! 🙏

Here is the [API documentation](https://home.miot-spec.com/spec/cubee.airrtc.1230w) for that specific device:
![image](https://github.com/home-assistant/core/assets/1733686/67b8e0d0-1c04-4ea4-840a-657ec3ec8f17)

### What version of Home Assistant Core has the issue?

core-2024.6.1

### What type of installation are you running?

Home Assistant Supervised

**Comment by AlexxIT** [comment]
WiFi devices not related to gateway and this integration
