### ISSUE TITLE
Is it possible to make the event reach Home Assistant faster?

### ISSUE THREAD

**Issue by ha0y** [AlexxIT/XiaomiGateway3#142]
Now I'm using both the old gateway(DGNWG02LM) and the new one(DMWG03LM). 
The old one has a native communication protocol, and Home Assistant can always handle the gateway event (button pressed etc.) in no time. For example, when I press a Zigbee button, the automation in Home Assistant can be triggered right away, no delay was felt. 
But for the new one with this component, there is sometimes a serious delay. It takes up to 1s that Home Assistant captures the event, no matter for zigbee or bluetooth devices. I tried to connect to the mqtt server of the gateway, and found that the event can always reach the gateway right away, but the time Home Assistant captures it varies. Sometimes Home Assistant reacts right away just like the old one; but for most times it was a long time(up to 1s) until Home Assistant captures this event. Thus, automatons triggered by zigbee and ble devices always makes me annoying.

Is it possible to make the event reach Home Assistant faster?

**Comment by AlexxIT** [comment]
You have some local problems. In my installation all works extremely fast.

**Comment by w27** [comment]
@AlexxIT Thank you. I will check my other devices to find out the problem. And I will keep this issue open to see if someone has the same problem.

**Comment by w27** [comment]
@AlexxIT I've just switched the gateway to ZHA mode. Now all the connected devices works extremely fast, which means that there are no problem with device connectivity. But in normal mode it is still lag, even if I migrate Home Assistant to my PC.

I tried to attach some debug output to the code, and found that the mqtt message was handled right away, but the state in Home Assistant was not updated in time. 

And I reviewed the code of official Xiaomi integration and found that it fires an event to Home Assistant when the message was received. Does this component waits Home Assistant to poll the state?

**Comment by w27** [comment]
❗❗❗❗❗❗
Just modified ``self.hass.bus.async_fire('xiaomi_aqara.click', {`` to ``self.hass.bus.fire('xiaomi_aqara.click', {`` and the state was updated faster than ever before!!!

I don't know why, but it just solves my problem. All I know is that the same part of ``xiaomi_aqara`` integration is not async.

Maybe others can try this and it may greatly improve the performance.

Finally, thanks for your great work!

**Comment by AlexxIT** [comment]
I think you have problems with whole Hass performance. You need to check which component do it.

**Comment by w27** [comment]
I am not using any 3rd party components except this one. Maybe it's because I'm running Hass on a low-performance computer stick. Just for my device, the sync firing works faster than the async one. I'm sorry that I'm not good at programming, so I have no idea about the reason.

**Comment by HeadFox** [comment]
+1 It solved my ranndom delay problem as well !
I have Aqara Wireless D1 single button (2020 version). I had no issue with automation and Homekit integration but with direct Hass integration I had a random delay (not every time) of 1 to 2 seconds.
But with the modification that @ha0y no delay at all

**Comment by AlexxIT** [comment]
Have you enable integration logs?

**Comment by HeadFox** [comment]
Where do you find this ?

**Comment by AlexxIT** [comment]
In integration options

**Comment by HeadFox** [comment]
Maybe I'm dumb but I can't find it. After I had these latency I decided to format my raspberry Pi4, and made a fresh install of supervised Hassio. No plugins installed. No settings touched. 
Is this option is in advanced mode ? 
The change definitely fixed the problem but maybe it's not the proper solution for this problem like you said. If you need me to debug or test something, I have a little bit of knowledge in python. :) 
And thanks for your awesome work on this plugin 💪

**Comment by AlexxIT** [comment]
Big logs make some delays in component. If you don't enable it - you don't have this problem.

**Comment by ha0y** [comment]
Logs are not enabled. The problem still exists in latest release. And the solution still works.

**Comment by AlexxIT** [comment]
Which trigger are you using? State or event? If event - try to use state. Check if it helps.

**Comment by ha0y** [comment]
I used the device trigger before, and I tried to use state trigger. It doesn't help. By the way, the state of these devices (e.g. button action) also reacts slower.

**Comment by AlexxIT** [comment]
Latest master version should fix this problem

**Comment by ha0y** [comment]
Fixed. Thanks!
