### ISSUE TITLE
Xiaomi Human Presence Sensor cannot be well recognized on Xiaomi Gateway 3

### ISSUE THREAD

**Issue by lrl193** [AlexxIT/XiaomiGateway3#1426]
Xiaomi Human Presence Sensor cannot be well recognized on Xiaomi Gateway 3. Causing the inability to use the sensor for automated settings normally, we hope to increase adaptability for better use.
![1724116236467](https://github.com/user-attachments/assets/7ac00240-257e-4352-a210-bdd7c8bdb4c9)

**Comment by zhangbabao** [comment]
<img width="1020" alt="微信图片_20240826120808" src="https://github.com/user-attachments/assets/d4592d82-615b-44a7-8b29-b9178add6edf">
确实无法识别实体

**Comment by lrl193** [comment]
thank you! With your guidance, I have resolved the issue. Looking forward to receiving even more perfect support in the next release.
