### ISSUE TITLE
Does it make sense to wait until there is a solution for ZNDMWG04LM with firmware 1.0.7 or is it a brick forever?

### ISSUE THREAD

**Issue by UncleSKO** [AlexxIT/XiaomiGateway3#1427]
If anyone has a solution, please let me know.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares

**Comment by UncleSKO** [comment]
Алекс, дякую. Я ходив по цьом посиланню і багато твоїх відео на ютуб передивився. В Github новачок, ще не дуже зрозумів як тут все оргнанізовано. Але з купи перечитаного зрозумів, що рішення поки немає, тому й запитав. Ключа не маю, тільки токен. Але, якщо б він і був, я так зрозумів, що мені б це не допомогло всеодно.  У мене квадратний європеєць ZNDMWG04LM. Написано Use UART. На відео ти клацаєш кнопки на круглому хабі, щоб відкрився телнет. На квадратному це теж працює? І якщо я куплю UART-адаптер, підпаяюсь до плати і якось перехоплю і розшифрую той ключ, він мені допоможе? Читав, що у людей які зберегли ключ, коли він був ще доступний в старих версіях, всеодно не можуть з ним підключити інтеграцію.

На Githubi наче вимога спілкування англійською, тому кидаю переклад.
Translation from Ua to Eng:
Alex, thank you. I followed this link and watched many of your YouTube videos. I'm new to Github, I still haven't really understood how everything is organized here. But from a lot of re-reading, I realized that there is no solution yet, that's why I asked. I don't have a key, only a token. But even if he was, I realized that it wouldn't help me anyway. I have a square European ZNDMWG04LM. It says Use UART. In the video, you click the buttons on the round hub to open telnet. Does it work on square too? And if I buy a UART adapter, solder it to the board and somehow intercept and decrypt that key, will it help me? I read that people who saved the key when it was still available in old versions still can't integrate with it.

**Comment by AlexxIT** [comment]
You should read whole issue about UART. This is not my solution. I have never use it. But you can get key for ZNDMWG04LM via UART method. And use it in this integration.

**Comment by jksmurf** [comment]
> You should read whole issue about UART. This is not my solution. I have never use it. But you can get key for ZNDMWG04LM via UART method. And use it in this integration.

I have a ZNDMWG04LM with 1.07_0019 FW. I did the UART check and succesfully got the Key (not the Token), based on [methods here]. This allowed me to ADD it to AlexxIT's Gateway 3 interface. In fact I did two of them. (https://github.com/AlexxIT/XiaomiGateway3/issues/1166).

My question however is about the need for telnet; I can access the Gateway menu using Putty, but no Admin/Password pair matches, so I cannot log in. I tried admin/admin, admin/blank, admin/123123 and a few other combinations.

- Do I need telnet access for anything in future? 
- If yes, is the only way to use UART, then downgrade the FW; and then strip out the password, so if I upgrade it again, it is blank? Is this possible and will blank password this be "sticky" if I upgrade the FW again?
- Is there some way to get Full Telnet Access using the Token+Key (which I now have saved) for each device?

Thx

![IMG_E0823](https://github.com/user-attachments/assets/5f5bdad2-c484-4473-a88f-98377a062081)

**Comment by matteos1** [comment]
this is the correct procedure ?
### How to Extract the Key for ZNDMWG04LM via UART on Windows

Here’s a step-by-step guide to obtaining the **key** for a **ZNDMWG04LM** device (e.g., a Xiaomi hub) using the **UART method** on a Windows machine.  

---

### **What You Need:**

#### **Hardware:**
- **UART cable** (e.g., a USB-to-TTL adapter such as CP2102 or FT232RL).
- **Jumper wires** (to connect the device to the PC via the UART adapter).
- A Windows PC.

#### **Software:**
- A serial terminal program, such as:
  - [[Putty](https://www.putty.org/)](https://www.putty.org/) (free).
  - [[Tera Term](https://ttssh2.osdn.jp/index.html.en)](https://ttssh2.osdn.jp/index.html.en) (free and user-friendly).
- USB-TTL adapter drivers (available from the manufacturer's website, e.g., for **CP2102** or **FT232RL**).
- A text editor like **Notepad++**.

---

### **Steps:**

#### **1. Install Drivers and Prepare the Hardware**
1. Download and install the driver for your USB-to-TTL adapter.
2. Connect the adapter to the **ZNDMWG04LM** device:
   - **TX (device)** → **RX (adapter)**.
   - **RX (device)** → **TX (adapter)**.
   - **GND (device)** → **GND (adapter)**.
3. Plug the adapter into your PC via USB.

#### **2. Check the COM Port**
1. Open **Device Manager** on Windows.
2. Look under "Ports (COM & LPT)" to find the COM port assigned to your adapter (e.g., "COM3").
3. Note the COM port number for configuring the terminal software.

#### **3. Configure the Terminal Software (Tera Term or Putty)**
1. Open your chosen terminal program (e.g., **Tera Term** or **Putty**).
2. Select **Serial** as the connection type and input the COM port number.
3. Configure the serial connection parameters:
   - **Baud rate:** 115200.
   - **Data bits:** 8.
   - **Parity:** None.
   - **Stop bits:** 1.
   - **Flow control:** None.

#### **4. Access the Device Console**
1. Restart the **ZNDMWG04LM** device.
2. During the boot process, you should see logs appear in the terminal.
3. Look for a prompt or messages indicating access to the device's console.

#### **5. Extract the Key**
1. At the console prompt, type the following command to access the configuration file:
   ```
   cat /data/miio/device.conf
   ```
2. Press **Enter**. This should display a file containing device information, including the key:
   ```
   key=YOUR_DEVICE_KEY
   ```
3. Copy the **key** from the output.

#### **6. Save and Use the Key**
1. Paste the key into **Notepad++** or another text editor and save it for future use.
2. Use this key in your desired integration (e.g., **Home Assistant** or similar platforms).

---

### **Important Notes:**
- Be cautious when accessing the device's firmware via UART to avoid accidentally modifying or corrupting system files.
- Some devices may require additional steps, such as rooting or using a custom firmware, to access the required data.

If you encounter issues with the hardware connection, terminal configuration, or key extraction, let me know—I’m here to help!
