### ISSUE TITLE
3.3.6 How about supporting the latest Xiaomi's People in Sensors by adding part of the code

### ISSUE THREAD

**Issue by MagicStarTrace** [AlexxIT/XiaomiGateway3#1437]
I'm using gw3 version 3.3.6, is there any good way to get it to support “Xiaomi People in Sensors” (sensor_occupy), I don't want to upgrade to the latest version, is there any way to add a portion of the code to make this happen?

Currently hass-xiaomi-miot can already see xiaomi.sensor_occupy.03 

Thank You！

**Comment by AlexxIT** [comment]
You can make your own edits to the source code of the old version of the component.
