### ISSUE TITLE
no device found for xiaomi_gateway3

### ISSUE THREAD

**Issue by henrykey** [AlexxIT/XiaomiGateway3#144]
installation is fine and added my xiaomi gateway but no device added. from option can list all bls and wifi device but zigbee.
what problem could be? or what I missed?
Home Assistant OS 5.8 
Xiaomi Gateway3: ZNDMWG03LM, firmware:1.4.7_0065
PS. I didn't find any from system log. is it necessary to set log level to debug?

Thanks!
Henry

**Comment by AlexxIT** [comment]
You missed reading the documentation. 1.4.7_0065 supported only after soldering.

**Comment by baobaobuku1210** [comment]
I swiped the firmware with Telnet, but I also had trouble finding the device
fw is 1.4.7_0065

**Comment by henrykey** [comment]
oh, I see. 
By the way, is there any method to solder or to degrade the firmware?
Thanks!

**Comment by AlexxIT** [comment]
You again don't read docs...

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant

**Comment by baobaobuku1210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
