### ISSUE TITLE
Setup failed - Home Assistant Core 2024.9.0

### ISSUE THREAD

**Issue by mari8b** [AlexxIT/XiaomiGateway3#1442]
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

**Comment by AlexxIT** [comment]
#1434

**Comment by Nismonx** [comment]
why raising a dubbed issue ?
https://github.com/AlexxIT/XiaomiGateway3/issues/1434

**Comment by mari8b** [comment]
Sorry, my fault...

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6
