### ISSUE TITLE
無法加入裝置整合

### ISSUE THREAD

**Issue by bossben8** [AlexxIT/XiaomiGateway3#1447]
更新後出現錯誤無法加入整合: ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration xiaomi_gateway3: cannot import name 'Converter' from 'custom_components.xiaomi_gateway3.core.converters.base' (/config/custom_components/xiaomi_gateway3/core/converters/base.py)
要加入整合出現:錯誤
設定流程無法載入: {"message":"Invalid handler specified"}

**Comment by AlexxIT** [comment]
Не понимаю
