### ISSUE TITLE
lumi.switch.l3acn3 Unable to receive wireless switch message

### ISSUE THREAD

**Issue by lydigaga** [AlexxIT/XiaomiGateway3#1448]
![123](https://github.com/user-attachments/assets/302558c3-3a4b-4072-aeb8-c5a397dbf86b)
I have switched the three buttons to wireless on/off mode, but gw3 seems unable to receive the message

**Comment by AlexxIT** [comment]
`Zigbee: None` is bad. You should pair this device again. Better to do this via MiHome.

**Comment by lydigaga** [comment]
After I restarted the home assistant, the Action appeared
