### ISSUE TITLE
The curl command for downloading socat is no longer available. Use wget instead

### ISSUE THREAD

**Issue by w27** [AlexxIT/XiaomiGateway3#145]
I've tried to switch to ZHA mode according to the documentation, but failed to configure ZHA integration with "Failed to connect". The socat was not running on the gateway. After reviewing the code, I found that the command uses ``curl`` which was not available on my firmware. After switching to wget, it works normally.

Firmware version: 1.4.7_0065(modified)

![20201220170148](https://user-images.githubusercontent.com/30557072/102709381-1a3bc200-42e5-11eb-986b-1b9adbbbccb3.jpg)

**Comment by zvldz** [comment]
https://github.com/niceboygithub/XiaomiGateway3fw/issues/3

**Comment by w27** [comment]
Thanks.
