### ISSUE TITLE
Telnet Login incorrect on DMWG03LM 1.0.8_0001

### ISSUE THREAD

**Issue by catsimple** [AlexxIT/XiaomiGateway3#1466]
just update my DMWG03LM from 1.0.7_0021 to 1.0.8_0001, then I'm not able to connect via Telnet.
I tried username: admin and empty password or password: admin, what I got is 'Login incorrect' while Gateway3 component working fine. any idea?

**Comment by AlexxIT** [comment]
DMWG03LM never had admin user. It has only root user.

**Comment by catsimple** [comment]
> DMWG03LM never had admin user. It has only root user.

So sorry! I goofed.
