### ISSUE TITLE
The Home Assistant Core version has been updated to 2024.10.1, but the integration error reports that it cannot be loaded.

### ISSUE THREAD

**Issue by ma303973022** [AlexxIT/XiaomiGateway3#1467]
As mentioned, the device is Xiaomi Intelligent Multi-mode Gateway 2, firmware version 1.03_0028, Home Assistant Core version updated to 2024.10.1, the integration error cannot be loaded.
[home-assistant_2024-10-07T08-54-35.852Z.log](https://github.com/user-attachments/files/17275957/home-assistant_2024-10-07T08-54-35.852Z.log)
[homeassistant.util.loop.txt](https://github.com/user-attachments/files/17275983/homeassistant.util.loop.txt)
[homeassistant.setup.txt](https://github.com/user-attachments/files/17275993/homeassistant.setup.txt)

**Comment by AlexxIT** [comment]
#1434
