### ISSUE TITLE
Aqara T1 E27 LED Bulb missing controls

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/XiaomiGateway3#1470]
Aqara T1 E27 LED Bulb missing controls - power-off memory, on\off-transition time

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:lumi-acn014:1

![image](https://github.com/user-attachments/assets/3de39dc2-0852-4962-9bb9-85b4ba9dd480)

**Comment by to4ko** [comment]
@AlexxIT  update - aqara t1 e27 (ZNLDP14LM, lumi.light.acn014) and aqara e27 lamps (ZNLDP12LM, lumi.light.aqcn02) - no **color temperature** control via integration. only brightness can be set.

**Comment by AlexxIT** [comment]
I have this model and can control color temperature:
Zigbee: ZNLDP12LM, lumi.light.aqcn02
Firmware: 32
Hardware: 1

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7
