### ISSUE TITLE
 lumi.gateway.mgl03 alarm control broken after update to HASS 2024.11

### ISSUE THREAD

**Issue by sdimitrov-sms** [AlexxIT/XiaomiGateway3#1484]
So after the upgrade to HASS 2024.11 looks like the alarm control for the Gateway: ZNDMWG03LM, ZNDMWG02LM, YTC4044GL, lumi.gateway.mgl03 broke. It works in terms of actions, but it doesn't show the current status:

<img width="935" alt="image" src="https://github.com/user-attachments/assets/b4942979-e279-4829-96e3-50e2a25ec1de">
<img width="935" alt="image" src="https://github.com/user-attachments/assets/5c0e2f0e-3928-4063-8e4d-e9d1b7af481f">

I tried rebooting HA and the Gateway but doesn't seem to solve the issue.

**Comment by sdimitrov-sms** [comment]
> @AlexxIT: I had the same issue with my Aqara M1S CN, this fixed the problem of "unknown status":
> 
> [niceboygithub/AqaraGateway@37c33e0](https://github.com/niceboygithub/AqaraGateway/commit/37c33e01610435234ab2583721dac56f64f69ec8)

Trying to understand in the code where can this fit, however, the way both are set up works differently (Aqara component and this one)

**Comment by shift-del1** [comment]
Yes, I also came to this conclusion, however I wanted to share this in case it can point anyone in the right direction.

**Comment by matteos1** [comment]
not work also for me

**Comment by MiroG225** [comment]
Same here. I can control the gateway, but status in HA is Unknown. Looks like HA->Gateway works, but Gateway->HA doesn't. Conected devices (ble door sensor, temp/hum clock) work as before.

**Comment by shift-del1** [comment]
This was written in the release log:

https://developers.home-assistant.io/blog/2024/10/22/new-alarm-state-property/

**Comment by matteos1** [comment]
Some solution?

**Comment by NunoOliveira** [comment]
I'm having the same issue.

```
custom_components.xiaomi_gateway3.alarm_control_panel.XAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
```

**Comment by AlexxIT** [comment]
Solution - master version

**Comment by MiroG225** [comment]
> Solution - master version

Don't get it

**Comment by sviperz** [comment]
@MiroG225 download and apply the _master_ version of integration.

Alternatively replace your _alarm_control_panel.py_ with the file from the _master_ branch.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7
