### ISSUE TITLE
The curtain motor cannot be controlled in HomeKit

### ISSUE THREAD

**Issue by meineihan** [AlexxIT/XiaomiGateway3#1485]
The curtain motor cannot be controlled in HomeKit, but the status can be updated. I added the motor to HomeKit using HomeKit Bridge, and I could control it before, but not now. It only works properly when the type is selected as garage door or gate. If I connect it to HomeKit via Xiaomi Miot Auto, I can also control it.
Home Assistant version is 2024.11.0, but it seems to have stopped working since 2024.10.3, and I'm not sure which version it started to fail.

**Comment by AlexxIT** [comment]
Start from device diagnostics. I have no idea what device you talking about.

**Comment by AlexxIT** [comment]
It's a strange converter. It's not in the component. Maybe there's a bug in it.
It's definitely not supposed to be like this: `"target-position"`, `"target_position"`

**Comment by meineihan** [comment]
> It's a strange converter. It's not in the component. Maybe there's a bug in it. It's definitely not supposed to be like this: `"target-position"`, `"target_position"`

But it works fine in Home Assistant, and I have been using this motor for almost a year. It also worked fine in HomeKit before. It has only recently started to become uncontrollable. When I click the icon in HomeKit, it prompts that it is shutting down, but the motor does not actually move.
![QQ图片20241108212707](https://github.com/user-attachments/assets/c21ab0f7-9193-4428-b991-ec939bdbfab5)

**Comment by AlexxIT** [comment]
Because your converter wrong. Target position shouldn't be a number. It should be helper for cover. Without domain and with right name. Check other cover covers.

**Comment by meineihan** [comment]
> Because your converter wrong. Target position shouldn't be a number. It should be helper for cover. Without domain and with right name. Check other cover converters.

>     10807: ["Linptech", "Linp Smart Curtain Motor", "linp.curtain.c2"],
    "spec": [
        MapConv("motor", "cover", mi="2.p.1", map={0: "stop", 1: "open", 2: "close"}),
        BaseConv("target_position", mi="2.p.2"),
        MathConv("target-position", "number", mi="2.p.2", min=0, max=100, entity=ENTITY_CONFIG),
        CurtainPosConv("position", mi="2.p.3"),
        BaseConv("motor_reverse", "switch", mi="2.p.4"),
        MapConv("mode", "select", mi="2.p.5", map={0: "default", 1: "doublmode", 2: "leftmode", 3: "rightmode"}),
    ],
Now it works!Thx!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7
