### ISSUE TITLE
[Device support] Add support for line.switch.fkgh43

### ISSUE THREAD

**Issue by Blue-Beaker** [AlexxIT/XiaomiGateway3#1486]
Integration version: 4.0.6  
Gateway: 1.5.6_0001 (paired with this integration before updating)  
I have a line.switch.fkgh43, and it appears in the integration as 'Unknown mesh' with id 13931.  
It has 3 switches but only the leftmost one is recognized and controllable by the integration.  
![图片](https://github.com/user-attachments/assets/6d245f2f-b00c-4859-903f-53d817d78cd2)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7
