### ISSUE TITLE
UnitOfConductivity.MICROSIEMENS + STATE_ALARM_TRIGGERED was used - please report it to the author

### ISSUE THREAD

**Issue by bobofruit1970** [AlexxIT/XiaomiGateway3#1489]
*HA version
![image](https://github.com/user-attachments/assets/01631f8e-a3ca-47bc-b411-bb6363655f7e)

*Gateway3 Integration version
v4.0.6

*Gateway and Firmware  version
![image](https://github.com/user-attachments/assets/2bd40db2-8fcf-4f36-b3c6-fcce99b0f415)

*Warning in log suggesting reporting to the integration author
![image](https://github.com/user-attachments/assets/8bc94ff9-0e45-4def-85a1-b56525e63315)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7
