### ISSUE TITLE
Support Aqara Smart Lock N200 (ZNMS17LM)

### ISSUE THREAD

**Issue by NathanDai** [AlexxIT/XiaomiGateway3#149]
https://homekitnews.com/2020/03/09/aqara-n200-smart-lock
[N200](https://homekitnews.com/2020/03/09/aqara-n200-smart-lock)

**Comment by AlexxIT** [comment]
Why you opened two issue?

**Comment by NathanDai** [comment]
sorry ,my network not good, I accidentally sent it . But could you support Aqara lock n200

**Comment by AlexxIT** [comment]
Maybe it already supported. BLE devices doesn't depend on model.

**Comment by NathanDai** [comment]
ZNMS17LM , This is its model. I ordered this lock online, and I'll test it next week.

**Comment by my7hcry** [comment]
![image](https://user-images.githubusercontent.com/71775933/103205952-af6a3680-4935-11eb-844f-c113cd64ace7.png)

I have a aqara N200 , it only have  two entities.

**Comment by AlexxIT** [comment]
@my7hcry try to do something with the lock. Open/close in different ways. Change some modes, etc.

**Comment by NathanDai** [comment]
i get my n200 lock and it works ok
