### ISSUE TITLE
Mi Cloud integration

### ISSUE THREAD

**Issue by Gregorountoi** [AlexxIT/XiaomiGateway3#1495]
Good day
Today I've found what integration broken
![issue1](https://github.com/user-attachments/assets/6ee1d85a-d6d0-4888-a416-cb7fa10742c5)
I have latest release of Xiaomi Gateway 3 and HA
![issue](https://github.com/user-attachments/assets/60a01a62-ae3d-4e2b-bed3-5e9e86483367)
Trying to reconfig - adding name, password... I've asked to go to web resource
I've asked to go to web resource and it shows me - Ok
![issue2](https://github.com/user-attachments/assets/527af562-ed39-453f-8870-e5a5c75bf5db)
But nothing happened on config page - it still ask me go to web page... again and again

**Comment by AlexxIT** [comment]
You can also relogin to mobile app. Sometimes it helps.

**Comment by Gregorountoi** [comment]
Nope. Mobile App relogin without any issues, but no luck in plugin Mi Cloud auth

**Comment by AlexxIT** [comment]
Try only one server at a time

**Comment by Gregorountoi** [comment]
No luck. Still endlessly asking to go to web page(((

**Comment by AlexxIT** [comment]
Requested for both servers? For both RU and CN?

**Comment by Gregorountoi** [comment]
Yes. I have another instance. Updated 2 month ago. It's Ok... Deleting/adding/starting normally

**Comment by AlexxIT** [comment]
So you can stop HA, copy one config entry from `/.storage/core.config_entries` from another HA, and run HA again.

**Comment by Gregorountoi** [comment]
Copy this entry - no luck
{"created_at":"1970-01-01T00:00:00+00:00","data":{"password":"xxxxxx","servers":["cn","ru"],"username":"xxxxxxx"},"disabled_by":null,"discovery_keys":{},"domain":"xiaomi_gateway3","entry_id":"xxxxxx","minor_version":1,"modified_at":"1970-01-01T00:00:00+00:00","options":{},"pref_disable_new_entities":false,"pref_disable_polling":false,"source":"user","title":"xxxxxx","unique_id":null,"version":4},

**Comment by Gregorountoi** [comment]
Solved. Changed Internet provider to mobile operation and problem is gone)
