### ISSUE TITLE
Add support Yeelight Classic Group yeelink.light.dn2grp

### ISSUE THREAD

**Issue by mpiexec** [AlexxIT/XiaomiGateway3#1501]
Only select domain available for Mesh Group entity, ie:

```
select.1862110441464549376_command
```

are mesh group (created via Yeelight Classic) supported?

**Comment by mpiexec** [comment]
<img width="808" alt="Screenshot 2024-11-28 at 16 29 13" src="https://github.com/user-attachments/assets/65ff4704-d266-4b4b-971a-25b62be02760">
<img width="490" alt="Screenshot 2024-11-28 at 16 22 27" src="https://github.com/user-attachments/assets/0c9c1a76-39d0-4ae0-aba9-bce14d999249">

**Comment by rayout** [comment]
![image](https://github.com/user-attachments/assets/935bd320-f6d2-47c9-ab2e-5a2b3f683b4a)

I just recreated the group in Mi Home. It has a different interface now, and the integration is displayed differently. It works now.

**Comment by mpiexec** [comment]
@rayout yes, it works, but finally I gave up on the idea of creating groups cos automations sometimes didn't work with such entity, for example, when I pressed the switch again immediately after turning on the lamps, sometimes there was no reaction

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8

**Comment by mpiexec** [comment]
@AlexxIT 

Thanks, now I can switch it on or off, but what about toggle action? I tried to replace automation with on/off + condition, but yeelight classic group doesn't expose current state :(

**Comment by AlexxIT** [comment]
All Xiaomi groups do not provide the current status. They're only for management.

**Comment by mpiexec** [comment]
Ok, but what about toggle action? Is it possible to expose that one?

**Comment by AlexxIT** [comment]
I can research about this feature. You can create separate issue.
