### ISSUE TITLE
Add support ydhome.switch.s2

### ISSUE THREAD

**Issue by gujiys** [AlexxIT/XiaomiGateway3#1507]
Please help add new device
https://home.miot-spec.com/spec/ydhome.switch.s2

**Comment by gujiys** [comment]
from custom_components.xiaomi_gateway3.core.devices import *

DEVICES = [{
    2448: ["ydhome", "Two-Button Switch ", "ydhome.switch.s2"],
    "spec": [
        BaseConv("left_switch", "switch", mi="2.p.1"),
        BaseConv("right_switch", "switch", mi="3.p.1"),
    ]
}] + DEVICES

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
