### ISSUE TITLE
Manage ringtone

### ISSUE THREAD

**Issue by Sagittaq2** [AlexxIT/XiaomiGateway3#151]
Hi,

Is possible manage ringtone (start/stop) from HA?

For example, to start or stop a ringtone with a switch.

Regards

**Comment by Sagittaq2** [comment]
Any news? Or an alternative to execute commands...

**Comment by AlexxIT** [comment]
v1.3.0 support `alarm_trigger`. You can enable and disable it via services

**Comment by Sagittaq2** [comment]
Ok. Thank!! I'll be waiting for manage diferents ringtones, too

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#xiaomi-multimode-gateway-beeper
