### ISSUE TITLE
请添加：V5无线一键开关 （BLE）集成

### ISSUE THREAD

**Issue by HASSAAS** [AlexxIT/XiaomiGateway3#1517]
DEVICES = [{
    16191: ["Lingju", "BLE Wireless Button", "giot.remote.v51kwm"],
    "spec": [
        BaseConv("action", "sensor"),
        MapConv("action", mi="2.e.1012.p.1", map={1: BUTTON_SINGLE}),
        MapConv("action", mi="2.e.1013.p.1", map={1: BUTTON_DOUBLE}),
        MapConv("action", mi="2.e.1014.p.1", map={1: BUTTON_HOLD}),
    ],
}] + DEVICES
设备ID:16191
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:remote-control:0000A021:giot-v51kwm:1
辛苦大佬了~！

**Comment by wangyz1997** [comment]
Done in #1518.

**Comment by wangyz1997** [comment]
Support added by 8b2a574522833150f03acba2c6d4551972815ec8. You can test if it works and close this issue.

对设备的支持已由8b2a574522833150f03acba2c6d4551972815ec8添加，你可以测试可用后关闭issue。

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
