### ISSUE TITLE
Add silence sensor to Aqara smart natural gas detector JT-BZ-01AQ/A

### ISSUE THREAD

**Issue by BrkOne** [AlexxIT/XiaomiGateway3#1519]
Model: JT-BZ-01AQ/A (lumi.sensor_gas.acn02)
Vendor: Xiaomi
Description: Aqara smart natural gas detector
Exposes: gas, gas_density, gas_sensitivity, selftest, test, buzzer, buzzer_manual_alarm, buzzer_manual_mute, linkage_alarm, linkage_alarm_state, state, power_outage_count, linkquality

Request add Buzzer manual mute.Thank you very much

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:gas-sensor:0000A022:lumi-acn02:1

https://www.zigbee2mqtt.io/devices/JT-BZ-01AQ_A.html#xiaomi-jt-bz-01aq%252Fa

**Comment by AlexxIT** [comment]
Just for information, this is a sensor whose value cannot be changed.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
