### ISSUE TITLE
Fix led switch for 090615.switch.aidh1 and 090615.switch.aidh2

### ISSUE THREAD

**Issue by KleinerSource** [AlexxIT/XiaomiGateway3#1527]
12470: ["PTX", "Mesh Single Wall Switch (no N)", "090615.switch.aidh1"],
    12471: ["PTX", "Mesh Double Wall Switch (no N)", "090615.switch.aidh2"],

BoolConv("led", "switch", mi="9.p.1"),  # config
Should be changed to
BaseConv("led", "switch", mi="9.p.1"),  # config

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the converter for the 'led' attribute from BoolConv to BaseConv to address the issue with PTX Mesh Single and Double Wall Switches (no N).

You can review changes in this commit: https://github.com/mark-addams001881/AlexxIT-XiaomiGateway3-1527/commit/6f13e85dc57678abf5f4c89eb5075cd8c13a4082.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by AlexxIT** [comment]
Terrible commit from AI. Neural network doesn't know the basics of python at all.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8
