### ISSUE TITLE
linp.sensor_occupy.es2, all the sensors show the status of "unkonwn". v4.0.8

### ISSUE THREAD

**Issue by alexanderxue** [AlexxIT/XiaomiGateway3#1529]
linp.sensor_occupy.es2, all the sensors show the status of "unkonwn".
v4.0.8
![image](https://github.com/user-attachments/assets/22c4f881-1245-4368-9d23-811eadce32b3)
```
    "version": "4.0.8",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.0003844919992843643
    },
    "cd19feeaa50fb8efc48edfe1c1d69735": {
      "config_entry_setup": 1.1907446770001116
    },
    "01JG6M85V6VS54XHAZJ49W7H85": {
      "config_entry_setup": 1.271278086998791
    },
    "8dd81f889f6c07c34b6388170e509551": {
      "wait_import_platforms": -3.181230737000078,
      "wait_base_component": -0.001549116999740363,
      "config_entry_setup": 3.199978172000556
    }
  },
  "data": {
    "version": "448b59b",
    "options": {
      "debug": [],
      "host": "192.168.50.99",
      "key": "uYYGv5mG0bHgc5os",
      "stats": true,
      "token": "32644f79675768714a4e4e5667523457"
    },
    "errors": [],
    "device": {
      "available": true,
      "extra": {
        "did": "blt.3.1jvfo5d6c4k03",
        "type": "ble",
        "mac": "a4:c1:38:07:38:c3",
        "cloud_name": "\u6b21\u5395\u4eba\u5728\u4f20\u611f\u5668",
        "cloud_fw": "2.1.1_0048",
        "market_brand": "Linptech",
        "market_name": "Human Presence Sensor ES3",
        "market_model": "ES3BB, linp.sensor_occupy.es2",
        "seq": 94,
        "rssi_54ef44385a71": -66
      },
      "last_seen": {
        "54ef44385a71": "19m22s"
      },
      "listeners": 6,
      "model": 20731,
      "params": {},
      "ttl": "1h5m",
      "uid": "a4c1380738c3"
```

**Comment by AlexxIT** [comment]
Your sensor hasn't sent anything yet.

**Comment by alexanderxue** [comment]
![Screenshot_2024-12-29-08-21-12-912_com xiaomi smarthome](https://github.com/user-attachments/assets/5ef90078-979e-49d5-b1c5-4636e7abe700)
But it's normal in mi home application

**Comment by 13860605362** [comment]
> ![Screenshot_2024-12-29-08-21-12-912_com xiaomi smarthome](https://private-user-images.githubusercontent.com/49608016/399130936-5ef90078-979e-49d5-b1c5-4636e7abe700.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MzY2NTcsIm5iZiI6MTczNTQzNjM1NywicGF0aCI6Ii80OTYwODAxNi8zOTkxMzA5MzYtNWVmOTAwNzgtOTc5ZS00OWQ1LWIxYzUtNDYzNmU3YWJlNzAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDAxMzkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNDk2NjQ0MjI3NmFlOGEzZDc5N2I4OTRjOWFiY2U4MjI3ZTA4Mzc5YjNhNzdmMDg2ZDVkMWRmZWYyN2VmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VdzegYWlT37aKf49WXt3vnppZvu5Er1oiRtWQ-HUC3c) But it's normal in mi home application

I had the same problem

**Comment by AlexxIT** [comment]
MiHome can get data from another gateways, etc. You can enable debug logs and check them.

**Comment by alexanderxue** [comment]
[home-assistant.log](https://github.com/user-attachments/files/18274098/home-assistant.log)

**Comment by AlexxIT** [comment]
No any data from this sensor

**Comment by alexanderxue** [comment]
My Xiaomi Multimode Gateway's Firmware is 1.5.1_0032. Do u think it caused the problem?

**Comment by alexanderxue** [comment]
I upgraded the Firmware to 1.5.6_90 .And It sovled. Thank u
![Screenshot_2024-12-30-20-25-52-515_io homeassistant companion android](https://github.com/user-attachments/assets/09183cce-f3b1-4cd1-a404-1f4aa8d79722)
