### ISSUE TITLE
Manage XiaoMi Gateway 3 Alert Mode

### ISSUE THREAD

**Issue by itispip** [AlexxIT/XiaomiGateway3#153]
Can Alert Mode be managed through this component?

Tried Xiaomi Miio component in HA official integration, it can only control the Alert Mode of Gateway 2; As to this component, it didn't discover Alert Mode at all.

**Comment by mikeinblue** [comment]
same questions

**Comment by elenril2** [comment]
I've also tried Xiaomi Miio integration but with the Gateway 3 it failed:
[homeassistant.components.xiaomi_miio.gateway] DeviceException during setup of xiaomi gateway with host ...
Is there any plans for alarm integration (check status, on/off alarm modes) in this component?

**Comment by AlexxIT** [comment]
Duplicate #133
