### ISSUE TITLE
Flash success, but after reboot still old firmware

### ISSUE THREAD

**Issue by shanglanxin** [AlexxIT/XiaomiGateway3#154]
I used main method to flash firmware from **v1.4.6_0043** (out of box) to custom **1.4.6_0012** as [link](https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/uart_recovery) said, all went properly.
But after reboot, I add gateway3 in HA, there were no entities and devices, so I checked and found that telnet can't access and the version of current firmware still was **v1.4.6_0043** old one.
I was confused, although I solved this by decode the telnet password at last.

maybe the flash happened in different space as the boot pointed to? 
or maybe this was a bug ?

**Comment by AlexxIT** [comment]
There was bug in custom. Download and update once again

**Comment by freestylergit** [comment]
Same issue, Gateway 1.4.6_0043 from factory, after successful flash custom [1.4.6_0012](https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20201223), still have 1.4.6_0043

For test, i was update gateway on latest firmware through MiHome, and after flashing custom, its downgrade to 1.4.6_0043 but still not working with HA integration.

**Comment by AlexxIT** [comment]
Maybe it has password on telnet?

**Comment by freestylergit** [comment]
Telnet disabled, even on custom firmware.

**Comment by shanglanxin** [comment]
@AlexxIT You mean the latest version in [link](https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20201223) which was uploaded yesterday?
I already tried it yesterday after the new firmware uploaded 13 hours later yesterday.

@freestylergit maybe you can try decode telnet password as I did? [direct link](https://github.com/AlexxIT/XiaomiGateway3/wiki/Decode-Telnet-Password)

**Comment by AlexxIT** [comment]
There is still problem in custom 1.4.6. You need to wait update our flash 1.4.7. It's fine

**Comment by shanglanxin** [comment]
Got it.
Thanks for your support and wish you a happy new year in advance.
