### ISSUE TITLE
ERROR: Unable to discover the device XX.XX.XX.XX

### ISSUE THREAD

**Issue by rkrotov** [AlexxIT/XiaomiGateway3#155]
Hi.
I am downgrade gateway to 1.4.7_0065 #20201211 (custom, telnet enable).
Whith add gateway in HA - ERROR: Unable to discover the device.
Can I see the log discover?
I can not perform downgrade below(1.4.6), after rebooting the factory version.

**Comment by AlexxIT** [comment]
Do you try reboot gate? Or reset gate?

**Comment by rkrotov** [comment]
Yes.
Reboot & reset.
Telnet worked.
I have HA and gate on different networks.
Only TCP is used?

**Comment by AlexxIT** [comment]
Only TCP. Hass and gate can work from different networks.

**Comment by AlexxIT** [comment]
Is your problem solved?

**Comment by rkrotov** [comment]
I got many new errors after updating.
I haven’t dealt with this in detail yet. Propose to close the issue because the error is not repeated.
