### ISSUE TITLE
Integration doesn't work after gateway restart if there is no Internet

### ISSUE THREAD

**Issue by freeball155** [AlexxIT/XiaomiGateway3#156]
I noticed that if after restarting the gateway there is no Internet, the integration does not work. I noticed it by chance. The electricity went out, then it appeared. Everything went up, but there was no Internet. The gateway pinged, but nothing worked - the readings from the sensors were not updated, the switches or lamps did not turn on (or did not turn off). When trying to make a telnet to the gateway, there were two outcomes: 
1) the telnet just hung up - I have seen this when there are problems with DNS and the device cannot do a reverse lookup
2) the telnet attempt was immediately discarded - connection refused

But as soon as the Internet appeared, everything immediately worked.

I have the integration configured through mi cloud credentials. Perhaps the problem is that after gateway restart, the integration tries to get the token from the xiaomi servers and cannot, because no Internet. Maybe saving the token somewhere inside the Home Assistant will help? And yes, I forgot to say, the server with the HA did not restart - I have it connected via UPS.

**Comment by AlexxIT** [comment]
What firmware on your gateway?

**Comment by freeball155** [comment]
1.4.6_0012

**Comment by AlexxIT** [comment]
Usual helps reboot gateway when some problem with connection.

**Comment by adizanni** [comment]
Hello, in version 1.4.6_0043 after the gateway reboots, the telnet is not open until it raches internet access; confirmed the issue

**Comment by freeball155** [comment]
Hello.

Can I help somehow to solve this problem? 

This is how it looks:
1) the gateway has rebooted and at this moment there is no Internet access::
sb@raspberrypi:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 10.100.35.129 icmp_seq=1 Destination Host Unreachable
From 10.100.35.129 icmp_seq=4 Destination Host Unreachable
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 received, +2 errors, 100% packet loss, time 7ms

2) the gateway is connected:
sb@raspberrypi:~$ ping 192.168.88.104
PING 192.168.88.104 (192.168.88.104) 56(84) bytes of data.
64 bytes from 192.168.88.104: icmp_seq=1 ttl=64 time=1.33 ms
64 bytes from 192.168.88.104: icmp_seq=2 ttl=64 time=0.869 ms

3) but telnet or mqtt does not work:
sb@raspberrypi:~$ telnet 192.168.88.104
Trying 192.168.88.104...
telnet: Unable to connect to remote host: Connection refused
sb@raspberrypi:~$ telnet 192.168.88.104 1883
Trying 192.168.88.104...
telnet: Unable to connect to remote host: Connection refused

As soon as the Internet is repaired, everything immediately starts working without additional gateway reboots or restarting the integration.

**Comment by AlexxIT** [comment]
I confirm the problem. This cannot be fixed on the original firmware. On custom - it is not yet clear

**Comment by SosoKapianidze** [comment]
Any news? I have same problem, how can I recover connection to hub? Log says that there's problem with telnet

**Comment by freeball155** [comment]
I switched to the custom version of firmware (1.4.6_0012 #20210127) and the problem seems to be completely gone.
For verification, I turned off the Internet access and rebooted the gateway. Immediately after loading, the gateway began to respond to ping, I was able to log in via telnet to the gateway. MQTT also started immediately.

**Comment by wzwick** [comment]
> I switched to the custom version of firmware (1.4.6_0012 #20210127) and the problem seems to be completely gone. For verification, I turned off the Internet access and rebooted the gateway. Immediately after loading, the gateway began to respond to ping, I was able to log in via telnet to the gateway. MQTT also started immediately.

I have had endless issues with this as well - how did you roll back the firmware?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
