### ISSUE TITLE
Add Support BLE mesh Switch，plz！

### ISSUE THREAD

**Issue by fengguanghou** [AlexxIT/XiaomiGateway3#157]
The Bluetooth mesh switch is now recognized as a light, not a switch, please fix it and add device support, thank you!

**Comment by lipwah** [comment]
please fix it and add device support, thank you!

**Comment by mikeinblue** [comment]
hey,plz check out this,hope can help u guys. https://github.com/hellkun/XiaomiGateway3

**Comment by fengguanghou** [comment]
> hey,plz check out this,hope can help u guys. https://github.com/hellkun/XiaomiGateway3
Thank you, This is a great project！but there is an error in this branch, and it seems there are still some problems getting the BLE device status.
Hope you can improve it soon，Thank you again。

**Comment by hellkun** [comment]
> > hey,plz check out this,hope can help u guys. https://github.com/hellkun/XiaomiGateway3
> 
> Thank you, This is a great project！but there is an error in this branch, and it seems there are still some problems getting the BLE device status.
> Hope you can improve it soon，Thank you again。

It's just a fork of this repo, only with a few mesh switches supported. It's not supposed to break anything other than BLE mesh devices. Could you provide some details about the problems you were referring to?

**Comment by fengguanghou** [comment]
Thank you very much for fixing this bug, now the BLE mesh switch is working! This is awesome, thank you again!
@AlexxIT

**Comment by AlexxIT** [comment]
Main work done by @hellkun 👍

**Comment by mikeinblue** [comment]
@AlexxIT @hellkun Thank you so much .it's worked perfectly
