### ISSUE TITLE
1.4.7_0115 is unsupported

### ISSUE THREAD

**Issue by vtiorsimoes** [AlexxIT/XiaomiGateway3#159]
Hi,

I have the new firmware version: 1.4.7_0115.

But no devices are show up.

**Comment by hellkun** [comment]
Are you using stock firmware?
My custom 1.4.7_0115 works fine.

**Comment by vtiorsimoes** [comment]
> My custom 1.4.7_0115 works fine.

Yes i am using stock firmware. Do I have to put custom firmware?

**Comment by AlexxIT** [comment]
Stock 1.4.7 unsupported. This is written in readme and when configuring the integration.
