### ISSUE TITLE
Добавить возможность смены названий через yaml конфиг - Add naming option via yaml config

### ISSUE THREAD

**Issue by AlexQuaken** [AlexxIT/XiaomiGateway3#161]
Добавить возможность смены названий через yaml конфиг. Сейчас все названия по-умолчанию формируются из мак адреса, а переименование вручную не дает эффекта на т.к. имена зависимых сущностей (таких как качество связи, мощность, и другие) остаются прежними. Да и в целом при сетапе более 5-10 устройств, работать с именами на основе мак адресов сложно, хотелось бы работать с осмысленными именами устройств. Хороший пример реализация в z2m.

Add naming option via yaml config. Now default names are formed from the MAC address, and manual renaming does not have an effect on since the names of dependent entities (such as linkquality, power, and others) remain the same. And in general, with a setup of more than 5-10 devices, it is difficult to work with names based on MAC addresses, it would like to work with meaningful sensor names. Good example implementation in z2m.

**Comment by AlexxIT** [comment]
Supported in latest integration version
