### ISSUE TITLE
Add support for Xiaomi Mijia Smart Door Lock

### ISSUE THREAD

**Issue by obs945** [AlexxIT/XiaomiGateway3#162]
My door lock is Xiaomi Smart Door Lock.
After add XiaomiGateway3 component, the system cannot recognize the device and only showed BLE device.
![截圖 2021-01-03 下午7 19 59](https://user-images.githubusercontent.com/55457794/103507185-8ac41080-4e99-11eb-9855-e64d2b33f91d.jpg)

BLE ID: 794
Brand: Xiaomi 
Device: Smart Door Lock 
Model: MJZNMS02LM

Hope this could be helpful.

**Comment by AlexxIT** [comment]
It should already supported. Unknown model not a problem. Do you have action entity? Is it attributes changed with any activity with lock?

**Comment by obs945** [comment]
I edit bluetooth.py and added the model into list. After that, the model name shows up. I think it is OK now.  👍
