### ISSUE TITLE
can't find BLE devices

### ISSUE THREAD

**Issue by chongci** [AlexxIT/XiaomiGateway3#164]
I have a Xiaomi Night Light 2 (MJYD02YL-A) and it already add to mi app.
also i have flash the custom firmware(v1.4.7_0115) then add to HA.
I can see all of zigbee device in HA but can't find any BLE device, why?

hope anyone can help me to solve, tks!!

**Comment by hellkun** [comment]
The device seems to be supported.
Did you restart HA after adding the device to MiHome?

**Comment by chongci** [comment]
> The device seems to be supported.
> Did you restart HA after adding the device to MiHome?

thanks for your reply! yes, i restart many times.

**Comment by hellkun** [comment]
I think you could try to enable debug mode (readme), and restart HA then send logs. Might be helpful for the author to see what's going on.

**Comment by chongci** [comment]
> I think you could try to enable debug mode (readme), and restart HA then send logs. Might be helpful for the author to see what's going on.

It's amazing! when i enable debug mode(w/ basic logs)and  after i check the logs, all of BLE devices found. i don’t know what happened? but i appreciate your help very much.
