### ISSUE TITLE
Adding devices in ZHA mode didn’t work for me.

### ISSUE THREAD

**Issue by develflowing** [AlexxIT/XiaomiGateway3#167]
Hello everyone!

Thanks for the wonderful code first of all. 

In Mi Home mode all works fine. Divorces added and works, but in ZHA mode I can't add any devices such as Xiaomi smoke sensor and others.

Command didn't work for me.
entity_id: remote.0x........_pair
command: pair
device: lumi.sensor_smoke

Mi Hub didn't change status to paring. Blue lamp, no blinking yellow.

What I do wrong?

Thanks.

**Comment by AlexxIT** [comment]
Pair switch don't work in ZHA mode. You should use ZHA pair GUI

**Comment by develflowing** [comment]
Which device I need to add in ZHA?
![image](https://user-images.githubusercontent.com/74180270/104029712-60e15580-51db-11eb-85f0-3067699684c9.png)

**Comment by develflowing** [comment]
I found it. Thanks

https://youtu.be/AEkiUK7wGbs
