### ISSUE TITLE
Docs: Improve remove telnet password wiki

### ISSUE THREAD

**Issue by alekc** [AlexxIT/XiaomiGateway3#169]
I might be dumb but it took me a bit until I noticed the username in reset password cmd, otherwise I wasn't able to login because I did not know the username. 
I would suggest to change this sentence `Use password to enter Telnet and remove Telnet password:` to `Use the obtained password to enter Telnet (username: admin), and remove Telnet password:`

**Comment by AlexxIT** [comment]
Fixed
