### ISSUE TITLE
RTCGQ11LM offtop

### ISSUE THREAD

**Issue by viiy** [AlexxIT/XiaomiGateway3#17]
I had 4 RTCGQ11LM sensors with a 1 minute timeout. I tried to hack one of them to 5 seconds (https://community.smartthings.com/t/making-xiaomi-motion-sensor-a-super-motion-sensor/139806) and kill it)
I bought 3 more (https://aliexpress.ru/item/4000030637208.html?spm=a2g0s.9042311.0.0.511633edlLFcvt&_ga=2.202507089.116360065.1599633679-1196966882.1576925006&_gac=1.119603578.1599456638.CjwKCAjwkdL6BRAREiwA-kiczCEuuzlJI_172Q5SQ-Qj8dLZ3-IJKRhi9J2idYZy08wecHiNoFH6kxoCEuAQAvD_BwE) and tada! ! it works with 5 seconds timeout without hacking !!

**Comment by AlexxIT** [comment]
No. It only works with 5 seconds few hours after setup.

**Comment by viiy** [comment]
> No. It only works with 5 seconds few hours after setup.
connected 5 hours ago, but still 5 seconds. will see tomorrow.=)

**Comment by rezmus** [comment]
if you click on the sensor button to confirm link it works frequently for a few hours. hardware hack does the same.

**Comment by viiy** [comment]
you all was right :(
