### ISSUE TITLE
Xiaomi Aqara MFKZQ01LM Cube Controller - actions problem

### ISSUE THREAD

**Issue by shummo** [AlexxIT/XiaomiGateway3#172]
Hi!  I have an Aqara Cube with a hacked  Xiaomi Gateway 3 ( ZNDMWG03LM )

I have 3 entity for cube : 
sensor.0xxxxxxxxxxxxxxxx_action
battery
zigbee.

I would like to use the cube with actions (flip180, flip90, rotate, slide, tap, shake)

I think that the action would be for that, but i can only use it for a state> alert.  As a device I can only use for trigger with the battery.

Can it be used like this? How?

**Comment by ptbsare** [comment]
@shummo 
![Screenshot_2021-01-14-12-13-57-085_com android chrome](https://user-images.githubusercontent.com/3147576/104544323-69fe7680-5662-11eb-9110-8e66ff62bacc.jpg)
![Screenshot_2021-01-14-12-16-14-542_com android chrome](https://user-images.githubusercontent.com/3147576/104544328-6d91fd80-5662-11eb-94b9-0d0abb77e1ba.jpg)

**Comment by shummo** [comment]
Thanks for your  help!

So i have to write in "TO" the 
action. And what's are the actions command? Where can i fund them?

**Comment by ptbsare** [comment]
@shummo The corresponding 'action command' can be found when you perform some actions on your cude (such as flip it) and then the actions are shown in HA (as my first picture showed).

**Comment by shummo** [comment]
Thanks, and sorry for that.

**Comment by AlexxIT** [comment]
Better to check state, not attribute. Because attribute can't trigger two same actions in a row. State can.
