### ISSUE TITLE
WSDCGQ11LM не показывается (not shown)

### ISSUE THREAD

**Issue by olafnew** [AlexxIT/XiaomiGateway3#175]
Добрый день. WSDCGQ11LM добавлен в MiHome, и виден внутри MiHome, а вот в интеграции - где отлично показываются все устройства - вообще ни в какую не показывается, и нигде нет о нем упоминания(в логах в т.ч.). Прошивка хакнутая .4.7_0115_mod20201222. Пожалуйста - помогите!

Hi! WSDCGQ11LM is added into MiHome app, and is shown in there, but within the integration - new device does not appear. Weirdly - it not shown in the logs as well. Firmware is a hacked 1.4.7_0115_mod20201222.
Please help

**Comment by AlexxIT** [comment]
Точно к этому шлюзу добавлен? Виден именно в его списке дочерних устройств в MiHome?

**Comment by olafnew** [comment]
> Точно к этому шлюзу добавлен? Виден именно в его списке дочерних устройств в MiHome?

Гарантированно висит именно на этом  шлюзе. И в списке дочерних устройств(внутри mihome) в рамках этого шлюза показывается

**Comment by AlexxIT** [comment]
А если включить логи, при старте этого устройства в логах не видно?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
