### ISSUE TITLE
problem with BLE mesh device yeelight M2

### ISSUE THREAD

**Issue by anschein** [AlexxIT/XiaomiGateway3#179]
I got six M2 bulb and other five works fine,only one bulb become unavailble in HA
in MI APP everything is fine
and with this bulb has a mesh group also miss in HA
how do i deal with the problem?
Is there any information in DEBUG mode can help with?
![image](https://user-images.githubusercontent.com/49552476/104865088-fd42ef00-5975-11eb-8152-34e369502815.png)

**Comment by anschein** [comment]
gateway Version: 1.4.6_0030
HA Version: 2021.1.3

**Comment by AlexxIT** [comment]
Show next logs when you try to control that bulb

**Comment by anschein** [comment]
sorry,you mean in MI APP or HA?

**Comment by AlexxIT** [comment]
HA logs

**Comment by anschein** [comment]
but this device is unavailable in HA,I can only use it in MI APP,
with this wrong device and also missing mesh group,
change status in APP and watch logs in gateways debug mode helpful?
[M2.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5847573/M2.txt)
THERE IS THE LOGs when i use MI APP to control the mesh light and the DEBUG MODE outputs

**Comment by anschein** [comment]
![image](https://user-images.githubusercontent.com/49552476/105318679-c59aa800-5bfe-11eb-8c9d-7686fe72dc5a.png)
i have 6 m2 lights but in HA only shows 5  and 1 is unavailable,
and in this 6 lights i have 2 mesh groups  but HA only show 1

**Comment by AlexxIT** [comment]
Your gate can't get state from one bulb. I think it can be controlled from other BLE gateway or directly from your phone in MiHome. Try to remove it from MiHome and add again.

**Comment by anschein** [comment]
Did i need to close all other device with the BLE gateway function when i reconnect this bulb?
And there is a question is I have total six bulbs but in HA only shows five with one unavailble,So there a one is missing in HA.
What`s the possible solustion for this problem?

**Comment by anschein** [comment]
I tried remove and add again,and closed all other BLE gateway,still the same problem- -

**Comment by AlexxIT** [comment]
So I think the problem is same. It can be controlled from other BLE gateway or directly from your phone in MiHome

**Comment by anschein** [comment]
I reset the gateway and change the FW,all bulbs be right,thanks for help.
And I think the problem maybe signal is too weak.
