### ISSUE TITLE
Cannot Add Gateway to HomeKit

### ISSUE THREAD

**Issue by aotaot399** [AlexxIT/XiaomiGateway3#181]
I flash Firmware to with this way 
[https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/uart_recovery](url)
and use Mi home to Add  Gateway  To my network with Mihome on Iphone
when step to mihome add success. I use the menu pair with homekit and select home > Add accessory with QR code > select add bridge -> but still load and not success with timeout ?
i'm reset your gateway to factory default and try again mor time it still not work with home kit

Before falsh this custom firmware. I can add Gateway  to home kit normally
anyone found the problem?

**Comment by mikeinblue** [comment]
1st:make sure your mihome and homekit in the same network.
2nd:unpair the gateway both mihome and homekit.then reset the gateway add it into mihome,then homekit,wish you lucky!

**Comment by mikeinblue** [comment]
make sure when you pair with mihome and then pair homekit use this！！！
![22844E58-EE21-4F30-A106-4A2DF06EF374](https://user-images.githubusercontent.com/62834868/105197649-cd633980-5b77-11eb-8e66-c139e8e96e23.jpeg)

**Comment by aotaot399** [comment]
thank for  comment
> 1st:make sure your mihome and homekit in the same network.
> 2nd:unpair the gateway both mihome and homekit.then reset the gateway add it into mihome,then homekit,wish you lucky!

I'm Try  thi step
1.It same network of wifi > yes and change to other router for test 
2.I'm do it from this step 
and use menu on Mihome 
"Pair with home kit"

![image](https://user-images.githubusercontent.com/13797053/105331182-bd923680-5c05-11eb-84d5-a6fd57696dc5.png)

What Your version gateway3
I'm CTW 41.4.6_0012

**Comment by mikeinblue** [comment]
1.4.7_0115

**Comment by mikeinblue** [comment]
Do you unbound in homekit?

**Comment by aotaot399** [comment]
> Do you unbound in homekit?

Sure. unbound homekit (remove home).remove device on mihome.Reset getway setting new.

**Comment by aotaot399** [comment]
> Do you unbound in homekit?

sure. I'm remove home on home app.Remove gateway on Mihome app.Reset gateway for new pair

**Comment by aotaot399** [comment]
> 1.4.7_0115

Why you use 1.4.7_0115 ?. AlexxIT / XiaomiGateway3 recommenet to use Custom firmware
My problem is on. CWF 1.4.6_0012

**Comment by aotaot399** [comment]
@AlexxIT  My problem is on. CWF 1.4.6_0012 
when downgrade flash to custom firmware 1.4.6_0012.
![image](https://user-images.githubusercontent.com/13797053/105371817-918fa900-5c37-11eb-95b0-bdbd90d44b99.png)
After flash  1.4.6_0012 it Cannot to pair homekit.

====================================
lastest
i'm test upgrade firmware back to officeial firmware 1.4.7_0115
and set again complete to pair homekit
I think CWF 1.4.6_0012 has problem to use homekit?

![image](https://user-images.githubusercontent.com/13797053/105373226-09aa9e80-5c39-11eb-8dc7-722c887f802d.png)

**Comment by mikeinblue** [comment]
You can use this customized 1.4.7 fw by here :https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.7_0115_mod20201222

**Comment by luisarn** [comment]
> You can use this customized 1.4.7 fw by here :
> https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.7_0115_mod20201222
> 
> And if you use a fw with telnet enabled,you can update the new customized fw via telnet.
> link's here:
> https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware

1.4.7 has region check, cannot pair to mihome if you are not in china and selects china server

**Comment by luisarn** [comment]
I have the same problem, cannot pair with homekit and then I'm trying to debug via telnet and found this:

# homekitserver
    Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreCreate maxBytes 32
 Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueLoadFromFlash  success.
 Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Storage configuration: accessorySetup = 12
 Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Using display: false / Programmable NFC: false
 Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] MTD accessory load all info ok
 Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreamManager = 60
 Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: maxTCPStreams = 17
 Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreams = 408
 Default [com.apple.mfi.HomeKit.Platform:ServiceDiscovery] Storage configuration: serviceDiscovery = 552
 Default [com.apple.mfi.HomeKit.Platform:WiFiManager] Storage configuration: wiFiManager = 16
 Default [com.apple.mfi.HomeKit.Platform:SoftwareAccessPoint] Storage configuration: softwareAccessPoint = 20
 Default [com.apple.mfi.HomeKit.Platform:MFiHWAuth] Storage configuration: mfiHWAuth = 8
 Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueStoreCreate maxBytes 2
 Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueLoadFromFlash  success.
 Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: runLoop = 320
 Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: fileHandle = 28
 Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: timer = 24
 Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformMFiTokenAuthIsProvisioned [0]
 Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Version information:
libhap: /MIPS/GCC/mipsel-multilib-linux-gnu/
  - Version: 2.0.1 (16A75) - compatibility version 5
Using platform: WACIO
  - Version: 2.0.1 (16A75) - compatibility version 5
 Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Storage configuration: server = 1880
 Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Turning on Apple Authentication Coprocessor.
 Default [com.apple.mfi.HomeKit.Platform:Clock] Using 'clock_gettime' with 'CLOCK_MONOTONIC_RAW'.
 Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Apple Authentication Coprocessor information:
- Device Version: 3.0 (0x07)
- Firmware Version: 1
- Authentication Protocol Version: 3.0
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: ipAccessoryServerStorage = 40
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numSessions = 17
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions = 14416
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].inboundBuffer.numBytes = 32768
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].outboundBuffer.numBytes = 32768
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].numEventNotifications = 320
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].eventNotifications = 7680
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numReadContexts = 320
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: readContexts = 15360
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numWriteContexts = 320
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: writeContexts = 20480
 Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: scratchBuffer.numBytes = 32768
 Info    AppCreate
/data/conf/wpa_client.conf does not exist.
    Info    AppCreate: homekitserver version 1.1.4
 Info    AppCreate: miio_agent_socket_init succ
 Info    register_agent_method: {"method":"bind","address":8}
 Info    miio_agent_socket_callback: [36] {"id":123,"result":["OK"],"_from":2}
 Info    ParseJsonContent: Result: OK. id=123
 Info    RegisterAndGetDeviceList:[66]{"id":123, "_to":2, "method":"local.reg_pid","params":{"pid":[ ]}}
 Info    miio_agent_socket_callback: [32] {"id":124,"result":[],"_from":2}
 Info    RegisterAndGetDeviceList:[62]{"id":124, "_to":2, "method":"local.get_dev_list","params":{}}
 Info    RegisterAndGetDeviceList:[268]{"id":125, "_to":4, "method":"local.reg_pid","params":{"pid":[41,62,586,805,65556,66631,42,64,450,43,63,451,386,98,354,   136,687,720,217,250,93,66641,356,610,714,66639,96,66642,357,609,66640,355,611,65843,66501,  65557,66630,66828,385,163,670,161,162,452,67858,67859]}}
 Info    RegisterAndGetDeviceList:[62]{"id":126, "_to":4, "method":"local.get_dev_list","params":{}}
 Info    GetSecuritySystemProperties: {"id":320, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":21,"siid":3}]}
 Info    miio_agent_socket_callback: [90] {"id":320,"result":[{"code":0,"did":"317121624","piid":21,"siid":3,"value":0}],"_from":32}
 Info    ParseResponseMessage: queue_dst = 0
 Info    GetSecuritySystemProperties: {"id":321, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":1,"siid":3}]}
 Info    miio_agent_socket_callback: [89] {"id":321,"result":[{"code":0,"did":"317121624","piid":1,"siid":3,"value":0}],"_from":32}
 Info    ParseResponseMessage: queue_dst = 1
 Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Accessory server starting.
 Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Firmware version: 1.4.6
 Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreGet domain-key 90.10 found
 Error   [com.apple.mfi.HomeKit.Core:AccessoryServer] [1.4.7 > 1.4.6] Firmware must not be downgraded! Not starting HAPAccessoryServer.
 Info    [com.apple.mfi.HomeKit.Platform:RunLoop] Entering run loop.
      Fault   precondition failed: server->primaryAccessory - HAPAccessoryServerUpdateSetupPayload

Doe anybody know how to fix this issue?

**Comment by aotaot399** [comment]
> I have the same problem, cannot pair with homekit and then I'm trying to debug via telnet and found this:
> 
> # homekitserver
> ```
> Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreCreate maxBytes 32
> ```
> 
> Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueLoadFromFlash success.
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Storage configuration: accessorySetup = 12
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Using display: false / Programmable NFC: false
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] MTD accessory load all info ok
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreamManager = 60
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: maxTCPStreams = 17
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreams = 408
> Default [com.apple.mfi.HomeKit.Platform:ServiceDiscovery] Storage configuration: serviceDiscovery = 552
> Default [com.apple.mfi.HomeKit.Platform:WiFiManager] Storage configuration: wiFiManager = 16
> Default [com.apple.mfi.HomeKit.Platform:SoftwareAccessPoint] Storage configuration: softwareAccessPoint = 20
> Default [com.apple.mfi.HomeKit.Platform:MFiHWAuth] Storage configuration: mfiHWAuth = 8
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueStoreCreate maxBytes 2
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueLoadFromFlash success.
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: runLoop = 320
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: fileHandle = 28
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: timer = 24
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformMFiTokenAuthIsProvisioned [0]
> Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Version information:
> libhap: /MIPS/GCC/mipsel-multilib-linux-gnu/
> 
> * Version: 2.0.1 (16A75) - compatibility version 5
>   Using platform: WACIO
> * Version: 2.0.1 (16A75) - compatibility version 5
>   Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Storage configuration: server = 1880
>   Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Turning on Apple Authentication Coprocessor.
>   Default [com.apple.mfi.HomeKit.Platform:Clock] Using 'clock_gettime' with 'CLOCK_MONOTONIC_RAW'.
>   Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Apple Authentication Coprocessor information:
> * Device Version: 3.0 (0x07)
> * Firmware Version: 1
> * Authentication Protocol Version: 3.0
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: ipAccessoryServerStorage = 40
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numSessions = 17
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions = 14416
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].inboundBuffer.numBytes = 32768
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].outboundBuffer.numBytes = 32768
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].numEventNotifications = 320
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].eventNotifications = 7680
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numReadContexts = 320
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: readContexts = 15360
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numWriteContexts = 320
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: writeContexts = 20480
>   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: scratchBuffer.numBytes = 32768
>   Info    AppCreate
>   /data/conf/wpa_client.conf does not exist.
>   Info    AppCreate: homekitserver version 1.1.4
>   Info    AppCreate: miio_agent_socket_init succ
>   Info    register_agent_method: {"method":"bind","address":8}
>   Info    miio_agent_socket_callback: [36] {"id":123,"result":["OK"],"_from":2}
>   Info    ParseJsonContent: Result: OK. id=123
>   Info    RegisterAndGetDeviceList:[66]{"id":123, "_to":2, "method":"local.reg_pid","params":{"pid":[ ]}}
>   Info    miio_agent_socket_callback: [32] {"id":124,"result":[],"_from":2}
>   Info    RegisterAndGetDeviceList:[62]{"id":124, "_to":2, "method":"local.get_dev_list","params":{}}
>   Info    RegisterAndGetDeviceList:[268]{"id":125, "_to":4, "method":"local.reg_pid","params":{"pid":[41,62,586,805,65556,66631,42,64,450,43,63,451,386,98,354,   136,687,720,217,250,93,66641,356,610,714,66639,96,66642,357,609,66640,355,611,65843,66501,  65557,66630,66828,385,163,670,161,162,452,67858,67859]}}
>   Info    RegisterAndGetDeviceList:[62]{"id":126, "_to":4, "method":"local.get_dev_list","params":{}}
>   Info    GetSecuritySystemProperties: {"id":320, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":21,"siid":3}]}
>   Info    miio_agent_socket_callback: [90] {"id":320,"result":[{"code":0,"did":"317121624","piid":21,"siid":3,"value":0}],"_from":32}
>   Info    ParseResponseMessage: queue_dst = 0
>   Info    GetSecuritySystemProperties: {"id":321, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":1,"siid":3}]}
>   Info    miio_agent_socket_callback: [89] {"id":321,"result":[{"code":0,"did":"317121624","piid":1,"siid":3,"value":0}],"_from":32}
>   Info    ParseResponseMessage: queue_dst = 1
>   Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Accessory server starting.
>   Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Firmware version: 1.4.6
>   Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreGet domain-key 90.10 found
>   Error   [com.apple.mfi.HomeKit.Core:AccessoryServer] [1.4.7 > 1.4.6] Firmware must not be downgraded! Not starting HAPAccessoryServer.
>   Info    [com.apple.mfi.HomeKit.Platform:RunLoop] Entering run loop.
>   Fault   precondition failed: server->primaryAccessory - HAPAccessoryServerUpdateSetupPayload
> 
> Doe anybody know how to fix this issue?

currently i'm use original firmware and connect with other intergetion > homekit Controller :)

**Comment by rezmus** [comment]
> 1.4.7 has region check, cannot pair to mihome if you are not in china and selects china server

some ppl updated on china to last fw and move back to eu region.

**Comment by luisarn** [comment]
> > I have the same problem, cannot pair with homekit and then I'm trying to debug via telnet and found this:
> > # homekitserver
> > ```
> > Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreCreate maxBytes 32
> > ```
> > 
> > 
> > Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueLoadFromFlash success.
> > Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Storage configuration: accessorySetup = 12
> > Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Using display: false / Programmable NFC: false
> > Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] MTD accessory load all info ok
> > Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreamManager = 60
> > Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: maxTCPStreams = 17
> > Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreams = 408
> > Default [com.apple.mfi.HomeKit.Platform:ServiceDiscovery] Storage configuration: serviceDiscovery = 552
> > Default [com.apple.mfi.HomeKit.Platform:WiFiManager] Storage configuration: wiFiManager = 16
> > Default [com.apple.mfi.HomeKit.Platform:SoftwareAccessPoint] Storage configuration: softwareAccessPoint = 20
> > Default [com.apple.mfi.HomeKit.Platform:MFiHWAuth] Storage configuration: mfiHWAuth = 8
> > Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueStoreCreate maxBytes 2
> > Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueLoadFromFlash success.
> > Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: runLoop = 320
> > Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: fileHandle = 28
> > Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: timer = 24
> > Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformMFiTokenAuthIsProvisioned [0]
> > Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Version information:
> > libhap: /MIPS/GCC/mipsel-multilib-linux-gnu/
> > 
> > * Version: 2.0.1 (16A75) - compatibility version 5
> >   Using platform: WACIO
> > * Version: 2.0.1 (16A75) - compatibility version 5
> >   Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Storage configuration: server = 1880
> >   Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Turning on Apple Authentication Coprocessor.
> >   Default [com.apple.mfi.HomeKit.Platform:Clock] Using 'clock_gettime' with 'CLOCK_MONOTONIC_RAW'.
> >   Info    [com.apple.mfi.HomeKit.Core:MFiHWAuth] Apple Authentication Coprocessor information:
> > * Device Version: 3.0 (0x07)
> > * Firmware Version: 1
> > * Authentication Protocol Version: 3.0
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: ipAccessoryServerStorage = 40
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numSessions = 17
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions = 14416
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].inboundBuffer.numBytes = 32768
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].outboundBuffer.numBytes = 32768
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].numEventNotifications = 320
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].eventNotifications = 7680
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numReadContexts = 320
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: readContexts = 15360
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numWriteContexts = 320
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: writeContexts = 20480
> >   Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: scratchBuffer.numBytes = 32768
> >   Info    AppCreate
> >   /data/conf/wpa_client.conf does not exist.
> >   Info    AppCreate: homekitserver version 1.1.4
> >   Info    AppCreate: miio_agent_socket_init succ
> >   Info    register_agent_method: {"method":"bind","address":8}
> >   Info    miio_agent_socket_callback: [36] {"id":123,"result":["OK"],"_from":2}
> >   Info    ParseJsonContent: Result: OK. id=123
> >   Info    RegisterAndGetDeviceList:[66]{"id":123, "_to":2, "method":"local.reg_pid","params":{"pid":[ ]}}
> >   Info    miio_agent_socket_callback: [32] {"id":124,"result":[],"_from":2}
> >   Info    RegisterAndGetDeviceList:[62]{"id":124, "_to":2, "method":"local.get_dev_list","params":{}}
> >   Info    RegisterAndGetDeviceList:[268]{"id":125, "_to":4, "method":"local.reg_pid","params":{"pid":[41,62,586,805,65556,66631,42,64,450,43,63,451,386,98,354,   136,687,720,217,250,93,66641,356,610,714,66639,96,66642,357,609,66640,355,611,65843,66501,  65557,66630,66828,385,163,670,161,162,452,67858,67859]}}
> >   Info    RegisterAndGetDeviceList:[62]{"id":126, "_to":4, "method":"local.get_dev_list","params":{}}
> >   Info    GetSecuritySystemProperties: {"id":320, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":21,"siid":3}]}
> >   Info    miio_agent_socket_callback: [90] {"id":320,"result":[{"code":0,"did":"317121624","piid":21,"siid":3,"value":0}],"_from":32}
> >   Info    ParseResponseMessage: queue_dst = 0
> >   Info    GetSecuritySystemProperties: {"id":321, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":1,"siid":3}]}
> >   Info    miio_agent_socket_callback: [89] {"id":321,"result":[{"code":0,"did":"317121624","piid":1,"siid":3,"value":0}],"_from":32}
> >   Info    ParseResponseMessage: queue_dst = 1
> >   Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Accessory server starting.
> >   Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Firmware version: 1.4.6
> >   Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreGet domain-key 90.10 found
> >   Error   [com.apple.mfi.HomeKit.Core:AccessoryServer] [1.4.7 > 1.4.6] Firmware must not be downgraded! Not starting HAPAccessoryServer.
> >   Info    [com.apple.mfi.HomeKit.Platform:RunLoop] Entering run loop.
> >   Fault   precondition failed: server->primaryAccessory - HAPAccessoryServerUpdateSetupPayload
> > 
> > Doe anybody know how to fix this issue?
> 
> currently i'm use original firmware and connect with other intergetion > homekit Controller :)

This might help: https://github.com/AlexxIT/XiaomiGateway3/issues/193
