### ISSUE TITLE
Aqara precision motion sensor state not update

### ISSUE THREAD

**Issue by bluefoxlee** [AlexxIT/XiaomiGateway3#182]
Got my Aqara precision motion sensor RTCGQ13LM and added few days ago. 
However I found the sensor and battery state remain unavailable since then.

After review the code, I found remove line 252 from utils.py fix the issue for me. 
`    'lumi.motion.agl04': ["Aqara", "Precision Motion Sensor", "RTCGQ13LM"],`

not quite sure if this is the right way to fix, since I am not a programer. Just like to report and share if anyone face the same issue. Thanks.

**Comment by AlexxIT** [comment]
Did you delete this line and the sensor started working?

**Comment by bluefoxlee** [comment]
I mark it with # to disable it.
And yes. It works now.

**Comment by AlexxIT** [comment]
It shouldn't work without this line. Double check all again

**Comment by bluefoxlee** [comment]
Pretty sure that’s how I make it works ATM. but I will make more test and report back.

I found there are two lines (252 and 362) list about RTCGQ13LM.
And notice mention about old devices uses params, new devices uses mi_spec. I guess RTCGQ13LM is new device?

**Comment by AlexxIT** [comment]
You right. Two lines is my mistake

**Comment by bluefoxlee** [comment]
Thanks Alex.
 
BTW really appreciate for the add-on. So I am finally able to add RTCGQ13LM (and Aqara thermostat S1 - have not try it yet) to HA. Thanks.

**Comment by AlexxIT** [comment]
I thought I support only S2 thermostat. Is S1 has same model?

**Comment by bluefoxlee** [comment]
> I thought I support only S2 thermostat. Is S1 has same model?

it has exactly the same front panel but slightly different back panel. model No. is KTWKQ01ES.
S2 is KTWKQ03ES. 

My S1 is installed at another place, which haven't got chance to make a test.
Will try to modify py file when I go back and report with another thread.
