### ISSUE TITLE
955:"ydhome.lock.m2silver"

### ISSUE THREAD

**Issue by mikeinblue** [AlexxIT/XiaomiGateway3#183]
Hi,Alex,thank you for your great job.
Is there any possible to integrate the ble locker ?My hass can display some parts of that.
![7DA933C2-0639-43F2-9153-38725953E434](https://user-images.githubusercontent.com/62834868/105189771-4494cf80-5b70-11eb-95ed-53ea97e6bec7.png)
![731C0759-4954-4E04-B236-D6C2BA52497F](https://user-images.githubusercontent.com/62834868/105189789-48c0ed00-5b70-11eb-8788-9783eaccae60.png)
Thank you again

**Comment by AlexxIT** [comment]
Will it is already works. Just need to add it model

**Comment by mikeinblue** [comment]
It just read the state.It doesn't work,also it has no model right now.:)So I think maybe it's possible make it work with hass.

**Comment by AlexxIT** [comment]
What state? Action? You need do something with lock for updating state

**Comment by mikeinblue** [comment]
It just displays locked or unlock.I can't  lock or unlock the locker.

**Comment by mikeinblue** [comment]
![A8D130F2-61F0-43A5-9E87-41293F12291B](https://user-images.githubusercontent.com/62834868/105246360-17ffa880-5bae-11eb-8e91-48cc0cc25c3c.png)
![C8763F89-F1EA-4306-96F6-F5D16DD35C7A](https://user-images.githubusercontent.com/62834868/105246367-1b932f80-5bae-11eb-90ec-a2b7ffb12837.png)

**Comment by bluefoxlee** [comment]
> It just displays locked or unlock.I can't lock or unlock the locker.

I believe you can edit bluetooth.py to add the model number. and so far as I know you won't able to lock or unlock it through this add-on but only read the state from lock.action entity. and it shows unavailable until someone open/close the door.
BTW, I am using Xiaomi XMZNMST02YD.

应该是没办法透过 Add-on 解锁或上锁，lock.action 刚开始会显示不可用，直到你有开锁或上锁的动作，就会显示 ID 等其他资料。不过好像目前不是所有锁都能读取所有资料，这个要请教作者了。

**Comment by AlexxIT** [comment]
Can you open this lock via mihome when you not at home?

**Comment by mikeinblue** [comment]
> Can you open this lock via mihome when you not at home?

No,it only can unlock with bluetooth .That means I only can unlock the locker near my door.

**Comment by AlexxIT** [comment]
Well gateway can only get state from lock. And can't control it.

**Comment by mikeinblue** [comment]
ok.thanks . I will close this issue.

**Comment by AlexxIT** [comment]
I'll close it later when add it model to component

**Comment by mikeinblue** [comment]
thanx

**Comment by AlexxIT** [comment]
The model will appear in version 2 of the component
