### ISSUE TITLE
Mesh light in HomeKit can't control brightness and color temp

### ISSUE THREAD

**Issue by chongci** [AlexxIT/XiaomiGateway3#184]
i have some third-party xiaomi ble mesh downlight, they can through xiaomi gateway3 add to mihome app and work fine(they can control brightness and color temperature by mihome app or xiaomi AI speaker).

now, i add xiaomi gateway3 to HA and through HA to work on homekit, but i only can turn on/off downlight in apple home app, can’t control brightness and color temperature.

how do i let them work more perfect on homekit? anyone can give me suggestion?

thanks!

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
