### ISSUE TITLE
Support same BLE device on multiple gateways

### ISSUE THREAD

**Issue by ptbsare** [AlexxIT/XiaomiGateway3#189]
hi, @AlexxIT 
I have four xiaomi gateway3 gateways, because you can hardly use one gateway to cover the area of the whole apartment. 
If I turn on ble mode on multiple gateways in HA, it turns out that some ble sensors cease to update, which is stated in this issue #110 . Same here. The problem is that the first gateway3 (may not be the closest one) registers the device and other gateways are not able to update the device states and the related entities even if they received the bluetooth packet sent by ble sensors (or ble locks).HA logs say: "warning: the xiaomi gateway 3 platform is not generating unique ids, the id is already used by sensor.xxxxxxxxxxxx_temperature, ignoring...xxx device.
If I enable ble devices on only one gateway, as I said above ,that may result in some ble sensors or locks not tracked because one gateway can hardly cover all the ble devices which are far away from this gateway.
Similar issues on ble mesh devices:
#187  #179  #109
So I think that supporting same device on multiple gateways may perfectly resolve all the above issues related to ble devices and ble mesh devices.
In fact the original purpose of ble mesh devices is that you can use multiple gateways to extend the coverage of ble radio so as to cover the whole area, but not using only one gateway to control all ble devices. That is what ble gateways are for.

**Comment by ptbsare** [comment]
#127 #99 may also be related to this issue.

**Comment by ptbsare** [comment]
I know that this may not be easy but xiaomi cease to release or develop new zigbee products and they pivot to ble mesh devices.(source: https://iot.mi.com/new/doc/embedded-development/overview) more and more ble mesh switchs/sensors/devices are released and more and more ble(mesh) devices-not-track/appear/update issues may appear under this repo.

**Comment by hellkun** [comment]
To conclude, I suppose BLE mesh devices should be considered as per-account based, instead of per-gateway based

**Comment by AlexxIT** [comment]
Component needs total code rewrite for this feature. It is in plans.

**Comment by fengguanghou** [comment]
Ah, the original is not only one person I encountered such a problem! I also have multiple gateways, and the status of my BLE device is always unstable, as is the Bluetooth lock, sometimes the lock information is obtained, sometimes not!
Hope to improve as soon as possible.

**Comment by mengyu-520** [comment]
Ah, the original is not only one person I encountered such a problem! I also have multiple gateways, and the status of my BLE device is always unstable, as is the Bluetooth lock, sometimes the lock information is obtained, sometimes not!
Hope to improve as soon as possible.
meto

**Comment by AlexxIT** [comment]
Implemented in the latest version
