### ISSUE TITLE
Yeelight Mesh downlight&spotlight issue

### ISSUE THREAD

**Issue by SosoKapianidze** [AlexxIT/XiaomiGateway3#190]
Hi, Alex! 
thanks for awesome integration with gateway3, I have issue with Mesh downlight&spotlights, while they-re binded to MI home they work properly with your integration, but if I remove it from Mi home they are disabled in HA, is it possible to add and use Mesh devices without Mi home, and if so, how to add them because they don't appear in HA event if I put them into pairing mode?
![image](https://user-images.githubusercontent.com/47385334/105634369-1caab200-5e77-11eb-8723-2639f854ca4f.png)

**Comment by ptbsare** [comment]
I am not expert here but ble/ble mesh devices are binded to mi home account, not a certain gateway.

**Comment by Zuz666** [comment]
> but if I remove it from Mi home they are disabled in HA

You are, in general, you know, why do you need it? :)

After Removing the device from the Mi home account, it is also deleted from the gateway database.  The XiaomiGateway3 HA component requires this database to work.

**Comment by SosoKapianidze** [comment]
@Zuz666 it's totally understandable that integration uses data written by Mi home, but it would be nice if integration could write devices itself into hub or into HA (if it's possible to communicate that way like zigbee)

**Comment by AlexxIT** [comment]
No. It cannot be fixed. Mesh devices totally controls with Xiaomi soft. Open source don't have working code for this devices for now.
