### ISSUE TITLE
Can't start homekitserver after downgrading from 1.4.7_0115 to 1.4.6_0012

### ISSUE THREAD

**Issue by luisarn** [AlexxIT/XiaomiGateway3#193]
Hi there,

Homekitserver cannot start after downgrading making the gateway unable to pair with homekit:

> Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueLoadFromFlash success.
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Storage configuration: accessorySetup = 12
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] Using display: false / Programmable NFC: false
> Default [com.apple.mfi.HomeKit.Platform:AccessorySetup] MTD accessory load all info ok
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreamManager = 60
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: maxTCPStreams = 17
> Default [com.apple.mfi.HomeKit.Platform:TCPStreamManager] Storage configuration: tcpStreams = 408
> Default [com.apple.mfi.HomeKit.Platform:ServiceDiscovery] Storage configuration: serviceDiscovery = 552
> Default [com.apple.mfi.HomeKit.Platform:WiFiManager] Storage configuration: wiFiManager = 16
> Default [com.apple.mfi.HomeKit.Platform:SoftwareAccessPoint] Storage configuration: softwareAccessPoint = 20
> Default [com.apple.mfi.HomeKit.Platform:MFiHWAuth] Storage configuration: mfiHWAuth = 8
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueStoreCreate maxBytes 2
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformProvisionValueLoadFromFlash success.
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: runLoop = 320
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: fileHandle = 28
> Default [com.apple.mfi.HomeKit.Platform:RunLoop] Storage configuration: timer = 24
> Default [com.apple.mfi.HomeKit.Platform:MFiTokenAuth] HAPPlatformMFiTokenAuthIsProvisioned [0]
> Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Version information:
> libhap: /MIPS/GCC/mipsel-multilib-linux-gnu/
> 
> Version: 2.0.1 (16A75) - compatibility version 5
> Using platform: WACIO
> Version: 2.0.1 (16A75) - compatibility version 5
> Default [com.apple.mfi.HomeKit.Core:AccessoryServer] Storage configuration: server = 1880
> Info [com.apple.mfi.HomeKit.Core:MFiHWAuth] Turning on Apple Authentication Coprocessor.
> Default [com.apple.mfi.HomeKit.Platform:Clock] Using 'clock_gettime' with 'CLOCK_MONOTONIC_RAW'.
> Info [com.apple.mfi.HomeKit.Core:MFiHWAuth] Apple Authentication Coprocessor information:
> Device Version: 3.0 (0x07)
> Firmware Version: 1
> Authentication Protocol Version: 3.0
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: ipAccessoryServerStorage = 40
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numSessions = 17
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions = 14416
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].inboundBuffer.numBytes = 32768
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].outboundBuffer.numBytes = 32768
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].numEventNotifications = 320
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: sessions[0...16].eventNotifications = 7680
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numReadContexts = 320
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: readContexts = 15360
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: numWriteContexts = 320
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: writeContexts = 20480
> Default [com.apple.mfi.HomeKit.Core:IPAccessoryServer] Storage configuration: scratchBuffer.numBytes = 32768
> Info AppCreate
> /data/conf/wpa_client.conf does not exist.
> Info AppCreate: homekitserver version 1.1.4
> Info AppCreate: miio_agent_socket_init succ
> Info register_agent_method: {"method":"bind","address":8}
> Info miio_agent_socket_callback: [36] {"id":123,"result":["OK"],"_from":2}
> Info ParseJsonContent: Result: OK. id=123
> Info RegisterAndGetDeviceList:[66]{"id":123, "_to":2, "method":"local.reg_pid","params":{"pid":[ ]}}
> Info miio_agent_socket_callback: [32] {"id":124,"result":[],"_from":2}
> Info RegisterAndGetDeviceList:[62]{"id":124, "_to":2, "method":"local.get_dev_list","params":{}}
> Info RegisterAndGetDeviceList:[268]{"id":125, "_to":4, "method":"local.reg_pid","params":{"pid":[41,62,586,805,65556,66631,42,64,450,43,63,451,386,98,354, 136,687,720,217,250,93,66641,356,610,714,66639,96,66642,357,609,66640,355,611,65843,66501, 65557,66630,66828,385,163,670,161,162,452,67858,67859]}}
> Info RegisterAndGetDeviceList:[62]{"id":126, "_to":4, "method":"local.get_dev_list","params":{}}
> Info GetSecuritySystemProperties: {"id":320, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":21,"siid":3}]}
> Info miio_agent_socket_callback: [90] {"id":320,"result":[{"code":0,"did":"317121624","piid":21,"siid":3,"value":0}],"_from":32}
> Info ParseResponseMessage: queue_dst = 0
> Info GetSecuritySystemProperties: {"id":321, "_to":32, "method":"get_properties","params":[{"did":"317121624","piid":1,"siid":3}]}
> Info miio_agent_socket_callback: [89] {"id":321,"result":[{"code":0,"did":"317121624","piid":1,"siid":3,"value":0}],"_from":32}
> Info ParseResponseMessage: queue_dst = 1
> Info [com.apple.mfi.HomeKit.Core:AccessoryServer] Accessory server starting.
> Info [com.apple.mfi.HomeKit.Core:AccessoryServer] Firmware version: 1.4.6

> 
> Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreGet domain-key 90.10 found
> **Error [com.apple.mfi.HomeKit.Core:AccessoryServer] [1.4.7 > 1.4.6] Firmware must not be downgraded! Not starting HAPAccessoryServer.**
> Info [com.apple.mfi.HomeKit.Platform:RunLoop] Entering run loop.
> Fault precondition failed: server->primaryAccessory - HAPAccessoryServerUpdateSetupPayload

Doe anybody have a clue on how to clear the HAPPlatformKeyValueStoreGet domain-key 90.10?

**Comment by zvldz** [comment]
Try downgrading bluetooth firmware version.

**Comment by luisarn** [comment]
> Try downgrading bluetooth firmware version.

Could you explain on how to downgrade the bluetooth firmware? Thanks!!!

**Comment by zvldz** [comment]
Download file https://github.com/serrj-sv/lumi.gateway.mgl03/raw/main/firmware/custom/mgl03_1.4.6_0012_mod20201223/mgl03_1.4.6_0012_mod20201223.zip
Unpack it and copy file full_ble_1.4.6_0012.gbl with name full.gbl to gw /data/
Reboot gw.
Check file /data/full.gbl it must be not exist.

Turn on ftp
https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad#turning-on-ftp

**Comment by luisarn** [comment]
Thanks @zvldz !

I'm able to downgrade the BLE based on your guide:

# cat ble_info
ncp_host_version=134
ncp_target_version=100
bootloader_version=101
ota=0

However it didn't solve the homekitserver issue:

>  Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Accessory server starting.
>  Info    [com.apple.mfi.HomeKit.Core:AccessoryServer] Firmware version: 1.4.6
>  Default [com.apple.mfi.HomeKit.Platform:KeyValueStore] HAPPlatformKeyValueStoreGet domain-key 90.10 found
>  **Error   [com.apple.mfi.HomeKit.Core:AccessoryServer] [1.4.7 > 1.4.6] Firmware must not be downgraded! Not starting HAPAccessoryServer.**
>  Info    [com.apple.mfi.HomeKit.Platform:RunLoop] Entering run loop.
>       Fault   precondition failed: server->primaryAccessory - HAPAccessoryServerUpdateSetupPayload

**Comment by zvldz** [comment]
So it's not bluetooth firmware.
Sorry, I don't know what else to recommend.

**Comment by rezmus** [comment]
did you factory reset after downgrade with 10 times button click?

**Comment by luisarn** [comment]
> did you factory reset after downgrade with 10 times button click?

Yes, not sure where the AccessoryServer is getting the 1.4.7 version number.

**Comment by rezmus** [comment]
you can patch homekitserver binary or just repack rootfs with 1.4.7 fw version in /etc/rootfs_fw_info

**Comment by zvldz** [comment]
> you can patch homekitserver binary or just repack rootfs with 1.4.7 fw version in /etc/rootfs_fw_info

Why does this error occur?

**Comment by rezmus** [comment]
some downgrade protection in homekitserver. not sure where it's kept, just patch it and forget.

**Comment by zvldz** [comment]
> However it didn't solve the homekitserver issue

Can you check patched binary or create firmware with patched homekitserver?

**Comment by luisarn** [comment]
> you can patch homekitserver binary or just repack rootfs with 1.4.7 fw version in /etc/rootfs_fw_info

Could you teach me how to do it via telnet?

**Comment by zvldz** [comment]
> Could you teach me how to do it via telnet?

Use instruction manual
https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad#the-hard-way-way-of-the-warrior

and firmware https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad/raw/e5b30fd2999b27c8a96a322cf1ba87953605f6bb/mgl03_1.4.6_0012_mod20210127.zip

**Comment by luisarn** [comment]
> Can you check patched binary or create firmware with patched homekitserver for test ?

@zvldz the firmware [https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad/raw/e5b30fd2999b27c8a96a322cf1ba87953605f6bb/mgl03_1.4.6_0012_mod20210127.zip]https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad/raw/e5b30fd2999b27c8a96a322cf1ba87953605f6bb/mgl03_1.4.6_0012_mod20210127.zip works! Thanks for your help!!!

**Comment by zvldz** [comment]
> works!

Thank you for testing ))

**Comment by aotaot399** [comment]
> > Can you check patched binary or create firmware with patched homekitserver for test ?
> 
> @zvldz the firmware https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad/raw/e5b30fd2999b27c8a96a322cf1ba87953605f6bb/mgl03_1.4.6_0012_mod20210127.zip works! Thanks for your help!!!

This Firmware 
can use with AlexxIT
XiaomiGateway3 Integration?

**Comment by zvldz** [comment]
> can use with AlexxIT
> XiaomiGateway3 Integration?

Yes, of course.

**Comment by aotaot399** [comment]
> > can use with AlexxIT
> > XiaomiGateway3 Integration?
> 
> Yes, of course.

I'm Flash 
1.4.6_0012 #20210127
But this version cannot add to AlexxIT XiaomiGateway3
something went wrong

![image](https://user-images.githubusercontent.com/13797053/106691520-392cb400-6606-11eb-9b87-9205d6c63143.png)

![image](https://user-images.githubusercontent.com/13797053/106691175-a1c76100-6605-11eb-838b-8e0228d90a9b.png)
![image](https://user-images.githubusercontent.com/13797053/106691694-89a41180-6606-11eb-9f43-4c8734336f3b.png)

![image](https://user-images.githubusercontent.com/13797053/106691002-557c2100-6605-11eb-9bef-949f65d56179.png)

**Comment by aotaot399** [comment]
Ok Success.I'm Found my problem.Token has invalid.Because Token is change when reset device
Thank @zvldz 

![image](https://user-images.githubusercontent.com/13797053/106702372-d98cd380-661a-11eb-9369-5a4d379a14d5.png)

**Comment by AlexxIT** [comment]
@aotaot399 yes, HA update cloud tokens only when starts
