### ISSUE TITLE
не понятно по датчику MCCGQ02HL

### ISSUE THREAD

**Issue by akomylator** [AlexxIT/XiaomiGateway3#194]
Подскажите пожалуйста не понятно что передает датчик в uart,понятно что передает 8 байт первый это 0 или 1 а остальные семь?к примеру 00 04 00 00 D8 6C 05 42

**Comment by AlexxIT** [comment]
Не очень понимаю, что такое uart. И это не биты, а байты.

**Comment by akomylator** [comment]
В консолей, мне бы расшифровать

**Comment by AlexxIT** [comment]
Работа с BLE данными описана в файле bluetooth.py. Этих данных мало, что что-то понять
