### ISSUE TITLE
BLE Mesh ID 2007 cause noname switch

### ISSUE THREAD

**Issue by uavana** [AlexxIT/XiaomiGateway3#195]
and it will pass NoneType attr to the init method
Jan 29 16:15:53 ha hass[14591]:     self.setups[domain](self, device, param[2])
Jan 29 16:15:53 ha hass[14591]:   File "/root/.homeassistant/custom_components/xiaomi_gateway3/switch.py", line 17, in setup
Jan 29 16:15:53 ha hass[14591]:     async_add_entities([Gateway3MeshSwitch(gateway, device, attr)])
Jan 29 16:15:53 ha hass[14591]:   File "/root/.homeassistant/custom_components/xiaomi_gateway3/__init__.py", line 272, in __init__
Jan 29 16:15:53 ha hass[14591]:     self._attr.replace('_', ' ').title())

**Comment by rezmus** [comment]
lemesh.switch.sw0a01
