### ISSUE TITLE
Loss of Bluetooth device information

### ISSUE THREAD

**Issue by mengyu-520** [AlexxIT/XiaomiGateway3#196]
About the information feedback problem of Bluetooth devices, Bluetooth door lock, Bluetooth motion sensor 2, door and window sensor 2, night light 2, home assistant information loss problem, can you solve it, boss?

Sorry, English is not good

**Comment by mengyu-520** [comment]
@AlexxIT

**Comment by AlexxIT** [comment]
Do you have any other BLE gateways in MiHome?

**Comment by mengyu-520** [comment]
@AlexxIT Four gateways 3, Three other BLE gateways,Do you want to turn off other BLE gateways?

**Comment by xrh0905** [comment]
> @AlexxIT Four gateways 3, Three other BLE gateways,Do you want to turn off other BLE gateways?

@mengyu-520 Try to turn off other BLE gateways and add all four gateways 3.
BLE Data collectd directly from gateway, and gateway that don't connect to devices will not be able to read data.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
