### ISSUE TITLE
Alarm Control Panel from v0.12 does not work.

### ISSUE THREAD

**Issue by jgalerap** [AlexxIT/XiaomiGateway3#199]
Alarm Panel latest addition does not properly work, I'm unable to change alarm to any state. These are the traces appearing in the logs.

```
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 12:42:00 AM (11 occurrences)
Last logged: 1:01:30 AM

Can't send get_properties [{'did': '374738511', 'siid': 3, 'piid': 1}]
Can't send set_properties [{'did': '374738511', 'siid': 3, 'piid': 1, 'value': 1}]
```

My device is **lumi.gateway.mgl03 ZNDMWG03LM** using custom firmware [**v1.4.6_0012**](https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20210127)

**Comment by bobo522487** [comment]
me too

**Comment by AlexxIT** [comment]
Maybe MiHome token has changed?

**Comment by bobo522487** [comment]
> Maybe MiHome token has changed?

you are right，problem has been solved. thank a lot！

**Comment by jgalerap** [comment]
Yep, it changed. I was not aware it changes automatically...

Thanks for the reply AlexxIT!

**Comment by AlexxIT** [comment]
Token should changes only when reset gateway WiFi or MiHome account.
