### ISSUE TITLE
Xiaomi Gateway v3 Installed but doesn't turn on in Integration

### ISSUE THREAD

**Issue by loglux** [AlexxIT/XiaomiGateway3#201]
I've installed Xiaomi Gateway v3 through HACS.
![image](https://user-images.githubusercontent.com/37578325/106892690-533cc400-66e4-11eb-87e1-ff8b1b64f608.png)
```
simulacra@Gemini-X55:~/hassio-config/homeassistant$ ls custom_components
alexa_media  hacs  localtuya  sonoff  tapo_control  xiaomi_gateway3
simulacra@Gemini-X55:~/hassio-config/homeassistant$
```
But it doesn't turn up in Integrations
![image](https://user-images.githubusercontent.com/37578325/106892754-6e0f3880-66e4-11eb-9aea-cff95237d82c.png)

**Comment by ptbsare** [comment]
Try  clear browser cache and refresh the page.

**Comment by loglux** [comment]
Thanks. Helped
