### ISSUE TITLE
Unsupported Smart Plug

### ISSUE THREAD

**Issue by loglux** [AlexxIT/XiaomiGateway3#202]
I can see in HA notification only but it's not pairing.
```
Xiaomi Gateway 3
New device:
did: lumi.137a0000026a07
mac: 137a0000026a07
model: Z809AE3R
version: 34
zb_ver: 3.0

```
https://zigbee.blakadder.com/Netvox_Z809A.html

**Comment by AlexxIT** [comment]
Because in mihome mode gateway pair only supported models
