### ISSUE TITLE
Whether the information record of Bluetooth lock can be saved all the time？

### ISSUE THREAD

**Issue by a120578270** [AlexxIT/XiaomiGateway3#204]
When you restart HA or close the door to open the door, the information content such as fingerprint unlocking is different and will not be kept in the interface all the time! Can always keep records to display, easier to view records!
![image](https://user-images.githubusercontent.com/58241282/106982098-4d0b1e00-679e-11eb-895e-92391f9023c9.png)
It just keeps showing like this
![image](https://user-images.githubusercontent.com/58241282/106982186-8774bb00-679e-11eb-9317-80e57475549e.png)

**Comment by mengyu-520** [comment]
蓝牙信息要丢失，坐等大神更新吧。

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
