### ISSUE TITLE
missing "no motion since" attribute

### ISSUE THREAD

**Issue by latel** [AlexxIT/XiaomiGateway3#205]
I have a Aqara motion sentor(lumi.sensor_motion.v2) 

when I connect it under。lumi.gateway.v3(which connect to homeassistant with [Xiaomi Gateway (Aqara)](https://www.home-assistant.io/integrations/xiaomi_aqara) integration), I can see following attributes in nore-red.

![image](https://user-images.githubusercontent.com/5621862/107120666-a328b000-68c9-11eb-8d60-524211b11423.png)

but when I connect it under xiaomi gateway3(lumi.gateway.mgl03, which connect to homeassistant through this component), I don't see the attibute "no motion since"

![image](https://user-images.githubusercontent.com/5621862/107120470-ca32b200-68c8-11eb-9f4f-5599aa1331ce.png)

anything I can do to help? this attribute is essential, because I want to use it to turn the light automatically when no motion is detected for a period.

lumi.gateway.v3: 
![image](https://user-images.githubusercontent.com/5621862/107120956-b5571e00-68ca-11eb-948f-c87e50ff26fb.png)
lumi.gateway.mgl03:
![image](https://user-images.githubusercontent.com/5621862/107120978-dc155480-68ca-11eb-822c-2d5b9798a0c9.png)

**Comment by AlexxIT** [comment]
You can setup necessary timeout and check on and off sensor state. Or add timeout node in Node-RED.

**Comment by latel** [comment]
> You can setup necessary timeout and check on and off sensor state. Or add timeout node in Node-RED.

yeah, you are right, however I think using the attributes coming from sensor itself is more reliable and accurate. 
Do you know why the attributes is missing here?

**Comment by AlexxIT** [comment]
Because sensor don't send this attribute. It generates internally in MiHome software.

**Comment by latel** [comment]
it's confused why I can get this attributes through Xiaomi Gateway (Aqara) integration on hass?

**Comment by AlexxIT** [comment]
Because Xiaomi Gateway (Aqara) uses official Xiaomi API. And this gate don't has official API.

Anyway I think users can set up automations of any compexity without these parameters.

**Comment by latel** [comment]
by "And this gate don't has official API", you mean this mod don't support official API or the original firmware don't support official API? This is weired, xiaomi gateway don't support official Xiaomi API it self?

**Comment by AlexxIT** [comment]
Nothing weird, lumi.gateway.v3 was almost one model, that support Xiaomi LAN API.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
