### ISSUE TITLE
MJDPO9YL. В offline нет состояния unavailable.

### ISSUE THREAD

**Issue by remarkua** [AlexxIT/XiaomiGateway3#206]
Сегодня подключил несколько MJDPO9YL.
Работают нормально, но!
Вопрос: В HA запоминается последний статус лампы перед отключением от нее питания. Лампа давно обесточена, а HA показывает что она включена, и это состояние не изменить...
Получается что состояние может быть или ON или OFF.
Нет состояния Unavailable.
Для сенсоров TH запоминание состояния предшествующего offline может и нормально, но для ламп это ИМХО нехорошо.
Возможно ли получать состояние unavailable от незапитанных ламп?

**Comment by AlexxIT** [comment]
Возможно, не сделано пока

**Comment by dentra** [comment]
Очень ждём

**Comment by dentra** [comment]
Этот коммит https://github.com/AlexxIT/XiaomiGateway3/commit/09d91d0240f4e2c548beabf84d9434362180d4fc не помог, все так же состояние остаётся какое было до физического отключения. Может логи какие нужны?

**Comment by AlexxIT** [comment]
Оно проявляется не сразу

**Comment by dentra** [comment]
Проверил, в течении часа, к сожалению, ничего не проявилось :(

**Comment by remarkua** [comment]
> Оно проявляется не сразу

Двое суток. К сожалению ничего не изменилось. 
Прошивка шлюза mgl03_1.4.6_0012_mod20210309.

**Comment by dentra** [comment]
В квартире утром несколько раз «моргал» свет, свитч провайдера походу не выдержал этого издевательства и ушёл в себя, собственно пропал интернет и в итоге появилось это состояние. Но это получается другое состояние больше offline, чем unavailable

**Comment by dentra** [comment]
Возможно был неправ и отвалился целиком шлюз, вечером проверю

**Comment by remarkua** [comment]
Отключаю MJDPO9YL. В HA ничего не изменяется. Долго жду, пока в Mi Home не станет состояние offline. Жду еще. Состояние в HA по прежнему "включено", после ручного выключения из HA через секунду состояние "включено"  возвращается.
Отключаю и затем подключаю питание шлюза.

**Comment by dentra** [comment]
У меня все абсолютно идентично @remarkua

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
