### ISSUE TITLE
Taiwan Server

### ISSUE THREAD

**Issue by wberrazeg** [AlexxIT/XiaomiGateway3#208]
Hello,
Great work, thanks for the service.
Is it possible to map Taiwan's server? 
Thanks ;)

**Comment by AlexxIT** [comment]
As I know there is no Taiwan server in MiHome. All servers here:
https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/config_flow.py#L20

**Comment by wberrazeg** [comment]
They do, here is the list of servers : cn, de, us, ru, tw, sg, in, i2 (extracted from the tocken extractor app)

**Comment by AlexxIT** [comment]
Taiwan is sg (c) @rezmus

**Comment by rezmus** [comment]
in is sg (c) @rezmus ;)

it's common mistake in all projects which copied/ported mi cloud code from openhub, which made 1st public code with mi cloud support. there are only 6 api servers - cn, sg, de, ru, us, i2. the rest are just mappings.

**Comment by bluefoxlee** [comment]
@wowgamr you can check ([Xiaomi Iot debugger tool](https://debugger.iot.mi.com/iot/guide). Taiwan is using Singapore server. 

你用該工具選擇新加坡伺服器叫可以抓到你的台灣設備。

**Comment by wowgamr** [comment]
> @wowgamr you can check ([Xiaomi Iot debugger tool](https://debugger.iot.mi.com/iot/guide). Taiwan is using Singapore server.
> 
> 你用該工具選擇新加坡伺服器叫可以抓到你的台灣設備。

Looks like you made a missclick :)

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
