### ISSUE TITLE
add support for aqara M2 gateway please!

### ISSUE THREAD

**Issue by miniknife88** [AlexxIT/XiaomiGateway3#209]
This gateway supports more aqara new products~

**Comment by AlexxIT** [comment]
Check this repo https://github.com/niceboygithub/XiaomiGateway3

**Comment by miniknife88** [comment]
Thanks reply!
But this component is not perfect ! Cannot be used with xiaomi gateway3

**Comment by xrh0905** [comment]
> Thanks reply! But this component is not perfect ! Cannot be used with xiaomi gateway3

Why not use both of repo?

**Comment by AlexxIT** [comment]
I don't plan to support this model. Use this component
https://github.com/niceboygithub/AqaraGateway
