### ISSUE TITLE
Cannot control multiple devices simultaneously

### ISSUE THREAD

**Issue by dobl1** [AlexxIT/XiaomiGateway3#210]
Hi,

I use the v3 gateway with fm v1.4.5_0016, I have around 20 Yeelight Mesh Downlight (YLSD01YL) connected (Bluetooth Mesh Devices). Using some automation and lights groups, the behaviour is very slow, and very far from the simultaneous scenario wished.

For example I have 5 downlights in my corridor, tring to switch them on or off, first takes one second, then the second one also, the third, ... see the video below.

https://user-images.githubusercontent.com/9740002/107291201-136d3800-6a68-11eb-88fe-df328c1bbf92.mp4

Is this a known problem? If so, is a solution possible?
In the meantime, is there a workaround?

Thanks for your great work and help.

**Comment by AlexxIT** [comment]
Use MiHome mesh groups. They will sync with Hass as separate devices.

Not Hass groups. Not Mihome cloud groups!

**Comment by AlexxIT** [comment]
And update fw to 146 if MiHome offer you exact this firmware

**Comment by dobl1** [comment]
> Use MiHome mesh groups. They will sync with Hass as separate devices.
> Not Hass groups. Not Mihome cloud groups!

I had created a group, but not visible in hass ?
![image](https://user-images.githubusercontent.com/9740002/107333975-71c10780-6ab6-11eb-8bcc-33646f88eb1f.png)

> And update fw to 146 if MiHome offers you exact this firmware

Unfortunatly MiHome only offers me the 1.4.7_0115 👎

**Comment by AlexxIT** [comment]
Did you try restart integration/hass? Mesh updates only on first start.
Sometimes mesh group don't sync with gate. I don't know why. Some software problem.
You may try to recreate group once again with power off gate. May be it sync after gateway back online.

**Comment by dobl1** [comment]
Hi,

Yes I tried restart the integration, HASS, Gateway, even create a light group in Xiaomi Home and one in Yeelight
I also added new downlights and created a group, after I restarted HASS, I have the new downlights but not the new group ..

![image](https://user-images.githubusercontent.com/9740002/107663062-3d527480-6c8b-11eb-8181-c15ecd3d21ed.png)

Any ideas ?

**Comment by AlexxIT** [comment]
Can you control this group in MiHome if you not at home? To ensure if it works with gw3.

**Comment by dobl1** [comment]
Yeah, it works from outside. This is not local BT connection.

**Comment by AlexxIT** [comment]
Enable component logs and show what happened on component start.

**Comment by dobl1** [comment]
After installing the latest version (0.12.2) I can now see them !
Good !

**Comment by dobl1** [comment]
The behaviour is better but, next issue .. not related to this pluggin.

As I said I bought a whole lot of Yeelight YLSD01YL ceiling lights (smart downlight working in BT Mesh)

I have a strange behavior because some of these downlights are in version 1.3.0_0075 and others have version 1.2.0_0063 while the Xiaomi Home or Yeelight application tells me in both cases that the firmware version that is installed is the latest.

So I have the feeling that I don't have the same version of the hardware in these downlights and the big concern being that the way in which its lights are switching on and off is not the same. (1.2.0_0063 lights up fast and 1.3.0_0075 are more progressive). The consequence is that the visual experience is not good since I have some downlights light up before the others.

Is someone experiencing the same ? How should I proceed in order to unify the behavior of all my downlights ?

Same models, but ...
![image](https://user-images.githubusercontent.com/9740002/107832292-5bee6380-6d90-11eb-8110-f189b8ce9f22.png)

... Different latest firmware
![image](https://user-images.githubusercontent.com/9740002/107832318-6577cb80-6d90-11eb-87e3-f74771ce95a5.png)


I don't get it ..
