### ISSUE TITLE
Disable Internet Access on Gateway / BLE Devices stops working

### ISSUE THREAD

**Issue by colethegamer123** [AlexxIT/XiaomiGateway3#211]
Hello my friend,

I saw in the FAQ: If Internet Access is disabled on the Gateway, the BLE devices stops working.

I disabled the Internet access yesterday and tested all the Zigbee and WiFi devices working perfectly except my Bluetooth Mijia Temperature & Humidity Sensors. That is clear and exactly as you written in the FAQ.

My question is there is any way to solve that to make it work BLE devices locally? I can create ACLs on the router by device and add exceptions and whitelist entries. I would test a lot of things if you can give me some ideas what to test and how.

Woudl be really good if everything could work locally, with this AWESOME integration.

Thank you.

**Comment by AlexxIT** [comment]
We have some fix in custom firmware. I don't know if it works well. But it tries fix BLE without Internet.

**Comment by colethegamer123** [comment]
Thank you very much, I didnt even knew about Custom Firmware. I'll try this method. One more question and Im closing the issue of course. Do you think you will be able to solve this BLE Offline working method without Custom firmware ever? Or is it totally impossible without custom firmware? Thank you very much as always :)

**Comment by AlexxIT** [comment]
For now BLE very depends on Xiaomi basic software. So all in hands of Xiaomi developers.

**Comment by colethegamer123** [comment]
Understood. Thank you for the informations. Good to know! and keep up the good work we are really like your integrations, without you Smart Home wouldnt be the same :) Have a nice day bro.
