### ISSUE TITLE
Warning error GW3 in HA

### ISSUE THREAD

**Issue by Aliskin-Papa** [AlexxIT/XiaomiGateway3#213]
FIRST ERROR:
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 0:22:25 (9 occurrences)
Last logged: 1:11:55

Can't send get_properties [{'did': '374612397', 'siid': 3, 'piid': 1}]
Can't send enable_telnet_service None

AND SECOND ERROR:
Logger: zeroconf
Source: /data/data/com.termux/files/home/homeassistant/lib/python3.9/site-packages/zeroconf/__init__.py:404
First occurred: 0:30:57 (1 occurrences)
Last logged: 0:30:57

Error sending through socket 10
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/homeassistant/lib/python3.9/site-packages/zeroconf/__init__.py", line 2952, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
PermissionError: [Errno 1] Operation not permitted

Подскажите, куда копать? Кому какие права выдать и на что?

**Comment by AlexxIT** [comment]
Вторая ошибка с этой интеграцией не связана.
По первой, если ошибка не частая - проблемы с WiFi. Если постоянная - перезагрузить шлюз. Если не поможет - проверить, что не поменялся токен и IP шлюза.

**Comment by Aliskin-Papa** [comment]
Спасибо, понял.
Токен стабильный, ip выделенный.
У меня НА стоит на андроид телефоне под Termuxom и меня напрягает именно это "Can't send enable_telnet_service" в сообщении - как будто прав не хватает послать сигнал на открытие Телнета в шлюзе...

**Comment by Aliskin-Papa** [comment]
Перенес НА на ноутбук, тоже самое:
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 10:15:28 (1 occurrences)
Last logged: 10:15:28

Can't send get_properties [{'did': '374612397', 'siid': 3, 'piid': 1}]

И при этом ble обновляются меееедленно и редко...

**Comment by Aliskin-Papa** [comment]
Если несколько ble шлюзов в розетка, они могут мешать основному?

**Comment by AlexxIT** [comment]
Это запрос статуса алярма шлюза. Не связан с остальными BLE шлюзами
