### ISSUE TITLE
Gateway 3  v1.4.6_0043  ZNDMWG02LM

### ISSUE THREAD

**Issue by TRibyn** [AlexxIT/XiaomiGateway3#216]
Добрый день!!!
Я новичок в этом деле. По незнанию купил Gateway 3 v1.4.6_0043 - ZNDMWG02LM (Telnet c паролем) . Хочу подключить выключатели Lonsonho. Как я понял - нужно понизить прошивку... С пайкой дружу. Интересует очередность действий: HassWP установил, UART имеется, модифицированный Mi Home установлен. Не совсем понимаю про telnet. Или для понижения прошивки не требуется распароливать telnet? Прошу описать очередность моих действий.
Заранее спасибо и прошу прощения за дилетантские вопросы!!!

**Comment by zvldz** [comment]
https://github.com/AlexxIT/XiaomiGateway3/wiki/Decode-Telnet-Password
https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/uart_recovery
https://simple-ha.ru/posts/261
