### ISSUE TITLE
Humidity rounding problem for LYWSD03MMC and MHO-C401

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#218]
Each time data is received, the humidity value is increased on 0.1 points

<img width="300" alt="image_2021-02-12_13-22-17" src="https://user-images.githubusercontent.com/511909/107764099-aa741180-6d40-11eb-864a-cd6c29ecefb3.png">

**Comment by peetereczek** [comment]
Same here

![image](https://user-images.githubusercontent.com/42431204/107848508-385d0480-6df4-11eb-8954-f826cd55524f.png)

**Comment by Aliskin-Papa** [comment]
Заметил одну странность, как будто у интеграции сбивается таймер опроса ble датчиков по телнет:
- включаем статистику
- в свойствах устройства смотрим на время обновления BLE
- отсчитывает 10 минут, сброс таймера, 30 секунд = данные обновлены
- запуск следующего цикла
Но! Рамдомно (может час, два, пять все работает как нужно) 10ти минутный таймер слетает и висит 20, 30 и т.д. минут. Помогает либо рестарт интеграции, либо из панели разработчика выщов службы обновления объекта "Статус BLE" устройствп и таймер восстанавливается.
