### ISSUE TITLE
BLE - Flower Care don't show battery

### ISSUE THREAD

**Issue by armandomuassab** [AlexxIT/XiaomiGateway3#22]
Mi Flower Care don't show battery
![Mi Flower Care](https://user-images.githubusercontent.com/49219238/92983575-9e76e180-f47a-11ea-9369-0aef7b6341c5.png)

**Comment by AlexxIT** [comment]
What is yours? As I see here - one model does not send the battery:
https://esphome.io/components/sensor/xiaomi_ble.html

**Comment by AlexxIT** [comment]
> Newer versions of HHCCJCY01 ship with firmware 3.2.1, and they don’t send the battery level data anymore.

https://esphome.io/components/sensor/xiaomi_ble.html
