### ISSUE TITLE
Сброс таймера обновления BLE.

### ISSUE THREAD

**Issue by Aliskin-Papa** [AlexxIT/XiaomiGateway3#220]
Заметил одну странность, как будто у интеграции сбивается таймер опроса ble датчиков по телнет:
- включаем статистику
- в свойствах устройства смотрим на время обновления BLE
- отсчитывает 10 минут, сброс таймера, 30 секунд = данные обновлены
- запуск следующего цикла

Но - непредсказуемо (может час, два, пять все работать как нужно) 10ти минутный таймер слетает и висит 20, 30 и т.д. минут. Помогает либо рестарт интеграции, либо из панели разработчика вызов службы обновления объекта "Статус BLE" устройства и таймер восстанавливается.

**Comment by AlexxIT** [comment]
Последнее точно ничего не делает

**Comment by Aliskin-Papa** [comment]
Таймер 100% сбрасывается на объектах и начиеает новый отсчет, попробуй!

**Comment by AlexxIT** [comment]
Статус BLE именно так и работает. Он обновляется при каждом получении данных от устройства

**Comment by Aliskin-Papa** [comment]
А можно вставить в код проверку "если хоть одно ble устройство не апдейт > 11 минут, рестарт интеграции". Иначе, например, пользоваться датчиксми температуры ble стремно, они могут и на 30 минут и на 5 часов "зависнуть", а от них котел, батареи работают....

**Comment by AlexxIT** [comment]
Рестарт интеграции не подтянет новые данные. Шлюз не хранит данные от BLE устройств
