### ISSUE TITLE
Can't connect to gateway when adding for the second time from home assistant

### ISSUE THREAD

**Issue by adizanni** [AlexxIT/XiaomiGateway3#221]
Hello,
after the first succesful inclusion of the Gateway 3 to Home Assistant, I have tried to add the Gateway 3 integration to a brand new installation of Home Assistant. After the Mi Cloud connection to retrieve the token, I try to connect but I receive the error "Can't connect to gateway". The only difference between the two installations: the first working one is based on docker and custom the second failing one is based on Home Assistant OS and HACS. Should I reset the gateway ? Does this mean that I have to redo the procedure for retrieving the telnet password ? (my firmware is the v1.4.6_0043).
Thanks in advance for the support.

Andrea

**Comment by AlexxIT** [comment]
Reboot the gateway and try again

**Comment by adizanni** [comment]
Thanks @AlexxIT for the fast reply.
I have rebooted several times. The error is instantaneous when submitting Host and Token. it is like it is not even trying to connect to the network.  but I have no error in the logs. When I run the previous container (not together with the new one) everything works fine. I may miss something in the new setup, maybe a Python dependency.

**Comment by adizanni** [comment]
Hello,
I'm not sure what is the reason but once I have opened the Gateway in the firewall, the configuration procedure worked well. I think it has been reported already that you need internet connectivity for the gateway for the first configuration to work properly.
I close this issue.

Andrea

**Comment by cryptooth** [comment]
I have same issue. First step on integration works well. It find the Gateway after login my mi credentials, then I select and submit button. After that I re-add new integration an select Gateway, host and token automatically popsup. But when I hit to submit button, gettin "Can't connect to gateway" error message. I'm running latest version of HomeAssistant.
