### ISSUE TITLE
Every time error "Can't send get_properties"

### ISSUE THREAD

**Issue by Aliskin-Papa** [AlexxIT/XiaomiGateway3#223]
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 14:23:44 (2 occurrences)
Last logged: 14:34:44

Can't send get_properties [{'did': '374612397', 'siid': 3, 'piid': 1}]

**Comment by Aliskin-Papa** [comment]
Т.к. это у многих и вообще не понятно что это и когда починять, пока, чтоб не бесило, в файле mini-miio.py можно удалить 129 строчку (или зарезюмировать) - в ней идет вывод этой ошибки в лог НА, все продолжит работать, но в логе хотябы не будет этой ошибки.

**Comment by RediskaWzik** [comment]
Закомментил эту строчку (sock.sendto(raw_send, self.addr)
Но ошибка все равно в лог лезет.
