### ISSUE TITLE
Lonsonho Zigbee Switches with neutral fall off periodically

### ISSUE THREAD

**Issue by TRibyn** [AlexxIT/XiaomiGateway3#224]
Добрый день!!!
Периодически отваливаются выключатели Lonsonho c нейтралью (2шт). В приложении MiHome написано оффлайн, в HAss горят восклицательные знаки. Приходится каждый раз подключать через HAss. Выключатели подключил как Aqara lumi.switch.b1nacn02 QBKG23LM. Из функций- только вкл/выкл. Помогите пожалуйста решить проблему.
Заранее спасибо!!!

**Comment by AlexxIT** [comment]
Известная проблема с этими выключателями. В режиме MiHome плохо работают. Попробуйте ZHA

**Comment by TRibyn** [comment]
> Известная проблема с этими выключателями. В режиме MiHome плохо работают. Попробуйте ZHA

**Comment by TRibyn** [comment]
> Известная проблема с этими выключателями. В режиме MiHome плохо работают. Попробуйте ZHA

Я так понимаю, что через ZHA я не смогу управлять с телефона. Жаль, что HomeKit нельзя установить на андроид.

**Comment by AlexxIT** [comment]
Через MiHome работать не будет, но будет работать через приложение ХА

**Comment by TRibyn** [comment]
Странные дела... В Mi Home выключатели оффлайн, а в Алисе все работает, хотя подвязан Mi аккаунт.

**Comment by AlexxIT** [comment]
В ХА оффлайн, в mihome оффлайн, но из Алисы работают?

**Comment by TRibyn** [comment]
Через HA и Алису работают, в Mihome-оффлайн. Но к Алисе привязаны через аккаунт MiHome.

**Comment by TRibyn** [comment]
> В ХА оффлайн, в MiHome оффлайн, но из Алисы работают?

Через 2 дня отвалились в HA и в Алисе. Беда... 40$ на ветер((

**Comment by AlexxIT** [comment]
Говорят эти выключатели и в zigbee2mqtt себя так ведут...

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
