### ISSUE TITLE
Zigbee устройства оффлайн после даунгрейда шлюза

### ISSUE THREAD

**Issue by navyhod** [AlexxIT/XiaomiGateway3#226]
Привет!

Прошил шлюз кастомной прошивкой https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20210127 и подключил к HA. Сразу после этого все zigbee устройства ушли в офлайн так что я их переподключил к шлюзу.
Ночью отвалились датчики дверей и температуры. В HA и Mi Home пишет что датчики офлайн.

Это из-за кастомной прошивки?
Спасибо

**Comment by AlexxIT** [comment]
После даунгрейда шлюз нужно сбросить 10 раз нажав на кнопку.

**Comment by navyhod** [comment]
Спасибо! Надо внимательней читать :)
