### ISSUE TITLE
Invalid Add-on repository!

### ISSUE THREAD

**Issue by pavolfranek** [AlexxIT/XiaomiGateway3#229]
I have problem with add on this repozitory to Home Assistant. 

After I insert path https://github.com/AlexxIT/XiaomiGateway3 to Manage add-on repositories, I get an error.
![obrázok](https://user-images.githubusercontent.com/54669927/108139039-80637c00-70bf-11eb-8950-0cae75185920.png)

In system logs is:
![obrázok](https://user-images.githubusercontent.com/54669927/108139178-cae4f880-70bf-11eb-9d94-0b9bad74d283.png)

## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.94
arch | x86_64
timezone | UTC

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | beta
supervisor_version | supervisor-2021.02.9
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 2.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

Can you please help?

**Comment by zvldz** [comment]
component is already in hacs it does not need to be added

**Comment by AlexxIT** [comment]
This is HACS custom component, not Hass.io addon.

**Comment by pavolfranek** [comment]
Thans for help. I can try tonight install https://hacs.xyz/
