### ISSUE TITLE
Xiaomi Gateway 3 Pair

### ISSUE THREAD

**Issue by viiy** [AlexxIT/XiaomiGateway3#23]
After the last update one more "Xiaomi Gateway 3" has appeared.(i have just one).
And second one not available.  
![chrome_2020-09-12_08-03-34](https://user-images.githubusercontent.com/917219/92987797-7dd87700-f4ce-11ea-84e6-fb72cda04a04.png)
![chrome_2020-09-12_07-54-54](https://user-images.githubusercontent.com/917219/92987798-7fa23a80-f4ce-11ea-90ec-9928d7eaf507.png)

**Comment by mbratukha** [comment]
I have the same

**Comment by AlexxIT** [comment]
You can delete the old one by renaming it to `delete`
