### ISSUE TITLE
[zha mode] port 8888 - connection refused every couple of days

### ISSUE THREAD

**Issue by kkmaslowski** [AlexxIT/XiaomiGateway3#230]
Hi. 
I'm using gateway in zha mode with latest version (0.12.2). Every couple of days integration stops working. Gateway is responding to ping, but port 8888 is closed. I need to reboot gateway. Can you add any kind of watchdog for socat process or detect it from integration and auto repainr without reboot?

**Comment by AlexxIT** [comment]
Check if telnet connection works when you have problem with 8888

**Comment by kkmaslowski** [comment]
No. Telnet does not work too.

Telnet:
```
$ telnet 192.168.10.119
Trying 192.168.10.119...
telnet: connect to address 192.168.10.119: Connection refused
```

Socat:
```
$ telnet 192.168.10.119 8888
Trying 192.168.10.119...
telnet: connect to address 192.168.10.119: Connection refused
```

Ping:
```
$ ping 192.168.10.119
PING 192.168.10.119 (192.168.10.119) 56(84) bytes of data.
64 bytes from 192.168.10.119: icmp_seq=1 ttl=64 time=5.33 ms
64 bytes from 192.168.10.119: icmp_seq=2 ttl=64 time=2.44 ms
```

Nmap says that all ports are closed. After gateway restart nothing changes. Telnet port and 8888 is back after HA restart.

**Comment by AlexxIT** [comment]
Gateway has a problem with WiFi. It's block connection from different local IP if they have not been connected for a long time.
A quick turn off/on WiFi on the router helps me. It also helps to restart the Gateway.

**Comment by kkmaslowski** [comment]
Mi Router Pro flashed with latest OpenWRT. Maybe I should update gateway firmware to make it more stable?

**Comment by AlexxIT** [comment]
I don't know if latest fw helps. I'm using 0012 on my two gateway and both has this problem.

**Comment by kkmaslowski** [comment]
Sad to hear that. Maybe I create hardware watchdog - connect gw through wifi socket and restart it in case of not responding telnet.

**Comment by kkmaslowski** [comment]
@AlexxIT  do you know if problem is related to wpa_supplicant or custom xiaomi service? 

Do you know how telnet service is started? I don't see it in /etc/init.d/rcS.

I configured rsyslogd on gateway for remote logging, maybe I catch error when problem occurs.

**Comment by AlexxIT** [comment]
You can create watchdog on gateway. `ping` your server and run `ifconfig wlan0 down up` in case no ping.
In latest stock firmware you can create this file `/data/scripts/startup.sh`.
Gateway run in on each start.

**Comment by zvldz** [comment]
If you are using custom firmware you can also create script ```/data/run.sh```
Do not forget to make script executable.
```
chmod +x /data/run.sh
```

**Comment by kkmaslowski** [comment]
@AlexxIT @zvldz 
I created the following scripts, I will let you know if problem is solved. Are you sure that bringing down and up wlan0 fixes connection? I don't have serial to debug it.

/data/scripts/startup.sh
```
#!/bin/sh
pkill -f syslogd
syslogd -R 192.168.10.100:514

nohup /data/scripts/watchdog.sh >/dev/null 2>&1
```

/data/scripts/watchdog.sh
```
#!/bin/sh
                             
while true; do               
 if [ "$(ping -c 3 -w 3 8.8.8.8)" ]; then
  echo "ping ok, sleeping 30s"           
  sleep 30                               
 else                         
  echo "ping failed, bringing wlan0 down and up"
  ifconfig wlan0 down                           
  sleep 1                                       
  ifconfig wlan0 up  
 fi                
done
```

**Comment by zvldz** [comment]
You do not need to ping google, you need to ping HA server.

**Comment by AlexxIT** [comment]
`ifconfig wlan0 down up` in one line. You don't need pause.

**Comment by kkmaslowski** [comment]
Ok, changed it to:
```
#!/bin/sh

while true; do
 if [ "$(ping -c 3 -w 3 192.168.10.100 ]; then
  echo "ping ok, sleeping 30s"
  sleep 30
 else
  echo "ping failed, bringing wlan0 down and up"
  ifconfig wlan0 down up
 fi                
done 
```

**Comment by kkmaslowski** [comment]
@AlexxIT , @zvldz I created /data/scripts/startup.sh and rebooted gateway. I don't see my script running, syslogd wasn't configured for remote logging too.
I also tried to create /data/run.sh with contents like startup.sh and still the same. 

I created 2 scripts with content like below:
```
# cat /data/run.sh 
#!/bin/sh
echo run.sh >> /data/TEST

# cat /data/scripts/startup.sh
#!/bin/sh
echo startup.sh >> /data/TEST
```

and file /data/TEST is empty after reboot. Both scripts have correct permissions (755):
```
# ls -l /data/scripts/* /data/run.sh 
-rwxr-xr-x    1 admin    0               37 Mar  1 11:33 /data/run.sh
-rwxr-xr-x    1 admin    0              137 Mar  1 11:32 /data/scripts/startup.sh
-rwxr-xr-x    1 admin    0              106 Mar  1 10:15 /data/scripts/startup.sh.off
-rwxr-xr-x    1 admin    0              204 Mar  1 11:20 /data/scripts/watch
```dog.sh

**Comment by zvldz** [comment]
What fw do you have now?

**Comment by kkmaslowski** [comment]
> What fw do you have now?
How can I check it using telnet?

I found file /etc/rootfs_fw_info, it shows 1.4.6_0012:
```
# cat /etc/rootfs_fw_info 
product=aqara-rtl8197-gateway
branch=develop
VERSION=1.4.6_0012
version=1.4.6_0012

```

**Comment by zvldz** [comment]
/data/scripts/startup.sh is only in 1.4.7_*
/data/run.sh only in custom fw

You must update fw or install custom fw

**Comment by kkmaslowski** [comment]
> /data/scripts/startup.sh is only in 1.4.7_*
> /data/run.sh only in custom fw
> 
> You must update fw or install custom fw

What do you recommend - install custom or update original firmware? Custom firmware can be flashed only using uart

**Comment by zvldz** [comment]
with telnet
fw
https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20210127

https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware

**Comment by kkmaslowski** [comment]
> with telnet
> fw
> https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.6_0012_mod20210127
> 
> https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware

Good job @zvldz! I didn't know that there is any custom firmware. I'll test it.

**Comment by kkmaslowski** [comment]
Today at 8:50 my gateway stared to be very unresponsible. Ping varies from 100ms to 5s in local network. Other devices are working correctly. I'm on gateway through telnet, but I don't see anything suspicious. Loadavg is normal (0.67), no errors in dmesg. Telnet responds very, very slow. 
I'm attaching logs. Gateway is  unresponsive to the end of log. 
[gw3-unresponsive.txt](https://github.com/AlexxIT/XiaomiGateway3/files/6089128/gw3-unresponsive.txt)
Maybe someone will find something useful. If there is error in it that could be used as trigger for gateway reboot let me know. 
@zvldz is it possible to add Monit binary to your image?

I restarted wlan0 at 9:30 using 'ifconfig wlan0 down up' and it changed nothing. Physical reboot of gateway fixed problem.

**Comment by AlexxIT** [comment]
08:48:55 - cloud_retry

**Comment by kkmaslowski** [comment]
I see no issues on modded firmware '1.4.7_0160 #20210309'. 
I had no problems for 1 week.
