### ISSUE TITLE
entities under Xiaomi Flower Care (HHCCJCY01) and Xiaomi TH Sensor (LYWSDCGQ/01ZM) show unavailable

### ISSUE THREAD

**Issue by xjqsusu** [AlexxIT/XiaomiGateway3#231]
I'm using XiaomiGateway3 ver.v0.12.2. and found the entities from Xiaomi Flower Care (HHCCJCY01) and Xiaomi TH Sensor (LYWSDCGQ/01ZM) show unavailable. do you happen to know the issue and have a fix? both of them are Bluetooth devices.

Device info
HHCCJCY01
by Xiaomi
Xiaomi Gateway 3
Entities
Plant Zone 1 Conductivity
Unavailable
Plant Zone 1 Illuminance
Unavailable
Plant Zone 1 Moisture
Unavailable
Plant Zone 1 Temperature
Unavailable

Device info
LYWSDCGQ/01ZM
by Xiaomi
Xiaomi Gateway 3
Entities
Guest Bedroom Thermometer Battery
Unavailable
Guest Bedroom Thermometer Humidity
Unavailable
Guest Bedroom Thermometer Temperature
Unavailable

**Comment by AlexxIT** [comment]
Gateway don't get any data from this sensors

**Comment by xjqsusu** [comment]
So it is my BLE device issue? anything I can try to fix this? BTW, I can see data of those BLE devices from Mi app.

**Comment by mikeinblue** [comment]
You should confirm that the ble device connect mihome through the gateway.Sometimes these devices connect through other device with Bluetooth gateway funtion like 'camera' or 'outlet'.Hope can help you.

**Comment by mikeinblue** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/187

**Comment by xjqsusu** [comment]
Thank you mikeinblue. I do not have any other Ble gateway, xiaomi outlet or speaker. From mihome app, i can see all 5 ble devices connecting to the only xiaomi gateway I have.![image](https://user-images.githubusercontent.com/12121877/108917127-1f1e3a00-75e4-11eb-890b-efe15a5ce2ca.png)

**Comment by AlexxIT** [comment]
Have you tried reboot gateway?

**Comment by xjqsusu** [comment]
Yes I tried rebooting the gateway. My firmware version is v1.4.6_0012.

I see below message in the log. Not sure if it is related.

custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues) 
First occurred: February 23, 2021, 10:24:54 PM (7 occurrences) 
Last logged: February 23, 2021, 10:27:08 PM

Can't send get_properties [{'did': '332544765', 'siid': 3, 'piid': 1}]
Can't send enable_telnet_service

**Comment by xjqsusu** [comment]
they work fine after upgrading to ver.1.01
