### ISSUE TITLE
v1.4.7_0115 telnet using the custom open telnet command

### ISSUE THREAD

**Issue by nunokaneco** [AlexxIT/XiaomiGateway3#233]
Hello 

I just try follow the steps as indicated in the following link  

https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709#soft-hack-to-open-telnet

But I can't understand where is to use the command indicated 

{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}

And also I don't understand where is to use the IP of the hub also the token in this commands as indicated in the page before the command  

Anyone available to help me ? Thanks in advance for the support and best regards

**Comment by CODeRUS** [comment]
as soon as you start setup process you can spot all required fields

**Comment by nunokaneco** [comment]
> install integration from master branch or wait for release, then as soon as you start setup process you can spot all required fields

Thank you for your reply, I already have the gateway V3 integration installed in the home assistant, My question is now how can I execute the commands mentioned above, do you have any idea? 

Thank you and best regards

**Comment by zvldz** [comment]
Why if gateway is already in integration?

**Comment by nunokaneco** [comment]
> Why if gateway is already in integration?

Because I accidently perform the update on the xiaomi gateway V3 and I lost the devices from the integration. 
And now I hope with this commands can get this to work again ...

**Comment by zvldz** [comment]
Remove integration and add it again with the custom open telnet command

**Comment by nunokaneco** [comment]
> dd it again with the custom open telnet command

Great thank you, can you please let me know where is to execute this command?  Is in he HA home assistant command console?

**Comment by zvldz** [comment]
https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fsimple-ha.ru%2Fposts%2F261%23telnet-miio

**Comment by zvldz** [comment]
If you still have questions, go to the chat https://t.me/xiaomi_gw_v3_hack

**Comment by nunokaneco** [comment]
> If you still have questions, go to the chat https://t.me/xiaomi_gw_v3_hack

Great thank you once again 

I don't see the space to insert the  telnet command as mentioned, I have removed the integration add again but I still not have this space to insert the command 

![image](https://user-images.githubusercontent.com/33290686/108913828-6d522e00-7622-11eb-82f8-0a5f32cf728a.png)

**Comment by zvldz** [comment]
it means that you are not using the latest version of the component
