### ISSUE TITLE
Aqara wall switch

### ISSUE THREAD

**Issue by victor7325** [AlexxIT/XiaomiGateway3#237]
Hi 
Is it possible to support Aqara wall switch?
https://www.aqara.com/us/smart_switch_no_neutral.html

**Comment by AlexxIT** [comment]
Do you have it?

**Comment by victor7325** [comment]
Yes

**Comment by AlexxIT** [comment]
Enable basic and mqtt logs in Integration Options and send it to me.

**Comment by bluefoxlee** [comment]
Wonder does all US wall switch must be fw. ver 30 to get supported?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
