### ISSUE TITLE
Is it possible to support xiaomi wifi speakers?

### ISSUE THREAD

**Issue by lovelylain** [AlexxIT/XiaomiGateway3#238]
With zigbee2mqtt we can connect ZigBee devices to Home Assistant, but there is no easy gateway to connect bluetooth and BLE Mesh devices to HA. Xiaomi gateway 3 is the most perfect solution to access bluetooth devices so far, but it's a bit wasteful to buy a Xiaomi gateway 3 device just for this function. New Xiaomi wifi speakers generally have mesh gateway function, is it possible to connect to HA like Xiaomi gateway 3?

**Comment by AlexxIT** [comment]
This integration has nothing common with Xiaomi WiFi speakers...
