### ISSUE TITLE
Aqara N200 got no lock action imfortion 

### ISSUE THREAD

**Issue by mythcry** [AlexxIT/XiaomiGateway3#239]
![image](https://user-images.githubusercontent.com/16695553/109185343-e2f8fe00-77ca-11eb-81de-1544dd463fb9.png)
![image](https://user-images.githubusercontent.com/16695553/109185968-73cfd980-77cb-11eb-9f86-d1f47b3d48ad.png)

It got  lock information in the lock action entity before , but it got none now.

**Comment by AlexxIT** [comment]
Did you do something with the lock? Open/close door, etc.

**Comment by mythcry** [comment]
all tried , no info updated.

**Comment by AlexxIT** [comment]
Enable basic and mqtt logs in integration options and send it to me

**Comment by mythcry** [comment]
fixed in the newest update. Work normal now
