### ISSUE TITLE
Bluetooth loop error: 'mac'

### ISSUE THREAD

**Issue by viiy** [AlexxIT/XiaomiGateway3#24]
I see new message in log
ERROR    gateway3      Bluetooth loop error: 'mac'

**Comment by jie000jue** [comment]
the same error：
2020-09-14 03:57:47  DEBUG    gateway3      192.168.198.101 | Process BLE {'dev': {'did': '1010274797'}, 'evt': {'eid': 4110, 'edata': '00'}}
2020-09-14 03:57:47  ERROR    gateway3      Bluetooth loop error: 'mac'
2020-09-14 03:58:19  DEBUG    gateway3      192.168.198.101 | Process BLE {'dev': {'did': '1010274797'}, 'evt': {'eid': 4106, 'edata': '27'}}
2020-09-14 03:58:19  ERROR    gateway3      Bluetooth loop error: 'mac'

**Comment by AlexxIT** [comment]
What is your BLE device?

**Comment by jie000jue** [comment]
a Loock smart lock

**Comment by viiy** [comment]
I think in my case it is LYWSD03MMC or LYWSDCGQ or CJXJSQ02ZM because all other devices are working correctly.
The latter is not on the device list, but works entirely through the xiaomi_miio integration.

**Comment by AlexxIT** [comment]
@jie000jue please send some log and what actions were being done with the lock at that moment. I will try to add support

**Comment by jie000jue** [comment]
#open the door,the data may be encrypted
{'dev': {'did': '1010274797'}, 'evt': {'eid': 11, 'edata': '200000018757665F5F'}}

#when i change the battery,the data change
{'dev': {'did': '1010274797'}, 'evt': {'eid': 4106, 'edata': '3E'}}
{'dev': {'did': '1010274797'}, 'evt': {'eid': 4106, 'edata': '29'}}

#every 1 or 2 minutes,the data never change
{'dev': {'did': '1010274797'}, 'evt': {'eid': 4110, 'edata': '00'}}

**Comment by AlexxIT** [comment]
@jie000jue maybe the first request contains the identifier of the person who opened the door?
Does the content change if you open the door in a different way?
What's in the history in Mi Home for the same time stamps?

**Comment by jie000jue** [comment]
when i opened the door by the same figure again,it becomes  {'eid': 11, 'edata': '200100018032fc5f5f'}.Mi home displays me opened the door.

it doesn't have the sensor of opening/closing the door.Maybe pry the lock.

**Comment by rezmus** [comment]
https://iot.mi.com/new/doc/embedded-development/ble/object-definition

**Comment by AlexxIT** [comment]
@rezmus Awesome!

**Comment by AlexxIT** [comment]
Check release v0.3.0
