### ISSUE TITLE
Xiaomi Door Sensor 2 MCCGQ02HL No Triggers

### ISSUE THREAD

**Issue by Hyoengju-Johannes-Lee** [AlexxIT/XiaomiGateway3#241]
First of all, I am really grateful for your work.! It's sooooo amazing.!!

<img width="639" alt="스크린샷 2021-02-27 12 32 38" src="https://user-images.githubusercontent.com/62842483/109384785-e4741480-78f7-11eb-95d9-d917972f3a21.png">

It is configured well as a binary sensor and I can see the state in developer tools.

<img width="679" alt="스크린샷 2021-02-27 12 30 46" src="https://user-images.githubusercontent.com/62842483/109384756-bf7fa180-78f7-11eb-9ea7-a67ab90d5825.png">

But, when I try to make a trigger, it does not show anything..! What would be missing..?

**Comment by Hyoengju-Johannes-Lee** [comment]
Oops, idk what was the problem, but now it works.! Maybe because of the unstability of home assistant..?

**Comment by Hyoengju-Johannes-Lee** [comment]
Ah, I was confused.
Light detection works, but door open/close deteciton doesn not..!

**Comment by Hyoengju-Johannes-Lee** [comment]
Ah, I was confused.
In "Conditions" I can use Condition Type - Device and find the sensor, but there is no for triggers.

**Comment by AlexxIT** [comment]
Show the web page for this device

**Comment by Hyoengju-Johannes-Lee** [comment]
I don't know if it can help, but ok.! Here.!
<img width="1291" alt="Screenshot 2021-03-11 at 13 05 44" src="https://user-images.githubusercontent.com/62842483/110778250-c947c400-826a-11eb-8510-0e286f538eb6.png">

**Comment by AlexxIT** [comment]
In screen you have automations. Does it work now?

**Comment by Hyoengju-Johannes-Lee** [comment]
Nope..! I am using it temporarily with "State" trigger type.
"Device" still shows "Unknown trigger"

<img width="1291" alt="Screenshot 2021-03-11 at 13 05 44" src="https://user-images.githubusercontent.com/62842483/110780834-d1edc980-826d-11eb-86f7-6aab501b7474.png">

**Comment by AlexxIT** [comment]
I don't have BLE Door sensor. But it works with my Zigbee sensor without problem. Don't know what it can be.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
