### ISSUE TITLE
Unable to open setting for zh-Hant

### ISSUE THREAD

**Issue by vin-w** [AlexxIT/XiaomiGateway3#243]
Hello, 

https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/translations/zh-Hant.json#L29

line 29 has missing comma

`        "data": {`
`          "host": "主機端",`
**`          "token": "密鑰"`** 
`          "telnet_cmd": "開啟 Telnet 命令"`
`        }`

**log:**
Logger: homeassistant.util.json
Source: util/json.py:32
First occurred: 上午12:40:21 (54 occurrences)
Last logged: 下午12:16:43

Could not parse JSON content: /config/custom_components/xiaomi_gateway3/translations/zh-Hant.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 11 (char 907)

**Comment by vin-w** [comment]
Created PR: https://github.com/AlexxIT/XiaomiGateway3/pull/244

**Comment by AlexxIT** [comment]
Fixed in latest master
