### ISSUE TITLE
Xiaomi Gateway 3 Firmware Lock cannot be turned on

### ISSUE THREAD

**Issue by leokklai** [AlexxIT/XiaomiGateway3#245]
Why I cannot turn on "Xiaomi Gateway 3 Firmware Lock" after used this integration?  When I switched this on, it will eventually turn to off after few seconds.  Or I need to flash the firmware in order to use this firmware lock?

**Comment by AlexxIT** [comment]
It is broken on new stock firmwares

**Comment by leokklai** [comment]
Thanks for your reply.  You mean that it cannot be locked if I am using the latest version of Gateway 3?

**Comment by AlexxIT** [comment]
Fix in latest master version

**Comment by leokklai** [comment]
Many thanks!

**Comment by ALERTua** [comment]
still doesn't work @ 1.4.7_0160

**Comment by AlexxIT** [comment]
Maybe you don't use latest master?

**Comment by ALERTua** [comment]
worked flawlessly after flashing https://github.com/zvldz/mgl03_fw/tree/main/firmware/custom/mgl03_1.4.7_0160_mod20210309

**Comment by AlexxIT** [comment]
It should work on vanilla firmware on latest master

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
