### ISSUE TITLE
Support change zigbee devices settings

### ISSUE THREAD

**Issue by a120578270** [AlexxIT/XiaomiGateway3#246]
Information about the device + link
Aqara high precision motion sensor (RTCGQ13LM; lumi.motion.agl04)

It has 2 parameters for customization:

Sensitivity adjustment (High; Middle; Low)
Detection period (2-180s, step: 1s)

The Xiaomigateway3 plugin does not currently support this setting!

![image](https://user-images.githubusercontent.com/58241282/109461869-bd574780-7a9d-11eb-9745-818e15d21598.png)

https://oh-lalabs.com/articles/review-aqara-high-precision-motion-sensor-rtcgq13lm
https://community.oh-lalabs.com/t/the-new-aqara-high-precision-motion-sensor-rtcgq13lm/484
https://www.reddit.com/r/Aqara/comments/k7aeqy/aqara_high_precision_motion_sensor_rtcgq13lm/
https://www.reddit.com/r/Aqara/comments/kksfnw/quick_test_aqara_high_precision_motion_sensor/
https://www.youtube.com/watch?v=h6hd60FS650
https://aliexpress.com/item/1005001739628125.html
https://item.jd.com/10024066313112.html

Some related information：
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2199/files

**Comment by a120578270** [comment]
Could you prioritize this requirement earlier?Due to work reasons, I am often out of the house, and soon I can go home for a few days. I hope I can test and use this function normally then. Thanks again!

**Comment by AlexxIT** [comment]
I don't prioritize enhancement while known bugs exists.

**Comment by a120578270** [comment]
> I don't prioritize enhancement while known bugs exists.

Hello, is there any other way, such as command, to first set the detection time and sensitivity of AQARA High Precision Human Body (RTCGQ13LM)? Now it is configured to the multi-mode gateway, the default is 2 minutes, and the cooling time is too long to use!

**Comment by AlexxIT** [comment]
I think this should be done through the miio protocol, but I don't have any working commands. You can try to use vevs mod for MiHome. Maybe it supports settings for this sensor

**Comment by a120578270** [comment]
> I think this should be done through the miio protocol, but I don't have any working commands. You can try to use vevs mod for MiHome. Maybe it supports settings for this sensor
I tried to use MIOT to see only this device, but the content log in it was all empty, indicating that MIHOME did not support this device. This setting is only available in AQARA APP!

**Comment by rezmus** [comment]
sensitivity (1 low, 2 medium, 3 high)
```
{"method":"set_properties","params":[{"did":"YOUR_DID","siid":8,"piid":1,"value":X}],"id":12345}
```
detection interval (2-180s)
```
{"method":"set_properties","params":[{"did":"YOUR_DID","siid":10,"piid":1,"value":X}],"id":12346}
```
you have to send the command and click reset button on sensor immediately after.

**Comment by ha0y** [comment]
> sensitivity (1 low, 2 medium, 3 high)
> 
> ```
> {"method":"set_properties","params":[{"did":"YOUR_DID","siid":8,"piid":1,"value":X}],"id":12345}
> ```
> 
> detection interval (2-180s)
> 
> ```
> {"method":"set_properties","params":[{"did":"YOUR_DID","siid":10,"piid":1,"value":X}],"id":12346}
> ```
> 
> you have to send the command and click reset button on sensor immediately after.

Hello,
this is a Zigbee device, not a wifi device, so we can not send commands like this using miio tools. And we've tried sending the MIoT commands to Xiaomi Cloud using [MIoT integration](https://github.com/ha0y/xiaomi_miot_raw), but it is also of no use.

If we are to send commands to Zigbee devices directly, we should use zigbee cluster commands.

**Comment by rezmus** [comment]
@ha0y just send cmd to hub ip/token ;) YOUR_DID is sensor did so hub knows which zigbee device it's addressed to. i tested this with my mgl03 hub and lumi.motion.agl04, everything works.

**Comment by ha0y** [comment]
> is sensor did so hub knows which zigbee

That's great, thanks! Have never thought that the command can be used in this way.

**Comment by a120578270** [comment]
> @ha0y just send cmd to hub ip/token ;) YOUR_DID is sensor did so hub knows which zigbee device it's addressed to. i tested this with my mgl03 hub and lumi.motion.agl04, everything works.

Hello, could you tell me specifically where to send this command? Then which contents in the command need to be modified for their own devices, thank you!

**Comment by rezmus** [comment]
i send cmds from pc to hub using local miio udp 54321 with php-miio (can be also done via cloud rpc). if you have motion sensor with DID send this cmd to hub IP and encrypt with hub TOKEN to change detection interval to 5s (remember to click reset button on sensor just after sending cmd).
```
php miio-cli.php --ip IP --token TOKEN --sendcmd '{"method":"set_properties","params":[{"did":"DID","siid":10,"piid":1,"value":5}],"id":12345}'
```

**Comment by ha0y** [comment]
@rezmus You said this command can be done by cloud rpc. Have you also tried ``get_properties`` via cloud rpc? I've tried before but the server just returns `{}`, unlike any other Xiaomi devices.

**Comment by rezmus** [comment]
use /home/rpc/did not /miotspec/prop/get

**Comment by a120578270** [comment]
> i send cmds from pc to hub using local miio udp 54321 with php-miio (can be also done via cloud rpc). if you have motion sensor with DID send this cmd to hub IP and encrypt with hub TOKEN to change detection interval to 5s (remember to click reset button on sensor just after sending cmd).
> 
> ```
> php miio-cli.php --ip IP --token TOKEN --sendcmd '{"method":"set_properties","params":[{"did":"DID","siid":10,"piid":1,"value":5}],"id":12345}'
> ```

Hello! Could you share the php-miio file?

**Comment by rezmus** [comment]
https://github.com/skysilver-lab/php-miio

**Comment by a120578270** [comment]
> https://github.com/skysilver-lab/php-miio
Thank you, "value":5 means a cooldown of 5 seconds, right? Is the sensitivity "piid":1? Is 1 the lowest? Three is the highest, right?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
