### ISSUE TITLE
Xiaomi Door Sensor 2 MCCGQ02HL нет данных заряда батареи и освещенности.

### ISSUE THREAD

**Issue by stylishkrio** [AlexxIT/XiaomiGateway3#248]
Если перезагрузить Xiaomi Gateway 3 то данные по освещенности не приходят с датчика. Помогает включение, выключение в пункте "Dim/bright light detection" в настройках самого датчика в mi home.
Данных по заряду батареи совсем нет.
![Снимок1t](https://user-images.githubusercontent.com/77132140/110209541-3b508f80-7e9e-11eb-8a02-f7320269121b.png)

**Comment by AlexxIT** [comment]
Проверьте новую версию работы с BLE в последнем мастере

**Comment by stylishkrio** [comment]
> Проверьте новую версию работы с BLE в последнем мастере

Полностью переподключил устройства к mi home. Xiaomi Gateway 3 firmware v1.4.7_0160 и v1.1b3. и BLE 1.3.0 и данные с датчиков появилась. Но.. позже перезагрузил Xiaomi Gateway 3. И увы..
![Снимок2-1](https://user-images.githubusercontent.com/77132140/110836988-c7edba00-82b1-11eb-8522-ad7fc5283404.png)

**Comment by AlexxIT** [comment]
Подождали какое-то время?

**Comment by stylishkrio** [comment]
> Подождали какое-то время?

Да. Но данные не появляются.

**Comment by pervolianinen** [comment]
> > Подождали какое-то время?
> 
> Да. Но данные не появляются.

Видимо ждать нужно ооочень долго. У меня открытие закрытие через 12 часов появилось...

**Comment by stylishkrio** [comment]
> > > Подождали какое-то время?
> 
> > 
> 
> > Да. Но данные не появляются.
> 
> 
> 
> Видимо ждать нужно ооочень долго. У меня открытие закрытие через 12 часов появилось...
> 
> Потом все подцепилось по факту действия. Смена света, открытие, батарея. Видимо сервера xiaomi на активацию влияют

Ну это тоже не дело такие интервалы.

**Comment by stylishkrio** [comment]
Есть такие четыре датчика. Стабильно после перезагрузки отваливается один любой. После 24 часов ожидания он не как не "оживает". 
![Снимок](https://user-images.githubusercontent.com/77132140/114276089-d56f9e80-9a2d-11eb-97fe-ef12c23ace6f.PNG)

**Comment by ekranas13** [comment]
Hey, love your work. 

I translated the discussion from russian and the author seems to have a similar issue to mine.

I have five xiaomi MCCGQ02HL door and window sensor 2. 4 of them work flawlessly. The fifth one displays the correct door opening and correct light illumination data. But its battery entity is always undefined. At first I thought its the device error but then I noticed this in the logs:

2022-02-20 00:17:21  DEBUG    base          192.168.1.231 [MQTT] ble/{1st} b'{"battery":100,"contact":0,"light":1}'
2022-02-20 00:17:21  DEBUG    base          192.168.1.231 [MQTT] ble/{2nd} b'{"contact":0,"light":0,"battery":80}'
2022-02-20 00:17:21  DEBUG    base          192.168.1.231 [MQTT] ble/{3rd} b'{"contact":0,"light":0,"battery":100}'
2022-02-20 00:17:21  DEBUG    base          192.168.1.231 [MQTT] ble/{4th} b'{"contact":0,"light":0,"battery":100}'
2022-02-20 00:17:21  DEBUG    base          192.168.1.231 [MQTT] ble/{5th} b'{"contact":1,"light":0,"battery":100}'

The fifth device almost has direct view of the gateway and is positioned about 7 meters away from it.

I tried waiting for more than 12 hours. I tried readding the device to the xiaomi gateway. Could you suggest something I could try?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
