### ISSUE TITLE
XiaomiGateway3 add ZHA , but Failed to connect 

### ISSUE THREAD

**Issue by SYMLY** [AlexxIT/XiaomiGateway3#249]
Hi AlexxIT!

I use the lumi.gateway.mgl03 ZNDMWG03LM. 
successful integration into the homassistant 
I successfully updated firmware via telnet 1.4.6_0012 #20210127   version
In the gateway config when I switch to mode MI HOME --> ZHA the notification is displayed
"Please create manually
Integration: Zigbee Home Automation......." 

I want manual create 
I fill it in with the appropriate data   just like in the video:
[https://www.youtube.com/watch?v=AEkiUK7wGbs&feature=youtu.be&ab_channel=AlexxIT](url)

but after submit:  Failed to connect

![image](https://user-images.githubusercontent.com/4970517/109806319-ddfdd980-7c24-11eb-859c-9dd6ea83a643.png)

**Comment by zvldz** [comment]
Maybe it's because site where 'socat' was downloaded from is now down. Try downloading 'socat' from http://mipsel.vacuumz.info/files/socat and putting it on gw in /data.
Also make it executable 'chmod +x /data/socat'

**Comment by SYMLY** [comment]
exists.
should I replace it?

**Comment by zvldz** [comment]
If 'socat' is in /data, then that's not it. Maybe @AlexxIT can suggest something.

**Comment by pervolianinen** [comment]
Has "failed to connect" - too. 
firmware gateway3 1.4.7_0115 putched.
Ha 2021.1.5

**Comment by AlexxIT** [comment]
Try to reboot gateway and setup ZHA integration again

**Comment by SYMLY** [comment]
Reboot didn't help it

**Comment by pervolianinen** [comment]
> Try to reboot gateway and setup ZHA integration again

Все тоже самое.

**Comment by doosterkamp** [comment]
I have the same issue:
https://community.home-assistant.io/t/xiaomi-mijia-smart-multi-mode-gateway-zndmwg03lm-support/159586/382

**Comment by zvldz** [comment]
Try the master version of the component

**Comment by SYMLY** [comment]
I have done this many times 
reboot --> mode change ZHA-->the notification comes (Please create manually ....)  --> try but Failed to connect
reboot --> try again : Failed to connect
change mod back MI Home -->  reboot 
and again first 

![image](https://user-images.githubusercontent.com/4970517/110008979-a8d4b280-7d1c-11eb-8eff-a49df4c456b8.png)

**Comment by SYMLY** [comment]
i don't know if that means anything
shouldn't be here a 8888 port 
![image](https://user-images.githubusercontent.com/4970517/110010010-16351300-7d1e-11eb-8e6f-3d0f5123c5b6.png)

**Comment by doosterkamp** [comment]
Still the same problem ...

What I just did:  

- Switch back the Gateway to `Mi Home` mode in HA
- Reset the Gateway
- Delete the integration from my main HA setup
- Unplug the Gateway and drank a cup of coffee (hard/cold reset)   
---  

- Downloaded a fresh HA playground [HassWP](https://github.com/AlexxIT/HassWP) for testing, just to be sure it isn't my RPi2 having difficulties
- Plugged in the Gateway and waited until it finished booting/initializing
- Reinstalled the `Xiaomi Gateway 3` integration, selecting `master` in HACS:  
  ![image](https://user-images.githubusercontent.com/1842171/110018177-5351d300-7d27-11eb-85f1-7d2c8b3ea651.png)  
- Restarted HA
- Added the `Xiaomi Gateway 3` integration to HA
- Clicked `options` and switched to `Zigbee Home Automation (ZHA)` mode:
  ![image](https://user-images.githubusercontent.com/1842171/110018918-20f4a580-7d28-11eb-96d2-9e4456aef13c.png)  
- Submitted it and waited for the notification:
  ![image](https://user-images.githubusercontent.com/1842171/110019044-45508200-7d28-11eb-9a6c-371f556b9d17.png)
- Add the `ZHA` integration
  - Select `Enter Manually` as Serial device path
  - Select `EZSP` as Radio Type
  - Copy/pasted the Serial Device Path: `socket://192.168.5.1:8888` and set port speed to `115200`
  - After clicking submit:  
    ![image](https://user-images.githubusercontent.com/1842171/110019608-f525ef80-7d28-11eb-94af-db64ffc38b12.png)
---
In short, nothing changed ...

**Comment by doosterkamp** [comment]
![image](https://user-images.githubusercontent.com/1842171/110020346-bb091d80-7d29-11eb-8ed8-79fdecc17151.png)
  
![image](https://user-images.githubusercontent.com/1842171/110020525-f4418d80-7d29-11eb-99fe-8601a33827b0.png)

**Comment by AlexxIT** [comment]
Fix in latest master version!

**Comment by doosterkamp** [comment]
@AlexxIT, the above uses the latest master version! Issue stays

**Comment by pervolianinen** [comment]
> Fix in latest master version!

Testing. Work fine with ha 2021.3.0

**Comment by SYMLY** [comment]
Hy @AlexxIT !

Open telnet in gateway and run your latest modiy link on the socat 

wget -O /data/socat http://pkg.simple-ha.ru/mipsel/socat && chmod +x /data/socat

reboot and everything is fine. 

I respect you very much. I am very happy with this all development.

**Comment by AlexxIT** [comment]
Hm. The latest master version should download this file automatically.

**Comment by AlexxIT** [comment]
@doosterkamp check if you not block Internet for gateway. Because it try to load necessary file.

**Comment by doosterkamp** [comment]
I just did the whole procedure (mentioned above) again ...
Still get a `Failed to connect`  
  
I tried what @SYMLY did:
![image](https://user-images.githubusercontent.com/1842171/110082842-31d80200-7d8e-11eb-833c-5736152f4128.png)    
This means the device has a 
And again did the whole procedure ...
Still get a `Failed to connect`  

Although, I just noticed that there's an error in the console, when clicking submit and the ZHA integration tries to connect, tha HA console shows the following error:
```
2021-03-05 08:42:36 ERROR (bellows.thread_0) [homeassistant] Error doing job: Exception in callback SerialTransport._poll_write()
Traceback (most recent call last):
  File "C:\Users\denni\Downloads\HassWP_2021.1.1\python-3.8.7\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\denni\Downloads\HassWP_2021.1.1\config\deps\Python38\site-packages\serial_asyncio\__init__.py", line 304, in _poll_write
    if self.serial.out_waiting:
AttributeError: 'Serial' object has no attribute 'out_waiting'
```

**Comment by doosterkamp** [comment]
Okay ... **I've got it working!**

- Switched back to my RPi, updated the HA Core to version 2021.3.1 (released today)  
- Restarted `EVERYTHING` ... again  
- walked through all the steps ... again  
  
And now the ZHA integration connects ...

@AlexxIT : with you HassWP setup it still doesn't by the way, but that's no priority anymore.
@AlexxIT 👍 Thank you very very much 👍 
@zvldz 👍 Also many thanks!
