### ISSUE TITLE
Cant send get_properties

### ISSUE THREAD

**Issue by colethegamer123** [AlexxIT/XiaomiGateway3#251]
Hello Alex! I hope your fine and I does not disturb you.

Since the newest updates I get the following error message:
```
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 2021. március 4. 22:20:34 (1246 occurrences)
Last logged: 8:43:06

Can't send get_properties [{'did': '317104647', 'siid': 3, 'piid': 1}]
```

I dont know what triggered this messages, but yesterday two things happened. I installed the newest Core & Supervisor version of Home Assistant and there was an electrical blackout in my house. All the devices are working correctly. I dont know which device are the integration speaking of, or it speaking about the gateway itself? I dont know, I never update any device's firmware and im using the integration since the first day, and this only came now.

Thank you very much for your effort.

Have a nice day.

**Comment by colethegamer123** [comment]
Please wait a bit, maybe the tomorrow morning update fix is fixed my problem, give me a day of testing and i'll proactively close the issue. Thank you.

**Comment by AlexxIT** [comment]
Duplicate #223
