### ISSUE TITLE
Gateway Offline, but HA still show entities as Available

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#253]
IMHO this is fundamental issue regarding devices/entities availability.

After powering XG3 off - MiHome show it Offlne after some short time,
* but in HA all related entities still in Available status even after 10+ minutes.

Core log:

Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:129
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 20:08:35 (45 occurrences)
Last logged: 20:21:09

Can't send get_properties [{'did': '{censored}', 'siid': 3, 'piid': 1}]
Can't send set_ip_info {'ssid': '""', 'pswd': '123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd'}

RPi4 4G, Home Assistant OS 5.12, core-2021.3.0

**Comment by AlexxIT** [comment]
HA can receive offline state from gateway. If MiHome knows it - HA will know it. You nave another problem with connection to gateway

**Comment by rqariot** [comment]
Hi
I have the same problem, XG is Offline in HA, devices are unavailable but in the MiHome application, XG is available.
regards.

**Comment by AlexxIT** [comment]
Maybe you don't have connection between HA and Gate. But you have connection between Gate and Cloud.
This is happened with some wifi routers.

**Comment by rqariot** [comment]
Thanks for your response.
It works during a month. but suddenly, it seems offline. I restart the gateway without succes.
HA and gateway are on the same network. I will check the connection between gate and cloud, has HA using the mi cloud?
regards

**Comment by AlexxIT** [comment]
No. Component doesn't controls devices via cloud

**Comment by AlexxIT** [comment]
You can try

**Comment by rqariot** [comment]
hello, 
I try with the latest version, bau I have the same problem
![image](https://user-images.githubusercontent.com/17224633/116828206-87b60400-ab9d-11eb-9cab-97de13b64ebe.png)
regards

**Comment by AlexxIT** [comment]
Check errors in logs

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
