### ISSUE TITLE
Problem with alarm trigger

### ISSUE THREAD

**Issue by elenril2** [AlexxIT/XiaomiGateway3#257]
I have a problem with alarm trigger, my device is lumi.gateway.mgl03. I've notice that when the alarm is triggered there's no change to state of alarm_control_panel - it's still armed_away and not alarm_trigger. Furthermore my automations in Mi Home  which trigger outdoor alarm siren also didn't work. There is no info about this in HA logs. I also have a suspicion that alarm states changes is reporting in Home Assistant entity with delay.

**Comment by bvermes17** [comment]
Hello @AlexxIT ,

Do you see any workarounds for this? Is anyhow the information of an ongoing alarm transferred to HA from the Gateway that can be used for automations on alarm trigger? 

Thanks a lot!

Belián

**Comment by elenril2** [comment]
The delay is also quite problematic. And I think this is a bug in developed feature and not enhancement.

**Comment by bvermes17** [comment]
Hello @elenril2 ,

I see no issue with the display of current state. As soon as I arm the alarm the state of the alarm entity is changed from disarmed to armed. 

You might want to check this on your end.

**Comment by elenril2** [comment]
Hi,
if I perform this action from HA, the state of the entity changes immediately. However, if I arm the alarm from Xiaomi Home, there is a delay. For example, I have automation in Xiaomi Home, when the alarm is armed at 2:30, in HA this action is recorded at 2:31:49.

**Comment by bvermes17** [comment]
Hello @elenril2 ,

I see what you mean now. I don't use automations in Mi Home so I don't know how that works.

**Comment by tam-wh** [comment]
I opened a pull request for this fix
#349

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
