### ISSUE TITLE
Last Update wrong on timed out / offline sensor

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#259]
Home Assistant OS 5.12, core-2021.3.0.
+ ZNDMWG02LM, lumi.sen_ill.mgl01 GZCGQ01LM

Gateway online, lumi sensor offline for 2 hours.
![image](https://user-images.githubusercontent.com/15225823/110242452-eb85cd00-7f5e-11eb-8f15-06af6bbf3d01.png)

Sensor Last Update (I'm right?) shows as on Gateway, but not sensor.
![image](https://user-images.githubusercontent.com/15225823/110242478-0bb58c00-7f5f-11eb-804f-66e8e2e0f44b.png)

**Comment by AlexxIT** [comment]
Component load last value from gate. Also load online state. But sensor don't send anything yet.

**Comment by Masterz69** [comment]
Sensor state on XG3 - OFFLINE. No data last 2 hours.
But in HA sensor state NOT Unavailable, and last state = 34 minutes.
Not match.

**Comment by Masterz69** [comment]
Checked Mi Home log for that sensor:
13:59 Light intensity is: 3 Lux <- sensor battery was removed

~ 16:05 - Mi Home show sensor as offline
? May be XG3 sent this information to HA, but status not updated, sensor in HA still ONLINE.

16:46 Light intensity is: 7 Lux <- battery inserted back

When screenshot taken - there is no data FROM sensor for 2+ hours.
Maybe gateway sent information ABOUT sensor status, but IMHO: 
* information ABOUT sensor (status?) not same as information FROM sensor.

IMHO.

**Comment by Masterz69** [comment]
Minor issue, no need to spend time on it. IMHO. Thank You for developing such a usefull add-on.
