### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by modem** [AlexxIT/XiaomiGateway3#261]
I've noticed my gateway and connected devices stopped reporting any data more than 12h ago. I have the following Uncaught thread exception in the logs.

Logger: root
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:139
First occurred: 3:23:46 AM (1 occurrences)
Last logged: 3:23:46 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 422, in run
    if not self._check_port(23) and not self._enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 452, in _enable_telnet
    if self.miio.send(raw['method'], raw.get('params')) != 'ok':
  File "/config/custom_components/xiaomi_gateway3/core/mini_miio.py", line 139, in send
    return json.loads(data.rstrip(b'\x00'))['result']
KeyError: 'result'

The most recent data I got was at 3:20:00 AM, just before this error.
After reloading the Integration I started to receive data again.

**Comment by xedsvg** [comment]
Are you using ZHA or cloud setup?

**Comment by modem** [comment]
I don't have any zigbee devide, I use it with several Xiaomi Temperature and Humidity Sensor 2 (LYWSD03MMC) which are BLE.

**Comment by modem** [comment]
I got the error again on March 12, and the sensors are quiet since then.

Logger: root
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:139
First occurred: March 12, 2021, 8:29:15 PM (1 occurrences)
Last logged: March 12, 2021, 8:29:15 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 422, in run
    if not self._check_port(23) and not self._enable_telnet():
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 452, in _enable_telnet
    if self.miio.send(raw['method'], raw.get('params')) != 'ok':
  File "/config/custom_components/xiaomi_gateway3/core/mini_miio.py", line 139, in send
    return json.loads(data.rstrip(b'\x00'))['result']
KeyError: 'result'


Is there any way to detect this error and send a notification?

**Comment by AlexxIT** [comment]
Do you read supported firmwares section in readme?

**Comment by modem** [comment]
Yes, I have the firmware v1.4.7_0115 which is under "Supported firmwares with custom open telnet command", then I've added the following command to the gateway configuration:
{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}

I have also selected Mi Home at the bottom, so it's cloud. Shame on me :sweat_smile: .
![image](https://user-images.githubusercontent.com/62859/111153209-9151c100-8589-11eb-9000-a56e15c7f51e.png)

**Comment by AlexxIT** [comment]
This command fail if gateway don't connected to Xiaomi Cloud.

**Comment by modem** [comment]
Maybe it can happen when there's a glitch in the internet connection, of the cloud may have sporadic issues...

**Comment by AlexxIT** [comment]
I think issue fixed in latest version
