### ISSUE TITLE
State still keep "off" even door is opened in Xiaomi Door Sensor 2

### ISSUE THREAD

**Issue by leokklai** [AlexxIT/XiaomiGateway3#265]
Just found the state not update when door is opened in Xiaomi Door Sensor 2 (MCCGQ02HL).

**Comment by AlexxIT** [comment]
Have you tried latest BLE logic from latest master?

**Comment by leokklai** [comment]
Where can I find the latest BLE logic?  Thanks in advance.

**Comment by AlexxIT** [comment]
In latest master version. You can install it with HACS reinstall option

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
