### ISSUE TITLE
Датчик WSDCGQ11LM не показывает значение батарейки.

### ISSUE THREAD

**Issue by adisik** [AlexxIT/XiaomiGateway3#268]
В HA не показывает значение батарейки для датчика WSDCGQ11LM 
![изображение](https://user-images.githubusercontent.com/12948757/110907433-6fa0d180-831e-11eb-89b1-07456bbbdc25.png)

**Comment by adisik** [comment]
Версия интеграции 1.1b3, на трех предыдущих тоже не было значения батарейки.

**Comment by AlexxIT** [comment]
Включите логи в настройках интеграции - basic+mqtt, соберите за 12 часов и пришлите. Можно в личку Телеграм

**Comment by adisik** [comment]
Отправил лог в телеграм

**Comment by adisik** [comment]
Помогло обновление прошивки шлюза до версии mgl03_1.4.7_0115_mod20210309 и установка версии компонента v1.1b3 - 2021-03-11.
@AlexxIT , спасибо за помощь.
