### ISSUE TITLE
IKEA GU10 Tradfri white spectrum bulb (LED1737R5, LED1739R5)

### ISSUE THREAD

**Issue by Sleinous** [AlexxIT/XiaomiGateway3#27]
Hi there,
Noticed a couple of IKEA bulbs were already supported on Gateway 3 integration (E14 & E27) - wondering if there are plans / if I can be of use to get the IKEA GU10 white spectrum bulbs added ? https://www.ikea.com/fr/fr/p/tradfri-ampoule-led-gu10-400-lumen-sans-fil-a-variateur-dintensite-spectre-blanc-90408603/

I noticed that Xiaomi Miio component mentions ZNDMWG03LM gateway but not yet tested/supported - they have an interesting list of IKEA bulbs though : 

https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-gateway

IKEA smart bulb E27 white | ikea.light.led1545g12 | LED1545G12
IKEA smart bulb E27 white | ikea.light.led1546g12 | LED1546G12
IKEA smart bulb E12 white | ikea.light.led1536g5 | LED1536G5
IKEA smart bulb GU10 white | ikea.light.led1537r6 | LED1537R6
IKEA smart bulb E27 white | ikea.light.led1623g12 | LED1623G12
IKEA smart bulb GU10 white | ikea.light.led1650r5 | LED1650R5
IKEA smart bulb E12 white | ikea.light.led1649c5 | LED1649C5

My bulb is listed as LED1737R5, LED1739R5 so i'm assuming : ikea.light.led1737r5 & ikea.light.led1739r5

I noticed the IKEA bulb you tested is the LED1649C5 but i'm wondering how you obtained the necessary params ?

```
{
    # light with brightness
    'ikea.light.led1649c5': ["IKEA", "Bulb E14"],  # tested
    'params': [
        ['4.1.85', 'power_status', 'light', 'light'],
        ['14.1.85', 'light_level', 'brightness', None],
    ]
},
```

Thanks

**Comment by AlexxIT** [comment]
No problem, will add soon

**Comment by Sleinous** [comment]
Thanks @AlexxIT, let me know if you need anything from me that I can maybe get from Mi home app debug. These bulbs are dimmable and colour changeable (from white to yellow)

**Comment by rezmus** [comment]
they are recognized as ikea.light.led1537r6 as far as i remember.

**Comment by Sleinous** [comment]
@rezmus So they are using the old versions of the GU10's I guess ?
The model I have bought (and it's cheaper counterpart) are the newer versions released around a year ago and that gradually replaced 1537R6 & 1650R5

**Comment by rezmus** [comment]
they id themselves like old models (at least at mi home level) because these are only ikea GU10 models present in mijia ecosystem.

**Comment by Sleinous** [comment]
Oki understood, thanks for the info !! :)

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Sleinous** [comment]
This is now working perfectly thanks again @AlexxIT I am able to change light intensity and switch them on & off. The only thing i'm not yet able to do is change the colour, these GU10's go from a strong yellow to a pure white too. Do you know how i'd go about doing that in HA ? Currently doing this through the Xiaomi home app

**Comment by AlexxIT** [comment]
Whats your model? LED1537R6 supports temp, and LED1650R5 - not.

**Comment by AlexxIT** [comment]
![IMAGE 2020-09-22 11:00:10](https://user-images.githubusercontent.com/511909/93857152-d673f500-fcc2-11ea-8ff4-afae21ecef85.jpg)

**Comment by Sleinous** [comment]
Hi there
My bulb is listed on ikea website as : LED1737R5/LED1739R5

Yes i'm looking for exactly the same as your screenshot, colour temp.
I can do it via Xiaomi Home app at the moment with these GU10

**Comment by AlexxIT** [comment]
Please enable [debug mode](https://github.com/AlexxIT/XiaomiGateway3#debug-mode), change color temp with Mi Home and show logs.

**Comment by Sleinous** [comment]
@AlexxIT Here's the logs for those GU10 bulbs

![image](https://user-images.githubusercontent.com/33639239/93941128-0dcbbb80-fd2e-11ea-8b90-56badb7f1375.png)

**Comment by Sleinous** [comment]
ok nevermind, just had a dumb moment... they're already correctly showing as colour-temp controllable... I just didnt realise you had to click on the switch - I need to find out how to get that colour temp slider to appear directly on my dashboard

![image](https://user-images.githubusercontent.com/33639239/93941415-b5e18480-fd2e-11ea-8e9d-0cb4e01a2a9f.png)

Thanks again for implementing @AlexxIT !
This enhancement can be closed and marked as complete 👍

**Comment by jorups** [comment]
Does LED1537R6 supports transitions in scenes?
Tried transitions via scene.turn_on/scene.apply/light.turn_on, etc. but without luck. Scene works in a way that lights turn on but without transition, so state on/off changes immediately.  Seems that they are working via tradfri hub (https://community.home-assistant.io/t/tradfri-transition/17530/9)
