### ISSUE TITLE
Aqara smart plug support

### ISSUE THREAD

**Issue by igelbro** [AlexxIT/XiaomiGateway3#274]
Please,.add Aqara smart plug (lumi.plug.maeu01) support.

**Comment by AlexxIT** [comment]
Do you have it? Enable basic and mqtt logs. Toggle plug. And send logs

**Comment by igelbro** [comment]
Напишите, пожалуйста, подробнее что сделать.

**Comment by rezmus** [comment]
update plug in aqara app (using any aqara hub) to firmware 32. it won't work with mgl03 if you have older firmware.

**Comment by AlexxIT** [comment]
Если розетка вообще не подключается, нужно обновить её прошивку на любом Акара хабе. Если подключается, но не управляется из ХА, нужно собрать с неё логи.

**Comment by igelbro** [comment]
[ha.log](https://github.com/AlexxIT/XiaomiGateway3/files/6176992/ha.log)

**Comment by AlexxIT** [comment]
В последней мастер версии должна поддерживаться

**Comment by igelbro** [comment]
Да, все работает. Спасибо!
