### ISSUE TITLE
Wrong open telnet command

### ISSUE THREAD

**Issue by MayuriXx** [AlexxIT/XiaomiGateway3#276]
Hello,

When i want to add my gateway, i have always this error message : Wrong open telnet command
I added my ip address and my token.
The model is : lumi.gateway.mgl03

Do you an idea ?

**Comment by hubaksis** [comment]
Hi @MayuriXx,

What is your gateway firmware version?

**Comment by MayuriXx** [comment]
My gateway version is : 1.4.7_0160 
And my HA : 2021.3.4

**Comment by AlexxIT** [comment]
You need to follow the link in the window and read the documentation

**Comment by MayuriXx** [comment]
your link it's for all issues, it's normal ?

**Comment by AlexxIT** [comment]
Documentation has answer on your problem.

![download](https://user-images.githubusercontent.com/511909/111962045-de421400-8b02-11eb-872f-bc4d8412fa90.png)

**Comment by MayuriXx** [comment]
oh yes excuse me so !! Thank you !!
