### ISSUE TITLE
Some questions: chip temperature, device list, firmware lock, bluetooth messages

### ISSUE THREAD

**Issue by hubaksis** [AlexxIT/XiaomiGateway3#277]
Hi there,

Firstly, thank you for the amazing job you've done!

I am trying to implement the same for OpenHab. As for now this is just to support some (around 20) devices that I've got.

Almost everything is based on your code. While working on it - I noticed a couple of things that I would like to clarify if possible:
1. Chip temperature (message '8.0.2006'). 
For my door sensor (MCCGQ01LM) values are usually in the range from 70 to 80.
For my motion sensor with illuminance (RTCGQ11LM) chip temp is 30-40.
Any idea if these values mean anything or what is the scale/divider/unit of measurement?

2. Get device list from the gateway.
This can be done if you send a command 'get_device_list' (or get_device_prop) to the gateway according to [this issue](https://github.com/rytilahti/python-miio/issues/699#issuecomment-643208618). Is there any reason why you are not using it? Sorry if I missed it, I think I saw receiving device list from the server only. 
I am using this command to get all devices' models.

3. Can you explain in a nutshell how firmware lock works?
Is it just setting an attribute for the firmware files with a command over telnet
`(md5sum /data/busybox | grep 099137899ece96f311ac5ab554ea6fec) && /data/busybox chattr +i /data/firmware.bin`
`(md5sum /data/busybox | grep 099137899ece96f311ac5ab554ea6fec) && /data/busybox chattr +i /data/firmware_ota.bin`

4. My gateway firmware is 1.4.6_0043 with removed telnet password
On power on I send a command to enable telnet, then I use the following telnet commands to enable remote MQTT access:
```killall mosquitto
mosquitto -d
killall zigbee_gw
exit
```

I can see messages in `zigbee/send` topic, but nothing for bluetooth Xiaomi Mi thermometer (lywsd03mmc).
I didn't turn off the cloud connection.
Can you advise on how to enable bluetooth messages or where I can get them? 

Thank you.

**Comment by hubaksis** [comment]
After some digging I can answer to my #4 question.

The code is in gateway3.py and shell.py.
To fix BT, the shell replaces file /data/silabs_ncp_bt from http://master.dl.sourceforge.net/project/mgl03/ depending on firmware version. Check for an updated version is done by comparing md5.
Then executes 
```
killall silabs_ncp_bt; pkill -f log/ble;  
/data/silabs_ncp_bt /dev/ttyS1 1 2>&1 >/dev/null | 
mosquitto_pub -t log/ble -l &```

Is everything correct?

**Comment by AlexxIT** [comment]
1. Don't know. Don't show this data in Home Assistant
2. I get not only a list of devices, but also their sensor values.
3. Check [wiki](https://en.wikipedia.org/wiki/Chattr) - Immutable. Gateway can't download new firmware version
4. Bluetooth messages don't send to mqtt by default. Check [this](https://github.com/AlexxIT/XiaomiGateway3/blob/99e022763f7f664fe94cd6b4dfd41874159d818d/custom_components/xiaomi_gateway3/core/gateway3.py#L486-L494)

**Comment by hubaksis** [comment]
Thank you!
All clear now.

**Comment by bubez81** [comment]
hello, it's possible to reactivate Bluetooth mqtt topics?

**Comment by AlexxIT** [comment]
@bubez81 check this project https://github.com/AlexxIT/gw3

**Comment by bubez81** [comment]
yes thank you checked!!
