### ISSUE TITLE
Feature or bug ? Device renaming have no effect on entities.

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#278]
Home Assistant OS 5.12, supervisor-2021.03.6, core-2021.3.4, add-on v1.0.1 - 2021-02-26

Multiple times renamed devices.
Entities still have same name, by device Zigbee ID.

**Comment by AlexxIT** [comment]
These are Home Assistant functions, not integration

**Comment by Masterz69** [comment]
Ok, i see it.

But, this function is blocked - cause on start device name is like "Aqara bla-bla", but entities named by IEEE address. 
Thats why HA can't rename as desired.

May be to create device with name = IEEE adress, or do it configurable ?
Thank You.

**Comment by AlexxIT** [comment]
When you rename device - HA automatically change entity names but don't change entity ids.

**Comment by Masterz69** [comment]
> When you rename device - HA automatically change entity names but don't change entity ids.

Let me show examples.

F.e. device name "button", entity name "sensor.0x321" -> HA will NOT change entity id (if confirmed in dialog).
Only if device name "button" and entity name like "sensor.button_battery".

XG3 integration create device name "Aqara Button" (just example), entity id "sensor.0x3456_battery".
To bulk rename entities to smth else, need to change device name to "0x3456", only then HA will rename entities automatically together with device name and entity names (if confirmed in rename dialog, sure).

Если в названиях сущностей было старое имя устройства - тогда HA заменяет его на новое.
Если нет - как в случае создания устройств и сущностей интеграцией - надо сначала согласовать имя ус-ва с именами сущностей, переименовав в 0x145...767 (пример) и потом механизм переименования HA будет работать в полной мере.

По сути мелочь, согласен. Может стоит упомянуть где-то в документации, на всякий случай.
