### ISSUE TITLE
Installed via HACS but don't see the integration

### ISSUE THREAD

**Issue by starman2k01** [AlexxIT/XiaomiGateway3#280]
Core 2021.3.3,
I installed via HACS and only see the integration in HACS, where I can't use it or configure it. The youtube shows the install bing available inside coniguration-> integrations, but it doesn't appear. Bug?
I'm on firmware 1.4.7_0160 but I don't think this makes any difference regarding Home Assistant integration, and appearing.
So I can't get the token since your integration doesn't appear?

**Comment by AlexxIT** [comment]
Just read the Config section in the readme carefully

**Comment by starman2k01** [comment]
Hi AlexxIT,
I did read the config section. There is no integration called "Xiaomi
Gateway 3" under configuration->Integrations after I install your HACS
integration. It doesn't appear at all. Something has broken it in new
builds.
Steve

*Stephen G. Pearse*
*Managing Director*
*ph: 978-273-3200*

**Comment by starman2k01** [comment]
The problem was I restarted HASS upon HACS install, like the screen said to do. That doesn't work. You don't restart until you re-install AGAIN via regular integrations screen.

**Comment by AlexxIT** [comment]
You just need to clear your browser cache
