### ISSUE TITLE
XiaomiGateway3 3.24 After the update, zigbee motion sensor 55 minutes automatically triggered

### ISSUE THREAD

**Issue by mengyu-520** [AlexxIT/XiaomiGateway3#281]
Firmware update today, the human body motion sensors in 55 execution triggered automatically?

**Comment by AlexxIT** [comment]
Didn't understand anything

**Comment by mengyu-520** [comment]
@AlexxIT After the update, zigbee motion sensor 55 minutes automatically triggered

**Comment by craigmcgowan** [comment]
Same issue here with buttons it appears after a quick look.

Whenever a heartbeat is sent back to the gateway, home assistant is registerting it as a click. Therefore, my bedside lamps have turned on every hour for last night. Not a happy mrs this morning!!!!

**Comment by AlexxIT** [comment]
What firmware on your gw?

**Comment by craigmcgowan** [comment]
1.4.7_0115

**Comment by jasonlai79** [comment]
Same here! 1.4.7_0115 as well

**Comment by mengyu-520** [comment]
1.4.7_0160

**Comment by craigmcgowan** [comment]
Has this issue been addressed in today's new release at all please?

**Comment by mengyu-520** [comment]
我也不知道，自行测试，不敢更新了

**Comment by lacikasimon** [comment]
Same problem

**Comment by craigmcgowan** [comment]
I see there have been a few more releases in recent days and I've love to try them out but is this bug squashed yet in any release? I can't see anything in the release notes

**Comment by AlexxIT** [comment]
I think it fixed in latest versions

**Comment by craigmcgowan** [comment]
I can confirm it does indeed appear fixed in latest release. Thank you.
