### ISSUE TITLE
Platform xiaomi_gateway3 does not generate unique IDs.

### ISSUE THREAD

**Issue by guardianbs** [AlexxIT/XiaomiGateway3#283]
Since adding a second Xiaomi Gateway 3 the BLE sensors are seen by both gateways. Upon startup Home Assistant reports
for example ' ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_gateway3 does not generate unique IDs. ID a4c138f30641_ble is already used by sensor.a4c138f30641_ble - ignoring xiaomi_gateway3.a4c138f30641_ble' with similar errors for each BLE sensor.
Question: Is this a XiaomiGateway3 component problem or a Home Assistant problem ?

**Comment by AlexxIT** [comment]
Probably fixed in latest versions
