### ISSUE TITLE
[Feature request] Name new devices by IEEE address

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#284]
In same way as Zigbee2MQTT do, f.e.

Bonus: 
* it will simplify following device renaming with simultaneous entity renaming, 
* as well not create devices with same name if multiple devices joined with same type/model.

**Comment by AlexxIT** [comment]
This integration can download human-readable names from the Xiaomi cloud. There is no point in showing names IEEE address

**Comment by ha0y** [comment]
I don't think it's a good idea to name new devices by IEEE address. Also, I can barely understand why Zigbee2MQTT prefer to do so, even if the device model will be reported by device during pairing. Can you identify your devices with IEEE address if they joined the network at the same time?

**Comment by Masterz69** [comment]
> This integration can download human-readable names from the Xiaomi cloud. There is no point in showing names IEEE address
If device & entities will be named using 'friendly name' from XG3 - fine, very fine. Probably the best idea.

> Can you identify your devices with IEEE address if they joined the network at the same time?
Now they named by device model - how do I identify if join five same model devices, f.e. :)

**Comment by AlexxIT** [comment]
@Masterz69 setup cloud integration. And devices will have names from Mi Home

**Comment by ha0y** [comment]
> Now they named by device model - how do I identify if join five same model devices, f.e. :)

At least you can identify different model devices easily now. Or do you prefer something like, you join a contact sensor, a pir sensor, a smart plug, and they all show like
```
0x00158d00012ae04d 
0x00158d00012ac14d
0x00158d00011ae04d
```
in your device registry??

**Comment by Masterz69** [comment]
> identify different model devices easily now

" identify different model devices easily nоw" - HOW ? When I join 5, f.e., Aqara Wireless Button - how to identify ?


At moment I have more trouble with renaming XG3 imported entities, never with names in Z2M, Believe me.

**Comment by ha0y** [comment]
> At moment I have more trouble with renaming XG3 imported entities, never with names in Z2M, Believe me.

You have some problems in your configuration. Those imported entities was named the same as the name set in your Mi Home. You should add your xiaomi account first, then import your devices.

**Comment by Masterz69** [comment]
> @Masterz69 setup cloud integration. And devices will have names from Mi Home

On device join moment - no mine defined friendly name in MiHome, unfortunately.
Later, on name change in MiHome - HA names still the same, not follow MiHome names. Just checked.

Probably this feature not in release jet. Will entity names follow device name change ?

**Comment by ha0y** [comment]
> When I join 5, f.e., Aqara Wireless Button - how to identify ?

When joining devices in Mi Home, you will be required to name them one by one.

**Comment by Masterz69** [comment]
> > At moment I have more trouble with renaming XG3 imported entities, never with names in Z2M, Believe me.
> 
> You have some problems in your configuration. Those imported entities was named the same as the name set in your Mi Home. You should add your xiaomi account first, then import your devices.

How You set device friendly name BEFORE it joined MiHome ? On joining name is set to device type.

**Anyway issue is: entity names set with IEEE as prefix. That is blocking from use HA rename feature.**

" You have some problems in your configuration. " - what can I send to You, to figure our "some problems".
I see no way to add XG3 to HA, only logging to Cloud on first integration adding.

**Comment by ha0y** [comment]
My bad. No problems in your configuration. This is an issue related with HASS. I will open another issue, trying to clarify the reason and solution.

**Comment by ha0y** [comment]
No problems in your configuration. Now I know the reason.

Mi Home should allow you to name your device once it is added. However, when your device is added, the component got it and add it to HASS on the fly. This creates an entry in device registry. But it is too fast that it was done before you can name your devices in Mi Home, so default name is used. And since the device has been added to device registry, the name is fixed and can only be changed by user.

However, if you delete the whole integration and add back again, all names are correct, because device registry was deleted so they can have a new name.

This is an issue. Maybe a delay can be applied before adding devices to hass, so user can rename their devices in Mi Home? @AlexxIT

**Comment by Masterz69** [comment]
When join devices to XG3 by using HA pair service (switch on lovelace) - have no chance to change device name.

For educational purposes added 2 Aqara buttons by HA interface.
Now I have two buttons in XG3, both with same name "Aqara Wireless Mini Switch", but...

In HA only one appears, with name "Aqara Button"...
Have two notifications about new devices, but only one device. Because of same friendly name ?

**Comment by Masterz69** [comment]
> > Now they named by device model - how do I identify if join five same model devices, f.e. :)
> 
> At least you can identify different model devices easily now. Or do you prefer something like, you join a contact sensor, a pir sensor, a smart plug, and they all show like
> 
> ```
> 0x00158d00012ae04d 
> 0x00158d00012ac14d
> 0x00158d00011ae04d
> ```
> 
> in your device registry??

See no issue. Anyway will go to rename device & entities, so by entities list easy to identify sensor/plug/...

> When join devices to XG3 by using HA pair service (switch on lovelace) - have no chance to change device name.
> 
> For educational purposes added 2 Aqara buttons by HA interface.
> Now I have two buttons in XG3, both with same name "Aqara Wireless Mini Switch", but...
> 
> In HA only one appears, with name "Aqara Button"...
> Have two notifications about new devices, but only one device. Because of same friendly name ?


HA allow duplicate device friendly name - just checked by renaming some.

XG3 provide possibility to change friendly name on joining, but not force - same names allowed.
Joining by HA service call does not provide possibility to change MiHome device friendly name.

I see - friendly name in HA not follow friendly name in XG3 when join by HA service call.
"Aqara Wireless Mini Switch" <> "Aqara Button"
Second button not created in HA.

At moment both sends data through MQTT:
{
  "cmd": "report",
  "id": 2000007928,
  "did": "lumi.158d000672704b",
  "dev_src": "0",
  "time": 1616918673000,
  "rssi": -44,
  "params": [
    {
      "res_name": "13.1.85",
      "value": 1
    }
  ]
}

{
  "cmd": "report",
  "id": 2000007927,
  "did": "lumi.158d00066f9d44",
  "dev_src": "0",
  "time": 1616918664573,
  "rssi": -50,
  "params": [
    {
      "res_name": "13.1.85",
      "value": 1
    }
  ]
}

**Comment by Masterz69** [comment]
HA allow duplicate device friendly name - just checked by renaming some.

XG3 provide possibility to change friendly name on joining, but not force - same names allowed.
Joining by HA service call does not provide possibility to change MiHome device friendly name.

I see - friendly name in HA not follow friendly name in XG3 when join by HA service call.
"Aqara Wireless Mini Switch" <> "Aqara Button"
Second button not created in HA.

At moment both sends data through MQTT:
{
"cmd": "report",
"id": 2000007928,
"did": "lumi.158d000672704b",
"dev_src": "0",
"time": 1616918673000,
"rssi": -44,
"params": [
{
"res_name": "13.1.85",
"value": 1
}
]
}

{
"cmd": "report",
"id": 2000007927,
"did": "lumi.158d00066f9d44",
"dev_src": "0",
"time": 1616918664573,
"rssi": -50,
"params": [
{
"res_name": "13.1.85",
"value": 1
}
]
}

**Comment by Masterz69** [comment]
Deleted both buttons from XG3 interface. Added both back to XG3.

XG3: both in list, "Aqara Wireless Mini Switch" and "... Switch2".
HA: two notifications about new devices, but NO DEVICES !

IMHO it can be related to naming by device type and duplicate friendly names.
Naming by IEEE resolves ALL the conflicts, BTW.

**Comment by Masterz69** [comment]
Looks HA core restart solved some issues etc.

HA restarted, both buttons deleted from XG3, joined by HA pair switch.
XG3 names: "Aqara Wireless Mini Switch" and "... Switch2".
HA names: "Aqara Button" and same "Aqara Button". - not equal to XG3 friendly names.

Renamed device in XG3, in reasonable time (couple of minutes) see no message in debug about this actions. 
Looks like friendly name change not propagated to HA.

![image](https://user-images.githubusercontent.com/15225823/112747184-59507200-8fbc-11eb-8d9b-b779c1beacb0.png)

Entity names prefixed with IEEE, like "sensor.0x158d00066f9d44_action".

This naming not helping to identify devices if same type. 
In case of different types - devices easily identified by entities. Sensor not same as plug, f.e.

P.S. in some cases after debug activated - all *_zigbee entities related to XG4 hub become "empty". But not always.

P.S.P.S. I offered my idea. No need to argue - IMHO it is better way. If will not be used - just close issue, pls. 
I always rename device and entities. In current situation need to make more actions - rename device twice. 

Anyway Thank You very much - integration is awesome, nothing is ideal.

**Comment by AlexxIT** [comment]
@ha0y no matter when user setup Cloud integration. Before or after gateway integration. Human-readable names from the Xiaomi Cloud will be loaded right after HA restart. @Masterz69 just can't setup cloud integration correctly.

**Comment by Masterz69** [comment]
> @ha0y no matter when user setup Cloud integration. Before or after gateway integration. Human-readable names from the Xiaomi Cloud will be loaded right after HA restart. @Masterz69 just can't setup cloud integration correctly.

How may ways exists to setup cloud config ?
Installed HACS add-on, added integration, logged in cloud (using email) and later added integration for hubs:
![image](https://user-images.githubusercontent.com/15225823/112748207-f7dfd180-8fc2-11eb-90c7-c3ffb4d018ab.png)

**Comment by Masterz69** [comment]
Just added one more by Xiaomi id (region Europe) - logged successfully, in MiCloud device info only hubs:
![image](https://user-images.githubusercontent.com/15225823/112748507-acc6be00-8fc4-11eb-8ae9-7560d17327de.png)

**Comment by Masterz69** [comment]
After adding cloud config by ID - friendly named updated form cloud.

It not worked by cloud config by Email.

**Comment by Masterz69** [comment]
Integration config by email removed, only by ID left.

Is HA restart required to sync HA device names with MiCloud names ?

Renamed other devices and that button too - see no changes in HA.
Reloaded integration (cloud config), it asked to restart HA - then device names changed as per Mi Cloud.
But not all of changed! Third renamed still have same name.

**Comment by Masterz69** [comment]
! BTW one more comment about adding integration with MI ID versus email/phone.

In Telegram:

[Philip Valuysky]
Model: viomi.vacuum.v7
Rooms: Can't get from cloud
Может быть тут есть те у кого такой же пылесос и по комнатам инфа отображается?
[Денис Трачук]
Мне помогло завести заново аккаунт, но с mi id, а не телефоном/почтой, в качестве логина

^^ March 30

So, IMHO some issue when integration added by email - it does not retrieve information from cloud, despite login is ok.

**Comment by AlexxIT** [comment]
I'm always used login by email without problem. It can be temporary problem with China cloud

**Comment by AlexxIT** [comment]
Do you have other WiFi devices in euro region?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
