### ISSUE TITLE
xiaomi mi Door Sensor 2 MCCGQ02HL добавляется как sensor без получения данных

### ISSUE THREAD

**Issue by pervolianinen** [AlexxIT/XiaomiGateway3#288]
Данный датчик добавляется как сенсор. Никаких данных (открытие/закрытие, освещенность, статус батареи) - нет
Прошивки шлюза 1.4.6_012, 1.4.7_0160.
У датчика 0035 и крайняя прошивки.
В MiHome датчик есть, в шлюзе в списке устройств отображается. 
Чайник Mi Kittle показывается корректно (статус, температура).
![1](https://user-images.githubusercontent.com/74545183/112727235-95d78b80-8f32-11eb-9af2-d186208fc7c9.png)

Используется крайняя версия xiaomigateway3

**Comment by NikDevx** [comment]
@pervolianinen  привет
У меня была похожая проблема.

Решил её так https://github.com/AlexxIT/XiaomiGateway3/issues/287

**Comment by pervolianinen** [comment]
> @pervolianinen привет
> У меня была похожая проблема.
> 
> Решил её так #287

У меня устройство добавляется. Но в entity вместо 2 бинарных и 2 обычных сенсоров, только 1.

**Comment by pervolianinen** [comment]
> Данный датчик добавляется как сенсор. Никаких данных (открытие/закрытие, освещенность, статус батареи) - нет
> Прошивки шлюза 1.4.6_012, 1.4.7_0160.
> У датчика 0035 и крайняя прошивки.
> В MiHome датчик есть, в шлюзе в списке устройств отображается.
> Чайник Mi Kittle показывается корректно (статус, температура).
> ![1](https://user-images.githubusercontent.com/74545183/112727235-95d78b80-8f32-11eb-9af2-d186208fc7c9.png)
> 
> Используется крайняя версия xiaomigateway3
За 12 часов каким-то образом потянулся сенсор открытия закрытия. Теперь 2 сенсора... Может все само подтянется?

**Comment by pervolianinen** [comment]
1. Ждать не менее 12 часов. 
2. После провести по очереди все действия открыть закрыть, свет. По несколько раз. 
Далее все свойства появляются. 
Похоже это связано с серверами xiaomi. У меня датчик изначально очень плохо подключался и не обновлялся...

**Comment by AlexxIT** [comment]
В последней бета-версии должно быть лучше с BLE
