### ISSUE TITLE
XG3 and devices became "uavailable" after debug on/off

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#290]
Just switched debug off for one of XG3, and all related to it _zigbee entities have no information aymore:
![image](https://user-images.githubusercontent.com/15225823/112747337-76397500-8fbd-11eb-9e55-42cbecfe2d9e.png)

As well as all devices become "unavailable".

![image](https://user-images.githubusercontent.com/15225823/112747350-8bae9f00-8fbd-11eb-9bfb-b460472e3eec.png)

Integration reload - no changes.
HA restart resolves sutiation.

Integration version 1.1b3.

**Comment by Masterz69** [comment]
Sometime it happens on enabling debug, sometime on disabling.

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
