### ISSUE TITLE
Поддержка камер

### ISSUE THREAD

**Issue by NikDevx** [AlexxIT/XiaomiGateway3#292]
@AlexxIT, привет.
Будет ли доступна поддержка камер в этом плагине?

В данном плагине https://github.com/al-one/hass-xiaomi-miot уже реализована такая функция.
Хотелось увидеть и в вашем плагине поддержку.

**Comment by AlexxIT** [comment]
Gateway никак не связан с WiFi устройствами

**Comment by NikDevx** [comment]
А как насчёт zigbee камеры Aqara G2?

**Comment by AlexxIT** [comment]
Камеру G2H можно. С обычной G2 были какие-то сложности
