### ISSUE TITLE
[Feature request] Populate entity with other same device data as attributes 

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#293]
Let me explain.
Z2M integration populate entity with attributes containing other device sensors values:
![image](https://user-images.githubusercontent.com/15225823/112989396-8d1ec980-916d-11eb-9e1e-233fe9f6bfec.png)

XG3 integration with only particular data:
![image](https://user-images.githubusercontent.com/15225823/112989486-a58ee400-916d-11eb-87b1-092d2a51697b.png)

Probably it can be an overkill to duplicate same data across multiple entities, but sometime it can be very handful.

Thank You for attention.

P.S. Sorry, messed up integration name on writing.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
