### ISSUE TITLE
xiaomi servers

### ISSUE THREAD

**Issue by yyy333y3** [AlexxIT/XiaomiGateway3#295]
when trying to setup in HA only 5 or 6 servers available, my account is based on (Saudi Arabia 'sa') so I couldn't use my account based on my location. I could switch my account location to china but then I will receive an update on my gateway and will have more issues than solutions. 

I tried to manually change the server list on the addon and the account now connected but no device is shown.

if you could kindly add Saudi Arabia 'sa' ti the server list I will really appreciate it

**Comment by AlexxIT** [comment]
Xiaomi don't have other servers. Your country used one of them. I don't know which one exact. You can try all of them

**Comment by yyy333y3** [comment]
after changing the server to sg it worked fine thanks alot
