### ISSUE TITLE
Перестала работать Bluetooth Mesh лампа

### ISSUE THREAD

**Issue by maximminton** [AlexxIT/XiaomiGateway3#296]
Вчера после обновления перестала работать Xiaomi Bluetooth Mesh Lamp MJDP09YL. Шлюз: lumi.gateway.mgl03 ZNDMWG03LM
Прошивка: 1.4.6_0012

Xiaomi Gateway 3 integration for Home Assistant: v 1.1.1

Из приложения Mi Home лампочка продолжает управляться, управление из НА пропало, хотя сама лампа в НА отображается.

**Comment by AlexxIT** [comment]
Отображается и нажимается в ХА? Как именно происходит в ХА?

**Comment by maximminton** [comment]
Да, отображается и нажимается. Но лампа на это никак не реагирует.
![F027020D-DC45-49D3-85EE-B21E772359C7](https://user-images.githubusercontent.com/31380862/113356846-99f91400-934b-11eb-9b7b-ae15c23bb332.png)

**Comment by AlexxIT** [comment]
В логах нет ошибок? Можно попробовать классическое - перезагрузить шлюз

**Comment by maximminton** [comment]
Шлюз перезагрузил, ничего не изменилось. В логе действительно появилась новая ошибка.

![Uploading 9962D9C5-C2A5-4AAD-8D18-E4816AF0C259.png…]()

**Comment by Strish** [comment]
Та же самая проблема. Сейчас версия 1.2.1.  Проблема появилась на 1.1.0. 
При включении из карточки делает вид, что включается и через 10 секунд выключается. При этом реально лампа не включается. 
Из MiHome управляются без проблем, при этом состояние в НА отображаются правильно.
После отката на v1.0.1 работают нормально.
Прошивка шлюза 1.4.6_0012.

**Comment by andrey-del** [comment]
Присоединяюсь, та же проблема на версии v1.2.1 шлюз fw 1.4.6_0012 лампы YLTS02YL, YLDP09YL, YLDP10YL

**Comment by andrey-del** [comment]
> Присоединяюсь, та же проблема на версии v1.2.1 шлюз fw 1.4.6_0012 лампы YLTS02YL, YLDP09YL, YLDP10YL

прошился на  v1.4.7_0160 - проблема осталась

**Comment by mabilko** [comment]
Проблема с MJTS01YL (Xiaomi Mesh Downlight). Прошивка шлюза 1.4.6_0012. Не обновляется в НА статус офлайн. Добавлял сами лампы, и группу ламп созданную в miHome. Если лампы отключить от питания, НА упорно показывает что лампы онлайн, хотя уже сутки как отключил от питания их. Игры с настройками и перезагрузками не помогают.

**Comment by AlexxIT** [comment]
@maximminton необходимо убедиться, что токен верный. Если верный - перезагрузить шлюз и ХА. И проверить работу снова.

**Comment by AlexxIT** [comment]
@mabilko шлюз говорит, что лампы всё ещё оналайн. Известная проблема.
Компонент не использует данные облака в отличии от МиХом и полностью полагается на информацию от шлюза.

**Comment by Strish** [comment]
Уточню еще: сейчас обновил ХА и после перезагрузки 2 лампы из 3 стали недоступными в ХА (из MiHome управляются нормально).
Из ошибок только эти:
![Xiaomi Gateway 3](https://user-images.githubusercontent.com/66323366/115296777-0fdee700-a164-11eb-92ba-893a48175688.jpg)
![xiaomi_gateway3](https://user-images.githubusercontent.com/66323366/115296796-166d5e80-a164-11eb-9a81-bb7b76b6c311.jpg)
![xiaomi_gateway3_1](https://user-images.githubusercontent.com/66323366/115296805-1a00e580-a164-11eb-84e5-eef4a911cda8.jpg)

**Comment by andrey-del** [comment]
Заметил что токены различаются в облаке и через прямую интеграцию, это может быть из-за этого не работать? хотя остальное функционирует
![token_cloud](https://user-images.githubusercontent.com/78949039/115602940-9b857e80-a2f0-11eb-8a1c-4c0790991959.JPG)
![token_z](https://user-images.githubusercontent.com/78949039/115602954-a04a3280-a2f0-11eb-9a82-0d9bd0437206.JPG)

**Comment by AlexxIT** [comment]
@andrey-del конечно именно из-за этого и не работает

**Comment by maximminton** [comment]
Ура!!! Заработало. Действительно был неверный токен для шлюза, хотя все остальное кроме лампы работало....
Спасибо @andrey-del  @AlexxIT за помощь.

**Comment by Strish** [comment]
И у меня заработало! Тоже был неверный токен на одном из трех шлюзов. Лампы заработали, ошибки исчезли.
Спасибо @andrey-del @AlexxIT.
