### ISSUE TITLE
RTCGQ11LM integrated with zigbee2mqtt - Battery stuck at 100%

### ISSUE THREAD

**Issue by akunia** [AlexxIT/XiaomiGateway3#298]
As per title, the battery on my 3 motion sensors RTCGQ11LM shows 100% ( OK for WSDCGQ11LM )
It worked correctly with standard integration.
FIRMWARE........: 1.4.6_0012 #20210309
Integration v1.2.0

**Comment by Antoni-Czaplicki** [comment]
Not on your problem, but can you use zigbee2mqtt with Xiaomi Home?

**Comment by AlexxIT** [comment]
Ask questions about z2m and ZHA integration in their projects. Gateway don't control zigbee devices from that time

https://github.com/Koenkk/zigbee-herdsman/pull/317

**Comment by akunia** [comment]
@Antoni-Czaplicki 
Po przejsciu na zigbee2mqtt urzadzenia zigbee sa offline w Xiaomi Home i nie da sie dodac nowych

**Comment by colethegamer123** [comment]
To be honest, I have the same problem on all my 20 device. 

Battery status is working with another Coordinator or with simple Xiaomi Gateway integration, but with Zigbee2MQTT with Xiaomi Gateway all Battery status are stucked at 100%.

**Comment by AlexxIT** [comment]
@colethegamer123 with z2m and another coordinator you don't have problems with battery of same sensors?

**Comment by colethegamer123** [comment]
Yes it was working before. Both with Xiaomi gateway integration and with Zigbee2MQTT but with another coordinator. All my battery percentages are unrealistic now. Stucked on 100% or not even showing. We will see if others have this problem too. Thank you
