### ISSUE TITLE
Mi motion Sensor stay on

### ISSUE THREAD

**Issue by Czapla-dev** [AlexxIT/XiaomiGateway3#3]
Xiaomi mi motion sensor stay on state: detected (on).

**Comment by konstcranky** [comment]
+1

**Comment by AlexxIT** [comment]
I know. Will fix it.

**Comment by viiy** [comment]
https://github.com/wernerhp/appdaemon_aqara_motion_sensors

**Comment by AlexxIT** [comment]
Fixed in latest release
