### ISSUE TITLE
Please support the Xiaomi Mesh LED Downlight (MJTS01YL)

### ISSUE THREAD

**Issue by sbyinin** [AlexxIT/XiaomiGateway3#30]
Please support the Xiaomi Mesh LED Light Downlight (MJTS01YL). These downlight are dimmable and colour temperature adjustable. Let me know if need any information from me to debug.

**Comment by AlexxIT** [comment]
Bluetooth Mesh in development. Need time

**Comment by Zuz666** [comment]
Hi, AlexxIT!
Thanks for interesting project. I can help with testing, debugging, and development.
I have new spots YLTS02YL and downlights YLTS04YL: https://sprut.ai/client/news/2623
And some new ble mesh bulbs YLDP26YL and old YLDP10YL.

**Comment by AlexxIT** [comment]
@Zuz666 I have two different mesh bulbs. They are enough for development, but it takes time

**Comment by Zuz666** [comment]
@AlexxIT, thanx!
Will BLE mesh groups also work?
What about MiHome / Yeelight cloud groups?
As I understand it there are different types of light groups and they all work differently in different app/ecosystems.

**Comment by AlexxIT** [comment]
Mesh groups also work. And I don't know what is "clous groups".

**Comment by Zuz666** [comment]
> Mesh groups also work. And I don't know what is "clous groups".
Thanks, I mean not "clous groups" -> "clouD groups".
You can create different types of light groups by MiHome / Yeelight apps (depends on the device type and model bulbs).
Some of them true BLE mesh groups (in this case app scripts run locally), some work only through one of ecosystem servers (in this case app scripts run in cloud, I call them cloud groups).
For example for YLDP26YL/ YLDP25YL model bulbs  you can't create a mesh group from MiHome / Yeelight app (may be not yet). But if you have old YLDP10YL bulbs you can add YLDP26YL/ YLDP25YL  to mesh group from MiHome app (from special YLDP10YL bulbs menu) but not from Yeelight app.
Cloud groups created by MiHome app not visible in Yeelight app but detected in Yandex Home. There is a special group "Light Group (MU & Yeelight)" visible in both ecosystem servers but it can't work with BLE bulbs.
This is so confusing, I plan to make a table to sort out the nuances myself.

**Comment by Zuz666** [comment]
> I really need this MESH support, I look forward to it
> I have a few YEELIGHT M2 (YLDP26YL)

It works now!

**Comment by Zuz666** [comment]
@AlexxIT can you add mesh bulbs description:
```diff
index 58a0a41..3365568 100644
--- a/custom_components/xiaomi_gateway3/bluetooth.py
+++ b/custom_components/xiaomi_gateway3/bluetooth.py
@@ -15,6 +15,8 @@ DEVICES = {
     1983: ["Yeelight", "Button S1", "YLAI003"],
     2443: ["Xiaomi", "Door Sensor 2", "MCCGQ02HL"],
     # Mesh
+    996: ["Yeelight", "Mesh E27 bulb", "YLDP10YL"],
+    2076: ["Yeelight", "Mesh Downlight/ Spotlight M2", "YLTS02YL/YLTS04YL"],
     1771: ["Xiaomi", "Mesh Bulb", "MJDP09YL"],
     1772: ["Xiaomi", "Mesh Downlight", "MJTS01YL"],
     2342: ["Yeelight", "Mesh Bulb M2", "YLDP25YL/YLDP26YL"],
```
This is to simple fix to make it as pull request.

**Comment by Nory-01** [comment]
Dear, 
Firstly, great integration nice work... 

I come to you, because, I have problem with Yeelight Mesh Downlight M2 (YLTS02YL/YLTS04YL), it's most of time unavailable on HA, but, when I active it by Mi Home App, it becomes available on HA, but not controllable... Have you see the same problem?

**Comment by AlexxIT** [comment]
Maybe your token wrong

**Comment by Nory-01** [comment]
Where I put token for this bluetooth light?

**Comment by AlexxIT** [comment]
Token changes each time a hub is added to the MiHome app.

**Comment by AlexxIT** [comment]
Topic added in latest release
