### ISSUE TITLE
BLE communication

### ISSUE THREAD

**Issue by skaken** [AlexxIT/XiaomiGateway3#300]
First of all, thank you very much for all your work, AlexxIT!
I’ve been dabbling around with FW and SW here and I have a couple of questions that I couldn’t find answers for:
I am trying to get notifications from a N100 lock, and for now I am only using the BLE part of Gateway 3, and I’m struggling a bit. Started of with v1.4.7_043(factory default) which gave me all kinds of problems.
 I therefore installed the custom FW 1.4.6_0012 and reinstalled everything in HA, getting a new token etc.
I saw this under known problems afterwards :
“Gateway on firmware v1.4.6_0012 won't setup without connection to Xiaomi Cloud”

Does this mean that the BLE functionality won’t work without the cloud or is it only during setup?
I probably should mention that I am blocking WAN on the gateway and I’m getting a (maybe related error) in HA log:
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues) 
First occurred: 4:03:44 PM (2 occurrences) 
Last logged: 4:34:14 PM

192.168.1.228 | Device offline

**Comment by AlexxIT** [comment]
> Does this mean that the BLE functionality won’t work without the cloud or is it only during setup?

In usual case yes. But I fix this in 0012 and 0160 firmwares.

**Comment by skaken** [comment]
Great! Thank you very much. Would it be possible to make a “Local control” option that skips the WAN connection without breaking the functionality? Might be a pull request? (I have a “trust issue” with Xiaomi after poking around in the FW of one of their lamps. They removed “LAN control” support rather suddenly without notifying their customers)

**Comment by AlexxIT** [comment]
The BLE device database is loaded from the cloud. If the gate does not see a device for a long time, it can delete it from the database
