### ISSUE TITLE
Can't add gate way

### ISSUE THREAD

**Issue by zisemixer** [AlexxIT/XiaomiGateway3#302]
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 10:54:41 PM (3 occurrences)
Last logged: 11:07:53 PM

192.168.3.144 | Device offline

Hello, AlexxIT.

My gateway 3 was in firmware 1.4.7. I have followed the procedure and solder it to 1.4.6_0012.
I can get the IP and token of the gateway3.However, by adding it per instruction, I always get error above.
My gateway 3 is definitely open and connecting to the internet.
I have also tried reboot HA and clear browser caches.
I have also tried for both raspberry pi 3 and Synology.

![无标题](https://user-images.githubusercontent.com/20958495/113482699-68f71b80-94d2-11eb-8681-d6e6d4df2a91.png)

Please help.
Thank you.
Regards,
Shawn

**Comment by AlexxIT** [comment]
Have you tried reboot the gate? Are you sure the IP address is correct?

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
