### ISSUE TITLE
Xiaomi motion sensor RTCGQ11LM - light sensor doesn't work in XiaomiGateway3

### ISSUE THREAD

**Issue by vdbosch** [AlexxIT/XiaomiGateway3#305]
Hi,
The light / lumensensor is not working in this Gateway.

When I test it with the cc2531 with Zigbee Home in Home Assistant, the lumensensor is active.
But I prefer your solution (than I also have Cloud).

Thanks for all the good work.

Regards,

Rob

**Comment by gromilQaaaa** [comment]
+1

**Comment by AlexxIT** [comment]
I have a lot of these sensors, everything works fine. What fw do you use?

**Comment by vdbosch** [comment]
Hi,

 

I have the Xiaomi Multi-Mode BT Wifi Zigbee Dispositivo Gateway Smart Home ZNDMWG03LM 

Firmware: v1.4.7_0160 

 

Regards,

 

Rob

**Comment by AlexxIT** [comment]
How it shows in device screen? With all device entities

**Comment by vdbosch** [comment]
4 entities are show, but Aqara Motion Sensor illuminance remain always 0 lx

Not in Zigbee Home Automation (there it works), so the sensor seems to work OK.

**Comment by vdbosch** [comment]
I tried now with much more light and now it seems working!

Seems it was a problem with the light or so, but still I don’t understand why I didn’t see this with Zigbee Home automation add-on.

 

Sorry to disturb you for this.

 

BTW, I am very happy with your Sonoff and Xaomi add-on!

Great work.

 

 



 

From: ***@***.*** ***@***.***> 
Sent: vrijdag 9 april 2021 21:56
To: 'AlexxIT/XiaomiGateway3' ***@***.***>
Subject: RE: [AlexxIT/XiaomiGateway3] Xiaomi motion sensor RTCGQ11LM - light sensor doesn't work in XiaomiGateway3 (#305)

 

4 entities are show, but Aqara Motion Sensor illuminance remain always 0 lx

Not in Zigbee Home Automation (there it works), so the sensor seems to work OK.
