### ISSUE TITLE
Шлюз перестал видеть и добавлять датчики

### ISSUE THREAD

**Issue by maxikoz** [AlexxIT/XiaomiGateway3#309]
После добавления в HA через плагин внезапно отпали все датчики - Temperature/Humidity и датчик движения.
После этого добавить датчики не получается, через Mi Home датчики не отображаются, сбрасывал настройки шлюза, пробывал смену региона, и спец версию под Андроид.

Возможно что у шлюза вышла из строя система отвечающая за Zigbee ?

**Comment by pervolianinen** [comment]
Перепрошейте. Бывает.... + удалите и создайте заного компоненты в HA, сегодня так развлекался после слета базы...

**Comment by AlexxIT** [comment]
Нужны подробности, что за прошивка, оригинал/нет. Верный ли токен. Можно включить логи в настройках интеграции и посмотреть, что там.

**Comment by maxikoz** [comment]
как включить логи ?

**Comment by pervolianinen** [comment]
> Нужны подробности, что за прошивка, оригинал/нет. Верный ли токен. Можно включить логи в настройках интеграции и посмотреть, что там.

Что странно это происходило на 3 прошивках. 0012, 0115 и 0160. Причем все прошивки были патченные. 
1. в двух случаях это происходило после появления сообщения в mihome о существовании новой версии прошивки (обновление не осуществлялось), и 3 раз произвольно. 
2. Во всех случаях отлично лечилось пере прошивкой по воздуху/uart. При этом в 2 случаях отваливались zigbee xiaomi (сторонние tuya нормально подключались) и их приходилось переподключать.
3. 2 раза отваливался bluetooth тоже перепрошивка и все начинала работать.
4. 1 раз пришлось удалять шлюз и переподключать заного Что интересно токен 3 суток не обновлялся в компоненте, вытаскивал через мобильное приложение. Также 3-е суток не подгружались данные bluetooth.

**Comment by AlexxIT** [comment]
Проблема всё ещё актуальна?
