### ISSUE TITLE
Xiaomi Mijia ZNKG03HL support

### ISSUE THREAD

**Issue by geradtl** [AlexxIT/XiaomiGateway3#312]
Alex, просьба добавить поддержку Mesh выключателя Xiaomi Mijia ZNKG03HL 
https://www.mijia-shop.ru/product/xiaomi-mijia-screen-display-switch-e-billing-control/

Сейчас корректно работает получение состояния и управление клавишами. 
Есть проблема в получении значений температуры и влажности: 
1. Обновление значений происходит каждые 30 секунд и в этом интервале значение меняется с неопределённого на фактическое (рандомно - то 90% времени показывает «неизвестно» а 10% значение, то наоборот). 
2. Точность значений температура и влажности сократить до 1 знака после запятой.
![znkg03hl_1](https://user-images.githubusercontent.com/66991361/115088684-673d4700-9f19-11eb-97c5-62deb8e06cd4.png)
![znkg03hl_2](https://user-images.githubusercontent.com/66991361/115088695-6b696480-9f19-11eb-8261-b24a1bcae718.png)
[znkg03hl.log](https://github.com/AlexxIT/XiaomiGateway3/files/6328062/znkg03hl.log)

Log файл прилагается.

**Comment by geradtl** [comment]
Поддержка выключателя ZNKG03HL уже есть в интеграции, он называется ISA-KG03HL. 
Первая часть описанной проблемы возникает из-за совместной работы двух шлюзов Xiaomi GW3. Один из них имеет прошивку 1.4.6_0012, а другой v1.4.7_0160. Прошивка v1.4.7_0012 неверно отдает значения температуры и влажности (-4004). Но так как интеграция берет данные с обоих шлюзов для одного и того же устройства, в HA значения все время меняются с реального на «неопределенное». Проблема решилась созданием разных учетных записей Mi Home для шлюзов и переносом BLE устройств только на один из них.
Точность значений температура и влажности устройство возвращается со странной точностью, последняя версия прошивки устройства этого не решает.

**Comment by Twin4eg** [comment]
Добрый день у меня выключатель определяется как ZNKG03HL/ISA-KG03HL шлюз lumi.gateway.mgl03 ZNDMWG03LM
Xiaomi Версия программного обеспечения: 1.5.1_0032 выключатель не работает в HA. При перезапуске HA выключатель не видно. если в mi home отправить команду он становится активным видит показания датчиков и состояние выключателей. управлять из HA выключателем не получается, не реагирует.

**Comment by AlexxIT** [comment]
@Twin4eg неправильный токен шлюза или неправильные сетевые настройки. Вам нужно добиться отсутствия ошибки "Device offline"

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
