### ISSUE TITLE
No devices added

### ISSUE THREAD

**Issue by maoravi456** [AlexxIT/XiaomiGateway3#313]
when I follow the instruction, step by step, and even watched the youtube videos(https://www.youtube.com/watch?v=rU_ATCVKx78 , https://www.youtube.com/watch?v=FVWfjE5tx2g ) - my devices stays at 1 device(Mi Smart Home Hub)

tried both Telnet commands

what am I doing wrong?
![image](https://user-images.githubusercontent.com/73000052/115123681-d755d680-9fc6-11eb-8003-454b164d7862.png)
![image](https://user-images.githubusercontent.com/73000052/115123694-e2106b80-9fc6-11eb-95fa-6b3f6d04cf3a.png)

**Comment by AlexxIT** [comment]
One device is a gate. What else do you want to see there?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
