### ISSUE TITLE
Door lock event missing

### ISSUE THREAD

**Issue by chenquanhao** [AlexxIT/XiaomiGateway3#314]
I use 鹿客 Loock classic 2x and successfully access homeassistant through Xiaomi gateway 3. But there is a problem. I use other methods to get the event of door lock. It is the event with the edata attribute 3 of eid = 0x0007, which corresponds to the event that the door is not completely closed.

In the "sensor.fc1a59xxxxxx_action", I can get events with edata attributes of 1、2 and 5 with 'action': 'door'（eid ==0x0007）, but no events with 3. I hope the new version can solve this problem. thanks

**Comment by chenquanhao** [comment]
I just didn't make it clear. I got the data eid:7 as well as edata:607c577ef3. As I understand it, it means eid:7 '=' action:door '，' edata:607c577ef3 '='action_ id:3'。 But when I get the above data in other ways，“sensor.fc1a59xxxxxx_action"  didn't show this information.

**Comment by AlexxIT** [comment]
Show the logs, everything you write is unclear.
