### ISSUE TITLE
Device stop working 

### ISSUE THREAD

**Issue by andiukas** [AlexxIT/XiaomiGateway3#315]
work 1 minute, then stop, after 5 minute start

![Screenshot_2021-04-20-22-56-45-937_io homeassistant companion android](https://user-images.githubusercontent.com/44068098/115456548-f3a67d00-a22b-11eb-9f82-4554b5d83794.jpg)

**Comment by andiukas** [comment]
![Screenshot_2021-04-20-23-05-41-081_io homeassistant companion android](https://user-images.githubusercontent.com/44068098/115457308-03729100-a22d-11eb-92f3-d29cf0e1f4af.jpg)

**Comment by AlexxIT** [comment]
This issue depends on EZSP driver of zigbee2mqtt project. You can try to find answer there
