### ISSUE TITLE
在多个XiaomiGateWay3网关环境时所有的设备都在相同网关中添加了。

### ISSUE THREAD

**Issue by hbwy1314** [AlexxIT/XiaomiGateway3#316]
在使用的时候会导致控制变得非常慢。
![1](https://user-images.githubusercontent.com/24299857/115954348-146c1c80-a523-11eb-8ad1-724f2827d9bf.jpg)
![2](https://user-images.githubusercontent.com/24299857/115954351-1635e000-a523-11eb-9903-5701225ba6cd.jpg)
![3](https://user-images.githubusercontent.com/24299857/115954352-16ce7680-a523-11eb-9644-247f3d68079a.jpg)

**Comment by saury** [comment]
每个网关注册个账号分开添加试试

**Comment by AlexxIT** [comment]
Each gate can see all BLE devices

**Comment by hbwy1314** [comment]
> Each gate can see all BLE devices

Which gateway is in the process of control or all gateways

**Comment by hbwy1314** [comment]
> Each gate can see all BLE devices

Which gateway is in the process of control or all gateways

**Comment by hbwy1314** [comment]
> 每个网关注册个账号分开添加试试

那米家的控制不是废了

**Comment by AlexxIT** [comment]
At the moment, only one gateway will control the Mesh devices (chosen at random). But data from sensors is received by all gateways simultaneously.
