### ISSUE TITLE
Zigbee2mqtt devices do not respond after several hours

### ISSUE THREAD

**Issue by froggyfly** [AlexxIT/XiaomiGateway3#319]
Hi, I'm trying to zigbee2mqtt mode because of ZHA can not work on one of my new light,
Changed to ZigBee 2mqtt mode success (the xiaomigateway3 integration said),  and the entity in Zha can't operate any more, Ble works well.
I set up the ZigBee2mqtt in supervisor, add: 
**serial:
  port: 'tcp://192.168.50.38:8888'
  adapter: ezsp**

The the zigbee2mqtt logs said:

[16:05:28] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-04-29 16:05:52: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-29 16:05:52: Failed to start zigbee
Zigbee2MQTT:error 2021-04-29 16:05:52: Exiting...
Zigbee2MQTT:error 2021-04-29 16:05:52: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-29T16_05_52_309Z-debug.log

502: Bad Gateway on the web ui,
any idea？

**Comment by AlexxIT** [comment]
Maybe some problem with local network. Try to reboot gate

**Comment by froggyfly** [comment]
> Maybe some problem with local network. Try to reboot gate
Thanks Alex,
Running on zigbee2mqtt mode success after reboot everything.

I have the devices linked to zigbee2mqtt by gateway3 now. All of them will have a chance that  will no response for several seconds. Looks like it always happened after a long time no actions.

**Comment by makabar** [comment]
btw... a built in zigbee2mqtt would be great

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
