### ISSUE TITLE
support Yeelight YLKG08YL dimmer

### ISSUE THREAD

**Issue by JD99** [AlexxIT/XiaomiGateway3#32]
было бы круто добавить поддержку этого диммера. но он вроде не подключается к хабу через приложение.

**Comment by JD99** [comment]
вижу вы уже отписались в репо по этому диммеру
https://github.com/nccchirag/yeelight-ble-rotary-dimmer/issues/1

**Comment by AlexxIT** [comment]
А его видят BLE хабы? Я думал он напрямую к лампам цепляется и по-другому работать не умеет.

**Comment by JD99** [comment]
у меня есть только сам диммер. когда покупал недоглядел, что он только к лампам. теперь думаю что с ним делать. так что про ble хабы ничего сказать не могу.

**Comment by viiy** [comment]
Хабы их не видят, так же хабы не видят пульты yeelight.
В mihome они отображаются внутри лампы в "Пульт ДУ и переключатель режимов"
