### ISSUE TITLE
Incorrect firmware size

### ISSUE THREAD

**Issue by kingwap99** [AlexxIT/XiaomiGateway3#320]
While update firmware, I got this error message as below.
May I know, How to fix it?
-------------------------------------
# export PATH="$PATH:/tmp"
# curl -s -k -L -o /tmp/update.sh https://raw.githubusercontent.com/zvldz/mgl03_fw/main/firmware/mgl03_update.sh && sh /
tmp/update.sh
* Getting firmware list

For recommended firmware, see https://github.com/AlexxIT/XiaomiGateway3/wiki
Available firmware:
[1] mgl03_1.4.6_0012_mod20210309.zip
[2] mgl03_1.4.7_0115_mod20210309.zip
[3] mgl03_1.4.7_0160_mod20210309.zip
Please choose firmware: 1
* Downloading ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.0M  100 13.0M    0     0   137k      0  0:01:37  0:01:37 --:--:--  933k

* Content-Length: 13732140
* Firmware size: 8724158
! Incorrect firmware size

* Cleaning temporary files

**Comment by zvldz** [comment]
You probably don't have enough space in / data.
You need to clean up any trash there.
You can enable ftp on the gateway for convenience.

**Comment by kingwap99** [comment]
> You probably don't have enough space in / data.
> You need to clean up any trash there.
> You can enable ftp on the gateway for convenience.

thanks , you are correct. the free disk space is only 5.8m, 
it seem I have to clean some files manually.

# df -k
Filesystem           1024-blocks    Used Available Use% Mounted on
/dev/root                11136     11136         0 100% /
ubi0_0                   46904     38660      5816  87% /data
/data/miio               46904     38660      5816  87% /data/miio

# ls -l data
drwxrwxrwx    2 app      0              232 Apr 30 00:03 basic_app
drwxrwxr-x    2 admin    0              240 Apr 29 22:51 basic_gw
-rwxr-x---    1 admin    0               73 Jan  1  1970 ble_info
-rwxr-xr-x    1 admin    0          1576152 Apr 29 03:06 busybox
drwxr-xr-x    2 admin    0              520 Apr 29 22:51 conf
drwxr-xr-x    2 admin    0              320 Jan  1  1970 factory
drwxr-xr-x    2 admin    0              384 Apr 28 19:48 firmware
-rw-r--r--    1 admin    0         13083422 Apr 29 23:46 firmware.bin
drwxr-xr-x    2 admin    0              224 Jan  1  1970 hw_setting
-rw-r--r--    1 admin    0          2157588 Apr 29 23:46 linux.bin
drwxr-xr-x    2 admin    0              968 Apr 30 05:19 miio
-rw-r--r--    1 admin    0            12288 Apr 29 22:04 miioconfig.db
drwx------    2 admin    0              232 Mar 31 00:04 mijia_automation
-rw-r--r--    1 admin    0                0 Jan  1  1970 mount_ok
-rw-r-----    1 admin    0               90 Jan  1  1970 passwd
-rw-r-----    1 admin    0               90 Jan  1  1970 passwd-
-rw-r--r--    1 admin    0         10350612 Apr 29 23:46 root.bin
-rw-r-----    1 admin    0               68 Jan  1  1970 shadow
-rw-r-----    1 admin    0               68 Jan  1  1970 shadow-
-rwxr-xr-x    1 admin    0           946604 Apr 29 22:17 silabs_ncp_bt
drwxr-xr-x    3 admin    0              448 Feb 16 02:10 silicon_zigbee_host
-rwxr-xr-x    1 admin    0           422976 Apr 28 19:49 socat
drwxr-xr-x    2 admin    0              624 Apr 28 22:14 zigbee
drwxr-xr-x    2 admin    0              312 Jan  1  1970 zigbee_gw
drwxr-xr-x    2 admin    0              232 Apr 29 22:51 zoneinfo

**Comment by zvldz** [comment]
You can delete files:
root.bin
linux.bin
firmware.bin

**Comment by kingwap99** [comment]
> You can delete files:
> root.bin
> linux.bin
> firmware.bin

thanks, and the same file name in sub directory "firmware"  also.
each time , after I failed to upgrade firmware from mi home app, all those files came back again.

and actually, My issue is ..... I am not able to switch to "mi home" or "zigbee2mqtt" mode, only "zha" is allowed,  the error message was "unknown error".

unfortunately, none of my zigbee devices is allowed to be added into zha mode 
so for me, only blueteeth function is fine

**Comment by AlexxIT** [comment]
This discussion is not about a component
