### ISSUE TITLE
zigbee2mqtt mode, long lag 

### ISSUE THREAD

**Issue by froggyfly** [AlexxIT/XiaomiGateway3#321]
Hi, 

Got some trouble after I switch to ZigBee 2mqtt mode

Quickly operate an entity in homeassistant,
For example, fast adjust the brightness of a lamp repeatedly, Entity will not respond after a while. 
Generally, this error will be repeated 15~20 actions. After a while, usually dozens of seconds, entity will resume. 
All entities did not respond in the homeassistant/zigbee2mqtt at this time, Listen to this topic, no mqtt event can be received.
But actions which from the physical buttons can be received by ZigBee2mqtt hassio/ homeassistant.
No error in the logs of zigbee2mqq hassio. 
All the switch/light's  LQI are more than 100, and they work good in ZHA mode.
I'm not sure if this is a gateway problem or a zigbee2mqtt problem?

Sometimes, the actions in Homeassistant by automotions will be delayed irregularly, and the operations will be executed after a period of time,
But this test can quickly reproduce this delay error.

**Comment by AlexxIT** [comment]
Maybe you have problems with WiFi?

**Comment by froggyfly** [comment]
> Maybe you have problems with WiFi?

looks not by WIFI

The zigbee2mqtt hassio can't control the lights after about one or two days, no issue log in zigbee2mqtt, dashboard is running but no response with the switchs.
Restart the zigbee2mqtt hassio can recover it.

**Comment by froggyfly** [comment]
I tried a zigbee2mqtt gateway with cc2652, 
The above delay problem has never occurred again, maybe somewhere has a problem on the zigbee2mqtt mode.

**Comment by mycanaletto** [comment]
+1
Same problem after 24/48 h

**Comment by froggyfly** [comment]
> Hello, a have exactly same as Ypu froggyfly.
> How much devices do you have?

I only paired 4 devices on it as a test.

**Comment by AlexxIT** [comment]
Duplicate #319
