### ISSUE TITLE
Force update sensor BLE temperature

### ISSUE THREAD

**Issue by wild-run** [AlexxIT/XiaomiGateway3#322]
any way to update bluethon temperature sensors more quickly?

**Comment by AlexxIT** [comment]
What firmware does your gate have?

**Comment by wild-run** [comment]
mode LYWSD03MMC firmware 0001

**Comment by AlexxIT** [comment]
This sensor updates not more than once per 10 minutes on default firmware. But gateway doesn't support this sensor on custom firmware

**Comment by wild-run** [comment]
can only add bluetooth devices through xioaomi app?

**Comment by AlexxIT** [comment]
At this moment yes

**Comment by wild-run** [comment]
ok, thanks it would be great to be able to add them from home assistant
