### ISSUE TITLE
has been supported firmware 1.5.0_0026

### ISSUE THREAD

**Issue by hbwy1314** [AlexxIT/XiaomiGateway3#325]
has been supported firmware 1.5.0_0026

**Comment by zvldz** [comment]
Is it update or the gw came with this fw?

**Comment by rezmus** [comment]
where did you get this firmware? update or hub from new batch?

**Comment by hbwy1314** [comment]
> Is it update or the gw came with this fw?

Comes with the new product. For the time being, ota upgrade hardware has not been found to be ZNDMWG03LM

**Comment by hbwy1314** [comment]
@rezmus The production date is 2021.04 and the command can directly start telnet

**Comment by rezmus** [comment]
@hbwy1314 if you have telnet access can you dump 1.5.0_0026 firmware? telnet to hub and send

```
dd if=/dev/mtd5 of=/data/mtd5.bin
dd if=/dev/mtd6 of=/data/mtd6.bin
wget -O /data/busybox "http://master.dl.sourceforge.net/project/mgl03/bin/busybox?viasf=1"
chmod +x /data/busybox
/data/busybox tcpsvd -vE 0.0.0.0 21 /data/busybox ftpd -w / &
```

then use any ftp client (user admin, pass empty), download both files (mtd5.bin & mtd6.bin) from /data/ and share somewhere.

**Comment by hbwy1314** [comment]
@rezmus I have dumped the file system. I can send you an email

**Comment by zvldz** [comment]
You can upload for example here https://www.sendspace.com/

**Comment by AlexxIT** [comment]
Or send it to my email sonofflan@gmail.com

**Comment by AlexxIT** [comment]
Thanks! Can you also show results for:

```
# cat /data/zigbee/coordinator.info
# cat /data/ble_info
# cat /etc/ble_info
```

**Comment by hbwy1314** [comment]
发自我的iPhone


------------------ Original ------------------
From: Alex X ***@***.***&gt;
Date: Wed,May 12,2021 7:53 PM
To: AlexxIT/XiaomiGateway3 ***@***.***&gt;
Cc: hbwy1314 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [AlexxIT/XiaomiGateway3] has been supported firmware 1.5.0_0026 (#325)






Thanks! Can you also show results for:
# cat /data/zigbee/coordinator.info# cat /data/ble_info# cat /etc/ble_info

**Comment by hbwy1314** [comment]
@AlexxIT 

{"sdkVer":"1.3.33","manufacturer":"silicon labs","hostVer":"1.14","hostDir":"","mac":"0xcc86ecfffe7b8eed","channel":20,"panId":"0x6f23","cloudLink":1,"timeZone":"GMT8","coorVer":"6.6.2-126.32","preLeave":0,"debugStatus":0,"gw_did":""}ncp_host_version=152
ncp_target_version=107
bootloader_version=100
ota=0
ncp_host_version=100
ncp_target_version=107
bootloader_version=100
ota=0

**Comment by matteos1** [comment]
with new update work ble? thank you

**Comment by AlexxIT** [comment]
@matteos1 yes

**Comment by shummo** [comment]
Is it recommended to upgrade my 1.4.6_0012 fw to this (1.5.0_0026)??? Are there any improvement/ new features?

**Comment by AlexxIT** [comment]
Upgrading only makes sense if you have new devices that are not supported in 0012
