### ISSUE TITLE
Cloud setup not working

### ISSUE THREAD

**Issue by ivantomicic-crowdhouse** [AlexxIT/XiaomiGateway3#326]
Hey, so I've installed integration and logged into cloud ( I can see gateway and get token ). However after I do that, I still see configure button instead of Rename / Option as shown in video.

Also when I try to add gateway itself, I get "Wrong open telnet command" error...

**Comment by ivantomicic-crowdhouse** [comment]
I was supposed to use soft_hack https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709

**Comment by zvldz** [comment]
try master version of component
