### ISSUE TITLE
Неверно отображается токен

### ISSUE THREAD

**Issue by pervolianinen** [AlexxIT/XiaomiGateway3#327]
1. Не верно отображается токен шлюза из компонента.
2. При получении токена другими способами шлюз корректно подключается.
3. Компоненты НА переставлялись.
4. Шлюз сбрасывался так как перестал взаимодействовать с bluetooth датчиком двери.

**Comment by AlexxIT** [comment]
Токен неверно отображается из-за пункта 4. Обновление всех токенов происходит только при старте ХА. И только если подключение к серверам будет успешным. Иначе будут взяты данные из кеша

**Comment by pervolianinen** [comment]
> Токен неверно отображается из-за пункта 4. Обновление всех токенов происходит только при старте ХА. И только если подключение к серверам будет успешным. Иначе будут взяты данные из кеша

Подключение было успешным перечень устройств поменялся в соответствии с mihomr, ha был перегружен. 
Через более чем 2 часа токен поменялся. В независимости от перегрузок и т.п
