### ISSUE TITLE
Cannot control ZNCZ04LM

### ISSUE THREAD

**Issue by Ababuy78** [AlexxIT/XiaomiGateway3#332]
I am not able to control Mi Smart Plug (Zigbee) (ZNCZ04LM) on Gateway 3 (ZDMWG02LM) with firmware 1.4.6_0043. The status, power consumption and total power are shown correctly.

I know it is not fully supported on this firmware, but would like to report it anyway so this can be corrected in the future (hopefully) and other people with the same issue have a reference for a known issue.

**Comment by AlexxIT** [comment]
This is very buggy firmware. I have many this plug on 0012. They always works fine
