### ISSUE TITLE
Can xiaomigetway3 support Yeelight Dimmer YLKG07YL/YLKG08YL in the future?

### ISSUE THREAD

**Issue by froggyfly** [AlexxIT/XiaomiGateway3#334]
Hi AlexxIT,

These Yeelight Dimmer YLKG07YL/YLKG08YL already be supported by <ble_monitor>, https://github.com/custom-components/ble_monitor

Is it possible to use the xiaomigateway3's BLE to let these dimmers be worked?

YLKG08YL is a wireless dimmer remote which has "dimmer", "push & dimmer", "sign click", "double click", "long hold" actions, and only cost 59 RMB ( $13 @ aliexpress.com ). Will be great if xiaomigetway3 can support it.

These dimmers usually link with the Yeelight's lights only, won't appear as a mii device in the mi app. 

https://nl.aliexpress.com/item/1005001846029666.html

**Comment by AlexxIT** [comment]
Yes, I have a working implementation. But there's a problem. The remote works fine, but the dimmer works horribly. Gateway misses a lot of clicks on the dimmer. And my Raspberry 3 catches these clicks perfectly. There seems to be some problem with the Gateway's software or hardware. I'm trying to figure out the reason right now.

**Comment by dumbodumbos** [comment]
Добрый. Есть ли подвижки в данном направлении. Рассматриваю приобретение данного диммера.

**Comment by AlexxIT** [comment]
@dumbodumbos диммер работает ужасно с Xiaomi Gateway 3. Думаю проблема на железном уровне. Пульт работает нормально.

Диммер работает нормально с этой интеграцией: 
https://github.com/custom-components/ble_monitor

**Comment by dumbodumbos** [comment]
Спасибо за ответ. А что за пульт - можете дать модель

**Comment by dumbodumbos** [comment]
> @dumbodumbos диммер работает ужасно с Xiaomi Gateway 3. Думаю проблема на железном уровне. Пульт работает нормально.
> 
> Диммер работает нормально с этой интеграцией: https://github.com/custom-components/ble_monitor

Спасибо за ответ. А что за пульт - можете дать модель

**Comment by AlexxIT** [comment]
Пульт YLYK01YL

Для новых BLE устройств может быть важно, к какому региону подключен шлюз. Сами шлюзы разных версий к региону НЕ привязаны.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
