### ISSUE TITLE
add one more entity (Smoke Density) to LUMI lumi.sensor_smoke

### ISSUE THREAD

**Issue by kingwap99** [AlexxIT/XiaomiGateway3#335]
In the mihome mode,
there is one more entity: Mi Smart Smoke Detector Smoke Density: 0 % obs/ft
May you please add it to ZHA also to  the complete it, thanks.

**Comment by AlexxIT** [comment]
I don't understand what you want

**Comment by kingwap99** [comment]
in MiHome mode, there are 3 entities
Mi Smart Smoke Detector Battery: 100%
Mi Smart Smoke Detector Smoke: Clear
Mi Smart Smoke Detector Smoke Density: 0 % obs/ft

but there is no Density entity, in ZHA mode, 
Can you add it also? thanks.

**Comment by AlexxIT** [comment]
No, I am not developing ZHA integration. Write to the official Hass repository
