### ISSUE TITLE
Aqara Cube (MFKZQ01LM) Rotate event

### ISSUE THREAD

**Issue by geradtl** [AlexxIT/XiaomiGateway3#34]
Добрый день, подскажите по интеграции Aqara Cube (MFKZQ01LM). В HA у него два события action_type и action_value. В Вашей  интеграции только одно событие. Как  определить направление и градус/степень поворота кубика?

**Comment by AlexxIT** [comment]
Не делал ещё. Добавлю

**Comment by AlexxIT** [comment]
Добавлено в последнем релизе. Не event, а action entity
