### ISSUE TITLE
Aqara precision motion sensor state not update.

### ISSUE THREAD

**Issue by bluefoxlee** [AlexxIT/XiaomiGateway3#342]
Kind of weird issue. Aqara precision motion sensor (lumi.motion.agl04) suddenly stop to update state.
Enabled and check the debug, it seems sensor did report some feedbacks.
It alway shows "off"on HA initial, then report unavailable after awhile. Restart HA will fix unavailable issue but still no update from the state. 

![截圖 2021-05-24 下午12 56 21](https://user-images.githubusercontent.com/894044/119298370-7e492480-bc8f-11eb-80cb-8086e6d785e8.png)

Going to try to pair another gateway 3 or Z2M to see if it's a hardware issue.

**Comment by a120578270** [comment]
Identify the error
![image](https://user-images.githubusercontent.com/58241282/119318916-6df37280-bcac-11eb-9c14-106be7ca3553.png)

**Comment by AlexxIT** [comment]
What firmware is your gateway?

**Comment by bluefoxlee** [comment]
> What firmware is your gateway?

I try both 1.46_0012 and 1.47_0160 custom firmware. The result are the same. 
It seems relate to [this fix](https://github.com/AlexxIT/XiaomiGateway3/commit/e6e2af3c6121d3c85082b2c526285eef6c32b83a) at two days ago.
Downgrade and tested with V1.2.1 fix the issue.

**Comment by AlexxIT** [comment]
Ok. I I'll check this. Thanks for tip

**Comment by bluefoxlee** [comment]
> Ok. I I'll check this. Thanks for tip

Thanks for the hard work, and let me know if you need to test. know nothing about coding but try to play around with it too.

**Comment by OTZro** [comment]
It looks the same as #346

**Comment by AlexxIT** [comment]
Check latest master version

**Comment by bluefoxlee** [comment]
Thanks. Confirm works. 
it's not in the release 1.2.3, I modify code from  [commit](https://github.com/AlexxIT/XiaomiGateway3/commit/240e47669d53a38e2a953a4551937819ec62b186).

Too bad, it seems ADV ble removed temporarily.

**Comment by AlexxIT** [comment]
I'm working on new BIG version on BLE support.

**Comment by bluefoxlee** [comment]
Yes, saw it on the telegram group (through translation tools.)
Look forward for the BLE update and great work. 

Thanks again!! close this issue for now.
