### ISSUE TITLE
Built in zigbee2mqtt

### ISSUE THREAD

**Issue by makabar** [AlexxIT/XiaomiGateway3#343]
Hello there,

I have a question about mqtt.
Btw... a built in zigbee2mqtt would be great or could mosquitto work as a bridge to my main mqtt-broker? 
I am not using HASS because I´m glad that my node-red installation ist working well.
Is it possible to send incoming zigbee or BT topics from the gateway to an external mosquitto server? Maybe the opportunity is already there and I am too stupid to figure it out. 
Last question: How to pair new devices by using CLI?

Best regards

**Comment by AlexxIT** [comment]
You can use external zigbee2mqtt, but you need change something in gateway firmware.

I'm not interesting to spend time on not Hass way, because I have a lot of work with Hass way.

**Comment by makabar** [comment]
Hello Alexx,
thank You for Your replay.
Running Z2M on external machine is no problem. 
I´ve flashed Z2M Firmware as suggested here https://github.com/zvldz/mgl03_fw/tree/main/zigbee.
According to my understanding the mgl03 should listen on port 8888 from now on, right?
Unfortunately it does'nt do it so I can´t establish a socket-connection to it.
`# netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:54322         0.0.0.0:*               LISTEN      1038/miio_client
tcp        0      0 127.0.0.1:54323         0.0.0.0:*               LISTEN      1038/miio_client
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      966/mosquitto
tcp        0      0 :::43567                :::*                    LISTEN      1472/homekitserver
tcp        0      0 :::23                   :::*                    LISTEN      965/telnetd
tcp        0      0 :::1883                 :::*                    LISTEN      966/mosquitto
`

**Comment by AlexxIT** [comment]
No, you need to download socat and run it manually on each gateway restart. Or check `etc/init.d/rcS` for custom startup script. But be careful, if you have mistake - you can brick gateway.

https://sourceforge.net/projects/mgl03/files/bin/

**Comment by AlexxIT** [comment]
I think there are no more questions on this issue
