### ISSUE TITLE
Aqara Door Lock N200 (ZNMS17LM) only show battery.

### ISSUE THREAD

**Issue by aho206** [AlexxIT/XiaomiGateway3#345]
![aqara n200](https://user-images.githubusercontent.com/65076364/119918575-4990e200-bf9b-11eb-951f-9a219c0ede07.jpg)

i only can see battery. other lock / unlock etc didnt found.

**Comment by weiyideai520** [comment]
你尝试开关一下门，让蓝牙设备上报下一信息，然后在hass上重栽一下 ，应该就有了

**Comment by aho206** [comment]
> 
> 
> 你尝试开关一下门，让蓝牙设备上报下一信息，然后在hass上重栽一下 ，应该就有了

![图片](https://user-images.githubusercontent.com/65076364/120099463-2702f280-c16e-11eb-8d08-ac7ba7b798f6.png)
出来了门锁action。 
但是兄弟，请问怎么可以得到他的状态啊？ 比如开门 关门 锁门之类的。

**Comment by weiyideai520** [comment]
action里面应该有状态变化

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#handle-ble-locks
