### ISSUE TITLE
Aqara Precision Motion Sensor doesn't work

### ISSUE THREAD

**Issue by OTZro** [AlexxIT/XiaomiGateway3#346]
Version: 1.2.3
Issue:

Aqara Precision Motion Sensor entity always show close status. 

After trancing code, I found that if I change 
```
{
    'lumi.motion.agl04': ["Aqara", "Precision Motion Sensor", "RTCGQ13LM"],
    'mi_spec': [
        ['4.1', None, 'motion: 1', 'binary_sensor'],
        ['3.1', '3.1', 'battery', 'sensor'],
    ]
}
```
at `core/zigbee.py` to `['4.1', None, 'motion', 'binary_sensor']`

and change 
```
                d = yaml.safe_load(prop)
                if isinstance(d, dict):
                    payload.update(d)
```
at `core/gateway3.py` to 
```
                if prop == 'motion':
                    payload[prop] = 1
```
Aqara Precision Motion Sensor work as normal motion sensor, but I don't know how and why it happen.

**Comment by AlexxIT** [comment]
Duplicate #342
