### ISSUE TITLE
zigbee2mqtt all devices disconnected

### ISSUE THREAD

**Issue by the3future** [AlexxIT/XiaomiGateway3#347]
<img width="1323" alt="120051786-ac927f80-c054-11eb-8cce-fb4a2e72abd2" src="https://user-images.githubusercontent.com/58800810/120248237-ebb90e80-c2a8-11eb-8bca-4b00768ed8e4.png">

Having a lot of trouble setting this up. My devices work for days with no issues at all, but all of sudden everything drops, and I have to pair the devices again. Is there something that I didn't set up correctly?

**Comment by the3future** [comment]
So after 3 days, this is happening again all of the sudden. 30 minutes ago it was still alright, but suddenly fail to work. 

It seems zigbee2mqtt unable to talk to Xiaomi Gateway.

**Comment by the3future** [comment]
Not sure anyone running into the same issue. I had the problem again, and I realise if I make any settings change on HA XiaomiGateway3, I can start using my Zigbee devices again

**Comment by colethegamer123** [comment]
I have totally the same problem, second time in this month. All the devices lost, Its inside Zigbee2MQTT but not changing status and other values are also missing like Battery and LQI.

**Comment by AlexxIT** [comment]
Duplicate #319
