### ISSUE TITLE
Can't send get_properties [{'did': '1060480130', 'siid': 2, 'piid': 2}, {'did': '1060480130', 'siid': 2, 'piid': 3}]

### ISSUE THREAD

**Issue by weiyideai520** [AlexxIT/XiaomiGateway3#348]
此错误来自自定义集成。

```
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157 
Integration: Xiaomi Gateway 3 (documentation, issues) 
First occurred: 上午8:17:30 (3 occurrences) 
Last logged: 上午8:18:48

192.168.199.232 | Can't send get_properties [{'did': '1060480130', 'siid': 2, 'piid': 2}, {'did': '1060480130', 'siid': 2, 'piid': 3}]
```

**Comment by Soolita** [comment]
Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/gateway3.py:135
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 9:11:59 (7 occurrences)
Last logged: 9:16:26

Processing MQTT: log/miio b'\x1b[0;32m2021:06:02:09:13:02.696 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"75639880","piid":21,"siid":3,"value":0}],"id":237113}{"method":"properties_changed","params":[{"did":"75639880","piid":2,"siid":3,"value":2}],"id":237114}{"method":"properties_changed","params":[{"did":"75639880","piid":1,"siid":3,"value":0}],"id":237115} length:102 bytes\x1b[0m'
Processing MQTT: log/miio b'\x1b[0;32m2021:06:02:09:13:02.697 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"75639880","piid":2,"siid":3,"value":2}],"id":237114}{"method":"properties_changed","params":[{"did":"75639880","piid":1,"siid":3,"value":0}],"id":237115} length:101 bytes\x1b[0m'
Processing MQTT: log/miio b'\x1b[0;32m2021:06:02:09:13:02.697 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"75639880","piid":1,"siid":3,"value":0}],"id":237115} length:101 bytes\x1b[0m'
Processing MQTT: log/miio b'\x1b[0;32m2021:06:02:09:16:25.213 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"75639880","piid":21,"siid":3,"value":2}],"id":237167}{"method":"properties_changed","params":[{"did":"75639880","piid":1,"siid":3,"value":2}],"id":237168} length:102 bytes\x1b[0m'
Processing MQTT: log/miio b'\x1b[0;32m2021:06:02:09:16:25.213 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"properties_changed","params":[{"did":"75639880","piid":1,"siid":3,"value":2}],"id":237168} length:101 bytes\x1b[0m'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 890, in on_message
    if prop in zigbee.GLOBAL_PROP:
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 135, in process_mesh_data
    continue
TypeError: 'NoneType' object is not iterable

**Comment by FaintGhost** [comment]
got same problem after update homeassistant to 2021.6.0

**Comment by runnerfanspb** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 2 июля 2021 г., 17:35:56 (24 occurrences)
Last logged: 3 июля 2021 г., 23:37:23

192.168.1.12 | Can't send get_properties [{'did': '408555916', 'siid': 3, 'piid': 1}]
192.168.1.12 | Can't send get_properties [{'did': '1040186662', 'siid': 2, 'piid': 1}]
 Ошибка возникает на Ha 2021.6.6 версия шлюза 1.5.0.0026

**Comment by AlexxIT** [comment]
Duplicate #223
