### ISSUE TITLE
how to support NIOYE Mesh Downlight

### ISSUE THREAD

**Issue by iam993** [AlexxIT/XiaomiGateway3#350]
NIOYE Mesh Downlight cannot work completely on this integration ,integration can search for every device include the light group  ,but can not control them in homeassistant . i make the light state changed in MiJia app ,and the homeassistant can sync state.

so ,how can i support them ,or support in integration ?

**Comment by rezmus** [comment]
show device icon from mijia app. can't find nioye downlight.

**Comment by iam993** [comment]
light is made by nioye . add to mijia app should choose the "mijia led mesh light".  pid is 2351 .

**Comment by rezmus** [comment]
lemesh.light.wy0c05

**Comment by iam993** [comment]
that's it, I was about to say

**Comment by iam993** [comment]
can the device be supported in the future?

**Comment by AlexxIT** [comment]
Supported in latest version
