### ISSUE TITLE
Add Mi Smart Door Lock Pro support

### ISSUE THREAD

**Issue by denisov-vlad** [AlexxIT/XiaomiGateway3#354]
Hi!

Is it possible to add this lock to Gateway3 integration?

https://aliexpress.ru/item/1005001987966865.html?spm=a2g0s.9042311.0.0.264d33edoRUNju&_ga=2.211088919.321838671.1622553099-637143444.1622206317&sku_id=12000018326190517

`2021-06-01 16:05:23  DEBUG    gateway3      192.168.33.20 | Setup ble device {'did': '1021014704', 'mac': 'd8479896743f', 'model': 2329, 'type': 'ble', 'online': True, 'init': {}, 'device_name': 'Mi Smart Door Lock Pro', 'device_model': 2329}
`

I can help with additional log if needed.

**Comment by denisov-vlad** [comment]
There was a lag before it appeared in HA.

**Comment by AlexxIT** [comment]
It appear only after some event from lock (open/close, etc).
