### ISSUE TITLE
FlexSwich support

### ISSUE THREAD

**Issue by IhorSyerkov** [AlexxIT/XiaomiGateway3#355]
New yeelight celling light and some of bulbs (YLDP26YL for-sure ) have FlexSwich support. It's quite cool, even your smart home is down you are able to turn on/off ligts :).

Would be cool to expose into HA swich for no/off **Flex-mode** .
Maybe somebody knows link to ble miio api, I searching on http://miot-spec.org/miot-spec-v2/instances?status=all , but looks like there only wifi devices.

**Comment by AlexxIT** [comment]
You can enable this mode with MiHome

**Comment by rezmus** [comment]
or miio, but it's not related to gw3
```
{"id":123,"method":"get_prop","params":["smart_switch"]}
{"id":124,"method":"set_ps","params":["cfg_smart_switch","1"]}
```

**Comment by AlexxIT** [comment]
You can change BLE Mesh devices properties by sending miot commands to gateway IP with gateway token.

**Comment by AlexxIT** [comment]
Adds support. Will be in next beta/release version
