### ISSUE TITLE
_gateway entity for v1.4.7_0160 gateways - have no load/RSSI info

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#358]
Issue first appeared after component upgrade to v1.2.3.
After full HA host restart - still the same: _gateway entities for gateways not populated with RSSI/load/uptime info in ~3 hours.

![image](https://user-images.githubusercontent.com/15225823/121667038-8c31de80-cab2-11eb-8ed4-8010850880c1.png)

![image](https://user-images.githubusercontent.com/15225823/121667106-9fdd4500-cab2-11eb-9b65-8292c1d682f0.png)

![image](https://user-images.githubusercontent.com/15225823/121667209-b5eb0580-cab2-11eb-967b-ce07f26ff9ea.png)

**Comment by Masterz69** [comment]
After downgrade to 1.2.0 back - still have no _zigbee entities for gateways.
Can it be related to HA OS 2021.6.x ???

**Comment by AlexxIT** [comment]
Check integration settings. Is "Zigbee and BLE performance data" enabled?

**Comment by Masterz69** [comment]
Yes, enabled - before and now for both XG3.
_zigbee entities present for devices, but not gateways. See attached screenshot.
_zigbee entities for gateways existed before upgrade to v1.2.3, and disappeared then.

![image](https://user-images.githubusercontent.com/15225823/121819513-24d48400-cc96-11eb-9029-03aa0490b7d9.png)
![image](https://user-images.githubusercontent.com/15225823/121819536-3d449e80-cc96-11eb-9ef5-4470ea66ebde.png)

**Comment by Masterz69** [comment]
Probably information parsing for v1.4.7_0160 not working anymore.
Just upgraded both gateways to custom firmware 1.5.0_0026 - _gateway entities populated with RSSI/uptime/load info after ~5 minutes after gateway loading.

Below see: XG3 H upgraded to 1.5.0_0026, XG3 S still 1.4.7_0160:
![image](https://user-images.githubusercontent.com/15225823/121888396-9fe27c80-cd20-11eb-888b-33026edcdbef.png)

**Comment by Masterz69** [comment]
So, solution for me for that particular issue - is to upgrade gateways to 1.5.0_0026.
