### ISSUE TITLE
Update post integration issues

### ISSUE THREAD

**Issue by hbwy1314** [AlexxIT/XiaomiGateway3#363]
After the integration is updated, all Bluetooth mesh devices in the multi-mode gateway will be offline. After the integration is closed, restart and return to normal???

**Comment by hbwy1314** [comment]
Homeassistant has also been updated to the latest version

**Comment by AlexxIT** [comment]
How many gateways do you have?

**Comment by hbwy1314** [comment]
6个



发自我的iPhone


------------------ Original ------------------
From: Alex X ***@***.***&gt;
Date: Tue,Jun 15,2021 9:46 PM
To: AlexxIT/XiaomiGateway3 ***@***.***&gt;
Cc: hbwy1314 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AlexxIT/XiaomiGateway3] Update post integration issues (#363)

**Comment by AlexxIT** [comment]
Xiaomi has a bug if user has more than one BLE Mesh gateway. I working on fix

**Comment by modem** [comment]
I have 1 gateway, connected to the EUR server, and all my HT2 bluetooth devices don't report any values. 2 of them report what seems to be stuck data and not related to the read data the devices are showing. Is it the same issue?

**Comment by AlexxIT** [comment]
@modem no. This problem only with Mesh switches and Mesh bulbs.

**Comment by modem** [comment]
I was able to solve my issues. I'm behind PiHole DNS and the gateway was not able to connect to the cloud. I restored the Pihole interface settings and it all started to work.
