### ISSUE TITLE
Mesh Light - cannot control brightness

### ISSUE THREAD

**Issue by algovera** [AlexxIT/XiaomiGateway3#364]
Unable to control mesh lights' brightness.

Okay for on/off and toggle, color temperature correctly.
But not the brightness settings. 

Tried all the brightness methods on nodered, lovelace UI, and none of them works.
brightness
brightness_pct
brightness_step
brightness_step_pct

Brightness not working in Lovelae, Color temp is Okay.
![image](https://user-images.githubusercontent.com/48702353/121800847-b3c9a800-cc66-11eb-8e72-52d839572928.png)

Purchased BLE based lights from two different manufacturers (Model 3164, 2293), here are their UIs and they are apparently different versions of a generic driver interface;

Both lights work fine on Mi Home UI through the screenshots below. In HA, only color temp is controllable but not brightness.

Model 3164 UI
![IMG_3860](https://user-images.githubusercontent.com/48702353/121801043-df995d80-cc67-11eb-9dd9-13b9b8470937.PNG)

Model 3164 Built-in scenes on Xiaomi app
Though irrelevant, they are more advanced in terms of built-in xiaomi scenes (on, off, on/off toggle, brights +/-, tempeature +/-)
![IMG_3913](https://user-images.githubusercontent.com/48702353/121801052-f17b0080-cc67-11eb-844a-bd09016432b1.PNG)

Same issue on Model 2293 does not work as well

Hoping to gain this control, so the lights can blend according to the ambient light and based on time of the day.

Any help is appreciated!

**Comment by rezmus** [comment]
add your lights to core/bluetooth.py like here

https://github.com/AlexxIT/XiaomiGateway3/issues/350

also add their model pid to MAX_BRIGHTNESS with max value 100.

**Comment by algovera** [comment]
Superb! it is working.

Now i am able to control brightness, by specifying the MAX_BRIGHTNESS with my pid.

After which I have grouped them, and their Model name is "Mesh Group".  For those whom later come by this issue, pid 0 will further specify groups' max brightness.

Now everything is working, by individual light model and as a group.

Big thanks!

**Comment by AlexxIT** [comment]
I'll close this when I add this model to component for other users

**Comment by algovera** [comment]
To help summarize, two models actually
Model 3164, 2293
both MAX_BRIGHTNESS 100

**Comment by algovera** [comment]
Got another controller - 3416 tested and veriified.

    2293: ["Unknown", "Mesh Lightstrip (RF ready)", "2293"],
    3164: ["Unknown", "Mesh Downlight (RF ready)", "3164"],
    3416: ["Unknown", "Mesh Downlight (Yeelight compatible)", "3416"],


MAX_BRIGHTNESS = {
    0: 100,
    2293: 100,
    3164: 100,
    3416: 100,
}

**Comment by AlexxIT** [comment]
Adds in latest master. Will be in next release. Thanks
