### ISSUE TITLE
Flower Care sensor (HHCCJCY01) update too often

### ISSUE THREAD

**Issue by furiaceka87** [AlexxIT/XiaomiGateway3#367]
Hi,
I've integrated  Flower Care sensor (HHCCJCY01) in my gateway ZNDMWG03LM using Chinese servers.
At the moment everything is working properly, but unfortunately all the parameters are update too often between 30s and 60s.

Do you know how to change this interval?

<img width="385" alt="Schermata 2021-06-26 alle 18 41 35" src="https://user-images.githubusercontent.com/40276630/123519896-31050c00-d6ae-11eb-8f38-088f5edf6364.png">

**Comment by viotemp1** [comment]
Hello,

I have also this issue. Can you please let us know if it is possible to increase the scan interval of these sensors?
Battery will drain pretty fast with current interval.

**Comment by AlexxIT** [comment]
You can't change report interval of this sensors.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
