### ISSUE TITLE
New install not showing in Integrations

### ISSUE THREAD

**Issue by bgbaker** [AlexxIT/XiaomiGateway3#37]
I have followed the installation video.
The integration install under HACS but then when I go to "Configuration" "Integration" and search for "Xiaomi.." or "3" to configure it, it does not come up in the results.
I was running an older version of Hass and HACS and then upgraded to all latest but the problem still remains.
![ss2](https://user-images.githubusercontent.com/4025207/93782986-7f6f1100-fc2b-11ea-8539-c70121983db8.png)
![ss1](https://user-images.githubusercontent.com/4025207/93782997-8138d480-fc2b-11ea-8cd8-558befff27c8.png)

**Comment by agasfers** [comment]
Try refreshing webpage - Ctrl+F5

**Comment by luna825** [comment]
I have the same situation.

**Comment by AlexxIT** [comment]
Check Home Assistant logs. Try restart Home Assistant.

**Comment by AlexxIT** [comment]
Browser cache
