### ISSUE TITLE
Firmware 1.5.0_0027

### ISSUE THREAD

**Issue by GavinIves** [AlexxIT/XiaomiGateway3#370]
i found new version 1.5.0_0027 telent login:admin password:admin 
can you add this version ,thank you very much

**Comment by GavinIves** [comment]
i found a way
use telent login in
then passwd -d admin

open telent command :{"method":"set_ip_info"}
 its ok!!!!

**Comment by GavinIves** [comment]
oh no !!!
when it restart ,you need do that again

**Comment by rezmus** [comment]
there is no point to update to 1.5.0_0027. beside run telnetd and password change on each boot there are no difference to 1.5.0_0026.

**Comment by GavinIves** [comment]
But I accidentally updated to a new version. I am not familiar with linux. Now I can only control the smart home by deleting the password every time I restart the gateway. I hope it can be controlled by you, as before, through configuration.

**Comment by igorpischik** [comment]
@GavinIves Could you please provide full command for enabling telnet on 1.5.0_0027 firmware version?

**Comment by GavinIves** [comment]
@igorpischik Use the telent tool to connect to the gateway, enter the user name :admin, password :admin, and enter the command :passwd -d admin.

**Comment by rama31244** [comment]
Hi, i accidentally upgraded firmware to v1.5.0_0027 as well. Do i need to downgrade or will it work with homeassistant using the same integration? Do i just telnet into the gateway as described above and run the original telnet command from the instructions?

**Comment by Double-Dude** [comment]
> Hi, i accidentally upgraded firmware to v1.5.0_0027 as well. Do i need to downgrade or will it work with homeassistant using the same integration? Do i just telnet into the gateway as described above and run the original telnet command from the instructions?

@rama31244 , use @GavinIves solution for now. It works!

**Comment by rama31244** [comment]
I'm a bit of a tech noob so don't fully understand his solution. Is it just
to telnet into gateway and run that "passwd -d admin" command? Will this
immediately make everything work again? Thanks for the assistance

**Comment by Double-Dude** [comment]
> @igorpischik Use the telent tool to connect to the gateway, enter the user name :admin, password :admin, and enter the command :passwd -d admin.

@rama31244 , download a telnet app on your phone, e.g. iOS iTerminal search in App Store. Select telnet and do the above suggested steps. Restarted your HA, then it should work for now. Repeat the same when you restart your mi hub.

**Comment by rama31244** [comment]
Worked a charm! Thank you so much. I was so worried I would need to open it
up and do soldering. I'm gonna turn on the firmware update lock to prevent
this in the future

**Comment by pravdik** [comment]
> > @igorpischik Use the telent tool to connect to the gateway, enter the user name :admin, password :admin, and enter the command :passwd -d admin.
> 
> @rama31244 , download a telnet app on your phone, e.g. iOS iTerminal search in App Store. Select telnet and do the above suggested steps. Restarted your HA, then it should work for now. Repeat the same when you restart your mi hub.

Just edit the shell.py to automatically send and disable the password during component initialization.

**Comment by Double-Dude** [comment]
> > > @igorpischik Use the telent tool to connect to the gateway, enter the user name :admin, password :admin, and enter the command :passwd -d admin.
> > 
> > 
> > @rama31244 , download a telnet app on your phone, e.g. iOS iTerminal search in App Store. Select telnet and do the above suggested steps. Restarted your HA, then it should work for now. Repeat the same when you restart your mi hub.
> 
> Just edit the shell.py to automatically send and disable the password during component initialization.

Thanks for your idea. Are you able to do a pull request for the fix?

**Comment by pravdik** [comment]
> 
> 
> > > > @igorpischik Use the telent tool to connect to the gateway, enter the user name :admin, password :admin, and enter the command :passwd -d admin.
> > > 
> > > 
> > > @rama31244 , download a telnet app on your phone, e.g. iOS iTerminal search in App Store. Select telnet and do the above suggested steps. Restarted your HA, then it should work for now. Repeat the same when you restart your mi hub.
> > 
> > 
> > Just edit the shell.py to automatically send and disable the password during component initialization.
> 
> Thanks for your idea. Are you able to do a pull request for the fix?

I have fixed it for myself and i think Alex is aware of this issue.

like this:
        raw = self.read_until(b"\r\n# ", timeout=3)
        if b'Password:' in raw:
            self.write(b"admin\n")
            self.write(b"passwd -d admin\n")
            # raise Exception("Telnet with password don't supported")

I'm not sure about this solution due to uncertainty how many times this class calls. Maybe password should be sent right after login if class only uses during initialization once.

**Comment by yangwe1** [comment]
Please anyone help...how can I prevent the firmware self-upgrade? I downgrade to 1.5.0_0026 but now 0027 again

**Comment by Double-Dude** [comment]
> Please anyone help...how can I prevent the firmware self-upgrade? I downgrade to 1.5.0_0026 but now 0027 again

@yangwe1 , do you mind share the method you used to downgrade the firmware please?

**Comment by botyto89** [comment]
@yangwe1 Hi, after you downgrade, you can go configuration - integration - Xiaomi Gateway 3 - your gateway IP - devices - your gateway and then turn on gateway Firmware lock, then your gateway won't be able to upgrade automatically anymore.

**Comment by botyto89** [comment]
@Double-Dude Hey, it took me a while to find out after accidentally upgraded to 1.5.0.0027, I even raised up an issue and the author didn't even mention downgrading. You can actually downgrade to a customized 1.5.0_0026_mod which is fully supported by this integration. The author does put it in the README but it is very hard to find as this is such an important step to keep this going in my opinion. 

**Anyway, follow this [link](https://github.com/zvldz/mgl03_fw/tree/main/firmware), download putty telnet in and then choose the firmware you like, don't forget to turn on firmware lock after you finish, so you won't need to worry about it again. The last thing, if you are using the new version of putty, when you telnet, your connection type should be other and the port number remains 23.** 

Hope this can help you and others with 1.5.0.0027 firmware.

**Comment by igorpischik** [comment]
Tested new firmware **1.5.0_0102** and after the upgrade this version doesn't require removing the admin password like we did on 1.5.0_0026 and 1.5.0_0027, also on this version password not reseted after gateway reboot.

Maybe this information will be helpful for someone.

**Comment by AlexxIT** [comment]
1.5.0_0027 won't be supported because 1.5.0_0102 released

**Comment by rama31244** [comment]
Hi
How do you suggest backing up before upgrading Xiaomi gateway 3 to 4.0.0?
Just a full hassio backup?

Thanks

**Comment by AlexxIT** [comment]
Yes. Just Hass backup

**Comment by rama31244** [comment]
Thanks

**Comment by rama31244** [comment]
Hi
I'm getting the following error in my home assistant log:
ATTR_COLOR_TEMP was used from xiaomi_gateway3, this is a deprecated
constant which will be removed in HA Core 2026.1. Use kelvin equivalent
(ATTR_COLOR_TEMP_KELVIN) instead, please report it to the author of the
'xiaomi_gateway3' custom integration

Is there something I need to change in my config?

Thanks

**Comment by AlexxIT** [comment]
Check other issues

**Comment by rama31244** [comment]
Sorry, you're right. Don't know how I missed this
