### ISSUE TITLE
Alarm Panel no Armed_Night mode?

### ISSUE THREAD

**Issue by itispip** [AlexxIT/XiaomiGateway3#371]
It has confused my some time.

On UI, Alarm Panel only have 2 buttons: Armed_Away mode & Armed_Home mode.

While looking at the underlying code, this component does support Armed_Night too.

Is this a bug or it's intended to hide Armed_Night mode by design?

**Comment by zvldz** [comment]
Maybe you need to add arm_night.
It is off by default.

https://www.home-assistant.io/lovelace/alarm-panel/

**Comment by itispip** [comment]
> Maybe you need to add arm_night.
> It is off by default.
> 
> https://www.home-assistant.io/lovelace/alarm-panel/

Thanks for reply. It doesn't work. Alex's component automatically created the Alarm Panel already without arm_night mode, cannot modify/add the night_mode by YAML.

**Comment by AlexxIT** [comment]
There is no night button for Hass alarm panel. But you can create script which starts night mode via service.
Integration supports night mode
