### ISSUE TITLE
Gateway and home assistant - trigger

### ISSUE THREAD

**Issue by darkkatarsis** [AlexxIT/XiaomiGateway3#372]
Hi,
After adding integration to home assistant, I can arm / disarm the gateway. However, the alarm_control_panel.alarm_trigger service does not work. Is this a known bug? Any chance it will work in the future?

my code:
```
service: alarm_control_panel.alarm_trigger
target:
  entity_id: alarm_control_panel.gateway_alarm
```

**Comment by elenril2** [comment]
I've reported it in [#257](https://github.com/AlexxIT/XiaomiGateway3/issues/257). Unfortunatelly there isn't any update on this problem.

**Comment by AlexxIT** [comment]
Alarm with manual sound trigger and other stuff in development.

**Comment by darkkatarsis** [comment]
> Alarm with manual sound trigger and other stuff in development.

Wow, great news!

**Comment by AlexxIT** [comment]
Duplicate #257
