### ISSUE TITLE
Add support for Aqara H1 EU switches

### ISSUE THREAD

**Issue by nickthegreek** [AlexxIT/XiaomiGateway3#374]
Hi, can you please add support for the H1 EU switches?

https://zigbee.blakadder.com/Aqara_WS-EUK01.html
https://zigbee.blakadder.com/Aqara_WS-EUK02.html
https://zigbee.blakadder.com/Aqara_WS-EUK03.html
https://zigbee.blakadder.com/Aqara_WS-EUK04.html

I own the first two so maybe I can assist.

Here's the log for EUK01 (lumi.switch.l1aeu1).

[log_h1.txt](https://github.com/AlexxIT/XiaomiGateway3/files/6741855/log_h1.txt)

**Comment by AlexxIT** [comment]
What you doing in this logs? Have you connected the device more than once? I can see a lot of pairing process there.

**Comment by nickthegreek** [comment]
Correct, I was experimenting. I could see in the notifications (in home assistant) that the device was successfully added, but I couldn't find it anywhere. If you want me to perform any specific steps let me know, I'd be happy to help.

**Comment by AlexxIT** [comment]
You need connect device to MiHome. Restart HA. Click all device buttons in all ways. And send logs again.
For both models.

**Comment by Izznolu** [comment]
Just got mine H1 Single and Double Version, both without neutral wire
works with:

```
{
    # without neutral wire
    'lumi.switch.l1aeu1': ["Aqara", "Single Wall Switch H1", "WS-EUK01"],
    'miot_spec': [
        ['2.1', '2.1', 'switch', 'switch'],
        ['7.1', None, 'button: 1', None],
        ['7.2', None, 'button: 2', None],
        [None, None, 'action', 'sensor'],
    ]
}, {
    # without neutral wire
    'lumi.switch.l2aeu1': ["Aqara", "Double Wall Switch H1", "WS-EUK02"],
    'miot_spec': [
        ['2.1', '2.1', 'channel 1', 'switch'],
        ['3.1', '3.1', 'channel 2', 'switch'],
        ['8.1', None, 'button_1: 1', None],
        ['8.2', None, 'button_1: 2', None],
        ['9.1', None, 'button_2: 1', None],
        ['9.2', None, 'button_2: 2', None],
        ['10.1', None, 'button_both: 4', None],
        [None, None, 'action', 'sensor'],
    ]
}
```
in zigbee.py

**Comment by AlexxIT** [comment]
@Izznolu thanks! Supported in latest master

**Comment by AlexxIT** [comment]
Added to v1.4.0. Thanks!
