### ISSUE TITLE
xiaomi Gateway 3 ZNDMWG03LM with LYWSD03MMC temperature

### ISSUE THREAD

**Issue by heliacagr** [AlexxIT/XiaomiGateway3#375]
hello i have install xiaomi Gateway 3 ( ZNDMWG03LM ) to xiaomi home application. and i connect all Xiaomi Mijia Smart Bluetooth Thermometer 2  ( LYWSD03MMC ) . i make install integration xiaomi gateway 3 i make "add Mi Cloud Account " i take token but when i make install say failed wrong token. any solution?

**Comment by AlexxIT** [comment]
Restart HA and try again

**Comment by heliacagr** [comment]
nop again wrong token

**Comment by heliacagr** [comment]
your video https://www.youtube.com/watch?v=CQVSFISC9CE  is old i can put custom inter* because xiaomi gateway 3 is already inside

**Comment by AlexxIT** [comment]
Try to get token another way

**Comment by heliacagr** [comment]
I make install xiaomi gateway 3 from hacs  after i go integration i found one xiaomi gateway 3 i make install i make mi cloud login and in dropdown menu show all my devices i press submit in gateway ip i see the token . After i go again integration xiaomi gateway 3 an
d in dropdown menu have add gateway (ip) when i press show host/token/open telnet command .
![IMG_20210703_101117](https://user-images.githubusercontent.com/71531189/124347882-1c150500-dbe7-11eb-8c9f-18adf48d574b.jpg)

**Comment by heliacagr** [comment]
Now i have error for tellnet command . What is the correct telnet command ?

**Comment by AlexxIT** [comment]
Have you read the text in this window carefully?

**Comment by heliacagr** [comment]
You mean i press documentation and i found the command ?

**Comment by heliacagr** [comment]
Sorry i forgot write my gateway come with firmware 1.5.0_0026

**Comment by heliacagr** [comment]
Ok i put this command and now work {"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
