### ISSUE TITLE
Devices are not available after update to 1.5.0 27

### ISSUE THREAD

**Issue by vitaliy-kozlov** [AlexxIT/XiaomiGateway3#376]
Hi. After update to latest 1.05.27 all devices stop working. Hub is discovered but all of connected devices is n/a. Please suggest.

**Comment by vitaliy-kozlov** [comment]
![image](https://user-images.githubusercontent.com/24417253/124334578-2b249480-dba0-11eb-8a4b-854075a458ea.png)

**Comment by AlexxIT** [comment]
Duplicate #370
