### ISSUE TITLE
Xiaomi Smart Gateway 3 does not start after update error

### ISSUE THREAD

**Issue by hudsonbrendon** [AlexxIT/XiaomiGateway3#38]
During an update there was a problem on my internet and the update ended up getting corrupted. Now my device always has a yellow LED, I tried to restart it by pressing the button for a few seconds but I was not successful, I believe the firmware has corrupted, does anyone know how to solve it?

**Comment by AlexxIT** [comment]
You can try flash new firmware https://github.com/AlexxIT/XiaomiGateway3/wiki
Or ask here https://t.me/xiaomi_gw_v3_hack
