### ISSUE TITLE
XiaomiGateway3 The firmware version has been updated(1.5.0_0027)

### ISSUE THREAD

**Issue by PWMFI** [AlexxIT/XiaomiGateway3#380]
### Discussed in https://github.com/AlexxIT/XiaomiGateway3/discussions/379

<div type='discussions-op-text'>

<sup>Originally posted by **PWMFI** July  3, 2021</sup>
The version number of the new version of the firmware is (1.5.0_0027). After Mi Home is updated, all HA entities do not respond. I hope the plugin author will update the plugin as soon as possible, thank you! ! !</div>

**Comment by zvldz** [comment]
downgrade firmware

**Comment by joasara** [comment]
The same thing happened to me, I have downloaded the version of the gateway but it is still not recognized by Home Assistant.

**Comment by PWMFI** [comment]
How do you solve it, can you only downgrade the firmware? Can the plug-in author support this version by updating?

**Comment by joasara** [comment]
I have now tested with v1.5.0_0026 and it seems to be stable.
Changing the version is very easy, follow what they put here:

https://github.com/zvldz/mgl03_fw/tree/main/firmware

**Comment by PWMFI** [comment]
> 我现在已经用 v1.5.0_0026 测试过，它似乎很稳定。
> 更改版本非常简单，请按照他们在这里放置的内容进行操作：
> 
> https://github.com/zvldz/mgl03_fw/tree/main/firmware

The current firmware is 1.5.0_0027, do you also follow this method?

**Comment by joasara** [comment]
Yes, but the user is "admin" and the password in "admin" again.

**Comment by PWMFI** [comment]
> Yes, but the user is "admin" and the password in "admin" again.

Okay thank you, do you need to disassemble the gateway for operation?

**Comment by joasara** [comment]
No, you can use the Telnet method.

**Comment by joasara** [comment]
Is very simply. Download putty and conect by telnet to the Gateway(admin/admin).
Later, you run this 3 comand:
--> wget -O /tmp/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1" && chmod +x /tmp/curl
--> export PATH="$PATH:/tmp"
--> curl -s -k -L -o /tmp/update.sh https://raw.githubusercontent.com/zvldz/mgl03_fw/main/firmware/mgl03_update.sh && sh /tmp/update.sh
Select the firmware 1.5.0_0026(4 option) and wait.

**Comment by PWMFI** [comment]
![微信截图_20210703153500](https://user-images.githubusercontent.com/63692121/124347005-7d9f9880-dc14-11eb-83c3-9b238adca1da.png)
thank you very much

**Comment by joasara** [comment]
Your welcome.

**Comment by AlexxIT** [comment]
Duplicate #370
