### ISSUE TITLE
Отвалились датчики BLE

### ISSUE THREAD

**Issue by petroffich** [AlexxIT/XiaomiGateway3#381]
Добра и здоровья! Несколько дней бьюсь. 
Сервер на малине 2021.6.6
Шлюз ZNDMWG03LM, Firmware: 1.5.0_0027, Режим Mi Home.
Два дверных сенсора MCCGQ02HL, Один термо/влаго LYWSD03MMC 
После очередной перезагрузки сервера датчики стали Unavailable. Ещё несколько раз перезагрузил сервер - эффекта ноль.
Переустановил интеграцию, в списке устройств появились шлюз и только два датчика - термо/влаго и датчик двери. 
Поработав полдня датчики снова стали Unavailable. Перезагрузки не помогают. Третий датчик так и не появился.
В самом Mi Home на телефоне все датчики видны и работают.
![Screenshot 2021-07-04 at 14 57 51](https://user-images.githubusercontent.com/82906592/124384340-5d85dd00-dcd9-11eb-8fb5-277d98a8add5.jpg)
![Screenshot 2021-07-04 at 15 06 46](https://user-images.githubusercontent.com/82906592/124384362-7c846f00-dcd9-11eb-99d4-d4ef337250da.jpg)

**Comment by petroffich** [comment]
Переустановил интеграцию ещё раз. Установка получилась только в два захода: сначала установил ингеграцию с учёткой ми хоум, потом к ней добавил вторую версию, уже с токеном. Сразу с токеном интеграция не устанавливалась, отваливалась с ошибкой "Недоступен шлюз"(или что-то вроде того.
После установки появился только датчик термо/влаго в рабочем состоянии. Датчики дверей не появились вообще. В самом ми хоум они по прежнему все видятся и работают.
![Screenshot 2021-07-04 at 15 26 13](https://user-images.githubusercontent.com/82906592/124384919-311f9000-dcdc-11eb-8c13-9712537b976c.jpg)

**Comment by AlexxIT** [comment]
Duplicate #370
