### ISSUE TITLE
Видны не все датчики BLE

### ISSUE THREAD

**Issue by petroffich** [AlexxIT/XiaomiGateway3#382]
Firmware 1.5.0_0027
Сделал, как написано в https://github.com/AlexxIT/XiaomiGateway3/issues/370
Но всё равно вижу только часть датчиков, и не все сенсоры, хоть и облачном режиме видны все
![Screenshot 2021-07-04 at 19 16 13](https://user-images.githubusercontent.com/82906592/124392067-5f14cc80-dcfc-11eb-9ff4-0e86a7b4eb4d.jpg)
![Screenshot 2021-07-04 at 15 35 29](https://user-images.githubusercontent.com/82906592/124392071-63d98080-dcfc-11eb-8f2a-d542a72d4479.jpg)

**Comment by AlexxIT** [comment]
Данные не появляются сразу же. Об этом написано в документации. Отображение датчиков в списке из облака совсем не значит, что шлюз получает от них данные. Также могут быть проблемы с подключением к шлюзу на сомнительных роутерах.
