### ISSUE TITLE
Add support for Aqara VRF

### ISSUE THREAD

**Issue by firesunCN** [AlexxIT/XiaomiGateway3#384]
Hi, can you please add support for the Aqara VRF
model: lumi.airrtc.vrfegl01
It can be identified by XiaomiGateway3 but cannot be controlled
https://www.aliexpress.com/i/4001018939528.html

**Comment by AlexxIT** [comment]
Duplicate #113

**Comment by AlexxIT** [comment]
Enable logs in integration options. Control device in different ways and sand this logs to me.
