### ISSUE TITLE
not show devices after install , firmware version is 1.5.0_0027

### ISSUE THREAD

**Issue by chestarss** [AlexxIT/XiaomiGateway3#386]
![image](https://user-images.githubusercontent.com/11288347/124920354-d19de900-e029-11eb-8425-b0484fff006c.png)

**Comment by chestarss** [comment]
xiaomi gateway3 options only show like above picture

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/124920531-fdb96a00-e029-11eb-88d4-f6b896f75fff.png)


how can i make device show in index page

**Comment by chestarss** [comment]
i select one device click submit not working

**Comment by AlexxIT** [comment]
This screen shows only cloud devices token

**Comment by AlexxIT** [comment]
Have you seen fw 0027 in supported list?
