### ISSUE TITLE
Alarm trigger - this integration support it?

### ISSUE THREAD

**Issue by vampywiz17** [AlexxIT/XiaomiGateway3#39]
Hello there,

I thinking that replace my Gateway 2 to this Gateway. My question is this device and integration possible to generate alarm trigger with built-in alarm feature?

On Gateway 2, only possibe disable/enable  alarm, but no output trigger if the alarm is happen.

**Comment by AlexxIT** [comment]
Haven't worked with alarm yet.

**Comment by vampywiz17** [comment]
@AlexxIT Thanks the answer. In the future, if you check the alarm side, please inform that technically possible or not.

**Comment by AlexxIT** [comment]
Duplicate #133
