### ISSUE TITLE
Aqara Single Wall Button (WXKG03LM) onle have power

### ISSUE THREAD

**Issue by a394004149** [AlexxIT/XiaomiGateway3#392]
![2](https://user-images.githubusercontent.com/58944417/125305883-5017c500-e361-11eb-8d6d-409c81aa07a7.png)
single click does not work

**Comment by a394004149** [comment]
when i use Automation Modes，it also doesn‘t work.

alias: 妈妈门口开关
description: ''
trigger:
  - device_id: c8b4c80daaa9c2717baf19961b076a7b
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
condition: []
action:
  - type: toggle
    device_id: 15302936133aedd9f87dd49aa9f46669
    entity_id: switch.unk_manufacturer_lumi_ctrl_86plug_aq1_217ffa03_on_off
    domain: switch
mode: single

**Comment by AlexxIT** [comment]
Ask about ZHA support in Home Assistant repository

**Comment by a394004149** [comment]
Can you give me more details? Thanks a lot

**Comment by AlexxIT** [comment]
ZHA developing by Home Assistant team
https://www.home-assistant.io/integrations/zha/
