### ISSUE TITLE
Can't read devices: Telnet with password don't supported

### ISSUE THREAD

**Issue by JachinY** [AlexxIT/XiaomiGateway3#398]
Sometimes suddenly can't connect to the xiaomi multimode gateway, prompt：Can't read devices: Telnet with password don't supported

**Comment by JachinY** [comment]
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway3.py", line 546, in _get_devices
    shell = TelnetShell(self.host)
  File "/config/custom_components/xiaomi_gateway3/core/shell.py", line 56, in __init__
    raise Exception("Telnet with password don't supported")
Exception: Telnet with password don't supported

**Comment by JachinY** [comment]
@AlexxIT Boss, please help me see what the problem is

**Comment by mytering** [comment]
getting the same error today

**Comment by mytering** [comment]
https://github.com/zvldz/mgl03_fw/tree/main/firmware

downgrade firmware its working back

**Comment by JachinY** [comment]
@mytering thank you, I will try it

**Comment by JachinY** [comment]
@mytering when I entering the third command, there is no thing show up. None list I can choosee

**Comment by Wassermalone** [comment]
@mytering what port did you use to connect to your gateway? 

When I try to connect to my gateway via PuTTY with port 22 I get the username/password prompt. But when only entering admin for rlxlinux login and no password I get a Login incorrect error.

**Comment by mytering** [comment]
try 123123 the newer firmware had a password

**Comment by Wassermalone** [comment]
Thanks for the quick reply!

123123 was the password that previously worked for me, but it seems that they've changed the password to "admin" with firmware update 1.5.0_0027 :/

**Comment by AlexxIT** [comment]
Duplicate #370
