### ISSUE TITLE
Devices parenthood is wrong in case of multiple hubs in the network

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/XiaomiGateway3#4]
I have 2 hubs in the same network. 
Each hub has 2 devices - door and TH sensors. 
Everything was correct after adding the integration.
But after rebooting I see the following:

Hub#1: 
- Xiaomi Gateway 3 #1
- Xiaomi Door Sensor #1
- Xiaomi TH Sensor #1
The integration for all 3 devices is "Xiaomi Gateway 3, Xiaomi Gateway 3"

Hub#2: 
- Xiaomi Gateway 3 #2 (the integration "Xiaomi Gateway 3")
- Xiaomi Door Sensor #2 (the integration "Xiaomi Gateway 3")
- Xiaomi TH Sensor #2 (the integration "Xiaomi Gateway 3")
- Xiaomi Gateway 3 #1 (the integration "Xiaomi Gateway 3, Xiaomi Gateway 3")
- Xiaomi Door Sensor #1 (the integration "Xiaomi Gateway 3, Xiaomi Gateway 3")
- Xiaomi TH Sensor #1 (the integration "Xiaomi Gateway 3, Xiaomi Gateway 3")

**Comment by slydiman** [comment]
BTW, the state of Xiaomi Door Sensor #1 is unavailable now, but the battery level is available for this device.
The state of Xiaomi Door Sensor #2 is ok.

**Comment by AlexxIT** [comment]
Waiting second gateway for test this case

**Comment by slydiman** [comment]
Seems fixed in 0.2.0. Thanks
