### ISSUE TITLE
ZNGZDJ11LM

### ISSUE THREAD

**Issue by cinsler78** [AlexxIT/XiaomiGateway3#40]
Good afternoon. Do you plan to support roller blinds ZNGZDJ11LM ?

**Comment by AlexxIT** [comment]
Do you have them? If so, enable debug mode and show logs.

**Comment by cinsler78** [comment]
Yes, I have them. How does it enable debugging mode?

**Comment by cinsler78** [comment]
Можно на русском?

**Comment by AlexxIT** [comment]
Можно https://github.com/AlexxIT/XiaomiGateway3#debug-mode

**Comment by cinsler78** [comment]
[new 1.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5270342/new.1.txt)

**Comment by cinsler78** [comment]
debugging mode включил. Я так понимаю всё что там по ZNGZDJ11LM видно это Unsupported model: lumi.curtain.aq2

**Comment by AlexxIT** [comment]
Хм. Для неподдерживаемого устройства нужно включить `debug: mqtt`. Иначе его данные игнорируются.

**Comment by AlexxIT** [comment]
В #42 ещё один владелец. Поэтому полезно писать на английском :)

**Comment by cinsler78** [comment]
Set the master version. The device appeared, but there are no objects. Log close at 0% open at 100% apply.
[log.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5275991/log.txt)

**Comment by AlexxIT** [comment]
Maybe there are some errors in the main HA log? You can write to me on Telegram.

**Comment by AlexxIT** [comment]
Device supported in latest version
