### ISSUE TITLE
小米门窗传感器2时不时显示不可用, Mi window and door sensor becomes off line occasionally

### ISSUE THREAD

**Issue by botyto89** [AlexxIT/XiaomiGateway3#404]
我有三个小米门窗传感器2，其中有一个刚接入gateway3的时候显示不可用，过几天好了，最近几天又不可用，其它两个没有出现过问题，在米家里查看一切正常

**Comment by AlexxIT** [comment]
Need more details

**Comment by botyto89** [comment]
Hey Alex, it was just on and off again yesterday, just wondering if you could advise me what kind of data or details do you need? Thanks!

**Comment by AlexxIT** [comment]
BLE sensor may become unavailable for many reasons. Problems with WiFi, very long distance between gateway and sensor, unsupported gateway firmware, some software errors in gateway soft

**Comment by botyto89** [comment]
Yeah you did remind me that I'm currently running on 0027...So regretful that I updated it by accident...it just kind of doesn't make sense to me that I have 3 identical sensors but just that one has this issue, I think it might just be the new firmware, it works ok for now anyway, I think I'll just wait on the better support for this new firmware, cheers
