### ISSUE TITLE
Wrong Mi Home token

### ISSUE THREAD

**Issue by leekeifuture** [AlexxIT/XiaomiGateway3#405]
Hello everyone. I have a problem on step of the connecting Gateway 3 to Home Assistant via HACS. After connecting "Xiaomi Gateway 3" integration, I've signed in my Mi account. After that, I'm chose my gateway device from the devices list.

![image](https://user-images.githubusercontent.com/16304511/126399819-bd34b3ff-429e-4583-b15d-a9694635a86d.png)

Next - I'm added the same integration (Xiaomi Gateway 3) and selected my Gateway.

![image](https://user-images.githubusercontent.com/16304511/126399879-243c1f50-8908-474d-ab8f-df91238498e6.png)
![image](https://user-images.githubusercontent.com/16304511/126400080-d64dc25a-4118-448e-acf0-4d380567ba0d.png)

And after submitting the wizard - it throws error "**Wrong Mi Home token**".

![image](https://user-images.githubusercontent.com/16304511/126400230-bad8d984-da8f-4007-b410-7e3376d371e0.png)

Also, I've tried to paste new value at "Open Telnet command" field from [soft_hack.md](https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709):
`{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}` - but error the same.

Also tried use original version of Mi Home (not vevs) - the same error. Tried change regions (China and Russia) - don't helped. And, of course, tried to reset Gateway and rebind it to Mi Home with new token - also don't helped.

Versions of Instruments I use:
- Mi Home Vevs 6.7.700_64211
- Home Assistant 2021.7.3
- HACS 1.13.2
- Xiaomi Smart Home Gateway 3 (ZNDMWG02LM) 1.5.0_0027

Last logs from Home Assistant server:

![VirtualBox_Home Assistant_21_07_2021_01_21_48](https://user-images.githubusercontent.com/16304511/126402849-ad59eda4-55a9-4168-a5fe-6624a3c30ff4.png)

**Comment by AlexxIT** [comment]
Reboot Home Assistant. Check if no Xiaomi cloud errors in logs. Any try to add again.
Maybe integration loads old token

**Comment by leekeifuture** [comment]
I've rebooted Home Assistant - the same problem.
And don't found any Xiaomi cloud errors in logs.

![image](https://user-images.githubusercontent.com/16304511/126453600-e7d5edee-027a-4bcc-ae23-1c896658757c.png)

Token is new, because, as I can see in Mi Home Vevs - it shows token in network info tab. And it matches.

![image](https://user-images.githubusercontent.com/16304511/126451442-28c50712-d165-4c9d-ad38-40eb66c98209.png)

**Comment by AlexxIT** [comment]
Hass is unable to connect to the gateway. Maybe you have a problem on your local network. Or the gateway does not have access to its cloud

**Comment by leekeifuture** [comment]
I've resolved the problem. My gateway was updated to last version, and I've downgraded to custom firmware. Now everything works fine. The issue can be closed. Thanks

**Comment by effelab75** [comment]
> I've resolved the problem. My gateway was updated to last version, and I've downgraded to custom firmware. Now everything works fine. The issue can be closed. Thanks

I have the same problem, do you know how to install it?

**Comment by leekeifuture** [comment]
> > I've resolved the problem. My gateway was updated to last version, and I've downgraded to custom firmware. Now everything works fine. The issue can be closed. Thanks
> 
> I have the same problem, do you know how to install it?

Just downgraded the gateway firmware version
