### ISSUE TITLE
Получение beaconkey

### ISSUE THREAD

**Issue by sneakythr0ws** [AlexxIT/XiaomiGateway3#407]
Было бы круто к текущиму выводу токенов устройст добавить вывод beaconkey
https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key
6-й пункт. Если я правильно понимаю, то либа та же и достаточно дернуть
`ble_dbg_tbl_dump '{"table":"evtRuleTbl"}'`
`miiocli device --ip <IP> --token <TOKEN> raw_command ble_dbg_tbl_dump '{"table":"evtRuleTbl"}'`

**Comment by AlexxIT** [comment]
Это уже давно реализовано
