### ISSUE TITLE
Feature request: Support for WX10ZM

### ISSUE THREAD

**Issue by dmitriy2018** [AlexxIT/XiaomiGateway3#408]
Hi

Is there a chance for adding support for WX10ZM? This seems to be ZigBee version of WX08ZM.

I have several of them, can test on my HA instance if needed.

Thanks

**Comment by AlexxIT** [comment]
Seems like it has BLE passive. And I think it is already supported

**Comment by dmitriy2018** [comment]
After some time it was added as model 4160 & I am able to turn it on and off as it was added as Light to HA. So the basic feature is working. However, there is no way to see the resource left in repellent tablet. It does show it in MIHome.

**Comment by rezmus** [comment]
ble mesh. repellent left % is 4.1 siid/piid.

**Comment by AlexxIT** [comment]
@dmitriy2018 please show device page screen

**Comment by AlexxIT** [comment]
I ordered this device. I will receive it in a couple of days and add it to the component

**Comment by dmitriy2018** [comment]
@AlexxIT thanks!

Device: Mi Smart Mosquito Repeller 2
Manufacturer: <unknown>
Model: 4160
Integration: Xiaomi Gateway 3

I also have lumi.relay.c2acn01 LLKZMK11LM that is working perfectly through your integration.

**Comment by pilot1981** [comment]
Hi @dmitriy2018, You are able to see in HA battery level and/or repellent level consumable of Xiaomi mosquito repellent smart 2 (version 2021) ?

I'm planning to buy Xiaomi mosquito repellent smart 2 (version 2021) and control it using Homekit...I need to publish entity using HA...

**Comment by AlexxIT** [comment]
Adds support. Will be in next beta/release version

**Comment by Sergey-SRG** [comment]
![Screenshot_2022-06-01-17-25-56-575_com xiaomi smarthome](https://user-images.githubusercontent.com/3891900/171428189-4a62fa43-c92a-421e-9230-c9fe1ef61571.jpg)
Есть решение как включать и выключать с хаба?

**Comment by rfvermut** [comment]
yeah. shows on/off status correctly but cannot change it
