### ISSUE TITLE
Неверная команда для открытия Telnet

### ISSUE THREAD

**Issue by FiftyFour7250** [AlexxIT/XiaomiGateway3#409]
Привет, я совсем новичок, так что напишу пошагово, всё что я делал. Распаковал portable версию, далее запустил hass.cmd, сразу на этапе регистрации в Home Assistant - добавил аккаунт Mi Home. Затем Настройки --> Интеграции -->Добавить интеграцию --> Xiaomi Gateway 3 --> Add Шлюз (192.168.1.65), далее в этом окне добавления уже указаны IP, токен, и команда для открытия Telnet, жму "Подтвердить", он секунд 10 думает, и выдаёт ошибку: 
![image](https://user-images.githubusercontent.com/78786088/126884352-82b2be17-0819-41ca-a17f-eb91c5deae53.png)

IP и токен те же, что и если в интеграциях нажать на настройки аккаунта Mi Home, и выбрать там "Информация о устройствах MiCloud". Закрытие, и повторный запуск hass.cmd - ничего не дало.
Версия прошивки(?) шлюза - v1.4.6_0043

В чем может быть проблема, подскажи пожалуйста)

**Comment by FiftyFour7250** [comment]
Починилось!
Заменил команду на 

`{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}`

**Comment by DPakhotin** [comment]
Та же проблема. Версия прошивки шлюза, та же - v1.4.6_0043.  Ни один из вариантов команды открытия Телнет (выше) не привел к результату.  По прежнему ошибка "Неверная команда для открытия Telnet"
Шлюз зарегистрирован на сервере "Россия" (не Китай!) - собственно, это и указал при первичной интеграции облачного аккаунта.
