### ISSUE TITLE
a little unstable for long time

### ISSUE THREAD

**Issue by jie000jue** [AlexxIT/XiaomiGateway3#41]
When the HA run for 3 days, the BLE devices don't work. And in the log, there is nothing about them. But in Mi-Home, they works well.
The Zigbee devices still work.
"Can't send handshake" and "lumi.0 lumi.gateway.mgl03 <= {}" appeared more often than first.

![20200924092904](https://user-images.githubusercontent.com/36131433/94091208-45c82100-fe4a-11ea-8211-1283ddb605f5.jpg)

**Comment by AlexxIT** [comment]
There may be problems with Wi-Fi connection to Gateway

**Comment by jie000jue** [comment]
i can telnet the gateway, when "Can't send handshake".May some wifi network interuption lead the gateway go wrong？

**Comment by AlexxIT** [comment]
Maybe the miio protocol has problems after the connection is broken, but telnet still works. I'll think about rewriting the logic for checking the availability of the hub.

**Comment by jie000jue** [comment]
Maybe the geatway reboot itself.So it doesn't send the ble message.

**Comment by fedkevichan** [comment]
Добрый день! Имеются 2 BLE устройства Часы Xiaomi TH (LYWSD02MMC). В MiHome шлюз их хорошо видит. А в НА одно устройство обновляет данные постоянно, а второе - только при перезапуске НА.
![2020-10-09_13-38-28](https://user-images.githubusercontent.com/63534559/95574358-7bb5f980-0a35-11eb-8b1c-349c3f62eab3.png)
[log.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5354362/log.txt)

**Comment by AlexxIT** [comment]
@fedkevichan Может быть датчик слишком далеко от шлюза. В логах действительно при старте данные от двух датчиков, а затем только от одного.

**Comment by fedkevichan** [comment]
> @fedkevichan Может быть датчик слишком далеко от шлюза. В действительности при старте данных от двух датчиков, а затем только от одного логах.

Датчики находятся примерно на одинаковом расстоянии. 
Первый работает. Второй - нет
![Screenshot_2020-10-09-16-50-01-993_com xiaomi smarthome](https://user-images.githubusercontent.com/63534559/95591554-1f140800-0a50-11eb-82cd-6ca13c9378cc.jpg)

**Comment by AlexxIT** [comment]
Если в доме есть другие BLE гейты - могут быть проблемы с получением данных с BLE датчиков

**Comment by AlexxIT** [comment]
If this problem still actual - you may reopen this issue.
