### ISSUE TITLE
Xiaomi Gateway Offline

### ISSUE THREAD

**Issue by algovera** [AlexxIT/XiaomiGateway3#410]
turns out my HA needs to be in the same subnet of xiaomi gateway; when they are in different subnet (LAN vs IoT), I am able to ping Xiaomi on HA but unable to control it.

I'd being within the same subnet a requirement?

Anyone with any clue?

=========== original issure =====
My HA and Xiaomi Gatewa are in different vlan, I have firewall rules set up to allow HA server and IoT vlan to communicate with each other, and I am able to ping xiaomi from HA, yet I am receiving this error.

![image](https://user-images.githubusercontent.com/48702353/126903727-d697c959-94b3-40ab-b3cd-b9aef14f8fe4.png)

I am able to get updates from use of xiaomi app as shown in log
![image](https://user-images.githubusercontent.com/48702353/126903783-0282a1ef-f1ed-4d4e-8081-b503523deec6.png)

I recently had to reset my xiaomi gateway since I wanted to update its SSID to IoT vlan, i am able to maintain my firmware with v1.5 0026, so hopefully this isn't an issue with the firmware

Does any one have any clue how I might be able to address this?

**Comment by AlexxIT** [comment]
Error not from latest version
