### ISSUE TITLE
Шлюз не получается вернуть в работу под Mihome

### ISSUE THREAD

**Issue by nextboy79** [AlexxIT/XiaomiGateway3#411]
Здравствуйте. Все попытки вернуть шлюзу возможность работать в Mihome заканчиваются неудачей. Попытался в настройках интеграции Gateway3 переключиться с Z2MQTT на Mihome - получаю вверху окна ошибку. Попытки подключить любые устройства к шлюзу так же неудачны. Минуту мигает розовый светодиод и получаю отказ.  Пробовал варианты с различными прошивками, как с модами, так и со стоком. Бесполезно.  Где то читал, что при интеграции Z2M происходит автоматическая перепрошивка Zeegbe чипа на протокол EZSP.  Может быть в этом дело, но вот как откатить его назад инфы не нашёл.

**Comment by AlexxIT** [comment]
В последней master версии компонента повышена стабильность этого переключателя. Попробуйте несколько раз. Предварительно перезагрузите шлюз

**Comment by nextboy79** [comment]
Алекс, благодарю вас за ответ. Буду пробовать.

**Comment by nextboy79** [comment]
Спасибо вам за ваши труды и за помощь мне в частности. Шлюз получилось вернуть к жизни по вашему методу.
