### ISSUE TITLE
Bluetooth Door / Window Sensors not working with v1.3.0 - 2021-07-28

### ISSUE THREAD

**Issue by nenadmilano** [AlexxIT/XiaomiGateway3#415]
After updating to v1.3.0 - 2021-07-28 all of my Aqara Door and Window Sensor stopped working, reverting back to 1.2.3 solved the issue.

**Comment by JachinY** [comment]
my door sensor (bluetooth) on 1.2.3version is unavailabke...

**Comment by AlexxIT** [comment]
Fixed in v1.4.1
