### ISSUE TITLE
Bluetooth Device Not Work / Duplicate Alarm

### ISSUE THREAD

**Issue by drako86** [AlexxIT/XiaomiGateway3#416]
After Update 1.2.3 -> 1.3.0 
My Bluetooth device (LYWSDCGQ/01ZM) temperature e umidity Xiaomi non work.
And i have duplicate Alarm (but in state unaviable)

TY

**Comment by Silencer2K** [comment]
> And i have duplicate Alarm (but in state unaviable)

+1

One alarm has a valid domain and is displayed on the integration page, the second is displayed only in the list of entities

Screenshot: https://cloud.mail.ru/public/sFsX/ormWq7TNS

**Comment by dikis-git** [comment]
After updating the integration to the latest version, my devices LYWSD03MMC and LYWSDCGQ/01ZM also stopped working

**Comment by nathbullen** [comment]
Had BLE devices working fine on 1.3.0 but after a power outage my hub rebooted and now they're all unavailable... Strange

**Comment by AlexxIT** [comment]
Should be fixed in v1.4.1. Probably you need reboot gateway and wait some time for collection BLE data
