### ISSUE TITLE
Error Can't send get_properties 

### ISSUE THREAD

**Issue by weiyideai520** [AlexxIT/XiaomiGateway3#417]
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 2021年7月28日 22:24:37 (916 occurrences)
Last logged: 09:08:53

192.168.199.232 | Can't send get_properties [{'did': '1090313358', 'siid': 2, 'piid': 2}, {'did': '1090313358', 'siid': 2, 'piid': 3}, {'did': '1060480130', 'siid': 2, 'piid': 2}, {'did': '1060480130', 'siid': 2, 'piid': 3}]
192.168.199.232 | Can't send get_properties [{'did': '1090313358', 'siid': 2, 'piid': 1}, {'did': '1060480130', 'siid': 2, 'piid': 1}, {'did': '1060478542', 'siid': 2, 'piid': 1}, {'did': '1060269048', 'siid': 2, 'piid': 1}, {'did': '1042682383', 'siid': 2, 'piid': 1}, {'did': '1060477723', 'siid': 2, 'piid': 1}]
192.168.199.52 | Can't send get_properties [{'did': '1090313358', 'siid': 2, 'piid': 1}, {'did': '1060480130', 'siid': 2, 'piid': 1}, {'did': '1060478542', 'siid': 2, 'piid': 1}, {'did': '1060269048', 'siid': 2, 'piid': 1}, {'did': '1042682383', 'siid': 2, 'piid': 1}, {'did': '1060477723', 'siid': 2, 'piid': 1}, {'did': '1060324729', 'siid': 2, 'piid': 1}, {'did': '1060324672', 'siid': 2, 'piid': 1}, {'did': '1041823689', 'siid': 2, 'piid': 1}]
192.168.199.52 | Can't send get_properties [{'did': '1041823689', 'siid': 2, 'piid': 2}, {'did': '1041823689', 'siid': 2, 'piid': 3}]

**Comment by AlexxIT** [comment]
Duplicate #223
