### ISSUE TITLE
插件更新到最新版本后好像小米的网关下的设备延迟很厉害，大家有没有这个问题

### ISSUE THREAD

**Issue by hxck123** [AlexxIT/XiaomiGateway3#418]
插件更新到最新版本后好像小米的网关下的设备延迟很厉害，大家有没有这个问题

**Comment by MaoZ1993** [comment]
更新1.3.0后似乎人体传感器经常丢信息，明明有人移动但是HA里显示没有人移动，上次移动时间是很久之前

**Comment by AlexxIT** [comment]
Please describe the problem in more detail in English
