### ISSUE TITLE
Configuring zigbee2mqtt

### ISSUE THREAD

**Issue by vhsousa** [AlexxIT/XiaomiGateway3#419]
Hi, i'm getting the following error when setting the mode to zigbee2mqtt

Logger: aiohttp.server
Source: custom_components/xiaomi_gateway3/core/utils.py:196

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='master.dl.sourceforge.net', port=443): Max retries exceeded with url: /project/mgl03/zigbee/ncp-uart-sw_mgl03_6_7_8_z2m.gbl?viasf=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ec8a910>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

[zigbee2mqtt.log](https://github.com/AlexxIT/XiaomiGateway3/files/6907668/zigbee2mqtt.log)

**Comment by AlexxIT** [comment]
You have problem with internet on your Hass server. Maybe problem with DNS. It tries to download Zigbee chip firmware

**Comment by AlexxIT** [comment]
It's may be problems with sourceforge site. Some users complain same problem
