### ISSUE TITLE
ZNCLDJ11LM Intelligent Curtain Motor

### ISSUE THREAD

**Issue by joseph2947** [AlexxIT/XiaomiGateway3#42]
Hello: Thank you for your plug-in, it is very good to use! 
But I found that "aqara zigbee curtain motor" is not supported, model: ZNCLDJ11LM.
I very much look forward to adding the device to this plugin in the future.
Attach the debug file of my system
A big thankyou!
[debug.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5273069/debug.txt)

**Comment by AlexxIT** [comment]
You need to enable `debug: mqtt`. Otherwise, the data of the unsupported device is ignored.

**Comment by joseph2947** [comment]
Hi sir:
    The file is as follows
Best regard
[debug2.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5273594/debug2.txt)

**Comment by joseph2947** [comment]
Sorry, I forgot to operate the curtain in the last uploaded log. 
I uploaded the debug file again, 
and this time, between 14:17 and 14:18, 
I used the "Xiaomi App" to operate the curtains "open" and "close".
The file is as follows
Best regard
[debug3.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5273902/debug3.txt)

**Comment by AlexxIT** [comment]
Check latest master version. It can be installed with HACS (reinstall > dropdown > master).
Check if I configured the open / close direction correctly.
Is the "closed" state correct?
Does the opening work for the specified percentage?
Do the open / close / stop buttons work?

**Comment by joseph2947** [comment]
Hi Sir:
  I downloaded the latest file and replaced the "xiaomi_gateway3" file in "custom_components".
And after restarting the system, a curtain motor device was found.
But after I clicked it in, there was no entity.
I downloaded the log and provide it for your review.
20:31~20:32 operate curtains
Thanks again for your quick reply
Best Regards
[debug4.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5276227/debug4.txt)
![1](https://user-images.githubusercontent.com/71556774/94150783-27930d00-feac-11ea-8295-07a4d135a3c1.JPG)
![2](https://user-images.githubusercontent.com/71556774/94150846-3974b000-feac-11ea-8b04-35a717593bf4.png)

**Comment by AlexxIT** [comment]
Please update to master again

**Comment by joseph2947** [comment]
Hi~
It works perfectly.
AlexxIT, you are really amazing!
Thank you for your hard work to solve the problem!
I really admire your superb skills
I will show it to my friends and family。
Best Regards
Joseph

**Comment by charles0103** [comment]
Hi~ AlexxIT
How to show the specified percentage？I can't see it.
thank you!

**Comment by AlexxIT** [comment]
You can create template sensor with motor percentage attribute.

**Comment by charles0103** [comment]
> You can create template sensor with motor percentage attribute.
OK!
Let me try
Thank you!
