### ISSUE TITLE
Connect AQARA TVOC Air Quality Monitor

### ISSUE THREAD

**Issue by Kejszijo** [AlexxIT/XiaomiGateway3#420]
### Discussed in https://github.com/AlexxIT/XiaomiGateway3/discussions/414

<div type='discussions-op-text'>

<sup>Originally posted by **Kejszijo** July 27, 2021</sup>
Hi,

I bought a [AQARA TVOC Air Quality Monitor](https://www.alza.hu/zigbee-levegominoseg-erzekelo-aqara-tvoc-air-quality-monitor-d6519580.htm?kampan=adw_alza_pla_all_smart-shopping-campaign_produkty_smart_c_1032308_AqRAA21023&gclid=Cj0KCQjw3f6HBhDHARIsAD_i3D_nCTt_Z1Sbwr80zpsNIvJfFKvA-aTIfotc0gJ4Bzgy8zCtj2MPRYQaAsGKEALw_wcB) and I want to connect to my gateway 3.
I try this command, but it not connect it.
service: remote.send_command
data:
  entity_id: remote.gatewayID_pair
  command: pair
  device: lumi.airmonitor.acn01

I push the button on the air monitor for 5-10 sec, I see the connect icon, but nothing happened.

Any suggestion?

Thanks!</div>

**Comment by AlexxIT** [comment]
Maybe gateway should have latest firmware to support this device. Maybe Xiaomi account should be connected to China server

**Comment by niceboygithub** [comment]
Use Mi Home app, add temperature/humidity zigbee device. Long press the button of TVOC air monitor  8 seconds and release

**Comment by Kejszijo** [comment]
> Use Mi Home app, add temperature/humidity zigbee device. Long press the button of TVOC air monitor 8 seconds and release

Hi,

Which firmware version do you use? 
I use 1.4.6_0043. Europe region with EU region gateway3 and unfortunately not working this preocess. 
Home app does not offer firmware upgrade.

**Comment by niceboygithub** [comment]
1.5.

**Comment by rezmus** [comment]
@Kejszijo you can't pair this sensor if you use eu region. switch to cn and pair there. you may need firmware update before.

**Comment by Kejszijo** [comment]
> @Kejszijo you can't pair this sensor if you use eu region. switch to cn and pair there. you may need firmware update before.

Hi,

Can I add EU gateway in China region? Or I must buy a CN Gateway?

**Comment by rezmus** [comment]
yes, you can.

**Comment by Kejszijo** [comment]
I use 20 connected sensor with this Gateway in EU region. If I think well and I put my gateway to China region, I must reset my gateway (lose my sensors), connect it in china region again, and I must reconnect all sensors again to gateway and configure with HA. Right?

**Comment by rezmus** [comment]
reset gateway by pressing button for 10s and pair to chinese region. then press button 3 times (trippleclick) and reset tvoc sensor. they should pair. reset hub again and move to eu. no sensors should be lost. btw: tvoc sensor is not supported in mi home so you can only access it from HA.

**Comment by Kejszijo** [comment]
> reset gateway by pressing button for 10s and pair to chinese region. then press button 3 times (trippleclick) and reset tvoc sensor. they should pair. reset hub again and move to eu. no sensors should be lost. you can ofc stay on chinese region if you want.
> 
> btw: tvoc sensor is not supported in mi home so you can only access it from HA.

Thanks, it's works. It forget the devices name after I go back to EU region, but that is the least. :)
I want to use it with HA, I don't use Mi Home app, so this is perfekt for me. 

Information: The sensor works with 1.4.6_0043 firmware.

**Comment by swas** [comment]
> 1.5.
> 
> > > Use Mi Home app, add temperature/humidity zigbee device. Long press the button of TVOC air monitor 8 seconds and release
> > 
> > 
> > Hi,
> > Which firmware version do you use?
> 
> 1.5.0
> 
> > I use 1.4.6_0043. Europe region with EU region gateway3 and unfortunately not working this process.
> > Home app does not offer firmware upgrade.
> 
> wait new firmware release, or use custom firmware upgrade (need notice that EU firmware is signed or not)

Hello!!

I just bought the tvoc sensor but doesn't pair with Mi Home, I reseted the device a lot of times but the gateway 3 (lumi.gateway.mgl03) does not detect it.

My GW firmware version is: 1.5.4_0090


Thanks a lot!
