### ISSUE TITLE
Zigbee2MQTT Problem / Devices no update / Assertion Failed

### ISSUE THREAD

**Issue by colethegamer123** [AlexxIT/XiaomiGateway3#421]
Hello Alex :)

Im using your Zigbee2MQTT integration with my Xiaomi Gateway 3 Multimode Gateway.

Everything was working until a few weeks before, now on the last official version and up2date with official HA OS, Im getting problems.

We had an electrical blackout two times this month, both times all the devices stopped refreshing status, so door sensors and buttons and motion sensors not working, but they are still inside Zigbee2mqtt but without LQI and Battery status. Nothing is working with them no Open/close status changing nothing totally.

In the logs of Z2M I see only this:
Assertion failed
Assertion failed

**Comment by AlexxIT** [comment]
Duplicate #319
