### ISSUE TITLE
Zigbee2mqtt config not working 

### ISSUE THREAD

**Issue by Blade0001** [AlexxIT/XiaomiGateway3#425]
Hi I tried to set up  Zigbee2mqtt swichting from ZHA mode. 

I used the video as manual but somehow the connection snipped is not working in my config. 

I got the following error massage: 

`Fehler beim Speichern der Add-on-Konfiguration, does not match regular expression. Got {'data_path': '/config/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt'}, 'serial': {'port': 'tcp://192.168.1.54:8888', 'adapter': 'ezsp'}, 'advanced': {'log_level': 'info', 'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blocklist': [], 'availability_passlist': []}, 'device_options': {}, 'blocklist': ...`

Do anyone have the same issue?

**Comment by AlexxIT** [comment]
Probably you using very old and unsupported z2m addon
