### ISSUE TITLE
Add Xiaomi Motion Sensor 2 for non China region

### ISSUE THREAD

**Issue by ronyad** [AlexxIT/XiaomiGateway3#427]
Xiaomi Motion Sensor 2 (RTCGQ02LM) not work for non chainise region, hence can't discovered 
Is there anyeway to conncet device to HA without mi app?

**Comment by rezmus** [comment]
it's ble sensor, you must connect it with mi app 1st. google for vevs mod, it will let you pair it on all regions.

**Comment by ronyad** [comment]
Thanks resmus!
I downloaded the app though emulator (BlueStacking)
Still can't added it on my region (Singapore)
It don't show in the new devices, and not discovered
any advise?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
