### ISSUE TITLE
Adds support Aqara Roller Shade E1

### ISSUE THREAD

**Issue by ftlpack** [AlexxIT/XiaomiGateway3#428]
Приветствую! Можно добавить поддержку в Gateway 3 zigbee мотора aqara e1 curtain (ZNJLBL01LM)?

Предоставлю необходимую информацию

**Comment by SadowskiT** [comment]
Xiaomi Gateway 3
New device:
did: lumi.54ef4410001d79eb
mac: 54ef4410001d79eb
model: lumi.curtain.acn002
version: 0.0.0_0024
zb_ver: 3.0
joined_type: 1

Shade was working in version 1.5.1 with firmware 1.4.6_0043 , 
after upgrade to version 1.6.1 and firmware 1.5.0_0102 new device is detected but then it don't shows up on devices list in integration. ( integration reinstalled, multiple HA machine restarts done, repairing process repeated many times )

**Comment by AlexxIT** [comment]
@SadowskiT enable debug logs and show pairing moment. Also check errors in Hass logs

**Comment by SadowskiT** [comment]
Thanks for your reply 
After gateway reset (or two;), by switching gateway to CN, then back to EU in Mi Home app , now it's working like expected.
