### ISSUE TITLE
Please kindly advise how to switch Zigbee2MQTT mode and Original mode in telnet?

### ISSUE THREAD

**Issue by hamwong** [AlexxIT/XiaomiGateway3#437]
Hi, I am sorry, I didn't use HACS, I think I was try run the sh file in /bin and I get into Zigbee2MQTT mode as my device keep offline from Miapp after that, but I didn't realize that as all my zigbee device didn't get offline, as I don't know why I always get offline, I tried run /bin/factory_reset.sh and I get back to MiApp but all my zigbee devices get offline, 

Please kindly advise how can I switch between Zigbee2MQTT mode and Original mode in telnet, Thank you very much.

**Comment by AlexxIT** [comment]
You can ask in this chat https://t.me/xiaomi_gw_v3_hack
