### ISSUE TITLE
Mi Bluetooth BLE devices cannot use trigger conditions during automation

### ISSUE THREAD

**Issue by edoole** [AlexxIT/XiaomiGateway3#438]
My 3 Xiaomi Bluetooth BLE devices cannot use trigger conditions in automation, But in the environmental conditions, the conditions can be selected normally. 
Xiaomi Door Sensor 2 (MCCGQ02HL) 
Xiaomi Motion Sensor 2 (RTCGQ02LM)
 Xiaomi TH Sensor 2 (LYWSD03MMC) .

Is this normal? or should I configure something?

**Comment by edoole** [comment]
Select the state 
No need to write an attribute
from to
on   off 
the test can be used

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
