### ISSUE TITLE
aqara doorlock n200 not function.

### ISSUE THREAD

**Issue by aho206** [AlexxIT/XiaomiGateway3#442]
hi, i notice that aqara doorlock N200 no longer function. ( it was fine and work good before)
is it because update?
how can fix it ?
![doorlock](https://user-images.githubusercontent.com/65076364/131148358-915a0c7a-b1f5-438f-93b4-4a37a3c7f79f.jpg)

**Comment by AlexxIT** [comment]
Have you any other BLE devices?
What update you talking about?

**Comment by aho206** [comment]
currently no other BLE device.
is it becuase of HA update?

**Comment by aho206** [comment]
before the doorlock went unavailable , the gateway disconnected one time. is it possible the cause?

**Comment by AlexxIT** [comment]
Maybe distance between Gateway and door is too big.

Are you using recommended gateway firmware?

**Comment by aho206** [comment]
distance is about 3m without any obstacle.
and the firmware = 1.4.5_0012

**Comment by AlexxIT** [comment]
Firmware not in recommended list

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares
> If you have problems with other firmware, don't even ask to fix it.
