### ISSUE TITLE
Can't pair device

### ISSUE THREAD

**Issue by aferraz** [AlexxIT/XiaomiGateway3#443]
Hi, 
 I have 4 gateway on my home. After an internet outage I lose sensor from one gateway.
After solving the internet problem I had to restart gateway to be able to go back to seeing the sensor values on HA but one of the sensors (temperature / humidity) no longer shows values.
I tried to delete it from the app but now I can't pair new device neither with the app nor with Home assistan.

HA core-2021.8.8 (hassos)
Integration Xiaomi Gateway 3  Version 1.3.0 installed with HACS
lumi.gateway.mgl03 ZNDMWG03LM Firmware: 1.4.6_0012

Someone can help me ?

Thanks 
 Alessandro

**Comment by AlexxIT** [comment]
Sensor with bad battery won't pair with gateway

**Comment by aferraz** [comment]
It's true, battery changet. It work
