### ISSUE TITLE
The manufacturer is an "unknown" device and cannot be displayed on the homekit

### ISSUE THREAD

**Issue by weiyideai520** [AlexxIT/XiaomiGateway3#444]
The manufacturer is an "unknown" device and cannot be displayed on the homekit
--------------
Home Assistant 2021.8.8
--------------
```
Logger: homeassistant.components.homekit
Source: components/homekit/accessories.py:254
Integration: HomeKit (documentation, issues)
First occurred: 10:23:15 (9 occurrences)
Last logged: 10:23:15

Failed to create a HomeKit accessory for light.5ce50ceb6358_light
Failed to create a HomeKit accessory for light.5ce50ceb5eba_light
Failed to create a HomeKit accessory for binary_sensor.54ef44e394a9_smoke
Failed to create a HomeKit accessory for sensor.582d3412ca0e_temperature
Failed to create a HomeKit accessory for sensor.582d3412ca0e_humidity
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 211, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_switches.py", line 105, in __init__
    super().__init__(*args, category=CATEGORY_SWITCH)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 254, in __init__
    model=model[:MAX_MODEL_LENGTH],
TypeError: 'int' object is not subscriptable
```
--------------
```
Logger: custom_components.xiaomi_gateway3.core.mini_miio
Source: custom_components/xiaomi_gateway3/core/mini_miio.py:157
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 10:22:35 (77 occurrences)
Last logged: 10:47:36

192.168.199.52 | Can't send get_properties [{'did': '1090313358', 'siid': 2, 'piid': 2}, {'did': '1090313358', 'siid': 2, 'piid': 3}]
192.168.199.232 | Can't send get_properties [{'did': '1090313358', 'siid': 2, 'piid': 2}, {'did': '1090313358', 'siid': 2, 'piid': 3}]
```
--------------

<a href="https://imgtu.com/i/hlOJXQ"><img src="https://z3.ax1x.com/2021/08/28/hlOJXQ.png" alt="hlOJXQ.png" border="0" /></a>

**Comment by weiyideai520** [comment]
-------
The model needs to be cast to a string here:
https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/core/helpers.py
Please open an issue on the component.
-------
https://github.com/home-assistant/core/issues/55560#issuecomment-912170803

**Comment by AlexxIT** [comment]
You have a lot of unknown devices. It's better to add them to bluetooth.py file. Can you provide company, device name and device model of each? Example:

```
1371: ["Xiaomi", "TH Sensor 2", "LYWSD03MMC"],
```

**Comment by AlexxIT** [comment]
Fixed in v1.4.0

**Comment by weiyideai520** [comment]
# Mesh  water valve 
#model：dwdz.switch.sw0a01
#Desc：Water valve, control water flow switch
4525:["Xiaomi", "Mesh valve", "sw0a01"],
# Mesh Switches
#model：wainft.switch.sw0a01
3150"："["Xinguang","Mesh Switch", "sw0a01"],
#model：lemesh.switch.sw0a01
2007:["Xinguang","Mesh Switch", "DHKG02ZM"],
# Mesh Light
#model：lemesh.light.wy0c07
3164："["Xinguang","Mesh Light", "wy0c07"],

**Comment by AlexxIT** [comment]
@weiyideai520 can you send link or picture for 4525? Interesting how it's looks like

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
