### ISSUE TITLE
BLE Mesh Light brightness is zero

### ISSUE THREAD

**Issue by ernestioo** [AlexxIT/XiaomiGateway3#445]
My BLE mesh light is always showing 0 percents, i am able to control the brightness and color_temp. But seems like after once it reaches the desired level. HA will return to 0%.  (For Example, switch on to 80%, 1 sec later 0% on HA)

**Comment by AlexxIT** [comment]
Show Hass device page

**Comment by ernestioo** [comment]
Here is the image![image](https://user-images.githubusercontent.com/31688296/132106884-27dedd55-fda5-43d0-99a3-1a1d99863aa9.jpeg)

**Comment by AlexxIT** [comment]
Do you know manufacturer, name and model for your device? Example:
```
948: ["Yeelight", "Mesh Downlight", "YLSD01YL"],
```

**Comment by AlexxIT** [comment]
Adds you model to latest master version as Unknown. Should work

**Comment by ernestioo** [comment]
It works now! Thank you!
