### ISSUE TITLE
Invalid entity, xiaomi_gateway3.xx_ararm

### ISSUE THREAD

**Issue by BlaineLi** [AlexxIT/XiaomiGateway3#451]
After the gateway is added, an entity will be added[xiaomi_gateway3.xxx_ararm], and there has been no state. If the alert mode is used, there is a corresponding entity in the device[alarm_control_panel.xxx_alarm]
![image](https://user-images.githubusercontent.com/54876924/132163325-ff8cf2dc-b05e-41d3-ba2d-7bd54adf88e7.png)
![image](https://user-images.githubusercontent.com/54876924/132163380-55845b41-f535-4741-8935-1ec95707cab7.png)
![image](https://user-images.githubusercontent.com/54876924/132163400-1a5bd32c-369b-4923-8ad8-ecc02d1a6f5a.png)
![image](https://user-images.githubusercontent.com/54876924/132163998-ea8e03cc-1a39-40a0-8d29-c510affb5b1f.png)

**Comment by AlexxIT** [comment]
Fixed in v1.4.0
