### ISSUE TITLE
Mijia smart mosquito repellent не управляется через Gateway v3

### ISSUE THREAD

**Issue by L61senko** [AlexxIT/XiaomiGateway3#452]
Mijia smart mosquito repellent автоматически интегрируется через шлюз 3й версии. К сожалению, при этом, можно только узнать его состояние, но не управлять им. 

Создаются 3 объекта
sensor.74a34ad0a309_battery 
sensor.74a34ad0a309_supply показывает "остаток" таблетки в процентах
и
binary_sensor.74a34ad0a309_opening показывает скорее всего включен или выключен

А хотелось бы самому включать/выключать

**Comment by AlexxIT** [comment]
Нельзя. Это старая модель не поддерживает удалённое включение через шлюз. Вот эта новая модель - поддерживает:
https://github.com/AlexxIT/XiaomiGateway3/issues/408
