### ISSUE TITLE
Firmware 1.5.0_0102

### ISSUE THREAD

**Issue by ren9821** [AlexxIT/XiaomiGateway3#453]
Using the latest xiaomigateway3 plug-in, the original gateway was flashed with custom firmware 1.5.0_0026, and then upgraded to 1.5.0_0102 on the Xiaomi app, now Telnet cannot be opened, and the putty prompt: Network error.connection refused
![image](https://user-images.githubusercontent.com/53131748/132784426-e4cc20fd-356d-4aae-a434-0842dd636d02.png)
![image](https://user-images.githubusercontent.com/53131748/132784564-8b3e3b8d-0a9e-4259-a8db-c50c2f5d76ec.png)
![image](https://user-images.githubusercontent.com/53131748/132784503-022869e8-5894-4d71-b96b-9172380bb1f7.png)

**Comment by AlexxIT** [comment]
You need reboot gateway and check MiHome token.

**Comment by NikDevx** [comment]
After update to 1.4.0 or 1.4.1 all accessory not response.
1.3.0 works fine.

**Comment by lesliedu** [comment]
> I was tested on firmware 1.5.0_0102 and 1.5.0_026
> After update to 1.4.0 or 1.4.1 all accessory not response.
> 1.3.0 works fine.

Same As me, 1.4.X can not work

**Comment by ren9821** [comment]
> You need reboot gateway and check MiHome token.

I tried this method, the token is also correct, the homeassistant and gateway are also restarted, but it still doesn't work.

**Comment by ren9821** [comment]
I just tried a newly purchased device. The firmware of the newly purchased device is 1.5.0_026. After upgrading to 1.5.0_0102 on the Xiaomi App, it still cannot be accessed like the screenshot I provided.

**Comment by NikDevx** [comment]
> I just tried a newly purchased device. The firmware of the newly purchased device is 1.5.0_026. After upgrading to 1.5.0_0102 on the Xiaomi App, it still cannot be accessed like the screenshot I provided.

Does MiHome app work with xiaomigateway3?

**Comment by ren9821** [comment]
> > I just tried a newly purchased device. The firmware of the newly purchased device is 1.5.0_026. After upgrading to 1.5.0_0102 on the Xiaomi App, it still cannot be accessed like the screenshot I provided.
> 
> Does MiHome app work with xiaomigateway3?

Normal

**Comment by ren9821** [comment]
Is there a way to solve

**Comment by ren9821** [comment]
> I was tested on firmware 1.5.0_0102 and 1.5.0_026
> After update to 1.4.0 or 1.4.1 all accessory not response.
> 1.3.0 works fine.
1.3.0 still doesn't work

**Comment by ren9821** [comment]
> I was tested on firmware 1.5.0_0102 and 1.5.0_026
> After update to 1.4.0 or 1.4.1 all accessory not response.
> 1.3.0 works fine.

1.3.0 still doesn't work

**Comment by WangRicky** [comment]
> I was tested on firmware 1.5.0_0102 and 1.5.0_026
> After update to 1.4.0 or 1.4.1 all accessory not response.
> 1.3.0 works fine.

upgrade homeassistant 1.4.x works fine

**Comment by NikDevx** [comment]
> > I was tested on firmware 1.5.0_0102 and 1.5.0_026
> > After update to 1.4.0 or 1.4.1 all accessory not response.
> > 1.3.0 works fine.
> 
> upgrade homeassistant 1.4.x works fine

Thanks
That helped

**Comment by qukefu** [comment]
I updated to 1.5.0._0102 from here https://github.com/zvldz/mgl03_fw/tree/main/firmware/custom.

This version shows more stable with zigbee body motion, and telnet password is blank. Everything works well from now.

**Comment by StarokaznikovOleg** [comment]
When switching from firmware 1.4.7_0065 to 1.5.0_0102, the token was changed on the gateway. While I figured it out, I broke my head. No where they write about it.

**Comment by AlexxIT** [comment]
It should not happened. Token changed only when you ADD device to MiHome. Update firmware shouldn't change token

**Comment by Rhylthus** [comment]
Long time user, i was on 1.4.6_0012 FW and everything was fine.

When i see integration update i decide to upgrade FW to match recommanded version 1.5.0._0102 (was done from xiaomi app).

I reboot the gateway and it's not working anymore in HA. In the log i have :

2021-11-20 11:12:01  DEBUG    gateway3      192.168.0.159 | Can't enable telnet
2021-11-20 11:12:35  DEBUG    gateway3      192.168.0.159 | Can't enable telnet
2021-11-20 11:13:09  DEBUG    gateway3      192.168.0.159 | Can't enable telnet

Gateway is still working on mi app. token has not changed and is still the same.

Could you advice what can i do? 

Thanks.

**Comment by AlexxIT** [comment]
Reboot (not reset): gateway, router, hass server. Check IP-address and token

**Comment by AlexxIT** [comment]
Firmware 1.5.0_0102 currently supported
