### ISSUE TITLE
Expected data source not listed  for 

### ISSUE THREAD

**Issue by tikondrus** [AlexxIT/XiaomiGateway3#455]
I try to configure energy monitoring with XiaomiGateway3 but Expected data source not listed

![2021-09-10_16-49-52](https://user-images.githubusercontent.com/34535914/132863793-2af4490f-32f5-49f1-a5a4-5164df753b83.png)

https://www.home-assistant.io/more-info/statistics/
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by NikDevx** [comment]
> I try to configure energy monitoring with XiaomiGateway3 but Expected data source not listed
> 
> ![2021-09-10_16-49-52](https://user-images.githubusercontent.com/34535914/132863793-2af4490f-32f5-49f1-a5a4-5164df753b83.png)
> 
> https://www.home-assistant.io/more-info/statistics/
> https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

https://github.com/AlexxIT/XiaomiGateway3/issues/453

**Comment by tikondrus** [comment]
I've rebooted my GW3 and checked the token. Token is correct. I see the same issue.

**Comment by tikondrus** [comment]
firmware is 1.5.0_0026 (not custom)

**Comment by AlexxIT** [comment]
What energy device do you using?

**Comment by tikondrus** [comment]
I've removed all XiaomiGateway3 integrations and added it againt. Devices were discovered successfully,
I use 
Device info
lumi.plug.mmeu01 ZNCZ04LM
by Xiaomi
Xiaomi Gateway 3
Firmware: 1.0.0_0022

**Comment by tikondrus** [comment]
At this very moment everithing works well. I don't know, what fixed the issue, the new HA or update for Xiaomi integration
![2021-09-23_17-56-26](https://user-images.githubusercontent.com/34535914/134531389-b3f3f1d6-7d67-48de-8834-c8b9267bd206.png)

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
