### ISSUE TITLE
command data when pairing Aqara Precision Motion Sensor

### ISSUE THREAD

**Issue by ldwnt** [AlexxIT/XiaomiGateway3#456]
![image](https://user-images.githubusercontent.com/7655486/132868501-caded20e-672d-4102-a540-5510cb101c0a.png)
1. Above is the screenshot of service call. Shall I keep line 1 to 3 (service, target.device_id) generated automatically?
2. Is the entity_id in the red rect the one I shall fill in data.entity_id?
![image](https://user-images.githubusercontent.com/7655486/132869305-9574eea4-b52e-445f-80c1-0e80f4c35921.png)
3. Shall I use lumi.motion.agl04 as data.device?

**Comment by AlexxIT** [comment]
You not need to use service for pairing official Xiaomi device. Just pair it from MiHome. Or toggle pair switch.

**Comment by ldwnt** [comment]
> You not need to use service for pairing official Xiaomi device. Just pair it from MiHome. Or toggle pair switch.

Correct me if I'm wrong, but I hear Aqara Precision Motion Sensor is supposed to work with Aqara gateways such as M1S, and can't be used with Xiaomi Gateway 3 in Mi home. Have you paired it with Mi home successfully before? If yes, may I use the fast paring mode (shortly press the gateway button for 3 times and then long press it for one time) to pair the sensor?

**Comment by rezmus** [comment]
trippleclick and reset motion sensor. it will pair on chinese region.

**Comment by ldwnt** [comment]
> trippleclick and reset motion sensor. it will pair on chinese region.

Thank you very much, I manage to pair the sensor. But my automation fails to trigger when sensor state changes. Where may I find the correct values for the state of Aqara Precision Motion Sensor?

![UN@1VC{PB74P26E~23WF3GO](https://user-images.githubusercontent.com/7655486/132985229-f702e1e9-0c59-4524-8a36-23f1c8b40f4f.png)

**Comment by ldwnt** [comment]
> > trippleclick and reset motion sensor. it will pair on chinese region.
> 
> Thank you very much, I manage to pair the sensor. But my automation fails to trigger when sensor state changes. Where may I find the correct values for the state of Aqara Precision Motion Sensor?
> 
> ![UN@1VC{PB74P26E~23WF3GO](https://user-images.githubusercontent.com/7655486/132985229-f702e1e9-0c59-4524-8a36-23f1c8b40f4f.png)

I try removing value "off" from the "from" input box and the automation works.
