### ISSUE TITLE
occupancy_timeout not working as expected with Aqara Precision Motion Sensor

### ISSUE THREAD

**Issue by ldwnt** [AlexxIT/XiaomiGateway3#457]
The occupancy_timeout is set to 5s for testing purpose, and initial state is 'off'. Then I walk into detection zone and keep moving all the time. However:

1) After the sensor captures my movement and the state is changed to 'on', it is always changed to 'off' after 5s, no matter how I move in front of the sensor.

2) After it's changed to 'off', it keeps ignoring my movements for about 1min and then captures my movement again.

![image](https://user-images.githubusercontent.com/7655486/132986699-c94b071d-83b9-4cf3-a1ac-e37111843cb1.png)

**Comment by AlexxIT** [comment]
It's better you to Google how motion sensor works.

**Comment by ldwnt** [comment]
> It's better you to Google how motion sensor works.

Do you mind give some hints? Previously I used Xiaomi Motion Sensor 2, its logic is the same as the default mode described in your picture below
[https://github.com/AlexxIT/XiaomiGateway3/raw/master/occupancy_timeout.png](url)

**Comment by ldwnt** [comment]
> This sensor has same logic. It can detect motion once in X seconds. For latest sensors this value can be changed in MiHome. For old sensors this value was 60 seconds and cannot be changed software. But you can change it hardware.

Thank you for elaboration. What I can't figure out is: the sensor is always "off" after X seconds, while I keep moving all the time. It's like this:

T: motion detected, state changed to on
[T, T+X seconds]: me moving all the time
T+X seconds: state changed to _off_

**Comment by AlexxIT** [comment]
You should set occupancy_timeout more than X. Example 1.5*X or 2*X. So sensor will have a chance extend on state

**Comment by ldwnt** [comment]
> You should set occupancy_timeout more than X. Example `1.5*X` or `2*X`. So sensor will have a chance extend on state

I think my previous test case includes the 2X scenario: say occupancy_timeout = 60s, and I was moving starting from T thru T+30s till T+60s, yet the state changed to off at T+60s.

**Comment by AlexxIT** [comment]
Maybe you sensor has X=60. So `occupancy_timeout` should be 120s.
