### ISSUE TITLE
Xiaomi Mesh Triple Wall Switch(ZNKG03HL/ISA-KG03HL)  new  firmware is unavailable

### ISSUE THREAD

**Issue by nesror** [AlexxIT/XiaomiGateway3#458]
XiaomiGateway3 firmware 1.5.0_0102
ZNKG03HL/ISA-KG03HL firmware:2.x.x(support converted to Button) is unavailable; firmware:1.x.x is ok;
now this all entity is :
10:10:26 switch.28d12723bde4_left_switch  unavailable
10:10:26 switch.28d12723bde4_left_switch  off
10:10:20 switch.28d12723bde4_left_switch  unavailable
10:10:20 switch.28d12723bde4_left_switch  on
10:09:12 switch.28d12723bde4_left_switch  unavailable

**Comment by nesror** [comment]
now I delete
[switch.py](https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/switch.py) line 76,77
```
else:
    self.device['online'] = False
```

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
