### ISSUE TITLE
Unable to display Battery Level 

### ISSUE THREAD

**Issue by terenceng81** [AlexxIT/XiaomiGateway3#459]
Hi, I am using version v1.5.0_0026.

I have three same model LYWSD02MMC devices, this is a digital clock which able to provide 4 info below:
1. Bluetooth BLE Icon: XXX seconds ago
2. Battery Level: XX %
3. Humidity: XX.X %
4. Temperature: XX.X °C.

I encountered some issues thus I deleted and readded this integration.

Somehow 1 of the devices cannot display item 2 Battery level, I tried to reload again but the same device still does not show this entity. I do not encounter this issue on the other two same model devices...

How do I refresh and get it to display again? it was working well before I re-add the integration?

Thanks in advance,
Terence

**Comment by AlexxIT** [comment]
Try latest master version

**Comment by terenceng81** [comment]
> Try the latest master version

I am already running the latest version, besides remove and reinstall the components, anything I could do?

I tried the method above once, renaming the entities is pain, thus asking is there any other way.

**Comment by AlexxIT** [comment]
Are you sure you using master version? Not release

**Comment by terenceng81** [comment]
> Are you sure you using master version? Not release

Yes, I reinstalled with the "Master" version, not 1.5.0, rebooted, , the issue still persist.

![image](https://user-images.githubusercontent.com/56790753/136244460-ea49ce74-88cc-494f-84ed-e2dece0b7bc8.png)

![image](https://user-images.githubusercontent.com/56790753/136244524-89976771-db9d-4282-84cf-90a15240b15b.png)

**Comment by terenceng81** [comment]
Yes, I think is bad firmware, as it I resetup HA, configured Gateway3, still the same issue, case closed.

**Comment by futonsleeper** [comment]
yo, just did a search to see if anyone could tell me why this device has 2 battery's

I'm guessing you might have the same question as I believe your fault is due to this device having 2 battery's?

I have just one battery in say the moment and it's functioning fine.
I'm gonna use 2 but my question is still there.

perhaps you could try removing a battery to see if you get data that way?
