### ISSUE TITLE
[New feature] Bluetooth Mesh Devices Dashboard

### ISSUE THREAD

**Issue by dobl1** [AlexxIT/XiaomiGateway3#462]
Hi,

Is it possible to create a dashboard (like those for Zigbee and BLE) for device monitoring for bluetooth mesh devices ?
I don't know if it's a technical limitation.

Regards and thanks for the amazing work 🦾 !

**Comment by AlexxIT** [comment]
Mesh devices doesn't has any useful information. Maybe this will be changed in next integration version

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
