### ISSUE TITLE
[Technical question] Load average interpretation (ZNDMWG03LM)

### ISSUE THREAD

**Issue by dobl1** [AlexxIT/XiaomiGateway3#463]
Hello

I have a Load Avg of about 2.6 on my gateway (Xiaomi Gateway 3 ZNDMWG03LM), I know that if I compare this with values ​​for linux servers, it is rather bad sign and means that there is pending processes and the gateway is slow.

![image](https://user-images.githubusercontent.com/9740002/133443838-776e90e7-2be9-4cd9-a216-324570b9e49f.png)

Is this normal and everyone has the same?
Is there a way to improve this?

Thank you !

**Comment by vturekhanov** [comment]
In short, it is OK if your gw3 firmware version is 1.4.7_xxxx or 1.5.0_xxxx. And there is no need to improve it.

**Comment by AlexxIT** [comment]
I think issue can be closed
