### ISSUE TITLE
Add "Change to wireless switch" support please

### ISSUE THREAD

**Issue by gmugu** [AlexxIT/XiaomiGateway3#467]
https://user-images.githubusercontent.com/8317478/134141680-2b3b41a6-3539-4201-9c43-4ef15ee7e13f.png

Mi Home recently added the function of "Change to wireless switch", hoping to be integrated into homeassistant, thanks!

**Comment by AlexxIT** [comment]
Show model from device page

**Comment by rezmus** [comment]
it looks like E1 wall switch switches. you can check siid/piid in specs (disable/enable button) and send cmd from integration.

**Comment by AlexxIT** [comment]
@gmugu model?

**Comment by xrh0905** [comment]
> @gmugu model?

@AlexxIT I have one of the BLE Mesh Switch that support this function. Model read from HA is `ZNKG01HL`

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
