### ISSUE TITLE
No battery after update to 1.5.0

### ISSUE THREAD

**Issue by Vovan177** [AlexxIT/XiaomiGateway3#470]
Hi.
After update to 1.5.0 Aqara temperature and humidity sensor (WSDCGQ11LM) havn't battery sensor. It became 'unknown'.

**Comment by vtkach7** [comment]
Same issue here. 
Firmware - v1.4.6_0012

**Comment by sstu** [comment]
One gateway on the firmware v1.4.6_0012 and the same problem, the second gateway on the firmware v1.4.6_0026 and has no problems.

**Comment by Vovan177** [comment]
Yeh, firmware v1.4.6_0012. At 1.4.1 battery was seen.

**Comment by sstu** [comment]
upgrade firmware v1.4.6_001 to v1.5.0_0102, solved the problem

**Comment by AlexxIT** [comment]
Problem only on Gateway fw v1.4.6. Fixed in latest master version.

**Comment by Zuz666** [comment]
> Problem only on Gateway fw v1.4.6. Fixed in latest master version.

Typo! Must be:
```
        ['8.0.2001', 'battery_percent', 'battery', None],
```

**Comment by AlexxIT** [comment]
No problem here. We use battery param only for old firmware. Because it doesn't have voltage param
