### ISSUE TITLE
disable zigbee signal of Xiaomi Gateway v3

### ISSUE THREAD

**Issue by pilot1981** [AlexxIT/XiaomiGateway3#477]
it's possible to disable zigbee signal of Xiaomi Gateway v3?

**Comment by AlexxIT** [comment]
You can kill zigbee app manually if you want. I don't plan to include this feature

**Comment by pilot1981** [comment]
How I can kill it? I don’t understand

**Comment by AlexxIT** [comment]
Connect to gateway via telnet

**Comment by pilot1981** [comment]
So, there is a command do use via CLI? You can say command to use?

**Comment by Stooovie** [comment]
I use the Gateway for BLE Mesh functionality only, I would also like an option to disable Zigbee so it doesn't interfere with my CC2562 stick. Thanks.

**Comment by AlexxIT** [comment]
@Stooovie you can enable ZHA mode. So without ZHA client zigbee chip won't work

**Comment by Stooovie** [comment]
But how?

**Comment by AlexxIT** [comment]
Yes. It is
