### ISSUE TITLE
Can't request MIoT API /home/device_list, Can't login to MiCloud

### ISSUE THREAD

**Issue by zubikovap** [AlexxIT/XiaomiGateway3#478]
После каждой перезагрузки Home Assistant вылазит две ошибки, при этом интеграция авторизована через e-mail и прекрасно отдаёт информация о устройствах MiCloud.
В чём может быть проблема?

Logger: custom_components.xiaomi_gateway3.core.xiaomi_cloud
Source: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:169
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 20:49:21 (1 occurrences)
Last logged: 20:49:21
Can't request MIoT API /home/device_list
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 169, in request
    assert resp['code'] == 0, resp
AssertionError: {'code': 3, 'message': 'auth err'}

Logger: custom_components.xiaomi_gateway3
Source: custom_components/xiaomi_gateway3/__init__.py:166
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 20:49:23 (1 occurrences)
Last logged: 20:49:23
Can't login to MiCloud

**Comment by AlexxIT** [comment]
Duplicate #504
