### ISSUE TITLE
Support new device: Lock MJZNMSQ01YD (BLE)

### ISSUE THREAD

**Issue by chimcanhcut1112** [AlexxIT/XiaomiGateway3#481]
can you support mjznmsq01yd ble xiaomi lock youth lite device ?

**Comment by AlexxIT** [comment]
Do you have it?

**Comment by chimcanhcut1112** [comment]
> Do you have it?

Yes, i'm using

**Comment by chimcanhcut1112** [comment]
[](url)

> And this lock is not supported? Do you see it in the Hass? Do you have other BLE devices in the Hass?

I don't know this not support or support? Link image screenshot [https://imgur.com/a/EwjJwkr](url)

Yes, I have two devices BLE, Sensor Door with Qing Clock, it's work smoothy

Thank you for listen.

**Comment by AlexxIT** [comment]
Can you see it in MiHome in Gateway BLE devices page?

**Comment by chimcanhcut1112** [comment]
> Can you see it in MiHome in Gateway BLE devices page?

Yes, i see it.

**Comment by AlexxIT** [comment]
Model 1257

**Comment by AlexxIT** [comment]
Are you still here?

**Comment by chimcanhcut1112** [comment]
> Are you still here?

I'm sorry, i'm here.
i'm check again, don't show state close/open. 
always show open

**Comment by AlexxIT** [comment]
Enable logs in integration settings. Do different actions with lock. And show logs

**Comment by krzakx** [comment]
Hi all.
I've just purchased this Lock and going to contribute in investigation soon. 
Unfortunalty I don't have any gateway device, do you think that it would be any posibility to connect it off-cloud throuought BLE into HA?

**Comment by krzakx** [comment]
wright, so already have this device in my hand and made some attempt to extract BLE encryption KEY unfortunalty without succes.
So would like to assets if getting it integrated throughout Xiaomi Gateway would be a "workaround" for me. What Gateway would you recommend to buy? ZNDMWG03LM??
