### ISSUE TITLE
How to upgrade firmware when firmware lock was turned on?

### ISSUE THREAD

**Issue by sthorley** [AlexxIT/XiaomiGateway3#483]
Hi, I had a Gateway 3 (lumi.gateway.mgl03) running 1.4.7_0160 that was working well with this integration. As it was working well I enabled the firmware lock. At some point it stopped working and the now when I try to load the integration it gives the error below.
`WARNING (192.168.0.173_main) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.0.173 | Can't send set_ip_info {'ssid': '""', 'pswd': '123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd'}`
I notice v1.5.0_0102 is now the recommended/supported version, but when I attempt to update in the mihome app it says it's running the latest version (probably because I'd previously firmware locked it). 

How can I go about getting this up and working again?

**Comment by AlexxIT** [comment]
Firmware lock don't break connection to gateway. In some regions, MiHome does not offer updates to the latest firmware. Usually it works well in the Chinese region

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
