### ISSUE TITLE
Some alarm_panel not updated in ha when clicked

### ISSUE THREAD

**Issue by ptbsare** [AlexxIT/XiaomiGateway3#485]
![InShot_20211018_184120243](https://user-images.githubusercontent.com/3147576/137716474-17a43061-3f86-428f-b850-dddff5ace50f.gif)
Devices respond fine. But the states in HA are not updated no matter how long you wait.
As you can see in the gif, some works well (HA2 HA4 HA5) while some don't(HA1 HA3).
fw version 1.4.6 0012

**Comment by ptbsare** [comment]
It seems that enabling ble mesh gateway support and also enabling ble device support in the integration config solves the issue.

**Comment by AlexxIT** [comment]
Check MiHome tokens and if gateways using shared network with Hass. Alarm mode using miio protocol.
Enable debug logs and check there

**Comment by ptbsare** [comment]
Alarm works flawlessly in v1.6.2.
