### ISSUE TITLE
Support new device: Xiaomi TH model XMWSDJ04MMC (BLE)

### ISSUE THREAD

**Issue by axa4953** [AlexxIT/XiaomiGateway3#490]
Hi team,

I have been able to successfully integrate a V3 Gateway (EU) with latest firmware (v1.5.0_0102) into HomeAssistant but cannot see the newly released Xiaomi Temperature and Humidity sensor (XMWSDJ04MMC) in the integrated device & entities. 

Thus, I assume it’s not supported yet. 

It would be great if support can be added sometime in the future; and I’ll be happy to beta test or help where I may can. 
Great work you and team have done already, congratulations and well done

**Comment by dentra** [comment]
Additional info, look at constants `MIID_MIAOMIAOCE_XXX` and their description at https://github.com/dentra/esphome-components/blob/master/components/miot/miot_spec.h#L607

**Comment by rezmus** [comment]
```
prop.2.1003 (Battery Level) uint8 = eid 18435 (0x4803)
event.2.1001 (Low Battery) = eid 18945 (0x4a01)
prop.3.1001 (Temperature) float = eid 19457 (0x4c01)
prop.3.1008 (Relative Humidity) float = eid 19464 (0x4c08)
```

**Comment by AlexxIT** [comment]
Added support. Will be in next beta/release version
