### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by adisik** [AlexxIT/XiaomiGateway3#493]
The component "Xiaomi Gateway 3" asked to create a new request with this error :

`panic: runtime error: index out of range [1] with length 1

goroutine 10 [running]:
encoding/binary.littleEndian.Uint16(...)
    encoding/binary/binary.go:53
github.com/AlexxIT/gw3/gap.ParseScanResponse({0x4c2000, 0x17, 0x104})
    github.com/AlexxIT/gw3/gap/gap.go:109 +0x81c
main.btchipProcessExtResponse({0x4c2000, 0x1e, 0x104})
    github.com/AlexxIT/gw3/btchip_reader.go:218 +0x370
main.btchipReader()
    github.com/AlexxIT/gw3/btchip_reader.go:125 +0x7f8
created by main.main
    github.com/AlexxIT/gw3/gw3.go:55 +0x104`

**Comment by AlexxIT** [comment]
Wrong project
