### ISSUE TITLE
Z2M - Map does not populate link between coordinator and end devices since 1.6.0

### ISSUE THREAD

**Issue by Wh1terat** [AlexxIT/XiaomiGateway3#495]
Hi,

Since update to 1.6.0 rc1 (now on rc2), when running with z2m the map does not populate the links between the coordinator (gateway) and end devices - but does to routers.

Everything still works fine and end devices are still connected, just doesn't display on map.

Is this related to the ezsp firmware update? Anyone else seen this?

![Screenshot_2021-10-29_11-50-54](https://user-images.githubusercontent.com/1288525/139422885-05af21a9-3b5f-494e-a52e-836fff1dab98.png)

![Screenshot_2021-10-29_11-51-52](https://user-images.githubusercontent.com/1288525/139422896-60ba1cef-4572-4e96-928f-7bbdf6e6dbd3.png)

**Comment by AlexxIT** [comment]
zigbee2mqtt support the EFR32 chip in experimental mode. It is not recommended to use the gateway in this mode. Write to the zigbee2mqtt project about any issues
https://www.zigbee2mqtt.io/guide/adapters/#experimental
