### ISSUE TITLE
After update to new version 1.6 all buttons and sensors conectet to gateway are unavailable.

### ISSUE THREAD

**Issue by dartek66** [AlexxIT/XiaomiGateway3#496]
After update to new version 1.6 all buttons and sensors conectet to gateway are unavailable.
Error:
2021-10-30 14:17:51 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway3] Gateway 192.168.1.157 firmware 1.4.6_0043 unsupported.

Befor update all worked.
How can I back to old version component?
Without automations my house is death.

**Comment by vturekhanov** [comment]
You have 2 options:
1. Install latest stable component release (1.5.1) using HACS or manually.
2. Upgrade gw3 firmware.

PS: carefully read release notes, especially BREAKING CHANGES part.

**Comment by AlexxIT** [comment]
Old gateway firmwares doesn't support in new component versions
