### ISSUE TITLE
Please support the Light Sensor GZCGQ01LM

### ISSUE THREAD

**Issue by slydiman** [AlexxIT/XiaomiGateway3#5]
Please support the Light Sensor GZCGQ01LM

**Comment by AlexxIT** [comment]
Waiting for shipment

**Comment by fishbone-git** [comment]
I have one of these and would also like to see support.  If it helps, while you are waiting, I can send a sample payload from the internal MQTT

**Comment by AlexxIT** [comment]
I took it from the post office today

**Comment by fishbone-git** [comment]
great. They payload is slightly different as it's not the 0.1.85 codes like the rest.  siid 2 is the illuminance and siid 3 I believe is the battery voltage.

**Comment by AlexxIT** [comment]
Supported in latest release
