### ISSUE TITLE
小米手环6为何又检测不到了？

### ISSUE THREAD

**Issue by zyunling** [AlexxIT/XiaomiGateway3#500]
在上周的时候，我用这个配合多模网关，BLE检测到很多蓝牙设备出来，
包括几个小米手环6，和很多附近的 Apple iBeacon

设置NR流，判断小米手环是否到家，正常用了几天
有一天网关丢失蓝牙设备后，手环等BLE 实体再也没有出现了
重启多模网关后，其他的蓝牙设备、zigbee设备都正常连接好了，就差手环再也没有检测到了，很奇怪 。

**Comment by AlexxIT** [comment]
Please write in english
