### ISSUE TITLE
1.6.0-rc2: mosquitto_pub is started every x seconds

### ISSUE THREAD

**Issue by dominikkarall** [AlexxIT/XiaomiGateway3#501]
Hi,

on my gateway the process _mosquitto_pub -t log/ble -l_ is started every few seconds. As a lot of those processes are running after a few hours the gateway gets very sluggish. I think this patch causes that issue:
https://github.com/AlexxIT/XiaomiGateway3/blob/f3ee90247d208379bea4063f814e8f75a6fa70a3/custom_components/xiaomi_gateway3/core/shell.py#L57

**Comment by AlexxIT** [comment]
Fixed. Will be in next release 2.0

Anyway you have some problems with Bluetooth chip. BT app constantly crashing.
