### ISSUE TITLE
new Firmware 1.5.1_0032

### ISSUE THREAD

**Issue by nesror** [AlexxIT/XiaomiGateway3#503]
zigbee device is work;
~~but ble and mesh device is not work;~~
this firmware  when open Use storage in memory [ADV] ,ble and mesh device is not work；

**Comment by Alxspb** [comment]
For me, after upgrading from 1.4.6_xxxx to 1.5.0_0102 all my Bluetooth mesh devices disappeared from mi home app and are unavailable in HA

**Comment by Alxspb** [comment]
В Mi home при взаимодействии с настройками Bluetooth-mesh сыпятся ошибки: "Не удалось получить статус", "Сбой операции"
Шлюз продолжает игнорировать все Bluetooth-mesh устройства, даже после прошивки mod firmware 1.5.0_0102 поверх стоковой. 
Пробовал добавить заново, но устройства не ищутся даже после сброса.

Буду пробовать даунгрейд до 1.4.6_x и ставить старую версию компонента. С последними релизами дела не задались (обновился из-за сообщения о прекращении поддержки 1.4.6)

**Comment by AlexxIT** [comment]
Added to latest master
