### ISSUE TITLE
Component architecture

### ISSUE THREAD

**Issue by dominikkarall** [AlexxIT/XiaomiGateway3#509]
Hi,
it would be great if future architectural changes could remove all hass dependencies in the core. I'm using the code of this module for an own module running in FHEM (fhempy).
The best solution would be to split the module itself in a XG3 package and XG3 custom component so that all non-hass users could use the XG3 package, but I would already be happy with the removal of hass dependencies in the core.

Thank you very much for your work!!

**Comment by AlexxIT** [comment]
Maybe in the second version of the component you will find something useful. There are very big changes. There will be a beta soon.
