### ISSUE TITLE
FW won't update past 1.4.6_0043

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/XiaomiGateway3#510]
Mi Home app says 1.4.6_0043 is the latest update. Even with FW Lock disabled and gateway rebooted. I can't update this integration to the new 1.6.0 (from 1.5.1) because FW < 1.4.7 isn't supported. What else can I check?

**Comment by neKola-ru** [comment]
I have the same problem

**Comment by gnezdin** [comment]
Same but with 1.4.6_0012.
Latest Android app 6.12.706

**Comment by ghostsam45** [comment]
same problem

Last firmware 1.4.6_0012

**Comment by retrostrobe** [comment]
I used [this approach](https://github.com/zvldz/mgl03_fw/tree/main/firmware) to update via telnet. Running custom v1.5.1_0032 now.

**Comment by gnezdin** [comment]
> I used [this approach](https://github.com/zvldz/mgl03_fw/tree/main/firmware) to update via telnet. Running custom v1.5.1_0032 now.

Many thanks! Successfully updated to 1.5.0_0102

**Comment by Stooovie** [comment]
Thank you! Can you guys report back if the update of the HA integration works fine? Thanks.

**Comment by havrancek** [comment]
I've done it a hard way, now every Ble sensor is unavailable. what now?

**Comment by AlexxIT** [comment]
All of you using not China MiHome server?

**Comment by retrostrobe** [comment]
I'm on the China server, but didn't feel confident to upgrade through MiHome in case the new firmware would lock the gateway or disable telnet. So, I put on a custom one instead.

**Comment by AlexxIT** [comment]
You can always read Integration docs before update. If you see a version without any warnings, it is safe to update. Don't upgrade if you don't see a version in the description.

**Comment by retrostrobe** [comment]
> Can you guys report back if the update of the HA integration works fine?

So far so good (for me at least). Zigbee and BLE devices are still in HA and functional.

**Comment by Stooovie** [comment]
Thank you guys, everything works as expected, update was easy via the telnet route.

**Comment by JaCoLJcL** [comment]
@AlexxIT but why now old version of integration my 1.4.6_0043 gate working great and now I have error Gateway 192.168.0.61 firmware 1.4.6_0043 unsupported?

I use all my ble temp from Your integration and now is gone and I dont have time to rewrote my code to xiaomi miot...

**Comment by Stooovie** [comment]
> @AlexxIT but why my old version of integration my 1.4.6_0043 gate working great and now I have error Gateway 192.168.0.61 firmware 1.4.6_0043 unsupported?
> 
> I use all my ble temp from Your integration and now is gone and I dont have time to rewrote my code to xiaomi miot...

FW under 1.4.7 is not supported. Update to 1.5.0[ via telnet ](https://github.com/zvldz/mgl03_fw/tree/main/firmware)and then update the HA component. It's a quick procedure.

**Comment by rezmus** [comment]
they host ota with new fw only on cn region. latest fw on other regions is 1.4.6_0012. global version of gw is sold with 1.4.6_0043. in this case app shows this version as latest (on regions other than cn). if you want latest fw (stock/custom) flash it via telnet or reset hub with 10s button press (wifi reset), connect to cn, update as many times as it offers new fw, reset again and connect back to region you use. you won't loose any connected sensors or local automation scenes. only custom sensor names and room assignment can be lost in mijia app. before update disable fw lock and read github issues about fw version you are going to update. make sure it is safe to use particular fw version. in the future some bugs, used as entry point for this integration, can be closed.

**Comment by AlexxIT** [comment]
@JaCoLJcL Because the new firmware has very modified files on the gateway. It's hard to support outdated versions. And from integration version 1.6.0, older gateway firmware is not supported. This is written in the update and it is written in the readme.

**Comment by JaCoLJcL** [comment]
@Stooovie @rezmus @AlexxIT ok i see.

But now, which version i must download to use gate? Moded or stock version and what is the diferenc
![putt](https://user-images.githubusercontent.com/70702183/142721125-c6fd0c31-b12c-4082-ab00-090e619cb6da.png)
e?

**Comment by AlexxIT** [comment]
@JaCoLJcL all answers in docs
- https://github.com/AlexxIT/XiaomiGateway3#requirements
- https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares

**Comment by AlexxIT** [comment]
So. I plan to bring back very limited support for older firmwares in the next version of the component. But I don't recommend using them anyway.

**Comment by gladiangel** [comment]
hi .... my app tells me to upgrade to version 1.4.7_0160 can i upgrade ... ??

**Comment by karolzamosc** [comment]
@AlexxIT I can not add gateway (lumi.gateway.mgl03) with firmware 1.5.1_0032, I got error: "Invalid command to open telnet protocol"...

**Comment by AlexxIT** [comment]
I think issue may be closed
