### ISSUE TITLE
Unknown error in MiCloud devices info

### ISSUE THREAD

**Issue by retrostrobe** [AlexxIT/XiaomiGateway3#511]
In MiCloud devices info, I can get info for all devices except lumi.gateway.v3. I noticed that the 'LAN key' was in the log, so perhaps there's something not right about it. Please see [log on pastebin](https://pastebin.com/jDxG0uxe).

v1.5.1 works (values removed):

![Screen Shot 2021-11-20 at 5 30 49 PM copy](https://user-images.githubusercontent.com/19503690/142714627-9f106def-f142-4e7c-9aeb-046c59f71be8.png)

v1.6.0 triggers an Unknown error occurred:

![Screen Shot 2021-11-20 at 5 13 26 PM](https://user-images.githubusercontent.com/19503690/142714659-553e6488-9b12-409a-befa-a88b33409c66.png)

Cheers.

**Comment by AlexxIT** [comment]
Please check latest master version. If it fix problem

**Comment by retrostrobe** [comment]
Yes, it works! Thank you.
