### ISSUE TITLE
Firmware 1.4.6_0012 unsupported

### ISSUE THREAD

**Issue by n0is3r** [AlexxIT/XiaomiGateway3#512]
After update to v1.6.1 - 2021-11-20 with HACS

Logger: custom_components.xiaomi_gateway3.core.gateway3
Source: custom_components/xiaomi_gateway3/core/gateway3.py:832
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 12:09:22 (6 occurrences)
Last logged: 12:14:23

Gateway 192.168.10.106 firmware 1.4.6_0012 unsupported

**Comment by oizo64** [comment]
Update to v1.5.0_0102 
https://github.com/zvldz/mgl03_fw/tree/main/firmware
