### ISSUE TITLE
Zigbee devices are unavailable after upgrade to v1.6.1

### ISSUE THREAD

**Issue by akunia** [AlexxIT/XiaomiGateway3#514]
Hi,
After upgrade to v1.6.1 , I disabled and enabled the "Mode ZHA or zigbee2mqtt [ADV]" , even reinstalled ZHA integration, rebooted the gateway and HA, but still no devices are visible. I'm on 1.5.0_0102 #20210816 .
I attach the result of sudo tail -F /usr/share/hassio/homeassistant/home-assistant.log |grep -E 'zigpy|zha' > 1.6.1.log after ZHA integration reload.
https://pastebin.com/Ncx2KC0e

**Comment by AlexxIT** [comment]
You need to enable integration debug logs (in integration settings), disable and enable mode zha, and show logs.

**Comment by akunia** [comment]
Hi @AlexxIT ,
Please find debug window content:
`2021-11-21 08:54:05  DEBUG    gateway3      192.168.3.132 | MQTT | ble/a4c1383a88fd b'{"humidity":78,"temperature":18.7,"battery":100}'
2021-11-21 08:54:05  DEBUG    gateway3      192.168.3.132 | MQTT | log/miio b'\x1b[0;32m2021:11:21:15:54:04.574 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.3.18hcvivl05g00","mac":"A4:C1:38:3A:88:FD","pdid":1371},"evt":[{"eid":4102,"edata":"0c03"}],"frmCnt":166,"gwts":1637481243},"id":15618} length:192 bytes\x1b[0m'
2021-11-21 08:54:05  DEBUG    gateway3      192.168.3.132 | Process BLE {'dev': {'did': 'blt.3.18hcvivl05g00', 'mac': 'A4:C1:38:3A:88:FD', 'pdid': 1371}, 'evt': [{'eid': 4102, 'edata': '0c03'}], 'frmCnt': 166, 'gwts': 1637481243}
2021-11-21 08:55:04  DEBUG    gateway3      192.168.3.132 | MQTT | log/ble b'{"did":"blt.3.18hcvivl05g00","eid":4100,"edata":"bc00","pdid":1371,"seq":168}'
2021-11-21 08:55:04  DEBUG    gateway3      192.168.3.132 | Process BLE Fix {'did': 'blt.3.18hcvivl05g00', 'eid': 4100, 'edata': 'bc00', 'pdid': 1371, 'seq': 168}
2021-11-21 08:55:04  DEBUG    gateway3      192.168.3.132 | MQTT | ble/a4c1383a88fd b'{"humidity":78,"temperature":18.8,"battery":100}'
2021-11-21 08:55:25  DEBUG    gateway3      192.168.3.132 | MQTT | log/miio b'\x1b[0;32m2021:11:21:15:55:23.385 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"event.gw.heartbeat","params":[{"free_mem":4640,"ip":"192.168.3.132","load_avg":"1.19|1.38|1.40|3\\/86|15580","rssi":80,"run_time":88643,"setupcode":"790-83-679","ssid":"Do4g","tz":"GMT1"}],"id":15632} length:210 bytes\x1b[0m'
2021-11-21 08:55:25  DEBUG    gateway3      192.168.3.132 | gateway <= {'free_mem': 4640, 'ip': '192.168.3.132', 'load_avg': '1.19|1.38|1.40|3/86|15580', 'rssi': 80, 'run_time': 88643, 'setupcode': '790-83-679', 'ssid': 'Do4g', 'tz': 'GMT1'}
2021-11-21 08:55:25  DEBUG    gateway3      192.168.3.132 | Gateway time offset: -1.2783386707305908
2021-11-21 08:55:34  DEBUG    gateway3      192.168.3.132 | MQTT | log/ble b'{"did":"blt.4.147pud6qggg00","eid":4102,"edata":"9f02","pdid":1371,"seq":147}'
2021-11-21 08:55:34  DEBUG    gateway3      192.168.3.132 | Process BLE Fix {'did': 'blt.4.147pud6qggg00', 'eid': 4102, 'edata': '9f02', 'pdid': 1371, 'seq': 147}
2021-11-21 08:55:34  DEBUG    gateway3      192.168.3.132 | MQTT | ble/a4c138675c13 b'{"humidity":67,"temperature":19.1,"battery":100}'
2021-11-21 08:55:34  DEBUG    gateway3      192.168.3.132 | MQTT | log/miio b'\x1b[0;32m2021:11:21:15:55:33.824 [D] miio_client_func: ot_agent_recv_handler_one(): fd:9, msg:{"method":"_async.ble_event","params":{"dev":{"did":"blt.4.147pud6qggg00","mac":"A4:C1:38:67:5C:13","pdid":1371},"evt":[{"eid":4102,"edata":"9f02"}],"frmCnt":147,"gwts":1637481333},"id":15635} length:192 bytes\x1b[0m'
2021-11-21 08:55:`

**Comment by AlexxIT** [comment]
I can't see, that you disable and enable ZHA mode. Updating should take about a minute for each on/off switch

**Comment by akunia** [comment]
Sorry,
The right logs: https://pastebin.com/raKfd6xX
Enabled  at 2021-11-21 09:15:09

**Comment by akunia** [comment]
Looks like NCP problem:
`  new 1 (24 hits)
	Line 57: 2021-11-21 09:12:47  DEBUG    utils         Try to update Zigbee NCP to version v6.6.2
	Line 59: 2021-11-21 09:12:50  DEBUG    utils         NCP flash error: Traceback (most recent call last):
	Line 64: 2021-11-21 09:12:50  DEBUG    utils         Try to update Zigbee NCP to version v6.6.2
	Line 66: 2021-11-21 09:13:00  DEBUG    ezsp          NCP first line error: b''
	Line 72: 2021-11-21 09:13:02  DEBUG    utils         NCP state: normal, version: NCP v6.7.10-167
	Line 72: 2021-11-21 09:13:02  DEBUG    utils         NCP state: normal, version: NCP v6.7.10-167
	Line 75: 2021-11-21 09:13:14  DEBUG    ezsp          NCP first line error: b'S\xca`z\xa3\xc1G@q\xb8;r:q\xb0k\x1c\xe88\xaec\xc4\x1eS\xee\xe7z\xa3\xc1G@q\xb8;r:q\xb0k\x1c\xe88\xaec\xc4\xfe'
	Line 76: 2021-11-21 09:13:14  DEBUG    utils         NCP state: None, version: NCP v6.7.10-167
	Line 76: 2021-11-21 09:13:14  DEBUG    utils         NCP state: None, version: NCP v6.7.10-167
	Line 77: 2021-11-21 09:13:14  DEBUG    utils         Try to update Zigbee NCP to version v6.6.2
	Line 79: 2021-11-21 09:13:19  DEBUG    utils         NCP state: boot, version: Gecko Bootloader v1.8.0
	Line 1530: 2021-11-21 09:13:57  DEBUG    ezsp          Rebooting NCP...
	Line 1541: 2021-11-21 09:14:04  DEBUG    utils         NCP state: normal, version: NCP v6.6.2-126
	Line 1541: 2021-11-21 09:14:04  DEBUG    utils         NCP state: normal, version: NCP v6.6.2-126
	Line 1571: 2021-11-21 09:14:10  DEBUG    gateway3      192.168.3.132 | MQTT | gw/588E81FFFEF7CC0C/settings b'{"z3GatewayHostVersion":"1.14","ncpVersion":"6.6.2-126.32","networkUp":true,"networkPanId":"0x9DC1","radioTxPower":7}'
	Line 1587: 2021-11-21 09:15:24  DEBUG    utils         Try to update Zigbee NCP to version v6.7.10
	Line 1593: 2021-11-21 09:15:25  DEBUG    utils         NCP state: normal, version: NCP v6.6.2-126
	Line 1593: 2021-11-21 09:15:25  DEBUG    utils         NCP state: normal, version: NCP v6.6.2-126
	Line 1596: 2021-11-21 09:15:33  DEBUG    utils         NCP state: boot, version: Gecko Bootloader v1.8.0
	Line 3157: 2021-11-21 09:16:13  DEBUG    ezsp          Rebooting NCP...
	Line 3160: 2021-11-21 09:16:20  DEBUG    ezsp          NCP init error
	Line 3161: 2021-11-21 09:16:20  DEBUG    utils         NCP state: None, version: Gecko Bootloader v1.8.0
	Line 3162: 2021-11-21 09:16:20  DEBUG    utils         Try to update Zigbee NCP to version v6.7.10
	Line 3169: 2021-11-21 09:16:30  DEBUG    ezsp          NCP first line error: b''`

**Comment by AlexxIT** [comment]
Try to restart gateway and repeat on/off ZHA mode

**Comment by AlexxIT** [comment]
`NCP state: normal, version: NCP v6.6.2-126` - this is good line in the end of change mode.
v6.6.2 - ZHA disabled, v6.7.10 - ZHA enabled

**Comment by akunia** [comment]
Yes I still have errors: https://pastebin.com/bKBf48pX

**Comment by igelbro** [comment]
Подтверждаю. После обновления с 1.5.1 на 1.6.1 отвалились все Zigbee устройства. Откат на 1.5.1 работоспособность не восстанавливает.

**Comment by rereduck** [comment]
Hello,
Same problem for me after update with Bluetooth devices.

**Comment by baspeters** [comment]
I'm not entirely sure if it is related, but after updating from v1.5.1 to v1.6.1 my Zigbee devices became unavailable as well. After a lengthy debugging session I found out what the problem was (in my case).

The v1.6.1 version propagates a new Zigbee firmware to the Gateway. My Xiaomi Gateway 3 came with firmware version v1.5.0_0026 and from the Xiaomi Home app, this version could not be updated to a later version (e.g. Latest Version). With the following Open Telnet command I got the device to work when I first started with this integration:
```
{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}
```
The update to v1.6.1 (in combination with the device firmware v1.5.0_0026) botched the EZSP connectivity. Disabling the ZHA/Z2M toggle did not revert properly, but yielded an "unknown" error without actually reverting anything. Reverting to v1.5.1 also didn't work. Switching back from ZHA mode to "MI Home" mode produced the same "unknown" error. So at this point, neither the updated nor the previously working version was functioning properly anymore.

After checking a lot of logs and trying several things, I noticed that the documentation of this integration specifically said that v1.5.0_0102 is the only *properly* supported version. I then decided to upgrade my Xiaomi Gateway 3 to this version. More specifically, I used the mgl03_1.5.0_0102_mod20210816 version and upgraded through the telnet method.

After restarting HA it did not immediately made a change. The ZHA integration was still in an error state. I removed the Xiaomi Gateway 3 integration from HA (keeping ZHA, because all my devices are configured in there). I proceeded to re-install and configure the Xiaomi Gateway 3 and used the "default" Telnet command:
```{"method":"enable_telnet_service","params":""}```
After enabling the "Mode ZHA or zigbee2mqtt [ADV]" toggle, the Gateway got updated correctly this time and the ZHA integration could connect just fine to the EZSP instance on port 8888.

It appears that the Zigbee firmware update introduced in v1.6 is not entirely compatible with Gateways that run on other versions than v1.5.0_0102.

**Comment by akunia** [comment]
Thank you for your feedback @baspeters .
I have 1.5.0_0102 , so even that version is not well supported by 1.6.x
I could reflash the firmware, but I home Alex will provide us a fix

**Comment by baspeters** [comment]
I'm positive @AlexxIT tested it on the (stock) 0102 firmware, but it just seems to be a bit finicky.

**Comment by AlexxIT** [comment]
The modified firmware is almost identical to the original firmware and should not affect the ZHA mode switch

**Comment by akunia** [comment]
> The modified firmware is almost identical to the original firmware and should not affect the ZHA mode switch

How to interpret your message @AlexxIT ?
Are you going to do something with the issue or we have to reflash / reinstall the integration?

**Comment by AlexxIT** [comment]
@akunia I don't see any problems in your latest logs. Your ZHA mode enabled fine. Just restart Gateway and Hass and check

**Comment by akunia** [comment]
Well, 
It works when I  pair again the devices, so closing the ticket.

**Comment by AlexxIT** [comment]
Please feedback later if ZHA works fine for you. How long you using it? How many devices? Is any problems with stability?

**Comment by rereduck** [comment]
Last update fix the issue for me. Thanks

**Comment by AlexxIT** [comment]
@rereduck so you using unsupported gateway firmware

**Comment by rereduck** [comment]
You're right, I'm using 1.4.6. I'll update to 1.5 asap. Thanks

**Comment by akunia** [comment]
> Please feedback later if ZHA works fine for you. How long you using it? How many devices? Is any problems with stability?

Sure Alex , I will.
I'm using ZHA integration since few months and the only problem I had was the Aquara cube that was not always responsive. 
I will report you in few weeks
