### ISSUE TITLE
Xiaomi Light Sensor

### ISSUE THREAD

**Issue by aferraz** [AlexxIT/XiaomiGateway3#516]
Home Assistent: core-2021.11.4
                           supervisor-2021.10.8
                           Home Assistant OS 6.6
Gateway: ZNDMWG03LM Firmware: 1.5.1_0032
Xiaomi Gateway 3 for Home Assistant: v1.6.1

Hi all,
 from last update all my Xiaomi Light Sensor (lumi.sen_ill.mgl01 GZCGQ01LM)  do not work from Home Assistant while they work from the Mi Home App.
Does anyone have the same problem?

Regards Alessandro

**Comment by akunia** [comment]
No problem with other Zigbee devices ?
I have lost all of them... https://github.com/AlexxIT/XiaomiGateway3/issues/514

**Comment by aferraz** [comment]
@akunia other devices work fine

**Comment by akunia** [comment]
So not the same issue as mine

**Comment by baspeters** [comment]
I actually have GZCGQ01LM sensors and they work fine with v1.6.1. I'm using them with ZHA though.

I did have issues with v1.6.1 and my specific firmware version of the Gateway and I see that you are also not using the "recommended" v1.5.0._0102 version. Maybe it is worth checking out... https://github.com/AlexxIT/XiaomiGateway3/issues/514

**Comment by aferraz** [comment]
Thanks @baspeters,
you are right, I do a test with the other firmware version

**Comment by aferraz** [comment]
Hi,
 with recommended firmware version Xiaomi Light Sensors work fine.

Thanks
