### ISSUE TITLE
FW v1.5.1_0032 Stock Cannot open telnet.

### ISSUE THREAD

**Issue by gorskygriff** [AlexxIT/XiaomiGateway3#518]
After update XG3 to 1.6.1 version I had to update Firmware from 1.4.6_0012 stock to 1.5.1_0032 stock (cause it listed as supported). After reboot gateway has Unavailable state and also I cannot connect to it by telnet.

**Comment by AlexxIT** [comment]
Check gateway IP, token, reboot gateway, Hass and router.

**Comment by gorskygriff** [comment]
Gateway, Hass and local machine are placed in different subnets. All devices are reachable. Xiaomi Home is still working normally.
I have deleted GW from Hass and then tried to add again, it is said "Can't connect to gateway".
I tried to enable telnet on GW with php miio-cli command from local machine, it is said "Device is unreachable".
Can anyone confirm that "open telnet command" works on 1.5.1__0032 Stock firmware?

**Comment by AlexxIT** [comment]
I can confirm that you don't read requirements section in readme:
https://github.com/AlexxIT/XiaomiGateway3#requirements

Any miio cmd shouldn't work from different subnets

**Comment by gorskygriff** [comment]
Thank you!
1. Reconfigured wifi settings.
2. Connected with the same subnet from local windows computer, with changed quotes in "open telnet command" as described in https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709#gistcomment-3721492
3. Upgraded with custom firmware 1.5.1_0032.
4. Now Hass can reach GW from different subnet.

**Comment by AlexxIT** [comment]
But some gateway functionality needs miio cmd. Alarm or Mesh devices shouldn't work
