### ISSUE TITLE
Stop Working 

### ISSUE THREAD

**Issue by Rawq86** [AlexxIT/XiaomiGateway3#52]
Integration has stopped working. Reinstalling doesn’t help, Re-adding results in an error
ERROR: Unable to discover the device. Helps

**Comment by Rawq86** [comment]
Home Assistant Core 0.116.0 work but Home Assistant Core 0.116.1 not work

**Comment by AlexxIT** [comment]
There is no such error in my component.

**Comment by Rawq86** [comment]
This is probably a HA bug as it works on the older version. THX

**Comment by AlexxIT** [comment]
Maybe there is a more detailed error?

**Comment by gleba** [comment]
Привет @AlexxIT, после отключения электричества шлюз стабильно не поднимается. Сперва я его сбрасывал и всё переустанавливал чтоб заработало. Потом в новом сбое менял поехавший ip шлюза в `/config/.storage/core.config_entries. А в последнем сбое ip не менялся но кнопки стали реагировать только после того как открыл в телефоне Mi Home. Мистика, о таком грамотный баг-репорт не составить. В логах HA ошибок нет.
Думаю эта проблема с холодным стартом когда Wi-Fi и инет поднимается с минутным запозданием ещё проявится, попробую нарыть конкретику. Может подскажешь куда смотреть.

**Comment by AlexxIT** [comment]
Про интернет с запозданием - #156
