### ISSUE TITLE
Opple Six Button (WXCJKG13LM) button 5/6 Identify as 3/4 (2.0 Alpha 1/2)

### ISSUE THREAD

**Issue by bluefoxlee** [AlexxIT/XiaomiGateway3#520]
Opple Six Button (WXCJKG13LM) button 5/6 Identify as 3/4 after update to V2.0 Alpha 1/2.
Downgrade back to 1.6.1 fixes the issue.
Firmware:  1.5.1_0032

**Comment by oscrey** [comment]
I have the same problem with Opple Six Button on firmware 1.5.0_0026. 
Fixed by adding an external converter:

`from custom_components.xiaomi_gateway3.core.converters.devices import *

class ZAqaraOppleConv(Converter):
    zigbee = "multistate_input"
    map = {0: HOLD, 1: SINGLE, 2: DOUBLE, 3: TRIPLE, 255: RELEASE}

    def decode(self, device: "XDevice", payload: dict, value: Any):
        button = value["endpoint"]
        value = self.map.get(value["present_value"], UNKNOWN)
        payload[self.attr] = f"button_{button}_{value}"

DEVICES = [{
    "lumi.remote.b286opcn01": ["Aqara", "Opple Two Button", "WXCJKG11LM"],
    "lumi.remote.b486opcn01": ["Aqara", "Opple Four Button", "WXCJKG12LM"],
    "lumi.remote.b686opcn01": ["Aqara", "Opple Six Button", "WXCJKG13LM"],
    "required": [ZAqaraOppleConv("action", "sensor"), Battery],
    "optional": [ZigbeeStats, BatteryPer],
}] + DEVICES
`

**Comment by AlexxIT** [comment]
Fixed in latest branch. You may remove external converter

**Comment by bluefoxlee** [comment]
@AlexxIT Test latest converter build, confirmed.  Thank you.
