### ISSUE TITLE
Cant enable pair mode after switch to z2m mode.

### ISSUE THREAD

**Issue by kuduacz** [AlexxIT/XiaomiGateway3#523]
Update xiaomi gateway 3 to latest firmware via telnet.
Switch to z2m mode on configuration.
And now to add zigbee device like aqara door sensor or motion sensor.
But cant enable pair mode. 
![9CBB7124-322B-4163-BF3B-44861BCADE21](https://user-images.githubusercontent.com/77231628/143005718-122b2790-456b-4035-ae66-9f53c610a8f4.png)
How to pair devices?

**Comment by zvldz** [comment]
You need to pair via z2m, not via component

**Comment by kuduacz** [comment]
Permint_join od true on cofiguration.yaml

Try to reset door sensor by press reset button for 10 sec.

But nothing show on zigbee2mqtt panel.
Canon You tell me step by step what i have to do to pair devices?

**Comment by zvldz** [comment]
Go to z2m web interface.
Enable 'Permit join' if is not enabled.
Press button for 10 seconds on sensor(blink blue).
Watch logs.
and press button on sensor every 2-3 seconds until interview is finished

**Comment by zvldz** [comment]
z2m sure worked with gw3 ?

**Comment by kuduacz** [comment]
![53E13965-FAB5-4779-B007-C848F459FEC2](https://user-images.githubusercontent.com/77231628/143009513-01c0a8e8-b00e-4601-a4eb-def9cdd3dd4b.png)
Preet
![A303A6E0-ED40-4F11-8741-5C6622FFECCD](https://user-images.githubusercontent.com/77231628/143009528-8e8be19c-e6c7-4493-b16a-c80a7542b34d.png)

Preety sure yes. But have not sure that i correctly config zigbee2mqtt addon.

**Comment by zvldz** [comment]
Did you write in configuration.yaml z2m settings for gw3 ?

**Comment by zvldz** [comment]
or in z2m addon settings

**Comment by kuduacz** [comment]
Yes.
Replace serial: with
Port:x.x.x.x:888
Adapter: ezsp
Like on screenshot.
![Uploading 424CAACE-40E1-416C-A26C-39C01E60B584.png…]()

**Comment by zvldz** [comment]
Serial should look like this
```

**Comment by kuduacz** [comment]
Serial:
   port: tcp://192.168.5.122:8888
   adapter: ezsp

**Comment by zvldz** [comment]
You need to look why z2m cannot connect.
Maybe port 8888 is not open or zigbee firmware has not changed.
Try rebooting gateway3 as well.

**Comment by zvldz** [comment]
What version of component ?
Maybe port is not 8888

**Comment by zvldz** [comment]
Although port should be 8888, I was wrong

**Comment by kuduacz** [comment]
Disable adguardhome and try

**Comment by kuduacz** [comment]
Nothing changed:
![Uploading BD1D3718-CD10-4BD0-A295-7BC830A4FD6D.png…]()

**Comment by kuduacz** [comment]
![9C50737B-43E8-4107-BD25-31B0442DA1B4](https://user-images.githubusercontent.com/77231628/143014869-027c41de-9ffc-4d54-8479-3bf5f37fb573.png)

**Comment by kuduacz** [comment]
![C0A95BBA-6B17-4F3F-83A3-78BDC166BA8E](https://user-images.githubusercontent.com/77231628/143015026-70281305-c1e1-48d5-b8cc-b74c467fcf4f.png)

![BAFB2CE1-E39A-40AB-9DA2-1A0CBF7150BD](https://user-images.githubusercontent.com/77231628/143015035-39b87152-325e-4f24-ae39-c83cc9187314.png)


Nothing changed

**Comment by zvldz** [comment]
You can try connecting gw3 to ZHA.
z2m is not recommended for use with  gw3
https://github.com/AlexxIT/XiaomiGateway3/tree/converters#zigbee2mqtt-mode

**Comment by kuduacz** [comment]
Yep. On ZHA mode work well.
But why it wont work on z2m mode.?

**Comment by AlexxIT** [comment]
> Serial: port: tcp://192.168.5.122:8888 adapter: ezsp

Serial should be lower case

**Comment by kuduacz** [comment]
serial is in lower case.
it seems like zigbee2mqtt wont start:
 `[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[19:07:21] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[19:07:22] INFO: MQTT available, fetching server detail ...
[19:07:22] INFO: MQTT server settings not configured, trying to auto-discovering ...
[19:07:23] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[19:07:23] INFO: MQTT credentials not configured, trying to auto-discovering ...
[19:07:23] INFO: Configuring'addons' mqtt user
[19:07:23] INFO: Previous config file found, checking backup
[19:07:23] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[19:07:23] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:07:24] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js`

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
