### ISSUE TITLE
Sonoff TH01 (SNZB-02) not reporting temperature/humidity to 2.0a2+

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#528]
Using converters branch from GitHub current version.

Added to ```devices.py```:
```py
}, {
    "TH01": ["Sonoff", "Temperature/Humidity Sensor", "SNZB-02"],
    "support": 5,
    "required": [
        ZTemperatureConv("temperature", "sensor"),
        ZBatteryConv("battery", "sensor"),
    ],
    "optional": [ZigbeeStats],
}, {
```

After that I joined device - it happens Ok, zigbee/battery/temperature entities created. 
Temperature entity have no ```temperature``` word in friendly name, probably just too long.
![image](https://user-images.githubusercontent.com/15225823/143237236-25b9e47d-ed7a-4baf-a4ab-9bdb12f48e99.png)

Actually temperature seen on screenshot is wrong and NOT changing for a while.
During 30min+ TH01 not sent any temperature update, despite it definitely changed by placing/removing on heat source.

Here is a log grepped for device IEEE:
[ha_2.0a_th01.txt](https://github.com/AlexxIT/XiaomiGateway3/files/7595591/ha_2.0a_th01.txt)
See no messages at all, so IMHO this is not parsing issue.

P.S. Info about _battery, probably already known.
![image](https://user-images.githubusercontent.com/15225823/143238177-c07140e1-2144-40df-85b7-ccde59a78ad3.png)

```txt
2021-11-24 13:59:37,584 192.168.1.16 [ZIGB] 0x00124b00222e938e (0x23d9) recv {'endpoint': 1, 'cluster': 'power', 'command': 'Command.Report_Attributes', 'battery_voltage': 28}
2021-11-24 13:59:37,619 192.168.1.16 [ZIGB] 0x00124b00222e938e (0x23d9) recv {'endpoint': 1, 'cluster': 'power', 'command': 'Command.Report_Attributes', 'battery_percentage_remaining': 101}
```
^^ this change _battery state & attribute, but only battery_voltage not change attribute:
```txt
2021-11-24 14:19:44,095 192.168.1.16 [ZIGB] 0x00124b00222e938e (0x23d9) recv {'endpoint': 1, 'cluster': 'power', 'command': 'Command.Report_Attributes', 'battery_voltage': 28}
```

**Comment by AlexxIT** [comment]
Device should have config. Many binds and reports. I'll add later
https://github.com/Koenkk/zigbee-herdsman-converters/blob/54b6c6bda94ec095b6728e0292e0619143efed57/devices/sonoff.js#L105

**Comment by AlexxIT** [comment]
Adds support. Will be in next beta/release version
