### ISSUE TITLE
No ZigBee devices were found in Zha mode

### ISSUE THREAD

**Issue by froggyfly** [AlexxIT/XiaomiGateway3#53]
Hello,

According to the video, I switched my gateway to ZHA mode,
Before switching to ZHA, there was an aqara D1 wall switch (with neutral wire ) on my device,

After switching to ZHA mode,  The D1 wall swtich will appear itself,

I tried to pair a Gledopto ZigBee rgbcct controller (GL-C-008) and found no device. 
My pairing steps: ZHA integrations page-Configure- Click on the plus button at the bottom right corner- page says seaching-reset my device.

I also try to reset my aqara D1 wall switch which would automatically appear, also didn't get anything on the seaching page, No device be found.

I'm runing a hass.io 0.114.4 on ubuntu 20.04 x64 pc.
That would be great if any help,
And thanks for the XiaomiGateway3, It's a very helpful component!

**Comment by AlexxIT** [comment]
I wrote in readme that the devices will not be transferred automatically. They appeared in my video because I had previously configured ZHA. ZHA is in a very early stage of development and may take a long time to search for devices. You need to try again.

**Comment by froggyfly** [comment]
> I wrote in readme that the devices will not be transferred automatically. They appeared in my video because I had previously configured ZHA. ZHA is in a very early stage of development and may take a long time to search for devices. You need to try again.

Hello AlexxIT,

This is strange that the Aqara D1 switch was automatically appear in ZHA mode as soon as I switching the gateway mode to ZHA.
I try to manually delete the switch at ZHA's page, researching can't find it again, and Gledopto controller has never appeared

Try to manually delete the D1 switch, research can't find it again, and Gledopto controller has never appeare.
https://zigbee.blakadder.com/Gledopto_GL-C-008.html

**Comment by froggyfly** [comment]
After I putting the Gledopto controller very near the getway, it can be paired now!
