### ISSUE TITLE
sensor.illuminance lumi.sen_ill.mgl01 GZCGQ01LM

### ISSUE THREAD

**Issue by ghostsam45** [AlexxIT/XiaomiGateway3#531]
brightness sensor much less precise since deposit 1.6.2

I also specify that I have upgraded the firmware 1.5.1_0032

https://ibb.co/6gSB9Vh

**Comment by ghostsam45** [comment]
2021-11-25 13:37:40  DEBUG    gateway3      192.168.1.34 | lumi.4cf8cdf3c7d0ded lumi.sen_ill.mgl01 <= {'0.3.85': 166} [0.01]

mi home android :

https://ibb.co/dp80scb

Home assistant :

https://ibb.co/BqwzMB2

**Comment by zvldz** [comment]
Change firmware of gw to 1.5.0_0102
and it will work.

**Comment by ghostsam45** [comment]
Thanks zvldz,  it works

**Comment by ilkanaev** [comment]
done and well working :-).

Thank you very much for your work and quick response!!!

**Comment by G-Christ** [comment]
Is downgrading the gateway firmware the only solution?
If so how can I do the downgrade?

**Comment by zvldz** [comment]
> If so how can I do the downgrade?

https://github.com/zvldz/mgl03_fw/tree/main/firmware

**Comment by G-Christ** [comment]
Thanks @zvldz,  It works and I get illuminance updates right away. :)

Battery stíll doesn't update. Is this a known issue, or is there a fix for that too?

**Comment by zvldz** [comment]
> Battery stíll doesn't update. Is this a known issue, or is there a fix for that too?

Both should have worked.
I think the problem is in fw, we have to wait for a newer one and then see what happens.

**Comment by HepoH3** [comment]
It seems that problem take a place after upgrading to 2nd version of the component even on 1.5.0_0102's version firmware. Can anyone confirm that?

**Comment by ghostsam45** [comment]
> It seems that problem take a place after upgrading to 2nd version of the component even on 1.5.0_0102's version firmware. Can anyone confirm that?

I did not have any problem following the update, the data is uploaded 5-10 minutes later without restarting

**Comment by HepoH3** [comment]
> > It seems that problem take a place after upgrading to 2nd version of the component even on 1.5.0_0102's version firmware. Can anyone confirm that?
> 
> I did not have any problem following the update, the data is uploaded 5-10 minutes later without restarting

Yup in the daylight it give normal values (about 100). I was checking at the night while turn on the light in the room and sensor gave value 20 which lead me to suspicion that problem get back. It's kinda odd that my room light give 5 times less illuminance than faint winter morning light.

**Comment by slakouz** [comment]
> Battery stíll doesn't update. Is this a known issue, or is there a fix for that too?
I see same issue for battery (illuminance working fine). Paired 2 new sensors to my 2 gateways and both still show Unknow value for Battery

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
