### ISSUE TITLE
Increase update frequency of Temperature & Humidity (LYWSDCGQ01ZM)

### ISSUE THREAD

**Issue by petermcandrew** [AlexxIT/XiaomiGateway3#533]
I'm finding that this sensor doesn't update frequently enough as im using it to control my heating.  Ideally an update every 1 minute would be ideal.  Is is possible to increase frequency?

![image](https://user-images.githubusercontent.com/846573/143500858-37d172f7-282c-4863-9074-ecec3dc6bfcd.png)

**Comment by AlexxIT** [comment]
Gateway firmware? Integration version?

**Comment by petermcandrew** [comment]
Gateway has just been updated to Firmware: 1.5.0_0102
Integration is v1.6.2

I have seen some improvement after updating, see below, but there are still times when I won't get an update for 10 minutes. 
I'm going to try out some Aqara devices tomorrow, so will see if this make a difference.

<img width="1426" alt="Screenshot 2021-11-26 at 20 10 58" src="https://user-images.githubusercontent.com/846573/143626727-25c9aa26-5ade-4c88-9972-85a61c3aa0da.png">

**Comment by AlexxIT** [comment]
Check distance between gw and sensor. Maybe problem with radio

**Comment by xrh0905** [comment]
What's the frequency in MiHome APP?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
