### ISSUE TITLE
Add support for Aqara H1 EU switches with neutral

### ISSUE THREAD

**Issue by shift-del1** [AlexxIT/XiaomiGateway3#537]
Issue "[Add support for Aqara H1 EU switches #374](https://github.com/AlexxIT/XiaomiGateway3/issues/374)" added support for WS-EUK01 and WS-EUK02 only (no neutral). Can you please add the same for switches with neutral wire? Thank you.

https://zigbee.blakadder.com/Aqara_WS-EUK03.html
https://zigbee.blakadder.com/Aqara_WS-EUK04.html

**Comment by AlexxIT** [comment]
Will be in 2.0 release
