### ISSUE TITLE
Add support for Aqara D100 BLE Door Lock

### ISSUE THREAD

**Issue by AngeloEyez** [AlexxIT/XiaomiGateway3#538]
Can Aqara D100 door lock be added to support list?
Currently I add the following line to bluetooth.py and works fine.

    # MiBeacon from official support
    3051: ["Aqara", "Door Lock D100", "ZNMS20LM"],   

thanks a lot!

**Comment by AlexxIT** [comment]
Thanks. Will be in version 2.0
