### ISSUE TITLE
ZNDMWG03LM on version 1.4.5_0012 - how to get to 1.4.6_0012?

### ISSUE THREAD

**Issue by agmaq** [AlexxIT/XiaomiGateway3#54]
Helo @AlexxIT, 

I bought the Xiaomi Gateway 3 from China and it has the fw version: 1.4.5_0012.
I used the Packet Sender Tool to obtain the token but unfortunately, I am not able to register the Gateway in the HA - the error says "ERROR: No response from the device".

I read your attention note that only firmwares v1.4.6_0012 and v1.4.6_0030 are supported. Since I am on the version 1.4.5_0012 and the Xiaomi Home app suggests me to update to the latest version 1.4.5_0016 (only?), I wanted to ask you how can I get to the version v1.4.**6**_0012? Or did not you mean v1.4.**5**_0012 instead? 

I really do not want to "try" if I can get to the higher version once I update to 1.4.5_0016 as the Xiaomi Home app suggests. What is your recommendation? 

Thank you in advance for your response. 

AG

**Comment by rezmus** [comment]
after you update to 1.4.5_0016 it will offer another ota. some updates must be done one by one.

**Comment by AlexxIT** [comment]
As @rezmus said - you can safely upgrade 1.4.5_0012

**Comment by agmaq** [comment]
Sorry guys for my late response. 
I tried that as you helped me and boom... it works very nice now!!!

Thanks you a lot!
