### ISSUE TITLE
[Feature request] Support effect_list of light

### ISSUE THREAD

**Issue by shin3c** [AlexxIT/XiaomiGateway3#541]
Hi, is it possible to add support to effect_list of light (Xiaomi Mesh)?

I've tired adding it for light (pid: 3164) in bluetooth.py. Then with my limited knowledge of Python, I find this function is not enabled in light.py, but I don't know how to modify it. More precisely, I don't know how to deal with list type variables. 

![effec_list](https://user-images.githubusercontent.com/94421978/144346262-f39e757f-147b-4057-aed4-4da522701527.png)

Thank you for your attention.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
