### ISSUE TITLE
How to get BLE device‘s mac address or did from Home Assistant?

### ISSUE THREAD

**Issue by TioaChan** [AlexxIT/XiaomiGateway3#542]
Hi,my mi gateway3 has linked lots of ble devices, and I want to get one of them's log from `Xiaomi Gateway3 Debug` page.
![image](https://user-images.githubusercontent.com/8370450/144395870-9cf1deb2-9998-4c25-92a3-49dbd7f2bf16.png)

But there are lot's of logs in debug pages and I can not find the target device.
![image](https://user-images.githubusercontent.com/8370450/144396933-4d3e5fad-93bd-4815-a6bc-25f6e8788a63.png)

So,how to get the target device's  did or mac address to find interrelated logs？Thanks.

**Comment by zvldz** [comment]
mac is in the attributes of *_ble entities

**Comment by TioaChan** [comment]
> mac is in the attributes of *_ble entities

thanks!
