### ISSUE TITLE
Disconnecting the internet causes problems

### ISSUE THREAD

**Issue by FiftyFour7250** [AlexxIT/XiaomiGateway3#545]
In version 1.5.1 and earlier, it was cool that when the Internet loss, and accordingly Mi Cloud with the gateway and sensors did not work, the status "Unavailable" appeared on the sensors in HA. After looking at the log, you could see that something happened, or even get notifications about that. But in the latest versions, the loss of the Internet is not displayed in any way. Absolutely. Devices are not available, but they just show the latest status. Moreover, in some version of the latest - after the Internet was restored, the sensors did not even work until restart HA.

**Comment by AlexxIT** [comment]
This is big #530 
Already fixed in v1.6.4
