### ISSUE TITLE
occupancy_timeout for BLE?

### ISSUE THREAD

**Issue by echupin** [AlexxIT/XiaomiGateway3#547]
Использую датчик движения qingping (bluetooth).
Время обнаружения по умолчанию 90 секунд.
Можно ли изменять это время подобно тому, как это делается в zigbee (occupancy_timeout) ?
Спасибо.

**Comment by AlexxIT** [comment]
Настройка occupancy_timeout для всех датчиков аналогична, описана в документации и не зависит от технологии датчика
