### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by Hi-hass** [AlexxIT/XiaomiGateway3#548]
ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'xiaomi_gateway3' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by Hi-hass** [comment]
## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.9.0-rc7-aml-s812
arch | armv7l
timezone | Asia/Shanghai

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by zvldz** [comment]
So update the component, you have a very old version
