### ISSUE TITLE
Why we need ZHA?

### ISSUE THREAD

**Issue by Kirmas** [AlexxIT/XiaomiGateway3#55]
Please provide a little more information, what are the pros and cons of ZHA? What should someone new choose?

Пожалуйста расскажи какие плюсы и минусы у ZHA? Что выбрать новичку?

**Comment by AlexxIT** [comment]
Read this article first (russian) https://habr.com/ru/post/519644/

Xiaomi Gateway by default supported only Xiaomi/Aqara zigbee devices and 7 IKEA models.
With this hack # 44 you can add some more "simple" bulbs, switches and relays from third parties.

ZHA is a large python library that communicates with zigbee devices on its own and can theoretically support more devices. But it is in active development. And it may not work very well.

**Comment by AlexxIT** [comment]
If this problem still actual - you may reopen this issue.
