### ISSUE TITLE
Adding multiple XiaomiGateway3's

### ISSUE THREAD

**Issue by koenvo27** [AlexxIT/XiaomiGateway3#550]
Hello there,

First of all thanks alot for the integration! It helped me really alot already!!

Recently i bought a second Xiaomi gateway 3 and i can't succeed to add it to the integration..

I'm not sure if it's a bug or its not supported?

Thanks for the help already.

Kind regards

K.

**Comment by AlexxIT** [comment]
Any details?

**Comment by koenvo27** [comment]
When i try to reconfigure / re add the gateway properties (because i don't have any option to add a second gateway i have to select one and it seems they don't want to work together..

The option of adding a new gateway is missing i think? 

Or i'm just beeing noob that's possible to..

Thanks already.

K.

**Comment by AlexxIT** [comment]
You need to add integration once again

**Comment by koenvo27** [comment]
Ok thanks now it works!
