### ISSUE TITLE
entity implements device_state_attributes

### ISSUE THREAD

**Issue by vorlocsev** [AlexxIT/XiaomiGateway3#552]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 18:23:52 (41 occurrences)
Last logged: 18:24:11

Entity binary_sensor.0x158d0003973bbb_contact (<class 'custom_components.xiaomi_gateway3.binary_sensor.XiaomiBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.0x158d0003973bbb_battery (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity alarm_control_panel.0x588e81fffeddeee4_alarm (<class 'custom_components.xiaomi_gateway3.alarm_control_panel.XiaomiAlarm'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.50ec50ca6875_light (<class 'custom_components.xiaomi_gateway3.light.XiaomiMeshLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity media_player.yandex_station_443078968308541a0050 (<class 'custom_components.yandex_station.media_player.YandexStationHDMI'>) implements device_state_attributes. Please report it to the custom component author.

What does it mean?

**Comment by vorlocsev** [comment]
Ohh, i found it. Return entity specific state attributes. This method is deprecated, platform classes should implement. extra_state_attributes instead.

**Comment by barnabyjones** [comment]
I came here to suggest this also. 

The new features are called device configuration URL and entity categories. They are outlined in the developer blog here: 

https://developers.home-assistant.io/blog/2021/10/26/config-entity/#entity-categories

**Comment by AlexxIT** [comment]
Duplicate
