### ISSUE TITLE
Can't add new IKEA LED.

### ISSUE THREAD

**Issue by K1ckMan** [AlexxIT/XiaomiGateway3#554]
Cannot add via Xiaomi Hub Gateway 3.

TRADFRI LED 345 lm
GU10
LED2005R5

New device:
did: lumi.50325ffffe4cdda5
mac: 50325ffffe4cdda5
model: TRADFRIbulbGU10WS345lm
version: 16
zb_ver: 3.0
joined_type: 1

**Comment by AlexxIT** [comment]
There is 4 different methods with adding non Xiaomi devices to Gateway. 3 of them in readme. 4th in beta version

**Comment by yanncd** [comment]
Hello,
I would like to know how to add it, i have the same issue.
Thank you
