### ISSUE TITLE
xiaomi_gateway3/device_trigger.py Error with core-2021.12.0

### ISSUE THREAD

**Issue by dscao** [AlexxIT/XiaomiGateway3#556]
Hi 
After upgrade to Home Assistant Core 2021.12 gateway3 device_trigger  is not working :

> Logger: homeassistant.components.automation.xiao_mi_kai_guan_san_ji_da_kai_re_shui_qi
> Source: custom_components/xiaomi_gateway3/device_trigger.py:50
> Integration: 自动化 (documentation, issues)
> First occurred: 09:51:29 (2 occurrences)
> Last logged: 09:54:56
> 
> Error setting up trigger 小米开关三击打开热水器
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 36, in async_attach_trigger
>     return await platform.async_attach_trigger(hass, config, action, automation_info)
>   File "/config/custom_components/xiaomi_gateway3/device_trigger.py", line 50, in async_attach_trigger
>     state_config = state_trigger.TRIGGER_SCHEMA(state_config)
> AttributeError: module 'homeassistant.components.homeassistant.triggers.state' has no attribute 'TRIGGER_SCHEMA'

> Logger: homeassistant.components.automation.xiao_mi_kai_guan_shuang_ji_da_kai_tai_yang_neng
> Source: custom_components/xiaomi_gateway3/device_trigger.py:50
> Integration: 自动化 (documentation, issues)
> First occurred: 09:51:29 (2 occurrences)
> Last logged: 09:54:56
> 
> Error setting up trigger 小米开关双击打开太阳能
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 36, in async_attach_trigger
>     return await platform.async_attach_trigger(hass, config, action, automation_info)
>   File "/config/custom_components/xiaomi_gateway3/device_trigger.py", line 50, in async_attach_trigger
>     state_config = state_trigger.TRIGGER_SCHEMA(state_config)
> AttributeError: module 'homeassistant.components.homeassistant.triggers.state' has no attribute 'TRIGGER_SCHEMA'

**Comment by aferraz** [comment]
same for me

**Comment by MaoZ1993** [comment]
Same here, button switches all not working anymore.

**Comment by propi62** [comment]
Same here. Xiaomi buttons not working since update. 2021.12

**Comment by AlexxIT** [comment]
For temporary fix you may change `device` automation to `state` automation.

**Comment by dscao** [comment]
Thank you, it's ok.

```
platform: device
device_id: 1fd4ae35525370212058d5a22b4aXXXX
domain: xiaomi_gateway3
type: button
action: triple
```

change to

```
platform: state
entity_id: sensor.0x158d000403XXXX_action
to: triple
```

**Comment by PWMFI** [comment]
How to operate

**Comment by propi62** [comment]
Where can i change it?

**Comment by PWMFI** [comment]
I won't modify it

**Comment by AlexxIT** [comment]
Fixed in latest release
