### ISSUE TITLE
After upgrading to v1.5.1_0032, Xiaomi Light Sensor (GZCGQ01LM) not updating

### ISSUE THREAD

**Issue by ilkanaev** [AlexxIT/XiaomiGateway3#559]
Hello,

After upgrading the Xiaomi Gateway 3 to v1.5.1_0032, the data from Xiaomi Light Sensor (GZCGQ01LM) almost not updated in HomeAssistant. it is well updated inside the Xiahomi Mi Home application but not in Home Assistant.
Sometimes, some data comming to the home assistant, but i see no relation between this received data and the numbers in Mi Home.

Core 2021.12.0
Supervisor 2021.12.1 (the issue started before upgrading to this one)
Docker 20.10.11

The only error i see is the logs is

**Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 11:59:38 (71 occurrences)
Last logged: 12:01:06

Entity binary_sensor.door_sensor_entrance_e4aaec35b4d0_contact (<class 'custom_components.xiaomi_gateway3.binary_sensor.XiaomiBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.door_sensor_entrance_e4aaec35b4d0_light (<class 'custom_components.xiaomi_gateway3.binary_sensor.XiaomiBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.e4aaec35b4d0_battery (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity alarm_control_panel.xiaomi_gateway_3_alarm (<class 'custom_components.xiaomi_gateway3.alarm_control_panel.XiaomiAlarm'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.kitchen_ht_ble (<class 'custom_components.xiaomi_gateway3.sensor.BLEStats'>) implements device_state_attributes. Please report it to the custom component author.**

Thank you in advance,
Yossi

**Comment by ilkanaev** [comment]
i think the data updated only when restarting the entire system, in rest of the cases it stay not updated....

**Comment by AlexxIT** [comment]
#531
