### ISSUE TITLE
I'd like to provide a feedback following the #531 and #559

### ISSUE THREAD

**Issue by ilkanaev** [AlexxIT/XiaomiGateway3#560]
Hi,
I'd like to provide a feedback following the #531 and #559 -

1. The events handling with v1.5.0_0026 much faster than in 1.5.0_0102. it means for example the delay between the Aqara Motion Sensor detects a motion till this has been operated is much faster when using  v1.5.0_0026. it is feelable difference, so i personaly went back to the  v1.5.0_0026 from v1.5.0_0102.
i've tested this on core-2021.12.1 + supervisor-2021.12.1 and earlyer versions.

2. It is not commented as supported, but when i am using the "Aqara Wireless Remote Switch D1 (Double Rocker)" and core-2021.12.1 + supervisor-2021.12.1 , and either version of the gateway, it looks like the events sent twice/ so the automations triggered twice. adding simple delay of 1second in 'actions' and using the single mode for automations, can be used as a warkeround for this issue:-).

3. I think there is a mistake - i followed the Supported Firmware (https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares) and installed the latest supported v1.5.1_0032, when it is actualy the wrong version to use :-). 

Thanks,
Yossi

**Comment by AlexxIT** [comment]
Thanks.

1. I don't know how to explain this behaviour
2. It looks like a bug. You can turn on debug mode
3. No any mistake. v1.5.1_0032 latest, but not tested firmware yet
