### ISSUE TITLE
Problem when adding a Add-on 

### ISSUE THREAD

**Issue by motogon** [AlexxIT/XiaomiGateway3#564]
Hi 

ERROR (MainThread) [supervisor.store] https://github.com/AlexxIT/XiaomiGateway3 is not a valid add-on repository

Версия core-2021.12.1
Версия supervisor-2021.12.1

**Comment by AlexxIT** [comment]
Why you decided to add it as addon?

**Comment by motogon** [comment]
as described : HACS > Integrations > Plus > XiaomiGateway3 > Install

**Comment by motogon** [comment]
tried the same way: nothing added 

Method 2. Manually copy xiaomi_gateway3 folder from latest release to /config/custom_components folder.

**Comment by AlexxIT** [comment]
https://youtu.be/FVWfjE5tx2g
