### ISSUE TITLE
Readings stopped coming from Xiaomi TH Sensor 2 (LYWSD03MMC)

### ISSUE THREAD

**Issue by sidlauskaslukas** [AlexxIT/XiaomiGateway3#565]
Hello,

I have 4x LYWSD03MMC sensors and one of them seems to be stuck, readings stopped coming to both HA and Mi Home applications. I had no issues for the last 2 years with these sensors and the Gateway 3 (ZNDMWG03LM) before I started using a custom firmware (1.5.0_0102) in my Gateway 3 which is required for this integration. I tried to restart the HA and the gateway, as well as the sensor itself (removed the battery), but it doesn't help.

<img width="399" alt="Screenshot 2021-12-14 at 20 07 10" src="https://user-images.githubusercontent.com/3224839/146060730-966c7455-5de0-45ea-b428-a75fab1e9127.png">

Environment:
Home Assistant Core 2021.12.0
Home Assistant OS 6.6
XiaomiGateway3 v1.6.4
Gateway 3 Firmware: 1.5.0_0102

**Comment by AlexxIT** [comment]
Try to add it again to MiHome. Maybe it forget its token.

**Comment by haigaru** [comment]
i same proplem. xiaomi light sensor is sto
![Screen Shot 2021-12-19 at 23 33 55](https://user-images.githubusercontent.com/60953672/146682874-86a82d00-42c8-446d-a4c0-8e5407812308.png)
p

**Comment by AlexxIT** [comment]
@haigaru #531

**Comment by haigaru** [comment]
@AlexxIT thank so much

**Comment by AlexxIT** [comment]
@sidlauskaslukas ?

**Comment by sidlauskaslukas** [comment]
@AlexxIT I managed to resolve this issue by re-adding it in Mi Home. The fun thing that now it's updating more often than other 3 devices (received messages count already surpassed the others by 200)
