### ISSUE TITLE
isa.magnet.dw2hl battery Unsupported state class

### ISSUE THREAD

**Issue by kudouxinyi** [AlexxIT/XiaomiGateway3#567]
2021-12-16 09:30:04 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.54ef44e7cb2d_battery (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.

Unsupported state class
The state class of this entity, is not supported.
Statistics can not be generated until this entity has a supported state class.

If this state class was provided by an integration, this is a bug. Please report an issue.

If you have set this state class yourself, please correct it. The different state classes and when to use which can be found in the developer documentation.

**Comment by rzv-trsc** [comment]
Seems to be linked to device_state_attributes for all Xiaomi gadgets: 

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: December 15, 2021, 9:20:11 PM (66 occurrences)
Last logged: 1:50:05 AM

Entity sensor.0x158d000548cf51_battery (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.a4c13858789c_battery (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.a4c13858789c_humidity (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.a4c13858789c_temperature (<class 'custom_components.xiaomi_gateway3.sensor.XiaomiSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity alarm_control_panel.0x588e81fffee69aac_alarm (<class 'custom_components.xiaomi_gateway3.alarm_control_panel.XiaomiAlarm'>) implements device_state_attributes. Please report it to the custom component author.
```

Started getting these after yesterday's update (haven't noticed them before). 
core-2021.12.2; Home Assistant OS 7.0; supervisor-2021.12.2

**Comment by AlexxIT** [comment]
Please, read existing issues before creation new one #546
