### ISSUE TITLE
Feature request - Support for Mi Smart LED Bulb Essential

### ISSUE THREAD

**Issue by konstcranky** [AlexxIT/XiaomiGateway3#57]
Hi, 

Can you add please support for 

Name: Mi Smart LED Bulb Essential (White and Color)
Model: yeelink.light.color5

I'm using these lamps and it will be useful to control it directly via HA :)

Thanks.

**Comment by AlexxIT** [comment]
It's wifi bulb. Gateway can't control it.

**Comment by tuncay59** [comment]
Hi,
I have the same bulb. Is there a change?
Is there any way to add it to Home Assistant?

**Comment by AlexxIT** [comment]
Any Xiaomi WiFi devices can be controlled via miio protocol
