### ISSUE TITLE
Automation with single button doesn't work anymore since version 2021.12.1 (2021.11.5 works OK)

### ISSUE THREAD

**Issue by vdbosch** [AlexxIT/XiaomiGateway3#570]

**Comment by AlexxIT** [comment]
Duplicate #556

**Comment by vdbosch** [comment]
Alex,

 

Thanks for feedback, with platform State the problem could indeed be solved.

 

Very much appreciated (and used) your solutions Sonoff Lan, Xiaomi Gateway 3 and WebRTC.

Great contribution, should become part of standard integrations.

 

Regards,

 

Rob
