### ISSUE TITLE
Migatway3 will lose all entities after router power-off?

### ISSUE THREAD

**Issue by itispip** [AlexxIT/XiaomiGateway3#577]
I'm not sure if it's a bug but it happens at least 2-3 time to me already

I have about 30 Xiao IoT devices. I found that if  I power off my Router for sometimes and power on again, the ble and zigeebee devices will become obsolete (not offline, but obsolete) in HomeAssistant through this component, but Wifi devices are still normal. 

The only way to bring them back is to delete the Gateway devices from Interigation and then install it again, but that will break all my HA automations as the new created devices/entity by Migatway3 is a different name from the customized name I have given ....

Anyone has similar problem & know a better way to bring the obsolete ble/zigbee entitities back?

**Comment by AlexxIT** [comment]
Are you using latest integration version?

**Comment by toranis** [comment]
Same problem here. Im using the latest integration.
Ez a hiba egy egyéni integrációból lett származtatva.

Logger: custom_components.xiaomi_gateway3.core.xiaomi_cloud
Source: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:170
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 18:49:41 (2 occurrences)
Last logged: 18:49:42

Can't request MIoT API /home/device_list
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 170, in request
    return resp['result']
KeyError: 'result'

**Comment by toranis** [comment]
The xiaomi DE server is not responding correctly i think, because the integration says there are no devices, but the xiaomi home app is working normaly.

**Comment by itispip** [comment]
> Are you using latest integration version?

Yes, latest version. But this issue happen on old version as well.

**Comment by AlexxIT** [comment]
Problem should be fixed at latest release

**Comment by toranis** [comment]
> Problem should be fixed at latest release

Thank you! Its working again! :D
