### ISSUE TITLE
Add some lights without names and types

### ISSUE THREAD

**Issue by wqh227** [AlexxIT/XiaomiGateway3#580]
I can't submit documents.
I bought some lights, these lights are usually Three-no products*, they use the control chip provided by Lemesh. Lemesh bought chips from Mijia and burned the program. Some lights even use Mijia chips that are not genuine, and these lights often drop from the Bluetooth mesh gateway. lemesh official website: http://www.lelight.cn
Three-no products*：Three-no products generally refer to products that have no production date, no quality certificate, and no manufacturer, and are of unknown origin.

```
@ -43,14 +43,15 @@ DEVICES = [{
    997: ["Yeelight", "Mesh Spotlight", "YLSD04YL"],
    1771: ["Xiaomi", "Mesh Bulb", "MJDP09YL"],
    1772: ["Xiaomi", "Mesh Downlight", "MJTS01YL/MJTS003"],
    1910: ["LeMesh", "Mesh light (RF ready)", "lemesh.light.wy0c02"],
    2076: ["Yeelight", "Mesh Downlight M2", "YLTS02YL/YLTS04YL"],
    2293: ["Unknown", "Mesh Lightstrip (RF ready)", "crzm.light.wy0a01"],
    2342: ["Yeelight", "Mesh Bulb M2", "YLDP25YL/YLDP26YL"],
    2351: ["Unknown", "Mesh Downlight", "lemesh.light.wy0c05"],
    2351: ["LeMesh", "Mesh Downlight", "lemesh.light.wy0c05"],
    2584: ["XinGuang", "XinGuang Smart Light", "LIBMDA09X"],
    3164: ["Unknown", "Mesh Downlight (RF ready)", "lemesh.light.wy0c07"],
    3164: ["LeMesh", "Mesh light (RF ready)", "lemesh.light.wy0c07"],
    3416: ["Unknown", "Mesh Downlight", "090615.light.mlig01"],
    3531: ["Unknown", "ightctl Light", "lemesh.light.wy0c08"],
    3531: ["LeMesh", "ightctl Light", "lemesh.light.wy0c08"],
    'miot_spec': [
        [2, 1, 'light', 'light'],
        [2, 2, 'brightness', None],
@ -134,12 +135,14 @@ DEVICES = [{
# if color temp not default 2700..6500
COLOR_TEMP = {
    # https://github.com/AlexxIT/XiaomiGateway3/issues/350
    1910: [3000, 6400],
    2351: [3100, 3100],
    2584: [3000, 6400],
    3531: [3000, 6400],
}
# if max brightness not default 65535
MAX_BRIGHTNESS = {
    1910: 100,
    2293: 100,
    2351: 100,
    2584: 100,
```
![20211227212220377](https://user-images.githubusercontent.com/36147621/147476024-f8df27bb-2be7-4a26-a19f-a9b1cfd4cfa2.jpg)
[bluetooth.zip](https://github.com/AlexxIT/XiaomiGateway3/files/7780350/bluetooth.zip)

**Comment by wqh227** [comment]
Use google translate. These products have different shapes, which may be downlights, spotlights, light strips, magnetic (module) lights

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
