### ISSUE TITLE
Xiaomi Smart Lock E Support lumi.lock.bmcn03 Support

### ISSUE THREAD

**Issue by Houtworm** [AlexxIT/XiaomiGateway3#583]
So I got this Xiaomi Door lock E, it is all over the chinese websites.

Sadly it is not working, I read in other threads that you need a piece of the log, Not sure what you are looking for specifically, But I think this is the device in question.

192.168.178.100 | Processing MQTT: log/miio b'[20211228 23:30:01] [D] ot_agent_recv_handler_one(): fd:12, msg:{"method":"_async.ble_event","params":{"dev":{"did":"1024898289","mac":"E8:79:D6:73:E0:08","pdid":1924},"evt":[{"eid":4106,"edata":"64e88fcb61"}],"frmCnt":65,"gwts":1640730601},"id":368678} length:189 bytes'
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 147, in mqtt_message
    await self.dispatcher_send(SIGNAL_MQTT_PUB, msg=msg)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/base.py", line 103, in dispatcher_send
    await handler(**kwargs)
  File "/config/custom_components/xiaomi_gateway3/core/gateway/ble.py", line 59, in ble_mqtt_publish
    await self.ble_process_event(data["params"])
  File "/config/custom_components/xiaomi_gateway3/core/gateway/ble.py", line 76, in ble_process_event
    self.devices[mac] = device = XDevice(
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 53, in __init__
    assert did.startswith("blt.")
AssertionError

Not sure if this is enough, Or if there is any private information in there, But I would love to see this puppy supported, and I would also love to help with that if needed :)

**Comment by AlexxIT** [comment]
This is enough, thanks

**Comment by Houtworm** [comment]
You are very welcome, It is the least I can do, Thank you for this amazing integration and all the hard work you put into it, It is the main integration I use in my HA setup :)

**Comment by AlexxIT** [comment]
You may use latest release version v1.6.5. It shouldn't have this bug. Bug only in v2-alpha

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
