### ISSUE TITLE
Updating from 1.5.1 to 1.6.5

### ISSUE THREAD

**Issue by Jo-Jo1987** [AlexxIT/XiaomiGateway3#585]
Currently facing a broken update in Home Assistant.
Whenever i update from 1.5.1 to 1.6.5 all my devices got lost.

Hopefully there is a bugfix for it.

**Comment by Somati-x** [comment]
I have the same problem...

**Comment by Jo-Jo1987** [comment]
any update?

**Comment by AlexxIT** [comment]
Are you using the recommended firmware? Did you specify the correct telnet command? Have you looked at the errors in the logs?

**Comment by Somati-x** [comment]
I will check everything again and provide all the information. I'm back to backup

**Comment by Somati-x** [comment]
> Ви використовуєте рекомендовану прошивку? Ви вказали правильну команду telnet? Ви переглянули помилки в журналах?

I will check everything again and provide all the information. I'm back to backup

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
