### ISSUE TITLE
Feature for support Aqara Wireless Switch on D1

### ISSUE THREAD

**Issue by dmr1987** [AlexxIT/XiaomiGateway3#587]
If you add this lines to definition lumi.switch.n3acn3 in file zigbee.py, user can enable wireless remote switch function on D1 switch. With this feature pressing button on walll switch not trigger relay output. This feature useful for control smart devices or another wall switches without triggereng relay output. User can trigger relay output from HA automation, if necessary

        ['4.10.85', 'channel_0_wireless', 'channel 1 wireless', 'switch'],
        ['4.11.85', 'channel_1_wireless', 'channel 2 wireless', 'switch'],
        ['4.12.85', 'channel_2_wireless', 'channel 3 wireless', 'switch'],

**Comment by xrh0905** [comment]
PR.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
