### ISSUE TITLE
I can't turn on 'Mode ZHA or zigbee2mqtt [ADV]'

### ISSUE THREAD

**Issue by dawidc1994** [AlexxIT/XiaomiGateway3#588]
Hi,
I'm trying connect some devices via zigbee and Xiaomi Gateway 3, but I can't set _Mode ZHA or zigbee2mqtt [ADV]_ option. I know sometimes ago it has been possible but now I reinstalled all home assistant and it's not working. HA is on Raspbery Pi 4.
Error: _Unknown error occurred_
Logs: _Try to update Zigbee NCP to version v6.7.10
2022-01-05 14:11:32  DEBUG    utils         NCP flash error: Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 215, in flash_zigbee_firmware
    utils.connect(host, port)
ConnectionRefusedError: [Errno 111] Connection refused_

Reinstall doesn't help.

**Comment by bemilicus** [comment]
Hello,
just yesterday i had same error on a brand new gateway 3. About 15 days ago a setup another gateway 3 without issues on a similar setup (rpi4) and same vertions of addons/os between the two installations.

**Comment by bemilicus** [comment]
Hello 
after an A/B comparison, i noticed that on my system (**i call it A** - with Xiaomi GW3 v1.65) there is a GUI (see shot) GUI slightly different if compared with the other rpi4 (the one i can't turn 'Mode ZHA or zigbee2mqtt' ON - **i call B**). On the **B system**, there is also Xiaomi GW3 v1.65 intalled BUT (ie) the debug option is under a dropdown menu. 

I'm not running the integration along with beta versions so i'm a little bit confused about the two different GUIs...

Anyway, i took the GW3 on my system (**A system** the one with the GUI in the screenshot) and got it to work as a proof that there should be something wrong in the **B system** even if the integration is reporting the same version number.

Just a thought...

![shot1](https://user-images.githubusercontent.com/62201229/150742659-7998a59a-e079-43b8-89fd-6d538d088945.png)

**Comment by bemilicus** [comment]
Hello
after some further comparison, finally i think i at least catched the discriminant.
The problem seems to raise ONLY when using wifi connection on the rpi4. Tried that on two different rpi4 with almost same OS.
If i stick with ethernet connection (eth0 on my systems), the setup of ZHA or zigbee2mqtt seems ok. When i switch to wifi connection, the setup GUI (xiaomi gw 3) is slightly different and the setup fails.

That's all i'm able to report
Someone on this please?

TIA

**Comment by AlexxIT** [comment]
It is not recommended to use the Hass server when connecting on WiFi. It will not work well

**Comment by bemilicus** [comment]
ok thanks
so i can turn zigbee2mqtt mode to ON while on ethernet. 
After setting it up, can i switch to wifi on my rpi4? It sound a little bit crazy to have wifi options available even on the HA gui and still being not able to use it...

Many thanks

**Comment by dawidc1994** [comment]
My Pi is connected via Ethernet, and I still can't turn on this option.

**Comment by AlexxIT** [comment]
You need to find the reason why Hass cannot connect to the gateway. Sometimes rebooting the gateway or wifi router helps

**Comment by dawidc1994** [comment]
But hass is connected to the gateway correctly. I see all parameters from another sensors like temperatures, humidity etc.

**Comment by AlexxIT** [comment]
@dawidc1994 maybe you block internet for gateway and it can't load important binary file. Or you have problems with internet connection to sourceforge.net

**Comment by giluriel** [comment]
Hi Guys,
I'm running into that same issue: after checking the option for ' [DANGER] Mode ZHA or zigbee2mqtt ' and clicking SUBMIT I'm getting an error message "Unknown error occurred" 
The Xiaomi Gateway 3 ver is 2.0.4 (it behaved the same with 2.0.3)
My Gateway is:
_IP: 10.1.100.112
MAC: 54:EF:44:22:7A:A0
Token: 6c39706b6d336e324e5446685157316f
Model: lumi.gateway.mgl03
Region: tw_
HASS 2022.2.6

here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/6133929/154149189-1ae8a721-e8ce-4fd1-95b9-5e0134b9a446.png)
TNX

**Comment by AlexxIT** [comment]
@giluriel you need to check logs

**Comment by romanu417** [comment]
Hi, have the same problems

@giluriel Did you fix it?

**Comment by giluriel** [comment]
Hi,

Yes, I did. I will try to remember how I did it....
(you saw that there are two versions of the telnet command to put there, 
right? only one works with each model)

Gil

On 08/06/2022 01:20, Roman wrote:

> Hi, have the same problems
> 
> @giluriel [1] Did you fix it?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/giluriel
[2] 
https://github.com/AlexxIT/XiaomiGateway3/issues/588#issuecomment-1149230324
[3]

**Comment by romanu417** [comment]
The error disappeared when I installed version 1.5.0_0102

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
