### ISSUE TITLE
Question: WIFI deauth every 5 mins of gateway hardware

### ISSUE THREAD

**Issue by nov30th** [AlexxIT/XiaomiGateway3#590]
I've used the XiaomiGateway3 with HA and it works normally about 1 or 2 years.

There is a question I would like to ask everyone here that is the WIFI of the gateway will **disconnect and reconnect every 5 mins** of your gateways?
I usually not check the router logs but today, it **MIGHT** always like this.

Hardware: lumi.gateway.mgl03 ZNDMWG03LM

each deauth request sent at XX:XX:45 as pic below.
![image](https://user-images.githubusercontent.com/11451122/148590372-ce3327fa-0547-4e79-8358-568bcc8e765f.png)

The signal is good, I guess is the software or mod as designing? As my Xiaomi gateway 2 doesn't have such a situation.
![image](https://user-images.githubusercontent.com/11451122/148590018-4d3d74e7-fb30-49b5-9abc-119bd06ab70f.png)

**Comment by nov30th** [comment]
I found it might be the WPA or WPA2 security related. But why.

dmesg:
![image](https://user-images.githubusercontent.com/11451122/148592169-4319467d-21be-4c93-a192-aca276d35e46.png)

WIFI Settings:
![image](https://user-images.githubusercontent.com/11451122/148592140-262e04ae-62b9-47d6-9bb6-2a4ec7dc8a03.png)

**Comment by nov30th** [comment]
searched google and found the message "Calling CRDA to update world regulatory domain" would execute the crda to set the country code of wireless or something, but there is no crda bin file to be executed.
Haven't tested with stock firmware as I always use the mod firmware.
weird.

**Comment by AlexxIT** [comment]
I guess you not read requirement section in docs
https://github.com/AlexxIT/XiaomiGateway3#requirements

Answer in you WiFi setting screen

**Comment by nov30th** [comment]
Thank you Alex, it is helpful that I haven't noticed the device did not "supports" the group key update as I haven't met such a situation with any other device before and it works like this for more than a year.

Does lumi know the issue or the device chip limitation? From my understanding it would be a bug or something, I would try to contact if it could be solved.

**Comment by AlexxIT** [comment]
This gw have a lot of WiFi settings problems. All of them described in requirements readme section. Ideally, they should all be fixed on the Lumi side. But I think they are no longer interested in supporting this version of the gateway

**Comment by AlexxIT** [comment]
And wifi problems are not the biggest problem of this model :)
