### ISSUE TITLE
Gateway 3 и разные подсети

### ISSUE THREAD

**Issue by geldelo** [AlexxIT/XiaomiGateway3#596]
Добрый день.

HA установлен в подсети 10.8.0.0, а Gateway 3 в другой подсети — 192.168.1.0.
Устройства пингуются нормально. При попытке добавить шлюз в HA — ошибка, Device Offline.
Что может быть, подскажите, пожалуйста?
P.S. Должен ли быть открытым порт 9898 на Gateway 3?

**Comment by AlexxIT** [comment]
Добрый. Может быть, что вы не прочли раздел Requirements в документации
https://github.com/AlexxIT/XiaomiGateway3#requirements

А по факту - miio протокол не ответит на запрос из другой подсети. Компонент не может открыть телнет. Альтернативно вы можете накатить на шлюз кастом прошивку с постоянно открытым телнетом, но часть функций компонента, которые завязаны на miio протокол, не будут работать. Такой подход только на ваш страх и риск.

**Comment by geldelo** [comment]
Если пингуется IP-адрес Gateway 3 из сервера, значит ли это что доступ к шлюзу по локальной сети есть? Или как определить в какой сети сейчас установлен сервер и изменить настройки?

У меня по сути установлен Wireguard на удаленном сервере вместе с HA и он коннектится к домашнему Kennetic (к которому подключены домашние устройства) с Wireguard'ом.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
