### ISSUE TITLE
Temporary unavability of some zigbee devices

### ISSUE THREAD

**Issue by Ky0sHiR00** [AlexxIT/XiaomiGateway3#599]
Hello,
I'm using your integration for a while but after new year some devices started acting weird.
Part of them - especially Aqara E27 bulps started to be temporary unavailable for between 2-40 minutes.
Below You can find extract from recent unavailability:
>2022-01-15 19:20:06  DEBUG    gateway3      192.168.31.141 | lumi.158d000547777b lumi.light.aqcn02 <= {} [0.01]
>2022-01-15 19:23:25  DEBUG    gateway3      192.168.31.141 | sensor.0x158d000547777b_zigbee | Msg missed: 92 => 96, 101 => 105, Basic
>2022-01-15 19:23:25  DEBUG    gateway3      192.168.31.141 | lumi.158d000547777b lumi.light.aqcn02 <= {'alive': {'status': 'online', 'time': 0}} [0.02]
>2022-01-15 19:23:25  DEBUG    gateway3      192.168.31.141 | lumi.158d000547777b lumi.light.aqcn02 <= {'chip_temperature': 100, 'fw_ver': 23, 'hw_ver': 1, '8.0.2228': 2307, 'light': 1, 'brightness': 100, 'color_temp': 153, 'lqi': 144} [0.01]`

**Comment by Ky0sHiR00** [comment]
Steps tried to resolve issue:

- Re-add of unavailable zigbee devices 
- Re-add gateway via integration
- Complete reset of gateway - adding new devices one by one
- Change place of hub including place without any electronic devices
- Stable IP for gateway

**Comment by AlexxIT** [comment]
This maybe fixed with 2nd version of integration

**Comment by yongman** [comment]
Same here.

**Comment by AlexxIT** [comment]
@Ky0sHiR00 is 2nd version helps with your problem?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
