### ISSUE TITLE
ERROR: No response from the device

### ISSUE THREAD

**Issue by v222008** [AlexxIT/XiaomiGateway3#6]
Привет. Как только узнал о новости решил сразу же пробую на своем XiaomiGateway3

и в ответ тишина а именно ERROR: No response from the device

Токин есть но в HA никак не конектится к шлюзу(

**Comment by AlexxIT** [comment]
Это проблема miio протокола на шлюзе. Шлюз не отвечает, такое бывает. Если есть уверенность, что IP и токен верные - надо не сдаваться. Возможно перезагрузить шлюз по питанию.

**Comment by v222008** [comment]
> Это проблема miio протокола на шлюзе. Шлюз не отвечает, такое бывает. Если есть уверенность, что IP и токен верные - надо не сдаваться. Возможно перезагрузить шлюз по питанию.

Такое предположение , что с последней обновой прикрили там на шлюзе лазейку. 

```

root@home:/home/pi/VIDEO/php-miio-master# php miio-cli.php --discover 192.168.40.70 --debug
array(2) {
  ["discover"]=>
  string(13) "192.168.40.70"
  ["debug"]=>
  bool(false)
}
Поиск 192.168.40.70
Соединение с устройством IP 192.168.40.70
Статус отладки [1]
Сокет успешно создан

Проверяем доступность устройства 192.168.40.70
Параметр SO_RCVTIMEO сокета успешно задан
 >>>>> Отправляем hello-пакет на 192.168.40.70 с таймаутом 5
 >>>>> Отправлено в сокет 32 байт
 <<<<< Получен ответ от IP 192.168.40.70 с порта 54321
Прочитано 32 байта из сокета
magic: 2131
length: 0020 --> 32 байт
unknown1: 00000000
devicetype: 12e6
serial: ac67
ts: 5f5261da --> 1599234522 секунд --> 2020-09-04 18:48:42
checksum: ffffffffffffffffffffffffffffffff
ts_server: 5f5261da --> 1599234522 секунд --> 2020-09-04 18:48:42
timediff: 0
Поиск выполнен.
Устройство найдено и отвечает.
root@home:/home/pi/VIDEO/php-miio-master# php miio-cli.php --discover 192.168.40.70 --debug
array(2) {
  ["discover"]=>
  string(13) "192.168.40.70"
  ["debug"]=>
  bool(false)
}
Поиск 192.168.40.70
Соединение с устройством IP 192.168.40.70
Статус отладки [1]
Сокет успешно создан

Проверяем доступность устройства 192.168.40.70
Параметр SO_RCVTIMEO сокета успешно задан
 >>>>> Отправляем hello-пакет на 192.168.40.70 с таймаутом 5
 >>>>> Отправлено в сокет 32 байт
 <<<<< Получен ответ от IP 192.168.40.70 с порта 54321
Прочитано 32 байта из сокета
magic: 2131
length: 0020 --> 32 байт
unknown1: 00000000
devicetype: 12e6
serial: ac67
ts: 5f5261de --> 1599234526 секунд --> 2020-09-04 18:48:46
checksum: ffffffffffffffffffffffffffffffff
ts_server: 5f5261de --> 1599234526 секунд --> 2020-09-04 18:48:46
timediff: 0
Поиск выполнен.
Устройство найдено и отвечает.

root@home:/home/pi/VIDEO/php-miio-master# php miio-cli.php --discover all --bindip 192.168.40.70                                                                        Поиск всех
Поиск выполнен.
Найдено 1 устройств.
 IP 192.168.40.70 DevType 12e6 Serial ac67 Token ffffffffffffffffffffffffffffffff

Token при паринге шлюза с михоме получаю  типа 4C7A534D5948436F32436A4A644C6465
 но потом как описал
```

**Comment by agavrin** [comment]
У меня  такая же история
`
php-miio git:(master) php miio-cli.php --debug --token 716a68553971623148574b4d54787371 --ip 192.168.1.45 --sendcmd '{"id":0,"method":"enable_telnet_service", "params":[]}'

array(4) {
  ["debug"]=>
  bool(false)
  ["token"]=>
  string(32) "716a68553971623148574b4d54787371"
  ["ip"]=>
  string(12) "192.168.1.45"
  ["sendcmd"]=>
  string(54) "{"id":0,"method":"enable_telnet_service", "params":[]}"
}
Соединение с устройством IP 192.168.1.45
Статус отладки [1]
Сокет успешно создан
Команда для отправки - {"id":0,"method":"enable_telnet_service", "params":[]}

Проверяем доступность устройства 192.168.1.45
Параметр SO_RCVTIMEO сокета успешно задан
 >>>>> Отправляем hello-пакет на 192.168.1.45 с таймаутом 5
 >>>>> Отправлено в сокет 32 байт
 <<<<< Получен ответ от IP 192.168.1.45 с порта 54321
Прочитано 32 байта из сокета
magic: 2131
length: 0020 --> 32 байт
unknown1: 00000000
devicetype: 12e6
serial: a262
ts: 5f55138a --> 1599411082 секунд --> 2020-09-06 16:51:22
checksum: ffffffffffffffffffffffffffffffff
ts_server: 5f55138b --> 1599411083 секунд --> 2020-09-06 16:51:23
timediff: -1

Устройство 192.168.1.45 доступно
Параметр SO_RCVTIMEO сокета успешно задан
Используется токен, указанный вручную, - 716a68553971623148574b4d54787371
 >>>>> Отправляем пакет на 192.168.1.45 с таймаутом 5
magic: 2131
length: 0060 --> 96 байт
unknown1: 00000000
devicetype: 12e6
serial: a262
ts: 5f55138a --> 1599411082 секунд --> 2020-09-06 16:51:22
checksum: b73b62d848ec54471778e7d96c73e48d
data: 69da64b5e77df9f37959107d72906ce1ca85b20e626ba81bc0388bab4fec53d0dda21236fa60a8e966ef05ffa309ffe8ad0e2b5ffa08a2a0eba6425de040ba3a
ts_server: 5f55138b --> 1599411083 секунд --> 2020-09-06 16:51:23
timediff: -1
 >>>>> Отправлено в сокет 96 байт
Ошибка чтения из сокета [35] Resource temporarily unavailable
Устройство 192.168.1.45 не доступно или не отвечает.`

**Comment by AlexxIT** [comment]
Есть проблемы на последней версии?

**Comment by v222008** [comment]
> Есть проблемы на последней версии?

К сожелению я застрял на етапе активации телнета на моей белой шайбе( или у меня руки из жо или я чтото нетак делаю...
