### ISSUE TITLE
Xiaomi Gateway v3: Unavailable entity displays as "on" in HA

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/XiaomiGateway3#607]
Hi, I have a lamp with a Yeelight M2 BT Mesh bulb that I like to turn off physically sometimes (as in, power is cut off from the bulb). I'd expect the bulb to display as "unavailable" in HA but it stays "on" indefinitely (even after like 12 hours). That looks like a bug to me, and it can also interfere with light automations. 

Xiaomi Gateway v3 (lumi.gateway.mgl03) on firmware 1.5.0_0102.

[Here's the log](https://www.toptal.com/developers/hastebin/zetixeqoce) from the component.

**Comment by AlexxIT** [comment]
Wrong unavailable for Mesh devices - is known problem. It's related to gateway internal software. I can't fix it without rewriting stock BLE/Mesh soft

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
