### ISSUE TITLE
How to add BLE device in HA with ZNDMWG03LM?

### ISSUE THREAD

**Issue by flo2ksmarthome** [AlexxIT/XiaomiGateway3#61]
How can i connect a Rubik's cube (XMMF01JQD) to my HA with ZNDMWG03LM? I want to use my cube as an sensor for my smarthome as shown in https://www.youtube.com/watch?v=4D_vqvUre_0.
Thanks for your help
Florian

**Comment by AlexxIT** [comment]
It should be added to Mi Home. And there are instructions on how to enable automation. You need to rotate one of the faces quickly 4 times. After this, events from the cube will begin to come to the HA.

**Comment by flo2ksmarthome** [comment]
Thanks, initial rotation 4 times helped to get my cube working in mi home, events are correctly registered, but no event is pushed to HA, how long does is take usually to receive events in HA?

**Comment by AlexxIT** [comment]
Instantly. Try reboot gw.

**Comment by flo2ksmarthome** [comment]
perfect, great job, reboot of HA and hub helped...
