### ISSUE TITLE
Cannot update Gateway 3

### ISSUE THREAD

**Issue by Soused19** [AlexxIT/XiaomiGateway3#619]
Hi, I have a Gateway 3 (lumi.gateway.mgl03) running on 1.4.6_0012 and MiHome offer update to 1.4.7_0160.
So I turn off Firmware Lock and try update but everytime it return error: "Upgrade failed, please retry later"
I try power off and on, but same error.

Earlier I flashed firmware via UART 

Please can me help?

THX, David

**Comment by AlexxIT** [comment]
Try to turn on and off firmware lock again. Also telnet to gateway and remove:

- /data/firmware.bin
- /data/firmware/* (leave empty folder)

**Comment by Soused19** [comment]
OK, i updated via telnet and looks fajn

![image](https://user-images.githubusercontent.com/75944845/153024244-7eaca1e3-66ae-4fb7-b4a9-1c80ba5467c0.png)
![image](https://user-images.githubusercontent.com/75944845/153025348-2470eba3-56e3-4b45-8607-7ea4fa1680d3.png)

But after that the gateway cannot connect to HA

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
