### ISSUE TITLE
zigbee GZCGQ01LM has battery state UNKNOWN

### ISSUE THREAD

**Issue by rbron01** [AlexxIT/XiaomiGateway3#626]
Hi Alex

Thanks for the great new release.

I saw that Xiaomi apparantly changed the battery status for the Light Sensor GZCGQ01LM.

In the Xiaomi Home app is the status of the battery moved to Consumbles in the profile menu.
Works now similar to the device WSDCGQ01LM.

Could you maybe have a look at it?

Regards
Rene.

**Comment by AlexxIT** [comment]
What version of the gateway firmware do you have? Can you show a screenshot of MiHome with the battery info?

**Comment by rbron01** [comment]
I am using version 1.5.1_0032 on the Chinese Mainland Server.

![IMG_7317](https://user-images.githubusercontent.com/61490695/153412715-a520ab99-d74b-4726-8389-f145758501d0.PNG)
![IMG_7316](https://user-images.githubusercontent.com/61490695/153412741-8cb945f4-198a-4489-a784-235dc10b4d6d.PNG)
![IMG_7315](https://user-images.githubusercontent.com/61490695/153412730-f2a40116-dd84-4400-b5ee-77a20eae1357.PNG)

**Comment by zvldz** [comment]
on fw 1.5.1_0032 there is a problem with getting the battery on this sensor.
try fw 1.5.0_0102

**Comment by rbron01** [comment]
Its not that important to move to a lower version which may cause other issues.
Shall we close this one then?

**Comment by AlexxIT** [comment]
Battery for GZCGQ01LM don't work on fw 1.5.1_0032
