### ISSUE TITLE
No response to switch presses in HASS

### ISSUE THREAD

**Issue by VitaLSHEL** [AlexxIT/XiaomiGateway3#627]
FW: 1.5.0_0102
Integration:2.0.*

When manually switching the state of an object in HASS, nothing happens, the state of the object returns to the previous one.
log warning: Logger: asyncio
Source: /usr/local/lib/python3.9/asyncio/selector_events.py:911
First occurred: 19:03:31 (84 occurrences)
Last logged: 19:19:23

socket.send() raised exception.

**Comment by AlexxIT** [comment]
Can you provide more info. This is error not from this integration

**Comment by igogold** [comment]
Однако сообщение возникает именно при попытке послать через шлюз команду на включение/выключение зигби розетки. Перезапуск Home Assistant помог, но надолго ли?

Перед тем, как перестало работать, через новый интерфейс запускал процесс сопряжения по зигби. Может быть, шлюз заглючил и начал игнорировать присылаемые команды, потому send() приводил к исключению? Буду наблюдать дальше.

С учётом того, что через эти зигби розетки отапливается помещение, не хотелось бы, чтобы оно снова заглючило.

**Comment by AlexxIT** [comment]
Check if v2.0.3 helps

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
