### ISSUE TITLE
Совместимость с вешалкой Mr.Bond

### ISSUE THREAD

**Issue by abcjoint** [AlexxIT/XiaomiGateway3#63]
Возможно ли, используя данную интеграцию подключить вешалку Mr.Bond (mrbond.airer.m1pro)?
Если нет, то планируется ли обновление с поддержкой этого устройства?

**Comment by AlexxIT** [comment]
Это Wi-Fi устройство. Шлюза не касается. К этому проекту вопрос https://github.com/rytilahti/python-miio
