### ISSUE TITLE
ZNDMWG03LM Firmware Lock & Pair become unavailable after updated to v2.0

### ISSUE THREAD

**Issue by aes-alienrip** [AlexxIT/XiaomiGateway3#633]
Firmware: 1.5.1_0032
Reboot ha / gateway doesn't work

**Comment by maybeloveu** [comment]
MJZNMS02LM  after updated to v2.0  become unavailable.

**Comment by AlexxIT** [comment]
@aes-alienrip Old gateway entities with `0x` in name are deprecated.

@maybeloveu problem with BLE lock is known problem. Will be fixed
