### ISSUE TITLE
WXKG17LM (lumi.remote.acn004) incorrect battery level

### ISSUE THREAD

**Issue by nefedovd** [AlexxIT/XiaomiGateway3#638]
<img width="1025" alt="Снимок экрана 2022-02-10 в 07 08 37" src="https://user-images.githubusercontent.com/48727599/153341558-d92c6c61-d2c5-4cd1-a365-c4eaf61530d5.png">

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release
