### ISSUE TITLE
status is not updated

### ISSUE THREAD

**Issue by Agenciate** [AlexxIT/XiaomiGateway3#64]
I have integrated the xiaomi gateway 3 with all its devices, I can see them in HA, but the statuses are not updated either in HA or in my home application. For example the door sensor is always closed and does not change to open.

How could I fix this?

**Comment by AlexxIT** [comment]
Try reboot gw.

**Comment by Agenciate** [comment]
I restarted the gateway and linked the sensors again and now it's going well.

Thank you very much for your work and attention
