### ISSUE TITLE
in v2.01&v2.02 Aqara Roller Shade E1 can't show the state or position

### ISSUE THREAD

**Issue by casatift** [AlexxIT/XiaomiGateway3#643]
cover can be control by set position, but the state always display unkonwn,  and position is 0.

**Comment by AlexxIT** [comment]
You need to collect logs

**Comment by casatift** [comment]
log show:
Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 09:47:34 (1 occurrences)
Last logged: 09:47:34

Unable to find referenced entities cover.0x54ef4410000d4557_motor

**Comment by AlexxIT** [comment]
This is some problem in your automations

**Comment by szymucha94** [comment]
Had the same issue - it was fixed in recent integration updates.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
