### ISSUE TITLE
Wrong Report of Devices Attached to Gateway.

### ISSUE THREAD

**Issue by guardianbs** [AlexxIT/XiaomiGateway3#650]
When zigbee devices are moved from one Gateway to another Gateway (delete from old Gateway, add to new Gateway) the Gateway Child Devices are reported correctly by the MiHome app. In Home Assistant the devices are shown correctly in Devices as being attached to the new Gateway but they are also still shown in Devices as being attached to the old Gateway, i.e. they appear to be attached to 2 Gateways. 

2 Motion sensors, a Six Button Switch and a Two Button Switch were moved from one Gateway to another.

The Child Devices are reported correctly using Gateway Command / Data display.

Restarting HA made no difference.

2 Gateways ZNDMWG03LM, first gateway on firmware 1.4.7_0115 the second on firmware  1.5.0_0102. Integration version v2.0.3.

![image](https://user-images.githubusercontent.com/71522772/153918550-503a528a-3a1e-472c-8d5d-59d61b807f30.png)

**Comment by guardianbs** [comment]
**Update**: The Devices are shown as being attached to 2 Gateways but there is only one copy of the Entities which shows up under each copy of the Devices.

**Comment by guardianbs** [comment]
Some time and no comments so 2 questions
1.  Is this an issue with the Integration or with hass, i.e. whose responsibility is it to delete devices from a gateway when they are moved to a new gateway ?
2.  Is there any way to manually delete devices from a gateway and if not should the Integration or hass provide the function.

**Comment by AlexxIT** [comment]
This is how Hass works. Displaying the device in two integrations at the same time does not affect anything.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
