### ISSUE TITLE
Device trigger for buttons in integration version 2+

### ISSUE THREAD

**Issue by ghostss2016** [AlexxIT/XiaomiGateway3#658]
WXKG06LM  not support action key

**Comment by AlexxIT** [comment]
What you mean?

**Comment by Smosia** [comment]
I think he is talking about problem with automatization triggers. 
In previous version of component, you could choose single/double button click  on wall switch aqara e1 or d1 as trigger in GUI for automatization. 

In new release there is no such option. 

This code works on both versions:
trigger:
  - platform: device
    device_id: 60c035474bdf1ce71620513d37cbe4b2
    domain: xiaomi_gateway3
    type: button_1
    action: single

But in 2 version GUI shows unsupported trigger, but it works. 

![IMG_20220217_230216_995](https://user-images.githubusercontent.com/3935484/154563166-680448d9-e437-4f61-8766-563f5aeaffe6.jpg)

Problems with:
- lumi.remote.b286acn02
- lumi.switch.b2lc04

**Comment by ghostss2016** [comment]
Yes. It is problem.

**Comment by AlexxIT** [comment]
You may check latest master version

**Comment by Smosia** [comment]
Looks like everything works good. 
Thank you
