### ISSUE TITLE
Question about other Wi-Fi devices

### ISSUE THREAD

**Issue by ajdezigns** [AlexxIT/XiaomiGateway3#66]
### Question about other Wi-Fi devices.

Hi Alexx, I had a question about the cloud update you did to your integration. Now that your integration pulls data about all devices on someone's account it has me wondering if it would be possible and control devices other then the hub such as the linp.doorbell.g03 for example.

**Comment by AlexxIT** [comment]
The miio library developers are discussing this feature. I didn't plan on doing this. It's a lot of work and I personally don't have time for it.
