### ISSUE TITLE
cannot add integration after installing in hacs

### ISSUE THREAD

**Issue by Vaskes1986** [AlexxIT/XiaomiGateway3#660]
Install integration in hacs.
But when I try to add it in integrations receve such error
Error occurred loading configuration flow for integration xiaomi_gateway3: cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py)

**Comment by AlexxIT** [comment]
What Hass version do you use?

**Comment by Vaskes1986** [comment]
Home Assistant 2021.5.4
Home Assistant Community Store Installed Version	1.15.2

**Comment by AlexxIT** [comment]
This is very old Hass version. It isn't supported
