### ISSUE TITLE
"Unkown error ocurred" when setting up Gateway

### ISSUE THREAD

**Issue by marcpages** [AlexxIT/XiaomiGateway3#662]
When trying to set up the gateway I get "Unkown error ocurred"

![image](https://user-images.githubusercontent.com/6256151/154807807-ffa55108-0226-4baa-9530-7e6b84e8435d.png)

See the core ouput:
![image-2-](https://user-images.githubusercontent.com/6256151/154807872-d2573c7f-5608-43c2-8131-a72aac37f416.png)

Ping to gateway IP from hassio server works.

I've also tried miiocli

![log (1)](https://user-images.githubusercontent.com/6256151/154808180-37e61ddf-2baf-497e-99d5-02acbfbab3a0.png)

Gateway is automatically found using cloud integration:

![image-3- (1)](https://user-images.githubusercontent.com/6256151/154808107-d5e8bdec-f892-43ed-b06e-b8e5ca7c914b.png)

Xiaomi Gateway 3
Gateway firmware: 1.5.0_0026
Core: 2022.2.9
HassOS: 7.4
Hacs: 1.22.0
XiaomiGateway3: 2.0.5
Raspberry PI 4

Can you help on that?

Thanks

**Comment by And221084** [comment]
добавляюсь, прошивка 1.5.1.0032 телнет больше нет

**Comment by AlexxIT** [comment]
Did you do everything from the readme?

https://github.com/AlexxIT/XiaomiGateway3#network-configuration

**Comment by gyulkiller** [comment]
I am also experiencing the exact same problem.  The error message is exactly the same.  Is it resolved?

**Comment by gyulkiller** [comment]
I changed XiaomiGateway3 to 2.0.4. It goes without any problem.  Perhaps there is a bug on latest 2.0.5.

**Comment by AlexxIT** [comment]
Fixed in latest release
