### ISSUE TITLE
Ikea motion sensor

### ISSUE THREAD

**Issue by giorgio190** [AlexxIT/XiaomiGateway3#663]
Hi, i tried to add an ikea motion sensor by true ui. The sensor seems to be added succesefully (Data: Paired b4xxxxxxxxx (TRADFRI Motion sensor) but there isn't any correlated entity.

Thanks

**Comment by AlexxIT** [comment]
You need to write converter for support this model

**Comment by giorgio190** [comment]
> You need to write converter for support this model

Ok i'll try... thanks

**Comment by giorgio190** [comment]
I've tried but no luck...someone was able to write the converter?

Thanks

**Comment by AlexxIT** [comment]
I don't have time to write converters for 3rd party zigbee devices
