### ISSUE TITLE
After Gateway Reboot BT Mesh Groups not responding

### ISSUE THREAD

**Issue by ezhische** [AlexxIT/XiaomiGateway3#668]
After gateway reboot mesh groups not responding in home assistant(active but not switch), but lamps in this groups works normal from HA.
Only way to get it work is to swith on and off in MiHome app and after restart integration, then it works until next gateway reboot.
HA 2021.02.8
Component 2.0.5

**Comment by dumbodumbos** [comment]
Да, есть такая проблема. Причем интересный момент - у меня 3 группы, но отваливается рандомно только 1 из 3 х при перезагрузках HA, причем не каждый раз.

**Comment by dumbodumbos** [comment]
После перехода с 32 битной ОС на 64 бита ( ХА стоит в докере ) - глюк пока не повторялся.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
