### ISSUE TITLE
Unable to get gateway to work after latest update from HACS

### ISSUE THREAD

**Issue by bgbaker** [AlexxIT/XiaomiGateway3#671]
Hi - I recently updated the component through HACS (although not sure from what version)
The gateway was no longer responding in Home Assistant
The logs just showed the component attempting to start and then nothing further
I decided to re-install from scratch.
I successfully configure the cloud connection and it shows me the gateway and BLE devices connected to it.

I then attempt to install the Gateway integration and it looks to be expecting the "Open Telnet Command" part but does not accept this.:
![image](https://user-images.githubusercontent.com/4025207/154963706-a8d071bb-9136-47f5-a2c3-c76d9a416f01.png)

`{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}`

It simply says "Unknown Error Occured"
![image](https://user-images.githubusercontent.com/4025207/154963870-759f42a3-7e6a-4da7-b728-707ad331cbc0.png)

My gateway is on firmware 1.4.6_0012:
![image](https://user-images.githubusercontent.com/4025207/154963974-d4580be1-8301-42ac-acca-369682d7b698.png)

Should I be attempting to update the firmware? How would I go about that if I cant get the Open Telnet command to work?

Would really appreciate your assistance

**Comment by AlexxIT** [comment]
This is bug from v2.0.5, you can downgrade component version.

And your gateway firmware is supported in a very limited way.

**Comment by bgbaker** [comment]
Thanks @AlexxIT 
I tried version 2.0.4 and seem to be getting the same behavior. Wants the open telnet command.
Which version should i downgrade to?

**Comment by AlexxIT** [comment]
Check carefully which version of the integration you have installed

**Comment by AlexxIT** [comment]
"Unknown Error Occured" fixed in latest integration versions.

"Not all required fields are filled in" - it's a "valid" error

**Comment by bgbaker** [comment]
Hi @AlexxIT - what do you mean by the latest integration versions?
and what would I enter into the "Open telnet command" field? I have never had to do this and it was working before

**Comment by bgbaker** [comment]
OK i see that 2.0.6 is out - i installed that and then used this for the "Open telnet command" and all is working
`{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}`

Thank you very much @AlexxIT
