### ISSUE TITLE
Xiaomi smart door lock 1s(XMZNMSS08LM) is not supported

### ISSUE THREAD

**Issue by Miaoerr** [AlexxIT/XiaomiGateway3#673]
I successfully added Xiaomi Mijia smartmulti mode gateway using this plug-in，but I found that there was no additional action on my door lock。
![image](https://user-images.githubusercontent.com/49992926/155068365-58a9ca40-2108-411b-990a-54b5f5b2cc26.png)

Information about my door locks：
**lumi.lock.bmcn04
XMZNMSS08LM
https://home.miot-spec.com/s/3641**

I didn't find this model in the document or issue. Do youI consider supporting it later, or can you tell me why can't support this model, or how can I help realize this part of the function, because I know some programming may have some help

**Comment by AlexxIT** [comment]
You need to enable logs and do actions with your lock. Also you need to use recommended gateway firmware

**Comment by Miaoerr** [comment]
> You need to enable logs and do actions with your lock. Then post results here. Also you need to use recommended gateway firmware

OK, the firmware versions of my Xiaomi Mijia smartmulti mode gateway are 1.5.1_0032, I will try to do actions and then post results here

**Comment by Miaoerr** [comment]
Sorry, I found that this plug-in supports xmznmss08lm. After I configured and used my door lock again, the plug-in has worked normally.Thank you very much for your research!

**Comment by 602293544** [comment]
朋友，你的门锁会不会时不时变成不可用？插件用的哪个版本 固件我也是151.0032

**Comment by Miaoerr** [comment]
> 朋友，你的门锁会不会时不时变成不可用？插件用的哪个版本 固件我也是151.0032

刚看了一下，是会有这个问题，不过我之前参考了别人的模板写了自动化每次Action变化会记录当时的状态存到新的变量里，然后用新的变量作为后续自动化的判断，所以没有受到影响
