### ISSUE TITLE
Can't patch Bluetooth utility with v2.0.6 and latest HA

### ISSUE THREAD

**Issue by Sol1in** [AlexxIT/XiaomiGateway3#674]
Hello, starting from upgrade to v2.0.x of Xiaomi Gateway, mesh groups stopped working properly. It seems that HA/XG3 cannot get state of the mesh group. I can turn on the light and it works, but almost instant it becaming looks like it is off in HA (but in fact the light is still on). If I switching it on and off fast - mesh-light turn off.
No issues for exact lamps - only for mesh groups.
I have several XG3 in my configuration, was tried to turn off Bluetooth Mesh Gateway on all but one but with no any changes.

I found this think in logs:
```
Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/gateway/base.py:77
Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues)) 
First occurred: 00:20:03 (2 occurrences) 
Last logged: 00:23:52

192.168.0.206 | Can't patch Bluetooth utility
```

There were no issues with old version of XG3 module.
I upgrade XG3 to newest firmware but with no changes in described behaviour.

**Comment by AlexxIT** [comment]
Are you sure you are using a supported gateway firmware?

**Comment by zvldz** [comment]
Why did you update the firmware?

**Comment by itourinan** [comment]
I saw in the HA log that the firmware I was using was limited so I updated it to the latest version. 

After that error I downgraded it to v1.5.0_0102 and it's fine now.

**Comment by Sol1in** [comment]
So I downgraded each of 4 XG3 to v1.5.0_0102, but still some of the BT Mesh Groups remain unavailable (random on each restart). Looks like HA is trying to get info only through one single XG3 and if the group is unavailable on it - it became unavailable in HA (in MiHome or Yeelight App it is still working). Seems like a bug.

**Comment by maury77** [comment]
I have the same problem

2022-02-27 20:15:08  DEBUG    main          SysInfo: {'installation_type': 'Unknown', 'version': '2022.2.5', 'dev': False, 'hassio': False, 'virtualenv': False, 'python_version': '3.9.9', 'docker': False, 'arch': 'armv6l', 'timezone': 'Europe/Rome', 'os_name': 'Linux', 'os_version': '5.10.63+', 'user': 'homeassistant'}
2022-02-27 20:15:19  ERROR    base          192.168.1.52 | Can't patch Bluetooth utility
-----
2022-02-27 20:51:39  ERROR    base          192.168.1.52 | Can't patch Bluetooth utility

**Comment by hsu32** [comment]
I have the same problem,too.

**Comment by nayaabkhan** [comment]
@itourinan Can you direct me to the instructions for downgrading?

**Comment by NicusorFlorinBaluta** [comment]
@AlexxIT any hope to add support for 1.5.4_0052? Or some easy to follow instructions to downgrade to v1.5.0_0102? Please

**Comment by nayaabkhan** [comment]
I was successfully able to downgrade to `v1.5.0_0102` using instructions here: https://github.com/zvldz/mgl03_fw/tree/main/firmware

**Comment by NicusorFlorinBaluta** [comment]
thanks man, i will try the same !

**Comment by nayaabkhan** [comment]
After setting up the integration with HA, make sure to lock the firmware to prevent reflexive upgrading :)

<img width="684" alt="Screenshot 2022-07-25 at 1 27 01 PM" src="https://user-images.githubusercontent.com/234889/180727308-f4fce225-1234-40ad-9da8-0ed2c7b2d30f.png">

**Comment by NicusorFlorinBaluta** [comment]
unfortunately i also did the stupid thing of upgrading the firmware of the window sensors so after downgrading the gateway, the sensors aren't picked up anymore

**Comment by AlexxIT** [comment]
@NicusorFlorinBaluta Support for 1.5.4 will not be available in the near future. Lots of changes. I don't have time for it yet. And there's not much of a profit in maintaining it.

**Comment by gartz** [comment]
I tried a lot of things to lock the firmware, but it always autoupdate to 1.5.4 and stop working, and I downgrade manually, but now the BLE keeps failing even after the downgrade.
