### ISSUE TITLE
Ble mesh curtain motor cannot be controlled

### ISSUE THREAD

**Issue by lclGithub** [AlexxIT/XiaomiGateway3#676]
Ble mesh curtain motor cannot be controlled. The recognized type is light,Can it be repaired?
Model：LS intelligent curtain motor

**Comment by AlexxIT** [comment]
Show model from device page on Hass

**Comment by lclGithub** [comment]
![网页捕获_23-2-2022_13221_192 168 31 70](https://user-images.githubusercontent.com/19635495/155266787-7fb6caec-177a-491c-afc5-c8f5597770bc.jpeg)
![网页捕获_23-2-2022_131939_192 168 31 70](https://user-images.githubusercontent.com/19635495/155266797-4251918a-624c-47e3-96d2-bc911ddd50da.jpeg)
![网页捕获_23-2-2022_132048_192 168 31 70](https://user-images.githubusercontent.com/19635495/155266798-128bb1eb-785a-4575-aeb2-897b7e2172ff.jpeg)
![网页捕获_23-2-2022_132358_192 168 31 70](https://user-images.githubusercontent.com/19635495/155266800-2d632848-8976-41f1-9e79-52efd5e1d1df.jpeg)

**Comment by lclGithub** [comment]
> 

ok

**Comment by AlexxIT** [comment]
It takes a long time to add this device. You may be able to do it yourself

https://home.miot-spec.com/s/5195
https://github.com/AlexxIT/XiaomiGateway3/wiki/Converters

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
