### ISSUE TITLE
Aqara LLKZMK11LM interlock

### ISSUE THREAD

**Issue by aerastov** [AlexxIT/XiaomiGateway3#68]
Алексей!
Спасибо за проделанную Вами работу!
Прошу рассмотреть возможность включения режима interlock на реле aqara средствами Home assistant. 
Через приложение михоум на данный момент это сделать невозможно (пробовал разные регионы, версию от vevs, ничего не дало результат).

**Comment by AlexxIT** [comment]
Adds support. Will be in next beta/release version
