### ISSUE TITLE
Not responding after burst action then resuming with queued action

### ISSUE THREAD

**Issue by stu85010** [AlexxIT/XiaomiGateway3#680]
Hello there,

I’m using zigbee2mqtt mode with Xiaomi Gateway3(CN) with version `v1.5.0_0102`. I got trouble to control many device at a time with Automation controls from Home Assistant, no matter the system is just boot or not, this issue could happen with specific procedure. Also, I had simplified the scenario of the reproducing procedure with only 3 to 4 devices.

## Simplified Reproducing Scenario
1. Two group of device, 
    - group 1 has (light switch A and B)
    - group 2 has light switch C
    - group 3 has light switch D
2. Each group controlled by Automation from Home Assistant:
    - Automation 1 triggers a toggle action to light switch A and B
    - Automation 2 triggers a toggle action to light switch C
    - Automation 3 triggers a toggle action to light switch D
3. The automation will be triggered by 3 Zigbee push buttons which is also connected to zigbee2mqtt
    - Push button 1 triggers the automation 1
    - Push button 2 triggers the automation 2
    - Push button 2 triggers the automation 3
4. This issue occurred when these push button is pressed too fast, like the burst triggering condition

## Reproducing Procedure
1. To avoid the confusion of the system works unexpectedly when boot long time ago, restart the Xiaomi Gateway and zigbee2mqtt, MQTT server
2. Restart home assistant and wait all integration ready
3. Open zigbee2mqtt log monitor, watch all log
4. Open panel of these two Automation from Home Assistant
5. Continuously clicking push button 1 and watch if the light A and B is toggling
6. After clicking 20~30 times, when you see the light A and B is not toggling, click push button 2 for 1 time then click push 3 button for 1 time
    - You may find the push button’s event is sent from zigbee2mqtt, to MQTT and to Home Assistant on time.
7. After few seconds later(sometimes it is 10-20sec, sometimes 2-3 minutes) you will see:
    1. Light A and B toggle few times in a very short interval, then  
    2. Light C toggles for one time and
    3. Light D toggles for one time

## The Unexpectedly Behavior
The corresponding action of push button 2 and 3 should be responded immediately during that test, not like, the command of button is queued for a long time ago, and the old command is executing when everybody leaved the house

## Expected Behavior
I don’t know if this phenomenon is just in your design or not, I’m wondering if we could decide the timeout and if some action stuck, it should be killed for system to respond the rest of command.

**Comment by stu85010** [comment]
> I believe you have to open an issue in z2m repository as integration does nothing with zigbee in z2m/zha mode.

I thought this issue might be relevant to both z2m or the modified firmware, because the Zigbee receiving feature is worked well during the no responding time.

If this is an issue from the modified firmware `v1.5.0_0102`, this repository is the right place or could you help me to reach the right repo? If this is an issue from z2m, should I forward this issue to [Koenkk/zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt)?

BTW, I had recorded the screen for your reference at [https://youtu.be/H0Drxy6d-q0](https://youtu.be/H0Drxy6d-q0)

**Comment by vturekhanov** [comment]
You can start here: https://github.com/Koenkk/zigbee-herdsman/issues/319
Please keep in mind ezsp support in z2m is currently experimental.

**Comment by AlexxIT** [comment]
@vturekhanov thanks!
