### ISSUE TITLE
lumi.curtain.acn002 no feedback/displayed as "closed" always.

### ISSUE THREAD

**Issue by KnNLmS** [AlexxIT/XiaomiGateway3#688]
Hi,

I have 3 pcs ZNJLBL01LM "Aqara Roller Shade Driver E1" connected via ZNDMWG02LM "Mi Smart Home Hub". The integration "Xiaomi Gateway 3" is working well for all equipments and it is the latest version (v2.0.6).

The only problem is about the feedback of Roller Shades. The command working on slider. But the feedback never being available and the HA always shows closed. Related to that issue Close command button not available (arrow down), but open command button always available .

Slider works always properly for sending commands.

Thanks.

**Comment by AlexxIT** [comment]
Very similar to #653 and probably fixed in latest master version

**Comment by KnNLmS** [comment]
> Very similar to #653 and probably fixed in latest master version

No, the problem reported on the latest version.

**Comment by AlexxIT** [comment]
Are you sure you've tried the **master** version?

**Comment by AlexxIT** [comment]
Check latest release
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v2.0.7

**Comment by KnNLmS** [comment]
Well fixed. Thanks.
