### ISSUE TITLE
Fail in battery Xiaomi TH Sensor (LYWSD03MMC) "unit_of_measurement"

### ISSUE THREAD

**Issue by GaLaXiaN-Z** [AlexxIT/XiaomiGateway3#69]
I have recently acquired one of these devices is the Xiaomi TH Sensor (LYWSD03MMC) that works through BLE, but when it gives me the entities for HA, the battery entity does not show the%, I do not know if it is my fault only or is it generalized for this reason I wanted to comment on it here, in case it is a general failure.
Sorry for my google-english.

**Comment by AlexxIT** [comment]
Fixed earlier
