### ISSUE TITLE
Aqara Opple Six Button does not allow to use same buttom more than one time

### ISSUE THREAD

**Issue by anasm2010** [AlexxIT/XiaomiGateway3#7]
When we triger a button, 1 for example, an event is received. however when we re trigger the same button, no event is received. 

Mb we can use the same solution as for long press, an event request is received on the long press and then we release the button and a release request is received. that can change the state of a button from pressed -> to released -> pressed ... and not be blocked on the sate of pressed only.

**Comment by AlexxIT** [comment]
I know. Will fix it.

**Comment by AlexxIT** [comment]
Fixed
