### ISSUE TITLE
Can you please in a future try support this device also? 

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/XiaomiGateway3#70]
Hello 

An first of all thank you for your work, now it is possible to get the BLE and MESH ble devices in the Home Assistant, Great !!

I just have a request that is to also in the future if possible to suporte the new Gateway Yeelight 

Thank you and best regards

**Comment by AlexxIT** [comment]
Oh. I don't have this gw. And don't have time to support all devices on the market :)

**Comment by MiAutomations** [comment]
Ok I understand. 

I just have received my in this past days, I tested with your integrations but the device is not supported ... I just have requested because it's a new gateway only for the BLE and Mesh BLE devices, and in my opinion, It can be a complement of the people that already have other xaiomi zigbee gateways integrated in the home Assistant from other ways...

Thank you 👍

**Comment by rezmus** [comment]
this integration depends on easy way to open telnet connection to the gateway. there is not such thing in yeelight hub.

**Comment by Zuz666** [comment]
@AlexxIT It's interesting! XiaomiGateway3 can be managed through local miIO protocol (basic commands works fine). Why we need telnet hack?

**Comment by rezmus** [comment]
with miio you can only push actions to zigbee devices (turn on/off plug) or pull state (property) of sensors (plug on/off). you can't subscribe for events like motion event, door open event, etc. you can't read state of ble devices and some more stuff you can't do without full access like zha.

**Comment by Zuz666** [comment]
@rezmus, yep but we can use workaround like this: https://github.com/rytilahti/python-miio/pull/703 (core of idea: https://github.com/rytilahti/python-miio/pull/703/commits/8baf9e802eb6a15686ac5de8816b247ac2d96993)

**Comment by rezmus** [comment]
i know this project, but it's like licking a lollipop through a piece of paper compared to telnet access. last time i checked they did not even had the algo to hash token used in automation. also automation in 3rd gateway is saved in different way.

**Comment by Zuz666** [comment]
@rezmus in this case, this project can't have a future, because the new firmware does not allow access to telnet.  My questions related to the possibility of developing this integration using a miIO protocol, which is used by all applications of the ecosystem.

**Comment by rezmus** [comment]
there are a ways to restore telnet access or keep it after update. when lumi closed lan/dev mode in mijia v2 hub so ppl had to solder uart to open it again nobody said existing integration had no future ;)

there are already some projects started to build custom firmware for this hub that will make it independent from the vendor. like openwrt based firmware  for v2 eu/aqara hub https://github.com/openlumi/owrt-installer

still i think that at some point such stripped miio integration for v3 will be made.

**Comment by Zuz666** [comment]
> still i think that at some point such stripped miio integration for v3 will be made.
That's what it's all about. On prospect it makes sense to do integration using the protocol that the ecosystem natively uses.

**Comment by Zuz666** [comment]
@MiAutomations I checked the collaboration of these devices, if the network has Xiaomi Gateway 3 and Yeelight Mesh Hub, then the BLE Mesh devices on Yeelight Mesh Hub are transparently managed through this integration.

**Comment by AlexxIT** [comment]
@Zuz666 Mesh devices are not attached to any hub. They can be controlled from any hub on the network that "reaches" them.

**Comment by Zuz666** [comment]
> Mesh devices are not attached to any hub.

@AlexxIT but when you check it in MiHome app you can see devices are distributed between gateways / hubs with BLE Mesh support. I think that device is the main one and it used by the gateway when sends a command to the certain BLE Mehs device. I need check it (traffic sniff), but it seems logical.
```HA->AlexIT_XG3->(miIO)->XG3->(miIO)->Yeelight Mesh Hub -> (BLE) -> Device```

**Comment by AlexxIT** [comment]
@Zuz666 I think in the gateway information just recently seen devices. And since this is Mesh technology, the gateway can reach distant bulbs through their neighbors.

**Comment by Zuz666** [comment]
@AlexxIT may be, more research required ;) But my XG3+ Yeelight Mesh Hub and lamp devices at 1-3 meter distance and they are distributed between gateways (hubs): 4+4 devices (8 total). After turning off Yeelight Mesh Hub lamps devices are showing on XG3. When turning on Yeelight Mesh Hub four devices migrate on it.

**Comment by MiAutomations** [comment]
> @MiAutomations I checked the collaboration of these devices, if the network has Xiaomi Gateway 3 and Yeelight Mesh Hub, then the all BLE Mesh devices connected to Yeelight Mesh Hub are transparently managed through this integration.
> @AlexxIT may be you can update faq. It may be helpful.

Yes, I know that. The ideia from my side, is to use this  gateway Yeelight one together with one that only have zigbee protocol and from this way the people can just buy the one for the BLE and mesh BLE in order to have this devices integrated also in the Home Assistant.

**Comment by Zuz666** [comment]
> people can just buy the one for the BLE and mesh BLE in order to have this devices integrated also in the Home Assistant.

@MiAutomations  yep, but XGW3 price is lower than Yeelight Mesh Hub. Just buy XGW3. )))

**Comment by Zuz666** [comment]
@AlexxIT interesting things! After disabling BLE Mesh support on XGW3 all BLE Mesh devices are migrated to Yeelight Mesh Hub (YMH). When I try use LAN automations (for example on /off BLE Mesh bulbs via Zigbee switch) it's not work still I turn on / off this automation in MiHome app. But in Yeelight/MiHome app it works.  Then I turn off YMH and turn off BLE Mesh support on XGW3 devices are migrated to XGW3. To work, this also required turn of/onw the automation in MiHome app.
I think you were right. And XGW3 send command via BLE Mesh network not via YMH. But I can't understand why LAN automation work like described above.
