### ISSUE TITLE
Gateway3

### ISSUE THREAD

**Issue by OldFedor** [AlexxIT/XiaomiGateway3#702]
The Gateway3 is connected. Sensors from the cloud have been detected. 
There is no data from the sensors - "unavailable". 
Do not refuse the courtesy to suggest - how to fix it?
![Рабочий](https://user-images.githubusercontent.com/68902349/158018540-4a1978bb-7df5-45b3-8802-6c266edb905d.jpg)

Sincerely, OldFedor

**Comment by sloncek** [comment]
I have updated the addon to the latest version and it worked from there on.

**Comment by OldFedor** [comment]
I have installed all the updates. The result is the same.

**Comment by AlexxIT** [comment]
Please submit:
- [ ] Hass version
- [ ] Gateway firmware
- [ ] Component version
- [ ] Errors in Hass log
- [ ] Component debug log
