### ISSUE TITLE
KTWKQ03ES（lumi.airrtc.tcpecn02）

### ISSUE THREAD

**Issue by louliangsheng** [AlexxIT/XiaomiGateway3#707]
This thermostat has a temperature range of 17 to 30°C. The temperature precision is "1", not "0.5".
Here are some parameters of this thermostat：
https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aair-conditioner%3A0000A004%3Alumi-tcpecn02%3A1
https://zigbee.blakadder.com/Xiaomi_KTWKQ03ES.html
Thank you very much for the plugin.

**Comment by AlexxIT** [comment]
Added to master version. Will be in next release

**Comment by louliangsheng** [comment]
The temperature range is correct. Can be closed, but cannot be opened. Temperature precision is correct but still can't adjust temperature.

**Comment by louliangsheng** [comment]
The wind speed of the thermostat has four gears: 1 2 3 and automatic. At present, the automatic gear is missing. I suggest that 100% is the automatic gear, 25% is the first gear, and so on.

**Comment by AlexxIT** [comment]
Don't understand what you mean "Can be closed, but cannot be opened".

**Comment by louliangsheng** [comment]
If I turn on the device through mihome or the physical button, it can be turned off through the gw3 plug-in, and the device can indeed be turned off, and then after a period of time, the gw3 plug-in will show that the device is turned on again, but the device is actually turned off.

**Comment by louliangsheng** [comment]
![image](https://user-images.githubusercontent.com/37586254/160272622-b12fe42d-7cb1-446d-a010-e4b12765fdb5.png)
Below are the entity properties of this device for miot auto plugin.


hvac_modes: cool, heat, off
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
current_temperature: 17.9
temperature: 30
fan_mode: High
model: lumi.airrtc.tcpecn02
lan_ip: 
mac_address: lumi.158d000479c864
entity_class: MiotClimateEntity
home_room: 阿辉的小窝 寝室
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:lumi-tcpecn02:1
air_conditioner.on: false
air_conditioner.mode: 2
target_temperature-2-3: 30
fan_control.fan_level: 3
state_updater: cloud
sub_entities: air_conditioner-2.on-1
friendly_name: 空调温控器
supported_features: 9
bind_sensor: sensor.zhimi_ca1_f980_temperature

**Comment by AlexxIT** [comment]
You send nice log earlier. Can you tell what time you have a problem with device?

**Comment by louliangsheng** [comment]
[xiaomi_gateway3.log](https://github.com/AlexxIT/XiaomiGateway3/files/8357446/xiaomi_gateway3.log)
After my tests, I found that the plug-in always thinks that the device is on, so it can't turn on the device, but if I switch to cooling and then switch to heating, it can be turned on normally. Therefore, the plugin has two titles now, one is that it cannot get the correct device status: the plugin always thinks that the device is turned on; the other is that I cannot control the temperature of the device through the plugin.

**Comment by AlexxIT** [comment]
I can't see off state from you device `{"res_name":"14.8.85","value":15}`
Like here: https://github.com/AlexxIT/XiaomiGateway3/issues/111#issuecomment-744447036

**Comment by louliangsheng** [comment]
I tried to close it many times, but neither the home assistant nor the log showed the closing status.
https://user-images.githubusercontent.com/37586254/160285163-6a04e6f5-c1a9-4c5d-8cde-bb494321f408.MOV

**Comment by AlexxIT** [comment]
Can you turn it off from MiHome?

**Comment by louliangsheng** [comment]
> 你能从 MiHome 把它关掉吗？

It can be turned off in mihome, and this device connected through the miot-auto plugin can work normally in homeassistant.

**Comment by louliangsheng** [comment]
Can you add support for hvac-action which makes climate icons look better in homekit.

https://github.com/home-assistant/core/issues/68739
https://developers.home-assistant.io/docs/core/entity/climate?_highlight=hvac_ac#hvac-action
https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/climate.py
![image](https://user-images.githubusercontent.com/37586254/163385841-684d38cc-c130-42a6-95bc-ce14d1bcb25a.png)

**Comment by AlexxIT** [comment]
@louliangsheng check master version

**Comment by louliangsheng** [comment]
@AlexxIT  I updated the plugin, his icon became normal, thank you for your work, but the switch state is still not fixed, now the device is turned off, but it still shows the open state in homeassistant, hope you can fix it, if there is any need You can tell me what I do.
![QQ图片20220415175836](https://user-images.githubusercontent.com/37586254/163560400-87e6464a-a0bb-4153-b941-815acb9dfed4.png)
Also he doesn't look normal now, his wind speed shouldn't be a fan, I've submitted a bug to HA-core.
https://github.com/home-assistant/core/issues/70084

**Comment by AlexxIT** [comment]
As I said earlier - I can't see off state in your logs

**Comment by louliangsheng** [comment]
https://github.com/niceboygithub/AqaraGateway/blob/master/custom_components/aqara_gateway/climate.py
I found a new plug-in, this plug-in, the device status feedback is normal, I don't know if it will help you.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
