### ISSUE TITLE
core-2022.4.0b0 does not work with temperature sensors

### ISSUE THREAD

**Issue by Jo-Jo1987** [AlexxIT/XiaomiGateway3#715]
All my device temperature and humidity sensors do not seem to work on the new version of home assistant core-2022.4.0b0
All other sensors seem to work for some weird reason.
![image](https://user-images.githubusercontent.com/45689992/161120955-29a36be8-04ca-40d7-8225-84c09b1eb8eb.png)
![image](https://user-images.githubusercontent.com/45689992/161121043-1a51d182-f600-4dc3-b91c-9aa8a0d12646.png)

Update, also the alarm settings cannot be changed.

Hopefully you develop a new version for the community soon, thanks in advance

**Comment by Antoni-Czaplicki** [comment]
See #716
