### ISSUE TITLE
Xiaomi(Gosund) swich S6AM

### ISSUE THREAD

**Issue by yq3012** [AlexxIT/XiaomiGateway3#718]
Hello AlexxIT,
This Xiaomi/Gosund switch(cuco.switch.s6amts) is a three-key switch, now gateway3 just recognize one key,  could you help to add more entities . 
very appreciated.

**Comment by AlexxIT** [comment]
Please show device page in Hass

**Comment by yq3012** [comment]
![pic1](https://user-images.githubusercontent.com/100590266/162618382-b68d85d0-cee8-4bbb-b969-2561a4ad5a46.PNG)

**Comment by yq3012** [comment]
{"type":"urn:miot-spec-v2:device:switch:0000A003:cuco-s6amts:2:0000C810","description":"Three Key Switch","services":[{"iid":1,"type":"urn:miot-spec-v2:service:device-information:00007801:cuco-s6amts:1:0000C810","description":"","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:manufacturer:00000001:cuco-s6amts:1:0000C810","description":"Device Manufacturer","format":"string","access":["read"]},{"iid":2,"type":"urn:miot-spec-v2:property:model:00000002:cuco-s6amts:1:0000C810","description":"Device Model","format":"string","access":["read"]},{"iid":3,"type":"urn:miot-spec-v2:property:serial-number:00000003:cuco-s6amts:1:0000C810","description":"Device Serial Number","format":"string","access":["read"]},{"iid":4,"type":"urn:miot-spec-v2:property:firmware-revision:00000005:cuco-s6amts:1:0000C810","description":"Current Firmware Version","format":"string","access":["read"]}]},{"iid":2,"type":"urn:miot-spec-v2:service:switch:0000780C:cuco-s6amts:1:0000C810","description":"Left Switch Service","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:cuco-s6amts:1:0000C810","description":"Switch Status","format":"bool","access":["read","write","notify"]}],"actions":[{"iid":1,"type":"urn:miot-spec-v2:action:toggle:00002811:cuco-s6amts:2","description":"Toggle","in":[],"out":[]}]},{"iid":3,"type":"urn:miot-spec-v2:service:switch:0000780C:cuco-s6amts:1:0000C810","description":"Middle Switch Service","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:cuco-s6amts:1:0000C810","description":"Switch Status","format":"bool","access":["read","write","notify"]}],"actions":[{"iid":1,"type":"urn:miot-spec-v2:action:toggle:00002811:cuco-s6amts:2","description":"Toggle","in":[],"out":[]}]},{"iid":4,"type":"urn:miot-spec-v2:service:switch:0000780C:cuco-s6amts:1:0000C810","description":"Right Switch Service","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:cuco-s6amts:1:0000C810","description":"Switch Status","format":"bool","access":["read","write","notify"]}],"actions":[{"iid":1,"type":"urn:miot-spec-v2:action:toggle:00002811:cuco-s6amts:2","description":"Toggle","in":[],"out":[]}]},{"iid":7,"type":"urn:miot-spec-v2:service:switch:0000780C:cuco-s6amts:2","description":"All Switch Service","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:cuco-s6amts:2","description":"Switch Status","format":"bool","access":["read","write","notify"]}]},{"iid":5,"type":"urn:cuco-spec:service:setting:00007801:cuco-s6amts:1","description":"setting","properties":[{"iid":2,"type":"urn:cuco-spec:property:temperature:00000002:cuco-s6amts:1","description":"temperature","format":"uint8","access":["read","notify"],"value-list":[{"value":0,"description":"Normal"},{"value":1,"description":"Overload"}]}]},{"iid":6,"type":"urn:cuco-spec:service:wireless-switch:00007802:cuco-s6amts:1","description":"wireless-switch","properties":[{"iid":1,"type":"urn:cuco-spec:property:on:00000001:cuco-s6amts:1","description":"on","format":"uint8","access":["read","notify","write"],"value-list":[{"value":0,"description":"Close"},{"value":1,"description":"Open-Close"},{"value":2,"description":"Open-Open"}]},{"iid":2,"type":"urn:cuco-spec:property:middle-on:00000002:cuco-s6amts:1","description":"middle-on","format":"uint8","access":["read","notify","write"],"value-list":[{"value":0,"description":"Close"},{"value":1,"description":"Open-Close"},{"value":2,"description":"Open-Open"}]},{"iid":3,"type":"urn:cuco-spec:property:right-on:00000003:cuco-s6amts:1","description":"right-on","format":"uint8","access":["read","notify","write"],"value-list":[{"value":0,"description":"Close"},{"value":1,"description":"Open-Close"},{"value":2,"description":"Open-Open"}]}]},{"iid":8,"type":"urn:cuco-spec:service:light:00007803:cuco-s6amts:2","description":"light","properties":[{"iid":1,"type":"urn:cuco-spec:property:on:00000001:cuco-s6amts:2","description":"on","format":"bool","access":["read","notify","write"]},{"iid":2,"type":"urn:cuco-spec:property:mode:00000002:cuco-s6amts:2","description":"mode","format":"bool","access":["read","notify","write"]},{"iid":3,"type":"urn:cuco-spec:property:start-time:00000003:cuco-s6amts:2","description":"start-time","format":"uint16","access":["read","notify","write"],"unit":"minutes","value-range":[0,1440,1]},{"iid":4,"type":"urn:cuco-spec:property:end-time:00000004:cuco-s6amts:2","description":"end-time","format":"uint16","access":["read","notify","write"],"unit":"minutes","value-range":[1,1440,1]}]},{"iid":9,"type":"urn:cuco-spec:service:autosetting:00007804:cuco-s6amts:2","description":"autosetting","events":[{"iid":1,"type":"urn:cuco-spec:event:left-switch-on-off:00005001:cuco-s6amts:2","description":"left-switch-on-off","arguments":[]},{"iid":2,"type":"urn:cuco-spec:event:left-one-click:00005002:cuco-s6amts:2","description":"left-one-click","arguments":[]},{"iid":3,"type":"urn:cuco-spec:event:left-double-click:00005003:cuco-s6amts:2","description":"left-double-click","arguments":[]},{"iid":4,"type":"urn:cuco-spec:event:middle-switch-on-off:00005004:cuco-s6amts:2","description":"middle-switch-on-off","arguments":[]},{"iid":5,"type":"urn:cuco-spec:event:middle-one-click:00005005:cuco-s6amts:2","description":"middle-one-click","arguments":[]},{"iid":6,"type":"urn:cuco-spec:event:middle-double-click:00005006:cuco-s6amts:2","description":"middle-double-click","arguments":[]},{"iid":7,"type":"urn:cuco-spec:event:right-switch-on-off:00005007:cuco-s6amts:2","description":"right-switch-on-off","arguments":[]},{"iid":8,"type":"urn:cuco-spec:event:right-one-click:00005008:cuco-s6amts:2","description":"right-one-click","arguments":[]},{"iid":9,"type":"urn:cuco-spec:event:right-double-click:00005009:cuco-s6amts:2","description":"right-double-click","arguments":[]}]}]}

**Comment by AlexxIT** [comment]
Please check latest master version

**Comment by yq3012** [comment]
got it, thank you.

**Comment by jjcszxh** [comment]
good
thank you.
