### ISSUE TITLE
4 BLE sensors are unknown and unavailable （LYWSD03MMC） 

### ISSUE THREAD

**Issue by zhangxin4711** [AlexxIT/XiaomiGateway3#722]
All my device temperature and humidity sensors do not seem to work on BLE gatway.
My gateway is ZNDMWG03LM and other device work well on it except BLE sensors.
Hope you give some advice. 
Thanks.

![image](https://user-images.githubusercontent.com/78671466/162225062-2a26508f-2e1a-4a1b-b949-14087e4388b1.png)

![image](https://user-images.githubusercontent.com/78671466/162225209-9256e8c8-8959-4dec-93c2-e9f2ac5d6e81.png)

![image](https://user-images.githubusercontent.com/78671466/162225293-1012f3d8-d2f1-42a9-abc2-ad8e14c712a6.png)

![image](https://user-images.githubusercontent.com/78671466/162225350-828d790d-5558-4611-93bd-369bb0330a7b.png)

**Comment by AlexxIT** [comment]
What versions of Hass, Integration and Gateway do you have?

**Comment by zhangxin4711** [comment]
> What versions of Hass, Integration and Gateway do you have?

Hass is core-2022.4.1
Integration is v2.0.9
Gateway is 1.54_0052

**Comment by AlexxIT** [comment]
Have you seen your gateway firmware in supported list?
https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares

**Comment by Ruskyy** [comment]
I share of the same problem.
The BLE devices show on the MiHome app connected to the gateway.
They are recognized by the integration, but their values are always unavailable.
Updated firmware to 1.54_0052.
Reinstalled the Integration multiple times.

Running HASS core-2022.4.7.

**Comment by ALERTua** [comment]
https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares :
> "these firmwares are not supported yet: v1.5.4_0XXX"

**Comment by Ruskyy** [comment]
Ended up misstyping mine.
Im actually runninhg 1.5.0.xxx
![image](https://user-images.githubusercontent.com/39529472/167309429-eb56595d-6f7d-4dda-bd27-b595657ae467.png)

The problem still presists.

**Comment by MeowRay** [comment]
同1.5.0_0102
温湿度计传感器，显示不可用
![image](https://user-images.githubusercontent.com/29674595/167414854-6066d08f-59cf-4164-b9ca-87aff4a2e656.png)

**Comment by vampywiz17** [comment]
@AlexxIT 

Same problems... My BLE temperature sensors not send any data... I use the recommended firmware (1.5.0_0102)

In mi home app, it work normally.

**Comment by explayc300** [comment]
Здраствуйте, аналогичная проблема с датчиками LYWSD03MMC
Прошивка шлюза 1.5.0_0102
HAOS 2022.6.6
Интеграция 2.1.0
Датчик движения Qingping CGPR1 работает хорошо.

Есть ли решение данной проблемы?

**Comment by ycg31** [comment]
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
Xiaomi Gateway 3 v2.1.0
gateway 1.5.0_0102

**Comment by AlexxIT** [comment]
For those who are using firmware 1.5.0 - can you see this sensor in MiHome in Gateway child devices screen?

**Comment by vampywiz17** [comment]
@AlexxIT 

Yes, we are see it.

**Comment by grastraa** [comment]
I'm also on 1.5.0 with this issue suddenly occurring after having made no changes. 
I see the BLE devices within the gateway in app (vevs), however it the values displayed are the values that HA last saw before they became unavailable. 

If I click one of my temp sensors, my phones BT is utilised and the current temp is displayed. Returning to the gateways BLE view, the temps are still of the old value.

So it seems to be a issue with the gateway device itself perhaps? 

I'm using a lumi.gateway.mgl03, if that's any help!

**Comment by Ruskyy** [comment]
> For those who are using firmware 1.5.0 - can you see this sensor in MiHome in Gateway child devices screen?

Yup. they all show up perfectly on the Mi App.

**Comment by nathbullen** [comment]
> I'm also on 1.5.0 with this issue suddenly occurring after having made no changes. I see the devices (temp sensors) within the BLE gateway in app (vevs mod), however it the values displayed are the values that HA last saw before they became unavailable.
> 
> If I click one of my temp sensors elsewhere in the app, my phones BT is utilised and the current temp is displayed. However, returning to the gateways BLE view, the temp sensors are still displaying old values.
> 
> So it seems to be a issue with the gateway device itself perhaps?
> 
> I'm using a lumi.gateway.mgl03, if that's any help!

I have exactly the same issue! Exact same devices and firmware versions too
They all went offline at about 6:30pm AEST yesterday and have been unavailable ever since. I can see them in the Mi Home app, but it connects via my phones BT and they seem to not be reporting the correct values to the Mi Hub, which isn't passing on data to HA.

**Comment by grastraa** [comment]
>They all went offline at about 6:30pm AEST 
![image](https://user-images.githubusercontent.com/67679349/181582919-acb788ee-963e-482d-9040-adbc203770cd.png)

Almost exactly hour earlier for me, same timezone

Certainly seems like it isn't an issue with this integration, but Mi Home. 

Out of curiosity...
What region are you set to?
Are you running the modded version of Mi Home? 

I'm running modded and set to the recommended Singapore region

**Comment by AlexxIT** [comment]
*Question only for supported gateway firmwares:*

Do you have another BLE devices? Do they continue to work properly in Home Assistant while LYWSD03MMC unavailable?

**Comment by grastraa** [comment]
Only BLE device I have other than the LYWSD03MMC temp sensors (which aren't working) is the XMMF01JQD Xiaomi Magic Cube, which seems to work just fine!

**Comment by nathbullen** [comment]
> > They all went offline at about 6:30pm AEST
> > ![image](https://user-images.githubusercontent.com/67679349/181582919-acb788ee-963e-482d-9040-adbc203770cd.png)
> 
> Almost exactly hour earlier for me, same timezone
> 
> Certainly seems like it isn't an issue with this integration, but Mi Home.
> 
> Out of curiosity... What region are you set to? Are you running the modded version of Mi Home?
> 
> I'm running modded and set to the recommended Singapore region

I'm running the modded gateway software yeah, my region is set to Australia

I only have the LYWSD03MMC sensors, I have 3 of them and they all seemed to go unavailable at roughly the same time. I've also noticed that my "Gateway Cloud Link" shows as "Disconnected", and it seems to have happened about 10-12 hours after everything else went offline. I've tried a few things and can't get it to log in.

**Comment by Ruskyy** [comment]
I'm running on supported firmware.
I do not have other BLE devices on the hub.

**Comment by vampywiz17** [comment]
> _Question only for supported gateway firmwares:_
> 
> Do you have another BLE devices? Do they continue to work properly in Home Assistant while LYWSD03MMC unavailable?

I don't use  other BLE , only zigbee devices, but this work well.

**Comment by sagilo** [comment]
@AlexxIT any idea what this is? all my BLE devices are shown as unavailable as well:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/5019344/192474543-86c049db-6d6b-4b85-90c2-37e70176d70b.png">
 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/5019344/192474638-5bf1ad50-51a4-416c-81f9-f69a384b6226.png">

Shown properly in the mi home app:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/5019344/192474834-10755971-d9f8-47c7-a5cb-6ecc5a392e88.png">

**Comment by AlexxIT** [comment]
@sagilo are you using supported firmware?

**Comment by sagilo** [comment]
I was using 1.5.0_0102 but recently updated to 1.5.4_0090, however, the issue isnt a new one and occurred for  1.5.0_0102 as well.
I see there are other users on this thread who are having the same issue with the supported v1.5.0_0102.
If you believe this is a fw issue, I can probably flash custom one but since other users experience the same i dont have high hopes.
Im available for sharing logs or anything you need in order to troubleshoot the issue, but it looks like BLE functionality is dead for now for all the component users?

**Comment by AlexxIT** [comment]
There is no need for logs. v1.5.4 is not supported

**Comment by sagilo** [comment]
@AlexxIT there are more than 3 users on this thread who use v1.5.0_0102 and it doesn't work either.. 
Anyway, I do appreciate the component and the development, but that's an odd way to handle issues. coming from your users. 
If issues aren't going to be fixed and the repo isn't maintained (for any reason) - that's perfectly fine, but it's better to reflect that in the repo info so users can know to find alternatives and not waste time to onboard

**Comment by AlexxIT** [comment]
And thousands of users, including me, who have 1.5.0 working...

**Comment by sagilo** [comment]
> And thousands of users, including me, who have 1.5.0 working with BLE...
> 
> Support for new BLE devices is added with each release. No need to doubt that it works: https://github.com/AlexxIT/XiaomiGateway3/milestone/1

As mentioned, there are 3 users on this thread which BLE devices doesn't work for them.
If downgrading to a supported version will help you troubleshoot this issue faster, I can try doing that and assist. But will it do any good or the statement is still that "it works"?

**Comment by grastraa** [comment]
> As mentioned, there are 3 users on this thread which BLE devices doesn't work for them.

I was one of those users. 

The issue myself and at least one other user encountered likely had nothing to do with this integration. It was a xiaomi app and/or server problem. I am also using a modified app, putting another variable in the mix.

Throw a sensor in your fridge and see if the official Mi Home app updates the temperature for it. They were online in my app and were displaying temps that looked correct, but were the value was actually many hours out of date.

My solution was to remove the trouble sensors and re add them, didn't happen smoothly but I eventually resolved my issues.

**Comment by asenchuk** [comment]
I lost all my 6 LYWSD03MMC at about 3:30 UTC yesterday. Just re-added them to MiHome and now it works again.
The difference I spotted - previously when getting devices info from MiCloud the `Bindkey` was `Not needed`. Now it is set.

<img width="350" alt="Screenshot 2022-11-26 at 11 59 47" src="https://user-images.githubusercontent.com/169769/204081079-294b1f17-4bee-437a-b969-b448d6fbfaed.png">
<img width="355" alt="Screenshot 2022-11-26 at 12 01 04" src="https://user-images.githubusercontent.com/169769/204081082-f2031122-9745-43be-ad08-be342775d52c.png">

It's definitely looks like MiHome issue, but I think it's worth mentioning in FAQ or something.

**Comment by attiss** [comment]
Same here, all my BLE devices were unavailable since yesterday (LYWSD03MMC & MCCGQ02HL). Removed them from MiHome, added them back then restarted the gateway and everything's back to normal.

**Comment by AlexxIT** [comment]
@attiss https://github.com/AlexxIT/XiaomiGateway3/issues/872#issuecomment-1328625585

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
