### ISSUE TITLE
Restore sensor value for Fahrenheits bug

### ISSUE THREAD

**Issue by schindlershadow** [AlexxIT/XiaomiGateway3#723]
I think these images speak for themselves, temperature reporting is out of control and seems to get worse every time I restart the integration/HA
![image](https://user-images.githubusercontent.com/7072789/162289821-c0d288b3-1e39-4b77-8928-55c72232174d.png)
![image](https://user-images.githubusercontent.com/7072789/162290109-0fbfcea8-f7ad-49ba-9d9a-8b42608ee802.png)

Logs: https://pastebin.com/sz2x9He2

GW FW: 1.5.0_0026 #20210518
Device: LYWSD03MMC (BT)
HA: 2022.3.5 
Integration versions tested: Master, v2.0.9

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release

**Comment by schindlershadow** [comment]
Thanks for the quick reply!

I updated to master and now it no longer increases with each restart but the temperature is still off.
![IMG_20220409_131339](https://user-images.githubusercontent.com/7072789/162584492-be3ed81d-b5de-4db3-a76c-a2b0d86d6dcb.jpg)

A reinstall did not help

**Comment by schindlershadow** [comment]
I do see the native_value attribute referenced in the commit and they seem to be reporting the Celsius values correctly. Somewhere in the Fahrenheit conversion must be the issue

![IMG_20220409_134711](https://user-images.githubusercontent.com/7072789/162585546-809b5282-a63b-46ab-a10c-274c846e7206.jpg)

**Comment by AlexxIT** [comment]
162.9 - double conversion 22.6 celsius to fahrenheit...

**Comment by AlexxIT** [comment]
Fixed
