### ISSUE TITLE
[zha mode] change wifi network

### ISSUE THREAD

**Issue by kkmaslowski** [AlexxIT/XiaomiGateway3#728]
Hi. 
How can I change wifi network name if gateway is in ZHA mode, so it's not available from Mi Home? Can I change network name through telnet and save changes?

**Comment by kkmaslowski** [comment]
It worked, thanks

**Comment by mcbyte-it** [comment]
Thanks, Fixed my issue of resetting the device to pair a new wifi.
This custom firmware with telnet is great
