### ISSUE TITLE
Wrong sensor type in homekit

### ISSUE THREAD

**Issue by abc13131412** [AlexxIT/XiaomiGateway3#729]
model: Smart Curtain Motor MJSGCLBL01LM
The light sensor appear as motion sensor in homekit
It’s that true? or it’s a bug?
![9C7970AB-AED5-452E-9AF9-6ABF72E8272D](https://user-images.githubusercontent.com/28754467/162785101-c19846c0-b9c1-47e5-8c04-34f4565742ee.jpeg)

**Comment by AlexxIT** [comment]
You need write to Hass repo. Because HomeKit component don't support binary light sensor as light sensor.

https://github.com/home-assistant/core/blob/27bc5e1d7479170cbc3bdb2f4e43e6c525dcfdcc/homeassistant/components/homekit/type_sensors.py#L352-L354
