### ISSUE TITLE
Fix unavailable state for Mesh light

### ISSUE THREAD

**Issue by froggyfly** [AlexxIT/XiaomiGateway3#73]
Thanks for the update! Yelight mesh lights (YLTS04YL) has been connected.
It can be controlled in Homeassistant now, but it didn't synchronize the state of entity's ON/OFF.
Entity display ON all the time, if light is ON, I can turn off the entity to close the light, the entity will become ON state after 2-3 seconds.
I also can turn on the light by first turning off the entity and then turning it on, or use a light_turn_on service.

It can be used, but it would be perfect to synchronize the state of entity's ON/OFF.

**Comment by Mantoui** [comment]
Thanks for the update, the coveted mesh device support, thanks
I have the following equipment, YLDP25YL/YLDP26YL. After upgrading to 0.7.0, the equipment has been discovered, and the switch can be controlled through HA, repeating the 2-3s delay upstairs,
When I use the control that comes with HA
Brightness: Brightness slider, cannot control brightness, DEBUG
`2020-10-19 14:52:38 Debugging (Thread 4) [custom_components.xiaomi_gateway3.gateway3] 10.2.0.107 | Process grid [{'did': '1060067550','siid': 2, 2,'piid' : 2,'value': 100,'tid': -1}]`

Color temperature, color temperature slider, cannot control color temperature, DEBUG:
`2020-10-19 14:52:52 Debugging (Thread 4) [custom_components.xiaomi_gateway3.gateway3] 10.2.0.107 | Process grid [{'did': '1060067550','siid': 2, 2,'piid' : 3,'value': 5050,'tid': -1}]`

HA version: 0.116.4

**Comment by AlexxIT** [comment]
@Mantoui Are you sure you copied the log accurately? I do not have the phrase `Process grid` in my code.

**Comment by Mantoui** [comment]
@AlexxIT 
Sure it's a duplicate debug, but it can't be reproduced now.

The current version is v0.7.1, and I still can't control the brightness and color temperature properly

If you need any information from me, please let me know. Thank you

**Comment by AlexxIT** [comment]
@Mantoui I have same bulb and don't have problem with it. I'll try to add more logs.

**Comment by Zuz666** [comment]
@froggyfly  I have same issue. Try to on / off (via HA) and when problem will be resolved until next HA restart. This should be done immediately within 1-2 seconds. I think it can be automated on startup HA script as temporally solution. )))

**Comment by Zuz666** [comment]
@AlexxIT as I can see only some bulbs have issue YLDP25YL/YLDP26YL works fine but YLDP10YL and YLTS02YL/YLTS04YL not.

**Comment by Mantoui** [comment]
@AlexxIT   
Thanks for your active update, just upgraded to v0.7.2
Debug is as follows:
Start up:
```
2020-10-21 14:14:09  DEBUG    gateway3      10.2.0.107 | Setup Mesh device {'did': '1060067550', 'mac': '5CE50CE4A089', 'model': 2281, 'type': 'bluetooth', 'device_name': 'Mesh', 'device_model': 2281}
2020-10-21 14:14:09  DEBUG    gateway3      10.2.0.107 | Setup Mesh device {'did': '1041177760', 'mac': '50EC50E45330', 'model': 2342, 'type': 'bluetooth', 'device_manufacturer': 'Yeelight', 'device_name': 'Yeelight Mesh Bulb M2', 'device_model': 'YLDP25YL/YLDP26YL'}
```

Power on:
`2020-10-21 14:23:53  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 3, 'value': 6400, 'tid': -1}, {'did': '1060067550', 'siid': 2, 'piid': 1, 'value': True, 'tid': -1}, {'did': '1060067550', 'siid': 2, 'piid': 2, 'value': 68, 'tid': -1}]`

Mijia app adjusts minimum color temperature
`2020-10-21 14:30:50  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 3, 'value': 3000, 'tid': -1}]`
Mijia app adjusts maximum color temperature
`2020-10-21 14:30:54  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 3, 'value': 6400, 'tid': -1}]`
Mijia app adjusts the minimum brightness
`2020-10-21 14:31:00  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 2, 'value': 1, 'tid': -1}]`
Mijia app adjusts maximum brightness
`2020-10-21 14:31:04  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 2, 'value': 100, 'tid': -1}]`
Now, developer tools
> light.5ce50ce4a089_light
> on
> min_mireds: 153
> max_mireds: 370
> brightness: 0.38910505836575876
> color_temp: 156
> friendly_name: 客厅灯-客厅 Light
> supported_features: 3

Through the brightness control of HA, no matter how the sliding rod is pulled, it is brightness': 100 as follows:

```
2020-10-21 14:40:56  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 2, 'value': 100, 'tid': -1}]
2020-10-21 14:41:11  DEBUG    light         10.2.0.107 | 1060067550 poll mesh <= {'light': True, 'brightness': 100, 'color_temp': 6400}
```

The color temperature of HA is controlled as follows:
```
2020-10-21 14:44:48  DEBUG    gateway3      10.2.0.107 | Process Mesh [{'did': '1060067550', 'siid': 2, 'piid': 3, 'value': 5780, 'tid': -1}]
2020-10-21 14:44:49  DEBUG    light         10.2.0.107 | 1060067550 poll mesh <= {'light': True, 'brightness': 100, 'color_temp': 5780}
```

Note: the sliding bar data range of color temperature exceeds 3000-6400

**Comment by AlexxIT** [comment]
@Mantoui what real model does the `1060067550` have?

**Comment by Zuz666** [comment]
> I can see only some bulbs have issue YLDP25YL/YLDP26YL works fine
@AlexxIT Oh, powered off (no power) YLDP25YL/YLDP26YL are returned to the on state too. (((

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
