### ISSUE TITLE
ZNKG03HL поддержка беспроводного режима

### ISSUE THREAD

**Issue by theodorx7** [AlexxIT/XiaomiGateway3#732]
Большая просьба добавить поддержку беспроводного режима аналогичным образом, как это было реализовано для выключателя DHKG02ZM (DHKG02ZM decoupled mode does not update states #689).

![IMG_1247](https://user-images.githubusercontent.com/99128059/163356590-4128c3eb-b5c9-4ad5-a756-ea81a3a95ae3.PNG)

![sensor DHKG02ZM](https://user-images.githubusercontent.com/99128059/163356876-70a33b15-8173-46b2-ba5c-42b23523c6cd.jpg)

**Comment by AlexxIT** [comment]
У этой модели давно есть такая поддержка
https://github.com/AlexxIT/XiaomiGateway3/blob/152922fbddccaa2611fb530fc4f1cbd5c26fa97c/custom_components/xiaomi_gateway3/core/converters/devices.py#L1403

**Comment by theodorx7** [comment]
Прошу прощения за беспокойство, по всей видимости я что-то упускаю из виду ввиду неопытности. Но у меня не отображаются сущности беспроводных кнопок. Могли бы Вы подсказать, как их можно активировать? В скрытых объектах беспроводные кнопки отсутствуют. Я вижу только переключатели клавиш в беспроводной режим. 

![Screenshot_1](https://user-images.githubusercontent.com/99128059/164896974-08f52158-d226-4e47-9823-a4c445a1b23a.jpg)

**Comment by theodorx7** [comment]
Кажется догадался. Xiaomi Gateway 3 у меня установлен версии 2.0.9, однако в файле devices.py содержимое было вот таким:
    2717: ["Xiaomi", "Mesh Triple Wall Switch", "ZNKG03HL/ISA-KG03HL"],
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
        Converter("channel_3", "switch", mi="4.p.1"),
        MathConv("humidity", "sensor", mi="6.p.1", round=2),
        MathConv("temperature", "sensor", mi="6.p.7", round=2),
        BoolConv("wireless_1", "switch", mi="2.p.2", enabled=False),
        BoolConv("wireless_2", "switch", mi="3.p.2", enabled=False),
        BoolConv("wireless_3", "switch", mi="4.p.2", enabled=False),
        Converter("baby_mode", "switch", mi="11.p.1", enabled=False),

Я добавил недостающие строки и сенсор появился. 
Большое спасибо!
