### ISSUE TITLE
ZigBee sensors - unknown status

### ISSUE THREAD

**Issue by cezarg1410** [AlexxIT/XiaomiGateway3#736]
Hello,
My environment:
- Debian 11,
- Home Assistant supervised installed on Debian. Version 2022.4.2
- Xiaomi Gateway 3 ZNDMWG02LM, firmware version: 1.5.0_0102 (was different, I changed it using Your tutorial)

Integration shows all sensors which are paired with the gateway but I cannot see any output from the sensors. Everything  is "unknown".
Example sensor: zigbee WSDCGQ01LM (lumi.sensor_ht) (Temeprature and humidity), ("nieznany" means "Unknown" - it's Polish language)
 
![image](https://user-images.githubusercontent.com/9452334/163817764-7474b3b3-c6ec-4244-ac26-715dc8a7bf3a.png)

Why is that happening? Previously i had Home Assistant Core in the Docker Container and there verything was fine.

**Comment by AlexxIT** [comment]
Are this sensors works in MiHome?

**Comment by cezarg1410** [comment]
Yes they work.
I have no idea where was the issue but it works now.
For other reasons i have now new HA installation (moved from kvm to native on Debian) and and issue no longer exists

**Comment by AlexxIT** [comment]
Sensor data appears with some delay
