### ISSUE TITLE
Sonoff SNZB-04 has been paired through the gateway but state is not updating

### ISSUE THREAD

**Issue by yusrimathews** [AlexxIT/XiaomiGateway3#741]
I paired the Sonoff SNZB-04 device successfully with my Gateway 3 hub, while the battery and Zigbee entities seem as if they work, the state is not updating.

Nothing in the logs related to this so not sure what the issue may be.

**See instance details below:**
Home Assistant 2022.4.7
Xiaomi Gateway 3 v2.0.10
Gateway ZNDMWG03LM ZNDMWG02LM Firmware: 1.5.0_0102
SNZB-04 (DS01) Firmware: 4

**Comment by vturekhanov** [comment]
It should be fixed in the latest master version. Try to use it.

**Comment by yusrimathews** [comment]
@vturekhanov latest version of what?

**Comment by vturekhanov** [comment]
Master of XiaomiGateway3 component. It is not a release nor even beta. It can be installed via HACS as "master".

**Comment by WarC0zes** [comment]
yes, I confirm that it works on the master version.

**Comment by yusrimathews** [comment]
@WarC0zes do you have an issue with the battery? Mines at 0% but the sensor is working fine.

I’m going to replace the batteries tomorrow as it may just be a glitch.

**Comment by batcatsaga** [comment]
I have the same issue. I tried installing the master version but still no change. The state is always "Closed". Only the zigbee entity updates.

**Comment by yusrimathews** [comment]
> @WarC0zes do you have an issue with the battery? Mines at 0% but the sensor is working fine.
> 
> I’m going to replace the battery tomorrow, it may just be a glitch.

Just to update, the battery issue I had resolved itself. Using the master version worked for me.

**Comment by WarC0zes** [comment]
> @WarC0zes do you have an issue with the battery? Mines at 0% but the sensor is working fine.
> 
> I’m going to replace the battery tomorrow, it may just be a glitch.

No problem for me, wait because it can take a while before going back up.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
