### ISSUE TITLE
Can firmware 1.5.4_0084 open port 8888?

### ISSUE THREAD

**Issue by oliver-ok** [AlexxIT/XiaomiGateway3#744]
I use 1.5.4_0032_stock firmware , the port 8888 is open by default. Zha works well with this firmware.
But when I update to firmware 1.5.4_0084 , no matter mod or stock version, the port 8888 is closed. Therefore I can not connect via ZHA.
I tried flash zigbee firmware to z2m version, it doesn't work.
Can any one help me? 
Thanks a lot!

**Comment by AlexxIT** [comment]
#666
