### ISSUE TITLE
SSM-U01 and SP-EUC01 reports 0kWh energy

### ISSUE THREAD

**Issue by szymucha94** [AlexxIT/XiaomiGateway3#746]
SSM-U01 and SP-EUC01 reports 0kWh energy regardless of how it is used. Tested multiple times SP-EUC01 under 800W load.
Re-adding devices, reinstalling integration doesn't help. It's seen under all T1 relays and all EU plugs.
Please, pretty please fix it

**Comment by szymucha94** [comment]
![2](https://user-images.githubusercontent.com/95378717/167226595-d4ceed8c-15e7-43e5-8d1d-b158824ec599.PNG)
![1](https://user-images.githubusercontent.com/95378717/167226596-2bf7034e-e61b-49b3-800e-948f0c922b2b.PNG)
examples

**Comment by szymucha94** [comment]
noticed same thing. This would probably work fine with zigbee2mqtt, but there are too many devices to fix after this change for me to try :P
Btw. if you're looking for alternative counters you can use this one:

sensor:
  - platform: integration
    source: sensor.0x54ef4410004311c5_power
    name: MARS_energy
    unit_prefix: k
    round: 2
    method: left
    
   
![Capture](https://user-images.githubusercontent.com/95378717/177138435-0c04d06b-60e9-4186-9800-c2a7e14b475e.PNG)

**Comment by szymucha94** [comment]
Bumping with installed firmware version:
FIRMWARE........: 1.5.0_0102 #20210816

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
