### ISSUE TITLE
BLE device EraClean CW-BS01 Max

### ISSUE THREAD

**Issue by VikeDragon** [AlexxIT/XiaomiGateway3#747]
Greetings!
There is a BLE device EraClean CW-BS01 Max
https://home.miot-spec.com/s/4617
Through MiHome, it is fully controlled, pulled up into a home assistant only as one Ble sensor in the "unknown" state. When debugging, only one entry in the log:
2022-05-08 09:32:20 Debugging base 192.168.31.179 [BASE] ec4d3ecfe846 (4617) setting blue (4617): ble
I tried to use the functionality of the device - I pressed buttons and switched modes, but there are no entries in the log.

I ask you to help connect the device correctly in the Home Assistant, through the integration of XiaomiGateway3

**Comment by rezmus** [comment]
gw3 only gets ble data sent by sensors, you need active bt connection to control device. it is out of scope of this project.

**Comment by VikeDragon** [comment]
> gw3 only gets ble data sent by sensors, you need active bt connection to control device. it is out of scope of this project.

Thank you, I'm sorry about that. The number of BLU devices is growing.
