### ISSUE TITLE
Add support Xiaomi Box BGX-5/X1-3001

### ISSUE THREAD

**Issue by tsunglung** [AlexxIT/XiaomiGateway3#75]
Hi

Got Xiaomi Safety Box (BGX-5/X1-3001) which is using Bluetooth. Please help to add this support.

I add the patch for your reference.

And if you have any other suggestions, please let me know.

![12885744045320](https://user-images.githubusercontent.com/46878487/96567261-290ff380-12f9-11eb-82f1-c0cad6491a15.jpg)

[XiaomiBox.patch.txt](https://github.com/AlexxIT/XiaomiGateway3/files/5407746/XiaomiBox.patch.txt)

`

**Comment by AlexxIT** [comment]
I will add support, no problem

**Comment by tsunglung** [comment]
Thank you!

**Comment by darkkatarsis** [comment]
@tsunglung does integration allow you to open safe?

**Comment by tsunglung** [comment]
> @tsunglung does integration allow you to open safe?

no

**Comment by AlexxIT** [comment]
@tsunglung is MiHome app has open safe function?

**Comment by tsunglung** [comment]
> @tsunglung does MiHome app allow you to open safe?

Yes
