### ISSUE TITLE
Zigbee device DELETE malfunction

### ISSUE THREAD

**Issue by guardianbs** [AlexxIT/XiaomiGateway3#754]
Home Assistant Core 2022.5.4
Xiaomi Gateway 3 version 2.1.0
Two gateways. First gateway on Firmware: 1.4.7_0115, second gateway on Firmware: 1.5.0_0102

Relates to issue #650

With the latest integration version there is a 'DELETE' option on the device screen.

Where the device (e.g. Aqara Motion Sensor) is attached to 2 gateways there are 2 'DELETE' options.

I selected the gateway that I wanted to delete the device from and selected the first 'DELETE' option.

The device was deleted from BOTH gateways. The Xiaomi app still shows the device attached to the second gateway correctly and accessible..

I deleted the integration for the second gateway and re-installed it. The device that was deleted from the first gateway but is still attached to the second gateway does not show up on either gateway.

Rebooted gateway, rebooted HA, device still does not show up.

Interestingly (and probably not related) the 10 BLE Mesh sensors which were showing up on both gateways also do not now show up on the re-installed integration.

**Comment by guardianbs** [comment]
Question ? What was the question ?

**Comment by AlexxIT** [comment]
This is a question from you, which I already answered last time. You moved devices from one gateway to another. But they remained in the database of the old gateway. Now Hass showing them on both integration and can't delete it properly. And gateways can't delete them properly.

Maybe someday I'll make function for cleaning gateway databases from trash.

**Comment by guardianbs** [comment]
Ok, My mistake. I thought that is what the DELETE option was added to achieve, but I see that it is not as simple as that.
Not a problem. I have deleted the 5 affected devices on the second gateway from the MiHome app and reinstalled them attached to the second gateway and now they appear correctly in the second integration.

The 10 BLE Mesh sensors which were showing up on both gateways are still not shown on the second gateway.

**Comment by AlexxIT** [comment]
You can download BLE device diagnostics. And you can see real gateways list there

**Comment by guardianbs** [comment]
The diagnostics for the BLE device show it being attached / available to the 3 gateways that I have but the BLE devices are only listed under two of the gateway integrations, not under the new one set up.

Also, (and probably out the of control of the integration) the options shown for the BLE devices are somewhat misleading as (from previous experience) using either DELETE option would presumably delete the device from ALL gateway integrations (again only showing two sets of options because it is only listed under two gateway integrations).

![BLE_Device](https://user-images.githubusercontent.com/71522772/168589699-ce83c8e9-13ae-4296-afa5-bdb21f562801.JPG)

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
