### ISSUE TITLE
PTX wall switch three/two keys (mesh) only showed one channel 

### ISSUE THREAD

**Issue by WalterDSU** [AlexxIT/XiaomiGateway3#757]
Model 3788 (PTX single fire key switch three keys)
Model 3789 (PTX single fire key switch two keys)
[xiaomi_gateway3-043c6f5f69cf9e5b42f6ca1086804404-PTX single fire key switch two keys (mesh)-057ec9371938f59e5be4df22ecdb5170.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/8747049/xiaomi_gateway3-043c6f5f69cf9e5b42f6ca1086804404-PTX.single.fire.key.switch.two.keys.mesh.-057ec9371938f59e5be4df22ecdb5170.json.txt)
[xiaomi_gateway3-043c6f5f69cf9e5b42f6ca1086804404-PTX single fire key switch three keys (mesh)-dfe7c4db231384b922065a06932f6974.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/8747050/xiaomi_gateway3-043c6f5f69cf9e5b42f6ca1086804404-PTX.single.fire.key.switch.three.keys.mesh.-dfe7c4db231384b922065a06932f6974.json.txt)

**Comment by WalterDSU** [comment]
this similar device mesh PTX-TK3/M works well.

**Comment by AlexxIT** [comment]
Added to latest master version. Will be in next release

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v2.1.1
