### ISSUE TITLE
Add support Aqara Leak Water Sensor E1 

### ISSUE THREAD

**Issue by Polymerkid0** [AlexxIT/XiaomiGateway3#758]
Does it support Aqara leak water sensor E1 ( lumi.flood.acn001) model: SJCGQ13LM?

I can add it through the Mi Home App by Xiaomi Gateway (model: ZNDMWG03LM). However, the sensor does not show in HA.

**Comment by AlexxIT** [comment]
You need to collect device debug logs

**Comment by terenceng81** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/56790753/235076153-f6034f99-5355-4276-ab6d-4e91d86bd6c8.png">

turn on all 3 below?
<img width="302" alt="image" src="https://user-images.githubusercontent.com/56790753/235076268-2aca7c91-3511-47bb-91a7-038ddc2c4525.png">

**Comment by terenceng81** [comment]
[xiaomi_gateway3-8717d98626f6067c355604a9eada9c3a-Unknown ZIGBEE-0a467dc21b91512d72ad4d92b819396d.json (3).txt](https://github.com/AlexxIT/XiaomiGateway3/files/11350792/xiaomi_gateway3-8717d98626f6067c355604a9eada9c3a-Unknown.ZIGBEE-0a467dc21b91512d72ad4d92b819396d.json.3.txt)

[home-assistant_xiaomi_gateway3_2023-04-28T06-56-22.373Z.log](https://github.com/AlexxIT/XiaomiGateway3/files/11350793/home-assistant_xiaomi_gateway3_2023-04-28T06-56-22.373Z.log)
can these logs be used?

**Comment by AlexxIT** [comment]
@terenceng81 thanks. Very helpful. Is your sensor wet or dry in logs?

**Comment by terenceng81** [comment]
> @terenceng81 thanks. Very helpful. Is your sensor wet or dry in logs?

No Wet or Dry in logs, only Zigbee signal as shown below :-)

<img width="748" alt="image" src="https://github.com/AlexxIT/XiaomiGateway3/assets/56790753/342f2ebc-7a96-4f49-9dee-1f4335dfc2b0">

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
