### ISSUE TITLE
Xiaomi Gateway 3 , smoke detector unavialable

### ISSUE THREAD

**Issue by abpross** [AlexxIT/XiaomiGateway3#759]
Xiaomi Gateway 3 for Home assistant does recognize the smoke detectors and also adds them to the integration,
but within the integration I get the message sensors not available.
smoke detectors are the "ble JTYJ-GD-03MI" smart smoke detectors by Honeywell/Xiaomi bluetooth.
In the app from Xiaomi the devices/sensors are available.

last update Xiaomi gateway: 1.5.4_0090

**Comment by vturekhanov** [comment]
Try to use recommended firmware: 1.5.0.102.

**Comment by abpross** [comment]
Firmware 1.5.0.0102 is from a year ago.
Is there an easy way to restore this version?

Will there be soon a update to solved this issue?

**Comment by vturekhanov** [comment]
1.5.0_0102 is the only recommended firmware at the moment.
Please find "easy way" here: https://github.com/zvldz/mgl03_fw/tree/main/firmware
Just in case don't forget disable Lock Firmware before downgrade if you enabled it early.

> Will there be soon a update to solved this issue?
It's not an issue. It's feature. :)

**Comment by abpross** [comment]
i have reset the firmware to version 1.5.1_0032 (2021-12-12)
and I home assistant recognizes the entities of the three smoke detectors.

I have a small question, the smoke detector has two  entities, mI smoke detector sensor and "Action" sensor
maybe you can tell me what the "Action"  means/does

**Comment by vturekhanov** [comment]
> maybe you can tell me what the "Action"  means/does

Is there a button on your smoke detector? If yes, press the button and get the result (observe the _action entity).

**Comment by AlexxIT** [comment]
1.5.4 don't supported yet. Read README
