### ISSUE TITLE
Smart Socket  ZNCZ04LM - Integrate Power Outage - Restore previous state 

### ISSUE THREAD

**Issue by digitalsteezdesign** [AlexxIT/XiaomiGateway3#76]
Hi AlexxIT,
I was wondering, is it possible to integrate some sort of extra polling between the GW3 and the Socket  ZNCZ04LM.
What happens is, after a power outage, this socket is not going to turn to it's previous state (ON) so that while midnight, if power outage, i have to wake-up to turn on the socket otherwise the UPS'es that are behind it will beep all night.

I saw that through zigbee to MQTT, for ZNCZ02LM, that could be implemented.
Thanks if you think you can develop such thing.

**Comment by digitalsteezdesign** [comment]
Here's a thing to help https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2583

**Comment by AlexxIT** [comment]
How polling can help to you? You can send right command to plug when it back online again.

**Comment by AlexxIT** [comment]
ZNCZ04LM should support this function. For ZNCZ02LM you can enable power memory in MiHome app.
I can't do anything if this function not in MiHome app for ZNCZ04LM
