### ISSUE TITLE
Possible to control BLE locks? (Lock and Unlock)

### ISSUE THREAD

**Issue by MadMirza** [AlexxIT/XiaomiGateway3#760]
I have a Xiaomi BLE lock, managed to get into HA using this wonderful Integration, able to view states and such, but I was wondering if I would be able to control the lock through home assistant, having the ability to Lock and Unlock would be wonderful.

Thanks.

**Comment by AlexxIT** [comment]
Can you do this function via MiHome?

**Comment by ikio79** [comment]
@AlexxIT I have BLE Aqara n100 lock and yes, it is possible to unlock it remotely in MI Home. It would be great to have an ability to unlock it from Home assistant.

**Comment by ikio79** [comment]
![c48eef8e-9eb5-4b11-a36c-c0ac6e4b4337](https://user-images.githubusercontent.com/60843788/194635679-62d4e1e2-e687-4913-8297-3528c1987760.jpeg)

**Comment by AlexxIT** [comment]
You can do it remotely? When you not at home?

**Comment by ikio79** [comment]
Unlock button is available only in case of direct  bluetooth connection between phone and lock. 
Only option to unlock without direct bluetooth connection is one-time password creation.

**Comment by AlexxIT** [comment]
It seems that the Gateway does not manage to open the lock. Only the user's phone can do that.
