### ISSUE TITLE
Aqara DJT11LM Action not working propertly

### ISSUE THREAD

**Issue by Viper7000** [AlexxIT/XiaomiGateway3#763]
I have Xiaomi GW3 ZNDMWG02LM (fw:1.5.0_0026) device and Xiaomi Gateway 3 HACS last integration
Zigbee sensor Aqara DJT11LM connect to GW3 and work great. In MiHome I see action from sensor, log and can use action in automation. Bat in HA I don't.
Action item no history, only have attribute of last action. I have Action event in log of sensor, but I can`t use action in automation

Sensor's card and log
![v1](https://user-images.githubusercontent.com/96679981/172045911-3ee05088-3907-4609-ad0a-b49db2b955a7.jpg)

Sensor's history
![v2](https://user-images.githubusercontent.com/96679981/172045792-f7de0db4-6548-4604-84d0-1688151d84bc.jpg)

Sensor's automation have only battery event :(
![v3](https://user-images.githubusercontent.com/96679981/172045829-f8498dca-2b65-4e2e-b72f-e73a6b85a991.jpg)

**Comment by szymucha94** [comment]
Use action entity state instead. I use the same sensor this way and it works

**Comment by Viper7000** [comment]
> Use action entity state instead. I use the same sensor this way and it works

Can you take some screenshots?
My problem I can't us automation and I have't entity state. Only attribute of last state. I wrote all of it higher.

**Comment by szymucha94** [comment]
![2](https://user-images.githubusercontent.com/95378717/174295581-7eedd9f3-33b1-44f1-9121-adb50c3954fe.PNG)
![1](https://user-images.githubusercontent.com/95378717/174295583-4730d98a-2983-4a64-b4b5-de982bfcd874.PNG)
according to zigbee2mqtt available states are:
Action (enum)

Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: **vibration, tilt, drop.**

Action state shows up when you hit the sensor only for very short time. It's sometimes too fast to see by yourself but it's enough for HASS to trigger automations.

**Comment by szymucha94** [comment]
According to your screenshots HASS received Action "Tilt" from your sensor, so it works as expected.
DJT11LM doesn't act like motion sensor - if vibrations are detected it just sends single message and that's it. It doesn't clear the state after vibrations stop. I can keep shaking it for 2 minutes and it will still not react after first message is sent. I think it will send another Action state after 3 minutes from first message, at least according to zigbee updates.

**Comment by Viper7000** [comment]
[szymucha94](https://github.com/szymucha94)
Thank you very much for the detailed instructions. Indeed, there is an event in history, it's just very difficult to notice. Created automation by state - everything works clearly
The question is closed

**Comment by Viper7000** [comment]
Problem solved
