### ISSUE TITLE
Tested with v1.5.4_0090 actually succeed

### ISSUE THREAD

**Issue by lingxide** [AlexxIT/XiaomiGateway3#768]
Hello,

From your description it mentioned "these firmwares are not supported yet: v1.5.4_0XXX" but actually v1.5.4_0090 is also supported. Nothing goes strange just simply click and done.

Let me know if you need additional information.

**Comment by retrostrobe** [comment]
@lingxide – Which firmware did you use? I used the custom mod, and lost the bluetooth devices. Zigbee is fine.

**Comment by ShangpingWu** [comment]
me,too.------all of bluetooth devices unavailable

**Comment by kingwap99** [comment]
faced the same issue.

**Comment by AlexxIT** [comment]
#666 firmware has a lot of changes within its files. Some functions continue to work, some stop works, some woks with problems
