### ISSUE TITLE
additional attributes from sensors

### ISSUE THREAD

**Issue by freeball155** [AlexxIT/XiaomiGateway3#77]
Hello.

In the JSON file for the Aqara Water Leak Sensor (SJCGQ11LM) there is a chip_temperature attribute:

cat /data/zigbee_gw/lumi.158d0004522a2b.json 
{
    "lumi.158d0004522a2b.mac": "158d0004522a2b",
    "lumi.158d0004522a2b.model": "lumi.sensor_wleak.aq1",
    "lumi.158d0004522a2b.prop": "{\"props\":{\"CCA\":1,\"alarm\":0,\"alive\":1,\"battery\":62,\"battery_end_of_life\":0,\"chip_temperature\":30,\"cur_state\":3,\"fw_ver\":4,\"hw_ver\":2,\"lqi\":0,\"parent\":0,\"power_tx\":10,\"pre_state\":4,\"pv_state\":0,\"reset_cnt\":15,\"send_all_cnt\":1,\"send_fail_cnt\":0,\"send_retry_cnt\":0,\"voltage\":2975}}",
    "lumi.158d0004522a2b.version": "1.2"
}

Is it possible to get it somehow in HA?

**Comment by AlexxIT** [comment]
Check #107 (duplicate)
