### ISSUE TITLE
1% means curtain is close.

### ISSUE THREAD

**Issue by micturkey** [AlexxIT/XiaomiGateway3#771]
Hi, I am using curtain code 5195 which is https://home.miot-spec.com/spec/lonsam.curtain.lscl .
I tried writing my own converters and it works well.
The only one problem is that this curtain is not accuracy and thus when it is close, the current position may be 1%, not 0%; and when it is open, the current position may be 99% or 98%, not 100%.
The status of 99% or 98% does not matter at all because no matter how much it is, it is always open.
But the status of 1% matters, because in this situation HA will recognize the curtain as an opening one.
In MiHome app, 1% means the curtain is close.

**Comment by szymucha94** [comment]
> By the way, is there any way to add action “stop” of curtains in the automation? In the automation configuration page, the only action I can do is to set position of curtains, but in lovelace I can stop the curtains’ running.

Call service "cover.stop_cover" with related entity?

**Comment by micturkey** [comment]
> > By the way, is there any way to add action “stop” of curtains in the automation? In the automation configuration page, the only action I can do is to set position of curtains, but in lovelace I can stop the curtains’ running.
> 
> 
> 
> Call service "cover.stop_cover" with related entity?

Thanks for your reply!
I will try it later and post the result.
