### ISSUE TITLE
Mi Smart Door Lock with Face Unlock X cannot access homeassistant system

### ISSUE THREAD

**Issue by gx19970920** [AlexxIT/XiaomiGateway3#776]
the Firmware version is 1.5.0_0026
Only the battery and bluetooth connection status can be viewed
![image](https://user-images.githubusercontent.com/33535925/177455079-38cbeb42-9059-4006-9c8b-54ee4b20f6cc.png)

**Comment by micturkey** [comment]
Try writing your own coverters like this? 
It is directly copied from current migateway3 code and I just added the spec infomation and it may work.
`{
    "lumi.lock.bmcn05": ["Xiaomi", "Mi Smart Door Lock with Face Unlock X", "XMZNMS06LM"],
    "spec": [
        MiBeacon,
        # sensors:
        Converter("action", "sensor", enabled=None),
        Converter("battery", "sensor", enabled=None),
        Converter("conductivity", "sensor", enabled=None),
        Converter("formaldehyde", "sensor", enabled=None),
        Converter("humidity", "sensor", enabled=None),
        Converter("idle_time", "sensor", enabled=None),
        Converter("illuminance", "sensor", enabled=None),
        Converter("moisture", "sensor", enabled=None),
        Converter("rssi", "sensor", enabled=None),
        Converter("supply", "sensor", enabled=None),
        Converter("temperature", "sensor", enabled=None),
        # binary_sensors:
        Converter("contact", "binary_sensor", enabled=None),
        Converter("gas", "binary_sensor", enabled=None),
        Converter("light", "binary_sensor", enabled=None),
        Converter("lock", "binary_sensor", enabled=None),
        Converter("motion", "binary_sensor", enabled=None),
        Converter("opening", "binary_sensor", enabled=None),
        Converter("sleep", "binary_sensor", enabled=None),
        Converter("smoke", "binary_sensor", enabled=None),
        Converter("water_leak", "binary_sensor", enabled=None),
    ],
}]`

**Comment by AlexxIT** [comment]
@gx19970920 try to make some actions with lock. Sensors may appear later.

**Comment by gx19970920** [comment]
> Try writing your own coverters like this? It is directly copied from current migateway3 code and I just added the spec infomation and it may work.
> 
> ```python
> {
>     "lumi.lock.bmcn05": ["Xiaomi", "Mi Smart Door Lock with Face Unlock X", "XMZNMS06LM"],
>     "spec": [
>         MiBeacon,
>         # sensors:
>         Converter("action", "sensor", enabled=None),
>         Converter("battery", "sensor", enabled=None),
>         Converter("conductivity", "sensor", enabled=None),
>         Converter("formaldehyde", "sensor", enabled=None),
>         Converter("humidity", "sensor", enabled=None),
>         Converter("idle_time", "sensor", enabled=None),
>         Converter("illuminance", "sensor", enabled=None),
>         Converter("moisture", "sensor", enabled=None),
>         Converter("rssi", "sensor", enabled=None),
>         Converter("supply", "sensor", enabled=None),
>         Converter("temperature", "sensor", enabled=None),
>         # binary_sensors:
>         Converter("contact", "binary_sensor", enabled=None),
>         Converter("gas", "binary_sensor", enabled=None),
>         Converter("light", "binary_sensor", enabled=None),
>         Converter("lock", "binary_sensor", enabled=None),
>         Converter("motion", "binary_sensor", enabled=None),
>         Converter("opening", "binary_sensor", enabled=None),
>         Converter("sleep", "binary_sensor", enabled=None),
>         Converter("smoke", "binary_sensor", enabled=None),
>         Converter("water_leak", "binary_sensor", enabled=None),
>     ],
> }]
> ```
Thanks，I had solved this problem，the state of lock and door are in the attribute of <action> entity.

**Comment by gx19970920** [comment]
> @gx19970920 try to make some actions with lock. Sensors may appear later.

Thanks, after I open and close the door several times, the states of lock and door show in the attribute of entity.

**Comment by AlexxIT** [comment]
Ok. Anyway I need to add this model to component. So all entity will appear instantly

**Comment by gx19970920** [comment]
> 还行。无论如何，我需要将此模型添加到组件中。因此，所有实体都将立即出现

thanks, if you need some information of this lock please e-mail me at gx19970920@gmail.com

**Comment by AlexxIT** [comment]
I can see its model on your screen. How many sensors do you have? BLE, Battery and Action?

**Comment by gx19970920** [comment]
> I can see its model on your screen. How many sensors do you have? BLE, Battery and Action?

![image](https://user-images.githubusercontent.com/33535925/180934519-400e4aea-05ce-46ea-8277-382a078067c2.png)

it has BLE, Battery and Action，the main information are in the attribute of action

![image](https://user-images.githubusercontent.com/33535925/180934692-94767ccd-b753-4e7f-8c40-c5a5e658bbb0.png)

**Comment by bmbb0123** [comment]
> Try writing your own coverters like this? It is directly copied from current migateway3 code and I just added the spec infomation and it may work.
> 
> ```python
> {
>     "lumi.lock.bmcn05": ["Xiaomi", "Mi Smart Door Lock with Face Unlock X", "XMZNMS06LM"],
>     "spec": [
>         MiBeacon,
>         # sensors:
>         Converter("action", "sensor", enabled=None),
>         Converter("battery", "sensor", enabled=None),
>         Converter("conductivity", "sensor", enabled=None),
>         Converter("formaldehyde", "sensor", enabled=None),
>         Converter("humidity", "sensor", enabled=None),
>         Converter("idle_time", "sensor", enabled=None),
>         Converter("illuminance", "sensor", enabled=None),
>         Converter("moisture", "sensor", enabled=None),
>         Converter("rssi", "sensor", enabled=None),
>         Converter("supply", "sensor", enabled=None),
>         Converter("temperature", "sensor", enabled=None),
>         # binary_sensors:
>         Converter("contact", "binary_sensor", enabled=None),
>         Converter("gas", "binary_sensor", enabled=None),
>         Converter("light", "binary_sensor", enabled=None),
>         Converter("lock", "binary_sensor", enabled=None),
>         Converter("motion", "binary_sensor", enabled=None),
>         Converter("opening", "binary_sensor", enabled=None),
>         Converter("sleep", "binary_sensor", enabled=None),
>         Converter("smoke", "binary_sensor", enabled=None),
>         Converter("water_leak", "binary_sensor", enabled=None),
>     ],
> }]
> ```

Sorry , 
I am facing the same problem (without action field).
May I ask, 
where should Ｉpaste this code?
Thanks

**Comment by AlexxIT** [comment]
I don't understand. BLE model is always number. (3685) on your first screen. It can't be string (lumi.lock.bmcn05)

**Comment by gx19970920** [comment]
> I don't understand. BLE model is always number. (3685) on your first screen. It can't be string (lumi.lock.bmcn05)

You are right. The reason why my interface displays the name of the door lock is that I manually wrote the file xaomigateway3.py

**Comment by AlexxIT** [comment]
Can you attach the file here?

**Comment by gx19970920** [comment]
![image](https://user-images.githubusercontent.com/33535925/192146336-a91bbc02-9308-43c3-b30c-7ad55150b77d.png)
from custom_components.xiaomi_gateway3.core.converters.devices import *

DEVICES = [{
    3685: ["lumi", "Mi Smart Door Lock with Face Unlock X", "lumi.lock.bmcn05"],
    "spec": [
        MiBeacon,
        # sensors:
        Converter("action", "sensor", enabled=None),
        Converter("battery", "sensor", enabled=None),
        # binary_sensors:
        Converter("contact", "binary_sensor", enabled=None),
        Converter("lock", "binary_sensor", enabled=None),
    ],
}] + DEVICES

**Comment by AlexxIT** [comment]
Oh. Now is all clear. Thanks. Works as should be.

**Comment by gx19970920** [comment]
But can these attributes such as lock status, door status, and unlock method be independent entities? In this way, it is more convenient to set up automations. If you have time and are interested, I hope you can refer to my suggestion

**Comment by AlexxIT** [comment]
You can make template entities if you want.
But you can use them in automations without any modifications. Just learn more about Hass automations

**Comment by gx19970920** [comment]
THANKS!!!!
