### ISSUE TITLE
The current version with new miaomi gateway3 latest firmware is not working with Bluetooth devices.

### ISSUE THREAD

**Issue by jacobswin** [AlexxIT/XiaomiGateway3#778]
If rollback to gateway3 previous firmware, it still can be working.

**Comment by robertop13es** [comment]
Same issue, I can't make a rollback, no option.

**Comment by RayCheng75** [comment]
Same issue. which version can working?

**Comment by mihsu81** [comment]
Open a telnet session to the gateway and run the commands:
```
wget -O /tmp/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1" && chmod +x /tmp/curl
export PATH="$PATH:/tmp"
curl -s -k -L -o /tmp/update.sh https://raw.githubusercontent.com/zvldz/mgl03_fw/main/firmware/mgl03_update.sh && sh /tmp/update.sh
```
You will need to select firmware version and wait for the flashing of the firmwares to complete.

**Comment by jacobswin** [comment]
> Open a telnet session to the gateway and run the commands:
> 
> ```
> wget -O /tmp/curl "http://master.dl.sourceforge.net/project/mgl03/bin/curl?viasf=1" && chmod +x /tmp/curl
> export PATH="$PATH:/tmp"
> curl -s -k -L -o /tmp/update.sh https://raw.githubusercontent.com/zvldz/mgl03_fw/main/firmware/mgl03_update.sh && sh /tmp/update.sh
> ```
> 
> You will need to select firmware version and wait for the flashing of the firmwares to complete. These instructions are from https://github.com/zvldz/mgl03_fw.

exactly

**Comment by robertop13es** [comment]
Thank you, It's working again

Best regards

Roberto

**Comment by robertop13es** [comment]
You have selected Auto Update, 

You have to change it on the profile.

I had to do it twice too

**Comment by pnagy** [comment]
@robertop13es  Thanks a lot! I'll give it a shot. Any tip why the gateway is not able to resolve the domain names? I need to manually resolve the domains and use the IP in the wget and curl commands...

**Comment by jacobswin** [comment]
Do you turnoff the firmware auto updating in MiHome?

**Comment by AlexxIT** [comment]
Firmware 1.5.4 don't supported yet. It's written in readme.
