### ISSUE TITLE
Is it necessary to keep some stocks of the gateway right now?

### ISSUE THREAD

**Issue by likellindil** [AlexxIT/XiaomiGateway3#78]
This project perfectly meets all my requirements, it helps so much for my own home automation.
I mean, do I need to purchase some extra gateways as backups, or if the new firmware will be hacked in the future?
Thanks again for this great project.

Best regards,
Ken

**Comment by Zuz666** [comment]
It's good idea. I already ordered a couple. ))) But in the future, the problem is likely to be solved, in addition by enthusiasts. May be the access mechanism may be changed (for miIO / HomeKit), which does not require the old firmware and telnet access.

**Comment by AlexxIT** [comment]
@likellindil My friend has 3 gw in production and 3 as backups :)
New firmware will most likely require soldering for opening

**Comment by likellindil** [comment]
Thanks for the answers.
Yes, I also have 3 in production and have placed the order for another 3 as backups : )
Thanks again for this great project!

**Comment by AlexxIT** [comment]
In this moment all fw supported without soldering
