### ISSUE TITLE
Xiomi Ble thermo and humidity meter doesn't work in HA

### ISSUE THREAD

**Issue by gyenesadam** [AlexxIT/XiaomiGateway3#781]
Hi!

Sorry for interrupting and bad english.
A few weeks ago my mentioned thermometers suddenly stop working in HA (not because an update), but stil working in Xiaomi home.
All of zigbee devices still working, only Ble devices gone.

The exact type on picture:

![Screenshot_20220725-185642_Mi Home](https://user-images.githubusercontent.com/77073590/180833905-5fdc4743-1bfa-471f-bfba-e8a68bd717ab.jpg)

**Comment by AlexxIT** [comment]
Do you use supported gateway firmware?

**Comment by gyenesadam** [comment]
I think yes, because it worked for months.

**Comment by gyenesadam** [comment]
Sorry, my fault.
There was an automatic update for 1.5.4_0090......

(But it happened months after the faults.)

**Comment by AlexxIT** [comment]
Well. 1.5.4 doesn't supported yet
