### ISSUE TITLE
Cannot get rooms for roidmi.vacuum.v66

### ISSUE THREAD

**Issue by EVTrifonov** [AlexxIT/XiaomiGateway3#783]
Integration failed to get rooms information for Roidme Eva vacuum (roidmi.vacuum.v66):
  Rooms: Can't get from cloud

**Comment by AlexxIT** [comment]
Different models has different API. Maybe there are no such APIs for your vacuum at all.

**Comment by EVTrifonov** [comment]
It is obvious that it will have different API.
Device supported by MI Home application will all functions, including rooms.
As I can see, API can provide rooms information.
And XiaomiGateway3 integration sees devicr but only rooms cannot be retrived.
Will integration supports rooms in the future?

**Comment by AlexxIT** [comment]
Don't think so. I can't get API for all vacuum models.
