### ISSUE TITLE
Support yeelink.remote.contrl

### ISSUE THREAD

**Issue by ouzhg** [AlexxIT/XiaomiGateway3#784]
Hello AlexxIT,

Xiaomi Wireless Switch (2 keys version) https://home.miot-spec.com/spec/yeelink.remote.contrl only recognized as one notification, , could you help to add more entities?

very appreciated.

**Comment by TrustedFloppa** [comment]
Home Assistant or Xiaomi Home?

**Comment by ouzhg** [comment]
Xiaomi Home can recognize the buttons, but home assistant cannot. This request is duplicated with #774
