### ISSUE TITLE
Telnet cannot be enabled in the latest firmware version of Aqara gateway P3

### ISSUE THREAD

**Issue by FredLiu0512** [AlexxIT/XiaomiGateway3#785]
firmware version：4.0.1_0001
model：aqara p3
I have the token, but still can't add

**Comment by WarC0zes** [comment]
Read the documentation.

Note: Use another integrations for support:
Aqara G2H (ZNSXJ12LM), Aqara H1 CN (QBCZWG11LM), Aqara M1S CN (ZHWG15LM), Aqara M2 CN (ZHWG12LM), **Aqara P3 CN** (KTBL12LM) - [external link](https://github.com/niceboygithub/AqaraGateway)

**Comment by AlexxIT** [comment]
This component doesn't support this model
