### ISSUE TITLE
Mi Door and Window Sensor 2 – Light sensor is misrecognized

### ISSUE THREAD

**Issue by vazome** [AlexxIT/XiaomiGateway3#787]
Issue: The device has Light and Closure sensors, but the Light sensor is not recognized properly both in HA and Apple Home.

Details:

1. The light sensor does not change its values in HA:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46573198/182029686-b4790760-77bb-4fc8-bc6e-f061d6e326fc.png">

2. The light sensor appears as Occupancy sensor in Apple Home:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46573198/182029519-7908c280-8096-4f8f-abc5-3ffa9b84bcf4.png">

3. Mi Home example of an open window in a bright room:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46573198/182029576-1430de10-650c-4925-83ca-64772a3926aa.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/46573198/182029534-01c49196-0a2b-45cf-9478-049d6a3bf79c.png">

Target device: isa.magnet.dw2hl (Mi Door and Window Sensor 2)
Associated gateway: lumi.gateway.mgl03 (Mi Smart Home Hub)

Additional integrations: [Homekit](https://www.home-assistant.io/integrations/homekit) 

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

XiaomiGateway3 2.1.0

**Comment by AlexxIT** [comment]
You need to collect device debug log

**Comment by vazome** [comment]
Sorry, I don't hold the device at the moment.

**Comment by STmateo** [comment]
Hi, how did you manage to add it to home assistant?
I tried through passive BLE monitor, but nothing happens. It's encrypted.
Did you flash the firmware somehow?
