### ISSUE TITLE
_zigbee attribute gateway_name issue in 2022.8.0

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/XiaomiGateway3#791]
Previously sensor.*_zigbee attribute gateway_name contains gateway 'friendly name' where device connected.
Now (2022.8.0) it is same 'Xiaomi Gateway 3' on all devices, connected to different XG3 gateways.

![image](https://user-images.githubusercontent.com/15225823/182910368-c2e0e4e7-a03a-46bd-831e-bdb4323b2012.png)

P.S. As well Chip temperature (Door Sensors & Buttons) & Battery Low (Door Sensors) become disabled on upgrade.
Battery Low on Buttons still enabled and working.
Battery Low on Door Sensor possible to enable, but still Unknown.

Mystery. After some hours attribute gateway_name on devices connected to one XG3 suddenly changed to gateway friendly name 'XG3 S', but connected to other - still 'Xiaomi Gateway 3'.

**Comment by AlexxIT** [comment]
Fixed in latest master-version
