### ISSUE TITLE
Cannot install a new integration instance of Xiaomi Gateway 3

### ISSUE THREAD

**Issue by SergKz66** [AlexxIT/XiaomiGateway3#795]
After losing connection with the gateway, I cannot install a new integration instance.
I delete the integration, restart HA, add the integration - it appears in the system with all the old settings and does not ask for a new token.
Updated the repository in HACS - now the integration is not added through the standard settings menu, it just does not find it for installation.
I deleted the /config/custom_components/xiaomi_gateway3 directory, reinstalled the HACS repository - it didn’t help, it still doesn’t find the integration to add.

**Comment by GormYa** [comment]
[https://github.com/AlexxIT/XiaomiGateway3/pull/672](https://github.com/AlexxIT/XiaomiGateway3/pull/672)

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
