### ISSUE TITLE
Mosquito Repeller 2

### ISSUE THREAD

**Issue by jiangyiqi99** [AlexxIT/XiaomiGateway3#797]
Mosquito Repeller 2 has an issue. For its Bluetooth don't send signal hourly, your components will change it to "Unavailable" because of no statue update. But in fact, it is online in the Mesh Network. You should remove this Overtime counter for Mosquito Repeller 2 to resolve this problem.

**Comment by AlexxIT** [comment]
Should be fixed in latest master version. TTL=1440m
