### ISSUE TITLE
Wired issue with the Aqara presence detector FP1

### ISSUE THREAD

**Issue by wenjiavv** [AlexxIT/XiaomiGateway3#798]
Hello

I am trying to integrate the Aqara presence detector FP1 to the Xiaomi Mijia Smart
Multi-Mode Gateway ( which is in Zigbee2mqtt mode and works perfectly with other sensors). 

Once I pair the FP1 to the gateway, FP1 just leave the Zigbee network automatically. 

Since the FP1 is supported by Zigbee2MQTT according to the [[devices guide](https://www.zigbee2mqtt.io/devices/RTCZCGQ11LM.html)](https://www.zigbee2mqtt.io/devices/RTCZCGQ11LM.html), I am wandering if there is a restriction of the firmware (1.5.0_0026) blocking the FP1.

If anyone have encounter the same issue or it's just irrelevant to the xiaomigateway3.

Thank u very much.

Debug log of the zig2mqtt:

`Starting interview of '0x54ef441000dddddd'`

`MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x54ef441000dddddd","ieee_address":"0x54ef441000dddddd","status":"started"},"type":"device_interview"}'`

`MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x54ef441000dddddd"},"type":"pairing"}'`

`MQTT publish: topic 'zigbee2mqtt/0x54ef441000dddddd', payload '{"last_seen":"2022-08-14T16:58:53+08:00"}'`

`Warning: Device '0x54ef441000dddddd' left the network`

**Comment by vturekhanov** [comment]
I believe your issue is not related to this integration as gw3 firmware and integration itself is not used in z2m mode for work with zigbee devices. Gw3 in z2m mode is like usb-stick with zigbee chip inside.

**Comment by AlexxIT** [comment]
You need to ask about this zigbee2mqtt project repo
