### ISSUE TITLE
Support for Mijia Wireless Switch WXKG01LM

### ISSUE THREAD

**Issue by dobl1** [AlexxIT/XiaomiGateway3#80]
Hello,

Is support for the Wireless Switch WXKG01LM planned ?
Related question : iIs moving from DGNWG02LM to ZNDMWG03LM too early ?

Regards.
Dorian

**Comment by froggyfly** [comment]
I used DGNWG02LM and ZNDMWG03LM both,
Gateway 3 works well in ZHA mode to connect ZigBee 3.0 devices and also can link the BLE devices to ha,
In the current situation, using two gateways at the same time can achieve better results, It provide more connectable devices.

**Comment by AlexxIT** [comment]
Supported
