### ISSUE TITLE
Aqara E1 (QBKG39LM, firmware: 0.0.0_0020) can't rejoin in gateway

### ISSUE THREAD

**Issue by ahit976** [AlexxIT/XiaomiGateway3#803]
I have 3 Aqara E1 switches (QBKG39LM, Zigbee, singe wire double switch), and Xiaomi Mijia Smart Multi-Mode Gateway（hacked,v1.5.0_0102. These 3 E1 switches worked well since Dec. 2022.

Last week one of E1 was reseted, and after that it CAN NOT rejoin in the XiaoMi 3 gateway again, neither by Mi Home APP nor by physical key on XiaoMi 3 Gateway. I rebooted the Gateway and Switch several times, and called Xiaomi support, it does not work. XiaoMi Gateway 3 has 14 zigbee devices, is less than the limit number of 32.
The E1 is still well, it can join in another M1s Gateway correctly. But it CAN NOT rejoin in the XiaoMi 3 gateway again.

I don't know wether is it related to the E1's fireware (QBKG39LM, firmware: 0.0.0_0020). 
Dose anyone run into the same problem? Thanks.

**Comment by AlexxIT** [comment]
Have you any other ZigBee devices with this gateway? If they works fine?

**Comment by ahit976** [comment]
> Have you any other ZigBee devices with this gateway? If they works fine?

THANKS for your attention. This Xiaomi 3 gate way has 2 aqara E1 zigbee switches, 3 zigbee body motion and door sensors, 1 zigbee aqara D1, and 7 blue tooth devices(some of them has the fonction of bluetooth gateway). All these devices worked well. 
But one of 3 E1 Can not rejoin the Xiaomi gateway 3. it is still work when join aqara M1s for testing.
Thanks

**Comment by AlexxIT** [comment]
How many beeps do you heard?

**Comment by ahit976** [comment]
> How many beeps do you heard?

after 60 sec，heard one short beep. i search the manaul. it shows that fail to link

**Comment by AlexxIT** [comment]
Can you pair other Zigbee devices with this gateway?

**Comment by ahit976** [comment]
> Can you pair other Zigbee devices with this gateway?

I successfully intergrated a wireless remote key with the gateway. i think the gateway is  well.

**Comment by AlexxIT** [comment]
Well. You may try to reboot Gateway 3. And power off M1S during pairing.

**Comment by ahit976** [comment]
> Well. You may try to reboot Gateway 3. And power off M1S during pairing.

Thanks. I did that but still not work. I think it may be something about the firmware of E1 switch.

**Comment by AlexxIT** [comment]
No. Any Zigbee device can be paired with gateway.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
