### ISSUE TITLE
Mi Smart Mosquito Repeller 2 (WX10ZM) is'nt manually controlled

### ISSUE THREAD

**Issue by eratnik** [AlexxIT/XiaomiGateway3#804]
Mi Smart Mosquito Repeller 2 is'nt work. I see when the status Mosquito is changed but I can't change it manually.
A few time after the status is changed to unavailable.
[config_entry-xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/9372346/config_entry-xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7.json.txt)
[xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7-Шлюз-093dbccc50fce33064c69c118295541d.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/9372351/xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7-.-093dbccc50fce33064c69c118295541d.json.txt)
[xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7-Mi Smart Mosquito Repeller 2-0527d3cee35f680aeaa282b8ca6bdb38.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/9372352/xiaomi_gateway3-42de121019c383631b2bfd38dc1ebdf7-Mi.Smart.Mosquito.Repeller.2-0527d3cee35f680aeaa282b8ca6bdb38.json.txt)
In MiHome Mosquito Repeller 2 works ok.
Tell me please if you need something else.
[![Screenshot-2.png](https://i.postimg.cc/3RLsQRrC/Screenshot-2.png)](https://postimg.cc/hzdy9Kdf)

**Comment by AlexxIT** [comment]
Have you any other Mesh devices (not BLE)? Can you control mosquito from MiHome?

**Comment by eratnik** [comment]
> Have you any other Mesh devices (not BLE)? Can you control mosquito from MiHome?

Only gateway ZNDMWG03LM. It's my problem?

**Comment by AlexxIT** [comment]
Can you control this device from MiHome?

**Comment by eratnik** [comment]
> Can you control this device from MiHome?

Yes, it's work well, but i think Mosqitto connect by my phone

**Comment by AlexxIT** [comment]
Well. Try to control it outside your home. Or far away from this device.

**Comment by mihsu81** [comment]
I'm having almost the same issue, but I can control the device from HA.
After a while (didn't check the actual period of time) all the entities become unavailable.
But if I open the device in Mi Home, all its attributes are again populated in HA, except Supply.
![image](https://user-images.githubusercontent.com/40715497/188278033-6c5f431f-db9b-43b6-81ec-4605e75237a8.png)

**Comment by AlexxIT** [comment]
Unavailable is another problem with right ttl (time to live) for this device.

**Comment by mihsu81** [comment]
@AlexxIT is the TTL issue solvable?

**Comment by AlexxIT** [comment]
Yes. Just need to add right number to device description. But I don't know right number. Maybe 10 minutes...
https://github.com/AlexxIT/XiaomiGateway3/blob/001e9d7ca5b657fb6ac666e54a0c334d5092e502/custom_components/xiaomi_gateway3/core/converters/devices.py#L1516

**Comment by eratnik** [comment]
> Well. Try to control it outside your home. Or far away from this device.

If i try to control the device in miHome outside, it works well. And when i connect Mosqitto to usb - home assistant control this also well. But when I change power to battery - I can't to control it in home assistant. 🤯

**Comment by mihsu81** [comment]
> Yes. Just need to add right number to device description. But I don't know right number. Maybe 10 minutes...
> 
> https://github.com/AlexxIT/XiaomiGateway3/blob/001e9d7ca5b657fb6ac666e54a0c334d5092e502/custom_components/xiaomi_gateway3/core/converters/devices.py#L1516

I've checked the logs of HA and its entities change to Unavailable after exactly 3 hours. What do I need to add in devices.py?

**Comment by eratnik** [comment]
> .

Sorry. Now, when i off wifi and Bluetooth in my phone miHome writes 'No Bluetooth mesh gateway found'. ![Screenshot_2022-09-03-19-59-19-349_com.xiaomi.smarthome.jpg](https://user-images.githubusercontent.com/23414787/188285198-8f6f667e-c941-408e-b898-5f08cf8593a0.jpg)

**Comment by mihsu81** [comment]
> > Yes. Just need to add right number to device description. But I don't know right number. Maybe 10 minutes...
> > https://github.com/AlexxIT/XiaomiGateway3/blob/001e9d7ca5b657fb6ac666e54a0c334d5092e502/custom_components/xiaomi_gateway3/core/converters/devices.py#L1516
> 
> I've checked the logs of HA and its entities change to Unavailable after exactly 3 hours. What do I need to add in devices.py?

Had a better look and found the instructions. 😆
I'll check with 175m and submit a PR if it works fine.
```
 {
    4160: ["Xiaomi", "Mosquito Repeller 2", "WX10ZM"],
    # "support": 5,  # @AlexxIT need some tests
    "spec": [
        Converter("switch", "switch", mi="2.p.1"),  # bool
        Converter("battery", "sensor", mi="3.p.1"),  # percentage 0-100
        Converter("supply", "sensor", mi="4.p.1"),  # percentage 0-100
        Converter("led", "switch", mi="9.p.1", enabled=False),  # bool
        MapConv("power_mode", "select", mi="2.p.2", map={
            0: "auto", 1: "battery", 2: "usb"
        }, enabled=False)
    ],
    "ttl": "175m"
},
```
P.S. How can I find the device 4 digit number? I'm trying to add Battery and Supply for a Soocas X3 .

**Comment by mihsu81** [comment]
"ttl": "1440m" worked fine (1 day). The entities didn't change to Unavailable anymore.

**Comment by AlexxIT** [comment]
Thanks. This was merged long time ago
