### ISSUE TITLE
RTCGQ02LM mi bluetooth motion sensor take 2mins to clear motion

### ISSUE THREAD

**Issue by lysiong** [AlexxIT/XiaomiGateway3#805]
I consider myself as beginner in HA. I recently just migrate from Mi Home automation to Home Assistant. All working fine except Mi Motion bluetooth sensor take 2mins to clear motion status(in HA) while in Mi Home take less than 1min. 

Detail as below
gateway: ZNDMWG03LM, firmware version: 1.5.0_0102
motion sensor: ble RTCGQ02LM

is that anyway to reduce this motion clear time from 2mins to 1min in HA?

**Comment by TrustedFloppa** [comment]
if you would have zigbee motion sensor would clear in 1-2 minutes on HA and xiaomi home
BLE has delay about refreshing current status. I think zigbee is more faster than BLE

**Comment by lysiong** [comment]
I just figure out need to set the occupancy_timeout value in customize.yaml. I don't know why HA not allow to set in configuration.yaml which come out error. Currently I set occupancy_timeout=5 which work perfectly as behave like set in Mi Home apps. 

I have 8pcs of Mi bluetooth motion2 sensor but only 1 Agara zigbee motion sensor, both response time seem like same.
