### ISSUE TITLE
ZNDMWG02LM firmware

### ISSUE THREAD

**Issue by TrustedFloppa** [AlexxIT/XiaomiGateway3#807]
Hello, I want to downgrade firmware because it updated it own, I found this https://github.com/zvldz/mgl03_fw but i am not sure if its working on ZNDMWG02LM and i dont want to brick my Gateway

**Comment by lysiong** [comment]
it is working, I have 2pcs of ZNDMWG03LM(china version) & 1pc of ZNDMWG02LM(global version), both downgrade from firmware version 1.54_0090 to 1.5.0_0102
