### ISSUE TITLE
Can't enable telnet

### ISSUE THREAD

**Issue by ameran** [AlexxIT/XiaomiGateway3#811]
Hi AlexxIT, Please help! 

I installed and got the integration working in April, it ran fine for a few months then updated HA and it broke, so I removed and reinstalled the integration.
I managed to get the integration to see the Gateway, and query the account which adds the devices, but it doesn't show their states or battery levels like it used to. 
I was able to downgrade the firmware on the Gateway to 1.5.0_0102 using this, but still it’s still not updating the sensors. 
The open telnet command I’m using in HA is :- {"method":"set_ip_info","params":{"ssid":"""","pswd":"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd"}}

I've enabled logging and the logs now say this :- 
2022-08-30 19:50:11.780 INFO (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 192.168.1.1XX | No answer on set_ip_info {'ssid': '""', 'pswd': '123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd'}
2022-08-30 19:50:11.782 DEBUG (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 192.168.1.1XX [BASE] Can't enable telnet

I can ping the gateway, I just can’t telnet to it, but this was how I updated the firmware, but now I can’t!
The MiHome app see’s the BT devices, its just not pulling through to HA.
Any ideas on what i’m doing wrong?!?!

Home Assistant 2022.8.4
Supervisor 2022.08.5
Operating System 8.4
Frontend 20220802.0 - latest
gateway ZNDMWG03LM ZNDMWG02LM
Firmware: 1.5.0_0102

devices - ble MCCGQ02HL

**Comment by AlexxIT** [comment]
If you reset gateway, its token may be changed

**Comment by ameran** [comment]
I retried, but it still wouldn't. 
Then I FTP'd into the GW, restarted it and tried to telnet again and somehow that worked!

**Comment by ameran** [comment]
I retried, but it still wouldn't.
Then I FTP'd into the GW, restarted it and tried to telnet again and somehow that worked!
Re-flashed firmware, now I'm able to telnet again.

Now it picks up all the sensors, but doesn't update their status or battery levels.

**Comment by AlexxIT** [comment]
Sometimes you need to full reset gateway after flash new firmware

**Comment by ameran** [comment]
I've done that, and the gateway shows up and adds the sensors, but it doesn't update the battery % or the status of the sensors and I don't see any errors in the logs.

What else should I try to restore functionality?

**Comment by AlexxIT** [comment]
You just need to wait
