### ISSUE TITLE
Aqara E1 mini wireless switch unknown

### ISSUE THREAD

**Issue by kei81131** [AlexxIT/XiaomiGateway3#812]
Hi the Aqara E1 mini wireless switch shown unknown   
(lumi.remote.acn007)

Is it really cant use at this moment? 
or I do something wrong?

**Comment by kei81131** [comment]
tried to Overwrite device model to xiaomi button WXKG01LM 
however still not working

**Comment by cyberken168** [comment]
not work.
any one can deploy it ?

**Comment by AlexxIT** [comment]
Is is work fine in MiHome? You need to provide more debug logs

**Comment by kei81131** [comment]
Thanks so much for your attention 
sorry that I don't know how to find debug logs 
Is this txt help?

Also, it works fine in MiHome

[xiaomi_gateway3-f055748956a558f0ff1a9d2f50fa3460-Unknown ZIGBEE-65ba351ae1d7d0ba9ec292f36b1e83ee.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/9643926/xiaomi_gateway3-f055748956a558f0ff1a9d2f50fa3460-Unknown.ZIGBEE-65ba351ae1d7d0ba9ec292f36b1e83ee.json.txt)

**Comment by AlexxIT** [comment]
Should be supported in latest master version

**Comment by cyberken168** [comment]
Just for the click function. 

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
  
const definition = {
        zigbeeModel: ['lumi.remote.acn007'],
        model: 'WXKG20LM',
        vendor: 'Xiaomi',
        description: 'Aqara E1 wireless mini switch',
        fromZigbee: [fz.xiaomi_multistate_action, fz.command_toggle],
        toZigbee: [tz.xiaomi_switch_click_mode],
        exposes: [e.action(['single', 'double', 'hold'])],
};

module.exports = definition;

**Comment by kei81131** [comment]
> Should be supported in latest master version

after updated devices.py 
it works properly, thanks so much
