### ISSUE TITLE
Cannot add (submit) gateway

### ISSUE THREAD

**Issue by Snubbeke** [AlexxIT/XiaomiGateway3#815]
Added the component XiaomiGateway3 (AlexITT) via HACS (latest version 2.1.1) while I installed the Xiaomi App on my phone and paired the gateway and all worked. HASS is on latest version Home Assistant 2022.8.7 - Supervisor 2022.08.5 - Operating System 8.5 - Frontend 20220802.0).

Configured the component with email address and password and selected Chinese server as instructed in the video from Alex. Gateway did not show up so I added the Europe server as well and now the gateway shows up and I was able to select in the configuration but in the next step the device / gateway shows up but after hitting submit, nothing happens. The pop up screen remains as is and I can submit forever but nothing happens.
See also [https://community.home-assistant.io/t/xiaomigateway3-alexitt-cannot-add-gateway/456456](url)

I can ping the gateway.
Uninstalled component and reinstalled.

**Comment by AlexxIT** [comment]
Just follow docs
https://github.com/AlexxIT/XiaomiGateway3#configuration
