### ISSUE TITLE
Add support for HS1BB motion sensor

### ISSUE THREAD

**Issue by Snakesms** [AlexxIT/XiaomiGateway3#816]
Please kindly add support for the newly released motion sensor from Linptech with model: hs1bb

From a functionality perspective, it looks almost identical to the motion sensor from Qingping CGPR1

As suggested I've attached a few diagnostic messages:
- Idle,
- motion detected
- no motion within 2 mins
- motion detected

If I can help with other data - pls let me know

Thanks and regard,
Sergiy

[xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech Motion Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json (1).txt](https://github.com/AlexxIT/XiaomiGateway3/files/9480104/xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech.Motion.Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.1.txt)
[xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech Motion Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json (2).txt](https://github.com/AlexxIT/XiaomiGateway3/files/9480105/xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech.Motion.Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.2.txt)
[xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech Motion Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json (3).txt](https://github.com/AlexxIT/XiaomiGateway3/files/9480106/xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech.Motion.Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.3.txt)
[xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech Motion Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json (4).txt](https://github.com/AlexxIT/XiaomiGateway3/files/9480108/xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech.Motion.Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.4.txt)
[xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech Motion Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/9480109/xiaomi_gateway3-573ef09ba19560005ff0f6f2252cc397-Linptech.Motion.Sensor-2e1386d7e455cceb9c0b3bc471d9ae61.json.txt)

**Comment by micturkey** [comment]
Since Linptech has updated the motion sensor to version 2, I think it is better to use this log:
https://github.com/AlexxIT/XiaomiGateway3/issues/809#issuecomment-1242608550
