### ISSUE TITLE
How to switching from ZHA to Mi Home mode 

### ISSUE THREAD

**Issue by NathanDai** [AlexxIT/XiaomiGateway3#82]
How to switching from ZHA to Mi Home mode , I try a lot of ways but it donot works 
now i could only use ZHA,but i could not use mi app to add a zigbee device

**Comment by froggyfly** [comment]
Delete the gateway3 and reinstall it without selected zha mode.

**Comment by NathanDai** [comment]
> 删除集成里的xiaomigateway3，在重新添加时候不要勾选zha模式

我尝试过了 无法回去 仍然是zha模式 并且HomeKit也会识别不到

**Comment by AlexxIT** [comment]
Have you read readme? https://github.com/AlexxIT/XiaomiGateway3#zigbee-home-automation-mode

**Comment by NathanDai** [comment]
最后找的问题了,是路由器dhcp分配的问题
