### ISSUE TITLE
Request to add support for lumi.light.acn003

### ISSUE THREAD

**Issue by littlehi** [AlexxIT/XiaomiGateway3#825]
Can you please add support for lumi.light.acn003
https://github.com/niceboygithub/AqaraGateway/commit/9c3ff9547dbaed73f76ba554b46eacf5e18e5713

**Comment by jwxa** [comment]
you can test it yourself.
it passed and my gateway firmware version is 1.5.4_0090

open file: custom_components\xiaomi_gateway3\core\converters\devices.py
search "lumi.light.acn014" in file, jump to the line, and add following json doc
before change it, you can have a copy to backup.
{
    "lumi.light.acn003": ["Aqara", "L1-350 Ceiling Light", "ZNXDD01LM"],
    "spec": [
        BoolConv("light", "light", mi="4.1.85"),
        ZXiaomiBrightnessConv("brightness", mi="14.1.85", parent="light"),
        ZXiaomiColorTempConv("color_temp", mi="14.2.85", parent="light"),
    ],
},

restart and enjoy yourself

**Comment by littlehi** [comment]
thank you,  but it doesn't support version 1.5.0_xx

**Comment by jwxa** [comment]
you can change the code like following and have a try
{
"lumi.light.acn003": ["Aqara", "L1-350 Ceiling Light", "ZNXDD01LM"],
"spec": [
BoolConv("light", "light", mi="2.1"),
ZXiaomiBrightnessConv("brightness", mi="2.2", parent="light"),
ZXiaomiColorTempConv("color_temp", mi="2.3", parent="light"),
],
},

**Comment by littlehi** [comment]
> you can change the code like following and have a try
> {
> "lumi.light.acn003": ["Aqara", "L1-350 Ceiling Light", "ZNXDD01LM"],
> "spec": [
> BoolConv("light", "light", mi="2.1"),
> ZXiaomiBrightnessConv("brightness", mi="2.2", parent="light"),
> ZXiaomiColorTempConv("color_temp", mi="2.3", parent="light"),
> ],
> },

Hi Jwxa, It still not working, the device is recognized correctly, but cannot be controlled.

**Comment by jwxa** [comment]
1.5.0_0102  passed

{
    "lumi.light.acn003": ["Aqara", "L1-350 Ceiling Light", "ZNXDD01LM"],
    "spec": [
        BoolConv("light", "light", mi="2.p.1"),
        ZXiaomiBrightnessConv("brightness", mi="2.p.2", parent="light"),
        ZXiaomiColorTempConv("color_temp", mi="2.p.3", parent="light"),
    ],
}

**Comment by littlehi** [comment]
it works, thank you.
