### ISSUE TITLE
Support  Linptech BLE Switch Sensor K11（linp.remote.k9b01） (Feature Req)

### ISSUE THREAD

**Issue by goxofy** [AlexxIT/XiaomiGateway3#826]
Hi AlixxIT, could you please support this Linptech BLE Switch K11 for gw3

specs here: https://home.miot-spec.com/spec/linp.remote.k9b01

now this ble switch only shows a Battery info but no switch entities.

![image](https://user-images.githubusercontent.com/1695416/190190729-422a9baf-c00b-440b-8a57-f00a8de54bcd.png)

**Comment by rezmus** [comment]
```
linp.remote.k9b01 - Linptech wireless switch K11

conditions:
101 Click the button (event.3.1012 {"sub_props":{"attr":[{"key":"prop.linp.remote.k9b01.3.1","value":1}],"express":0}})
101 Double-click the button (event.3.1012 {"sub_props":{"attr":[{"key":"prop.linp.remote.k9b01.3.1","value":15}],"express":0}})
101 Long press the button (event.3.1012 {"sub_props":{"attr":[{"key":"prop.linp.remote.k9b01.3.1","value":8}],"express":0}})
```
```
prop.2.1003 (Battery Level) uint8 = eid 18435 (0x4803)
event.3.1012 (Click) = eid 19980 (0x4e0c)
event.3.1013 (Double Click) = eid 19981 (0x4e0d)
```
according to spec there is separate event for single/double click, but spec are sometimes fake. according to mijia automation it will be eid 19980 (0x4e0c) with value 1 for single, 8 for long and 15 for double.

**Comment by goxofy** [comment]
H! @rezmus , could you tell me to how use these informations? thanks alot

**Comment by rezmus** [comment]
it is more for @AlexxIT but you can try to add it yourself, should not be hard ;)

**Comment by goxofy** [comment]
thanks a lot！@rezmus

**Comment by goxofy** [comment]
i have added this device support by myslef， thank you all！

**Comment by AlexxIT** [comment]
@goxofy so can you provide how you did it?

**Comment by goxofy** [comment]
> @goxofy so can you provide how you did it?

ok， @AlexxIT i will pull a request for this device

**Comment by nesror** [comment]
use latest master branch, it not work on Xiaomi Multimode Gateway 2
<img width="502" alt="image" src="https://user-images.githubusercontent.com/8413360/203677492-4e3168fb-5f51-4ecf-be3c-feea4bd76e35.png">

MQTT log:
Click the button
[MQTT] miio/report b'{"id":1902911651,"method":"event_occured","params":{"did":"blt.3.1c80rtqik5g02","siid":3,"eiid":1012,"tid":117,"arguments":[{"piid":1,"value":1}]},"type":6}'
[MQTT] miio/report_ack b'{"id":1902911651,"result":"ok"}'

Double-click
 [MQTT] miio/report b'{"id":921131652,"method":"event_occured","params":{"did":"blt.3.1c80rtqik5g02","siid":3,"eiid":1012,"tid":118,"arguments":[{"piid":1,"value":15}]},"type":6}'
 [MQTT] miio/report_ack b'{"id":921131652,"result":"ok"}'

Long press 
 [MQTT] miio/report b'{"id":921131653,"method":"event_occured","params":{"did":"blt.3.1c80rtqik5g02","siid":3,"eiid":1012,"tid":118,"arguments":[{"piid":1,"value":8}]},"type":6}'
 [MQTT] miio/report_ack b'{"id":921131653,"result":"ok"}'
