### ISSUE TITLE
Xiaomi Water Leak Sensor not updating water leak status

### ISSUE THREAD

**Issue by biscuitee** [AlexxIT/XiaomiGateway3#829]
Hi, I have added a Xiaomi Water Leak Sensor (BLE Model: lumi.flood.bmcn01) to Xiaomi Gateway 3. The gateway is connected to my Home Assistant via XiaomiGateway3 integration.   The water leak sensor has shown up in the Gateway3 integration.

While I am able to receive leak notification from my Mi Home App, HomeAssistant is not able to detect any change from the Water Leak Sensor (which always show as Dry and battery at 100%).  
Log in HA for the water leak sensor only get updated when I restarted the HA, but it is showing only the dry status (even Mi Home App is showing water leak detected status).

   Rain Sensor Water Leak cleared (no detected)
   11:55:43 AM - 26 minutes ago
   Rain Sensor Water Leak became unavailable
   11:55:42 AM - 26 minutes ago

Can anyone help to resolve this issue? Many thanks.

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by biscuitee** [comment]
Hi, is the following the diagnostic log required? 

"integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "b23a66a",
    "options": {
      "host": "***",
      "token": "***",
      "telnet_cmd": "{\"method\":\"set_ip_info\",\"params\":{\"ssid\":\"\\\"\\\"\",\"pswd\":\"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd\"}}",
      "ble": true,
      "stats": false,
      "debug": [
        "true",
        "zigbee"
      ],
      "buzzer": false,
      "memory": false,
      "zha": false
    },
    "errors": [],
    "device": {
      "type": "ble",
      "model": 2147,
      "fw_ver": null,
      "available": true,
      "decode_time": 699,
      "entities": {
        "water_leak": "off",
        "battery": {
          "state": "100",
          "value": 100
        },
        "action": {
          "state": "DISABLED",
          "value": ""
        }
      },
      "gateways": [
        "54ef44c87a62"
      ],
      "unique_id": "54ef44c62821"
    },
    "logger": null
  }
}

**Comment by AlexxIT** [comment]
Thanks. You need to:

1. Download device diagnostics
2. Wet the sensor
3. Download device diagnostics again
4. Show second diagnostics

**Comment by biscuitee** [comment]
Hi

I have added the debug logger as follows:

logger:
   default: info
   logs:
      xiaomi_gateway: debug
      homeassistant.components.xiaomi_aqara: debug
      homeassistant.components.sensor.xiaomi_aqara: debug
 #     homeassistant.components.binary_sensor.xiaomi_aqara: debug
      homeassistant.components.binary_sensor: debug

however I am not able to find any entry in homeassistant log for the water leak sensor.  There dont seem to be sending response to homeassistant, but the sensor is working fine in xiaomi mihome app.  the model of the sensor in gateway3 is ble SJWS01LM

**Comment by AlexxIT** [comment]
I don't need logs. I need diagnostics

**Comment by kyc1338** [comment]
I have the same leak sensor and have no issue using gateway 3 to integrate into HA.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
