### ISSUE TITLE
Can't read devices. invalid continuation byte

### ISSUE THREAD

**Issue by rozhkovets** [AlexxIT/XiaomiGateway3#83]
home assitant 0.116.4
XiaomiGateway3 v0.7.2
Xiaomi Gateway 3 (ZNDMWG03LM) v1.4.6_0012

After adding Xiaomi Gateway 3 (ZNDMWG03LM) to home assistant I get a message that the configuration has been created, but no new devices and objects are being added.
In logs I get a lot of

2020-10-27 13:32:05 DEBUG (Thread-7) [custom_components.xiaomi_gateway3.gateway3] 192.168.88.101 | Read devices
2020-10-27 13:32:06 DEBUG (Thread-7) [custom_components.xiaomi_gateway3.gateway3] Can't read devices: 'utf-8' codec can't decode byte 0xdb in position 746: invalid continuation byte

ping gateway is ok, telnet is open and i can connect and login

**Comment by AlexxIT** [comment]
Have you downgraded firmware?

**Comment by rozhkovets** [comment]
yes, downgrade after mistaken update to v1.4.7_0063

**Comment by AlexxIT** [comment]
You need telnet. Go here `/data/zigbee_gw/` and remove all files except `zigbee_gw.db`.
Probably there are extra json files from `v1.4.7_0063`.

**Comment by rozhkovets** [comment]
this solved the problem, thanks
