### ISSUE TITLE
Aqare Water Leak Sensor E1 not supported

### ISSUE THREAD

**Issue by biscuitee** [AlexxIT/XiaomiGateway3#837]
Hi, I have recently bought the Aqare Water Leak Sensor E1 and added to Mi Home App.  The sensor is connected with Xiaomi Gateway 3 and I have added Gateway 3 to Home Assistant via this integration.  However I am unable to find the Aqara water leak sensor in my home assistant under Xiaomi Gateway 3 hub.  Other sensors and buttons are showing up except the Aqara Water Leak Sensor E1.  Can someone help?

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by biscuitee** [comment]
Hi,  I am not sure how to show the diagnostic but the Aqara Water Leak Sensor E1 is not showing up as a device in Gateway 3 in Home Assistant.

Separately I have another xiaomi BLE water leak sensor that shown up in the Gateway 3 Home Aassistant.  However the status is never updated and show as Dry always.  The diagnostic config as follow:
      "54ef44c62821": {
        "type": "ble",
        "model": 2147,
        "fw_ver": null,
        "available": true,
        "decode_time": 154,
        "entities": {
          "water_leak": "off",
          "battery": {
            "state": "100",
            "value": 100
          },
          "action": {
            "state": "DISABLED",
            "value": ""
          }
        },
        "gateways": [
          "54ef44c87a62"
        ]
      },

**Comment by AlexxIT** [comment]
You can enable Debug logs and catch work of Sensor E1.

**Comment by biscuitee** [comment]
Hi

I have added logger to homeassistant config as follow:
logger:
   default: info
   logs:
      xiaomi_gateway: debug
      homeassistant.components.xiaomi_aqara: debug
      homeassistant.components.sensor.xiaomi_aqara: debug
      homeassistant.components.binary_sensor: debug

However i couldnt find any entry of the sensor in the homeassistant.  In fact, I could not see the sensor appearing as a device under Gateway 3 integration.  What should I do next?

**Comment by terenceng81** [comment]
I have exactly the same issue..

**Comment by terenceng81** [comment]
Attached the device diagnostics log

[xiaomi_gateway3-8717d98626f6067c355604a9eada9c3a-Unknown ZIGBEE-0a467dc21b91512d72ad4d92b819396d.json (4).txt](https://github.com/AlexxIT/XiaomiGateway3/files/11350800/xiaomi_gateway3-8717d98626f6067c355604a9eada9c3a-Unknown.ZIGBEE-0a467dc21b91512d72ad4d92b819396d.json.4.txt)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
