### ISSUE TITLE
gateway 3 not found

### ISSUE THREAD

**Issue by wifi75** [AlexxIT/XiaomiGateway3#84]
hello why on my list there isn't gateway 3?

![image](https://user-images.githubusercontent.com/31816231/97295976-4fc9af00-1850-11eb-8f76-8a8e0a5ca7da.png)

installation it is ok:

![image](https://user-images.githubusercontent.com/31816231/97296050-6c65e700-1850-11eb-898a-96ab3c96d263.png)

**Comment by alexv190** [comment]
It also does not work for me.
Using hassio on raspberry 4.
Installed addon via HACS
It worked fine when I was testing it on my PC - Home assistant on windows via docker

**Comment by AlexxIT** [comment]
Browser cache
