### ISSUE TITLE
Can I open from gui log

### ISSUE THREAD

**Issue by maury77** [AlexxIT/XiaomiGateway3#840]
I set configuration setting on gui but the page is not appear in teh notify of HA

![image](https://user-images.githubusercontent.com/35746732/195075536-52cfdcf1-e885-44d4-bbeb-f6f9cf72a73b.png)

![image](https://user-images.githubusercontent.com/35746732/195075845-292607db-5159-4bfb-8d61-9248acc6e816.png)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#debug-mode
