### ISSUE TITLE
Sensor data is not being pushed to homekit via Xiaomi Gateway 3

### ISSUE THREAD

**Issue by barisonal** [AlexxIT/XiaomiGateway3#842]
If a zigbee sensor (Sonoff SNZB-03 Motion Sensor) lost connection to Xiaomi Gateway 3 (ZNDMWG03LM), it can reconnect to the gateway and sensor data goes to home assistant, but the thing is data in not being pushed to homekit. 

It looks like Apple Home App can not access to sensor's information. 
<img width="653" alt="CleanShot 2022-10-12 at 02 32 42@2x" src="https://user-images.githubusercontent.com/5008507/195217042-a5b4a4e6-d062-4e1a-aee8-381459855a95.png">

**Comment by AlexxIT** [comment]
If sensor works in Home Assistant and doesn't work in HomeKit - it's a problem of HomeKit integration
