### ISSUE TITLE
Strange behavior for WS-EUK01/WS-EUK02 Aqara Wall Switches - Not pairing with Gateway 3 ZNDMWG02LM

### ISSUE THREAD

**Issue by digitalsteezdesign** [AlexxIT/XiaomiGateway3#847]
I tried pairing a brand new wall switch WS-EUK01 & WS-EUK02 and the 3 beep sound comes at the end of the pairing. (incompatible device)
I have the HUB ZNDMWG02LM with 1.4.6_0012 SW. What i find strange is that the HUB actually pairs it, but unpairs it after.
Tried with the app also on mainland CHINA but with most recent xiaomi IOS App, doesn't see the hub anylonger on CHINA servers.
![AQARA WS-EUK01 incompatible with HUB Xiaomi 3](https://user-images.githubusercontent.com/71170980/196038486-4de11c4f-b8af-4b7d-be56-6d3f824faa3d.jpg)
What can i do aside from selling these switches? Thanks!

**Comment by rezmus** [comment]
hub can be connected to any region and zigbee3 devices will pair only on cn region.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#regional-restrictions
