### ISSUE TITLE
Wrong name Xiaomi Mesh Downlight

### ISSUE THREAD

**Issue by RnzTop** [AlexxIT/XiaomiGateway3#848]
All mesh Downlights in device menu named “Xiaomi Mesh Downlight”, although before that they had individual names that I gave them. Sometimes they take back their names on their own, but not in a different way.

**Comment by RnzTop** [comment]
![Uploading 102F63E1-C816-4955-81FA-D22BDCF2B4DF.png…]()

**Comment by AlexxIT** [comment]
You haven't attach image. Can you provide more info?

**Comment by RnzTop** [comment]
![FD63C70D-BEAA-41F2-921D-9E2BB55106E8](https://user-images.githubusercontent.com/93583185/208729743-15c2d414-7d3a-4fd7-941e-d2d70f584f34.png)

**Comment by RnzTop** [comment]
All spots have the names I set, but sometimes they are all displayed with the same name (as in the screenshot).

**Comment by AlexxIT** [comment]
Have you set up names in the MiHome app?

**Comment by RnzTop** [comment]
![8F8654F7-3E2D-4218-819F-907040E33124](https://user-images.githubusercontent.com/93583185/208740009-d566120f-7005-4033-a4fa-0b04e699da42.png)
In the Mi Home application, the spots have the names I set. When migrating to HA through integration, I also gave them individual names.
Sometimes the list of devices displays the names I set earlier, and sometimes they are the same.

**Comment by AlexxIT** [comment]
You need to set up cloud integration. Names are downloaded from the cloud.
