### ISSUE TITLE
Mesh devices can't get state with Xiaomi Black Hub in the account 

### ISSUE THREAD

**Issue by kingwap99** [AlexxIT/XiaomiGateway3#849]
Is there any one faced this same issue 
"bt mesh switch entities don't reflect the status changed by Mijia app but can be only set on / off"
I am useing the updated firmware for mi smart home hub ZNDMWG02LM and installed one xiaomi bub 2 ZSWG01CM
My ha server worked well before and this issue just happened abroud 6 days ago
```
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Taipei",
    "os_name": "Linux",
    "os_version": "5.15.0-52-generic",
    "supervisor": "2022.10.0",
    "host_os": "Ubuntu 20.04.5 LTS",
    "docker_version": "20.10.20",
    "chassis": "desktop",
    "run_as_root": true
  },
  "custom_components": {
    "tapo": {
      "version": "1.2.16",
      "requirements": [
        "plugp100==2.1.18"
      ]
    },
    "aqara_gateway": {
      "version": "0.0.14",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "xiaomi_miio_raw": {
      "version": "2022.8.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "xiaomi_miio_fan": {
      "version": "2022.8.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "var": {
      "version": "0.15.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "tuya_v2": {
      "version": "1.2",
      "requirements": [
        "tuya-iot-py-sdk==0.2.2"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "webrtc": {
      "version": "v2.3.1",
      "requirements": []
    },
    "xiaomi_gateway3": {
      "version": "2.1.2",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
    "line_notify": {
      "version": "1.0.1",
      "requirements": []
    },
    "tapo_control": {
      "version": "3.7.0",
      "requirements": [
        "pytapo==2.3",
        "onvif-zeep-async==1.2.0"
      ]
    },
    "hello_miai": {
      "version": "1.0.0",
      "requirements": []
    },
    "dohome": {
      "version": "0.2.0",
      "requirements": []
    },
    "xiaomi_miio_cooker": {
      "version": "2022.8.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "xiaomi_miot": {
      "version": "0.7.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "yeelight_bt": {
      "version": "1.3.0",
      "requirements": [
        "bleak>=0.18.0",
        "bleak-retry-connector>=2.1.3"
      ]
    },
    "notify_line": {
      "version": "2022.7.1",
      "requirements": []
    },
    "zhimi": {
      "version": "1.0.1",
      "requirements": [
        "miservice>=2.0.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "9459a0f",
    "options": {
      "host": "***",
      "token": "***",
      "telnet_cmd": "{\"method\":\"set_ip_info\",\"params\":{\"ssid\":\"\\\"\\\"\",\"pswd\":\"123123 ; passwd -d admin ; echo enable > /sys/class/tty/tty/enable; telnetd\"}}",
      "ble": true,
      "stats": true,
      "debug": [
        "true"
      ],
      "buzzer": true,
      "memory": true,
      "zha": false
    },
    "errors": [],
    "device": {
      "type": "mesh",
      "model": 3789,
      "fw_ver": null,
      "available": true,
      "decode_time": 2,
      "encode_time": 3,
      "entities": {
        "channel_1": "off",
        "channel_2": "off",
        "mesh": {
          "state": "2022-10-22T05:43:12+00:00",
          "value": "2022-10-22T05:43:12.780703+00:00"
        }
      },
      "gateways": [
        "54ef4424c031",
        "54ef4431600e",
        "54ef4423bfed"
      ],
      "stats": {
        "mac": "b460ede09cc6",
        "available": true,
        "msg_received": 5,
        "last_msg": "3.p.1"
      },
      "unique_id": "b460ede09cc6"
    },
    "logger": null
  }
}
```

**Comment by super-new13** [comment]
我也遇到了这种情况

**Comment by AlexxIT** [comment]
Is problem still actual?

**Comment by kingwap99** [comment]
> Is problem still actual?

thanks a lot, but 
yes, still be there.
the diagnostics as below for your reference
If necessary, I can share my mijia app devices with you and let you login into my ha system to check it.


{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Asia/Taipei",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "notify_line": {
      "version": "2022.7.1",
      "requirements": []
    },
    "zhimi": {
      "version": "1.0.1",
      "requirements": [
        "miservice>=2.0.1"
      ]
    },
    "line_notify": {
      "version": "1.0.1",
      "requirements": []
    },
    "dohome": {
      "version": "0.2.0",
      "requirements": []
    },
    "tuya_v2": {
      "version": "1.2",
      "requirements": [
        "tuya-iot-py-sdk==0.2.2"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "webrtc": {
      "version": "v3.0.1",
      "requirements": []
    },
    "xiaomi_miio_cooker": {
      "version": "2022.11.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "hello_miai": {
      "version": "1.0.0",
      "requirements": []
    },
    "yeelight_bt": {
      "version": "1.3.0",
      "requirements": [
        "bleak>=0.18.0",
        "bleak-retry-connector>=2.1.3"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.5",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "frigate": {
      "version": "3.0.0",
      "requirements": []
    },
    "xiaomi_gateway3": {
      "version": "3.0.1",
      "requirements": [
        "zigpy>=0.42.0"
      ]
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo_control": {
      "version": "4.2.1",
      "requirements": [
        "pytapo==2.9.2",
        "onvif-zeep-async==1.2.0"
      ]
    },
    "aqara_gateway": {
      "version": "0.0.14",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "xiaomi_miio_fan": {
      "version": "2022.8.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "var": {
      "version": "0.15.0",
      "requirements": []
    },
    "xiaomi_miio_raw": {
      "version": "2022.12.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.42.0"
    ],
    "version": "3.0.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "41fa3b1",
    "options": {
      "host": "***",
      "token": "***"
    },
    "errors": [],
    "device": {
      "type": "mesh",
      "model": 2007,
      "fw_ver": null,
      "available": true,
      "decode_time": 51,
      "encode_time": 52,
      "entities": {
        "switch": "off"
      },
      "gateways": [
        "54ef444128f0",
        "54ef443f1e94"
      ],
      "unique_id": "5ce50cef2ebc"
    },
    "logger": null
  }
}

**Comment by AlexxIT** [comment]
I can see you using multiple gateways. In my experience, this can be a problem. These gateways have very glitchy Mesh software when there are multiple gateways.
Are you using the latest firmware? 1.5.4?

**Comment by kingwap99** [comment]
> I can see you using multiple gateways. In my experience, this can be a problem. These gateways have very glitchy Mesh software when there are multiple gateways. Are you using the latest firmware? 1.5.4?

sorry, it would be better to inform you beforehand.
Because already updated all the gateways , please check the chart as below

![Screenshot_2023-02-01-22-57-15-727_com xiaomi smarthome](https://user-images.githubusercontent.com/33337987/216078725-4906f26d-7a13-4f4d-ae8c-7abdc8a40f2d.jpg)

**Comment by xrh0905** [comment]
> 

Looks like you have some "blind gateway" still running?
This makes it impossible to allow the intergration to pull the status of device, since it never reach the gateway.
Maybe you can try to disable gateways that didn't mark as `auxiliary gateway` or `Hubs` and try again.

看起来你还开着盲网关
这个集成只能读取连接在多模网关上的设备
如果设备连接到盲网关就无法控制了
可以先关掉盲网关试试

**Comment by kingwap99** [comment]
> > 
> 
> Looks like you have some "blind gateway" still running? This makes it impossible to allow the intergration to pull the status of device, since it never reach the gateway. Maybe you can try to disable gateways that didn't mark as `auxiliary gateway` or `Hubs` and try again.
> 
thanks for your suggestion.
but my consideration is that if it just connects to Xiaomi central gateway directly?
so I think if Xiaomi central gateway is the root cause

**Comment by oimag** [comment]
Yes, the black gateway ZSWG01CM is the root cause.
I have the same issue, all mesh devices (I have mesh switches and mesh bulbs) can only send status from HA to MiHome, but cannot receive the status change from MiHome. If I disconnect the balck gateway, then everything works well, but this is not a solution.

**Comment by AlexxIT** [comment]
Same as #975

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
