### ISSUE TITLE
Xiaomi TH Sensor 2 (LYWSD03MMC)

### ISSUE THREAD

**Issue by v222008** [AlexxIT/XiaomiGateway3#85]
Подскажите а bindkey можно просмотреть устройств LYWSD03MMC?

**Comment by AlexxIT** [comment]
Пока нет

**Comment by akunia** [comment]
@AlexxIT I would like to report that the battery level for LYWSD03MMC is always at 100%. Can you fix that in this ticket?

**Comment by AlexxIT** [comment]
Do you tried latest beta. It has new BLE logic

**Comment by akunia** [comment]
No, I don't. 
I'll wait the next stable version.
Thanks

**Comment by akunia** [comment]
@AlexxIT , Tested with the latest version v1.1.0 . Still all my 5 BT sensors shows 100% of battery

**Comment by AlexxIT** [comment]
@akunia What firmware on your gateway?

@v222008 теперь можно посмотреть bindkey

**Comment by akunia** [comment]
@AlexxIT it's FIRMWARE........: 1.4.6_0012 #20210127

**Comment by AlexxIT** [comment]
Read bindkey supported in latest version
