### ISSUE TITLE
Waiting for “Multi-Mode Gateway 2” support BLE And Mesh long time.When will support be available.

### ISSUE THREAD

**Issue by GuidoKuo** [AlexxIT/XiaomiGateway3#852]
Hoping for good news every day.

**Comment by niceboygithub** [comment]
He did hard work for several days. XD

**Comment by AlexxIT** [comment]
It is already supported in latest master version

**Comment by niceboygithub** [comment]
nice jobs. Multimode gateway 2 becomes more powerful in HA.

**Comment by AlexxIT** [comment]
All gateways becomes more powerful. And not only for HA

**Comment by wolnlow** [comment]
1.5.4_0090 not supported

**Comment by wolnlow** [comment]
1.5.4_0090 not supported

**Comment by sumsethan** [comment]
seems like some ble  and mesh devices are unavaliable
heres unavaliable devs in my home :
```
ble CGG1
ble hs1bb
ble LYWSD02MMC
ble LYWSD03MMC
ble MJYD02YL-A
ble XMWSDJ04MMC
ble ydhome.lock.m2silver
mesh MJSGCLBL01LM
```
And mesh light groups
```
mesh yeelink.light.mb1grp
```
mesh lights works very well though

**Comment by nesror** [comment]
> It is already supported in latest master version
Which Multi-Mode Gateway 2 firmware is supported？

**Comment by AlexxIT** [comment]
Xiaomi Multimode Gateway - supported all firmwares. I have tested 1.5.0 (my main gateway) and 1.5.4
Xiaomi Multimode Gateway 2 - I have tested 1.0.3_0028

**Comment by wolnlow** [comment]
[custom firmware](https://github.com/zvldz/mgl03_fw/tree/main/firmware) 1.5.4_0090 not supported
`ble MCCGQ02HL
ble RTCGQ02LM
ble MJYD02YL-A
ble LYWSD03MMC
ble SJWS01LM
mesh (10356)
ble (417)`

**Comment by ctrlands** [comment]
hello, are you work well on Multi-Mode Gateway 2, i got the error msg: "192.168.0.102 | Can't prepare gateway", there is no any devices

**Comment by ctrlands** [comment]
use the putty to access Multi-Mode Gateway 2,
![image](https://user-images.githubusercontent.com/29942027/200725291-c94e71d8-6c34-482e-b7d5-cf91b2d80fc3.png)

**Comment by xiaoxi9511** [comment]
> Xiaomi Multimode Gateway - supported all firmwares. I have tested 1.5.0 (my main gateway) and 1.5.4 Xiaomi Multimode Gateway 2 - I have tested 1.0.3_0028 Aqara Hub E1 - I have tested 4.0.1_0001 (my second main gateway)

I've been waiting for Multi-Mode Gateway 2 for a long time. Good luck with your testing and waiting for your good news.

**Comment by macher91** [comment]
@ctrlands Use root user if you want use telnet

**Comment by ctrlands** [comment]
> @ctrlands Use root user if you want use telnet

thks, i find the same question in #822   but the devices what i have are unavailable ，watting [AlexxIT](https://github.com/AlexxIT) to update

**Comment by tangxingjie1991** [comment]
Does not work under Multi-Mode Gateway 2  1.0.6_0016

**Comment by fevenor** [comment]
All BLE show unavailable with Multi-Mode Gateway 2 1.0.5_0008

**Comment by baiyz0825** [comment]
i try using the latest master version to connect multy-mode gateway2 to ha,it can connected,but the ble devies can't show in ha. my version is below , is there anyone  known to demode to the 1.0.3_0028 (tested version)
![image](https://user-images.githubusercontent.com/81071870/210194134-ddd338bb-a59b-4e61-9478-b270e0ea83c3.png)
