### ISSUE TITLE
ZNDMWG02LM and ZNDMWG03LM

### ISSUE THREAD

**Issue by maury77** [AlexxIT/XiaomiGateway3#856]
I have a ZNDMWG03LM with all objects inserted on the Chinese servers.

If I buy ZNDMWG02LM I can insert it within the same servers so that it sees the same network

Does ZNDMWG02LM only connect to global servers?

**Comment by AlexxIT** [comment]
Have answer in docs
https://github.com/AlexxIT/XiaomiGateway3#regional-restrictions
