### ISSUE TITLE
Support for firmware 1.5.4_0090? Or downgrade to earlier firmware?

### ISSUE THREAD

**Issue by chjohans** [AlexxIT/XiaomiGateway3#858]
I just bought a Xiaomi Gateway 3 and I was gonna use it with this custom integration, but I didn't read properly first because I added it in the Xiaomi Home app and when that asked me to upgrade the firmware I did that. So I'm now on version 1.5.4_0900, and now I see that this version is currently not supported by this integration.

So what are my options now?

Is it "in the works" to add support for this firmware? Or is it possible to downgrade my firmware version?

Or should I just use the Homekit support in HA instead?

**Comment by TrustedFloppa** [comment]
#807 You can downgrade firmware

**Comment by chjohans** [comment]
Thanks, much appreciated!! I have it working quite well with all my sensors by using the HA Core HomeKit integration. But would like to try this as well.

Do you happen to know if those two integrations can co-exist? Or if I have to delete/disable the currently working HomeKit integration in order to use this?

**Comment by TrustedFloppa** [comment]
Like the normal homekit on home Assistant?

**Comment by chjohans** [comment]
Yes, the XIaomi Smart Hub was automatically detected by the HA Core HomeKit integration, all I had to do was to enter the HomeKIt code that is on the sticker on the Smart Hub. Works quite well too, it instantly detects any sensor changes from the Smart Hub. But I'll still try this integration just to try it.

**Comment by AlexxIT** [comment]
Original issue #666 
Also this firmware supported in latest master-version

**Comment by chjohans** [comment]
Thank you, that's great news!
