### ISSUE TITLE
Light Group Support

### ISSUE THREAD

**Issue by lonebaggie** [AlexxIT/XiaomiGateway3#86]
Will light groups be supported  or is this an MI home app feature and not replicated in the hub ? 

Grouping lights in HA give "popcorn" effect changing each light in the group one at at time , rather than together

**Comment by Zuz666** [comment]
@lonebaggie there are many of light groups types. As far I know true BLE-mesh groups work on hub (XG3). Cloud light group via Yeeligth / Mijia / Xiaomi ecosystem servers. BLE-mesh light groups will be supported in the feature when @AlexxIT add support to it! :)

**Comment by AlexxIT** [comment]
Mesh groups supported in latest version
