### ISSUE TITLE
Xiaomi ZNCZ01ZM plug power consumption data update issue.

### ISSUE THREAD

**Issue by kyriosw** [AlexxIT/XiaomiGateway3#866]
Hi, 
I have a question about the power consumption data of the Xiaomi ZNCZ01ZM plug.
Every time I check the power consumption data from Mijia APP on my cellphone, the data in HA will start updating.
But it will only update a couple of times, then no new data will come in.
Gateway: ZNDMWG03LM
Firmware: 1.5.0_0102

Is there any configuration I need to change?

Thx

![putty](https://user-images.githubusercontent.com/101687233/202719488-e2af04aa-bd63-45e8-b0b2-f1c90bd07a2c.PNG)

**Comment by wangzhu83** [comment]
Same problem

**Comment by AlexxIT** [comment]
You need to collect integration debug logs in the moment when you MiHome app. Maybe it sends special command to plug.

**Comment by AlexxIT** [comment]
#188
