### ISSUE TITLE
BLE stopped working

### ISSUE THREAD

**Issue by iy2koi** [AlexxIT/XiaomiGateway3#872]
Hi,
yesterday all my devices went offline in the Xiaomi app (and HA) for ~10 minutes. After it came back everything were fine for 2 hours but since then all my ble device are offline. The fw on the hub is the recommended stock v1.5.0_0102. It seems only affect devices on the EU server.

[https://community.home-assistant.io/t/xiaomi-gateway-3-integration-stop-working-not-show-temp-hum-sensors-anymore/493959](url)

```Logger: custom_components.xiaomi_gateway3.core.gateway
Source: custom_components/xiaomi_gateway3/core/gateway/base.py:109
Integration: Xiaomi Gateway 3 ([documentation](https://github.com/AlexxIT/XiaomiGateway3), [issues](https://github.com/AlexxIT/XiaomiGateway3/issues))
First occurred: 22:20:05 (1 occurrences)
Last logged: 22:20:05

192.168.8.163 | Can't patch Bluetooth utility```

**Comment by akunia** [comment]
Hi,
I experience the same since yestarday morning, all BLE devices are offline. I'm in ZHA mode with custom  1.5.0_0102 #20210816.

**Comment by Eduadel** [comment]
Same is happening to me. BLE Temp Sensors lost the connection.

**Comment by akunia** [comment]
@AlexxIT how we can debug?

**Comment by akdri** [comment]
Same problem Firmware: 1.5.0_0102
![Screenshot_2022-11-27-02-09-00-456_io homeassistant companion android](https://user-images.githubusercontent.com/5574939/204114800-dd70071a-07d4-4cd3-96b5-5dd0c19150b6.jpg)

**Comment by mcasteels** [comment]
unfortunately same issue at my install

Home Assistant 2022.10.3
Frontend 20221010.0 - latest
Xiaomi GW3, firmware 1.5.0_0102.
Zigbee OK.

I thought it was first an issue at my end so ended up removing all and setting it up again.  Strange thing is that it does detect the BLE devices to add them.  But can't read the data AND 1 device had 3 sensors before (temp, humidity and Battery) now it only has 2 sensors, it lost the battery

**Comment by iy2koi** [comment]
I managed to solve it.

It seems the integration has nothing to do with the issue, it is a xiaomi app/server problem.

The app appeared to be updating states but it was using the phone's bluetooth connection, the gateway wasn't seeing the devices even though it was visible in the bluetooth child devices.

Try these steps:

1. Remove the device from Xiaomi Home app
2. Remove the battery from the device (may not necessary)
3. Add it to the app as usually (top-right + sign - Add a device)
4. In HA select the HUB from the integration page and choose the "Gateway reboot" command (may not necessary)
5. Restart HA (may not necessary)
6. Wait 5-10 minutest (or a bit more) until the device broadcasts a BLE message. After that, the states will be updated in HA.

You can check if the device connected to the gateway (not through the phone) by turning off the bluetooth on the phone and choose the device in the app. If the history or the current values are shown, it's connected throught the gateway. Before these steps there was no data.

**Comment by akunia** [comment]
Hi,
Indeed, removing, adding back th esensor in miHome is enough. No restart o battery removal is needed.
Thanks

**Comment by AlexxIT** [comment]
The cloud was buggy last week. The encryption keys of some BLE devices reset.

**Comment by zscorpio** [comment]
> Hi, Indeed, removing, adding back the sensor in miHome is enough. No restart o battery removal is needed. Thanks

I do this but nothing help...BLE still stop working

**Comment by mcasteels** [comment]
It did work for me, but you also need to give HA some time to communicate again.

What I did.  In the Xiaomi Home App
I went to the thermometer in the app and removed it.  Went to the physical location and added it again.  Checked afterwards the connection to see if it was working.  In some cases I had to bring it closer to the GW!

wait for around 30min. And then saw it again as working in HA.
