### ISSUE TITLE
Fail to start zigbee2mqtt

### ISSUE THREAD

**Issue by ju0k** [AlexxIT/XiaomiGateway3#875]
Hello, I am neew to HA and trying to run zigbee2mqtt on xiaomi gateway 3 but the log shows that it stops on "Starting zigbee-herdsman (0.14.76)"

`[15:32:18] INFO: Preparing to start...
[15:32:18] INFO: Socat not enabled
[15:32:18] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-11-28 15:32:20: Logging to console and directory: '/config/zigbee2mqtt/log/2022-11-28.15-32-20' filename: log.txt
Zigbee2MQTT:info  2022-11-28 15:32:20: Starting Zigbee2MQTT version 1.28.2-dev (commit #9289a26)
Zigbee2MQTT:info  2022-11-28 15:32:20: Starting zigbee-herdsman (0.14.76)`

**Comment by AlexxIT** [comment]
This project does not provide support for z2m
