### ISSUE TITLE
sensors "unavailable", also after remove & reconfigure of the addon?

### ISSUE THREAD

**Issue by BartProvoost** [AlexxIT/XiaomiGateway3#879]
Since last week my BLE sensors (LYWSD03MMC) are all unavailable, also some parameters of the gateway, but the commands (like reboot) seem to work?

I moved my internal network to a different subnet, but did that before without any problems...

![image](https://user-images.githubusercontent.com/33250175/204765880-c3764517-ad40-4c63-9cff-2d798e8aebe1.png)

The "Gateway Data" parameter was always unknown or unavailable, but since last night it's "ok", not sure what changed or what it means...

![image](https://user-images.githubusercontent.com/33250175/204767440-2ded4c97-0090-46ce-89b6-4313a20f3d72.png)

**Comment by JaCoLJcL** [comment]
Same here, lets check the dates

![image](https://user-images.githubusercontent.com/70702183/204922468-7c681a66-d9d5-49d1-b5b3-f2741ff3006e.png)

Only LYWSD03MMC don't work, My LYWSD02MMC works fine ...

I see that LYWSD03MMC don't work on Xiaomi Home to ! Maybe Xiaomi do some update?

**Comment by AlexxIT** [comment]
@BartProvoost Is your gateway on supported firmware?

**Comment by AlexxIT** [comment]
There was a bug in the Xiaomi cloud recently. You may need to repair the sensor to the MiHome

**Comment by fx-zone** [comment]
Same problem. All sensors in the HA are "unavailable" but the data is available in the XiaomiHome app.
![mi](https://user-images.githubusercontent.com/97675861/205013401-2fb37bb9-9b0f-4c59-aadf-a0aeb74cf463.JPG)

How to repair the sensors in the app?

**Comment by JaCoLJcL** [comment]
> Same problem. All sensors in the HA are "unavailable" but the data is available in the XiaomiHome app. ![mi](https://user-images.githubusercontent.com/97675861/205013401-2fb37bb9-9b0f-4c59-aadf-a0aeb74cf463.JPG)
> 
> How to repair the sensors in the app?

You are sure that this is legit data?

**Comment by fx-zone** [comment]
@JaCoLJcL   Why not? Nothing personal in it... 
Or did I misunderstand you?

**Comment by JaCoLJcL** [comment]
I have data to in app but is not actual data but last remeber data... If You want to connect to BT device it will not show data but call You to turn on BT in phone. Check it!

**Comment by JaCoLJcL** [comment]
> There was a bug in the Xiaomi cloud recently. You may need to repair the sensor to the MiHome

After repair nothing happend :( I can connect to BT device via Phone but MEHS BT in gate3 don't work :/

**Comment by fx-zone** [comment]
@JaCoLJcL  You're right. It's the last data from a week ago.

**Comment by larbre86** [comment]
I have the same problem too.
Since a few days, there are no data in HA.
But it's not only about the temperature sensors.
My doorsensors are connectet to the hub, an in xiaomi app i can track the stats.
But if i arm the hub an open the door, ther ist no alert in system. I think it's a problem of xiaomi right now...

**Comment by anapogo** [comment]
I have the same problem.
All 5 temperature/humidity sensors in HA are “unavailable”, but they all work fine in the MiHome app.
Gateway Firmware: 1.5.0_0026
If you enter the gateway in the MiHome app, all sensors are visible ...

How to fix sensors in the app?

**Comment by BartProvoost** [comment]
> @BartProvoost Is your gateway on supported firmware?

yes: 1.5.0_0102

**Comment by BartProvoost** [comment]
When I open them in the Mi Home app it says "connecting to the monitor..." which takes a very long time, but a few days ago I could connect to one of the sensors and it asked to do a firmware update.

**Comment by JaCoLJcL** [comment]
> When I open them in the Mi Home app it says "connecting to the monitor..." which takes a very long time, but a few days ago I could connect to one of the sensors and it asked to do a firmware update.

Wrong. If You can do soft update You connect direct to the device (with BT on Your phone).

**Comment by JaCoLJcL** [comment]
When I go back to my ESPHome project... then: data in APP it seems to get legit. Check it guys. Data in HA is still offline :/

**Comment by BartProvoost** [comment]
I removed 3 of the sensors from the app and added them again. 2 of them are working now (in the app and HA), on the 3rd one I did a firmware update but a few hours later it seems like it's not connected anymore in the app.

**Comment by JaCoLJcL** [comment]
All my sesnors are back

**Comment by BartProvoost** [comment]
Same here, except the one I updated yesterday...

**Comment by larbre86** [comment]
Hey guys, i updated my devices after i checked it doesn't work.
But it changed nothing.
No sensors are working in HA.
But i don't think it's an issue with the plugin, because i can switch the hub-alert in HA.
The only thing, the sensors doesn't work.

When i'm arming the house, the hub doesn't give an alert if a window opens.
This should be a problem of xiaomi :-/

**Comment by BartProvoost** [comment]
Since yesterday everything works normal again, even the updated sensors. I don't use the "arming" features though... But I did restart my HA setup a few times because I was configuring other things, so maybe you should just restart/reload?

**Comment by larbre86** [comment]
yes it's working normal again.

**Comment by fx-zone** [comment]
Yes, everything is working normally again for me. I hope it stays like this.

**Comment by Tatoo974** [comment]
Hi, same problem for me now. All sensors down, gateway is offline in HA but not in Mi home…
Did several reboot unfortunately.
Could someone help me ?

**Comment by anapogo** [comment]
Wait a bit, my 5 sensors are working fine, although I had the same problems before...

**Comment by jem24h** [comment]
For me it' still not working, I have plenty of bluetooth bulb which remain unavailable

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.15.80",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "xiaomi_gateway3": {
      "version": "2.1.2",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
    "miio_yeelink": {
      "version": "0.1.12",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6"
      ]
    },
    "ytube_music_player": {
      "version": "20220205.01",
      "requirements": [
        "ytmusicapi==0.24.0",
        "pytube==10.5.1",
        "integrationhelper==0.2.2"
      ]
    },
    "landroid_cloud": {
      "version": "2.3.4",
      "requirements": [
        "pyworxcloud==2.1.23"
      ]
    },
    "eufy_security": {
      "version": "2.9.0",
      "requirements": [
        "websocket-client==1.1.0"
      ]
    },
    "webrtc": {
      "version": "v2.3.1",
      "requirements": []
    },
    "sun2": {
      "version": "2.1.3",
      "requirements": []
    },
    "xiaomi_miot_raw": {
      "version": "v1.3.1",
      "requirements": [
        "construct",
        "python-miio>=0.5.3"
      ]
    },
    "alarmo": {
      "version": "v1.9.7",
      "requirements": []
    },
    "ptz_camera": {
      "version": "1.0.0",
      "requirements": []
    },
    "deepstack_face": {
      "version": "0.9.0",
      "requirements": [
        "pillow",
        "deepstack-python==0.8"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "4894b05",
    "options": {
      "host": "***",
      "token": "***",
      "telnet_cmd": "{\"method\":\"enable_telnet_service\",\"params\":\"\"}",
      "ble": true,
      "stats": false,
      "debug": [],
      "buzzer": false,
      "memory": false,
      "zha": false
    },
    "errors": [],
    "error": "KeyError: '0xbc33acfffe7e97e3'"
  }
}`

**Comment by AlexxIT** [comment]
@jem24h `0xbc33acfffe7e97e3` this is ID of zigbee device.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
