### ISSUE TITLE
Support BLE moving event

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#88]
```
Unsupported BLE {'dev': {'did': 'blt.3.14m13ngxxxxxx', 'mac': '50:EC:50:xx', 'pdid': 2038}, 'evt': [{'eid': 15, 'edata': '640000'}], 'frmCnt': 217, 'gwts': 1603998474}
```
@to4ko

**Comment by devilcell** [comment]
could you add BLE device in HA with MJYD02YL-A

**Comment by devilcell** [comment]
![image](https://user-images.githubusercontent.com/14147582/97654254-7d576800-1a9d-11eb-8867-d533198dd687.png)
this one ,  this product include motion sensor and light sensor

**Comment by Zuz666** [comment]
@AlexxIT moving event? What does this mean?

**Comment by AlexxIT** [comment]
@devilcell partly device is already supported

@Zuz666 MJYD02YL-A support "moving event"

**Comment by dscao** [comment]
这个MJYD02YL-A的移动状态等了好久了，否则只能使用mqttl方案。参考这个：
https://bbs.hassbian.com/thread-10725-1-1.html

`sensor:
- platform: mqtt
    name: mi_yedeng_move_NAME
    state_topic: 'mqttl/设备ID/15'
    value_template: >-
       {% if value|int(0,16) == 1 %}
         有人移动,环境光-暗
       {% elif value|int(0,16) == 100 %}
         有人移动,环境光-亮
       {% else %}
         未知
       {% endif %}
  - platform: mqtt
    name: mi_yedeng_battery_NAME
    icon: 'mdi:battery-80'
    state_topic: 'mqttl/设备ID/4106'
    unit_of_measurement: '%'
    value_template: "{{value|int(0,16)}}"
  - platform: mqtt
    name: mi_yedeng_timedelay_NAME
    state_topic: 'mqttl/设备ID/4119'
    value_template: "{{value|int(0,16)}}"

homeassistant:
  customize:
    sensor.mi_yedeng_move_NAME:
      friendly_name: 感应夜灯状态
    sensor.mi_yedeng_battery_NAME:
      friendly_name: 感应夜灯电量
    sensor.mi_yedeng_timedelay_NAME:
      friendly_name: 无人移动时间  #上报0秒，2分钟，5分钟，10分钟，20分钟，30分钟，用秒表示`

**Comment by dscao** [comment]
这个蓝牙的移动状态包含两部分：
1、移动状态：有人移动,环境光-暗 / 有人移动,环境光-亮
2、移动状态输出后1秒左右另一个主题输出“无人移动时间”：0
     2分钟后输出：120
     5分钟后输出：300
     10分钟后输出：600
     20分钟后输出：1200
     30分钟后输出：1800
     中途有人移动，重新输出 状态 和 0 开始，如一直无人则直到输出1800后不再输出消息。


小米loT文档中应该是：

名称 | ID | 时间间隔（秒） | 变化量
无人移动 | 0x1017 | 1 | 1

名称 | 长度 | 描述
时间长度 | 4 | 无人移动状态的持续时间，单位为秒

**Comment by dscao** [comment]
MJYD02YL-A idle_time sensor is not show,  # The duration of the unmanned state, in seconds

**Comment by AlexxIT** [comment]
@dscao I don't plan to add it. It's very usable?

**Comment by dscao** [comment]
> @dscao I don't plan to add it. It's very usable?

之前用自动化中使用这个无人移动时间感觉只用single模式时还是有些作用的，在写有人自动开灯无人关灯的情境中比较方便。
无人移动时间会不断变化，hass中的自动化状态变化到600或1200执行关灯动作，如果期间环境不允许可以下一阶段再试。有这个无人移动时间则自动化编写就相对简单。
- id: '1598978768635'
  alias: 卫生间自动关灯
  description: ''
  trigger:
  - entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
    platform: state
    to: '120'
  - entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
    platform: state
    to: '300'
  - entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
    platform: state
    to: '600'
  - entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
    platform: state
    to: '1200'
  - entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
    platform: state
    to: '1800'
  condition:
  - condition: state
    entity_id: switch.hassmartweishengjiandeng
    state: 'on'
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
      state: '0'
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.mi_mengci_kaiguan_e4aaec34d5e2
      state: 门窗关闭
  action:
  - delay: '5'
  - data: {}
    entity_id: switch.hassmartweishengjiandeng
    service: switch.turn_off
  mode: single



另外小米门锁上锁动作不能判断是门内还是门外。为了实现出门上提把手600秒后进入离家模式关闭所有电源。门内增加一个蓝牙夜灯，上锁600秒后蓝牙的无人移动时间等于600时，执行离家脚本。600秒内有人移动无人移动时间又变成0，说明只是上提把手而人没有出去或2分钟内回来了，则不执行离家脚本。还可以防止外面有别人上提把手导致误触发关闭所有电源电器。
`- id: '1600427380971'
  alias: home进入离家模式
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.lock_event
    to: 上提把手锁门
    for: '120'
  condition:
  - condition: state
    entity_id: sensor.mi_yedeng_timedelay_50ec50e2191d
    state: '120'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.athome
  - service: alarm_control_panel.alarm_arm_away
    data: {}
    entity_id: alarm_control_panel.home_alarm
  mode: single`

如果能加上就更好了，或者对于这种场景我需要学习一下是否有其它更好的方法。

**Comment by to4ko** [comment]
> > @dscao I don't plan to add it. It's very usable?
> 
> 之前用自动化中使用这个无人移动时间感觉只用single模式时还是有些作用的，在写有人自动开灯无人关灯的情境中比较方便。
> 无人移动时间会不断变化，hass中的自动化状态变化到600或1200执行关灯动作，如果期间环境不允许可以下一阶段再试。有这个无人移动时间则自动化编写就相对简单。
> 
> * id: '1598978768635'
>   alias: 卫生间自动关灯
>   description: ''
>   trigger:
>   
>   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>     platform: state
>     to: '120'
>   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>     platform: state
>     to: '300'
>   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>     platform: state
>     to: '600'
>   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>     platform: state
>     to: '1200'
>   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>     platform: state
>     to: '1800'
>     condition:
>   * condition: state
>     entity_id: switch.hassmartweishengjiandeng
>     state: 'on'
>   * condition: not
>     conditions:
>     
>     * condition: state
>       entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
>       state: '0'
>   * condition: not
>     conditions:
>     
>     * condition: state
>       entity_id: sensor.mi_mengci_kaiguan_e4aaec34d5e2
>       state: 门窗关闭
>       action:
>   * delay: '5'
>   * data: {}
>     entity_id: switch.hassmartweishengjiandeng
>     service: switch.turn_off
>     mode: single
> 
> 另外小米门锁上锁动作不能判断是门内还是门外。为了实现出门上提把手600秒后进入离家模式关闭所有电源。门内增加一个蓝牙夜灯，上锁600秒后蓝牙的无人移动时间等于600时，执行离家脚本。600秒内有人移动无人移动时间又变成0，说明只是上提把手而人没有出去或2分钟内回来了，则不执行离家脚本。还可以防止外面有别人上提把手导致误触发关闭所有电源电器。
> `- id: '1600427380971'
> alias: home进入离家模式
> description: ''
> trigger:
> 
> * platform: state
>   entity_id: sensor.lock_event
>   to: 上提把手锁门
>   for: '120'
>   condition:
> * condition: state
>   entity_id: sensor.mi_yedeng_timedelay_50ec50e2191d
>   state: '120'
>   action:
> * service: input_boolean.turn_off
>   data: {}
>   entity_id: input_boolean.athome
> * service: alarm_control_panel.alarm_arm_away
>   data: {}
>   entity_id: alarm_control_panel.home_alarm
>   mode: single`
> 
> 如果能加上就更好了，或者对于这种场景我需要学习一下是否有其它更好的方法。

Use English please

**Comment by dscao** [comment]
> > > @dscao I don't plan to add it. It's very usable?
> > 
> > 
> > 之前用自动化中使用这个无人移动时间感觉只用single模式时还是有些作用的，在写有人自动开灯无人关灯的情境中比较方便。
> > 无人移动时间会不断变化，hass中的自动化状态变化到600或1200执行关灯动作，如果期间环境不允许可以下一阶段再试。有这个无人移动时间则自动化编写就相对简单。
> > 
> > * id: '1598978768635'
> >   alias: 卫生间自动关灯
> >   description: ''
> >   trigger:
> >   
> >   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >     platform: state
> >     to: '120'
> >   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >     platform: state
> >     to: '300'
> >   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >     platform: state
> >     to: '600'
> >   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >     platform: state
> >     to: '1200'
> >   * entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >     platform: state
> >     to: '1800'
> >     condition:
> >   * condition: state
> >     entity_id: switch.hassmartweishengjiandeng
> >     state: 'on'
> >   * condition: not
> >     conditions:
> >     
> >     * condition: state
> >       entity_id: sensor.mi_yedeng_timedelay_50ec50e218f3
> >       state: '0'
> >   * condition: not
> >     conditions:
> >     
> >     * condition: state
> >       entity_id: sensor.mi_mengci_kaiguan_e4aaec34d5e2
> >       state: 门窗关闭
> >       action:
> >   * delay: '5'
> >   * data: {}
> >     entity_id: switch.hassmartweishengjiandeng
> >     service: switch.turn_off
> >     mode: single
> > 
> > 另外小米门锁上锁动作不能判断是门内还是门外。为了实现出门上提把手600秒后进入离家模式关闭所有电源。门内增加一个蓝牙夜灯，上锁600秒后蓝牙的无人移动时间等于600时，执行离家脚本。600秒内有人移动无人移动时间又变成0，说明只是上提把手而人没有出去或2分钟内回来了，则不执行离家脚本。还可以防止外面有别人上提把手导致误触发关闭所有电源电器。
> > `- id: '1600427380971'
> > alias: home进入离家模式
> > description: ''
> > trigger:
> > 
> > * platform: state
> >   entity_id: sensor.lock_event
> >   to: 上提把手锁门
> >   for: '120'
> >   condition:
> > * condition: state
> >   entity_id: sensor.mi_yedeng_timedelay_50ec50e2191d
> >   state: '120'
> >   action:
> > * service: input_boolean.turn_off
> >   data: {}
> >   entity_id: input_boolean.athome
> > * service: alarm_control_panel.alarm_arm_away
> >   data: {}
> >   entity_id: alarm_control_panel.home_alarm
> >   mode: single`
> > 
> > 如果能加上就更好了，或者对于这种场景我需要学习一下是否有其它更好的方法。
> 
> Use English please

Simply put, sometimes the idle_time sensor is usable for automation，of course there may be other methods to replace.

**Comment by AlexxIT** [comment]
Device supported in latest version
