### ISSUE TITLE
integration is not connected

### ISSUE THREAD

**Issue by Vladimir-huligan** [AlexxIT/XiaomiGateway3#880]
hello. The integration of Xiaomi Gateway 3 into HA does not connect. In the integration, he sees "Gateway (192.168.1.149)" 
but writes in the logs:
```
integration_manifest": {
"domain": "xiaomi_gateway3",
"name": "Xiaomi Gateway 3",
"config_flow": true,
"documentation": "https://github.com/AlexxIT/XiaomiGateway3 ",
"issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues ",
"codeowners": [
"@AlexxIT"
],
"dependencies": [
"http"
],
"requirements": [
"zigpy>=0.33.0"
],
"version": "2.1.2",
"iot_class": "local_push",
"is_built_in": false
},
"data": {
"version": "4894b05",
"options": {},
 "errors": [
 {
 "name": "custom_components.xiaomi_gateway3.core.mini_miio",
 "message": [
 "192.168.0.108 | Device offline"
 ],
 "level": "WARNING",
 "source": [
 "custom_components/xiaomi_gateway3/core/mini_miio.py",
 324
 ],
 "timestamp": 1669812743.0195236,
 ```

**Comment by fx-zone** [comment]
I also have this problem since about 1 week. I thought it was an update and made a backup, but that didn't change anything either.

**Comment by AlexxIT** [comment]
Show me the full diagnostics of the device

**Comment by Vladimir-huligan** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Barbados",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "xiaomi_gateway3": {
      "version": "2.1.2",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "4894b05",
    "options": {},
    "errors": [],
    "devices": {}
  }
}

Заранее спасибо за помощь!

**Comment by Vladimir-huligan** [comment]
Maybe I didn't write it correctly. This is the initial integration setup, it didn't work for me. I haven't been able to set it up for a long time.

**Comment by larbre86** [comment]
I reinstalled my plugin, and now anything doesn't work. Even arming oder disarming...
My protocol is the same like above

**Comment by AlexxIT** [comment]
Maybe you do not have a direct LAN connection between the HA and the gateway.

**Comment by Vladimir-huligan** [comment]
![Снимок](https://user-images.githubusercontent.com/73360995/209313053-30052cd4-68e3-475b-bbc0-c03d71830fca.JPG)
the home assistant sees the gateway, but does not connect

**Comment by AlexxIT** [comment]
I see that you have two different local networks. This could be a problem.

**Comment by Vladimir-huligan** [comment]
the fact is that the vacuum cleaner is geographically in another place, because the network is different

**Comment by AlexxIT** [comment]
I can see in the error: `192.168.0.108 | Device offline`
But the IP address on your screenshot is from another location.
You need to manually specify the correct gateway IP address.
And also find out the correct gateway token in another way.

**Comment by Vladimir-huligan** [comment]
не понимаю при чем тут пылесос. пылесос находится в квартире, а шлюзы на даче. теперь их два. токены они оба показывают но так и не подключаются

**Comment by Vladimir-huligan** [comment]
![1](https://user-images.githubusercontent.com/73360995/230836891-bbe9d0ba-5a6f-4b09-a75b-9ef2f5c5c56f.png)
