### ISSUE TITLE
Add support for MJTD01SYL Mi Desk Lamp 1S

### ISSUE THREAD

**Issue by aliilhami** [AlexxIT/XiaomiGateway3#881]
Right now there is only one way to add Xiaomi Mi Desk Lamp 1S (MJTD01SYL) model to HA, it is through Apple Homekit integration. It would be good if we can add it through this integration like all other devices.

**Comment by AlexxIT** [comment]
FAQ number 1
https://github.com/AlexxIT/XiaomiGateway3#faq
