### ISSUE TITLE
Xiaomi Gateway 3 stopped connecting

### ISSUE THREAD

**Issue by tolis18gr** [AlexxIT/XiaomiGateway3#882]
Xiaomi Gateway stopped connecting to home assistant. I uninstalled the integration fully from HACS but i was never able to connect it back again. I get "Unknown error occurred"

- Check Integration errors in Hass logs (Configuration > Logs), maybe answer there

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/xiaomi_gateway3/core/utils.py:169
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: 22:05:37 (2 occurrences)
Last logged: 22:22:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_gateway3/config_flow.py", line 102, in async_step_token
    error = await utils.check_gateway(**user_input)
  File "/config/custom_components/xiaomi_gateway3/core/utils.py", line 169, in check_gateway
    raw = json.loads(telnet_cmd)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

- Check Integration debug (Configuration > Integrations > Xiaomi Gateway 3 > Configure > Debug) for something useful

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Athens",
    "os_name": "Linux",
    "os_version": "5.15.74",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.2",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "xiaomi_gateway3": {
      "version": "2.1.2",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
  "integration_manifest": {
    "domain": "xiaomi_gateway3",
    "name": "Xiaomi Gateway 3",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
    "issue_tracker": "https://github.com/AlexxIT/XiaomiGateway3/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http"
    ],
    "requirements": [
      "zigpy>=0.33.0"
    ],
    "version": "2.1.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "4894b05",
    "options": {},
    "errors": [
      {
        "name": "aiohttp.server",
        "message": [
          "Error handling request"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/xiaomi_gateway3/core/utils.py",
          169
        ],
        "timestamp": 1669926163.9223135,
        "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py\", line 435, in _handle_request\n    resp = await request_handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py\", line 504, in _handle\n    resp = await handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py\", line 117, in impl\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/security_filter.py\", line 60, in security_filter_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/forwarded.py\", line 100, in forwarded_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/request_context.py\", line 28, in request_context_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/ban.py\", line 82, in ban_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/auth.py\", line 236, in auth_middleware\n    return await handler(request)\n  File \"/usr/src/homeassistant/homeassistant/components/http/view.py\", line 136, in handle\n    result = await result\n  File \"/usr/src/homeassistant/homeassistant/components/config/config_entries.py\", line 180, in post\n    return await super().post(request, flow_id)\n  File \"/usr/src/homeassistant/homeassistant/components/http/data_validator.py\", line 73, in wrapper\n    result = await method(view, request, data, *args, **kwargs)\n  File \"/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py\", line 110, in post\n    result = await self._flow_mgr.async_configure(flow_id, data)\n  File \"/usr/src/homeassistant/homeassistant/data_entry_flow.py\", line 280, in async_configure\n    result = await self._async_handle_step(\n  File \"/usr/src/homeassistant/homeassistant/data_entry_flow.py\", line 367, in _async_handle_step\n    result: FlowResult = await getattr(flow, method)(user_input)\n  File \"/config/custom_components/xiaomi_gateway3/config_flow.py\", line 102, in async_step_token\n    error = await utils.check_gateway(**user_input)\n  File \"/config/custom_components/xiaomi_gateway3/core/utils.py\", line 169, in check_gateway\n    raw = json.loads(telnet_cmd)\n  File \"/usr/local/lib/python3.10/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
        "count": 2,
        "first_occurred": 1669925137.9563982
      }
    ],
    "devices": {}
  }
}

- Read the readme carefully, maybe the answer is there
Followed the directions as described. It was working fine for several months but stopped at the 24th of November. Gateway works fine from Xiaomi Home

- Check if you using supported gateway firmware
FW version 1.5.0_0026

**Comment by tolis18gr** [comment]
Can anyone help please; I cannot understand why it stopped working suddently.Any suggestion would be much appreciated.

**Comment by larbre86** [comment]
Hey tolis, you are not the only one..
Check the other threads...

**Comment by tolis18gr** [comment]
Hi @larbre86 ,

Thanks for the reply! 
Well I have read most of them but it seems that the solution isn’t found yet.

**Comment by tolis18gr** [comment]
After updating HAS to the lates version by now, everything started working again.
