### ISSUE TITLE
Button WXKG01LM 

### ISSUE THREAD

**Issue by viiy** [AlexxIT/XiaomiGateway3#9]
This button has 3 states: single, double, hold->release.
After each state, the button remains in that state until another appears.
In order to track the repeated occurrence of the same state (for example, "single" after "single"), I created an automation that resets the state to null after each event, and it works.
But every 70 minutes, a "single" event automatically comes, for no reason.

**Comment by mbratukha** [comment]
Could you please share your automation that resetting the state?

**Comment by viiy** [comment]
> @viiy, Could you please share your automation that resetting the state?

1) add `python_script:` to configuration.yaml

2) create file /config/python_scripts/set_state.py
`inputEntity = data.get('entity_id')
if inputEntity is None:
    logger.warning("===== entity_id is required if you want to set something.")
else:    
    inputStateObject = hass.states.get(inputEntity)
    if inputStateObject is None and not data.get('allow_create'):
        logger.warning("===== unknown entity_id: %s", inputEntity)
    else:
        if not inputStateObject is None:
            inputState = inputStateObject.state
            inputAttributesObject = inputStateObject.attributes.copy()
        else:
            inputAttributesObject = {}
    
        for item in data:
            newAttribute = data.get(item)
            logger.debug("===== item = {0}; value = {1}".format(item,newAttribute))
            if item == 'entity_id':
                continue            # already handled
            elif item == 'allow_create':
                continue            # already handled
            elif item == 'state':
                inputState = newAttribute
            else:
                inputAttributesObject[item] = newAttribute
            
        hass.states.set(inputEntity, inputState, inputAttributesObject)`

3) add automation
`- id: '1599051632631'
  alias: Btn reset
  description: ''
  trigger:
  - entity_id: sensor.0x158d0003637891_action
    platform: state
    to:
    - single
    - double
    - release
  condition: []
  action:
  - delay: '1'
  - data:
      entity_id: sensor.0x158d0003637891_action
      state: ''
    service: python_script.set_state
  mode: single`

**Comment by viiy** [comment]
it turns out that not the "single" is repeated, the last action is repeated ... so the button is still useless ;(

**Comment by viiy** [comment]
@AlexxIT on last version (v0.2.0) buttons reset to "unknown" after press, and i saw each state on config/devices/device/deviceId page, but in log i saw only "unknown" state, also automation now not work.

**Comment by AlexxIT** [comment]
Oh, will check it

**Comment by mbratukha** [comment]
The automation is now working for me (v.0.2.0).

**Comment by AlexxIT** [comment]
I checked automation with buttons, everything works
