### ISSUE TITLE
The device doesn't appear in the Home Assitant

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/XiaomiGateway3#90]
Hello Team 

Just for your information and future integration

I just have received the new BLE door/windows and light sensor and I can't see this device in the list of the devices over the HA Home Assistant integration, but the sensor is available on the gateway v3 over the Mi Home APP.

If you need some information or test over this device please advice 

Thank you

**Comment by AlexxIT** [comment]
Try latest component version v0.8 and also reboot gateway.
