### ISSUE TITLE
HA 2023.1 update: Unexpected exception importing platform custom_components.xiaomi_gateway3.climate

### ISSUE THREAD

**Issue by osnwt** [AlexxIT/XiaomiGateway3#904]
After update to Home Assistant core 2023.1 the following error is shown:

```
2023-01-05 00:43:34.387 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
2023-01-05 00:43:34.389 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).

```

**Comment by randybb** [comment]
duplicate of #899

**Comment by lysiong** [comment]
same as mines, me on stable version of HA 2023.1 update.

**Comment by goxofy** [comment]
same problem

**Comment by philtempleton** [comment]
I'm also experiencing this issue since installing the HA 2023.1.0 update.
- Supervisor: 2022.12.1
- OS 9.4
- Frontend 20230104.1 - latest

**Comment by kismomesz** [comment]
> I'm also experiencing this issue since installing the HA 2023.1.0 update.
> 
> * Supervisor: 2022.12.1
> * OS 9.4
> * Frontend 20230104.1 - latest

Same problem

**Comment by Lobo2022** [comment]
Same problem

Home Assistant 2023.1.2
Interface: 20230104.0 - latest

**Comment by mashiahd** [comment]
Same... any fix >?

**Comment by DJTerentjev** [comment]
> Same... any fix >?

What is version of xiaomi_gateway3 integration?

**Comment by kismomesz** [comment]
Already fixed, available in beta version.
