### ISSUE TITLE
Possible to support Xiaomi BLE lock XMZNMSO5LM?

### ISSUE THREAD

**Issue by sephrioth** [AlexxIT/XiaomiGateway3#905]
Here is the lock, but I can't find it in gateway3 devices.
https://home.miot-spec.com/s/lumi.lock.wbmcn1

**Comment by AlexxIT** [comment]
Can you see this lock in the Gateway child devices in MiHome?

**Comment by sephrioth** [comment]
Yes, I can see it.
![85DAE7EF-AA55-4643-9B8E-0ED22C2D8148](https://user-images.githubusercontent.com/4231328/211276564-b4ec2943-62fe-4601-bda1-1da0a8d1ca66.png)

**Comment by AlexxIT** [comment]
Enable statistics. You should see this device in Hass. At least BLE sensor.

https://github.com/AlexxIT/XiaomiGateway3#integration-config

**Comment by sephrioth** [comment]
> Enable statistics. You should see this device in Hass. At least BLE sensor.
> 
> https://github.com/AlexxIT/XiaomiGateway3#integration-config

I enabled statistics sensors, then checked all BLE sensors one by one, but still can't find the lock related sensor.

**Comment by AlexxIT** [comment]
You need to make some actions with lock. Open/close/etc.

**Comment by sephrioth** [comment]
Still no luck... no new BLE sensors

**Comment by AlexxIT** [comment]
What integration version and gateway firmware are you using?

**Comment by sephrioth** [comment]
Integration: v2.1.2
 Firmware: v1.5.0_0102

**Comment by AlexxIT** [comment]
Maybe it is new Lock and you need latest gateway firmware. Latest integration alpha version support it.

**Comment by sephrioth** [comment]
I can try integration alpha version later, but what do you mean the latest gateway firmware, which is not supported?

**Comment by AlexxIT** [comment]
Latest gateway firmware 1.5.4

**Comment by sephrioth** [comment]
> 

Okay, so the alpha version will support 1.5.4, right? Okay, I will try later

**Comment by sephrioth** [comment]
> Maybe it is new Lock and you need latest gateway firmware. Latest integration alpha version support it.

I can't update my firmware to 1.5.4 despite I set the firmware lock to disabled.  
The update process failed at the beginning.

**Comment by AlexxIT** [comment]
Try to enable lock and disable lock.

**Comment by sephrioth** [comment]
> Try to enable lock and disable lock.

I updated firmware from telnet. Now my gateway firmware version is 1.5.4 and gateway3 version is v3.0.0, but still no new device...

**Comment by AlexxIT** [comment]
Enable basic logs and post them here
https://github.com/AlexxIT/XiaomiGateway3#integration-config

**Comment by sephrioth** [comment]
I enabled basic logs in 'Configure' and debug logging in settings, then restart HA, but no gateway3 log show up, weird?

**Comment by sephrioth** [comment]
Okay, now I have this..

> Error unloading entry Gateway3 for light
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
>     result = await component.async_unload_entry(hass, self)
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 624, in async_unload_entry
>     return await component.async_unload_entry(entry)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_unload_entry
>     await platform.async_reset()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 723, in async_reset
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 826, in async_remove
>     await self.async_will_remove_from_hass()
>   File "/config/custom_components/xiaomi_gateway3/light.py", line 160, in async_will_remove_from_hass
>     child.entities.pop(self.attr)
> KeyError: 'group'
> 
> Platform xiaomi_gateway3 does not generate unique IDs. ID 14a306d7d482d000_light is already used by light.gateway3_wash_area - ignoring light.gateway3_wash_area
> Platform xiaomi_gateway3 does not generate unique IDs. ID 14a3b47670873000_light is already used by light.gateway3_bedroom_spotlight - ignoring light.gateway3_bedroom_spotlight

**Comment by AlexxIT** [comment]
This error fixed in latest release
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.1.0

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant

**Comment by LostBrainz** [comment]
> Here is the lock, but I can't find it in gateway3 devices. https://home.miot-spec.com/s/lumi.lock.wbmcn1

hi, i have the same lock(
you fix tis problem? 
everyting working?
