### ISSUE TITLE
Solved the firmware lock issue

### ISSUE THREAD

**Issue by gartz** [AlexxIT/XiaomiGateway3#909]
The command to lock the firmware in the HASS is throwing errors, then I did some research and found that there are two issues:
1. the busybox is not in /data/busybox
2. the version available in the firmware of busybox doesn't have support to chattr.

To fix the issue I connected by telnet (use the telnet tutorial), after updating the firmware to the one that works, I did the following:

```
touch /data/firmware/firmware_ota.bin
curl -s -k -L -o /tmp/busybox https://github.com/niceboygithub/XiaomiGateway3fw/blob/master/binutils/busybox-mipsel?raw=true
chmod +x /tmp/busybox
/tmp/busybox chattr +i /data/firmware/firmware_ota.bin
```

Those commands will download a busybox that has chattr enabled, add execution permission, then make the /data/firmware/firmware_ota.bin read-only, forcing the auto-update to fail, allowing the device to stay in the stable firmware.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/blob/a10b17fb0923bfeaa0950a24c7cae054b50cd864/custom_components/xiaomi_gateway3/core/shell/shell_mgw.py#L116-L119
