### ISSUE TITLE
New Home Assistant 2023.1 error

### ISSUE THREAD

**Issue by GeoViljoen** [AlexxIT/XiaomiGateway3#910]
With the HA 2023.1 release the following error is appearing in the Home Assistant logs.
Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
9:25:28 AM – (ERROR) setup.py
Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
9:25:28 AM – (ERROR) Xiaomi Gateway 3 (custom integration)

**Comment by frabar55** [comment]
the same for me with the HA 2023.1 too

Thanks

**Comment by GeoViljoen** [comment]
Sorry, I see it has been reported already....
