### ISSUE TITLE
Setup failed for custom integration xiaomi_gateway3

### ISSUE THREAD

**Issue by datvista** [AlexxIT/XiaomiGateway3#911]
Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by Bastien42** [comment]
Can confirm that on latest HA core integration is broken

**Comment by lysiong** [comment]
same error after install HA core 2023.1.2

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1

**Comment by datvista** [comment]
Thank you, resolved.

**Comment by Alex2030S** [comment]
> https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1

Great job!!!

**Comment by du100tom** [comment]
Perfect. Thank you.

**Comment by Edvatronas** [comment]
Or how to install this? https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1 (Sorry I'am new in HA)

**Comment by bobofruit1970** [comment]
@Edvatronas 
1. Open HACS
2. Choose "Xiaomi Gateway 3"
3. Click three dots in right upper corner

![image](https://user-images.githubusercontent.com/67933104/211932872-de7b3af1-d8e2-4cb8-8624-b8a0dfcf2296.png)

5. Choose redownload
6. Mark "Show beta version" and wait 3-4 seconds

![image](https://user-images.githubusercontent.com/67933104/211934198-f529591f-fd3e-48e5-96a7-39920dcc276d.png)

8. select version v3.0-alpha.1 and wait 3-4 seconds
9. select download

**Comment by Edvatronas** [comment]
> @Edvatronas
> 
>     1. Open HACS
> 
>     2. Choose "Xiaomi Gateway 3"
> 
>     3. Click three dots in right upper corner
> 
> 
> ![image](https://user-images.githubusercontent.com/67933104/211932872-de7b3af1-d8e2-4cb8-8624-b8a0dfcf2296.png)
> 
>     5. Choose redownload
> 
>     6. Mark "Show beta version" and wait 3-4 seconds
> 
> 
> ![image](https://user-images.githubusercontent.com/67933104/211934198-f529591f-fd3e-48e5-96a7-39920dcc276d.png)
> 
>     8. select version v3.0-alpha.1 and wait 3-4 seconds
> 
>     9. select download
> 
>     10. Restart Home Assistaant

Many Thanks :) No more Errors in HA.
Just.. I have aqara motion sensor and Yealylight blub, which must turn on when the motion is detected... before light turns on in 1 sec, right know it takes maybe 5 sec. and I'am not happy with that. I was thouth the delay is because the errors, but right know there is no errors, but I have delay for 5 sec. Maybe it's different reason, but I'am stuck with that.

**Comment by fratellino69** [comment]
not working send button (Invia in the attached img). when click, nothing happens

![Immagine](https://user-images.githubusercontent.com/52664623/212176285-67a44f49-b372-4091-938c-8f7f060f7d8e.png)

**Comment by AlexxIT** [comment]
Nothing can not happen. Perhaps there is an error that shows up in the HA logs.

**Comment by abpross** [comment]
Same problems after update Home Assist. to 2023.1.4
and update Hacs: Xiaomi Gateway 3
the  update Hacs: Xiaomi Gateway 3, did not resolved the problem for me.

**Comment by petrotti77** [comment]
Versione v3.0-alpha.1 su HA 2023.1.1 e successive non funziona. Eseguito ripristino di HA 2023.1.1 e versione 2.1.2 di xiaomi gatewey 3 e adesso tutto funziona. Si prega gentilmente di risolvere. Grazie.

**Comment by Ahriman** [comment]
> https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1

Thank you, working perfect again :)

**Comment by Deny11Matrix** [comment]
Home Assistant 2023.1.5 e Versione v3.0-alpha.1: funziona di nuovo :)

**Comment by Vanooname** [comment]
Same problems after update Home Assist. to 2023.1.6

Version v3.0-alpha.1 solved the problem. But the alpha version installer is not very good. Is it planned to fix the problem in standard releases?

**Comment by Edvatronas** [comment]
I also have problems with  entities as shown in attached img
![Screenshot_3](https://user-images.githubusercontent.com/119501537/213780386-641a073a-f1fe-44db-affe-c3f744a33855.png)
![Screenshot_4](https://user-images.githubusercontent.com/119501537/213780401-a9db5c4b-aed2-4f80-b60e-6350795fe4df.png)

**Comment by SiwenL** [comment]
I have the same entity no longer in use issue as @Edvatronas 's screenshot using **v3.0-alpha.1.**
Then I had another error: "Can't connect to gateway" while delete the integration -> redownload **v3.0.0** or **Master** (as per #925 recommended) -> add back the gateway
<img width="599" alt="image" src="https://user-images.githubusercontent.com/46313354/214230620-ffcedcf0-8f97-4c0c-a3e5-d9706574d45c.png">
The gateway is working fine in the Xiaomi App.

Wondering anyone has the similar issue?
