### ISSUE TITLE
Home Assistant 2023.1.2 Xiaomi Gateway 3 Error does not start

### ISSUE THREAD

**Issue by ErnestoBrandao** [AlexxIT/XiaomiGateway3#912]
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 05:56:45 (1 occurrences)
Last logged: 05:56:45

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

2023.1.1 is OK

**Comment by zxjlover** [comment]
Me too. HOW TO DO?

**Comment by ErnestoBrandao** [comment]
Back to 2023.1.1 restore backup for now. :(

**Comment by AlexxIT** [comment]
#911
