### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#913]
- [x] Empty Bluetooth oe attribute in _gateway sensor (gw3).
- [x] Strange RSSI attribute value (-116 instead of -16) in _gateway sensor (gw3).
- [x] Turning on "Mode ZHA or zigbee2mqtt" option in integration settings doesn’t delete devices and entities from Mi Home mode. They are just in unavailable state. Perhaps they could be deleted manually (didn't check that).
- [ ] _zigbee sensor of ZBMINI device has empty Type and Parent attributes until relay switch changes its state (gw3).
- [x] Perhaps this icon is not necessary "switch": "mdi:light-switch". HA has it's own default icon for switch entities.
- [ ] Group of mesh-lightbulbs doesn’t appear in HA after creating in Mi Home.
- [ ] Local mesh-group operation can’t be checked due to item No 6.
- [ ] A lot of "Entity ___________ cannot be added a second time to an entity platform" lines in HA logs after HA restarts. Unable to reproduce after each restart.
- [ ] _zigbee sensor of zigbee devices (mains powered) paired to mgw2 has empty Type and Parent attributes.
- [ ] Issues with mesh-devices control in multi-gateway setup if main gateway is unavailable.
- [x] Adding mgw2 to HA has some issues in case of incorrect open telnet command (admin instead of root). There is no any error output, telnet opened but password for root is not empty.
- [ ] A lot of empty attributes in _gateway sensor (mgw2).
- [ ] Remove old settings from Config window

**Comment by gevorgmansuryan** [comment]
also zigbee TS0003 (TS0003)by Tuya stopped responding after upgrading to version 3

**Comment by AlexxIT** [comment]
@gevorgmansuryan if your other zigbee devices works - problem not related to v3

**Comment by Enzokot** [comment]
`*_zigbee` sensor of zigbee devices paired to gw3 has empty or question mark `type` or `parent` attributes.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/43236573/213160498-253f26ce-26f4-4b81-adf6-b592af01edac.png)

</details>
