### ISSUE TITLE
WXKG17LM (lumi.remote.acn004) cannot change multi mode

### ISSUE THREAD

**Issue by kei81131** [AlexxIT/XiaomiGateway3#914]
I've updated master version last week, 
and found that WXKG17LM (lumi.remote.acn004) had new configuration mode [speed or multi]
if choose multi, it can detect single/double click and hold

However, only single click today. 
Don't know why, please help
![WXKG17LM](https://user-images.githubusercontent.com/111072203/211266502-08da68f5-2429-4214-870e-f93f4a71ab01.jpg)

**Comment by AlexxIT** [comment]
You need to wake up the device when you change the setting

**Comment by kei81131** [comment]
Oh, got it 
and it works well, thank you so much

**Comment by kei81131** [comment]
BTW
WXKG16LM (lumi.remote.acn003) have no configuration mode
Is this device not support?

**Comment by AlexxIT** [comment]
@kei81131 I don't know
