### ISSUE TITLE
problems with version 2023.1.2 Source: setup.py:210

### ISSUE THREAD

**Issue by gladiangel** [AlexxIT/XiaomiGateway3#915]
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 09:28:42 (1 occurrences)
Last logged: 09:28:42

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by rogodra** [comment]
This alpha version fixes the problem:
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.0-alpha.1

**Comment by AlexxIT** [comment]
#911
