### ISSUE TITLE
Disable buzzer option not showing in v3.0-alpha.1

### ISSUE THREAD

**Issue by Cheerpipe** [AlexxIT/XiaomiGateway3#919]
Disable buzzer option was working well until i upgraded to v3.0-alpha.1.

In v3.0-alpha.1 this option has disappeared and buzz sound has returned

![image](https://user-images.githubusercontent.com/972765/211321210-ae9f99ac-288c-46e8-8a26-ae5d1930f81f.png).

**Comment by AlexxIT** [comment]
v3.0 has new way to disable buzzer:
https://gist.github.com/AlexxIT/095a4324e57615be81030cae4eb6d450

**Comment by Talixme** [comment]
> v3.0 has new way to disable buzzer: https://gist.github.com/AlexxIT/095a4324e57615be81030cae4eb6d450

Hello,

First things first, Thanks a lot for all your work!!!!

I have the same problem here,can you please explain how to do it??
Do i have to install openmiio???

Thanks a lot.

**Comment by shummo** [comment]
Thanks, Now I understand it :)

**Comment by AlexxIT** [comment]
You shouldn't change `openmiio_agent` file. Only add `lua` script to same folder.

**Comment by mihailM** [comment]
Hello! 
@AlexxIT is this modification working only on mgl03_1.5.0_0102? Or it doesn't matter? It's look like it doesn't work at mgl03_1.5.4_0090

**Comment by mihailM** [comment]
@AlexxIT strange, everything complete like on guide, it's work well on one gateway with 0102 and doesn't work at 4_0090. Thanks for quick answer will recheck everything!

**Comment by tzungshiun** [comment]
I also suffered it, my firmware is 1.5.4.
And it is fxed after rebooting gateway again.

Mikhail Mikhailichenko ***@***.***> 於 2023年4月25日 週二 15:54 寫道：

**Comment by yuqianma** [comment]
I encountered the buzzer issue on 1.5.4 too.
It works most of time. But buzzes one or two times irregularly when the motion sensor is triggered.

How to debug this issue? Having no idea...
Saw `[BASE] Applied 0 patches to daemons` in log. Is it fine?
