### ISSUE TITLE
HACS wants to go back to 2.12

### ISSUE THREAD

**Issue by jjpvdpoel** [AlexxIT/XiaomiGateway3#922]
Because of the climate component issue with the new Home Assistant update, I've done a redownload with the "master" option on HACS. The issue is gone now (great!), but HACS is prompting me to do an "update" to the stable 2.1.2 now.
Is there any sight on a 2.1.3 soon?

**Comment by AlexxIT** [comment]
No. After v3.0-beta will be next beta or v3.0 release
