### ISSUE TITLE
Xiaomi BLE devices unavailable on 2023.1.0b0+

### ISSUE THREAD

**Issue by karolzamosc** [AlexxIT/XiaomiGateway3#925]
I noticed that 2023.1.0b0+ fix the #899 issue but causes the BLE devices become unavailable in HA

**Comment by hayvan96** [comment]
Same here, running latest HA and 3.0alpha version.
Data are visible and correct in Xiaomi home so it's not a server side issue like in November.

**Comment by karolzamosc** [comment]
> Same here, running latest HA and 3.0alpha version. Data are visible and correct in Xiaomi home so it's not a server side issue like in November.

And rolling back to previous version causes the BLE works back again so it is not Xiaomi servers issue

**Comment by kemendib** [comment]
Same here. The BLE devices keep becoming unavailable from time to time. They reappear after a while. In Mi Home, under the gateway I can see the bluetooth child devices and they seem to update and work as they should, so it has to do something with the integration. I am using the latest available alpha version of the integration and the latest version of HA.

**Comment by BartProvoost** [comment]
Same problem with the last update of HA, but I also get this notification now:

![image](https://user-images.githubusercontent.com/33250175/212131199-74cf3084-6109-4571-953f-e0982d237a4a.png)

And these errors in the logs:

We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
5:49:16 PM – (WARNING) loader.py - message first occurred at 5:49:16 PM and shows up 14 times
Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)
January 11, 2023 at 5:26:15 PM – (ERROR) setup.py

**Comment by hayvan96** [comment]
> > Same here, running latest HA and 3.0alpha version. Data are visible and correct in Xiaomi home so it's not a server side issue like in November.
> 
> And rolling back to previous version causes the BLE works back again so it is not Xiaomi servers issue

Rolling back HA update or the add on?

**Comment by karolzamosc** [comment]
> > > Same here, running latest HA and 3.0alpha version. Data are visible and correct in Xiaomi home so it's not a server side issue like in November.
> > 
> > 
> > And rolling back to previous version causes the BLE works back again so it is not Xiaomi servers issue
> 
> Rolling back HA update or the add on?

add on

**Comment by MarcinKnD** [comment]
just make an update to 2023.1 and error 

`Logger: homeassistant.setup
Source: setup.py:210
First occurred: 20:05:38 (1 occurrences)
Last logged: 20:05:38

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)`

**Comment by AlexxIT** [comment]
#911

**Comment by hayvan96** [comment]
Sorry but this bug is not closed. You're right the last comments, which are off topic, are from users still on v2. But see the OP post and my additions: v3alpha doesn't fix this issue. As a matter of fact other bug reports are flourishing on the same subject.

**Comment by AlexxIT** [comment]
@hayvan96 try latest master. Maybe it helps. It has fix for timeouts for some BLE devices

**Comment by karolzamosc** [comment]
> @hayvan96 try latest master. Maybe it helps. It has fix for timeouts for some BLE devices

Unfortunately BLE is still not working...

**Comment by AlexxIT** [comment]
So you need to check logs, enable debug and provide some useful info. Because BLE works for most users on latest Hass, latest (and old) gateway firmware and on integration master version.

**Comment by karolzamosc** [comment]
[xiaomi_gateway3.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10420218/xiaomi_gateway3.txt)

For example, HHCCJCY01 sensor is discovered and works fine. But Xiaomi Kettle YM-K1501 is unavailable all the time...

**Comment by AlexxIT** [comment]
Kettle fixed on master version. If it doesn't work for you - you did not install the master version.

**Comment by AlexxIT** [comment]
@karolzamosc I can see international Kettle in your logs. The fix tested only on CH version. I need file `/data/openmiio_agent.json` from your gateway. You can send it to me in private msg to contacts from Github page.

**Comment by kemendib** [comment]
It still does not work for me. I am not a programmer, I don't know how to use debug mode, I can only tellnyou that it was working before and now it is only working partially. I am using 2 Flower Care sensors and a Xiaomi temperature and humidity sensor.

**Comment by karolzamosc** [comment]
> @karolzamosc I can see international Kettle in your logs. The fix tested only on CH version. I need file `/data/openmiio_agent.json` from your gateway. You can send it to me in private msg to contacts from Github page.

Ok, works fine... After installing master version nothing happened but after rebooting not only HA but host - I have this:
![Screenshot_2023-01-15-15-03-27-169_io homeassistant companion android](https://user-images.githubusercontent.com/61420368/212545517-bbd4b74a-1790-434d-9ba8-67bcf80b789f.jpg)

**Comment by AlexxIT** [comment]
@kemendib Flower Care and some TH sensors has problems on latests alpha version. And shouldn't have problems on latest master version.

@karolzamosc OK, so fix for CH version also work for EU version. This is different models.

**Comment by kemendib** [comment]
@AlexxIT you mean version v2.1.2? With that the integration stops working at all.

**Comment by karolzamosc** [comment]
> @AlexxIT you mean version v2.1.2? With that the integration stops working at all.

![Screenshot_2023-01-15-15-11-47-522_io homeassistant companion android~2](https://user-images.githubusercontent.com/61420368/212545810-b418fde5-d474-4731-a666-f8bfdd3972dd.jpg)

**Comment by AlexxIT** [comment]
Master is v3 version. It has a lot of difference vs v2.
I don't have time to publish stable release.
So as temporary solution is better to use master version.
I'm using it several months as main for my gateways.

**Comment by kemendib** [comment]
Thank you very much, I am testing the master version now! So far it seems to work! Thanks again, and also for your whole work! :)
