### ISSUE TITLE
how do I connect a non-xiaomi BLE device?

### ISSUE THREAD

**Issue by Yury777** [AlexxIT/XiaomiGateway3#93]
I have a nordic thingy52, which has a lot of sensors and transmits their values via BLE, in addition there is a built-in microphone and speaker, I would like to connect it to HA, via Xiaomi Gateway3, is it possible?
https://www.nordicsemi.com/Software-and-tools/Prototyping-platforms/Nordic-Thingy-52

**Comment by AlexxIT** [comment]
Third party Bluetooth don't surprised. It's technically very difficult

**Comment by Yury777** [comment]
а это поможет? 
https://github.com/wlgrd/thingy52_homeassistant

**Comment by AlexxIT** [comment]
There are no such utilities on the hub. There is a completely different architecture

**Comment by Yury777** [comment]
жаль, железка очень мощная, можно ее использовать как сенсоры, подключить к ней исполнительные устройства (есть 4 мосфета), да еще и общаться через нее с умным домом голосом...

**Comment by Yury777** [comment]
а gateway3 какие данные по BLE видит? по идее он должен сканировать эфир и спариваться со всеми из белого списка и считывать GATT характеристики.

**Comment by AlexxIT** [comment]
Я не специалист по BLE. И на данный момент вся логика спрятана внутри ПО от Xiaomi. Что там происходит - понять трудно

**Comment by alonl** [comment]
@AlexxIT many thanks for this great project.
I have a question related to the discussion here:
I understand that it is difficult to add a support for a third-party BLE device; however, is there a chance that what I'm looking for might be easier? I want to control a Switchbot device via BLE using the Xiaomi Gateway 3. It doesn't require pairing, as I understand, and it's as easy as in here: https://github.com/cagnulein/switchbot_press
Do you think it is possible? I'll be happy to contribute and code it myself, if needed, but first I wanted to get your opinion.
Thanks again!

**Comment by AlexxIT** [comment]
@alonl previously you need disable default Xiaomi Bluetooth utility on gateway for free access to BT chip. Then write your own code for MIPS arch to handle work with chip.

I think better to find other solutions to handle third party Bluetooth devices.
