### ISSUE TITLE
XiaomiGateway3

### ISSUE THREAD

**Issue by gonczil** [AlexxIT/XiaomiGateway3#931]
XiaomiGateway3 is not working since the release of Home Assitant 2023.1.1, it does not load the application. If I download back the last version 2022 it runs without any problems. Am I doing something wrong or has anyone else experienced this error?
Thank you!

**Comment by Enzokot** [comment]
See https://github.com/AlexxIT/XiaomiGateway3/issues/911

**Comment by gonczil** [comment]
Thanks!!!

**Comment by gonczil** [comment]
It works perfectly!
:D
