### ISSUE TITLE
Support XMWXKG01LM and HS1BB on Gateway fw 1.5.4

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#940]
v3.0.0 changelog says "Support latest firmwares for Xiaomi Multimode Gateway 1"，But after I updated the firmware of Xiaomi Multimode Gateway to 1.5.4_0090, the Xiaomi Wireless Switch BLE (XMWXKG01LM) and the Linptech Motion Sensor (HS1BB) became unavailable.

**Comment by AlexxIT** [comment]
Known problem. You need to collect basic logs for your devices:
https://github.com/AlexxIT/XiaomiGateway3#integration-config

**Comment by gt-levkan2002** [comment]
> Known problem. You need to collect basic logs for your devices: https://github.com/AlexxIT/XiaomiGateway3#integration-config

I have enabled the basic log. Where can I view the relevant log？
