### ISSUE TITLE
¿How to bypass the 32 zigbee device limit?

### ISSUE THREAD

**Issue by Cheerpipe** [AlexxIT/XiaomiGateway3#941]
I just hit 32 zigbee device limit let me without space to pair all my sensors so i am exploring alternatives to break this limit. What is the best alternative and how should i go forward? I have some ideas but i am not sure wich one is the best.

1.- Just add a second zigbee hub gateway, ¿will this make a significant noise in my wireless network?
2.- Add a router. The truth is i don't have any idea how to do this. I don't even know if it is possible with the hub in Xiaomi mode.

Thanks in advance.

**Comment by AlexxIT** [comment]
You need to buy another gateway. Many users has two and more gateways. Zigbee very light radio protocol.

You may buy any powered Xiaomi Zigbee device. Socket, plug, etc.
