### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by GavinIves** [AlexxIT/XiaomiGateway3#942]
I see that the latest version of Xiaomi Multimode Gateway is supported on the latest version. Is it 1.5.4? Because I see that readme does not update the supporting firmware. If it is supported, do you need to do any additional operations? I do not see the detailed instructions

**Comment by AlexxIT** [comment]
There is issue about 1.5.4 support #666
It's better to ask you questing there.
1.5.4 supported in latest firmware.
There are known problems with the support of new BLE sensors. They have changed the format of transmitted data.
