### ISSUE TITLE
“Unknown error occurred“when ZHA mode

### ISSUE THREAD

**Issue by astangcong** [AlexxIT/XiaomiGateway3#944]
Now I have updated the GE3(DMWG03LM) to V3.0，but after I “” Enter the serial port settings”，then it says：Unknown error occurred

**Comment by AlexxIT** [comment]
Unknown error = unknown problem. You need to search and provide more details.

**Comment by astangcong** [comment]
sorry，but i don't know how to get logs of this gateway3 integration

**Comment by BeckXuan** [comment]
I encountered the same issue.
I learned that the openmiio_agent takes over the device and the port 8888 as well. And I noticed that when connecting to the port 8888 of the gateway, its log file /var/log/openmiio.log displays an error as below
`WRN github.com/AlexxIT/openmiio_agent/internal/zigbee/zigbee.go:139 > error="unknown baud rate"`
Referring to the source code, I found the relative lines https://github.com/AlexxIT/openmiio_agent/blob/master/internal/zigbee/zigbee.go#L184-L192
It seems that no baudRate is offered and also it cannot probe the correct baudRate to connect to the hardware. And then it raises the error and shutdown the connection to port 8888.
My solution is to add a initial baudRate to the command. I don't know if it is a correct way, but it works for me.
The solution in detail:
change the line in file `xiaomi_gateway3/core/shell/base.py`
from
`RUN_OPENMIIO = "/data/openmiio_agent miio mqtt cache z3 --zigbee.tcp=8888 > /var/log/openmiio.log 2>&1 &"`
to
`RUN_OPENMIIO = "/data/openmiio_agent miio mqtt cache z3 --zigbee.tcp=8888 --zigbee.baud=115200 > /var/log/openmiio.log 2>&1 &"`
and then reboot both the gateway and the homeassistant.

**Comment by AlexxIT** [comment]
It's better to update and fix probe logic. Because probe ensure that chip in correct state and can answer to requests.
Looks like you using default chip firmware because 115200 baud rate.
What model is your gateway? What firmware?

**Comment by BeckXuan** [comment]
> It's better to update and fix probe logic. Because probe ensure that chip is in correct state and can answer to requests. Looks like you using default chip firmware because 115200 baud rate. What model is your gateway? What firmware?

gateway: Xiaomi Multimode Gateway 2
firmware 1.0.6_0016, and the same issue for firmware 1.0.3_0028
Thanks!

**Comment by AlexxIT** [comment]
OK. I'll check with my gw
