### ISSUE TITLE
debug mode issues

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#947]
![1674663016291](https://user-images.githubusercontent.com/105607530/214619888-3ce94e8f-8e00-4887-9700-3221e8c2c584.jpg)
readme mentions "The link to the logs will apear in Notifications", but when I turn the debug logs switch on, the url does not appear in the notifications.

My integration and HA versions are up to date.

**Comment by AlexxIT** [comment]
Sorry. I have updated readme with new info about link to logs
https://github.com/AlexxIT/XiaomiGateway3#debug-mode
