### ISSUE TITLE
Bug after HA 2023.1.1

### ISSUE THREAD

**Issue by Xanderyuku** [AlexxIT/XiaomiGateway3#948]
Hello,
I use a hub Xiaomi V3 (Eu Serveur) with Xiaomi integration (2.1.1 version) and beyond version 2023.1.1 of Home Assistant or beyond 2.1.1 of the Xiaomi Integration all the hardware Aqara becomes unavailable, blocked, I have to restore my backups without being able to update Home assistant.

Firmware of my gateway Xiaomi: Firmware 1.4.6_0043 (last version in Mi Home App)

Exemple of errors i have:

![image](https://user-images.githubusercontent.com/48673913/214679799-b73e467c-96a5-403a-9a06-b6e1b0cc6814.png)

![image](https://user-images.githubusercontent.com/48673913/214679963-e07a2cb6-2264-4103-8f1a-258ef7716469.png)

If you have an idea or a solution i will really appreciate.

Edit: I already try to update the integration 3.0 or 3.0 Alpha 1 it's the same problem...

Have a good day
Xander

**Comment by AlexxIT** [comment]
Show detail log error

**Comment by JurajBrabec** [comment]
Hi AlexxIT,

I think I have the same issue, and the relevant error is: `NameError: name 'TEMP_CELSIUS' is not defined` @  `file "/config/custom_components/xiaomi_gateway3/climate.py", line 39, in XiaomiClimate _attr_temperature_unit = TEMP_CELSIUS`

Full messages are below:

- **Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
January 29, 2023 at 14:52:04 – (ERROR) setup.py**
```
Logger: homeassistant.setup
Source: setup.py:340
First occurred: January 29, 2023 at 14:52:04 (1 occurrences)
Last logged: January 29, 2023 at 14:52:04

Unable to prepare setup for platform xiaomi_gateway3.climate: Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
```

- **Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
January 29, 2023 at 14:52:04 – (ERROR) Xiaomi Gateway 3 (custom integration)**
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/xiaomi_gateway3/climate.py:39
Integration: Xiaomi Gateway 3 (documentation, issues)
First occurred: January 29, 2023 at 14:52:04 (1 occurrences)
Last logged: January 29, 2023 at 14:52:04

Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 32, in <module>
    class XiaomiClimate(XEntity, ClimateEntity):
  File "/config/custom_components/xiaomi_gateway3/climate.py", line 39, in XiaomiClimate
    _attr_temperature_unit = TEMP_CELSIUS
NameError: name 'TEMP_CELSIUS' is not defined

```
I hope it helps.

**Comment by AlexxIT** [comment]
I think you just using new Hass but outdated component
#899 #907
