### ISSUE TITLE
The zigbee device cannot be triggered and controlled

### ISSUE THREAD

**Issue by Sircoco2** [AlexxIT/XiaomiGateway3#952]
Multimode Gateway 2(1.06. _0016): After a period of time, all zigbee devices cannot be triggered and controlled (the device is not offline), but the Bluetooth mesh device is normal and needs to restart the gateway to recover.

**Comment by AlexxIT** [comment]
You need telnet to gateway and run `ps`.

**Comment by AlexxIT** [comment]
I thinks this is same issue like #961
