### ISSUE TITLE
Connection failed to xiaomi gateway3 at Setup

### ISSUE THREAD

**Issue by SiwenL** [AlexxIT/XiaomiGateway3#954]
### Setup failed for custom integration xiaomi_gateway3: Can't connect to gateway
<img width="599" alt="Screenshot 2023-01-24 at 2 59 42 PM" src="https://user-images.githubusercontent.com/46313354/215241892-a263e274-13c4-4ed3-a478-3193c409da6e.png">

The gateway is working fine in the Xiaomi App.
Home Assistant version: **2023.1.5**
Xiaomi Multimode Gateway CN version **1.5.1_0032**

The error appeared after integration was deleted and reinstalled other versions.
Reinstallation comes from _entity no longer in use_ issue during **version v3.0-alpha.1** as per https://github.com/AlexxIT/XiaomiGateway3/issues/925 recommended.

Attempts have been tried so far:
1.  reinstalled with different versions in different browsers: master/ v3.0-alpha.1/ v2.1
     1.a **v3.0-alpha.1** with manual open telnet input was working fine but facing the same connection issue now
2. reset the xiaomi gateway 3
3.  Host and token had been validated from the cloud configuration via custom integration

My next attempt will be  
1. Getting a new xiaomi gateway3

Meanwhile what else can I do to deal with this situation? Thanks in advance!
Or what other info do I need to provide? (really new to HA)

**Comment by AlexxIT** [comment]
You need to check error description in the Hass log

**Comment by maiapig** [comment]
the same problem...don't have the open telnet command option, and when I want to add my gateway, tips show that can't connect the gateway. the attached is log, I run the HA in docker with host internet. thanks
<img width="1533" alt="无标题" src="https://user-images.githubusercontent.com/38374633/215339294-46ab2f46-8013-494c-adb6-a60cd239c5a9.png">

**Comment by AlexxIT** [comment]
Device offline is a problem with your network.

**Comment by SiwenL** [comment]
> You need to check error description in the Hass log
The error didn't show up again with the same setting, connection resumed, thanks for the response.
