### ISSUE TITLE
Xiaomi Gateway 3--Firmware: 1.4.6_0040

### ISSUE THREAD

**Issue by mkhalil1991** [AlexxIT/XiaomiGateway3#957]
Hi Alexx,

Updated the Home Assistance core to the latest version (2023.1.7) and the Zigbee devices aren't responding after the update. I can access the gateway and Bluetooth devices but not the Zigbee ones. 

Your help and support are always appreciated as usual mate :) 

Thanks

**Comment by ricardobatata** [comment]
Hello,

I have exact the same problem..

**Comment by AlexxIT** [comment]
This firmware not supported more than year.

**Comment by mkhalil1991** [comment]
Thanks
How can I update the firmware?

**Comment by randybb** [comment]
https://github.com/AlexxIT/XiaomiGateway3#supported-firmwares

**Comment by mkhalil1991** [comment]
Thanks, I m a noob and don't know much. How to open the Telnet command in the Xiaomi Gateway 3? Help please.
