### ISSUE TITLE
Problem in ativating Zigfbee2mqtt mode

### ISSUE THREAD

**Issue by frabar55** [AlexxIT/XiaomiGateway3#959]
![image](https://user-images.githubusercontent.com/74005034/215521163-f875de83-0670-4d74-939a-189fe22c55a6.png)

**Comment by frabar55** [comment]
I forgot the diagnostic file, sorry
[config_entry-xiaomi_gateway3-6fd15513d7eaecf34436a5f1a2f5b654.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10537268/config_entry-xiaomi_gateway3-6fd15513d7eaecf34436a5f1a2f5b654.json.txt)

**Comment by AlexxIT** [comment]
I guess you haven't read the documentation

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3#zigbee2mqtt-mode

**Comment by frabar55** [comment]
Hi Alexx,
I followed what you suggested in documentation:
- installed zigbee2mqtt instance (via python)
- in config I inserted the two statements regarding the devices (see attached)
result: Zigbee2mqtt and zigbee-herdsman remains in starting mode (see below)
Thanks for your help

zigbee2mqtt-xi.service - zigbee2mqtt-xi
     Loaded: loaded (/etc/systemd/system/zigbee2mqtt-xi.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-02-04 11:53:44 CET; 6s ago
   Main PID: 270195 (npm start)
      Tasks: 23 (limit: 18961)
     Memory: 127.8M
        CPU: 2.138s
     CGroup: /system.slice/zigbee2mqtt-xi.service
             \u251c\u2500270195 npm start
             \u251c\u2500270209 sh -c node index.js
             \u2514\u2500270210 node index.js

feb 04 11:53:44 francesco-nipogi systemd[1]: Started zigbee2mqtt-xi.
feb 04 11:53:45 francesco-nipogi bash[270195]: > zigbee2mqtt@1.30.0 start
feb 04 11:53:45 francesco-nipogi bash[270195]: > node index.js
feb 04 11:53:46 francesco-nipogi bash[270210]: Zigbee2MQTT:info  2023-02-04 11:53:46: Logging to console and directory: '/v>
feb 04 11:53:46 francesco-nipogi bash[270210]: Zigbee2MQTT:info  2023-02-04 11:53:46: Starting Zigbee2MQTT version 1.30.0 (>
feb 04 11:53:46 francesco-nipogi bash[270210]: Zigbee2MQTT:info  2023-02-04 11:53:46: Starting zigbee-herdsman (0.14.89)
~
~

**config.yaml**
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt-xi
  server: 'mqtt://localhost'
  user: mqtt-user
  password: And02Enr07
  version: 5
  include_device_information: true
serial:
  port: tcp://192.168.178.35:8888
  adapter: ezsp
advanced:
  log_directory: /var/log
  network_key:
    - 18
    - 40
    - 1
    - 186
    - 221
    - 19
    - 54
    - 33
    - 229
    - 49
    - 35
    - 233
    - 65
    - 164
    - 69
    - 106
experimental: {}
frontend:
  port: 8585
ota:
  update_check_interval: 10
disable_automatic_update_check: false

**Comment by AlexxIT** [comment]
I'm not using z2m and can't help with problems with it
