### ISSUE TITLE
Control a Mesh Mi device without a gateway?

### ISSUE THREAD

**Issue by BillyNate** [AlexxIT/XiaomiGateway3#96]
I searched high and low looking for a way to connect to a Mesh Mi Light without the gateway, but wasn't able to find anything about this.  
If I take a look at how the Mesh Mi Light manifests itself I'm only seeing an "ordinary" Bluetooth device (no BLE Mesh advertisement), with services somewhat familiar to other Xiaomi devices (the 0xFE95 service for example).  
Since this seems to be the only place currently with other people trying to "hack" into these devices, I decided to try my luck here.  
Did anybody try to reverse engineer the protocol of a Mesh Mi device connecting to the gateway? Or willing to shine some (or any) light on the matter?  
Thanks in advance!

**Comment by AlexxIT** [comment]
I don't find any success with reverse it protocol in GitHub

**Comment by BillyNate** [comment]
Thank you for your response, much appreciated!  
I stumbled on the procedure used to [connect to a kettle](https://github.com/aprosvetova/xiaomi-kettle), and noticed the conversation over at the [Yeelight rotary dimmer](https://github.com/nccchirag/yeelight-ble-rotary-dimmer/issues/1) on which you also commented.  
Hopefully someone figures it out 😓

I'm also wondering if there's any BLE Mesh advertisement after the Mesh Mi device is authenticated by the gateway. Maybe someone could check this out?

**Comment by BillyNate** [comment]
Since this didn't yield much in a week, I'll close the issue.
