### ISSUE TITLE
Two gateways, but only one shows a BLE device

### ISSUE THREAD

**Issue by joyzainzy** [AlexxIT/XiaomiGateway3#960]
I have two gateways (GATEWAYS A AND B)
Model:ZNDMWG03LM

Question 1: 
All BLE devices are connected to gateway A, but not to gateway B.

Question 2: 
Gateway B only displays Zigbee devices, not BLE devices.

**Comment by joyzainzy** [comment]
Problem solving after restarting the homeassistant system

**Comment by AlexxIT** [comment]
Info about linking BLE devices to gateway maybe changed with every Hass restart and means nothing. Integration will read BLE data from every gateway.

**Comment by joyzainzy** [comment]
Thank you very much for your reply.
I have a new question now

All Zigbee devices are offline and out of control.

Restarting the gateway only resolves temporarily, but the issue recurs.

Gateway Model: ZNDMWG03LM

发件人: Alex ***@***.***>
发送时间: 2023年1月31日 12:40
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [AlexxIT/XiaomiGateway3] Two gateways, but only one shows a BLE device (Issue #960)


Info about linking BLE devices to gateway maybe changed with every Hass restart and means nothing. Integration will read BLE data from every gateway.

―

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/961#issuecomment-1410122713
