### ISSUE TITLE
Failing in HA 2023.2

### ISSUE THREAD

**Issue by Stooovie** [AlexxIT/XiaomiGateway3#964]
The intergration has been repeatedly failing in HA 2023.2.0. All three BLE Mesh  bulbs Xiaomi M2, YLDP25YL) I use the Gateway for get disconnected, and I have to rebot the gateway, either via software or hardware. Happened three times today (EDIT: 7 times in the last 24 hours). This was not the case before, I have been using the integration for more than a year.

I don't see anything in the log so far. I have enabled logging of the integration and will update this post.

**Comment by Stooovie** [comment]
Here is the component's log. Ignore Xiaomi Fan errors, that device is disconnected. What is repeatedly failing are my Xiaomi M2 BLE Mesh bulbs that are connected via the Gateway (have been for two years, working fine).

[https://0x0.st/oCrW.log.zip](https://0x0.st/oCrW.log.zip)

**Comment by SemonCat** [comment]
same here

**Comment by ZFF85** [comment]
unfortunately I have same problem...

**Comment by Stooovie** [comment]
I made the unfortunate mistake of trying several fixes at once but I have physically disconnected the bulbs from power and reinstalled the 3.0.0 version and the issue hasn't come back since in almost 24 hours.

**Comment by AlexxIT** [comment]
@Stooovie there is nothing in your logs about this component. You need to collect component debug logs

**Comment by jmpaiva** [comment]
I have the same problem after upgrading to latest HA version.

The other day I was not getting any data from BLE devices which I fixed (for some hours) by installing the plugin's beta version

Today, there no data from the BLE devices neither from the zigbee via Z2M event after installing the lastest non.beta version

The only logs I see are these
"2023-02-06 22:17:36.399 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Timeout while requesting MIoT api /v2/home/device_list_page"

Zigbee2MQTT Edge's dashboard shows a blank response, nothing is loaded

**Comment by Stooovie** [comment]
> @Stooovie there is nothing in your logs about this component. You need to collect component debug logs

You mean the Basic/Zigbee/MQTT debug logs?

**Comment by ab-fuze** [comment]
here are the log collected after it stops to answer and all the sensors/switches goes offline on HA but available on MI Home
`2023-03-09 18:52:26 [D] 192.168.31.126 [MIOT] 28d1273bcae8 (1772) read {'mi_spec': [{'siid': 2, 'piid': 1}, {'siid': 2, 'piid': 2}, {'siid': 2, 'piid': 3}]}
2023-03-09 18:52:27 [W] 192.168.31.126 | Can't update gateway stats|  File "/config/custom_components/xiaomi_gateway3/core/gateway/gate_mgw.py", line 113, in gw3_update_serial_stats|    payload = self.device.decode(GATEWAY, {"serial": serial.decode()})|IndexError: list index out of range|
2023-03-09 18:52:40 [D] 192.168.31.126 [LUMI] 54ef44217cf1 (lumi.gateway.mgl03) recv {'cloud_link': True}
2023-03-09 18:53:27 [D] 192.168.31.126 [BASE] 28d127272511 (1772) poll state light
2023-03-09 18:53:27 [D] 192.168.31.126 [MIOT] 28d127272511 (1772) read {'mi_spec': [{'siid': 2, 'piid': 1}, {'siid': 2, 'piid': 2}, {'siid': 2, 'piid': 3}]}
2023-03-09 18:53:57 [D] 192.168.31.126 [BASE] 28d12726e2d0 (1772) poll state light`

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
