### ISSUE TITLE
Issue about joining 2 gateways

### ISSUE THREAD

**Issue by kei81131** [AlexxIT/XiaomiGateway3#968]
Hi Alex

I've added 2 gateways through gateway3
 - ZNDMWG03LM (Firmware: 1.5.0_0102)
 - DMWG03LM (Firmware: 1.0.3_0028)

They work very great on zigbee devices.
Ble devices also great but sometimes I can't control them through gw3.
And i find out the reason is that ble device is under the gateway which is far away instead of next to that.
It looks like gateways are fighting for control.

Can I assign which ble device under specificed gateway?
Just like zigbee device

Wish you have a nice day

**Comment by AlexxIT** [comment]
BLE devices not binded to any gateway or phones or PC. They just send data everywhere like radio.
