### ISSUE TITLE
Support Multimode 1 on fw 1.4.6_0043

### ISSUE THREAD

**Issue by henkosch** [AlexxIT/XiaomiGateway3#969]
I have a gateway ZNDMWG03LM. It has been working fine in the last year or so. In the last 1-2 months it has stopped working. It can see all of the zigbee devices, but all of them show up with unknown state and the state is not updated.

Gateway Fw: 1.4.6_0043

I have upgraded HA and XiaomiGateway3 plugin with HACS to the newest version without any luck. I was keeping HA up-to-date, and I think 2023.1 broke the integration first, but I'm not sure. I just updated the XiaomiGateway3 integration in HACS today for a very long time, but it did not solve it.

Tried to delete everything, reset the gateway, pair the zigbee devices again using the Xiaomi app. They are working fine in the Xiaomi app. Then I set up the integration in HA, it succeeds, can enumerate all devices, but they show up with unknown state in HA. No updates are coming over at all. Interestingly after setting up the integration, the original Xiaomi app stops working as well, devices in the Xiaomi app will stop receiving zigbee updates... There is nothing useful in the HA logs...

Gateway:
[xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi Multimode Gateway-52e3801030e6fe85d032464bda4d1b1e.json (3).txt](https://github.com/AlexxIT/XiaomiGateway3/files/10610701/xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi.Multimode.Gateway-52e3801030e6fe85d032464bda4d1b1e.json.3.txt)

TH Sensor 1:
[xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi TH Sensor-f57c58a31add730321060fd9658aa3dc.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10610700/xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi.TH.Sensor-f57c58a31add730321060fd9658aa3dc.json.txt)

TH Sensor 2:
[xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi TH Sensor-a276548519bf3d23cc9f9ea6168f046a.json.txt](https://github.com/AlexxIT/XiaomiGateway3/files/10610702/xiaomi_gateway3-c5b8d26e44859773aa648dc44eb3f5d6-Xiaomi.TH.Sensor-a276548519bf3d23cc9f9ea6168f046a.json.txt)

Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
UI 20230202.0 - latest

HACS : Xiaomi Gateway 3 - v3.1.0

**Comment by AlexxIT** [comment]
Firmware 1.4.6_0043 not supported more than year

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
