### ISSUE TITLE
MCCGQ02HL xiaomi door/windows sensor entity status no update after few hours

### ISSUE THREAD

**Issue by lysiong** [AlexxIT/XiaomiGateway3#974]
Hi AlexxIT,
I having issue with one of the MCCGQ02HL xiaomi door/windows sensor status no update since v3 integration although Mi Home side working fine . I got 3pcs of MCCGQ02HL, only this particular sensor most of the time not working, my gateway is ZNDMWG03LM, Firmware: 1.5.0_0102.  

If I try **remove it from Mi Home & re-add back, it will work for few hours** then not update again & stuck at the last state while Mi Home side still working fine. 

By the way, I have 2pcs of ZNDMWG03LM gateway, both using fixed IP & same firmware 1.5.0_0102. Initially tot is gateway firmware issue, I try upgrade to 1.5.4_0090(did reset gateway after upgrade) but problem still the same. I already downgrade back to 1.5.0_0102. 

my HA is the latest version 2023.2.3

**Comment by lysiong** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/45681255/217971736-e808e3e0-c1b3-4977-a128-595e7c1e39ed.png">
or is that possible I have too many gateway? I not able to disable the camera & ceiling light gateway as there is no option to disable the bluetooth gateway.

**Comment by AlexxIT** [comment]
You need to collect debug logs

**Comment by lysiong** [comment]
can I message you in telegram for the debug logs?

**Comment by lysiong** [comment]
> You need to collect debug logs

can I message you in telegram for the debug logs?

**Comment by kei81131** [comment]
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/45681255/217971736-e808e3e0-c1b3-4977-a128-595e7c1e39ed.png">
> 
> or is that possible I have too many gateway? I not able to disable the camera & ceiling light gateway as there is no option to disable the bluetooth gateway.

Try click in multi gateway, can you find that MCCGQ02HL xiaomi door/windows sensor?

I've similar problem before, sensor updated in Mi app but no response in GW3
and I found that my sensor was not under multi gateway, which was under camera......
So, that make sense why no response in GW3

Then I turned off camera's bluetooth gateway (maybe few hours later, I forgot)
sensor returned under multi gateway, and GW3 works well 

Hope this will helps you

**Comment by lysiong** [comment]
> > or is that possible I have too many gateway? I not able to disable the camera & ceiling light gateway as there is no option to disable the bluetooth gateway.
> 
> Try click in multi gateway, can you find that MCCGQ02HL xiaomi door/windows sensor?
> 
> I've similar problem before, sensor updated in Mi app but no response in GW3 and I found that my sensor was not under multi gateway, which was under camera...... So, that make sense why no response in GW3
> 
> Then I turned off camera's bluetooth gateway (maybe few hours later, I forgot) sensor returned under multi gateway, and GW3 works well
> 
> Hope this will helps you

MCCGQ02HL was found on both gateway & one of the camera. I got try off the camera for few hours, then on back, the sensors will appear back after few hours on camera, seem like it already stick to camera as sensor is very near to that camera. 

I also notice this issue will temporary solved(integration detect back the sensor activity) once I restart the HA but problem will appear back after few hours once the sensor go to sleep(presume) & wake back.

**Comment by kei81131** [comment]
> > > or is that possible I have too many gateway? I not able to disable the camera & ceiling light gateway as there is no option to disable the bluetooth gateway.
> 
> > 
> 
> > Try click in multi gateway, can you find that MCCGQ02HL xiaomi door/windows sensor?
> 
> > 
> 
> > I've similar problem before, sensor updated in Mi app but no response in GW3 and I found that my sensor was not under multi gateway, which was under camera...... So, that make sense why no response in GW3
> 
> > 
> 
> > Then I turned off camera's bluetooth gateway (maybe few hours later, I forgot) sensor returned under multi gateway, and GW3 works well
> 
> > 
> 
> > Hope this will helps you
> 
> 
> 
> MCCGQ02HL was found on both gateway & one of the camera. I got try off the camera for few hours, then on back, the sensors will appear back after few hours on camera, seem like it already stick to camera as sensor is very near to that camera. 
> 
> 
> 
> I also notice this issue will temporary solved(integration detect back the sensor activity) once I restart the HA but problem will appear back after few hours once the sensor go to sleep(presume) & wake back.  


![image](https://user-images.githubusercontent.com/111072203/218376448-73413e25-a129-40b2-9a30-539265910939.jpeg)
Turn off the gateway function of the camera

**Comment by lysiong** [comment]
> > > > or is that possible I have too many gateway? I not able to disable the camera & ceiling light gateway as there is no option to disable the bluetooth gateway.
> > 
> > 
> > > 
> > 
> > 
> > > Try click in multi gateway, can you find that MCCGQ02HL xiaomi door/windows sensor?
> > 
> > 
> > > 
> > 
> > 
> > > I've similar problem before, sensor updated in Mi app but no response in GW3 and I found that my sensor was not under multi gateway, which was under camera...... So, that make sense why no response in GW3
> > 
> > 
> > > 
> > 
> > 
> > > Then I turned off camera's bluetooth gateway (maybe few hours later, I forgot) sensor returned under multi gateway, and GW3 works well
> > 
> > 
> > > 
> > 
> > 
> > > Hope this will helps you
> > 
> > 
> > MCCGQ02HL was found on both gateway & one of the camera. I got try off the camera for few hours, then on back, the sensors will appear back after few hours on camera, seem like it already stick to camera as sensor is very near to that camera.
> > I also notice this issue will temporary solved(integration detect back the sensor activity) once I restart the HA but problem will appear back after few hours once the sensor go to sleep(presume) & wake back.
> 
> ![image](https://user-images.githubusercontent.com/111072203/218376448-73413e25-a129-40b2-9a30-539265910939.jpeg) Turn off the gateway function of the camera

Mines dont have this option, I believe u login to china region but mines one on SG region.

**Comment by lysiong** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/45681255/218392977-de0c3f5d-548e-4b72-9707-42be46abfc6f.png">

**Comment by kei81131** [comment]
> <img width="540" alt="image" src="https://user-images.githubusercontent.com/45681255/218392977-de0c3f5d-548e-4b72-9707-42be46abfc6f.png">
> 
> 

Latest fw?
Mines 4.3.4_0407

**Comment by lysiong** [comment]
> > <img alt="image" width="540" src="https://user-images.githubusercontent.com/45681255/218392977-de0c3f5d-548e-4b72-9707-42be46abfc6f.png">
> 
> Latest fw? Mines 4.3.4_0407

<img width="540" alt="image" src="https://user-images.githubusercontent.com/45681255/218646509-3e2fc2a8-ff17-4f04-a9ea-04446145158c.png">

**Comment by lysiong** [comment]
If I join china region then I will have that Bluetooth gateway disable switch, SG region don't have that function. Problem is china region in our country is slow respond when watch the camera playback.

**Comment by lysiong** [comment]
@kei81131 , let me try this method, I try join CN region to disable the gateway on camera & light then add back SG region to see if sensor still stick to camera or not. I also notice the ZNDMWG03LM gateway firmware version also got effect on this matter, old version of firmware seem like made sensor won't stick to other gateway.

**Comment by kei81131** [comment]
> @kei81131 , let me try this method, I try join CN region to disable the gateway on camera & light then add back SG region to see if sensor still stick to camera or not. I also notice the ZNDMWG03LM gateway firmware version also got effect on this matter, old version of firmware seem like made sensor won't stick to other gateway. 


I'm afraid not, cause it requires factory reset before pairing

I've tried a method to assign which ble under which gateway. 
It works for me but it sounds stupid...
You can take a look

In your case, open a new mi account to separate camera, and SHARE camera to original account.
Then you can use original account to watch camera also camera's gateway will not interact ble devices under original account.

BTW, side effect is no automations in different accounts in mihome app

**Comment by lysiong** [comment]
> > @kei81131 , let me try this method, I try join CN region to disable the gateway on camera & light then add back SG region to see if sensor still stick to camera or not. I also notice the ZNDMWG03LM gateway firmware version also got effect on this matter, old version of firmware seem like made sensor won't stick to other gateway.
> 
> I'm afraid not, cause it requires factory reset before pairing
> 
> I've tried a method to assign which ble under which gateway. It works for me but it sounds stupid... You can take a look
> 
> In your case, open a new mi account to separate camera, and SHARE camera to original account. Then you can use original account to watch camera also camera's gateway will not interact ble devices under original account.
> 
> BTW, side effect is no automations in different accounts in mihome app

sound like interesting, I do have both SG & CN account in Mi Home, but I haven try the share user feature of the Mi Home. I will give a try.

**Comment by lysiong** [comment]
I just try, look like can share device to same region only or else you wont see any invitation.

**Comment by lysiong** [comment]
or another solution is change all motion sensor to zigbee type.

**Comment by kei81131** [comment]
> or another solution is change all motion sensor to zigbee type. 

Yes, zigbee devices is more suitable in your case

**Comment by lysiong** [comment]
> > or another solution is change all motion sensor to zigbee type.
> 
> Yes, zigbee devices is more suitable in your case

For all the bluetooth motion sensor, I now temporary use Xiaomi BLE integration from official HA & add one ESP32 module as a bluetooth proxy module, so far so good.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
