### ISSUE TITLE
ZNXDD01LM issue

### ISSUE THREAD

**Issue by rumianoesa** [AlexxIT/XiaomiGateway3#978]
When I turn on the light with Home Assistant service, Home Assistant and also Mijia Cloud show switch status is on
```
        "type": "encode",
        "value": {
          "light": true
        }
```
```
        "type": "decode_lumi",
        "value": [
          {
            "siid": 2,
            "piid": 1,
            "value": 1
```

However, the light itself is still off. Switch status returns to off after a while
```
        "type": "decode_lumi",
        "value": [
          {
            "siid": 2,
            "piid": 1,
            "value": false
          },
          {
            "siid": 2,
            "piid": 2,
            "value": 100
          },
          {
            "siid": 2,
            "piid": 3,
            "value": 6500
```

Only if I change or reset brightness value after I turn on the light with Home Assistant service, the light will be actually turned on
```
        "type": "encode",
        "value": {
          "brightness": 255
        }
```

_____________________________________________________________________

When I change brightness value with Home Assistant service, the light itself will refrence it. But Home Assistant and Mijia Cloud do not refresh the brightness value. When I change brightness value with Mijia Cloud, Home Assistant will refresh it.

And color_temp value in dashboard is always min. But the light itself will refrence the color_temp value if I change it with Home Assistant service, just like I change brightness value. In this case, Home Assistant and Mijia Cloud do not refresh it as well.

**Comment by AlexxIT** [comment]
Looks like gateway return wrong device state. I can't do anything about it.
