### ISSUE TITLE
''Open Telnet Command" did not show up. 

### ISSUE THREAD

**Issue by CCCCCChen** [AlexxIT/XiaomiGateway3#980]
Gateway: Xiaomi Multimode Gateway CN (ZNDMWG03LM)
Firmware: 1.5.4_0090
HA version: Home Assistant 2023.2.2
XiaomiGateway3 version: [v3.1.0 - 2023-02-01](https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.1.0)
Issue:
When I try to hack into this gateway after connecting to my xiaomi cloud, I couldn't find "Open Telnet Command". Is this firmware not supported or is there any step I miss during the hacking?
![1676303065904](https://user-images.githubusercontent.com/10110671/218504446-27157083-103b-4e92-a698-31771a55f13c.png)

Thanks.

**Comment by tianzhuang55** [comment]
same here.

Gateway: Xiaomi Multimode Gateway CN (ZNDMWG03LM)
Firmware: 1.5.4_0090
HA version: Home Assistant 2023.1.7

**Comment by tianzhuang55** [comment]
SORRY, just reviewed the release notes, and the telnet command has been cancelled since V3.0

**Comment by CCCCCChen** [comment]
Oh I see. Thank. XD
