### ISSUE TITLE
Linptech ES1 support missing

### ISSUE THREAD

**Issue by to4ko** [AlexxIT/XiaomiGateway3#983]
Alex,

please add support for Linptech ES1 occupancy sensor

https://home.miot-spec.com/spec/linp.sensor_occupy.hb01

some logs atached

[es1.log](https://github.com/AlexxIT/XiaomiGateway3/files/10733494/es1.log)

**Comment by diodnick** [comment]
Hello! I had the same issue. You need to update the MiHome app to the latest version. There is support for this presence sensor in the xiaomi gateway 3.

**Comment by diodnick** [comment]
And need China region

**Comment by to4ko** [comment]
it's not about his sensor support in mihome (which is ok). its sbout Alex component to suport the sensor already added to mihome.

**Comment by to4ko** [comment]
closing this on as device appeared in HA after number of HA restarts
