### ISSUE TITLE
ZY-M100 mmWave sensor support

### ISSUE THREAD

**Issue by Cheerpipe** [AlexxIT/XiaomiGateway3#986]
Is there any chance to get ZY-M100 support? It is paired but isn't any converter for this.

I may help with test and debug 

DPs: https://github.com/zigpy/zha-device-handlers/pull/1928#issuecomment-1338267352

**Comment by Cheerpipe** [comment]
¿What converter should i use for this?

![image](https://user-images.githubusercontent.com/972765/221749491-bd17c2a8-64c6-4528-b390-869df2b6e6c3.png)

I tried ZConverter, Converter, ZMathConverter and MathConverter but none of those can read/write any value. I am getting this error:

![image](https://user-images.githubusercontent.com/972765/221750462-64d8a744-3da6-46f4-bd2a-0d2f418ee0a3.png)

What is the difference between Converter and ZConverter by the way?

Thanks in advance

**Comment by Cheerpipe** [comment]
This is my current converter:

```
{
    "TS0601": ["Tuya", "mWave sensor", "ZY-M100"],
    "support": 1,
    "spec": [
         BoolConv("occupancy", "binary_sensor"),
         MathConv("Sensitivity", "number", min=0, max=9),
         MathConv("Near Detection", "number", min=0, max=1000),
         MathConv("Far Detection", "number", min=0, max=1000),
    ],
}
```

**Comment by AlexxIT** [comment]
If you can't write the converters yourself, you can use the ZHA mode on the gateway

**Comment by 000al000** [comment]
I try solution from [Cheerpipe](https://github.com/Cheerpipe) but have error

2023-11-26 14:27:22 [D] 10.100.10.226 [ZIGB] 0xa4c1385a0455c8d3 (0x0ae1) recv {'endpoint': 1, 'seq': 246, 'cluster_id': 61184, 'command_id': 2, 'value': b'\x00\x0fm\x02\x00\x04\x00\x00\x00\x00'}
2023-11-26 14:27:22 [D] 10.100.10.226 [ZIGB] 0xa4c1385a0455c8d3 0x0ae1 send {'endpoint': 1, 'seq': 246, 'cluster_id': 61184, 'command': 'Default_Response', 'value': 2, 'status': 'Status.UNSUPPORTED_CLUSTER'}

**Comment by Cheerpipe** [comment]
> I try solution from [Cheerpipe](https://github.com/Cheerpipe) but have error
> 
> 2023-11-26 14:27:22 [D] 10.100.10.226 [ZIGB] 0xa4c1385a0455c8d3 (0x0ae1) recv {'endpoint': 1, 'seq': 246, 'cluster_id': 61184, 'command_id': 2, 'value': b'\x00\x0fm\x02\x00\x04\x00\x00\x00\x00'} 2023-11-26 14:27:22 [D] 10.100.10.226 [ZIGB] 0xa4c1385a0455c8d3 0x0ae1 send {'endpoint': 1, 'seq': 246, 'cluster_id': 61184, 'command': 'Default_Response', 'value': 2, 'status': 'Status.UNSUPPORTED_CLUSTER'}
> 
> Maybe somebody can give link to instruction how create own converter?

Hi. I ended up using zha with z2m and now changed to zha because z2m don't have automatic reconnect wen connection is interrupted.
