### ISSUE TITLE
Mi Curtain Companion Questions

### ISSUE THREAD

**Issue by HomeQi** [AlexxIT/XiaomiGateway3#987]
[homeassistant.components.homekit.accessories] cover.ec4d3ed52514_motor: Battery charging binary_sensor state missing: None

**Comment by HomeQi** [comment]
And the state of the curtains will appear 1% or 99% when opening or closing the curtains, and will not reset, I need to click on the details and manually adjust

**Comment by HomeQi** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/54731976/219880219-97e5bd37-5905-4a3e-bdb9-542da9d7099a.png">

**Comment by HomeQi** [comment]
I looked through the relevant answers under all the issue, but found no results, I hope you can help me when you are free.thanks

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by AlexxIT** [comment]
Closed without response
