### ISSUE TITLE
Xiaomi Gateway 3 (ZNDMWG03LM) Mesh update interval 

### ISSUE THREAD

**Issue by clearwhitesky** [AlexxIT/XiaomiGateway3#989]
Hi, this post is similar to the post I made on HACS forum.

I have a dozen of Xiaomi Mesh power socket (ZNCZ01ZM) which is capable of getting outlet, power, led, power_protect, power_value.

As I understood (maybe I’m wrong) that the Mesh message can be sent out randomly by the device itself thus we don’t have much control over how often we wanted to. As such automation might not be able to trigger at the precise moment if needed.

As for my device (ZNCZ01ZM) it gets updated roughly at about 9 to 10 mins timeframe and even if it gets updated, I believe it's just a message to respond to the gateway it is still there, it doesn’t contain the full message.

I've noticed once I fire up my Mi Home app and enter into the device, the app will update the complete messages back to the gateway, and thus the power_value update instantaneously.

So, I think besides having the device send the message randomly we can somehow focus it to send it back to the gateway.

Personally, I have not tested on other Xiaomi BLE Mesh devices if by visiting the device using the App, the sensor reports the value back to HA but I believe they do.

Is there a way we can send the command similar to entering the device on Mi Home app and attach it to an automation? Doing so is as good as having the possibility to set the refresh interval.

**Comment by AlexxIT** [comment]
This integration support `homeassistant.update_entity` service. But it will work only for powered devices.
https://www.home-assistant.io/docs/scripts/service-calls/#homeassistant-services
