### ISSUE TITLE
Add support PTX Mesh Triple Wall Switch

### ISSUE THREAD

**Issue by oimag** [AlexxIT/XiaomiGateway3#993]
Could you please add this new mesh device to next version? Thanks.

**Brand**: PTX
**Name**: Mesh Triple Wall Switch
**Model**: 090615.switch.aksk3
**Model number**: 11356
**Entities**: channel_1, channel_2, channel_3

I added this line in "./core/converters/devices.py" and it's works well

```
}, {
    3788: ["PTX", "Mesh Triple Wall Switch", "090615.switch.meshk3"],
    **11356: ["PTX", "Mesh Triple Wall Switch", "090615.switch.aksk3"],**
    "spec": [
        Converter("channel_1", "switch", mi="2.p.1"),
        Converter("channel_2", "switch", mi="3.p.1"),
        Converter("channel_3", "switch", mi="4.p.1"),
    ],
```

**Enviroment**:
Device Xiaomi Multimode Gateway CN v1.5.4_0090
XiaomiGateway3:  v3.1.0 
Homeassistant:  2023.2.5

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.2.0
