### ISSUE TITLE
Issue with Xiaomi Wireless Button

### ISSUE THREAD

**Issue by jiangyiqi99** [AlexxIT/XiaomiGateway3#998]
This bug haven't appear until version 3.0 .
The Wireless Button won't have the information about which button did I click. The information "Button" always valued Button=1. And the Auto Script with definate button click is also invalid. Please fix this small problem.

**Comment by jiangyiqi99** [comment]
What I want to add is that the ID of this feature is "[yeelink.remote.contrl](https://home.miot-spec.com/spec/yeelink.remote.contrl):

**Comment by wanghubcc** [comment]
I also encountered the same problem

**Comment by micturkey** [comment]
Update to the master version and try again :)

**Comment by jiangyiqi99** [comment]
> Update to the master version and try again :)

Thank you for your waiting. Due to the Important Conference in China, I had some trouble to access Github. So I was sorry to delay to reply. Thank you for your help and this problem has successfully resolved. The click information is completely correct now and the auto script is triggered normally. Thanks for the help! Have a nice day!
